### ISSUE TITLE
[Proposal] Rolling back failed migrations

### ISSUE THREAD

**Issue by oceanapplications** [laravel/ideas#1004]
Currently if a migration fails, it doesn't make any additions to the migrations table.  Sometimes this leaves us with a table that can't be remove using rollback.  This is annoying as I have to hunt down the table or whatever changes were made in a database editor and delete it manually.  If I forget to manually remove one of the changes before running migrate again, it will likely fail once more as the item already exists giving out a new error.  All in all, not a very pleasant process.

My proposal would be to add a success or failed status column to the migrations table and perhaps a rollback-failed command to remove the most recent failure.

Any thoughts on this?

**Comment by michaeldyrynda** [comment]
In order for this to work, you'd need to wrap your migrations in transactions, however, I don't believe this behaviour is consistent across all the supported database drivers.

These kind of errors should only present themselves during development, which is largely why the `migrate:fresh` command exists.

**Comment by oceanapplications** [comment]
If the now optional down methods were properly implemented, would wrapping it in transactions still be necessary?

The fresh command is a great addition but sometimes there's stages in a project without a properly seeded database where losing all the data isn't optimal.

**Comment by michaeldyrynda** [comment]
You couldn't run the `down` method on a migration that failed part way through in any event as you don't know what state it's in.

In any event, it looks like migrations do run in a transaction, if the driver supports doing so. Looks like it's only Postgres and SQL Server that do that, though.

**Comment by Patryk27** [comment]
> I don't believe this behaviour is consistent across all the supported database drivers.

Certainly MySQL doesn't support transactions on DDLs.

> My proposal would be to add a success or failed status column to the migrations table and perhaps a rollback-failed command to remove the most recent failure.

That would work only with the simplest cases.

What happens when a migration creates many indexes, fails half-way through and then the `down` is called - it won't succeed, because it will start removing not yet created indexes.

**Comment by mfn** [comment]
As others commented: this can _only_ be solved by using a database which supports wrapping DDL i transactions. Everything else is bound to fail (or so much work it could be easier to switch to a better DB).

**Comment by sisve** [comment]
This feature is already implemented for the database engines that support it; postgresql and SQL Server. I believe this issue should be closed.

**Comment by oceanapplications** [comment]
> What happens when a migration creates many indexes, fails half-way through and then the down method is called? It won't succeed, because it will start to remove not yet created indexes.

Each index removal would need to be wrapped in an if statement checking if they exist first, not optimal but perhaps a dropIfExists function for indexes could be introduced? If you wanted to use rollback for failed migrations, complication of the down methods would certainly be increased in some cases but I don't think that'd be a significant problem.

Postgres and SQL Server may support transactions but as long as MySQL, which lacks this feature, is the most popular database, I believe some form of rollback on a failure would be valuable in the development process.
