### ISSUE TITLE
migrate:fresh should also drop views

### ISSUE THREAD

**Issue by rokde** [laravel/ideas#1008]
It is possible to create database table views with a migration. So it should be possible to drop all views on "freshing" up the database. Otherwise you will ran into an exception.

This would be very fine :)

**Comment by laurencei** [comment]
We discussed this at the time of the original PR.

Probably the best option here is something like `migrate:fresh --drop-views`. You can always do a PR for it and see what Taylor says

**Comment by taylorotwell** [comment]
I don't remember the exact reason for not dropping views. I'm not sure we were certain we could even do it in a cross-platform way? Anyways, if someone wants to research and it and open a PR with a suggestion I will review it.
