### ISSUE TITLE
[Proposal] Allow for Dependency Injection when defining relationships.

### ISSUE THREAD

**Issue by jonnyso** [laravel/ideas#1011]
When defining a relationship in a Model, make it possible to also pass an Interface as an argument to the relationship:

`public function user()
 {
      return $this->belongsTo(UserInterface::class);
 }`

**Comment by Patryk27** [comment]
Why would you ever create a model interface?

**Comment by Dayvisson** [comment]
@jonnyso , I get what you  mean, but I think you want to use a relationship with an abstract class instead an interface.

Let's say you want a model that have a relashionship sometimes with DogMoldel and sometimes with CatModel, and this is configured by your environment vars. This way you could have an abstract AnimalModel and bind the concrete model in the ServiceProvider.

and then implement:

`public function animal() { return $this->belongsTo(AnimalModel::class); }`

**Comment by matt-usurp** [comment]
Okay a poor example for usage. Having something that is as concrete as a relationship interchangeable through an environment variable isn't the most solid move. 

A better usage example comes from package maintainers that supply pre-made models or entities. Its a common thing in Doctrine (see the [resolve target entities configuration](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/cookbook/resolve-target-entity-listener.html)) where you can define your package entities and point them at interfaces that translate to the consumers classes. The benefit of this is that your consumer just implements the interface and it works without you having to expose a series of configuration options in your package.

**Comment by jonnyso** [comment]
Thank you for you answers. An abstract class is indeed more apropriated for my use case, I'm working on a multi tennant application that will work with different external applications.

An example:

I will have a module for working with application A, it's User Model must contain relationships neessary to interact with application A and it's unique aspects, as well as relationships to work with core functionalities that belong my application.

When I need to work with Application B, it's User Model will be essetialy different, apart from the relationships related to my application. So my Models need a UserInterface to deal with both User Models, in wich the one that will be instantiated will be defined in a Service Provider.

**Comment by taylorotwell** [comment]
No plans on implementing this right now.

**Comment by mattcroftuk** [comment]
I got around the lack of DI here by overriding the `newRelatedInstance` method in my model, and replacing `new $class` with `app($class)` worked for my use case but not sure if it would cause any other underlying issues else where.

**Comment by jonnyso** [comment]
I did something similar, no problems so far.
