### ISSUE TITLE
[Proposal] Take Mailable Abstract

### ISSUE THREAD

**Issue by mcordingley** [laravel/ideas#1012]
I just got bitten by this one with trying to write an ad-hoc mailable. `Illuminate\Mail\Mailable` appears to be intended to be inheritable, but not instantiable. To more clearly communicate this and to make the error a "compile"-time error instead of run-time, the class should be marked as being abstract.

`Mailable` also implicitly requires implementations to have the `build` method. That method requirement should be made explicit in the class as a protected abstract method: `abstract protected method build();`

**Comment by abellion** [comment]
https://github.com/laravel/framework/pull/22099
