### ISSUE TITLE
Eloquent query latest() / oldest() - use CREATED_AT constant?

### ISSUE THREAD

**Issue by Snaver** [laravel/ideas#1015]
Although as per the [documentation](https://laravel.com/docs/5.6/queries#ordering-grouping-limit-and-offset) you can pass through a field to sort by - would it be better to leverage the CREATED_AT constant?

The code looks simple enough, laravel\framework\src\Illuminate\Database\Query\Builder.php line 1432 - happy to implement this unless there's a reason it's not be done??

**Comment by mfn** [comment]
And where would you reference the constant from?

If you're eyeing with `\Illuminate\Database\Eloquent\Model::CREATED_AT` => The Builder has no dependency on the `Model` and the constant there has a different purpose.

**Comment by Snaver** [comment]
Ah bugger of course, that makes sense. Thanks for pointing that out @mfn.

I guess I can achieve what I'm after by using scopes to override the default functionality: 

```
/**
 *
 * @param \Illuminate\Database\Eloquent\Builder $query
 * @param  string  $column
 * @return \Illuminate\Database\Eloquent\Builder
 */
public function scopeLatest($query, $column = null)
{
    if (!$column) {
        $column = self::CREATED_AT;
    }

    return $query->orderBy($column, 'desc');
}

/**
 *
 * @param \Illuminate\Database\Eloquent\Builder $query
 * @param  string  $column
 * @return \Illuminate\Database\Eloquent\Builder
 */
public function scopeOldest($query, $column = null)
{
    if (!$column) {
        $column = self::CREATED_AT;
    }

    return $query->orderBy($column, 'asc');
}
```

**Comment by imbrish** [comment]
Correct me if I'm wrong, but `Illuminate\Database\Eloquent\Builder` could override these two methods of `Illuminate\Database\Query\Builder` to use columns of its stored model?

I never had a reason to change names of these columns, if I had though I'd expect the constants to be taken into consideration when building a query from a model. Thus thumbs up for a PR :)
