### ISSUE TITLE
[Proposal] Making Views Macroable

### ISSUE THREAD

**Issue by IsraelOrtuno** [laravel/ideas#1016]
I would like to know your thoughts about making the View Macroable so we colud do things like nesting values into the data array without having to check for the existence of that key:

```php 
\View::macro('seo', function ($key, $value) {
    if (! $this->offsetExists('seo')) {
        $this->with('seo', []);
    }
    $view['seo'][$key] = $value;
});

// and then
view('welcome')->seo('meta:whatever', '...');
```

I have tested it adding the Macroable trait to the view and it works pretty neat but not sure if that would affect other parts of the framework.

* The code of this example is simplified, it would be a bit more complex for accessing nested arrays.

**Comment by taylorotwell** [comment]
You might find `Responsable` objects a good fit for your use case. Your toResponse method could return your view and I would pass a presenter to your view to work with your data in a way that suits your needs.
