### ISSUE TITLE
loaded relations and serialisation conflict

### ISSUE THREAD

**Issue by aleemb** [laravel/ideas#1018]
If I have an accessor that calls something like `return ucfirst($post->authors->name)` then the `authors` relationship is considered loaded.

This means calling `toJson` on the model will include that relationship. Even though that relationship is not in the `$with` class property. This is undesirable since including the `authors` collection in their entirety is not what the user intended.

In the interim please also consider exposing a `getWith()` method that returns the value of `$with` property to allow users to handle this manually. This would help with more fine-grained control over data serialisation.

**Comment by aleemb** [comment]
```
Class Post extends Model {
    protected $with = [];

    protected $appends = ['name'];

    function authors() {
        return $this->belongsToMany('Author');
    }

    function getNameAttribute() {
        return $this->first_name . ' ' . $this->last_name;
    }
}

$foo = Foo::find(1);

// includes authors which is unexpected
// if $appends is set to [] then authors is not included
$foo->toJson();
```

**Comment by aleemb** [comment]
To further add to this discussion, `getEagerLoads()` doesn't work on paginated items, so can't call `$posts->paginate()`

**Comment by taylorotwell** [comment]
`with` doesn't really have anything to do with serialization. I think you would be served well by using Eloquent Resources to have better control over your serialization.
