### ISSUE TITLE
Support for PHP-PM

### ISSUE THREAD

**Issue by duxet** [laravel/ideas#102]
https://github.com/php-pm/php-pm is a young, but pretty decent way to run php apps - it's not only fast, but also easy to run, just like `artisan serve`.

The problem is that at the moment all session and auth data is stored globally, not per request. So to get it fully working without any framework structure changes, the state of these modules would have to be reset after every request.

It could be useful for testing too, to make them faster by skipping unnecessary bootstrapping after every test.

**Comment by barryvdh** [comment]
Is I understand, you could write a Terminable middleware that resets those things right? Could we create a middleware for PHP-PM?

**Comment by duxet** [comment]
I haven't checked session stuff yet, but to get auth working now, the only way could be creating new AuthManager, as there is no method to reset the state of guard.

**Comment by franzliedke** [comment]
Have you seen https://github.com/php-pm/php-pm-httpkernel? That's specifically for Symfony & Laravel, and it already jumps through a few hoops to e.g. re-initialize the session after every request.

If anything needs to be improved, that would be the place to do so...

/cc @marcj

**Comment by duxet** [comment]
Yes, i have tried it, but this package only passes request and response
between Laravel and React HTTP server.

**Comment by franzliedke** [comment]
In any case, I still suggest sending improvements there.

You might draw some inspirations from the special solutions they built for Symfony apps:
- https://github.com/php-pm/php-pm-httpkernel/blob/09fb0ae741f29761e129becc1971790c6cf1fe6e/Bootstraps/Symfony.php#L61-L84
- https://github.com/php-pm/php-pm-httpkernel/blob/09fb0ae741f29761e129becc1971790c6cf1fe6e/Bootstraps/Symfony.php#L105-L197

**Comment by duxet** [comment]
Right, it's possible to make it work with complete recreating auth and session services in bridge package , but i think it would be way better to make SessionStore directly connected to Request object, instead of making it a singleton - that just doesn't make sense for me.

**Comment by franzliedke** [comment]
@duxet That sounds sensible. :)

**Comment by taylorotwell** [comment]
If anyone wants to work on it: go for it.

Personally it is not *that* interesting to me overall because A) the performance benefit is only drastic if your framework bootstrap is slower than your application logic. This isn't usually going to be the case considering your application will be making database queries, etc.

**Comment by sisve** [comment]
You're giving mixed signals here. You can't both say that someone can work on it, and then close the issue. It's highly unclear what's going on here.

**Comment by halaei** [comment]
I think the performance boost will depend on the case and it can be more than just bootstrap time. Reusing open connections to remote servers matter as well.
I have seen the benefit of switching from short-living fpm processes to long-living cli daemons in practice. It may be case dependent, but when it matters, it can matter a lot.

**Comment by pdbreen** [comment]
In an API situation, where Redis caching can be used, I'm seeing about 33ms bootstrap vs 15ms of actual work.  The throttling middleware also had a large overhead so that was also removed for these type of routes.  Granted, probably not the best use of Laravel and I should setup an nginx proxy cache, but the app in its entirety does benefit from what Laravel offers and for now, keeping the API requests on the same code/stack has productivity advantages.  

![bootstrap](https://user-images.githubusercontent.com/1670907/37369706-4356645c-26e0-11e8-9e69-c906bd5cd3b8.png)

**Comment by marcj** [comment]
> A) the performance benefit is only drastic if your framework bootstrap is slower than your application logic

That is unfortunately not correct. Although, most of the time a bootstrap of a feature-rich framework is a big factor of the overall executing time, there're a lot of other factors involved here that can end up being a bigger factor than your actual framework bootstrap.

To name a few other than the overall framework bootstrap that affect performance and can be optimised by PHP-PM.

1. Loading PHP files and compile it (optimised by opcache, but even better by PHP-PM)
2. Connecting to various endpoints (databases for example, DNS resolution)
3. Reading and interpreting caches (for ORMs for example, compiled templates)
4. Creating object all the time (like listener, services, controllers)
5. Instantiating common objects used for every request (like mapping classes, settings from the database, etc.)

> This isn't usually going to be the case considering your application will be making database queries, etc.

My database queries are usually way faster (in the range of ~1ms) than the bootstrap of the framework (> 20ms).
