### ISSUE TITLE
Better soft delete uniqueness validation

### ISSUE THREAD

**Issue by rogervila** [laravel/ideas#1022]
Hello,

Validating unique items when using soft deletes looks a bit complicated

```php
$validation = [];

if ($this->method() == 'POST') {
    $validation['serial'] = 'unique:products,serial,NULL,id,deleted_at,NULL|required|string';
}

return $validation;
```

Of course, "unique", like "exists" [should not be responsable of checking soft deletes records](https://github.com/laravel/internals/issues/291), but there could be a filter option for it.

Example:

```php
$validation = [];

if ($this->method() == 'POST') {
    $validation['serial'] = 'unique:products,serial|required|string|softdeletes';
}

return $validation;
```

**Comment by rogervila** [comment]
A proposal from @sisve

`'unique:App\Models\User,email,scopes:trashed,otherscope'`

**Comment by sisve** [comment]
A clarification;

1. It makes sense to support all scopes, and not just one in particular (the softdeletable scope).
2. Scopes are attached to models, not tables. We would need model information to resolve them properly.

Thus we need to specify both the model and the scopes in the validation rule.

**Comment by kamui545** [comment]
Why don't you use `Rule::unique()`?

```php
Rule::unique('table')->where(function (Builder $query) {
    $query->whereNull('deleted_at');
    // apply other scopes...
});
```

**Comment by taylorotwell** [comment]
See above. Can use Rule::unique
