### ISSUE TITLE
[Proposal] Add Schedulable Trait and additional Schedule method

### ISSUE THREAD

**Issue by davidpiesse** [laravel/ideas#1024]
Having written a Trait to allow Model defined schedules ([article here](https://medium.com/@piesse/laravel-user-defined-scheduling-%EF%B8%8F-9775e861a034)) I still have to use the following code in Kernel.php (where I have already setup areDue() and runSchedule())
```php
    protected function schedule(Schedule $schedule)
    {
        $schedule->call(function () {
            Checkin::filter->areDue->each->runSchedule();
        })->everyMinute();
    }
```
Basic version looks like this (no higher order functions)
```php
    Checkin::all()->each(function($checkin){
        if($checkin->isDue()){
            dispatch(new SendCheckinEmail($checkin));
        }
    });
```
If a model/class has a Schedulable trait (or some better name) then it has a customisable schedule that might be *every ten mins* or *the first Wednesday of each Quarter at 12:35pm*.

Schedule calls would now be
```php
    protected function schedule(Schedule $schedule)
    {
        $schedule->callClass(Checkin::class);
    }
```
This would create a new Schedule event class, that is registered and called every minute.
Within the event it would call ```areDue()``` which returns the collection that need running now.

**Use case**
A user defines the schedule for sending an email (Think Basecamp Check In's). This would allow you to add a trait to your model ```use Schedulable;```, add one ```$schedule->callClass(Checkin::class);``` and that is it.

Two new files (Trait and Scheduling Event), one new method added to Scheduler

What do you think & what should these things be named (hardest part)?

David 🚀

**Comment by neelkanthk** [comment]
@davidpiesse 

I have developed a package for adding scheduling feature in models.

Package repository: https://github.com/neelkanthk/laravel-schedulable
