### ISSUE TITLE
Get rid of Arr::random() throwing an InvalidArgumentException.

### ISSUE THREAD

**Issue by BrandonSurowiec** [laravel/ideas#1035]
This was added way back in 5.4 to prevent passing in a number greater than the array had.

```php
public static function random($array, $amount = 1)
{
        if ($amount > ($count = count($array))) {
            throw new InvalidArgumentException("You requested {$amount} items, but there are only {$count} items in the array.");
        }
    
        // ...

}
```
<https://github.com/laravel/framework/commit/3cebb0541513debbcddb579aa2b2bc730d436c4c#diff-3827e5712dc6ff2e21499fcd308a18a1>

Would be nice to simply adjust the amount with `$amount = min($amount, count($array));` instead of erroring the whole page if there aren't as many items. Thoughts?

**Comment by sisve** [comment]
Why? Why should we support asking Arr:random for 10 items, and only get 5 back?

**Comment by BrandonSurowiec** [comment]
Why not? Is there a use case for wanting an error to be thrown if all 10 of the random items aren't there?

PHP's native `array_rand` method throws a warning and fails, but it could be smoothed over to operate like `take(10)`, which would give up to 10 items.

It would be friendlier for newer Laravel developers and allow for code like this to not error `Model::latest()->take(50)->get()->random(10)`. 

I know the above can be written better, like `Model::latest()->take(50)->get()->random()->take()` or `Model::inRandomOrder()->take(10)`, but that's the point. Seems unnecessary to penalize for code snippet #1.

**Comment by vlakoff** [comment]
On the contrary, I think your code above (`Model::latest()->take(50)->get()->random(10)`) can be quite dangerous, as the developer would then just assume there are 10 items. Whereas there could be less items "silently", and introducing bugs later in the code.

If there are possibly less available items than the requested number, I think it should be explicitly stated in the code:

    $latest = Model::latest()->take(50)->get();
    $results = $results->random(min($latest->count(), 10));

**Comment by BrandonSurowiec** [comment]
You're right. The problem I'm trying to point out is that it isn't clear that one would have to explicitly pass in the lesser count. Especially, a newer developer who doesn't watch the PRs or read the changelog since they're just getting acquainted. Reading the documentation for those methods makes no mention of the lesser count rule.

It *could* be added to the documentation, but I think it would be better if we encapsulate the lesser count within the `random()` method to remove the implicit.

The other common gotcha is when working with a collection, it's easy to think that `->random()->take(10)` can be shortened to `->random(10)`.

If the developer needs to enforce exactly 10 items, I think it's more obvious to make a logical check for that before randomizing. 

Thank you for your input!

**Comment by vlakoff** [comment]
Hence the exception, I think it's better to warn than to silently gives an unexpectedly altered result. Per principle of least astonishment, this explicit error is also consistent with the design choice of PHP's `array_rand()`.

**Comment by BrandonSurowiec** [comment]
That's the main question. Does it make sense to throw an exception vs. return the results that we do have? To me if feels clunky to return in exception in this case.  An exception isn't thrown with `->take(10)` if there are only 5 items in the collection. The 5 items are returned.

At the very least the documentation should be updated. `take()` and `random()` are advertised similarly. `random()` also advertises that it always returns a collection of items when passing in the number of items to receive.

> **random()**
> <https://laravel.com/docs/5.6/collections#method-random>
> You may optionally pass an integer to random to specify how many items you would like to randomly retrieve. *A collection of items is always returned* when explicitly passing the number of items you wish to receive:


> **take()**
> https://laravel.com/docs/5.6/collections#method-take
> The take method returns a new collection with the specified number of items:

**Comment by vlakoff** [comment]
`take()` calls `slice()` underneath, which indeed can return partial slices without warning (think of it like `substr()` and similar, in PHP, JavaScript, etc.).

This `take()`'s errorless behavior is also consistent with database's `take()` (which is in fact `limit()`).

So, `random()` and `take()`'s behavior may seem logical, when looking at them separately. But when looking at them together, there may be an inconsistency indeed.

<br> If it were up to me, I would throw an exception too in Collection's `take()`, and I would ditch database's `skip()` and `take()` in favor of the conventional `offset()` and `limit()` ;)

But for the situation here, I suppose the best we could do is to add notes in the documentation, to explicitly state the behavior when there is less available items than requested.
