### ISSUE TITLE
Change updated_at while updating eloquent model.

### ISSUE THREAD

**Issue by Fox4Iit** [laravel/ideas#1036]
Example:
$user->logs() = $someLogs;
$user->save();
When updated, the updated_at column of $user, doesn't get affected!.

**Comment by staudenmeir** [comment]
I assume `logs` is a relationship?

A model is only considered updated when its own attributes change, related models don't count.

Also, `$user->save()` doesn't even save the logs to the database. You have to use the `push()` method.
[And `$user->logs =` instead of `$user->logs() =`]
