### ISSUE TITLE
Easier mocking of cache and other magic facades

### ISSUE THREAD

**Issue by tflori** [laravel/ideas#1041]
Today I tried to refactor a test to use mock expectations rather than checks for specific data in the cache. That led me to a problem: when calling `Cache::shouldReceive()` it creates a mock for `$app['cache']`. The `'cache'` instance is just the `CacheManager` and when I now call `Cache::makePartial()` only the `CacheManager` is partial. `Cache::driver()` is returing a not mockable class (I can't overwrite the protected property `->stores`), `Cache::get()` is defering to `CacheManager->get()` what then leads to an error message `Cache store [key] does not exist`.

It's really frustrating to define every single call when you want to use expectations. Even more frustrating it is to debug why these errors occur.

The easiest, most understandable and fastest approach for me would be to use `$app['cache']` only for the default cache driver and `$app['cache.manager']` for the `CacheManager`, remove the magic `__call()` from `CacheManager` and then we can easly mock.

TBH: I'm using laravel at work, I have not choosen it. It frustrates me more from day to day. To much rocket sience for easy understandable code. For example this `CacheManager` the most people will have only one cache driver in use and when they need more it's understandable that they need `$app['cache.manager']` to get different caches. They will understand why..

Of course I could overwrite it more difficult in my tests:
```php
<?php

class SomeTest extends TestCase
{
    /** @var TaggableStore|Mock */
    protected $cacheMock;

    public function setUp()
    {
        $this->cacheMock = m::mock(app('cache.store'));
        Cache::shouldReceive('store')->andReturn($this->cacheMock);
    }
}

**Comment by tflori** [comment]
I'm not sure that this method is working - when I call `Cache::get()` it will yell again that there is no get call defined. And when I add `Cache::makePartial` it will pass `Cache::get()` to `CacheManager::get()` again :disappointed:

**Comment by sisve** [comment]
Have you considered staying away from mocking?

    Cache::swap(new ArrayStore());

**Comment by tflori** [comment]
You ask if I have considered to empty the storage every time but what you mean is to to test afterwards if somethig got put into it. That is called blackbox testing and that's nothing you want to do in test driven development.

`Cache::shouldHaveReceived('put')->with('key', 'value', 1440)` has a huge difference to `self::expectSame('value', Cache::get('key'))`. But the first one is only possible with partial mocks and partial mocks don't work nicely with protected methods and a magic `__call()` method.

As said it's useless to put the managers as facade in front of the storage - the people with multiple storages will understand that they need a specific storage. Cache is only one example. The real problem is that the manager is bypassing the dependency container and you are not able to provide a mock for a storage that is used by the manager.

So another solution would be that the manager stores instances in `$app->instance('cache.'.$name, $storage)` and using them in `Cache::storage()` with `$app['cache.'.$name]` if you want to stick with the managers in front of the storage.

**Comment by deleugpn** [comment]
I don't know what kind of TDD you're mentioning, but I love the fact that I can TDD with `Cache::fake()` or `Queue::fake()`. If by black box you mean that you want an e2e test on your application, Laravel test suit isn't for that and you shouldn't even be mocking/swapping in that case.

**Comment by tflori** [comment]
That must be one of the great advantages of open source software...

I don't want blackbox tests. To check after execution that a variable is stored in cache is a blackbox test. I want to have whitebox tests but I can't.

I still don't have a solution (except overwriting the instances myself), no useful comments and my request got closed from a third person without any comment.

**Comment by deleugpn** [comment]
You're likely to find that the whitebox test that you want is usually tied to the implementation and often needs refactoring if you refactor your code as well. Twitter blog has a good article on the matter: https://blog.twitter.com/engineering/en_us/topics/insights/2017/the-testing-renaissance.html

Think of your whitebox test as an expensive syntax checker that you're writing yourself. If instead of `Cache::put`, you someday decide to use `Cache::remember` for practicality, your tests will break even though your code is still achieving the same result. TDDing with Laravel Feature Test suite is extremely satisfying and offers a lot of room for refactoring.

**Comment by tflori** [comment]
Is this now a discussion if whitebox tests are useful? I don't want to start this discussion.

But one thing: when you change what your code is doing, you change your test as well. I don't know what is the difference between `Cache::put` and `Cache::remember` but when they make different things and you change from one to the other you should at least add a test that your code now behaves different. And TBH: `remember` sounds like a specialty from your cache implementation and I would avoid using special methods in favor of being able to change the cache implementation.

Anyway if this is the way ideas are handled in laravel community I will not have to spent more time here.

**Comment by deleugpn** [comment]
I was simply giving you an overview of whys and hows of the Laravel built-in test suite. I'm sorry if that didn't please you.
If you want to stick with that approach, I remember reading a blog post about partially mocking Laravel Facades. You should be able to Google it using the terms Facades, Partial Mock and Spatie.
