### ISSUE TITLE
Multiple 'cc' and 'bcc' email addresses in MailMessage class

### ISSUE THREAD

**Issue by mspiderv** [laravel/ideas#1046]
Currently (Laravel 5.6.0) it is only possible to define zero or one 'cc' or 'bcc' email address in `Illuminate\Notifications\Messages\MailMessage` class. I would like to define more than one 'bcc' email addresses.

When I call `cc` or `bcc` methods on `MailMessage` multiple times, it will override the previous email address, because `cc` method looks like this:
```
public function cc($address, $name = null)
{
    $this->cc = [$address, $name];
    return $this;
}
```

**Comment by M165437** [comment]
Are you sure that a notification mail is the way to go? Did you look at the normal "mailable" class which allows multiple to, cc and bcc receipients? https://laravel.com/docs/master/mail#sending-mail

**Comment by taylorotwell** [comment]
Return a mailable from your notification toMail method.

**Comment by taylorotwell** [comment]
Return a mailable from your notification toMail method.
