### ISSUE TITLE
UnauthorizedException - candidate for cleanup?

### ISSUE THREAD

**Issue by amadeann** [laravel/ideas#1047]
I noticed that `Illuminate/Validation/UnauthorizedException.php` is used only in one place in the framework; in `Illuminate/Validation/ValidatesWhenResolvedTrait.php`, in `failedAuthorization` method. 

However, this method is overwritten in `Illuminate/Foundation/Http/FormRequest.php` class, which is the only place where `ValidatesWhenResolvedTrait` is used. Overwritten method throws `AuthorizationException`, which makes the `UnauthorizedException` redundant.

Would it be a good candidate for cleanup? I think the `UnauthorizedException` could be removed altogether. In the trait's `failedAuthorization` method, we could either throw the `AuthorizationException` or just remove this method as well.

**Comment by taylorotwell** [comment]
You can make a PR for this if you want.
