### ISSUE TITLE
Envoy arguments

### ISSUE THREAD

**Issue by isneezy** [laravel/ideas#1049]
I'm working on a laravel project where we use docker-compose for local development environment and deployments, and we are trying to shorten the commands that we use to install composer dependencies and make artisan calls with laravel/envoy. Here is an example of what we have done so far:
```
@task('artisan-migrate')
   docker-compose exec -u 1000 web php artisan migrate
@endtask

@task('artisan')
   docker-compose exec -u 1000 web php artisan {{$command}}
@endtask

@task('composer-install')
   docker-compose exec -u 1000 web composer require {{$package}}
@endtask
```

And use as follow `envoy run artisan-migrate` and `envoy run artisan --command="migrate --seed"`

And now our `Envoy.blade.php` file is getting to big because we have to put each usage as a task and we have to remember all those names.

I want to know if it is possible, how can we take a command like this `envoy run composer install xxx/yyy` or `envoy run artisan migrate --seed` and define only a task named `composer` and then pass the `install xxx/yyy` and `migrate --seed` part respectively?

If there is no way i'm willing to contribute if it is an acceptable feature and useful to others.

Sorry about my English

**Comment by taylorotwell** [comment]
What you are doing may work a little better as something like a Bash alias or function.
