### ISSUE TITLE
Equivilent of Symfony/Twig preload()/prefetch() etc...

### ISSUE THREAD

**Issue by votemike** [laravel/ideas#1052]
Twig has magic methods to allow you to add preload/prefetch/preconnect Link headers: 
https://symfony.com/blog/new-in-symfony-3-3-asset-preloading-with-http-2-push
https://symfony.com/blog/new-in-symfony-3-3-weblink-component

It would be great if Blade could also have this feature.

**Comment by taylorotwell** [comment]
I'll admit I'm not very familiar with this type of thing but if it's fairly simple to implement feel free to make a PR.

**Comment by tomschlick** [comment]
Alternatively, @JacobBennett and myself each have packages that handle this sort of thing in various ways.

https://github.com/tomschlick/laravel-http2-server-push

https://github.com/JacobBennett/laravel-HTTP2ServerPush

**Comment by JacobBennett** [comment]
Thanks for the shout out Tom!
