### ISSUE TITLE
Storage::putFileAs() - rename file if exists

### ISSUE THREAD

**Issue by CDNRocket** [laravel/ideas#1053]
Currently, if you choose a custom name, Storage::putFileAs(), will replace the existing file if already exist with the same name.

Should be nice to add extra args to this method for choose if append something unique to the base file name.

**Comment by tomschlick** [comment]
IMO, its a bad idea to change the name of a file magically. Instead you should just wrap it in a file exists check.

That method works as I would think it should. The word "put" implies it will either create/update a file just like the "PUT" HTTP method.
