### ISSUE TITLE
[Proposal] Introduce item getter & setter to base collections

### ISSUE THREAD

**Issue by ollieread** [laravel/ideas#1054]
I've recently come into a situation where I wanted a particular class to behave like a collection. The data in the 'collection' isn't stored in an array, and is grabbed from another source.

My initial thought was to simply extend the `Illuminate\Support\Collection` class, but that would mean overriding every method that references `$this->items`.

This whole thing could be simplified by introducing the following method;

    public function getItems(): array
    {
        return $this->items;
    }

Then we'd just need to replace all instances of `$this->items` with `$this->getItems()`.

I can't find anything within the class that would cause an issue, and since `$items` is protected, it shouldn't cause an issue for any implementations out there.

It may even be worth going as far as adding a setter, like so;

    public function setItems(array $items)
    {
        $this->items = $items;
        return $this;
    }

Then anyone with a custom class that needs to behave like a collection, can override these two methods to deal with the reading and write of the data.

**Comment by Patryk27** [comment]
The `getItems()` method you're talking about already exists - it's named `all()`; the setter also exists - it's the constructor ;-)

What you're talking about shouldn't be solved by inheritance (in most cases inheritance is **not** the answer) - you should go with traits or composition.

**Comment by ollieread** [comment]
@Patryk27 I'm not following. If I wanted a class to act like a collection, I should define traits and methods, duplicating all of the code from a collection?

My proposal was to have the Collections class honour its own API. I'm aware that `getItems()` exists, but it's not used internally.

**Comment by ollieread** [comment]
@martinbean The repository pattern isn't quite what I was looking for. Repositories are designed to handle data retrieval and persistence, and would not work as a collection.

My particular use case was that I wanted a collection of something, but wanted specific functionality. We're talking about a less generic collection, that can still be treated as a collection, as it extends the base collection class. Much the same way that we have an Eloquent specific collection. In my example, the data wouldn't be stored in a simple array.

The whole purpose of this proposal was to have `Illuminate\Support\Collection` honour its own API.

**Comment by martinbean** [comment]
> Repositories are designed to handle data retrieval and persistence, and would not work as a collection.

@ollieread From _Patterns of Enterprise Application Architecture_, where the Repository pattern is introduced:

> Mediates between the domain and data mapping layers **using a collection-like interface** for accessing domain objects.

However, I’m not sure what it is you’re trying to do that couldn’t be done using a custom collection class? If you need to add your own methods, you can return a customer collection class instance from an Eloquent model by overriding the `newCollection()` method:

```php
class Foo extends Model
{
    public function newCollection(array $models = [])
    {
        return new CustomCollection($models);
    }
}
```

**Comment by ollieread** [comment]
@martinbean But if the data is to be stored in something other than a single array, ie, the `items` property, I'll need to override and redefined the majority of the methods in the original class, essentially duplicating almost 2k lines of code.

**Comment by Patryk27** [comment]
@ollieread so you cannot grab all the data at the beginning - you'd rather want something like a lazy-collection?

**Comment by martinbean** [comment]
@ollieread I’m still struggling to understand your use case. You seem to be detailing a solution without explaining what your actual use case is.

**Comment by ollieread** [comment]
@Patryk27 yes.

@martinbean I feel that the use case is somewhat irrelevant. The collection should honour its own API. All references it `$this->items` replaced with, say `all()`. My particular use case involved a sort of lazy collection, like suggested above.

**Comment by martinbean** [comment]
@ollieread I think if you’re wanting something as ubiquitous as the Collection class in the framework changing, a good use case is going to help your argument.

If you feel any and all references to `$this->items` should be replaced with a call to the Collection’s own `all()` method—and that would assist you in your applications and implementations—then that can easily be achieved by opening a Pull Request in the [laravel/framework](/laravel/framework) repository. From there, it can only be merged or rejected with a reason.

**Comment by ollieread** [comment]
I'm going to pick this back up @martinbean.

The introduction of the lazy collection proves my point 10 fold!
