### ISSUE TITLE
RE: An open letter to: Taylor, or whomever is closing ideas

### ISSUE THREAD

**Issue by garygreen** [laravel/ideas#1056]
Ref #1051 which was locked before any contributors could even add their thoughts.

> The closes are mainly B,C,D. If they are A I usually indicated it in the issue. I don't plan to type a formal response for each issue close. If it makes people feel better I can copy and paste the exact same wording for every close but I'm not sure if that is much better.

This isn't very helpful reply, Taylor. What contributors are after is a bit more feedback other than just simply closing an issue without any formal response. To suggest copying and pasting the same response "to make people feel better" is almost a passive aggressive remark and shows lack of empathy for those who have spent time contributing PRs or ideas.

Also, what is the process for when issues are closed and contributors wish for them to have a more formal response or reconsideration? You mention the closes are a mixture of stale, re-open if interested, fixed already and not considered likely for the framework - all of these are entirely different responses and simply closing an issue does not convey which it is. Should the ideas or issues be re-opened again, until they warrant a proper response?

In all honesty, I haven't seen any open source project run like this. If you contribute to Symphony, you receive a formal and proper response. This isn't difficult or unreasonable thing to ask for.

**Comment by garygreen** [comment]
Going to close this and hope the feedback will be taken on board. 👍

**Comment by taylorotwell** [comment]
Sorry some people are feeling this way. I just needed to start getting through 700+ issues and needed to it in an efficient manner. I'll try to leave responses when I have time from now on.

Regarding issues that are closed and you want more formal consideration, email me. My email address is available on my profile when signed into GitHub.

Thanks!
