### ISSUE TITLE
[5.7] Request ArrayAccess with dot notation

### ISSUE THREAD

**Issue by TitasGailius** [laravel/ideas#1057]
Hello,

I've already made a PR to improve Request object by enabling dot notation support when used with ArrayAccess which has been rejected. https://github.com/laravel/framework/pull/23456

Does anyone have any idea what Taylor meant there? I investigated it a couple of times myself but I couldn't reproduce that breaking change.
I'd really love to make correct adjustments but I can't figure out what's wrong with the previous one.

Thanks in advance

**Comment by drbyte** [comment]
Note: he rarely looks back at closed PRs, unless you draw his attention to it. 
To do that, click on his github profile and use his email address to send him a message.
Alternatively one can re-submit the whole PR as that will cause it to come into view again.

**Comment by AuditeMarlow** [comment]
It is not so much about being able to reproduce the breaking change, your PR changes the behaviour of the __get method. This is bad practice, as this may lead to unexpected problems later on. Instead, what you should've done is append behaviour, rather than replacing it. I personally wouldn't append behaviour in the __get method myself here, though, as this is already widely used and will still be prone to error by introducing new behaviour in the method.

**Comment by TitasGailius** [comment]
@AuditeMarlow What you basically said is that we could never have dot notation support because it simply "changes the behaviour"? This doesn't seem right...

**Comment by sisve** [comment]
The closing comment on the [original pr](https://github.com/laravel/framework/pull/23456) was about a breaking change.

> You have a big breaking change in the __get method by using Arr::get... all null inputs will now use the "default" closure and fallback to the route variables. That was not the prior behavior.

I believe that "inputs" in this case is request data, not the $key parameter.

The old code checked array_key_exists in $this->all() and returned that value. It would only check for route values if the key wasn't found in $this->all(). This means that it could return a null value without ever checking the route values.

    if (array_key_exists($key, $this->all())) {
        return data_get($this->all(), $key);
    }
    
    return $this->route($key);

The new code calls Arr::get(...) which calls the default closure (and uses the route value) even when there's an existing null-value in $this->all(). This is the breaking change you need to either prove doesn't exist, or prove that you havn't changed.

So, add a test with request inputs with null values and show that the old behavior is still there.

**Comment by vlakoff** [comment]
Somehow related: https://github.com/laravel/framework/issues/23243. These `null` values are really painful to handle :\

**Comment by crynobone** [comment]
@TitasGailius while the PR maybe rejected, I do feel that the new tests is quite useful. It at less test the usage of the getter for `Illuminate\Http\Request`.
