### ISSUE TITLE
Allow sending only text/plain via Mailables

### ISSUE THREAD

**Issue by rask** [laravel/ideas#1058]
From what I understand Mailables require a HTML view in order to work. If you define only a text view as such

```php
public function build()
{
    return $this->text('view.name');
}
```

Then the mailable fails with an error saying `invalid view []` or similar. After adding a `->view('view.name')` to `build()` the Mailable works OK.

Or is this intended and I'm asking for trouble here? Why can't I just send a text/plain email with a Mailable? I would prefer to have light emails for a light application and setting up HTML emails is a chore and maintaining those is tedious.

**Comment by drbyte** [comment]
You must have an error somewhere.

This works fine to send text-only emails for me:
```php
    public function build()
    {
        return $this->text('emails.text_message_content')
            ->replyTo($this->sender->email, $this->sender->name)
            ->subject($this->subject);
    }
```

And the view:
```php
@extends('emails.layout_textonly')

{!! $message_text !!}
```

**Comment by rask** [comment]
Strange. When I'm testing rendering a mailable inside a `TestCase` class as such:

```php
$mailable = new Mymailable();

$content = $mailable->render();
```

with a mailable with no `->view()` I either receive an error stating `[]` is an invalid view or then the `$content` variable contains the view name similar to `view.path.and.name`. After I add `->view()` then it works as it should.

I need to dig a bit deeper and see if this really is some user error on my end or if this needs a real fix.

**Comment by rask** [comment]
OK going to paste my current setup (with dummy content) for brevity:

#### MyMailable

```php
public function setSomeValue($string)
{
    $this->some_value = $string;
}

public function build()
{
    $some_value = (string) $this->some_value;

    return $this->subject('Hello World')
        ->text('mail.hello-world')
        ->with('value', $some_value);
}
```

#### resources/views/mail/hello-world.blade.php

```text
Hello World, {{ $value }}!

This is an email from
{{ env('APP_NAME') }}
```

#### MyMailableTest

```php
$m = new MyMailable();
$m->setSomeValue('foobar');

$m_content = $m->render();

$this->assertContains('foobar', $m_content);
```

---

With this setup when I run

    vendor/bin/phpunit

I receive 

    InvalidArgumentException: View [] not found

But when I alter `MyMailable::build()` to include the `view()` call as follows

```php
public function build()
{
    $some_value = (string) $this->some_value;

    return $this->subject('Hello World')
        ->view('mail.hello-world')
        ->text('mail.hello-world')
        ->with('value', $some_value);
}
```

Then everything works as expected and the assertion succeeds in my test case.

**Comment by cryode** [comment]
@rask You're not going crazy! The `Mailer` class appears to handle `render()` and `send()` differently, the latter of which has proper checks to skip the HTML view if it isn't defined. `render()` doesn't:

```php
public function render($view, array $data = [])
{
    // First we need to parse the view, which could either be a string or an array
    // containing both an HTML and plain text versions of the view which should
    // be used when sending an e-mail. We will extract both of them out here.
    list($view, $plain, $raw) = $this->parseView($view);

    $data['message'] = $this->createMessage();

    return $this->renderView($view, $data);
}
```

In your case, `$view` is null, and `$plain` has your plain-text view name. It simply gets ignored.

Adding in this simple fallback would get your test passing:

```php
list($view, $plain, $raw) = $this->parseView($view);
$view = $view ?: $plain;
```

I'll submit a PR fix for this momentarily. Appreciate the report! 👍

**Comment by rask** [comment]
Neat, thanks and no problem! I'll be following update notes. :)

**Comment by AkenRoberts** [comment]
@rask Someone was finally able to submit a PR and this should be fixed in Laravel 5.6.18+.

**Comment by rask** [comment]
@AkenRoberts Alrighty, good to hear!

**Comment by mbaierl** [comment]
Thanks @AkenRoberts  - learned something new :-)
Weird thing is - I had
```"laravel/framework": "5.6.*",```
which did not update to 5.6.21, but
```"laravel/framework": "5.6.21",```
did....

**Comment by acorncom** [comment]
Looks like this can be closed now

**Comment by rask** [comment]
I guess so. Thanks everyone!
