### ISSUE TITLE
Application::environment() contract and function could use improvement, causes IDEs to complain

### ISSUE THREAD

**Issue by phillip-elm** [laravel/ideas#1060]
The `Application::environment()` function makes use of some questionable code that makes IDEs like PHPStorm complain. It wouldn't take much effort to maintain the same functionality, but make the contract more consistent.

The current contract is here:

**src/Illuminate/Contracts/Foundation/Application.php**
```
/**
 * Get or check the current application environment.
 *
 * @return string
 */
public function environment();
```

The current implementation is here:

**src/Illuminate/Foundation/Application.php**
```
/**
 * Get or check the current application environment.
 *
 * @return string|bool
 */
public function environment()
{
    if (func_num_args() > 0) {
        $patterns = is_array(func_get_arg(0)) ? func_get_arg(0) : func_get_args();
        foreach ($patterns as $pattern) {
            if (Str::is($pattern, $this['env'])) {
                return true;
            }
        }
        return false;
    }
    return $this['env'];
}
```

This doesn't seem very clear or indicative of the possible uses of this function, which are:

- `$app->environment() === 'local'`
- `$app->environment('local')`
- `$app->environment(['local', 'foo', 'bar'])` (wrapped in an array)
- `$app->environment('local', 'foo', 'bar')` (variadic args)

The contract has a return type of string only, the implementation also can return boolean values. Neither of them accept arguments but you see it used with arguments very frequently in code throughout a number of laravel applications and guides on the web.

PHPStorm does not like this - when I try to provide an argument, it complains that the interface doesn't allow any arguments, yet I've provided one - and that's what it should be doing.

After discussing it with a colleague, we agree that this function should be revisited in future releases to have a more consistent contract / implementation.

----

I propose something like the following:

**src/Illuminate/Contracts/Foundation/Application.php**
```
/**
 * Get or check the current application environment.
 * 
 * If a string or array of strings is provided, it will be checked against the current environment; if a match is found, true is returned. False otherwise. 
 * If no arguments are provided, this method will return the name of the current environment as a string.
 *
 * @param string|string[] $patterns,...
 *
 * @return string|bool
 */
public function environment(...$patterns);
```

**src/Illuminate/Foundation/Application.php**
```
/**
 * @inheritDoc
 */
public function environment(...$patterns)
{
    if (count($patterns) > 0) {
        $patterns = is_array($patterns[0]) ? $patterns[0] : $patterns;
        foreach ($patterns as $pattern) {
            if (Str::is($pattern, $this['env'])) {
                return true;
            }
        }
        return false;
    }
    return $this['env'];
}
```

The pros / cons of this are:

**Pros:**
- IDEs don't complain about arguments provided to this function
- The contract is clear and concise
  - You know exactly what it does by looking at it
  - Which is the intent of a contract anyway
- The contract matches the implementation
- The implementation is nearly identical to it's previous self
- All previous argument formats (no args, single string, single array, variadic args) still work

**Cons:**
- Change to a core contract; while minimal, if this change were implemented, it may require some changes in laravel applications.

**Comment by taylorotwell** [comment]
Minor changes could be made for 5.7 if you want to PR them. I will admit that attempting to constantly satisfy IDEs in a dynamic language like PHP feels like a bit of a lost cause but it's fine. :)
