### ISSUE TITLE
Add method to run all seeds (similar to migrating ALL migrations)

### ISSUE THREAD

**Issue by ajthinking** [laravel/ideas#1063]
By default all migrations in migrationsfolder are called on ```php artisan migrate```. It would be nice if the eqvivalent could be implemented for the seeds. The default DatabaseSeeder class could then be updated to something like:

```
<?php
use Illuminate\Database\Seeder;
class DatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $this->runAll();
    }
}
```

**Comment by staudenmeir** [comment]
That's not possible for databases with foreign keys. The seeders have to run in a specific order.
