### ISSUE TITLE
An easy way to use the same template in markdown email & email notifications template

### ISSUE THREAD

**Issue by alfonsobries** [laravel/ideas#1064]
The email laravel notifications has his own way to create custom templates and the mail driver also has his custom template for the markdown emails, both works great but if you want to create your custom template you need to change both.

For example in the default markdown template we have a css file to change styles and in the notifications template an array with styles.

I think the CSS file method is better but im not sure, but maybe a way to unify both templates will be  a great feature, what do you think?

**Comment by alfonsobries** [comment]
Notice that the notifications are very useful for users in your app and an email are better for for example contact forms, newsletter susbscribe notifications, etc. For now i resolve this issue by creating a temporal user that can use the notifiable trait.

Example:

`
$email = request()->input('email');
// Create a temporaly user (never save it9
$temporaly_user = new \App\Models\User(['email' => 'alfonso@vexilo.com']);
// Send some email type notification
$temporaly_user->notify(new Notification());
`

**Comment by taylorotwell** [comment]
You can return a Mailable from a notification toMail method which should allow you to unify everything.
