### ISSUE TITLE
[Question] What is Controller callAction used for?

### ISSUE THREAD

**Issue by tjallingt** [laravel/ideas#1067]
In `Illuminate\Routing\ControllerDispatcher` we can see that it checks if there is a `callAction` method defined on the controller and it will attempt to call that instead of the method itself:

```php
/* ControllerDispatcher.php */

    /**
     * Dispatch a request to a given controller and method.
     *
     * @param  \Illuminate\Routing\Route  $route
     * @param  mixed  $controller
     * @param  string  $method
     * @return mixed
     */
    public function dispatch(Route $route, $controller, $method)
    {
        $parameters = $this->resolveClassMethodDependencies(
            $route->parametersWithoutNulls(), $controller, $method
        );

        if (method_exists($controller, 'callAction')) {
            return $controller->callAction($method, $parameters);
        }

        return $controller->{$method}(...array_values($parameters));
    }
```

The base Controller class `Illuminate\Routing\Controller` implements the `callAction` method:

```php
/* Controller.php */

    /**
     * Execute an action on the controller.
     *
     * @param  string  $method
     * @param  array   $parameters
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function callAction($method, $parameters)
    {
        return call_user_func_array([$this, $method], $parameters);
    }
```

Which AFAIK results in exactly the same behaviour as the `$controller->{$method}(...array_values($parameters))` line.

I understand the argument that some people might overwrite this method to allow them to choose which method handles which action but this use-case is also easily fulfilled (I think) by using a route parameter.

Also if this is the case why does the base controller implementation implement this method, as it stands the last line is never reached (if you are not writing your base controller that without a `callAction` method that is)

**Comment by sisve** [comment]
What's your idea that you want to discuss?

> I understand the argument that some people might overwrite this method to allow them to choose which method handles which action but this use-case is also easily fulfilled (I think) by using a route parameter.

What if the logic isn't based on a route parameter, but anything else, like remote ip address, cookies, evil sheenanigans and server mood?

> Also if this is the case why does the base controller implementation implement this method, as it stands the last line is never reached (if you are not writing your base controller that without a callAction method that is)

Controllers does not have to inherit from the base controller class, thus the callAction extension point wouldn't be present.

**Comment by tjallingt** [comment]
> What's your idea that you want to discuss?

Im sorry i found this bit of code in laravel internals and since laravel/internals links to laravel/ideas i hoped this would be an okay place to ask this question...

> What if the logic isn't based on a route parameter, but anything else, like remote ip address, cookies, evil sheenanigans and server mood?

I guess this answers my question partially, it seems to be a way to add extra logic around what method is actually called. However it seems to me that it'd be better to have the controller tell the dispatcher what method to call so it can actually match the arguments of the correct method...

**Comment by sisve** [comment]
> However it seems to me that it'd be better to have the controller tell the dispatcher what method to call so it can actually match the arguments of the correct method...

This sounds wrong. I believe it is up to the dispatcher to determine which method to call; it doesn't have to be callAction.

You can write a custom dispatcher for this purpose. Keep in mind that the callAction method was introduced long before the dispatcher, so the method stays with us mostly for supporting existing code.

> [...] base controller implementation should probably not implement callAction [...]

Removing it now will break everyone that has written a dispatcher that presumes it exists.

**Comment by tjallingt** [comment]
Legacy code huh... Okay check, thank you for helping me clear this up :+1:

> This sounds wrong. I believe it is up to the dispatcher to determine which method to call; it doesn't have to be callAction.

Dont get me wrong I very much agree with this sentiment but everything going on in callAction is doing the opposite; it masks the method actually being called from the dispatcher. Potentially breaking the parameter matching/injection.

It is starting to make sense to me why this method isn't documented haha
