### ISSUE TITLE
Eloquent “Three-Way” Pivot Table

### ISSUE THREAD

**Issue by regiszanandrea** [laravel/ideas#1069]
Hi, 

I have a question that is how to make a relationship with three Models. So, I have these models: Team, User and Tournament. And a table with their ids (user_id, team_id and tournament_id). How to create the relationship in eloquent? The best answer that I found is this:

Relation Model:
```
public function user()
{
   return $this->belongsTo(User::class);
}

public function team()
{
    return $this->belongsTo(Team::class);
}

public function tournament()
{
    return $this->belongsTo(Tournament::class);
}
```
User model:
```
public function tournament()
{
    return $this->belongsToMany(Relation::class);
}
```

.
.
.

So, this is the best way? There is an alternative?

Thanks

**Comment by MatthewSH** [comment]
This doesn't seem like a proposal or feature request. It seems as though you're asking for support. You can get that on [Larachat](https://larachat.co) or on the [Laracasts forum](https://laracasts.com/discuss).

**Comment by regiszanandrea** [comment]
Ok @MatthewSH, 
Thanks.
