### ISSUE TITLE
[Proposal] Container-instantiated validation rule objects

### ISSUE THREAD

**Issue by levacic** [laravel/ideas#1079]
Right now when using custom rule objects, they need to be instantiated manually before being passed as a rule.

For example, in form requests:

```php
// Currently suggested way - lacks ability to autowire dependencies:
public function rules()
{
    return [
        'name' => [
            'required',
            new Uppercase(),
        ],
    ];
}
```

However, some rules might require external dependencies to be injected, which is where this can get ugly. With form requests, it's possible to use method injection:

```php
// Method-injection - not ideal:
public function rules(Uppercase $uppercase)
{
    return [
        'name' => [
            'required',
            $uppercase,
        ],
    ];
}
```

However, we don't find this very clean, especially when we need multiple rule objects - it gets cumbersome, and the `rules()` signature gets noisy. An alternative is to manually instantiate it from the container when needed:

```php
// Manual call to container - not ideal:
public function rules()
{
    return [
        'name' => [
            'required',
            app(Uppercase::class),
        ],
    ];
}
```

While this is slightly more maintainable, it still makes the code unnecessarily hard to read - the `app()` call doesn't add any semantic meaning to the code and represents useless boilerplate. Ideally, we could do this:

```php
// Most-readable solution - not currently possible:
public function rules()
{
    return [
        'name' => [
            'required',
            Uppercase::class,
        ],
    ];
}
```

This is, however, not currently possible. I'm not knowledgeable enough about the internals, but I _think_ that all it takes would be updating `Illuminate\Validation\ValidationRuleParser::prepareRule()` to check (just before the final `return (string) $rule;` whether the rule is a string that represents an existing FQCN - and if so, instantiate it via the container and return that. It also seems to me that this change would be unlikely to cause any BC breaks in practice, so it should be a safe improvement to make.

**Comment by sisve** [comment]
How would you customize the rule instance if you used any of these syntaxes?

The Rule class is already macroable, you could add a `Rule::uppercase($moreOptions)` if you wanted.

**Comment by martinbean** [comment]
It’s a +1 from me. I found _exactly_ the same the other day where I have a rule that validates a value based on a repository I inject in its constructor:

```php
class Currency implements Rule
{
    private $currencies;

    public function __construct(CurrencyRepository $currencies)
    {
        $this->currencies = $currencies;
    }

    public function passes($attribute, $value)
    {
        return $this->currencies->contains($value);
    }
}
```
```php
class CreateSkuRequest extends FormRequest
{
    public function rules()
    {
        return [
            'currency' => [
                app(Currency::class), // Urgh!
            ],
        ];
    }
}
```

**Comment by levacic** [comment]
@sisve That's a valid point I definitely overlooked, and I'm not quite sure what the best way would be. Thanks for pointing that out!

The most obvious solution would be something like:

```php
Uppercase::class
```

This would be consistent with the default rules but I personally don't find it very nice/readable at all.

An alternative would be an array where the first item is the rule class and the rest of them are parameters, e.g.

```php
[Uppercase::class, 'foo', 'bar'],
```

Or maybe (inspired by how ESLint is configured) an array where the first item is the rule class and the second a hashmap of customizable properties, e.g.

```php
[Uppercase::class, ['foo' => 'bar', 'baz' => 'qux']]
```

which would be better as it allows named parameters.

Both of the array options would also allow for a more straightforward implementation in `Illuminate\Validation\ValidationRuleParser::prepareRule()`, as it's easier (and non-ambiguous) to differentiate a string and an array, compared to a string representing a built-in rule vs. a string representing a FQCN.

However, I don't really find any of these solutions very clean and at this point the most readable one seems the original where the container is manually invoked. I recently learned that `resolve()` is also an alias for `app()` which I think gets the intention across more clearly, so perhaps that's okay I guess? Add chaining to that for configuration and I guess it's fine.

I haven't yet tried the macro approach so that might be a nice solution as well.

@martinbean Any thoughts on a nice alternative approach to this problem?

**Comment by martinbean** [comment]
@levacic Not really. I’m with you in that, the rules should be resolved out of the container somehow (so dependencies are also resolved) and resorted to adding `app(RuleName::class)` in my form request class, which feels yucky.

**Comment by cyrossignol** [comment]
As @sisve pointed out, `Rule` is already macroable, so we could solve this using features that the framework provides today:

```php 
class ValidationServiceProvider extends ServiceProvider 
{
    protected $rules = [
        'uppercase' => \App\Validation\Uppercase::class,
        'currency' => \App\Validation\Currency::class,
        ...
    ];

    public function boot() 
    {
        foreach ($this->rules as $rule => $handler) {
            Rule::macro($rule, function () {
                return $this->app->make($handler);
            });
        }
    }
    ...
}
```

```php
class SomeRequest extends FormRequest 
{
    public function rules() 
    {
        return [
            'name' => [ 'required', Rule::uppercase() ], 
            'currency' => [ 'required', Rule::currency() ],
        ];
    }
}
```

Should be easy enough to extend this example if we need rule macros that take an argument. If we wanted to load rulesets lazily, we could use a pattern similar to how facades work. 

```php
class ValidationServiceProvider extends ServiceProvider 
{
    public function boot() 
    {
        CustomRule::setApplication($this->app);
    }
}
```

```php
class CustomRule
{
    protected static $app;

    public static setApplication(Container $app) 
    {
        static::$app = $app;
    }

    public static function __callStatic($method) 
    {
        // or just app()->make(...) if you're feeling lazy
        return static::$app->make('App\Validation\\' . ucfirst($method));
    }
}
```

```php
public function rules() 
{
    return [ 
        'name' => [ CustomRule::uppercase(), ... ],
    ];
}
```

In both cases, the rule is still unit-testable.

**Comment by driesvints** [comment]
Closing as this was rejected, sorry.
