### ISSUE TITLE
[Proposal] Passport single use tokens

### ISSUE THREAD

**Issue by OwenMelbz** [laravel/ideas#1086]
Hi,

I'm aware you can programmatically revoke, and renew tokens, however wondering if it's within potential scope for Passport if this is something that could be built in, to be a little more "magic" ?

Effectively it is for single use api tokens, so once it has been consumed, it will return a new fresh token each time (maybe like csrf?)

You could also optionally say if you don't want it to refresh, or define excluded routes etc?

I there are a variety of ways you could return the new token, through response headers I guess would be the least intrusive?

Obviously the idea needs fleshing out, but if its a concept that might be considered useful then 👌🏼

**Comment by Meeshalk** [comment]
@OwenMelbz i think it's already there. There's a middleware which can handle exactly what you described. FreshApiToken i guess. See the passport docs, you'll find it at the end, under consuming your own API using JavaScript application.

**Comment by OwenMelbz** [comment]
oh yeah it’s there now, opened this 2 years ago 😂 so can be closed
