### ISSUE TITLE
Scheduler sendOutputTo / appendOutputTo improvements

### ISSUE THREAD

**Issue by nie7321** [laravel/ideas#1092]
My basic idea is that I'd like to be able to use the sendOutputTo / appendOutputTo [methods on the scheduler](https://laravel.com/docs/5.6/scheduling#task-output) to keep a log of my tasks, in case there's ever a question as to whether or not something ran (or ran, but failed).

At the moment, it does not decorate what it logs with timestamps, which would be extremely helpful for my use-case.

Perhaps these methods could integrate with the new Log stuff somehow, instead of just accepting a file path?

I don't know how these requests usually go, but I am not opposed to taking a stab at a PR -- I'm just not sure what the ideal API for this would be.

**Comment by akalongman** [comment]
@nie7321 could you look at PR and tell me is this feature you asking for?

**Comment by nie7321** [comment]
That's exactly what I'm asking for.

You rock 👍

**Comment by nie7321** [comment]
I am going to close this out, since I ended up doing what Taylor suggested in the PR:

https://github.com/laravel/framework/pull/23782#issuecomment-378263616

It worked out just fine.
