### ISSUE TITLE
Do not fake model events

### ISSUE THREAD

**Issue by shadoWalker89** [laravel/ideas#1100]
Hi, so when calling `Event::fake()` The model event dispatcher is changed to the fake one

https://github.com/laravel/framework/blob/d36ae2327475f5bb352f1ef62f993a7f28627880/src/Illuminate/Support/Facades/Event.php#L33

Which cause problems, when using the eloquent events to fill some table fields that are not nullable.
Tests start to fail.
Shouldn't we keep the original event dispatcher on eloquent ?

**Comment by BrandonShar** [comment]
I agree with you, but faking those events was added deliberately and I don't think they're interested in changing it. I made [this package](https://github.com/scorelabs/laravel-event-fake) to add some features to Event::fake if you're interested.

**Comment by shadoWalker89** [comment]
I made a PR to the core to add the `Event::fakeExceptModels()`
https://github.com/laravel/framework/pull/23811

This was inspired by the package of @BrandonShar

**Comment by shadoWalker89** [comment]
PR turned down by taylor

**Comment by BrandonShar** [comment]
Good point, I never pass args to Event::fake so I didn't think about it. You're welcome to PR the change if you want.
