### ISSUE TITLE
[Proposal] Add groupByRaw

### ISSUE THREAD

**Issue by lancepioch** [laravel/ideas#1112]
We already have the following raw methods:

* selectRaw
* whereRaw
* havingRaw
* orderByRaw

I'm willing to submit a PR with support.

**Comment by dabernathy89** [comment]
I think this is a great idea.

**Comment by afbora** [comment]
This's what i'm looking for! 👍

**Comment by webbello** [comment]
This will be a great help for developer

**Comment by rentalhost** [comment]
@lancepioch do you still intend to do a PR for this case?

**Comment by lancepioch** [comment]
@rentalhost yeah I'll see if I can throw out a PR for this tomorrow or next week.

**Comment by rentalhost** [comment]
@lancepioch I have implemented this feature with two tests (one for the feature itself and another to check if mixed bindings types still works as expected). Do you care if I PR?

**Comment by lancepioch** [comment]
If you already got it done, go for it 🥇
