### ISSUE TITLE
[Proposal] Permit add exceptions in Maintance Mode

### ISSUE THREAD

**Issue by cesargb** [laravel/ideas#1118]
For example permit the access to App from certain Ip's Address.

In this case perhaps can add options `except` in command `down`

`php artisan down --except="ip:10.0.0.1" --except="net:192.168.0.0/16"`

**Comment by drbyte** [comment]
If this isn't accepted, here's an alternate approach: https://github.com/spatie/laravel-littlegatekeeper

**Comment by microwavekonijn** [comment]
Why not add a new command which extends `\Illuminate\Foundation\Console\DownCommand`, then in the method `getDownFilePayload` add a new entry with a array of ip's which are allowed. Then create a new middleware which extends and replaces `\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode` and checks which ip are allowed and if not execute the parent method.

**Comment by cesargb** [comment]
This proposal has been included in Laravel 5.6.20
