### ISSUE TITLE
[Proposal] add $sortable property to Eloquent\Model

### ISSUE THREAD

**Issue by Tarasovych** [laravel/ideas#1125]
I wish I can use this atribute inside Model to set up what model fields are available to `orderBy()` while fetching data with Eloquent query.

```php
class User extends Model
{
    protected $sortable= [
        'name' //allow to call orderBy() only with 'name' parameter
    ];

    protected $sortable= []; //allow to call orderBy() with any parameter

    protected $sortable= []; //don't allow to call orderBy()
}
```

**Comment by ntzm** [comment]
By default you're allowed to sort by any column, if you want to sort based on user input, I'd recommend looking at https://github.com/spatie/laravel-query-builder
