### ISSUE TITLE
[Proposal] paginate() method on eloquent should also detect 'per_page' on url query like 'page'

### ISSUE THREAD

**Issue by frdteknikelektro** [laravel/ideas#1126]

**Comment by sisve** [comment]
This would make every Laravel installation "vulnerable" to people editing it manually, like adding `per_page=1000000` to get everything at once. I presume that will totally mess up request times, memory usage and anger the server gnomes.

**Comment by frdteknikelektro** [comment]
Ah I see. . .

**Comment by deleugpn** [comment]
I have had my fun with this before: https://hackernoon.com/dynamic-but-limited-page-size-with-laravel-pagination-2826cab8b053
