### ISSUE TITLE
[Bug] Schema Builder: collaction() should be wrapped by quotes

### ISSUE THREAD

**Issue by rentalhost** [laravel/ideas#1127]
Else, `->collection('binary')` could fails in some cases, because of the generated code is something like `addressable_type` varchar(255) collate binary not null` (the correct is `addressable_type` varchar(255) collate "binary" not null`).

I think that it should be applied to both: collaction and charset.

It affects MariaDB 10.1, but I don't know if it affects other DBMS and which versions.

I am not the best person to PR that, so if someone could do that, it will be very useful.

---

Full test case:

```php
Schema::create('addresses', function (Blueprint $blueprint) {
    $blueprint->string('addressable_type')->collation(static::COLLATION_BINARY);
});
```

Code generated:

```php
create table `platform_addresses` (`addressable_type` varchar(255) collate binary
  not null) default character set utf8mb4 collate utf8mb4_unicode_ci
```

Code manually fixed:

```php
create table `platform_addresses` (`addressable_type` varchar(255) collate "binary"
  not null) default character set utf8mb4 collate utf8mb4_unicode_ci
```

**Comment by tomschlick** [comment]
This seems like a legit bug and should be raised as such (or better yet a PR to fix) on laravel/framework

**Comment by rentalhost** [comment]
I moved it to https://github.com/laravel/framework/issues/23944 so I am closing this here. Thanks!
