### ISSUE TITLE
[Proposal] Running seeds like migrations (e.g. incrementally)

### ISSUE THREAD

**Issue by desh901** [laravel/ideas#1130]
My proposal is to handle seeds like migrations: it would be useful to create a `seeds` table like `migrations` and process the files in `database/seeds` incrementally (like migrations). So each time i need to seed my application only the latest seeds will be run.

**An example**
I have a web application deployed on some servers with different environments: development, staging and production.

In this web app i have a `car_vendors` table in which i need to store all of the car brands that i need. I decide to create a seed to populate my table with some brands and then i deploy my app in the described servers with their respective environment. 

Now, let's say I don't want my users (admins) to manually manage car brands since the changes (in particular  the newly created ones) should be reflected manually on each environment. 

Right now, each time I need to add some brands I have to create a seed file. Also I have to remember that i have to seed all my environments with the newly created brands, and to do this I have to remember each time which was the latest seed run on each of them.

Clearly i could extend my Seed class and just check for the existence of the element in the table before creating it but that would be a tedious operation. Another workaround would be seeding the table within migrations but to me it feels kinda dirty.

**Comment by deleugpn** [comment]
I see absolutely 0 problems with using a `Seed` from a `Migrations` class. You use `Schema` facade to alter the database state, what would prevent you from using Eloquent or Seed instead?

**Comment by Kyslik** [comment]
>Another workaround would be seeding the table within migrations but to me it feels kinda dirty.

That would not solve the problem at all, as I understand you have multiple seeders for particular table. It makes sense to use seeder within migration but that will be good only for the **first** batch, subsequent `car_vendors` are going to require separate seeder each time (if you are already in production).
