### ISSUE TITLE
[Security] artisan schedule:finish exposes Database password and other things.

### ISSUE THREAD

**Issue by zhuomingliang** [laravel/ideas#1145]
I have a schedule and When `artisan schedule:run` is runing, I found something special by using `ps auxef`

```
/usr/bin/php7.0' 'artisan' schedule:finish "framework/schedule-f5c851ed37dbe754e89dbc6577c7fc33e4e913c1") > '/dev/null' 2>&1 
& HOME=/var/www LOGNAME=www-data PATH=/usr/bin:/bin 
LANG=en_US.UTF-8 SHELL=/bin/sh PWD=/var/www APP_NAME=_ENV=local 
APP_KEY=base64:oYL/37oqxUycwrUfFXExkDTnjQdopudfKNsILSSPcGQ= 
APP_DEBUG=false APP_LOG_LEVEL=error APP_URL=http://localhost TIME_ZONE= 
DB_CONNECTION=pgsql DB_HOST=localhost DB_PORT=6432 
DB_DATABASE=blog DB_USERNAME=postgres DB_PASSWORD=f50e3e2a8f1bc4495186c2c667f939a7 
BROADCAST_DRIVER=log CACHE_DRIVER=apc SESSION_DRIVER=file QUEUE_DRIVER=sync 
REDIS_HOST=127.0.0.1 REDIS_PASSWORD=null REDIS_PORT=6379 MAIL_DRIVER=smtp 
MAIL_HOST=smtp.mailtrap.io MAIL_PORT=2525 MAIL_USERNAME=null MAIL_PASSWORD=null 
MAIL_ENCRYPTION=null PUSHER_APP_ID= PUSHER_APP_KEY= PUSHER_APP_SECRET=
```

It means every normal user who has a ssh access can see it. I think it is a security problem.

**Comment by OwenMelbz** [comment]
@zhuomingliang cant the ssh user just read the env file? or boot up tinker and run `config('database')`anyway?

Although I admit this might be a concern is the argument not you should be securing your box more important? just as much as not having 777 folders everywhere?

**Comment by zhuomingliang** [comment]
They can't visit any project code and configure file.

Yeah, they only can get schedule logs. I hope the ssh user can't get the database passoword by using `ps auxef`.

**Comment by sisve** [comment]
The `e` in `ps auxef` shows the environment for the command, but only for commands you have right to access. This means that you can only see environment variables if you're running artisan as your own user (in which case you already have this information available to you) or as root using sudo (in which case ... well, you're root).

**Comment by zhuomingliang** [comment]
Turns out I am on root, and normal user can't see it. Thanks @sisve .
