### ISSUE TITLE
[Question] Does anyone use Apc cache driver?

### ISSUE THREAD

**Issue by halaei** [laravel/ideas#1146]
I just wondering what will happen if someone removes apc support from laravel framework? Does it just shrink the code a little and make the possible contributions easier, or it actually break some code in production? Thanks for your response.

**Comment by sisve** [comment]
I don't understand the thought behind this question.

If you remove something that is present in the framework, then all sites that is using that feature will fail. In this case every site using the apc cache will fail.

Why would the small reducing in code make it easier to contribute? Is the apc cache a barrier for entry?

**Comment by sisve** [comment]
* The ApcStore (apc_inc) does not create new entries for missing keys.
* The DatabaseStore (incrementOrDecrement) does not create new entries for missing keys.
* The MemcachedStore does not create new keys, [according to the protocol](https://github.com/memcached/memcached/blob/master/doc/protocol.txt#L285-L287).

<br>

* The ArrayStore creates new entries for missing keys. This looks easy to fix.
* The FileStore seems to create new entries for missing keys. This is hidden by an integer cast that will transform missing values (null) into a zero. It's also hidden by some weird attempt to use tap()
* The RedisStore creates new entries for missing keys. This is how the [incr](https://redis.io/commands/incr)/[incrby](https://redis.io/commands/incrby) commands work. We can probably solve this by writing a lua script that only increments if the key exists.

I would argue that the correct course of action would be to change all the cache stores to work identically in this regarding. I think that incrementing something that doesn't exist should fail.
