### ISSUE TITLE
[Proposal] Artisan Make Reverse command to undo generation

### ISSUE THREAD

**Issue by OzairP** [laravel/ideas#1149]
Often we make mistakes when generating scaffolding via the `artisan make:` command. I propose a `artisan make:reverse` command to reverse the last generated scaffold, therefor deleting it.

Additionally the reverse command should recognize if any of the files marked for deletion were modified and present a prompt to the user. This can be surpassed by adding a `-f` or `--force` flag.

**Comment by AkenRoberts** [comment]
Personally, I don't think creating + maintaining said feature is worth the overhead compared to letting developers manually delete files in their preferred way.

It is also unlikely the Laravel core team gives such a feature attention. Someone in the community would need to create a _very_ solid pull request for it to likely be considered.

**Comment by OzairP** [comment]
While I agree with your overhead argument, I think that the small tasks that are sped up by artisan is one of the things that makes Laravel so attractive. Lately I've been trying on Rails and I'm impressed by the amount of code generation is done, entire controllers and views are scaffolded and can be reversed.

A similar argument could be made to `artisan make:controller` since it generates a simple empty class.

**Comment by sisve** [comment]
How would a make:reverse even know what the last action was? Is there a suggested implementation for this? How would this handle scenarios where the previous make:something overwrote existing code, would a make:reverse revert to the code before make:something?

**Comment by OzairP** [comment]
@sisve the only implementation I can think of is to write the last operation to the disk in some `tmp` directory.

As far as the `make` command overriding something and trying to reverse it, at the moment it would not restore the previous overwritten contents, it can be implemented but it would be tedious.

**Comment by OzairP** [comment]
Alternatively we can move to what Rails does and do `artisan destroy:controller MyController` and it would reverse the operations done by `artisan make:controller`. That way nothing has to be persisted, but it still won't reverse any files that were overwritten by `make`

**Comment by OzairP** [comment]
Closing due to lack of support

**Comment by fletch3555** [comment]
Lack of support? This is an "ideas" forum, where people suggest features that may or may not get adopted into the framework.

**Comment by OzairP** [comment]
@fletch3555 So far no one has shown approval towards the idea. There are bigger issues to tackle.

**Comment by michaeldyrynda** [comment]
This sounds like a perfect use case for version control to me
