### ISSUE TITLE
[Proposal] Add an `entries()` method for Arr

### ISSUE THREAD

**Issue by BinotaLIU** [laravel/ideas#1150]
[Javascript has an `Object.entries()` method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries)  
It might be a good idea if we implement this in `Arr` class, it is useful when we are dealing with an associate array but we want to get a serial number of each entries.

I'm now using macro to make this idea work. But I think this is a good idea if we add this :smile: 

[There are a commit on my own fork already done this](https://github.com/BinotaLIU/laravel-framework/commit/a4a3650cfce4705575c92bb8198398ddaa16c18a).

**Comment by 36864** [comment]
Could you provide a real-world use case?

**Comment by BinotaLIU** [comment]
For example, I have a associative array witch key for video title, value for video url.

I want to show user some list like this:

 * Video 1: Video Title A
 * Video 2: Video Title B
 * Video 3: Video Title C

I wrote following code in my blade template:
```blade
  @php
    $i = 1;
  @endphp

  @foreach ($videos as $title => $url)
    <li>
      Video {{ $i }}: <a href="{{ $url }}">{{ $title }}</a>
    </li>
  @endforeach
```


With an entries method:
```blade
  @foreach (Arr::entries($videos) as $i => [$title, $url])
    <li>
      Video {{ $i + 1 }}: <a href="{{ $url }}">{{ $title }}</a>
    </li>
  @endforeach
```

**Comment by 36864** [comment]
In blade you can already do that using the `$loop` variable.

**Comment by BinotaLIU** [comment]
@36864 I see, didn't even notice that feature. Thanks.
