### ISSUE TITLE
[Proposal] Support boolean type for SoftDeletes

### ISSUE THREAD

**Issue by hzw729087** [laravel/ideas#1155]
Hi, 
For some reason, I added a deleted_at column as the type of boolean(tinyint) to the table. But SoftDeletes sets the deleted_at column to timestamp when soft deleting and has a wrong where clause when querying. 
Is there any possibility to support deleted_at column as the type of boolean(tinyint)?
deleted_at equals to true instead of "yyyy-MM-dd HH:mm:ss" or false instead of NULL.

**Comment by brunogaspar** [comment]
Don't think it makes much sense to make it accept booleans as the intent of this column is for you to also know when a row was deleted.

**Comment by hzw729087** [comment]
@brunogaspar Yes, but there should be another column for users who just want to know whether a row is soft deleted or not.

**Comment by michaeldyrynda** [comment]
This is more of an exceptional situation than one for everybody. You can create your own `SoftDeletes` trait that overrides the default, making the necessary query changes for this use case, but I wouldn't expect to see it in the framework.

**Comment by hzw729087** [comment]
@michaeldyrynda Thanks, the `SoftDeletes`  and  `SoftDeletingScope` were created. It is working.
