### ISSUE TITLE
[Proposal] Support custom casting types

### ISSUE THREAD

**Issue by rentalhost** [laravel/ideas#1188]
Currently Eloquent casting [supports the most common types](https://github.com/laravel/framework/blob/0c5b584234e51074b6beef240ae8948178a38fb6/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L474): `int` (`integer`), `float` (`double`, `real`), `string`, `bool` (`boolean`), `object`, `array` (`json`), `collection`, `date`, `datetime` (`custom_datetime`) and `timestamp`.

Although it can solve most of the problems, I believe it is feasible to implement a casting `interface` to expand this concept, making possible cast to anything else (since it implements a specific interface). 

Something like:

```
interface CastingInterface {
    public function setter(...); // Called before persist data.
    public function getter(...); // Called before read persited data.
}
```

So you can implements this interface to a casting class, and handle without need implements an acessor or mutator.

The use should be like:

```
protected $casts = [
    'pallete' => PalleteCasting::class
];
```

**Comment by tomschlick** [comment]
This has been attempted a few times with: 

https://github.com/laravel/framework/pull/13706 

https://github.com/laravel/framework/pull/18106

and a few others.

**Comment by tomschlick** [comment]
@rentalhost FYI, that wasn't a call to close this issue. Just a reference to those previous discussions / PRs so it could learn from them. This is a much needed change but so far no one has come up with a mergeable solution.
