### ISSUE TITLE
store, destroy, update, show VS create, delete, edit, view

### ISSUE THREAD

**Issue by skyrpex** [laravel/ideas#1195]
`store`, `destroy,` `update` and `show` are commonly used as controller methods (and route names). On the other hand, there's `create`, `delete`, `edit` and `view` for model policies.

Is there any reason for this? Would it be better if we choose one of the variations and stick with it?

**Comment by skyrpex** [comment]
You're right. Thanks.

**Comment by skydev2020** [comment]
What is the difference between show vs edit?

**Comment by donnysim** [comment]
show is usually kept for readonly forms, previews, content display like article page etc., index is mostly associated with lists, edit is to get data required for editing the entry if using in api or to return a view with the form filled for editing in web.
