### ISSUE TITLE
Eloquent instance Initialization events

### ISSUE THREAD

**Issue by ralphschindler** [laravel/ideas#1197]
There are a couple of areas in eloquent that still make it difficult to write extensions that can handle complex attributes.  (By "complex attributes", I mean non-natively-known attribute types that can be expressed as objects until serialization, like how datetime objects are handled). Take for example there were an attribute of type `Coordinate`, and one wishes to be able to achieve the following workflow:

```php
class Coordinate {} // assume exists as a 3rd party value object
class Place extends Model { uses 3rdParty/HasGeoTrait; ...} // assume this kind of model

$place = Place::find(1234);
$place->coordinate->setLatLong(30.01, -90.10);

// or

$place = new Place;
$place->coordinate->setLatLong(30.01, -90.10);
```

While the former can be setup by a 3rd party trait by hooking into the `retrieved` eloquent event, the latter cannot because there is no event fired early enough to setup an attribute with a value object for the `coordinate`.

Thus, I am proposing that the base eloquent model introduce 2 new events that will fire at construction time:

```diff
diff --git a/src/Illuminate/Database/Eloquent/Model.php b/src/Illuminate/Database/Eloquent/Model.php
index 443f09e8b..7c42b78a3 100644
--- a/src/Illuminate/Database/Eloquent/Model.php
+++ b/src/Illuminate/Database/Eloquent/Model.php
@@ -148,9 +148,13 @@ abstract class Model implements ArrayAccess, Arrayable, Jsonable, JsonSerializab
     {
         $this->bootIfNotBooted();

+        $this->fireModelEvent('initializing', false);
+
         $this->syncOriginal();

         $this->fill($attributes);
+
+        $this->fireModelEvent('initialized', false);
     }

     /**
```

This will give 3rd party traits the opportunity to do some initialization on eloquent models whether they were retrieved or newly instantiated.

Thoughts?

**Comment by Patryk27** [comment]
Totally by the way - how can `Coordinate` be a `value object`, if it's mutable?

**Comment by ralphschindler** [comment]
@Patryk27 semantically, it is a value object because it has no identity (contrasted with an Entity) and it's equality with other objects of the same type is based on the set of primitive values it wraps. It is true that you find immutability an increasingly common and (arguably) worthwhile characteristic of Value Objects, but that is not to say it is a defining characteristic. In the purest and simplest sense, VO's are *small simple object, like money or a date range, whose equality isn't based on identity.* [1](https://martinfowler.com/eaaCatalog/valueObject.html)

**Comment by Patryk27** [comment]
If we want to stick with Martin Fowler, let's bring some more context: https://martinfowler.com/bliki/ValueObject.html

> To avoid aliasing bugs I follow a simple but important rule: value objects should be immutable.

... and virtually every resource agrees on this topic ;-)

**Comment by dwightwatson** [comment]
Are dispatched events heavy/resource intensive, or are they insignificant if there no relevant listeners?

Just curious what the performance impact would be (if any) from two additional events with every instantiated model, especially with large collections/relationship chains.

**Comment by ralphschindler** [comment]
I believe they are insignificant when there are no relevant listeners. The impact is similar in nature to firing off a `retrieving`/`retrieved` event which is an event that has long been in Eloquent. Future packages would either continue to use `retrieving` to listen for all models being hydrated from a db row, or would use `initializing` when they want to listen for all models either being hydrated or models being created by using `new SomeModel`.

It is worth noting this gives 3rd parties (traits primarily), the opportunity to hook into the model lifecycle without having to instruct developers to override their models `__construct` method.
