### ISSUE TITLE
apiResources and method limit

### ISSUE THREAD

**Issue by oxycoder** [laravel/ideas#1202]
From the docs:
We can do: 
```
Route::apiResource('photos', 'PhotoController')->only(['index', 'show'];
```
But we can't do
```
Route::apiResources([
    'photos' => 'PhotoController',
    'posts' => 'PostController'
])->only(['index', 'show']);
```
Would be great if this option available in future

**Comment by martinbean** [comment]
@oxycoder Open a pull request? It’s what I did to add the `resources()` method to the router: https://github.com/laravel/framework/pull/6994

**Comment by fletch3555** [comment]
No need to be snarky @martinbean.  This is an "ideas" repo, where the purpose is to discuss ideas for enhancements to the framework.  In line with that, they're suggesting it as an idea.  If it gets downvoted to hell, they don't have to waste their time on it.  If it's widely approved, then maybe they'll work on the PR, or maybe someone else can.  That's the beauty of open-source!

**Comment by TBlindaruk** [comment]
I have created a PR https://github.com/laravel/framework/pull/24490,

But it will allow to do it by the assoc array.
