### ISSUE TITLE
[Proposal] Add schema method `storedAsNotNull` and `virtualAsNotNull`

### ISSUE THREAD

**Issue by mpyw** [laravel/ideas#1211]
Currently `->storedAs()` and `->virtualAs()` always make them nullable.

https://github.com/laravel/framework/blob/1cbb54e9da52d66bc09e181c34520df283bf46cd/src/Illuminate/Database/Schema/Grammars/MySqlGrammar.php#L892-L897

But making generated columns non-nullable provides robust and flexible constraints.

### Goals

- We have `members` table and `plans` table
  - `members.role` takes one of `owner` `guest` `subscriber`
  - `members.plan_id` has value **only when `members.role` is `subscriber`**
- We also need to sort members in `owner` `guest` `subscriber` order.

### Code

```php
$table
->unsignedTinyInteger('sort_priority')
->storedAsNotNull("
    CASE WHEN role = 'owner' AND plan_id IS NULL THEN 1
         WHEN role = 'guest' AND plan_id IS NULL THEN 2
         WHEN role = 'subscriber' AND plan_id IS NOT NULL THEN 3
         ELSE NULL
    END
")
->index();
```

`members.sort_priority` allows us making fast sorting `ORDER BY sort_priority, id` ensuring strong consistency.

**Comment by mpyw** [comment]
Options

- Backward Compatible: Add `storedAsNotNull` and `virtualAsNotNull`
- Breaking Change: Make `storedAs` and `virtualAs` not null by default and accepts `nullable` call

**Comment by driesvints** [comment]
A pr for this was merged.
