### ISSUE TITLE
Problem with repositories/cookies/controllers and the __construct of the controller.

### ISSUE THREAD

**Issue by GustavoFenilli** [laravel/ideas#1223]
So I have this code, a Repository that connects to my api, to use it I made a serviceprovider and bind it, so I can call it inside the methods parameters.

    class ConnectionRepository implements ConnectionRepositoryInterface
    {
    public function __construct(Client $client)
    {
        $this->client = $client;
        
        $this->setClientVariables();
        $this->setOptions();
    }

    public function get($url)
    {
        $response = $this->client->request('GET', $url, $this->options);

        return json_decode($response->getBody(), true);
    }

    public function connect()
    {
        if(!(Cookie::has('access_token') && Cookie::has('refresh_token') && Cookie::has('user'))){
            $response = $this->client->request('POST', 'login', $this->options);

            $values = json_decode($response->getBody(), true);

            if($values['code'] == 200){
                $this->setCookies($values['token'], $values['refresh_token'], $values['user']);

                return redirect($this->adminHome);
            }

            return $values;
        }

        return redirect($this->adminHome);
    }
    public function setOptions()
    {
        $this->options = [
            'base_uri' => $this->baseUri."/",
            'http_errors' => false,
            'headers' => [
                'Accept' => 'application/json',
                'Authorization' => "Bearer {$this->accessToken}",
            ]
        ];
    }

    public function setCookies($accessToken, $refreshToken, $user)
    {
        Cookie::queue('access_token', $accessToken, 60000);
        Cookie::queue('refresh_token', $refreshToken, 60000);
        Cookie::queue('user', json_encode($user), 60000);
    }
    }

And I have a controller that works, I call the ConnectionRepositoryInterface in all methods that use it, but it seens to me that I could simple make a __construct() and pass it there so I can call it $this->client from the methods, but it doesn't work, the cookies that get passed when I call my repository inside the constructor doesn't work, it doesn't get the right value for it.

    class LoginController extends Controller
    {
    public function showLoginForm()
    {
        return view('auth.login');
    }
    
    public function login(Request $request, ConnectionRepositoryInterface $client)
    {
        //
        $response = $client->setParams($request)->connect();

        return $response;
    }

    public function usuarios(ConnectionRepositoryInterface $client)
    {
        return $client->get('usuarios/1');
    }

    public function logout(ConnectionRepositoryInterface $client)
    {
        return $client->logout();
    }
    }

I think its because Sessions aren't called yet when I create the instance in the constructor, I get it that if I passed something like Request $request in the construtor it should not work, but my class is a custom class that should work normally.

**Comment by sisve** [comment]
The setClientVariables() method is missing from your code. Anyhow, the problem isn't that the Controller's __construct method is magically denying you stuff, it is that it is invoked way early in the request life cycle, before there's an active http request initialized in the framework. There is a default request that isn't populated, and using it will not work. It's not authenticated, it does not have cookies, and it does not enjoy life in general.

You cannot do stuff that depend on the current request in the controller constructor, not can you do it in code you call from the constructor. You could do the initialization from a middleware, which are executed later on when there's a valid request instance.

**Comment by GustavoFenilli** [comment]
the setClientVariables() method is just getting the cookies to variables, I see, so I should make a middleware for that, but I can't think a way of how it would work, because the middleware would create the object but how would I use it in the controller? I can't do something like $this->client.

**Comment by sisve** [comment]
You could register a singleton in your service provider, and then fetch that instance from the middleware and tell it what cookies to use. The controller would then use the same instance to do the request.

**Comment by RemiCollin** [comment]
You cannot really trust any code dealing with session/request inside the `__construct()` method of the Controller, because laravel's instantiate it very early in the process. 

Raised this related issue some time ago already : https://github.com/laravel/ideas/issues/463
