### ISSUE TITLE
Always encapsulate eloquent ::where() SQL output

### ISSUE THREAD

**Issue by Caroga** [laravel/ideas#1225]
Hi all,
I've been redirected here as a result of the following thread:
https://github.com/laravel/framework/issues/24551

Basically eloquent's `where()` outputs different SQL queries when being called either with separate parameters or an array of parameters, while in fact this should just produce the same output. 

But what is the difference you might ask?
Well, the following (copy paste alert):
```php
$users = DB::table('users')->where('id', 1)->get();
```
Gives:
```sql
select * from "users" where "id" = ?
```
While
```php
$users = DB::table('users')->where(['id' => 1])->get();
```
Gives:
```sql
select * from "users" where ("id" = ?)
```

The problem with this is that it breaks model/sql caching, cause , well, it misses a cached response. 

My request would be to unify this process and make `where('id', 1)` output a encapsulated where clause.

Please read through https://github.com/laravel/framework/issues/24551 as well (not a long thread).

Hope that you all can agree with this request. Thank you.

**Comment by AkenRoberts** [comment]
I believe it's worth consideration. Two biggest concerns:

* Does the encapsulation affect query performance substantially enough to warrant not adding?
* Will any breaking changes occur in generated SQL (think more complicated use cases)?

**Comment by fletch3555** [comment]
I can't imagine the encapsulation would affect query performance at all, since it's simply extra parens for grouping, not sub-queries.  However, I'm certainly not a database expert, so perhaps I've overlooked something.

Other than getting answers to the questions posed by @AkenRoberts, I see no reason this shouldn't be strongly considered.  I've used other ORMs in the past that had this behavior (or something similar... it's been a while), and it's worked well.

**Comment by sisve** [comment]
We've merged breaking changes without discussion before. No-one has managed to show how this could cause problems for a few days. There's no need to be this cautious. Just add those parentheses  and let mysql's query cache be happy again (until it's removed...)

**Comment by Caroga** [comment]
From what I've read and know I can say that 
- Using parenthesis does not have a negative impact on running your sql queries, and is recommended from the manual (to prevent mistakes in markup or something). 
A google search shows me some old post discussing this.
https://stackoverflow.com/questions/5525744/parenthesis-and-sql-query-performance 

- Eloquent, and please correct me if I'm wrong, stacks the different clauses before creating the SQL query. So theoretically it should just fall into place, even for the more complex queries.

**Comment by donnysim** [comment]
This would be a breaking change, I use array syntax to achieve grouped where instead of passing a function. I assume others might too.

**Comment by AkenRoberts** [comment]
> This would be a breaking change, I use array syntax to achieve grouped where instead of passing a function. I assume others might too.

@donnysim I don't believe anyone is suggesting removing that feature. Rather, the suggestion is to always treat a single where as a grouped where, in order to keep queries consistent and take advantage of the DB's caching.

**Comment by Caroga** [comment]
closing this as there is no point to continue this 3 years after opening.
