### ISSUE TITLE
Ability to changes locale from .env file

### ISSUE THREAD

**Issue by znsstudio** [laravel/ideas#1235]
Recently working on some projects I realized every time I have to change config file to use changes I made on below link/commit. I purpose it should be as implementation just to use .env file for translation and language for website.

https://github.com/znsstudio/laravel/commit/2bb887e0c1e2887a1d873e44b1b6f936085d39d9

**Comment by znsstudio** [comment]
Instead of creating multiple projects on gitlab with different config settings this fix gives me CI/CD just to modify environment settings

**Comment by fletch3555** [comment]
This doesn't really need any discussion.  Similar issues have been declined multiple times in laravel/laravel with the answer of "you're free to do this in your own project"

**Comment by znsstudio** [comment]
Problem with every upgrade it overrides this useful feature or having conflicts. In my opinion like most of config settings it should be also environment specific

**Comment by michaeldyrynda** [comment]
Why are you overriding your config files on each Laravel release? If you're maintaining a fork of the skeleton repo as a base for your applications, you need to be conscious of that and not blow the files away each time a new update comes up.
