### ISSUE TITLE
blade for exclude xss injection only

### ISSUE THREAD

**Issue by raiika** [laravel/ideas#1239]
{!! !!} gives raw
{{ }} escapes all tags

maybe it will be convenient if we escape xss injection only for those who uses ckeditor as user input

**Comment by sisve** [comment]
Could you explain in more details what you're asking for?

**Comment by raiika** [comment]
I have a ckeditor to write to database, so in this ckeditor I accept <strong> <i> <p> and other html tags, and later I display these tags to html...
The only eay to display these html tags is by using {!! $rawHtml !!} , but this approach will let someone to write <script> for xss injection...

Do u get what I mean ?

**Comment by sisve** [comment]
How would the escaping function know which tags are allowed, and which aren't? That sounds like something that could differ between every call to it.

**Comment by raiika** [comment]
2 approach, disable xss only, or allow html only

Ofcourse we use regex, but sorry I dont master the regex coding...

Xss only approach:
We exclude all < script * > and </script> 
Also iframr and other 4 tags (I dont remember all)
And also any tags with onclick behavior or any other javascript call syntax

Html approach:
We only include tags with p, div, table, td, etc, with a limited inStyle css, and only allowed something like href, or something like that

**Comment by fletch3555** [comment]
Unfortunately, blocking just script/iframe tags isn't really enough.  Also, blocking all event callbacks sounds like a monumental undertaking.

Refs:
http://www.lmgtfy.com/?q=xss+without+script+tag
https://stackoverflow.com/a/37435642

**Comment by LKDevelopment** [comment]
@raiika Take a look at https://github.com/ezyang/htmlpurifier there you can "filter" the evil tags right before you store it in the database...

**Comment by raiika** [comment]
yeah, I ended up using other library to overcome this.
wish in the future Laravel could make his own original blade for this.
