### ISSUE TITLE
Expose redis database number as an environment variable

### ISSUE THREAD

**Issue by w0rd-driven** [laravel/ideas#1247]
Rather than segregate redis instances by the `CACHE_PREFIX` environment variable, Laravel has the ability to segregate by database number but it isn't exposed by default.

In `.env.example` add `REDIS_DATABASE=0` underneath `REDIS_PORT=6379`. In `config/database` change https://github.com/laravel/laravel/blob/master/config/database.php#L115 from the default of 0 to `'database' => env('REDIS_DATABASE', 0),`.

For my use case the most important databases are closer to 0 with 0 being production, 1 being staging and so on. I believe the limit is from 0-15 which is more than enough for most environments. This would also allow you to mix and match between prefix and databases to create more possibilities than just segregating by prefix alone.

https://stackoverflow.com/questions/27835300/laravel-how-to-separate-cache-and-session-into-different-redis-database shows another use case where this could be beneficial, to segregate the cache and session into their own separate databases. That's a much bigger lift in terms of possibly breaking expectations to segregate those outright. 

I consider exposing the environment variable extremely low hanging fruit that I can easily tackle in a PR. I'm mainly posting this to make sure I'm not making incorrect assumptions or that there's some valid reason this was never done. Like `APP_NAME` before Laravel 5.4 this is something I tend to alter on every new Laravel project I create so it would save a little bit of time if this were in the framework proper. If there's no glaring objections I'll work up a PR ASAP. Thanks.

**Comment by sisve** [comment]
Just send a PR. The glaring objections will show up when they see the proposed code changes.

**Comment by crynobone** [comment]
This already handle for 5.7, If you on 5.6 or below might as well follow the same structure on your app.

<https://github.com/laravel/laravel/blob/develop/config/database.php#L111-L123>

**Comment by w0rd-driven** [comment]
I should've looked in the develop branch. I hadn't realized master was the stable version until 5.7 releases though I should've guessed that.

That change is sufficient and I only have minor gripes with DB over DATABASE and the values not existing in .env.example. It looks like session would default to 0 if redis is utilized and the cache would default to 1, which may not be intuitive from a `redis-cli` usage perspective. The artisan cache commands would just work I believe and I suspect that's how most people would interact with it. My usage patterns would rather the cache be 0 as redis is almost never used for session caching but that may not be better for the collective.

Ultimately I can live with minor gripes and if it's annoying enough when 5.7 drops I'll propose a PR then. I'll also look to just throw out a PR first as it's better to see the code to know how to shape it and leave this for more feature requests that may not easily have code attached.

Thanks again.
