### ISSUE TITLE
Determining the router of request

### ISSUE THREAD

**Issue by bluemmb** [laravel/ideas#1251]
Many apps have both mobile and web clients and they might use the same controllers and methods to handle both web and api requests.

To know which router has called the function we have used 2 middlewares  and a helper class and as i was searching for the solutions, seems some people encountering the same thing.

So I thought it would be great if it was implemented in the core. This is what I thought can solve this :

```php
class Request extends SymfonyRequest implements Arrayable, ArrayAccess
{
    /**
     * Determining the router.
     *
     * @var string
     */
    protected $router;

    /**
     * Get the router.
     *
     * @return string
     */
    public function getRouter()
    {
        return $this->router;
    }

    /**
     * Set the router.
     *
     * @param  string  $type
     * @return $this
     */
    public function setRouter($type)
    {
        $this->router = $type;
        return $this;
    }
}
```

```php
namespace Illuminate\Routing\Middleware;

use Closure;

class WebRouter
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        $request->setRouter("web");
        return $next($request);
    }
}
```

```php
namespace Illuminate\Routing\Middleware;

use Closure;

class ApiRouter
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        $request->setRouter("api");
        return $next($request);
    }
}
```

```php
namespace App\Http;

use Illuminate\Foundation\Http\Kernel as HttpKernel;

class Kernel extends HttpKernel
{
    protected $middlewareGroups = [
        'web' => [
            \Illuminate\Routing\Middleware\WebRouter::class,
        ],

        'api' => [
            \Illuminate\Routing\Middleware\ApiRouter::class,
        ],
    ];
}
```

**Comment by Patryk27** [comment]
So, if I understand correctly, you're calling `getRouter()` later in the controllers, right?
Can you provide an example of how such controller looks like?

I'm just curious whether this problem wouldn't be simpler to solve using terminable middlewares or patterns like Action-Domain-Responder.

**Comment by michaeldyrynda** [comment]
Or even just something like [this](https://timacdonald.me/versatile-response-objects-laravel/), leveraging response objects.

**Comment by bluemmb** [comment]
@Patryk27 Yes, right. I created a gist for [samples](https://gist.github.com/bluemmb/fbd9015a47b2d8a54076c76f2f421027).

@michaeldyrynda Thanks. It's very nice and interesting solution. 3 things are here :

- It needs creating extra classes for each method and it seems to be hard to implement and maintain for startups and small applications.

- In sample codes above. In AddressController.php there is a small difference between responses for mobile api and web that I have explained it, and I am sure it could be handled by your solution. But things get very messy and there are more possible responses in some cases, specially in storing new data in a table that have relations with some other tables or extra special logics and It would be hard to handle it with this solution.

- Also knowing which router has passed the request to the application is a standard feature to be there and may come handy, although I can't think of the situation right now.

Anyway, I am new to Laravel and doing Business Projects. I may not see many things here and sorry about that.

**Comment by michaeldyrynda** [comment]
I still think dedicated classes are a cleaner approach than passing strings around through middleware.

In its simplest form, you can even just check if `request()->wantsJson()` inside your controller methods and return some JSON from there, rather than taking the full blown approach suggested in the article.

I’ve seen Jeffrey Way take this approach in some of [his code](https://github.com/laracasts/Lets-Build-a-Forum-in-Laravel/blob/713853deb83d108f6bfa167fbdfc44e244c57e18/app/Http/Controllers/ThreadsController.php#L29) recently.

**Comment by golonix** [comment]
I also think ADR pattern fits here best. @bluemmb true, you have a lot of classes, but as @michaeldyrynda mentioned, you have clean separation.

> But things get very messy and there are more possible responses in some cases, specially in storing new data in a table that have relations with some other tables or extra special logics and It would be hard to handle it with this solution.

In ADR you have one action that handles stuff (actually calls the domain to handle stuff). Then, domain data (and any other) is passed to the responder. Responder is responsible to building the response. Obviously, in your case you need content negotiation, so creating response based on `Accept` header from the request. 

So, if you need to create different responses and add some additional data (for example API calls don't require supported locations from your gist, but web calls do), ADR is the way to go. Implement responder object that reacts on `Accept` header from the request and call proper method. Here's simple gist example for you case: [link](https://gist.github.com/golonix/3a26de134a7d42ca17e31c3165902991).

Btw. I'm working on a package that will add some support for ADR in Laravel: https://github.com/HydrefLab/laravel-adr

**Comment by bluemmb** [comment]
OK sure. Thanks for putting your attention and time. I agree that the mentioned approaches are better.

I will try to have better contribution next time.
