### ISSUE TITLE
[Proposal] Route::current()->parametersWithoutBind()

### ISSUE THREAD

**Issue by raiika** [laravel/ideas#1260]
For some reason I need to get the url parameters without the bind while using bind (the url value).

Route::current()->parametersWithoutBind()

**Comment by sisve** [comment]
Could you give an example of what you want to retrieve? What is "without the bind"?

**Comment by michaeldyrynda** [comment]
I assume the string value that’s in the URL, rather than the bound model

**Comment by deleugpn** [comment]
Looks weird to me. If the string in the url was capable of mutating into an eloquent object, it knows how to go back to being a string.

**Comment by raiika** [comment]
May I know how Laravel handle it ? Or should I make it myself ?

**Comment by rs-sliske** [comment]
`$model->getRouteKey()` ?

**Comment by raiika** [comment]
I am using custom Route::bind

**Comment by sisve** [comment]
I still have no clue what you're asking for. Could your clarify what "get the url parameters without the bind while using bind (the url value)" means?

If you have a `{locale}/zomg/{user}` route, then `$route->parameters` will give you a keyed collection with the values.

    // $route->parameters
    array(
        "locale" => (the locale object),
        "user" => (the user object)
    )

If you just want the url;

    // $route->uri
    "{locale}/zomg/{user}"

Does any of these address your problem? If not, can you clarify what you you want?

**Comment by raiika** [comment]
Rather than object, I want the string

**Comment by deleugpn** [comment]
From the request object, you may use `$request->segment($index);` to get the segmentation of the Path the Router loaded. Either way, I stand by my first comment. The object knows how to make up the string because it was resolved said string.

**Comment by sisve** [comment]
@raiika Are you asking about the original value that was resolved into the object? As in, if I keep my `{locale}/zomg/{user}` example and the url `sv-se/zomg/1337`, are you asking for the "1337" value instead of the User object?

@deleugpn You presume that the object is a Eloquent model and you've used implicit binding. Explicit binding can resolve things in any weird way, and there's no requirement for the object generated to even have a stringable representation.

**Comment by raiika** [comment]
@sisve yes, that's right.

**Comment by sisve** [comment]
I do not know of any way to get that information with the current api. Going via `$request->segments()`, as @deleugpn mentioned, is probably the quickest solution, but you may still look into the route objects different properties to figure calculate which segment you're looking for,

**Comment by raiika** [comment]
@sisve yeah, and I know this won't be implemented in the future so I guess I'll just use another way of retrieving the string. Thanks anyway for your time.

**Comment by rs-sliske** [comment]
@fletch3555 by default it goes off the primary key, but you can customize which field is used, 

$model->getRouteKey() returns the identifier which is used for route generation.


@raiika whats your use case?
you could maybe add your own middleware to store the parameters somewhere before the model binding runs, or disable the binding on certain endpoints

**Comment by fletch3555** [comment]
Fair point, I forgot about the `getRouteKeyName()` method.

Okay, so to be more dynamic, you can modify the snippet I posted above to something like this:

```
$parameterWanted = 'user';
$model = $route->parameters[$parameterWanted];
$value = $model->{$model->getRouteKeyName()};
```

**Comment by raiika** [comment]
I did not use default model binding by calling getRouteKey,
I currently using

    Route::bind('model', function (){});

That is why, I don't think this will work, because only Route knows how to convert the model back

**Comment by d3jn** [comment]
To clarify on my solution to this it's basically additional field and couple of methods for `Route` class:

```php
...
class Route
{
...
    protected $originalParameters;
...
    public function originalParameters()
    {
        if (isset($this->originalParameters)) {
            return $this->originalParameters;
        }

        throw new LogicException('Route is not bound.');
    }

    public function originalParameter($name, $default = null)
    {
        return Arr::get($this->originalParameters(), $name, $default);
    }
...
    public function bind(Request $request)
    {
        $this->compileRoute();

        $this->parameters = (new RouteParameterBinder($this))
                        ->parameters($request);

        // Here is the only addition to bind method. We init originalParameters with parameters only once when
        // this route instance is bound. Therefore subsequent changes to parameters will not affect originalParameters.
        $this->rawParameters = $this->parameters;

        return $this;
    }
...
}

**Comment by raiika** [comment]
Did you edit the Vendor folder ?

**Comment by d3jn** [comment]
> Did you edit the Vendor folder ?

Of course not, I solved my problem by extending eloquent model and passing parameter value it was resolved with into it's instance. Or your resolution logic can return array with both original and resolved values.

It just gave me an idea about some possible `Route` class improvement regarding similar issues.

**Comment by d3jn** [comment]
[Here](https://github.com/d3jn/framework/commit/3c288f0653b39472601ae94c190f283445ccd64d) is a link to the proposed solution. It's a non-breaking change, allows `Route` class to preserve original parameters values from request when it was bound, kinda makes sense to be there.

I don't see using request segments like @deleugpn proposed as a good solution to the problem because hardcoding parameter's position in the request url would be a bad practice and complicate maintaining of such a code - route parameters values should be retrieved by name.

Am I missing something?

**Comment by raiika** [comment]
Nice!! @d3jn, 
I think this will become very handy for me, thank you
