### ISSUE TITLE
Allow providing a reason in policies

### ISSUE THREAD

**Issue by donnysim** [laravel/ideas#1267]
At the moment it takes time to find the exact reason why something was allowed or denied, you have to dig through all the possible before/policy callbacks/checks to find which spot actually denies or allows a permission when it shouldn't/should. Now with introduction to guest users in 5.7, there will be even more situations to check (if guests are allowed).

Simplified example:

```php
public function before(User $user)
{
    if ($user->isSomething()) {
        return true;
    }

    if ($user->isSomethingElse()) {
        return false;
    }
}

public function destroy(User $user, Client $client)
{
    if ($user->getActiveCompanyKey() !== $client->company_id) {
        return false;
    }

    if (!$user->hasAccessToCompany($client->company) || !$user->can('client.destroy', $client->company)) {
        return false;
    }

    return true;
}
```

In this case it is difficult to tell why the user was denied an action so you need to check every `return false;`. I propose allowing to return a policy result that has a reason why something was allowed or denied. 

```php
public function before(User $user)
{
    if ($user->isSomething()) {
        return policy_allow('user is something');
    }

    if ($user->isSomethingElse()) {
        return policy_deny('user is something else');
    }
}

public function destroy(User $user, Client $client)
{
    if ($user->getActiveCompanyKey() !== $client->company_id) {
        return policy_deny('not an active company');
    }

    if (!$user->hasAccessToCompany($client->company)) {
        return policy_deny('no access to company');
    }
    
    if (!$user->can('client.destroy', $client->company)) {
        return policy_deny('has no client.destroy permission for company ' . $client->company->getKey());
    }

    return policy_allow('user has full access to company');
}
```

What is shown to the user is up to the developer - he can show the reason or just keep it private. This also could provide which callback denied it - `ClientPolicy@before`, `ClientPolicy@destroy`, maybe global `before callback`. This would be a breaking change.

**Comment by Patryk27** [comment]
Can't you just throw an exception?

**Comment by donnysim** [comment]
That wouldn't work for allowing permissions as you can't throw an exception if you allow it, in addition, default behavior policy/gate checks don't throw on denying, there's a special `authorize` method for that. Also, throwing in the policy would introduce inconsistent behavior and might not work with upcoming Nova which uses policies without throwing any exceptions.

**Comment by Patryk27** [comment]
> you can't throw an exception if you allow it _[a policy]_

Yes, you can't - but I believe it is a very rare case that people want to log `Access has been granted, because user is an administrator.` information, since this can be usually deduced manually when searching for the bugs.

> default behavior policy/gate checks don't throw on denying

They do (`HandlesAuthorization::deny`, called from inside `Gate::authorize`) and that exception is caught inside `Gate::check`.

> throwing in the policy would introduce inconsistent behavior

Inconsistent behavior with what part of the Laravel framework?

> and might not work with upcoming Nova which uses policies without throwing any exceptions.

What has Nova to do with the Laravel framework itself?

**Comment by donnysim** [comment]
> Yes, you can't - but I believe it is a very rare case that people want to log Access has been granted, because user is an administrator. information, since this can be usually deduced manually when searching for the bugs.

That's true, why I mentioned:

> What is shown to the user is up to the developer - he can show the reason or just keep it private.

Generally you won't be showing any success message for granted, there's no point, this is just for the developer to know, where it comes from - global is admin check etc..

> They do (HandlesAuthorization::deny, called from inside Gate::authorize) and that exception is caught inside Gate::check.

Yes, `Gate::authorize` throws an exception, but you will not get the exception or the reason outside of it if you want to show it to the user. All you will get is `true`/`false`, no message, no handler hint etc..

> Inconsistent behavior with what part of the Laravel framework?
> What has Nova to do with the Laravel framework itself?

For a moment I thought that the `Controller` does the error catching, so kind of my bad not taking a look.

Generally, when a client says he gets an action unauthorized exception, it's difficult to just say without in depth debugging. When you have global permissions, permissions that are administratable by the tenant, the tenant has employees that can have their permissions, also those permissions depend on subscription and so on, it's very complicated to say what went wrong. Maybe the permission or role did not assign as it was supposed to, maybe subscription expired but did not reset because a cron did not launch, maybe cache did not clear and so no. I know everyone will mention - thats what tests are for - well, tests don't help against server problems and they don't inform the user why something was denied etc.. At the moment, there is no logical way of showing why something happened without replacing Gates logic and so this also would allow more in depth permission testing where you could check specific permission checks. Maybe after updating code, the test passes, but only because later permission check denied it, not the one you expected to deny it.

**Comment by mfn** [comment]
> Generally, when a client says he gets an action unauthorized exception, it's difficult to just say without in depth debugging.

I can totally reason with this.

That's why in my code I do `Log::notice` _all_ the cases where I return `false`.

**Comment by donnysim** [comment]
`raw` method was made public in 5.7 which allows returning raw response and handling it manually, so I guess I'll close this.
