### ISSUE TITLE
[proposal] Allow setting class name of the relationship dynamically

### ISSUE THREAD

**Issue by connectkushal** [laravel/ideas#1276]
@taylorotwell 

If possible, it would be convenient to have the related class name be set dynamically like this
```
use App\Article;

class User {
...
  public function articles() {
    return $this->hasManyArticle(...);
  }
}
```
over this
```
public function articles() {
  return $this->hasMany('App\Article', ....);
}
```

**Comment by connectkushal** [comment]
maybe something similar to how whereUserId [works] (https://github.com/laravel/framework/blob/5.6/src/Illuminate/Database/Query/Builder.php#L2812)

**Comment by Patryk27** [comment]
What advantages has `hasManyArticle` over `hasMany(Article::class)`?

Because I see at least one strong **disadvantage**: no support for static analysis, so e.g. PhpStorm will not help in refactoring such models.
