### ISSUE TITLE
[Proposal] What if the now() helper uses the configured timezone

### ISSUE THREAD

**Issue by JuanDMeGon** [laravel/ideas#1283]
Using the configured timezone in the config/app.php file would be a good alternative, as it may provide an intuitive behavior.
If I configure a specific timezone, I expect to obtain the current time, when calling the now() helper, with the already set timezone.
Of course, if I want to use a different one I need to pass it as a parameter.
Thanks.

**Comment by Patryk27** [comment]
When you change timezone in the configuration, it **is** reflected in the Carbon instance returned using the `now()` helper.

**Comment by JuanDMeGon** [comment]
OMG, you are right!
I checked the code, and I did not notice where is it passing the configured timezone. Do you know how is it working? Just curious.

**Comment by mfn** [comment]
https://github.com/laravel/framework/blob/45dfc96bdc13739bf78601f5d33c3dd6472f04f3/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php#L49

Carbon is "just" a wrapper around DateTime which itself obeys the PHP intrinsic method `date_default_timezone_set`, aka a global setting.

**Comment by JuanDMeGon** [comment]
Ohhhh awesome! Didn't know about that. Thanks for letting me know. 
Best wishes.
