### ISSUE TITLE
PasswordBroker should not hardcode minimum length of password

### ISSUE THREAD

**Issue by sutara79** [laravel/ideas#1307]
Minimum length of password is set to 6.
https://github.com/laravel/framework/blob/5.7/src/Illuminate/Auth/Passwords/PasswordBroker.php#L175

It should be
`return $password === $confirm;` or
`return $password === $confirm && mb_strlen($password) >= 1;`.

Validation rules for resetting password already exist below.
https://github.com/laravel/framework/blob/5.7/src/Illuminate/Foundation/Auth/ResetsPasswords.php#L69

When I want to set minimum lenght of password to less than 6, I have to override not only [rules](https://github.com/laravel/framework/blob/5.7/src/Illuminate/Foundation/Auth/ResetsPasswords.php#L64) method, but also [reset](https://github.com/laravel/framework/blob/5.7/src/Illuminate/Foundation/Auth/ResetsPasswords.php#L38) method.
It is bothersome.

**Comment by taylorotwell** [comment]
This is done in Laravel 6.0.
