### ISSUE TITLE
[proposal] An helper which will help us to take back data and which will also help to save application values can be useful.

### ISSUE THREAD

**Issue by ismailcaakir** [laravel/ideas#1329]
A new helper which will help us to organize applicaton values and make app values more understanfull can be more useful.
For ex.
Let's  put /resources/values/url.php in our application to use some of the data in the file as config files.These files can be created optionally about the project you need ( url.php, string.php, color.php... x.php ). In this wise our charge about definication of the values in application wil be easier .

```php
<?php

/**
 * Example resources/values/services.php 
 */

return [

    'ExampleService' => [

        'apiUrl' => 'https://api.example-service.com',

        'apiCallBackUrl' => 'https://my-application.com/redirect',

        'apiAccessToken' => 'access-token',

        'apiAuthToken'   => 'auth-token'
    ],

    'ExampleService2' => [

        'apiUrl' => 'https://api.example-service-2.com',

        'apiCallBackUrl' => 'https://my-application.com/redirect',

        'apiAccessToken' => 'access-token',

        'apiAuthToken'   => 'auth-token'
    ],

];

```

Use

```php
Route::get('auth/service1', function (){

    /*
     * example method name -> values(key)
     */

    $params = [
        'accesToken'        => values('services.ExampleService.apiAccessToken'),
        'authToken'         => values('services.ExampleService.apiAuthToken'),
        'apiCallBackUrl'    => values('services.ExampleService.apiCallBackUrl'),
        'apiUrl'            => values('services.ExampleService.apiUrl'),
    ];

});

```

Don't forget to comment your ideas

**Comment by michaeldyrynda** [comment]
You can already do this with config files, I don’t think we need to duplicate the concept with a new helper.

**Comment by ismailcaakir** [comment]
@michaeldyrynda I know, but the data in the example is not the setting data. The task of the settings directory is not exactly that.

**Comment by brkphp** [comment]
may not be required for settings but may be required for data to be used in the resource.

For example: theme way, custom color data

**Comment by mfn** [comment]
> You can already do this with config files, I don’t think we need to duplicate the concept with a new helper.

Same though there.

Don't see the _additional benefit_.

**Comment by michaeldyrynda** [comment]
It’s all still _configuration_ though, not anything new. It’s even framed as such in the original issue text.
