### ISSUE TITLE
[Proposal] open generated files in IDE

### ISSUE THREAD

**Issue by Juddling** [laravel/ideas#1330]
Add an option to open generated files in your IDE with the default `.php` file handler.

```
php artisan make:controller ExampleController --open
```

(I've already done this on a local project and it's awesome)

I'll make this work with mac os, Linux and Windows.

Also need to consider how to handle in the case where multiple files are generated.

e.g. making a model with `-m` generated the migration too.

**Comment by karlos545** [comment]
That'd be super handy. I'd be happy to contribute a driver or two.

**Comment by Juddling** [comment]
@fletch3555 I'd rely on the OS's default program associated with `.php` files.

e.g. on my macbook:

```
open app/User.php
```

Will open PHPStorm

**Comment by ismailcaakir** [comment]
Great idea can be a really useful feature.

**Comment by ngyikp** [comment]
For some code inspiration, you could take a look at how the Node/React community does editor launching: https://github.com/facebook/create-react-app/blob/master/packages/react-dev-utils/launchEditor.js

Hint: It's probably not as straight-forward as `open abc.php` :(

**Comment by Juddling** [comment]
Works with surprisingly little code: https://github.com/laravel/framework/compare/master...Juddling:launch-editor

## Local Setup / Contributing
Clone the fork

```
git@github.com:Juddling/framework.git laravel-framework-fork
git checkout launch-editor
```

Create a new Laravel install (use develop which consumes framework 5.8), and symlink in the fork.

```
composer create-project laravel/laravel:dev-develop test-launch-editor
cd test-launch-editor
rm -rf vendor/laravel/framework
ln -s ~/laravel-framework-fork vendor/laravel/framework
```

(This can also be done by adding the GitHub url as a repository in the composer.json and setting the version to `dev-launch-editor`)

Then generate some files!

## Commands tested on macOS:
- [ ] make:auth (doesn’t open files but probably shouldn’t)
- [x] make:channel
- [x] make:command
- [x] make:controller
- [x] make:event
- [x] make:exception
- [x] make:factory
- [x] make:job
- [x] make:listener
- [x] make:mail
- [x] make:middleware
- [ ] make:migration (FAILED)
- [x] make:model
- [x] make:notification
- [x] make:observer
- [x] make:policy
- [x] make:provider
- [x] make:request
- [x] make:resource
- [x] make:rule
- [x] make:seeder
- [x] make:test

## Todo
- [x] OS: macOS
- [ ] OS: Windows
- [x] OS: Linux
- [ ] Add `--open` option
