### ISSUE TITLE
[IDEA] Scheduler jobs shouln't affect each others execution time

### ISSUE THREAD

**Issue by mfn** [laravel/ideas#1337]
_Note: see https://github.com/laravel/framework/issues/25834 for some background_

`schedule:run` runs all commands supposed to be run at a certain time sequentially within the same process (at least this is the experience I'm having).

Which means: if you hit a long running job before other jobs, the other jobs execution times may be skewed or totally off; depending on the long running jobs.

Expectations from using cron is that jobs are independently executed and thus their start time doesn't affect each other that way.

**Comment by laurencei** [comment]
Just use `->runInBackground()` to fork the process

**Comment by mfn** [comment]
#fail 

Ok, wasn't aware of it. Also it isn't mentioned at https://laravel.com/docs/5.7/scheduling …

Thanks!

**Comment by mfn** [comment]
Btw, how pathetic: this issue was anything but "leet":
![image](https://user-images.githubusercontent.com/87493/46336297-b573ee80-c62a-11e8-9714-74f0be4a50a4.png)

**Comment by laurencei** [comment]
lol
