### ISSUE TITLE
[5.7] Missing pivot id in belongsToMany

### ISSUE THREAD

**Issue by lk77** [laravel/ideas#1348]
Hello,

i have a problem with the belongsToMany relation,
when accessing pivot object,
the id attribute is not loaded, only the foreign keys are loaded.

For me it's not a logical behaviour, and we should not be forced to do withPivot('id') in relations to get the id.

For example, in a fresh laravel 5.7 install :
```
        $main = MainTable::first();
        $secondaries = $main->secondaries;
        $pivot = $secondaries->first()->pivot;
        dd($pivot->toArray());
```
result in :
```
array:3 [▼
  "main_table_id" => 1
  "secondary_table_id" => 1,
  "field1" => 15
]
```
what do you think ?

thanks

nb: my test models and database schema

[pivotTest.sql.txt](https://github.com/laravel/ideas/files/2461209/pivotTest.sql.txt)
[MainTable.php.txt](https://github.com/laravel/ideas/files/2461213/MainTable.php.txt)
[MainTableToSecondaryTable.php.txt](https://github.com/laravel/ideas/files/2461214/MainTableToSecondaryTable.php.txt)
[SecondaryTable.php.txt](https://github.com/laravel/ideas/files/2461215/SecondaryTable.php.txt)

**Comment by staudenmeir** [comment]
It's generally not recommended to have an `id` column in a pivot table. Why do you need it?

**Comment by lk77** [comment]
Because we are monitoring changes on pivot tables with laravel auditable, and having an id is easier, because the package does not handle composed primary keys. And it's the accepted way to do it in my company, it's a design choice i must comply with.

**Comment by staudenmeir** [comment]
If you need this in all your `BelongsToMany` relationships, you could create a parent class for your models (or a trait) and override the [`HasRelationships::belongsToMany()`](https://github.com/laravel/framework/blob/ac745730492ef23a04ce614228d11e496feb625d/src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php#L405) method:

```php
public function belongsToMany($related, $table = null, $foreignPivotKey = null, $relatedPivotKey = null,
                              $parentKey = null, $relatedKey = null, $relation = null) {
    return parent::belongsToMany(...func_get_args())->withPivot('id');
}
```

**Comment by omega246beta501** [comment]
Something that has worked for me is to add explicitly the primary key to the pivot table.
Following your example: 
`return $this->belongsToMany(SecondaryTable::class, 'main_table_to_secondary_table')->using(MainTableToSecondaryTable::class)->withPivot(['id', 'field1]');`

**Comment by lk77** [comment]
I'm closing this, since it's pretty old, and it seems to be a design choice by laravel, that will not be changed anytime soon.
