### ISSUE TITLE
Updating Illuminate\Support\Str without Stringy

### ISSUE THREAD

**Issue by roennow** [laravel/ideas#1351]
danielstjules/Stringy seems dead. 

Last release june 2017 and 10 pull requests open and not touched since then. would it be an idea to stop mirroring from that and either make a fork or use the code the way it is but update it directly in the Illuminate\Support\Str class?

I ask as I have a pull request open that fixes danish letter ø and å not being translated correctly.

**Comment by driesvints** [comment]
Merged.
