### ISSUE TITLE
[Proposal] Job middleware

### ISSUE THREAD

**Issue by hubertnnn** [laravel/ideas#1356]
Currently if you need to limit your job execution (eg. becouse of API limits etc.) you have to write an ugly code like this (from laravel documentation):

```
public function handle() 
{
    Redis::throttle('key')->allow(10)->every(60)->then(function () {
        // Job logic...
    }, function () {
        // Could not obtain lock...
        return $this->release(10);
    });
}
```

It is even worse if you need more than 1 "wrapper"
```
public function handle() 
{
    Redis::throttle('key')->allow(10)->every(60)->then(function () {
        Redis::funnel('key')->limit(1)->then(function () {
            // Job logic...
        }, function () {
            // Could not obtain lock...
            return $this->release(10);
        });

    }, function () {
        // Could not obtain lock...
        return $this->release(10);
    });
}
```

I suggest addition of middleware system for jobs similar to controllers, so that you could define your jobs much easier:

```
// app/Jobs/MyJob.php
class MyJob
{
    public $middleware = ['throttle:10,60', 'funnel:1'];

    public function handle()
    {
        // Job logic...
    }
}

// app/Jobs/Middleware/ThrottleMiddleware.php
class ThrottleMiddleware
{
    public function handle($job, Closure $next, $allow, $every)
    {
        Redis::throttle('key')->allow($allow)->every($every)->then(function () {
            $next($job);
        }, function () {
            // Could not obtain lock...
            return $this->release(10);
        });
    }
}

// app/Console/Kernel.php
protected $jobsMiddleware = [
    'throttle' => \App\Jobs\Middleware\ThrottleMiddleware::class,
    'funnel' => \App\Jobs\Middleware\FunnelMiddleware::class,
];

```

**Comment by danrichards** [comment]
A separate use case where job middleware would be useful, is modifying environmental conditions. This is something I've built route middleware around that would be lovely to expose in our job environment.

```
public $middleware = [
    'max_execution_time:60',
    'memory_limit:1024M',
];
```

**Comment by viezel** [comment]
Agreed. The same can be said about artisan commands. The ability to have middlewares supported in the `console/Kernal` would be very beneficial.

**Comment by taylorotwell** [comment]
I think this is a pretty interesting proposal and I think I would have used this feature before if it existed. It's actually pretty simple to implement I think... I wouldn't use that syntax though. For maximum flexibility and power I would just make it a normal PHP method on the job:

<img width="409" alt="image" src="https://user-images.githubusercontent.com/463230/62238268-3e1d0180-b398-11e9-908b-8675a5957530.png">

Alternatively allow specifying middleware on the dispatch:

<img width="331" alt="image" src="https://user-images.githubusercontent.com/463230/62238270-3fe6c500-b398-11e9-9bab-634abc75c35f.png">

**Comment by viezel** [comment]
yes please @taylorotwell 👏 . Can we get it into 6.0 release?

**Comment by olivernybroe** [comment]
Using @taylorotwell proposal doesn't have to disallow the other syntax.
It could be like with many other properties in Laravel. 
So you can set it directly in the property or override the method for full control.

**Comment by LasseRafn** [comment]
I'm so down for this!

**Comment by librevlad** [comment]
Sounds very interesting and clean! I'd probably not use Console Kernel to define those.
P.S. Can we also get job logging on that note? Maybe to Horizon? Really need something to debug jobs, especially when writing something that relies on 3rd party API or web scraping.

**Comment by michaeldyrynda** [comment]
Pretty clean; I definitely prefer the public method approach over a property, because it gives you a little more flexibility in terms of extension than a property 👍

**Comment by histonedev** [comment]
Middleware looks  like a great idea. Currently I write this logic in Parent Job class's handle method and call a perform method from there, which is then overridden in child job classes. A controller like middleware will be a far cleaner solution.

**Comment by SjorsO** [comment]
What are some other real world examples for job middleware apart from throttling?

**Comment by histonedev** [comment]
@SjorsO In our case, the jobs are user based. Each job contains a user object and does some processing on that user. We dont want overlaps. i.e. one particular job should run only once per user. For this, we set a user_id based redis lock and upon start, we check if the current job type is already running for this user.

**Comment by matthew-muscat** [comment]
This is also something we would utilise if it's available — it's particularly useful for repetitive rate limiting / throttle operations, but i can see this also being useful for jobs that require a common set of functionality to occur prior to the job starting.

Would also be great if we could add `terminate` actions for flexibility and consistency with the HTTP middleware implementation.

**Comment by DarkGhostHunter** [comment]
Okay, seeing the code there must be some new additions:

1) The `PendingDispatch` should have the middleware function.
2) These middlewares would be also serialized as part of the dispatchable.
3) The middlewares should be instanced before handling the Job.
4) The Queue Worker would pass through a Pipeline class, and finally hit the Job handle.

Should that be enough?

**Comment by driesvints** [comment]
This will be in Laravel 6.0
