### ISSUE TITLE
[proposal] implementing morphHas or morphHasMany

### ISSUE THREAD

**Issue by yamenarahman** [laravel/ideas#1360]
I was thinking if there are any intentions to implement the inverse of the polymorphic relation `morphTo`; Now a model can belong to any other model by specifying the `model_id` and `model_type` , what if a model can have any other model by refering also `model_id` and `model_type` ? a real life example may be I can comment on a post with a text or photo, so now the post has comments but those comments maybe text comments or photos comments. Is what I'm saying applicable or even good structured?

**Comment by staudenmeir** [comment]
What would the database look like in such a case?
