### ISSUE TITLE
Route::view('spa{a?}', 'spa')->where('a', '.*');

### ISSUE THREAD

**Issue by allowing** [laravel/ideas#1363]
I want to implement a single page application. For example, the `http://localhost/spa` url uniformly responds to the same page. `laravel` does not seem to support wildcard routing, so I thought of the following implementation:

```php
Route::view('spa{a?}', 'spa')->where('a', '.*');
```

But the parameter `a` here seems to be superfluous. Is there an implementation like this:

```php
Route::view('spa*', 'spa');
```

**Comment by sisve** [comment]
Isn't this a fallback route?

https://laravel.com/docs/5.7/routing#fallback-routes

**Comment by allowing** [comment]
No, there is a difference between `fallback route`.

**Comment by allowing** [comment]
I want to implement a single page application, but I don't want to deploy it separately, I want to implement it through routing. Like `vue`, `react`, it is required to return to the same page.
