### ISSUE TITLE
Laravel subdomain

### ISSUE THREAD

**Issue by hichxm** [laravel/ideas#1372]
With Laravel we can manage the subdomains of our application from the file "web.php".
But the problem is the fact of writing the domain name in raw to this endoit.

```php
use Illuminate\Support\Facades\Route;

Route::domain("sub0.mywebsite.fr")->group(...);
Route::domain("sub1.mywebsite.fr")->group(...);
Route::domain("sub2.mywebsite.fr")->group(...);
Route::domain("sub3.mywebsite.fr")->group(...);
```

The fact that the domain name is written in clear is quite embarrassing for the production, especially that somebody develops a different domain name. For me all my domains locally with ".dev" while in production it ends with ".fr", ".com", ".net" ....

I think that only specify the subdomain and not the domain will help the developers which will prevent them from modifying the configuration of the file "config/app.php".

Example:
```php
use Illuminate\Support\Facades\Route;

Route::subDomain("sub0")->group(...);
Route::subDomain("sub1")->group(...);
Route::subDomain("sub2")->group(...);
Route::subDomain("sub3")->group(...);
```

**Comment by thannaske** [comment]
I would just define a variable in the `config.php` file that allows me to set the domain name in the `.env` file.

`
[...]
"base_domain" => env('BASE_DOMAIN', 'default-domain.dev'),
[...]
`

Afterwards you may use:

```php
Route::domain("sub0." . config('base_domain'))->group(...);
```

**Comment by hichxm** [comment]
Yes I know this tip but with another static method in Route class named subDomain is better i going make pull request for that. :open_hands:

**Comment by hichxm** [comment]
And this subDomain make your example with config.

**Comment by hichxm** [comment]
https://github.com/laravel/framework/pull/26344
