### ISSUE TITLE
[Proposal] Switch the default increments() to a bigint

### ISSUE THREAD

**Issue by victorlap** [laravel/ideas#1384]
With regards to https://twitter.com/dhh/status/1060565296048562177

See also https://github.com/rails/rails/pull/26266

Since there already is bigIncrements for all suported database drivers, implementation of this should not see too many hurdles.

- [SqlServer](https://github.com/laravel/framework/blob/bf975fa30108a873098f8bd8ee348f8f4a3130f6/tests/Database/DatabaseSqlServerSchemaGrammarTest.php)
- [SQLite](https://github.com/laravel/framework/blob/e47252d5daf79aa0209c21028c60e9ed94c1e761/tests/Database/DatabaseSQLiteSchemaGrammarTest.php)
- [Postgres](https://github.com/laravel/framework/blob/0ac989a221ef436fc04c8bfbd7e7458bfb5870d3/tests/Database/DatabasePostgresSchemaGrammarTest.php)
- [MySql](https://github.com/laravel/framework/blob/bf975fa30108a873098f8bd8ee348f8f4a3130f6/tests/Database/DatabaseMySqlSchemaGrammarTest.php)

**Comment by tomschlick** [comment]
This would need to be done in a way that would keep the existing migrations using their current setup. Othewise you wont be able to run migrations for things like CI servers, new environments, etc. Especially if you use foreign keys linked to those columns.

**Comment by victorlap** [comment]
Yes, this will break previous migrations. However we can tackle this in three different ways:

1. Let it break, write a section in the upgrade guide, that every `increments()` should be altered to `smallIncrements()`. Changes to `Schema` methods have been done in the past, altough not this rigorous maybe.
2. Let uses revert to the previous setting by implementing a method along the likes of `Schema::disableBigIntegerIncrements()` that can be put somewhere in a service provider. This allows for new apps to use bigIncrements, while migrations in older apps can still function and would produce the same output as before.
3. Figure out a way to determine when the migration was created and automagically doing what # 2 suggests.

**Comment by michaeldyrynda** [comment]
I'd be for this, but the question is whether or not the breaking change goes into 5.8 in Feb, or if we wait for 6.0 (whenever that happens to be).

Do we know of any projects that are using Laravel at scale large enough that this will impact them?

@victorlap's suggestions on moving forward are good, though, and as long as they're covered in the upgrade guide, should be sufficient.

We've done similar before i.e. with the [`defaultStringLength`](https://laravel-news.com/laravel-5-4-key-too-long-error) - so I'd suggest break it and provide the fallback for those that want to preserve functionality, rather than updating things.

**Comment by tomschlick** [comment]
Sounds good to me. I’d say it’s worth a PR at this point 👍

**Comment by victorlap** [comment]
> Do we know of any projects that are using Laravel at scale large enough that this will impact them?
In the company I work for, we make sure that all ids are bigints, to reduce the likelyhood of running into problems. We do have some projects where this could have gone wrong. 

The default `jobs` and `failed_jobs` tables also use the `bigIncrements()` method.

**Comment by crynobone** [comment]
Why not just let the default migration stubs to use `bigIncrements()` so any new install can start use it by default without interfering with old applications.

**Comment by sisve** [comment]
I've proposed another solution in https://github.com/laravel/framework/pull/26472, which is what @crynobone suggests; to change the default migration stub instead of adding an application-wide flag.
