### ISSUE TITLE
[Proposal] Render slots for components

### ISSUE THREAD

**Issue by assertchris** [laravel/ideas#1389]
## Given

I love components, but there's something about them that makes it a little harder to compose them, than the client-side libraries we're used to. There's no way, currently, to use `$slot` as a function.

I can't, for instance, do this:

```html
@component('components.list', ['items' => $items])
    <!-- treat slot as though it must be rendered once for each item -->
    {{ $item->label }}
@endcomponent
```

...and then to create that component as:

```html
@foreach($items as $item)
    {{ $slot($item) }}
@endforeach
```

## Propsal

If we add the following blade directive:

<img width="614" alt="screenshot 2018-11-15 at 08 47 51" src="https://user-images.githubusercontent.com/200609/48535204-27d72000-e8b3-11e8-8276-58303cf23f0c.png">

...and modify the `ManagesComponents` concern slightly:

<img width="664" alt="screenshot 2018-11-15 at 08 48 26" src="https://user-images.githubusercontent.com/200609/48535245-41786780-e8b3-11e8-8127-752b50eb47c6.png">

...then we can make components like this:

<img width="687" alt="screenshot 2018-11-15 at 08 49 15" src="https://user-images.githubusercontent.com/200609/48535266-594feb80-e8b3-11e8-99b2-ed3ea8ec2a2f.png">

...which can be used like this:

<img width="618" alt="screenshot 2018-11-15 at 08 49 59" src="https://user-images.githubusercontent.com/200609/48535290-7389c980-e8b3-11e8-955a-5f5221b957a1.png">

Whaddya think?

**Comment by assertchris** [comment]
Inb4 someone points out you can already do this (slightly less appealing) thing:

<img width="935" alt="screenshot 2018-11-15 at 08 56 30" src="https://user-images.githubusercontent.com/200609/48535542-63beb500-e8b4-11e8-8d01-e36a84dc892f.png">

**Comment by tylernathanreed** [comment]
My work around for this involves declaring multiple slots, such as `items.0.title`, `items.0.body`, `items.1.title`, `items.1.body`. Making this work requires diciphering the `$__data` variable, which feels for like a hack than a feature.

Having some sort of array-based support for components would be great for accordions, lists, tab panels, etc.

**Comment by assertchris** [comment]
If you've landed here, all these years later; I made a stand-alone library that enables this very thing (requires PHP 7.4 and Laravel 7): https://github.com/assertchris/laravel-renderless-components
