### ISSUE TITLE
[Proposal] "loadJobsFrom" method on service providers, for package development

### ISSUE THREAD

**Issue by rogervila** [laravel/ideas#1395]
I use to extract the same behaviour between my Laravel projects to a custom package, since its very easy to maintain.

One of this behaviours implies triggering jobs, and I would like to keep them on the package.

Could it be possible to add a `loadJobsFrom` method on `Illuminate\Support\ServiceProvider`?

Thank you.

**Comment by deleugpn** [comment]
When does the Framework load jobs automatically?

**Comment by rogervila** [comment]
> When does the Framework load jobs automatically?

You are right. My mistake. Thank you.
