### ISSUE TITLE
[Proposal] AuthServiceProvider Policy Registration Include Array?

### ISSUE THREAD

**Issue by gofish543** [laravel/ideas#1429]
I was toying around with policies earlier today and I noticed, by default, policy registration is done on a model => policy basis. 
I'm curious if it would be beneficial to allow for a model => [policy, ...] registration instead.
Example...
```
<?php

namespace App\Providers;

use App\Policies\RoundPolicy;
use App\Round;
use Gate;
use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;

class AuthServiceProvider extends ServiceProvider {

    /**
     * The policy mappings for the application
     *
     * @var array
     */
    protected $policies = [
        Round::class => [
            RoundPolicy::class,
            ...
            SuperSecretPolicy::class,
            HeroicPolicy::class,
        ],
    ];

    /**
     * Register any authentication / authorization services
     *
     * @return void
     */
    public function boot() {
        $this->registerPolicies();
    }

    /**
     * Register the application's policies.
     *
     * @return void
     */
    public function registerPolicies() {
        foreach ($this->policies as $key => $value) {
            if (is_array($value)) {
                foreach ($value as $item) {
                    Gate::policy($key, $item);
                }
            }
            else {
                Gate::policy($key, $value);
            }
        }
    }
}
```
Take note of the registerPolicies function which allows for the policy registration to be a single value or an array, functioning similar to the EventServiceProvider event/listener registration.

Let me know what you think!

** Duplicate of my issue in the wrong spot https://github.com/laravel/framework/issues/26773 **

**Comment by staudenmeir** [comment]
What would be a use case where you want to split a policy into multiple parts?

What happens if a method is defined in multiple policies? Does the last one override the previous ones?

**Comment by gofish543** [comment]
Use Case: Separation of Logic. For example: AdminRoundsPolicy, CoachRoundsPolicy, and ApiRoundsPolicy. Each would have its own set of functions and checks that need to be done to approve the gate check, BUT all are defined on the Round model. Kind of like an event being fired and many listeners are waiting for it. Why separate all the logic into separate listeners? Because it is cleaner, easier to maintain, and easier to debug.

If a method is defined in multiple policies all of them would get called. I'd honestly think it would be cool if there was a param like `$cascade = true|false` or a `use CascadingPolicy`. If its false, a successful check on any overloaded method would return true. And if true, all checks must be successful for the gate to return true.
The naming for $cascade isn't the right word, but hopefully you get the idea from the example below

-----------------
Example:
$cascade = false;
Gate::check('view')....
- AdminRoundsPolicy => false
- CoachRoundsPolicy => true
- ApiRoundsPolicy => false
Gate::check('view').... true
-----------------
Example:
$cascade = true;
Gate::check('view')....
- AdminRoundsPolicy => false
- CoachRoundsPolicy => true
- ApiRoundsPolicy => false
Gate::check('view').... false

**Comment by staudenmeir** [comment]
You could separate the logic by splitting the `RoundPolicy` class into multiple traits:

```php
class RoundPolicyPolicy
{
    use HandlesAuthorization, AdminRoundsPolicy, ApiRoundsPolicy, CoachRoundsPolicy;
}
```

**Comment by gofish543** [comment]
That is a solution yes.
IMO, not the right one, feels like a work around. Which is why I created this feature.

**Comment by martinbean** [comment]
@gofish543 A policy check should return `true` or `false` for a given user. Nothing more. A user is either allowed to do something or not.

If you’re building your application using resourceful controllers, then your controller will relate to a single model, and your model would have a corresponding policy class. It doesn’t make sense to have multiple policies for a model.

If you have multiple checks you need to do to determine if a user can do something, then that sounds like a use case for middleware. You can apply multiple middleware to check if the _type_ of user can do something:

```php
Route::middleware('auth, 'coach')->group(function () {
    // Coach-only routes
});

Route::middleware('auth', 'admin')->group(function () {
    // Admin-only routes
});
```

You can also set middleware on a per-action basis in your controllers:

```php
class PlayerController extends Controller
{
    public function __construct()]
    {
        $this->middleware('coach')->only('edit', 'update', 'destroy');
    }
}
```

**Comment by gofish543** [comment]
@martinbean I believe you have misinterpreted what the main point of this feature request is. 
I would like to mimic the EventsServiceProvider where a single event has many listeners.
I would like to have a single model have many policies.

**Comment by martinbean** [comment]
@gofish543 I’ve not misinterpreted. I understand what you’re trying to do but policies ≠ listeners; it doesn’t make sense for a model to have multiple policies the same way an event may have multiple listeners.

Like I say, your model should have a single policy that checks whether a user is able to perform an action or not. An event listener doesn’t determine if an event is successful or not.

**Comment by dillingham** [comment]
This would be valuable for packages. 
I imagine it performing like middleware.

User -> PackagePolicy@update = false
User -> UserPolicy@update = true <- doesn't get called
