### ISSUE TITLE
Add InvalidArgumentException For orderBy() in Illuminate\Database\Query\Builder

### ISSUE THREAD

**Issue by cocoeyes02** [laravel/ideas#1434]
Hi, I suggest improve of orderBy().
https://github.com/laravel/framework/blob/28cdb6bc2cfd4d802efe5ea7c6e7f7e581163117/src/Illuminate/Database/Query/Builder.php#L1778-L1793

If $direction is a typo (ex. 'as', 'aesc'), that means orderBy('desc').
I think it doesn't good to me because this process causes the bug of direction unintentionally.

This is why I want InvalidArgumentException before this process.

```
public function orderBy($column, $direction = 'asc')
{
    if (!in_array(strtolower($direction), ['asc', 'desc'], true)) {
        throw new InvalidArgumentException('Invalid value of direction .');
    }

    $this->{$this->unions ? 'unionOrders' : 'orders'}[] = [
        'column' => $column,
        'direction' => strtolower($direction) == 'asc' ? 'asc' : 'desc',
    ];

    return $this;
} 
```

thanks.

**Comment by mfn** [comment]
I'm in favour of this; no reason to accept typos or plain invalid values.

**Comment by deleugpn** [comment]
I would be in favour of this instead:

```
$this->{$this->unions ? 'unionOrders' : 'orders'}[] = [
        'column' => $column,
        'direction' => strtolower($direction),
    ];

    return $this;
```

If value is invalid, database engine will throw exception. Query Builder doesn't need to know about valid values of a group clause.

**Comment by staudenmeir** [comment]
@deleugpn This is vulnerable to SQL injections when an application allows user input:

```php
$query->orderBy($request->column, $request->direction)
```

**Comment by deleugpn** [comment]
Wouldn't that be solved by prepared statement?

**Comment by staudenmeir** [comment]
No, you can't pass the column name or the direction as a binding.
