### ISSUE TITLE
NotifiableContract

### ISSUE THREAD

**Issue by FrontEndCoffee** [laravel/ideas#1442]
There is a [Notifiable](https://github.com/laravel/framework/blob/5.7/src/Illuminate/Notifications/Notifiable.php) trait, but there is no interface/contract to go with it. This would be a great feature for the sake of type-hinting.

**Comment by nmokkenstorm** [comment]
@driesvints I had the same thought when working on an application yesterday, and I ran into the ticket [here](https://github.com/laravel/framework/issues/26848), and opened a PR here](https://github.com/laravel/framework/pull/29128)

Adding an interface in `Illuminate\Contracts\Notifications` was pretty straightforward. However the Notifiable trait is included by default in the User model in `laravel/laravel`, not `laravel/framework`, so actually including it there and throughout the framework would be a breaking change.

I'd still like to include a contract so users can at least pull it in on their implementation level models, hence the PR, but I'd love to share thoughts on how to better integrate this with the framework.

**Comment by driesvints** [comment]
Since Taylor has rejected the PR I don't think we'll be considering to add this anytime soon, sorry.
