### ISSUE TITLE
Deprecate $defer property in favor of interface on service providers

### ISSUE THREAD

**Issue by svenluijten** [laravel/ideas#1453]
I propose we move to deprecate the `$defer` property on service providers. In my experience, there's a bit of confusion around the property (what it does, how it works, and what else it needs). People will sometimes forget to implement the `provides` method, causing cryptic errors.

In place of this property, we'd have a `Deferred` interface that each service provider can implement, which would look a bit like this (typehint optional, of course):

```php
interface Deferred
{
    public function provides(): array;
}
```

A deferred service provider would then end up looking like this:

```php
class RiakServiceProvider extends ServiceProvider implements Deferred
{
    // ...

    public function provides()
    {
        return [Connection::class];
    }
}
```

The only method that'd need changing would be [`\Illuminate\Support\ServiceProvider::isDeferred`](https://github.com/laravel/framework/blob/5.7/src/Illuminate/Support/ServiceProvider.php#L298), and it'd end up looking like this during the deprecation period (5.8?):

```php
public function isDeferred()
{
    return $this->defer || $this instanceof Deferred;
}
```

After the deprecation period, we could change it over to only have the `instanceof` check left.

This way, we avoid cryptic errors like `Unresolvable dependency resolving [Parameter #0 [ <required> $foo ]]` when the `provides` method isn't implemented. Instead, the user will get an error that the method should be added.

**Comment by lloy0076** [comment]
Acting as *devil's advocate* why would you need to deprecate it?

The interface way could become the recommended way and the **only** way according to the documentation and the `isDeferred()` could be adjusted to complain if it sees the `->defer` (but not crash)...and all the 3rd party packages still work.

As opposed to completely crash.

Another alternative would be to fix the error if it were fixable...

**Comment by ellisio** [comment]
I echo @lloy0076's comment. If you were to remove the `$defer` property, you could throw a `@deprecated` phpdoc on it; with it being removed in `6.x`, whenever that happens. I would be against removing this in any `5.x` release.

**Comment by svenluijten** [comment]
@lloy0076 @ellisio there have been plenty of breaking changes in previous 5.x releases. Laravel doesn't follow [semver](https://semver.org/), and Taylor has said publicly that only a major overhaul would warrant a 6.x release.

I do agree that we shouldn't just remove it outright in the upcoming release, I suggest we `@deprecate` it in 5.8, and then remove it in 5.9. This way there's pleny of leeway for applications and packages to adjust, and we can start using the interface immediately. 

Using the `Deferred` interface would also become the only documented way in version 5.8 of the documentation.

**Comment by mfn** [comment]
Please change the title, almost got a heart attack reading it.

Yes, you're proposing to deprecated it but the higher level goal is to replace it with something better => so please 🙏 reflect that in the title.

As to for your proposal: I'm in general 👍 , I've been bitten by this too (forget to adjust provides) and TBH, deferring should be advocated to be the default case _whenever possible_. 95% of my Service Providers are deferred.

**Comment by svenluijten** [comment]
https://github.com/laravel/framework/pull/27067 got merged, the new interface is called `\Illuminate\Contracts\Support\DeferredProvider` 🎉 

Documentation PR can be found [here](https://github.com/laravel/docs/pull/4887).
