### ISSUE TITLE
Add the countBy() method to the Collection class

### ISSUE THREAD

**Issue by elbojoloco** [laravel/ideas#1454]
I want to propose the addition of a `countBy($key)` method to the Collection class. It's been something I felt missing for a long time, but I never thought to reach out about it. I've written it out and tested it, I'm very happy with the result.

```
/**
 * Count the number of items in the collection by a given key.
 *
 * @param  string  $key
 * @return static
 */
public function countBy($key)
{
    return $this->groupBy($key)->map(function ($items) {
        return count($items);
    });
}
```

Let's say we have a collection of `$users` with their roles eager loaded.

`$userCountByRole = $users->countBy('role.title');`
Would return something like this:
```
{
    "admin": 3,
    "author": 32,
    "guest": 78,
}
```

The reason I think this should be added to the base class is because this method can be applied almost anywhere, so adding it manually to all your models would be a tedious task.

**Comment by svenluijten** [comment]
This might be a bit too specific to be included in core. To prevent having to implement this in every model, you can add it as [a macro](https://laravel.com/docs/5.7/collections#extending-collections) so you can re-use it everywhere.

**Comment by Sealtyel** [comment]
This has been added to the framework collections class
