### ISSUE TITLE
Multiple mail driver support.

### ISSUE THREAD

**Issue by dkulyk** [laravel/ideas#1455]
Need to add multiple configurations for mail like database. And support to specify a mail driver name to the Mailable class.

**Comment by anik786** [comment]
This is really important in multi-tenant applications.

**Comment by mikemand** [comment]
I don't think this idea is getting enough attention. This is important for not only multi-tenant applications, but applications that have to deal with sending transactional AND bulk emails. I don't know about the other mail providers, but Postmark does not allow you to send bulk email on their transactional servers. They are currently in beta for bulk sending, but you have to use a separate host (and thus username and password) to send on their bulk servers.

Conceptually, I could see it working similar to how Storage works, in that you can use a `driver` method to choose which mail driver to use (for example, `Mail::driver('something')->send()` or `Mail::driver('something')->queue()`). In a `Mailable` or a mail Notification, you could do something like `$this->emailDriver` to set the driver that notification/mailable uses (like you can with `$this->queue` to pick which queue a notification is put on). I'm not sure if it has to be in the constructor of the class, or if you can do it within the `toMail` method of the Notification.

**Comment by Megachill** [comment]
+1 Would love to see `Mail::driver('mailgun')` etc as per mikemand comment above

**Comment by dkulyk** [comment]
This is [implemented](https://github.com/laravel/framework/pull/31073) in 7.0

**Comment by Megachill** [comment]
> This is [implemented](https://github.com/laravel/framework/pull/31073) in 7.0

Cheers, just saw that too ;) Awesome

**Comment by ArtisanTinkerer** [comment]
So how does this work with notifications?

**Comment by mikemand** [comment]
After the `(new MailMessage)` line (or, if you are using your own mailer, after you instantiate it) call `->mailer('your-driver-here')`.
