### ISSUE TITLE
Some contracts depend on concrete classes

### ISSUE THREAD

**Issue by berrymore** [laravel/ideas#1456]
According to the Laravel's [documentation](https://laravel.com/docs/5.7/contracts)

> All of the Laravel contracts live in their [own GitHub repository](https://github.com/illuminate/contracts). This provides a quick reference point for all available contracts, as well as a single, decoupled package that may be utilized by package developers.

I'm building my `Domain` layer's services on top of these `Contracts`. It's very conveniently, because Laravel provides really helpful interfaces and `Laravel Framework` is a realization of these interfaces itself.

Using of `Contracts` gives flexibility in case to swap concrete realization in every moment. But there are some collisions in contracts. Some of them depend on concrete classes from Illuminate.

For example [Illuminate\Contracts\Mail\Mailer](https://github.com/illuminate/contracts/blob/master/Mail/Mailer.php). It depends on `\Illuminate\Mail\PendingMail` in `return` directive of `to()` and `bcc()` methods. But there is no `illuminate/mail` requirement in `composer.json`
```json
"require": {
    "php": "^7.1.3",
    "psr/container": "^1.0",
    "psr/simple-cache": "^1.0"
}
```

I think it is possible to write interface for `\Illuminate\Mail\PendingMail` class to fully decouple contracts for `Mail` component.

The next interfaces seem to be wrong
[Illuminate\Contracts\Support\Responsable](https://laravel.com/api/5.7/Illuminate/Contracts/Support/Responsable.html)
[Illuminate\Contracts\Session\Session](https://laravel.com/api/5.7/Illuminate/Contracts/Session/Session.html)
[Illuminate\Contracts\Routing\Registrar](https://laravel.com/api/5.7/Illuminate/Contracts/Routing/Registrar.html)
[Illuminate\Contracts\Routing\ResponseFactory](https://laravel.com/api/5.7/Illuminate/Contracts/Routing/ResponseFactory.html)
[Illuminate\Contracts\Routing\UrlRoutable](https://laravel.com/api/5.7/Illuminate/Contracts/Routing/UrlRoutable.html)
[Illuminate\Contracts\Redis\Factory](https://laravel.com/api/5.7/Illuminate/Contracts/Redis/Factory.html) (it returns `Connection` class, but `Connection` interface presented)
[Illuminate\Contracts\Notifications\Dispatcher](https://laravel.com/api/5.7/Illuminate/Contracts/Notifications/Dispatcher.html)
[Illuminate\Contracts\Notifications\Factory](https://laravel.com/api/5.7/Illuminate/Contracts/Notifications/Factory.html)
[Illuminate\Contracts\Mail\Mailer](https://laravel.com/api/5.7/Illuminate/Contracts/Mail/Mailer.html)
[Illuminate\Contracts\Http\Kernel](https://laravel.com/api/5.7/Illuminate/Contracts/Http/Kernel.html) (?)
[Illuminate\Contracts\Foundation\Application](https://laravel.com/api/5.7/Illuminate/Contracts/Foundation/Application.html)
[Illuminate\Contracts\Debug\ExceptionHandler](https://laravel.com/api/5.7/Illuminate/Contracts/Debug/ExceptionHandler.html)
[Illuminate\Contracts\Console\Kernel](https://laravel.com/api/5.7/Illuminate/Contracts/Console/Kernel.html) (PendingDispatch)
[Illuminate\Contracts\Broadcasting](https://laravel.com/api/5.7/Illuminate/Contracts/Broadcasting/Broadcaster.html) (almost entirely)
[Illuminate\Contracts\Auth\Access\Gate](https://laravel.com/api/5.7/Illuminate/Contracts/Auth/Access/Gate.html)
[Illuminate\Contracts\Auth\SupportBasicAuth](https://laravel.com/api/5.7/Illuminate/Contracts/Auth/SupportsBasicAuth.html) (?)

Best regards, Sergey.

**Comment by deleugpn** [comment]
Feel free to send small PRs trying to fix these issues. @X-Coder264 has sent a lot of PRs to improve the contracts on 5.8 release, perhaps even some of these might have been fixed?

**Comment by X-Coder264** [comment]
I agree that all of these interfaces should be appropriately fixed. My focus for interfaces for 5.8 was on violations and missing methods, but I've seen this issue on some contracts, I just didn't think there would be so many of them.

**Comment by berrymore** [comment]
Ok, thanks, I will try to fix them in the near free time. @X-Coder264 Are these fixes should go to the `master` branch?

**Comment by X-Coder264** [comment]
Yeah, they should definitely go to the `master` branch as any change to a contract is a breaking change.

**Comment by deleugpn** [comment]
Remember to chunk them into small PRs to increase your chance to get them approved.
Perhaps one contract per pull request.
