### ISSUE TITLE
add a better mutators and accessors on eloquent

### ISSUE THREAD

**Issue by khanzadimahdi** [laravel/ideas#1461]
some times we need to run a method on a value before saveing it into database , in eloquent we have accessors and mutators , but it is a bit hard to run same codes on multiple fields! it think it is better to use an array similar to "casts" property in eloquent. it can be some thing like the below code:

### instead of using the below:
``` php
class myModel extends Model {
    public function setPublishedAtAttribute($value){}
    public function setClosedAtAttribute($value){}
}
```
### the better syntax can be
``` php
class myModel extends Model {
    protected $mutators = ['closed_at' => 'aMethodName1', 'published_at' => 'aMethodName2'  ];
}
```
in this syntax we can use a mutator multiple time in multiple classes without reapetetive codes.

**Comment by mfn** [comment]
What's "better" here?

Except that it's wrapping around even more magic to the already wizardy system 😄

**Comment by JeroenVanOort** [comment]
If you want to avoid repeating code between models, you could add your mutators and accessors to a trait and apply that trait to the models of your choice.

Adding more magic to Laravel would make it even harder to use static analysis tools.

**Comment by koenhoeijmakers** [comment]
You don't have to repeat your code.

```
public function aMethodName1($value) {}

public function setPublishedAtAttribute($value)
{
    return $this->aMethodName1($value);
}
```

**Comment by imanghafoori1** [comment]
It is in fact better, because this way we can add mutators and accessors at `RUN TIME` and not at `Compile Time`

and that is a huge difference.
for example when you want to write a laravel package that needs to add some mutators on the User model.
This way you can add them within the `boot` method of your package. without changing the code of the target model.
and upon the removal of the package, the mutators just go away when you remove the package.
No need to go to the user model and remove some method.

Decoupling !!!

**Comment by khanzadimahdi** [comment]
@imanghafoori1 i think using arrays in order to handle mutators and accessors is a better and easier way , and it can be handled dynamically at run time. 
@JeroenVanOort when we have different fields (or properities) in each Model, using traits is not a good idea. 
for example: i a have ['fieldA','fieldB'] in Model1 and i have ['fieldC','fieldD'] in Model2. mutators (or accessors) has completely the same logic here, however i cant use same methods (i mean mutators or accessors) because the name of them (methods) depends on their field's name.

**Comment by mfn** [comment]
> i think using arrays in order to handle mutators and accessors is a better and easier way , and it can be handled dynamically at run time

IMHO this is a totally backwards way and feels like going back in time. I don't like it at all.

**Comment by imanghafoori1** [comment]
> > i think using arrays in order to handle mutators and accessors is a better and easier way , and it can be handled dynamically at run time
> 
> IMHO this is a totally backwards way and feels like going back in time. I don't like it at all.

https://cleancoders.com/episode/clean-code-episode-26/show

In this episode uncle bob vastly discusses the `type safety` vs `independent deployability` and eventually says that : 
> All we have to do, is to sacrifice a little tiny bit of `type safety` to get the vast benefits of `independent deployability` so we do not have to throw the baby out with the bath water.

Since we can just use unit tests to remedy the `type safety`.

![image](https://user-images.githubusercontent.com/6961695/50685884-5c07cb00-1030-11e9-978f-1affd6671965.png)

**Comment by mfn** [comment]
Nice one, wouldn't have expected Uncle Bob turning on me on this one ;-)

Still not convinced with this _technical_ approach.

**Comment by imanghafoori1** [comment]
Again I invite you to take a look at the https://octobercms.com/docs/database/relations#introduction
and have a deeper look into it.
when you start to modularize your application with :
https://github.com/nWidart/laravel-modules
you immediately realize that module in different modules can not be totally decoupled.
When you add a add a `comment` module : the User module code should change to define new relations.
then when you add  `like` module both the `comment` and `user` module code are modified.

same thing when you remove them.
So are they really modules then?!

**Comment by imanghafoori1** [comment]
Let me mention that modern languages like `Go` or `Rust` allow you to add methods on the `type`s from other modules. so that problem is somewhat solved at the language level. But in php, we need some work around, something like `Macroable` trait.

Hope my explanation is good enough to grasp.
