### ISSUE TITLE
When use sqlite in memory mode then running database migrate each test method

### ISSUE THREAD

**Issue by sh-ogawa** [laravel/ideas#1469]
Illuminate\Foundation\Testing\RefreshDatabase::refreshTestDatabase method refer RefreshDatabaseState::$migrated but refreshInMemoryDatabase method don't refer this static property.

Is there a reason why this method's database migration is not controlled by flags?

I want to refer RefreshDatabaseState::$migrated at refreshInMemoryDatabase method.
Because I want to control the performance of the test code by reducing the number of insert to the database.

```php
protected function refreshInMemoryDatabase()
{
    if (! RefreshDatabaseState::$migrated) {
        $this->artisan('migrate');
        $this->app[Kernel::class]->setArtisan(null);
        RefreshDatabaseState::$migrated = true;
    }
}
```

**Comment by staudenmeir** [comment]
The `$migrated` property is only relevant for persistent databases. It's used to make sure the database is only migrated once.

In-memory SQLite databases are not persistent and therefore have to be migrated in every single test.

**Comment by staudenmeir** [comment]
Please close the issue.
