### ISSUE TITLE
Register or preBoot ?

### ISSUE THREAD

**Issue by imanghafoori1** [laravel/ideas#1472]
After all years of talking to coworkers and friends about laravel, I always wondered that people (even relatively experienced ones) do not know that the `register` methods on the providers are called before the `boot` methods.

Not only that, they can not believe me if I tell me this is the way that it works...

I remember that I first read about this rule  in the Taylor's book `'Laravel 4 from Apprentice to Artisan'`
and it took me a while to memorize which one is call first, (`boot` or `register`)

I  always ask myself what if these methods were named:
`boot` and `preBoot` 
or maybe
`register` and `postRegister`... ?!

**Comment by mfn** [comment]
To me the names are fine and "expected".

I've re-read the documentation at https://laravel.com/docs/5.7/providers : 
> So, what if we need to register a view composer within our service provider? This should be done within the boot method. **This method is called after all other service providers have been registered**, meaning you have access to all other services that have been registered by the framework:

Emphasis isn't even mine, it's in the docs.

Also, with two or three `var_dump` you can easily "proof" the order of , not sure what else to say here.

To me this seems to be an educational problem.

Of course this doesn't mean the docs can't be improved, if you've any suggestions.

**Comment by imanghafoori1** [comment]
I am aware of the docs and how to proof it with var_dump and etc...
But surprisingly most people do not know it.
I mean why it shouldn't be self documenting and obvious in the first place, the order these methods are called...

I know this change is against the past and now it is very hard to change the method names...
but something to think about.

**Comment by imanghafoori1** [comment]
Even when you create a provider using `make:provider` there is nothing in the doc-blocks about it...
I think the doc-blocks at least can be improved.

![image](https://user-images.githubusercontent.com/6961695/50727305-45e03480-112e-11e9-911f-0dc028d00d50.png)
