### ISSUE TITLE
[Proposal] Allow "app()->build()" to use parameters

### ISSUE THREAD

**Issue by DarkGhostHunter** [laravel/ideas#1476]
The `app()->build()` method is very useful when trying to instance classes that depends on others, without pushing them inside the Service Container, because they're short lived or only work for a single purpose.

```php
<?php

use Illuminate\Contracts\View\Factory as ViewFactory;

class Once
{
    /** @var ViewFactory */
    protected $view;
    
    public function __construct(ViewFactory $view)
    {
        $this->view = $view;
    }
}
```

The problem lies when this class construct expects a parameter not resolvable, like a primitive.

```php
<?php

use Illuminate\Contracts\View\Factory as ViewFactory;

class Once
{
    /** @var ViewFactory */
    protected $view;
    
    /** @var string */
    protected $prependToRenders;

    public function __construct(ViewFactory $view, string $prependToRenders)
    {
        $this->view = $view;
        $this->prependToRenders = $prependToRenders;
    }
}
```

Trying to use `app()->build(Once::class)` will result in a `BindingResolutionException`

```
Unresolvable dependency resolving [Parameter #1 [ <required> $prependToRenders]] in class Once
```

To avoid this, the `build` method should allow additional parameters for these variables that are not instantiable (like a string), like it can be done when using `make()`, allowing for temporal injection of primitives (like strings, ints). 

This method could mimic the functionality given by [`when()`](https://laravel.com/docs/5.7/container#binding-basics).

```php
<?php

$string = '<script>console.log("view.inserted");</script>';

$instance = app()->build(Once::class, ['$prependToRenders' => $string]);
```

**Comment by koenhoeijmakers** [comment]
Could you explain why you _must_ use `build` instead of the `make` method, as `make` just calls `build` when necessary?

**Comment by DarkGhostHunter** [comment]
Holy crap, I really committed to that brain fart. Gonna close this.
