### ISSUE TITLE
[Proposal] onBeforeRender & onAfterRender for views

### ISSUE THREAD

**Issue by rashidlaasri** [laravel/ideas#1479]
#### Proposal:
Adding two events/hooks to the view files to be able to alter the view content before displaying it on the browser.

#### Example of use case:
Search view files for links and append a referral code.

#### Usage Example:

```php
View::onBeforeRender('view-name', function($view) {
    // do something with the view content...

    return $view;
});
```

```php
View::onAfterRender('view-name', function($view) {
    // do something with the view content...

    return $view;
});
```

**Comment by Sladewill** [comment]
Aren't you able to achieve this by changing the way you generate the views in the first place. i.e.

```php
<?php namespace App\Http\Controllers;

class YourController extends Controller {
    function index() {
        // before view render
        $html = view('view-name')->render();
        // after view render
        return $html;
    }
}

**Comment by crynobone** [comment]
https://laravel.com/docs/5.7/views#view-composers

composers is very much archive `onBeforeRender`, I don't know what the use-case for after rendering since the content should basically be `string`.
