### ISSUE TITLE
Respect JsonSerializable for nested objects on JSON output

### ISSUE THREAD

**Issue by kylekatarnls** [laravel/ideas#1481]
Hello, as raised in the issues [#21703](https://github.com/laravel/framework/issues/21703) and [#26313](https://github.com/laravel/framework/issues/26313), the `JsonSerializable` implementations are not respected in nested objects when requesting a `JsonResponse`, for example, date model attributes.

In my opinion, the first problem is here:

```php
protected function addDateAttributesToArray(array $attributes)
{
    foreach ($this->getDates() as $key) {
        if (! isset($attributes[$key])) {
            continue;
        }

        $attributes[$key] = $this->serializeDate(
            $this->asDateTime($attributes[$key])
        );
    }

    return $attributes;
}
```

This is called when toArray() is called, and toArray() is called when jsonSerialize() is.

toArray() should not call `serializeDate()`, it should not convert properties, it should just group them in an array. Then when this array is taken by a JSON process, if a property does not implements `JsonSerializable`, then only at this moment, Laravel should fallback to a default formatting (in this case, the most appropriate format would not be the default format `"Y-m-d H:i:s"` for dates but more likely `"Y-m-d\TH:i:s\Z"` to be read natively by `Date` in JS and use UTC timezone). On an other hand if this array is passed to DB stuff (Eloquent save/QueryBuilder) and there only `getDateFormat()` (and Query Grammar date format) is relevant and can be used to convert date properties.

I can submit a PR for that once we would agree on how to "fix" the `toArray` method output for models.

**Comment by driesvints** [comment]
We're now considering to update the default serialization for both `toArray` and `toJson` to `"Y-m-d\TH:i:s.uP"` (notice the microseconds). This is a better format because consuming clients will immediately now very precisely pointed out timestamps with the timezone.

Any thoughts on that?

**Comment by kylekatarnls** [comment]
If you hardcode `"Y-m-d\TH:i:s.uP"` as date format for models, it may still be divergences with output of dates outside the models in JSON responses:

1. Won't respect `serializeUsing` => not a problem as the method is deprecated for good reason
2. Won't respect `->settings(['toJsonFormat' => $format])`, it's a pretty advanced feature, I guess Laravel models can live without it.
3. Won't enforce UTC: by default `json_encode(Carbon::parse('2000-01-01 00:00:00', 'Europe/Paris'))` outputs: `"1999-12-31T23:00:00.000000Z"`. Not too bad since when you pass it to `new Date()` you get the same date rather you pass `"1999-12-31T23:00:00.000000Z"` or  `"2000-01-01T00:00:00.000000+01:00"` but it's still a difference in the raw output.
4. It can still be a lot of difference if the user used `Date::swap(...)` to extend the `Carbon` class or use an other library.

I think none of those case are blockers. IMO, `"Y-m-d\TH:i:s.uP"` is better than the current format, it would be an improvement with no apparent regressions.

But in order to the issues mentioned above, you may consider using: `json_encode(Date::instance($date))` for any date property of a model when calling `toArray` or `toJson`. Is there something preventing you to do that?

**Comment by driesvints** [comment]
> But in order to the issues mentioned above, you may consider using: json_encode(Date::instance($date)) for any date property of a model when calling toArray or toJson. Is there something preventing you to do that?

No, not at all. The proposed format above was just a first attempt at a new default. Happy to look into what you're suggesting.

**Comment by driesvints** [comment]
Gonna close this one already in favor of https://github.com/laravel/ideas/issues/1940
