### ISSUE TITLE
Filesystem (AWS, Minio)

### ISSUE THREAD

**Issue by EvodiaAut** [laravel/ideas#1484]
Hi can we change in [config/fielsystem:64](https://github.com/laravel/laravel/blob/master/config/filesystems.php#L64) from `url' => env('AWS_URL')` to `'endpoint' => env('AWS_URL')`?
See [laravel/docs/homestead.md](https://github.com/laravel/docs/blame/5.7/homestead.md#L425) there a be the right one.

When you use `url' => env('AWS_URL')` and save a file into the cloud you get
`.....<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided (truncated...)
 InvalidAccessKeyId (client): The AWS Access Key Id you provided does not exist in our records......`

And a minimal wish is we add in s3 key for out of the box use homestead with mino
```
'use_path_style_endpoint' => env('AWS_USE_PATH_STYLE_ENDPOINT', false)
```

**Comment by pedrommone** [comment]
As you can see with the error log, `The AWS Access Key Id you provided does not exist in our records`. So, is a problem in your side, a auth problem.

Anyway, this is not the right channel for questions, you can use Stackoverflow or Laracasts Forum.

**Comment by EvodiaAut** [comment]
And you mean i don't set the access key after this error message? 🤔

I have set all environment variables for use laravel file storage with AWS

```env
FILESYSTEM_DRIVER=s3
AWS_ACCESS_KEY_ID=homestead
AWS_SECRET_ACCESS_KEY=secretkey
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=xxxxx
AWS_URL=http://homestead:9600
```

I think you don't unterstand the issue, it's not a bug report but a request to change the documentation like [laravel/docs/homestead.md ](https://github.com/laravel/docs/blame/5.7/homestead.md#L425).
And can overwrite 'use_path_style_endpoint' for fast usage with Minio


When i set the default config from 'S3' `url' => env('AWS_URL') ` to `'endpoint' => env('AWS_URL')` it works all fine. (**A new laravel user set the config right but get an error because the default config has an error**)

This issue should simplify using laravel with AWS and implementation for Minio.

**Comment by Sladewill** [comment]
It's most likely because minio is AWS compatible bucket but not an actual implementation in laravel. We have used it for a customers setup but we had to do some digging to get this information but that's kinda a nice thing with laravel as you learn more about it by doing this.
