### ISSUE TITLE
Hooks / Container access from migrations

### ISSUE THREAD

**Issue by koenhoeijmakers** [laravel/ideas#1485]
Sometimes you may want to run certain commands / scripts to fix your data when a new table column is added.

Therefore it would be nice either have access to the `Container` from the migration or if that is unwanted to have a `before` and `after` hook that you can register when a given migration is ran (by class name i would say).

**Comment by sisve** [comment]
Couldn't you do the data modification from within the migration itself?

**Comment by koenhoeijmakers** [comment]
In my current case that's a yes i could (although i'd rather keep those scripts by hand), but i believe that there's definitely times where somebody is going to want this.

**Comment by martinbean** [comment]
You don’t need hooks; just run the commands before or after the migration itself:

```php
class CreateSomeMigration extends Migration
{
    public function up()
    {
        // Do what you would do in a before hook here

        Schema::create('foo', function (Blueprint $table) {
            //
        });

        // Do what you would do in an after hook here
    }
}
```

**Comment by deleugpn** [comment]
What's the problem with using the container statically?
