### ISSUE TITLE
[Proposal] Surface subscribers in EventServiceProvider

### ISSUE THREAD

**Issue by Gman98ish** [laravel/ideas#1488]
**Proposal**

Illuminate\Foundation\Support\Providers\EventServiceProvider has a public method listens() which returns all the listener mappings. However, there is no corresponding method for getting all the subscribers. Could add a method `subscribers()` which returns registered subscribers.

**Example of use case:**

Asserting that a subscriber has been registered in testing

**Usage Example:**

```php
/**
 * @test
 */
public function registers_cool_subscriber()
{
    $eventServiceProvider = app(EventServiceProvider::class);

    $this->assertTrue(in_array('App\Subscribers\CoolSubscriber', $eventServiceProvider->subscribers());
}
```

**Comment by yuloh** [comment]
The subscribers aren't stored in the dispatcher, it only stores the listeners that the subscriber registers.  `Dispatcher::getListeners`  will return any listeners the subscriber registers.  For example:

```php
<?php

require __DIR__ . '/bootstrap/app.php';

$subscriber = new class() {
    function subscribe($events) {
        $events->listen('example', function () {});
    }
};

app('events')->subscribe($subscriber);

var_dump(app('events')->getListeners('example')); // returns callable[]
```

Would that work for your use case?

**Comment by Gman98ish** [comment]
Ahh, I totally missed that. Thanks!
