### ISSUE TITLE
[Proposal] return an array of strings from getFacadeAccessor

### ISSUE THREAD

**Issue by imanghafoori1** [laravel/ideas#1490]
Currently Facades will eventually call one method on one object.
![image](https://user-images.githubusercontent.com/6961695/51429143-e51e2500-1c20-11e9-9f43-e02e38f97ead.png)

Maybe we return an array for strings or objects:

![image](https://user-images.githubusercontent.com/6961695/51429150-097a0180-1c21-11e9-8ace-a27f81e6a4e2.png)

or the abstract string can may represent a "tag" on the container so that all the tagged instances get called. ( I think we should return 'tag' from an other method, and not getFacadeAccessor)

It starts to compete with `events` feature which already do the same job, but this can differ from that in the way, that each call is made with the result of the previous call.
> the returned value of `A1` is delivered as parameter to `A2` 
and returned value from `A2` to delivered to `A3`
The final value we get from the Facade call is the return value from `A3`

This is useful to add `preConditions` and `postConditions` to a method call or some how decorate it.
usage example:
- Converting `null` values to `Null objects` (postCondition)
- Normalizing parameters before handing them to the actual Facade (preCondition)

Note that the two cases above do not violate the L in SOLID
so if we apply them to existing Facades used in an app nothing breaks.

**Comment by fletch3555** [comment]
Can you give a concrete example of how this would work? I don't quite understand what you're even suggesting.

**Comment by sisve** [comment]
How would this work with strict type hints for those that are using them?

**Comment by imanghafoori1** [comment]
> How would this work with type hints for those that are using them?

Sorry, but I do not get it exactly.

**Comment by imanghafoori1** [comment]
I tested my implementation with this and it worked for me :

```php
// nomalizer layer
class ParamNormalizer
{
    function __call($method, $params)
    {
        return is_array($params[0]) ? $params[0] : $params;
    }
}
```

```php 

class Calc
{
    function add(array $a)
    {
        return array_sum($a);
    }
}
```

```php
class MyFacade extends \Illuminate\Support\Facades\Facade
{
    protected static function getFacadeAccessor()
    {
        return [normalizer::class, Calc::class];
    }
}
```

```php
MyFacade::add(1,2,3); // 6

MyFacade::add([1,2,3]); // 6

```

**Comment by imanghafoori1** [comment]
maybe we can put an array of `preConditions` and `postConditions` in separate methods.

```php

class MyFacade extends \Illuminate\Support\Facades\Facade
{
    protected static function getFacadeAccessor()
    {
        return Calc::class;
    }

    protected static function getPreFacadeHandlers()
    {
        return [ParamNormalizer::class, ToInt::class,];
    }

    protected static function getPostFacadeHandlers()
    {
        return [...];
    } 
}

```

**Comment by mfn** [comment]
What is the point of all of this, where is to goal to get, what problem is it solving?

How would everyone using the Laravel Framework benefit from this and pre/post conditions?

It adds so much more magic for _what_ exactly?

These ideas don't even sound useful on paper, just confusing (to me). 🤷‍♀️

**Comment by imanghafoori1** [comment]
Let me shed some light on it.
We just want` to add some code to an existing structure or class without changing it.
In this over simplified example the `Calc::class` comes from a library or composer package.
We want to add some behavior to it without changing the actual class.
I my self have needed such a thing in many cases of my day to day work.

It just gives end-users opportunity to have clear code bases and more code reuse.
Laravel itself  has repeated this peace of code through out many places 
`is_array($params[0]) ? $params[0] : $params;`

The other use case is to add postConditions to implement the null object pattern with out tampering with the original classes.

Or Imagine a repository class from a package, you want to fire events before and after the calling methods on the repository, but the package does not do that.

`UserCreated`, `UserCreating`, ... 

Then you can do that use a `post` and `pre` Not condition but `hooks`.

I  think (not every one I know) preConditions are nifty places to add some authorization or validation.

The terms `preConditions` and `postConditions` are coming on my tongue from `Design By Contract` concepts by Bertrand Meyer.

You may spend some time on this page : 

https://en.wikipedia.org/wiki/Design_by_contract

https://github.com/php-deal/framework/wiki

Thanks for attention.

**Comment by martinbean** [comment]
A façade class exists solely to pull something from the service container. That’s why the façade accessor returns a single string: it’s saying what it wants from the container. It has nothing to do with asserting conditions, casting parameters etc. A façade is literally for saying, “Get me [foo] from the container” without having to pass the container around your application.

**Comment by imanghafoori1** [comment]
> A façade class exists solely to pull something from the service container.

No it's not `just` that, obviously.
If you look at it's source code. you can see that you can return an object from the `getFacadeAccessor`.
then it has noting to do with the container and will use that object.

Facade builds many other features around ` pull something from the service container`.
Like aiding `tests`, `making the resolved instance singleton`, `etc`
I do not want to mention them all. you can take a look at the base facade class.

**Comment by martinbean** [comment]
> you can take a look at the base facade class.

@imanghafoori1 I’m familiar with the `Facade` class. I’m also aware that `getFacadeAccessor` should return a string, _not_ an object: https://github.com/laravel/framework/blob/27469f0a700569aa7ee3256c56ad553c96ce34b2/src/Illuminate/Support/Facades/Facade.php#L150

Yes, Laravel façades comes with aids for things like testing and mocking, but it’s primary purpose is to proxy calls to something bound in the container. That’s _why_ it’s called a façade!

**Comment by imanghafoori1** [comment]
@martinbean 
https://github.com/laravel/framework/blob/27469f0a700569aa7ee3256c56ad553c96ce34b2/src/Illuminate/Support/Facades/Facade.php#L165

Take a look at this line and also make a quick check in your application.

```php
class MyFacade extends \Illuminate\Support\Facades\Facade
{
   

    protected static function getFacadeAccessor()
    {
        return new Calc();
    }
}```

**Comment by martinbean** [comment]
@imanghafoori1 If you return an object from the façade, then exactly what is it a façade _for_…?

**Comment by imanghafoori1** [comment]
That feature is removed in 5.8, we can no longer return an object.

Pull request:
https://github.com/laravel/framework/pull/25525
[5.8] Only allow strings for resolving facade roots (#25525)

**Comment by imanghafoori1** [comment]
@martinbean I used that feature to by pass the fact that resolved strings become singletons and stateful.
If you return an object it is not longer memoized and each time you get a new one.

**Comment by martinbean** [comment]
> If you return an object it is not longer memoized and each time you you call your facade you get a new instance.

@imanghafoori1 Not true. It depends how the object has been bound in the container. If it’s been bound as a singleton then calling the façade multiple times will only ever instantiate one instance and return it each time:

![screenshot 2019-01-21 at 14 17 33](https://user-images.githubusercontent.com/167312/51479835-60015000-1d87-11e9-9d26-459d49249208.png)

That was calling `FooFacade::getFacadeRoot()` twice. Notice how both objects have the same ID (`#216`)?

So yeah, I’m struggling to see concisely what it is you’re proposing and what problem it solves.

**Comment by imanghafoori1** [comment]
It seems that you have used app()->make() in the `getFacadeAccessor` and not the `new` keyword yeah ?

**Comment by martinbean** [comment]
> It seems that you have used app()->make() in the getFacadeAccessor and not the new keyword yeah ?

@imanghafoori1 No, I used a façade how it was meant.

I created a service provider and put something in the container:

```php
class FooServiceProvider extends ServiceProvider
{
    public function register()
    {
        $this->app->singleton('foo', function () {
            return new Foo;
        });
    }
}
```

I then created a façade that references this item in the container:

```php
class Foo extends Facade
{
    protected static function getFacadeAccessor()
    {
        return 'foo'; // Key in container
    }
}
```

So now when I use the façade, it’ll resolve the `foo` key from the container, which is a singleton, so the same instance will be returned each time:

```php
$instanceOne = FooFacade::getFacadeRoot();
$instanceTwo = FooFacade::getFacadeRoot();

dd($instanceOne, $instanceTwo);

// $instanceOne and $instanceTwo both point to same instance
```

I think you need to re-visit how façades work, before suggesting overhauling how they’re constructed and what they’re used for.

**Comment by martinbean** [comment]
@imanghafoori1 But you’re then using a façade wrong? 

Again, concisely show the problem and how your idea solves it. If you can do that simply, your ideas might get a bit more support and traction. If you can’t, then you’re going to struggle to convince people a convoluted test case and “fix” is worthwhile.

**Comment by imanghafoori1** [comment]
Here we have ended up with something different than the original title. let's end it up. It's just an idea. I do not get anyone brain to get involved unnecessarily. let's finish it up.
