### ISSUE TITLE
Signal instead of cache in `queue:restart`

### ISSUE THREAD

**Issue by ilyachase** [laravel/ideas#1498]
Hi there!
Currently `queue:restart` command uses cache for signaling running worker to stop. Therefore it forces users to configure cache in some way. Also worker provides requests in cache between every task or sleep delay.
Isn't it more robust and effective to use `pcntl` exntension?
For example, register new handler for `SIGTERM` using `pcntl_signal()`, and instead of getting timestamp from cache, use `pcntl_signal_dispath()`?

Or at least add it as another option (some kind of fallback) if cache isn't configured.

Thoughts?

**Comment by sisve** [comment]
No, 1) pcntl is not available on Windows, 2) pcntl is not available when running in fpm, and 3) pcntl cannot send signals to queue workers on other machines/containers.

What's the usage scenario where you're using the `queue:restart` command without any cache configured? It would technically work with the `file` cache driver too, assuming you are only using a single server.

**Comment by ilyachase** [comment]
> pcntl is not available when running in fpm

I doubt any one will try to run Console command `queue:restart` through fpm :) It seems to be running mainly in CLI mode (where pcntl almost always awailable).

> assuming you are only using a single server.
On a single server pcntl will work just fine.

> What's the usage scenario where you're using the queue:restart command without any cache configured?

My point is to use more appropriate tools to tasks. Your task is to signal running process, and there are process signals right for this.

I got your point, but may be pcntl useful at least when user didn't configured cache at all (and pcntl is awailable)?

**Comment by sisve** [comment]
> I got your point, but may be pcntl useful at least when user didn't configured cache at all (and pcntl is awailable)?

How do we know that the user hasn't configured a cache? The default site template (laravel/laravel) comes with a working cache configuration (for a single server setup). How do we know when a cache isn't configured?

**Comment by deleugpn** [comment]
I wouldn't add more options to the framework if it's not fixing anything. The option being described here relies on a project going out of their way to remove the cache configuration and then set the worker to use signals. Why?

**Comment by ilyachase** [comment]
Okay guys, thanks for explanation :)
