### ISSUE TITLE
Create new method named lastWhere() in Illuminate/Support/Collection

### ISSUE THREAD

**Issue by cocoeyes02** [laravel/ideas#1499]
Hi, I suggest new method in Illuminate/Support/Collection.

In Illuminate/Support/Collection, first() and firstWhere() exists. 
https://github.com/laravel/framework/blob/28cdb6bc2cfd4d802efe5ea7c6e7f7e581163117/src/Illuminate/Support/Collection.php#L723
https://github.com/laravel/framework/blob/28cdb6bc2cfd4d802efe5ea7c6e7f7e581163117/src/Illuminate/Support/Collection.php#L735

Compared to that, last() exists but lastWhere() doesn't exist.
https://github.com/laravel/framework/blob/28cdb6bc2cfd4d802efe5ea7c6e7f7e581163117/src/Illuminate/Support/Collection.php#L973

Why should lastWhere() not exist? For example...

```php
/**
 * Get the last item by the given key value pair.
 *
 * @param  string  $key
 * @param  mixed  $operator
 * @param  mixed  $value
 * @return mixed
 */
public function lastWhere($key, $operator, $value = null)
{
    return $this->last($this->operatorForWhere(...func_get_args()));
}
```

**Comment by derekmd** [comment]
```php
$items->reverse()->firstWhere()
```
