### ISSUE TITLE
[Docs] Cache documentation pages so it can be accessed offline

### ISSUE THREAD

**Issue by rgb-one** [laravel/ideas#1529]
A way to cache the Laravel documentation on the client-side so that it can be accessed offline can be a useful feature.
**DevDocs** illustrates this feature: https://devdocs.io/offline

The [HTML Service Worker API](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API) allows for this functionality as well (Not sure if DevDocs makes use of this as well).

**Comment by chriskonnertz** [comment]
Why not simply downloading the `laravel/docs` repo?  https://github.com/laravel/docs

**Comment by rgb-one** [comment]
And then read the markdown files? That does work but it is not a very elegant solution.

Right now for laravel offline docs, there's: 
- [Zeal](https://zealdocs.org) (I use this)
- [this scrip I made](https://gist.github.com/rgb-one/62a84c04929ba6778c8d1a7a3bd8bf80), (Use to use this)
- DevDocs (has only the API docs)

These are what I know of. And Zeal and the script work well.

But I think offline docs for via laravel.com would be a cool feature. Anyone else find this feature interesting and/or have feedback?

**Comment by drbyte** [comment]
https://kapeli.com/dash provides this and keeps it up to date upon load.

**Comment by rgb-one** [comment]
Yea, Zeal uses the Dash doc set.

**Comment by imliam** [comment]
What's wrong with reading the markdown files? Markdown was designed to be readable, but even so there's an abundance of software out there that lets you read markdown in a pretty view.

You could even just clone [laravel.com](https://github.com/laravel/laravel.com) yourself locally to get the same view as the site if the other options aren't appealing.

**Comment by Sladewill** [comment]
Your browser has the option of saving pages for offline use as well.

**Comment by rgb-one** [comment]
Ok, I'm gonna close this since there are multiple alternatives available. If anyone else has any other offline options still post it.
