### ISSUE TITLE
[Proposal] Migration foreign key class helper

### ISSUE THREAD

**Issue by thattomperson** [laravel/ideas#1547]
adding an overload for `$table->foreign()->references()` to accept a class path

```
$table->foreign('user_id')->references(App\User::class);
```

and internally have the migration just get the key and table from `$model->getKey()` and `$model->getTable()`

**Comment by staudenmeir** [comment]
Please see https://github.com/laravel/framework/issues/26634#issuecomment-441852131 why having external dependencies in your migrations is not ideal. Theoretically, the table name or the primary key could change in the future.
