### ISSUE TITLE
Execute schedule only in CLI mode

### ISSUE THREAD

**Issue by ttimot24** [laravel/ideas#1554]
Hi,

I just realised that if an exception is thrown in Console\Kernel's schedule method then it will affect the website also.

It would be good if you can make the schedule method executed/booted only in CLI mode.

Laravel version: 5.4

**Comment by sisve** [comment]
Laravel 5.4 is really old and no longer supported. Have you tried upgrading to see if this is already resolved?

**Comment by ttimot24** [comment]
@sisve You are right. It works properly in Laravel 5.5. Thanks!
