### ISSUE TITLE
Make `\Illuminate\Database\Connection::$reconnector` injectable

### ISSUE THREAD

**Issue by iainconnor** [laravel/ideas#1557]
Currently, `\Illuminate\Database\Connection::$reconnector` is set via https://github.com/laravel/framework/blob/5.8/src/Illuminate/Database/DatabaseManager.php#L167-L169.

This means that this setting cannot be overridden without first calling `\Illuminate\Database\DatabaseManager::configure`, coupling that override/customization very tightly with the current order of operations and breaking some of the "lazy loading" (in this case, lazy configuration) that the Database component does very nicely.

If `DatabaseManager` had an injectable or settable "default reconnector" (optional, defaulting to the current implementation), then one could override this before actually creating or configuring any connections, keeping the "lazy" aspects in tact, but allowing customization of this functionality.

For clarity's sake, our current use-case for wanting to customize the reconnector is wanting to add a "maximum retries" setting. When experiencing some edge-case database issues, they were exacerbated by the default reconnector "infinitely" trying to reconnect (infinitely in quotes because _eventually_ something times out, but still has the tendency to turn a minor blip into a feedback loop).

**Comment by iainconnor** [comment]
Could be resolved by https://github.com/laravel/framework/pull/27845.

**Comment by staudenmeir** [comment]
Please close the issue.

**Comment by iainconnor** [comment]
Resolved via https://github.com/laravel/framework/pull/27845
