### ISSUE TITLE
[Discussion - Possible Proposal] calling json_encode/json methods on objects/array values in e helper during blade rendering

### ISSUE THREAD

**Issue by surgiie** [laravel/ideas#1563]
Im mostly interested in hearing how viable it is or others thoughts are on calling `json_encode`/ json methods within the `e` helper when it is called in blade rendering on a jsonable/jsonSerializable object or on arrays. 

Currently the e function declaration is:

```php
function e($value, $doubleEncode = true)
{
    if ($value instanceof Htmlable) {
        return $value->toHtml();
    }
    return htmlspecialchars($value, ENT_QUOTES, 'UTF-8', $doubleEncode);
    
}
```
What are your thoughts of making it something along the lines of :

```php
function e($value, $doubleEncode = true)
{
    if ($value instanceof Htmlable) {
        return $value->toHtml();
    }else if ($value instanceof JsonSerializable || is_array($value)) {
        $value =  json_encode($value);
    } elseif ($value instanceof Jsonable) {
        $value = $value->toJson();
    } elseif ($value instanceof Arrayable) {
        $value = json_encode($value->toArray());
    }
    return htmlspecialchars($value, ENT_QUOTES, 'UTF-8', $doubleEncode);
}

```
if the value is jsonable / jsonSerializable or is an array then this change would allow for you to simply just pass a value such as a collection straight into blade brackets and gives you the convenience of not having to worry about having to call `json_encode`/json methods or relying on using the `@json` directive:

```php
{{$collection}}

// vs
@json($collection)  
//or
{{json_encode($collection)}}

```
My thoughts:

Honestly is such a trivial thing, that its not a big deal to just use `@json` directive or calling `json_encode` yourself. Although its convenient, it does introduce unnecessary checks on each call. Im just sharing my thoughts and was curious to see what everyone else thought.  I find that its mostly just a small convenience and may not be worth doing but could be convenient in some cases..

**Comment by sisve** [comment]
Why would you want to move away from `@json`? It's very explicit about what data is returned, while the `{{ }}` tags is only known to provide html-encoded values. When would you want to use this suggested way? Everytime you need json you need to encode the data using json rules, not html rules.

**Comment by surgiie** [comment]
@sisve

Thats a good point. I agree with you and felt the same mostly. I was just curious on others input.
