### ISSUE TITLE
Container should throw or catch ReflectionException

### ISSUE THREAD

**Issue by paul-thebaud** [laravel/ideas#1573]
This issue is creating after discussing it on laravel/framework#27959

When using the `make` method from the `Illuminate\Container\Container` class, if the given `$abstract` does not exists in container, it will try to create a reflection class of it (on line 794). This line can throw a `ReflectionException` if the class does not exits.

I propose to add the `@throws ReflectionException` tag to the concerned methods documentation, or catch the exception when trying to reflect the class.

It is important to notice that the second possibility will create a breaking change since people who are catching `ReflectionException` will loose this exception throwing.

What do you think about this ?

Note : I will soon create a pull-request to catch the exception (I will reference it when created).

**Comment by mfn** [comment]
I stand by my previous comment, see https://github.com/laravel/framework/issues/27959#issuecomment-475359822
> Personally I think it's a nightmare to correctly maintain all the `@throws` and they should just be removed:
> - if it's an exception in the same method, you can usually easily see it yourself
> - if it's deep down, it usually gets out of sync in the docs anyway

In a nutshell, **unless** it's automated I think this is a waste of time because no one is checking callees or parent methods when changing logic i.e. adding/removing exception (explicit or implicit) and **very soon** your nice phpdoc out of sync.

A missing phpdoc is either sad or maybe not necessary because everything is self-documented.

But a wrong phpdoc to me is "useless to harmful" and sometimes just confusing.

**Comment by paul-thebaud** [comment]
@mfn That's why I created a PR for Laravel 5.9, to catch the exception instead of adding it to the method documentation.

**Comment by mfn** [comment]
So what are going for here now? If the PR is merged (LGTM), then this issue here is void, isn't it?

**Comment by paul-thebaud** [comment]
Yes. This issue is to discuss if it is a better idea to catch or add to the documentation the ReflectionException.

**Comment by mfn** [comment]
Ok, thanks for the clarification.

I don't understand what's so important specifically with the Container and the ReflectException.

I bet you will literally hundreds of methods whose throws is non-existent or out of date. What is with them? Are we going to discuss this for each of those methods?

I think there should be a clear guide for the framework what is supposed to be done.

**Comment by paul-thebaud** [comment]
No problem. I open this discussion because I was having a problem with method in particular. But I don't think it always needs a discussion.
It is just about correctly maintening documentation, and for this IDE are useful.

**Comment by paul-thebaud** [comment]
Closing this as laravel/framework#27977 was merged into master.
