### ISSUE TITLE
Accept password value from console

### ISSUE THREAD

**Issue by mnrafg** [laravel/ideas#1574]
It could be better if we had some method when writing Artisan Command such as `$this->askPassword('Type passphrase to run the task')`, because it is necessary if we do want to protect some commands from running by unauthorized parties.

**Comment by thannaske** [comment]
Whoever has access to the system to run a command could just look it up within the command definition itself. Password protected commands don‘t sound very secure for me. Maybe consider running jobs from the webfrontend and allow them to be executed for authenticated users only?

**Comment by mfn** [comment]
This is already possible and documented at https://laravel.com/docs/5.8/artisan#prompting-for-input
```php
$confidentialInput = $this->secret('Your social number, please');
```
