### ISSUE TITLE
"Fake Cron" for development purposes

### ISSUE THREAD

**Issue by alexbowers** [laravel/ideas#1575]
For development purposes, it isn't always ideal to have an actual cron setup every minute to run the `schedule:run` command.

A daemon command in artisan that would trigger that command every minute would be very useful.

I can prepare a PR for this, but unsure whether it would be accepted / whether it belongs in core framework.

**Comment by alexbowers** [comment]
Package released https://packagist.org/packages/alexbowers/laravel-fake-cron

**Comment by josegus** [comment]
Exactly what i need right now, thanks
