### ISSUE TITLE
Optionally disable or reformat the middleware column in route:list

### ISSUE THREAD

**Issue by crashkonijn** [laravel/ideas#1576]
Hi all,

In most of our projects running `route:list` would require you to enlarge your command window quite a bit to be able to see all information correctly, however one of our projects now reached the point where `route:list` doesn't fit on two 1440p screens anymore. I can imagine that with simpler projects `route:list` doesn't fit on a single 1080p screen as well.

I'm not sure how other people use this command but in 99% I only need method, uri & name.

I would like to propose one of the following things:
1. Either add a `--simple` option that only shows those three columns.
2. Add a `--full` option to show all columns and on default only show the other three.
3. Add the option to hide columns
4. What helped to at least fit it on my screen again was to implode the middleware with `\n` instead of `,` when the string was larger than a certain length.

I'm very curious to learn if any one else has run into this problem, and what your thoughts are.

Cheers!

**Comment by 36864** [comment]
For BC reasons, the first or third options would be preferable. Maybe both?

`route:list --simple` could be an alias for `route:list --hide=domain,action,middleware`

**Comment by crashkonijn** [comment]
That sounds like a good idea! I'm curious what other people think before spending time creating a PR.

**Comment by devcircus** [comment]
Make aliases you can use in your terminal for different combinations of columns, like
```
php artisan route:list --columns=method --columns=uri --columns=name --columns=action
```

**Comment by brunogaspar** [comment]
This is already possible on 5.8, i think :)

https://github.com/laravel/framework/pull/25683 added pretty much what's being discussed here, more or less.
