### ISSUE TITLE
dispatchIf helper

### ISSUE THREAD

**Issue by crissi** [laravel/ideas#1587]
A new helper, that make it easy to only fire a job if a condition is true
`dispatchIf(bool $shouldDispatch, $job)`

**Comment by michaeldyrynda** [comment]
Laravel is currently working to remove helpers in the global namespace, not add more.

**Comment by sisve** [comment]
Is it too hard to do it with the existing stuff?

    if ($shouldDispatch) {
        dispatch($job);
    }

**Comment by crissi** [comment]
No not all, I was thinking others might have ran into the same usecase

Få Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: Simon Svensson <notifications@github.com>
Sendt: Thursday, April 4, 2019 8:08:14 AM
Til: laravel/ideas
Cc: Christian; Author
Emne: Re: [laravel/ideas] dispatchIf helper (#1587)


Is it too hard to do it with the existing stuff?

if ($shouldDispatch) {
    dispatch($job);
}
