### ISSUE TITLE
[Proposal] Use onWriteConnection on implicit route model bindings

### ISSUE THREAD

**Issue by tonysm** [laravel/ideas#1592]
I was reading up on this [book](https://adelf.tech/2019/architecture-of-complex-web-applications) and it mentioned an issue I wasn't aware of (if you want to read the problem description in full, check the section `“Rapid” Application Development` in the free sample of the ebook).

Long story short, when you use read/write connections on your database config, you need to avoid using the implicit route model binding entirely on WRITE HTTP requests (not GET|HEAD), because in these kind of requests, chances are you need the most up-to-date version of your data, which comes from the _write_ database connection.

I did some tests locally by:

- Having 2 MySQL databases running (no replication needed for the test)
- Created 2 users, one on each database, so they both have the 1 ID
- Did setup 2 routes `GET /users/{user}` and `POST /users/{user}` so I could test this

Confirmed the "issue".

The alternative solution is simple enough:

```diff
- Route::post('/users/{user}', function (App\User $user) {
+ Route::post('/users/{user}', function ($user) {
-    return $user;
+    return App\User::onWriteConnection()->findOrFail($user);
});
```

But this felt like something we could handle inside the framework itself. This also involves form requests, as you would have to rely on this approach in order to get the resource (instead of simply using `$this->route('resource')`).

If there's interest, I would be more than happy to try to implement this. One possible solution that wouldn't affect any application out there would be to implement another version of the [`SubstitutesBindings`](https://github.com/laravel/framework/blob/e6c8aa0e39d8f91068ad1c299546536e9f25ef63/src/Illuminate/Routing/Middleware/SubstituteBindings.php) middleware that deals with the read/write connection decision, so existing applications would still keep working.

Any thoughts?

**Comment by Sladewill** [comment]
Does this still occur if you don't have closures and use actual controllers.
When you cache the routes in production systems closures shouldn't really be used otherwise it throws an exception about "serializing closure".

**Comment by tonysm** [comment]
> Does this still occur if you don't have closures and use actual controllers.
When you cache the routes in production systems closures shouldn't really be used otherwise it throws an exception about "serializing closure".

Yes, still behaves the same. The problem is not when the route is handled. It's how the implicit route model binding works in the context of having read/write database connections (when you use database replication).

**Comment by deleugpn** [comment]
What's the actual issue?

**Comment by tonysm** [comment]
> What's the actual issue?

The problems are described in the issue with linked reference if you want to dig in further.

---

Anyways, I'll close the issue as it seems relatively easy to implement a custom SubstitutesBinding middleware to always resolve the model binding on write HTTP requests (POST|PUT|DELETE) from the write connection and all.

**Comment by deleugpn** [comment]
I'm still interested in understanding the issue as I have plans to use read/write connections by the end of this year. Your original description says you _confirmed_ the issue by sending 2 GET and 2 POST requests, but I don't understand what issue is that. What is the end result? Why is it an issue? What is the expected behavior? What actually happens?

**Comment by crynobone** [comment]
> Anyways, I'll close the issue as it seems relatively easy to implement a custom SubstitutesBinding middleware to always resolve the model binding on write HTTP requests (POST|PUT|DELETE) from the write connection and all.

Can you share the middleware code here, So far I did experiencing delay between master and slave but didn't use bindings for the route.

On the `POST` method, I would just use `DB::recordsHaveBeenModified(true)` to force all following query to use write connection. Might be useful to see alternative implementation.

**Comment by tonysm** [comment]
Will write about it in a blogpost, will make sure I paste the link here once it's done.
