### ISSUE TITLE
[Proposal] Make some classes final out of the box

### ISSUE THREAD

**Issue by MladenJanjetovic** [laravel/ideas#1594]
It would be nice to follow good practice and make most of the classes final. 
There are several facts that this can improve code quality and make development easier and safer.
Here are some nice reads:
https://ocramius.github.io/blog/when-to-declare-classes-final/
https://matthiasnoback.nl/2018/09/final-classes-by-default-why/

I guess that these classes can be made Final out of the box, and when making them with CLI:

1. Controllers
2. Tests
3. Form Requests
4. Mails
5. Seeders
6. Migrations
7. Resources
8. Middlewares
9. Commands

Just for example, imagine when you want to extend your custom class in IDE and you don't get all of these above listed as autocomplete :)

These are just off the top of my head. I can create PRs for this.
@taylorotwell  Let me know

Best,

**Comment by ludo237** [comment]
Final is a pain in the ass then it comes to tests and mocking stuff

**Comment by MladenJanjetovic** [comment]
@ludo237 I didn't experience that. Can you provide some example please? Tnx

**Comment by srdjanmarjanovic** [comment]
@MladenJanjetovic @ludo237 is right, mocking final classes is not possible with contemporary versions od PHPUnit. See https://github.com/sebastianbergmann/phpunit-mock-objects/issues/388#issuecomment-348478557

**Comment by MladenJanjetovic** [comment]
@srdjanmarjanovic Agree. But when will you mock any of the classes I listed in proposal?

**Comment by taylorotwell** [comment]
If you want to make your own classes final, Laravel gives you the freedom to do that. I think `final` classes make sense in certain scenarios, especially when doing package development and you really want to limit what people can extend and modify.
