### ISSUE TITLE
New Validation Rule: Safe Download Url

### ISSUE THREAD

**Issue by halaei** [laravel/ideas#1607]
Usage: the user enters a url of a photo/music/document, the server download the resource from the given url and show it to the user as a downloadable file ...

Security consideration: users must not be able to fool our server to download something like http://localhost:3000/secret_asset.txt for them.

I am not 100% sure what is the best way to protect against such abuse, but I think the use-case is common and the solution should be publicly available, probably inside laravel.

If the best way is to use a validation rule here is my recommendation:
```php
class ValidateSafeUrl implements Rule
{
    /**
     * @var Validator
     */
    private $validator;

    /**
     * Create a new rule instance.
     *
     * @param Validator $validator
     */
    public function __construct(Validator $validator)
    {
        $this->validator = $validator;
    }
    /**
     * Determine if the validation rule passes.
     *
     * @param  string  $attribute
     * @param  mixed  $value
     * @return bool
     */
    public function passes($attribute, $value)
    {
        // Make sure the url is from an active domain (using active_url validation rule)
        if (! $this->validator->validateActiveUrl($attribute, $value)) {
            return false;
        }
        $host = parse_url($value, PHP_URL_HOST);
        $ip = gethostbyname($host);
        // Don't let the user to send IP addresses
        if ($ip == $host) {
            return false;
        }
        // Make sure the IP address is public 
        // From https://stackoverflow.com/a/13818647/1561026
        return (bool) filter_var(
            $ip,
            FILTER_VALIDATE_IP,
            FILTER_FLAG_IPV4 | FILTER_FLAG_NO_PRIV_RANGE |  FILTER_FLAG_NO_RES_RANGE
        );
    }
}
```
Let me know if there is a better approach to handle this issue.

**Comment by ludo237** [comment]
Technically anything that's not in either the public folder (storage/app/public) or public remote folder (like s3 and such) should be hidden by default

**Comment by halaei** [comment]
> Technically anything that's not in either the public folder (storage/app/public) or public remote folder (like s3 and such) should be hidden by default

@ludo237 I don't think you get my point. I am talking about when a server gets a file from another domain in the web for the user. e.g. Try Google search similar image feature.
![Screenshot_20190417-205829_Chrome](https://user-images.githubusercontent.com/7089140/56304577-a8949380-6153-11e9-85b0-ab806f79e2c9.jpg)

**Comment by halaei** [comment]
Maybe not that common to be in framework
