### ISSUE TITLE
[Proposal] Pre-populated Collection Objects

### ISSUE THREAD

**Issue by PHLAK** [laravel/ideas#1608]
I'd like to be able to define a pre-populated collection class like so:

```php
<?php

namespace App\Collections;

use Illuminate\Support\Collection;

final class States extends Collection
{
    $items = [
        'alabama',
        'alaska',
        'arizona',
        // ...
}
```

And then use it from another file.

```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Collections\States;

class SomeModel extends Model
{
    public function getFirstState() {
        $states = new States();

        return $states->first();
    }

    public function getRandomState() {
        $states = new States();

        return $states->random();
    }
}
```

However due to the way the the `$items` property is initialized in the constructor this is not possible without overriding the Collection constructor. You have to do something like the following:

```php
<?php

namespace App\Collections;

use Illuminate\Support\Collection;

final class States extends Collection
{
    $items = [
        'alabama',
        'alaska',
        'arizona',
        // ...
}

public function __construct()
{
    // Intentionally empty
}
```

I feel like this is ugly and unnecessary code and believe we can solve this without any breaking changes by modifying the Collection constructor to the following:

```php
public function __construct($items = [])
{
    if (! empty($items)) {
        $this->items = $this->getArrayableItems($items);
    }
}
```

This will prevent overriding the default value of the `$items` property when a Collection is instantiated with no value or an empty value. This shouldn't change the default behavior of a Collection since the default value of the `$items` property is already an empty array.

I'm interested in other's opinions and if desired will open a PR for this change.

**Comment by Patryk27** [comment]
What should be outcome of this code?
```php
dump(
  new States(['foo'])
);
```
Because  our version **silently** ignores given items.

Overall, overriding constructor seems more appropriate to me anyway:
1. We won't have to change any existing (and working!) code.
2. You'll be able to manually specify what happens when someone passes arguments to the constructor (or even override the constructor itself).
