### ISSUE TITLE
Ability to flag a user to reset their password on next login

### ISSUE THREAD

**Issue by ryanmortier** [laravel/ideas#1610]
I'm not sure if this should be the responsibility of the developer or if we can have it implemented into the framework but it would be a nice addition to be able to flag a user that they must reset their password the next time they login and then force a log out for that particular user if they are currently logged in.

One situation this would be beneficial is a corporate application where a user is not allowed to register an account. Instead, an administrator creates an account for a user and then we can set a randomized password that is emailed to the new user and they are forced to reset/create a new password upon logging in. Also, I would think that this temporary password that is emailed to them should also expire after a period.

**Comment by ahinkle** [comment]
Sounds like something for userland and not the framework itself.

**Comment by ollieread** [comment]
I'm with @ahinkle, this is most definitely a userland thing.
