### ISSUE TITLE
Query Builder's where() on JSON should be able to search within array of objects

### ISSUE THREAD

**Issue by rennokki** [laravel/ideas#1614]
This is what i found related to my idea: https://stackoverflow.com/questions/38797627/query-a-json-column-with-an-array-of-object-in-mysql

Currently, if I have something like this:
```
id    email          options
1     a@b.com        ["fruits": ["apple","strawberry"]]
```

I can query up based on `fruits`:
```php
$user = User::whereJsonContains('options->fruits', 'apple')->first(); // user found!
```

If i have an array of objects:
```
id    email          options
1     a@b.com        ["fruits": [{"fruit": "apple", "color": "green"}, {"fruit": "strawberry", "color": "red"}]]
```

I am not able to use the same syntax at all:
```php
$user = User::whereJsonContains('options->fruits->fruit', 'apple')->first(); // nope
$user = User::where('options->fruits->fruit', 'apple')->first(); // nope
$user = User::where('options->fruits[]->fruit', 'apple')->first(); // nope
```

Is this doable? Is some kind of limitation within the code that doesn't allow this? I don't find any kind of documentation on this edge case.

**Comment by staudenmeir** [comment]
This works on MySQL and PostgreSQL:

```php
$user = User::whereJsonContains('options->fruits', [['fruit' => 'apple']])->first();
```

**Comment by rennokki** [comment]
I'll give it a try tomorrow. I should have specified i work with pgsql. Maybe this will help me indeed. I'll keep you updated.

**Comment by rennokki** [comment]
It works perfectly! :D
