### ISSUE TITLE
Flatten folder structure (remove resources)

### ISSUE THREAD

**Issue by garygreen** [laravel/ideas#1615]
It would be nice to have a flatter folder structure in Laravel out the box. I've personally gotten rid of the `resources` folder in our Laravel app and flattened it out into:

* css
* js
* views

(`lang` has been put inside `database/lang`, as we don't use it much and seems the most logical place)

This is the flatter folder structure without `resources`:

![image](https://user-images.githubusercontent.com/1702638/56690247-e9048c00-66d4-11e9-8140-f0a16024a79b.png)

Been rocking this folder structure for a long time now and I have to say it's so much more pleasant having instance access to `views` and `js` along with `css`. It may only reduce by one click, but given that developers spend huge amount of time in all of these locations it makes sense to have them more top-level.

These paths can of course already be customised (it's how we're doing it in the first place), and folder structure is a personal thing, but just wondered what you guys think about jiggling things around abit to improve developer experience?

**Comment by mfn** [comment]
I find it neat they're not at the top level.

OTOH I die every time with the Laravel default of placing models into `app/` 🤷‍♀️

**Comment by Sladewill** [comment]
In large applications flatter is nightmarish feel free to lay the stuff out how you want but it seems fine as it is.

**Comment by garygreen** [comment]
Remember when `routes` was buried inside `app\Http`? Or tests in `app/tests`? And `config` in `app/config`? Laravel has already shifted around a lot of stuff to the top-level where it makes sense and it's worked well.

Currently Laravel only has [4 folders](https://github.com/laravel/laravel/tree/v5.8.3/resources) sitting inside resources. You could argue at least 2 of them are "entry" points into your application - `views` and `js` - especially if your application is JS heavy and/or you've got a SPA, or possibly a hybrid approach. Views is the entry point to the visual part of your application, paired with css. `lang` is the odd one out, it's more of a series of configs.

There's definitely a case to be made that they belong more on the top level. It would be *simpler* to reduce the folder structure and allow developers to create their own (if they so desire) generic `resources` folder.

Obviously this is subjective so I'm glad Laravel allows this to be configured, but historically Laravel hasn't been opposed to rethinking the folder structure and jiggle stuff around to where it's made sense.

**Comment by Sladewill** [comment]
Well on the standard boiler plate there are only 4 folders but by the time developers start work sometimes other things go inside that folder as well, it would be an absolute mess then having those in the route folder.

Yes the changes made already are good and make it easier to access certain things that are heavily used like the routes also considering people have more than 1 routes file for web/api etc. But certain things shouldn't be changed and force everyone to do that. By the time you setup laravel you can choose to change the structure to how you want/or make your own branch/copy setup to configure it how you want.

**Comment by mfn** [comment]
> Remember when `routes` was buried inside `app\Http`? Or tests in `app/tests`? And `config` in `app/config`?

Thanks for the perspective! I only knew about `routes`, the other seem to predate my use of Laravel.

**Comment by shez1983** [comment]
i agree about models being placed in app and not app/models by default..
