### ISSUE TITLE
Migrations Squashing Feature

### ISSUE THREAD

**Issue by ziming** [laravel/ideas#1619]
Coming from django previously, I think it will be great if Laravel has a squash migrations feature. So that we don't get into a problem of too many migrations months or years down the road and can freely create migrations without worry

For Django
https://docs.djangoproject.com/en/dev/topics/migrations/#migration-squashing

For Rails
https://github.com/jalkoby/squasher

Thanks!

**Comment by deleugpn** [comment]
Probably a really nice to have but at the same time a hot / hard topic around Laravel.

**Comment by Sladewill** [comment]
We end up having to delete migrations a lot of times because of this as the folder becomes huge. This would be pretty nice, but it would have to order the columns in the migration accordingly.

**Comment by michaeldyrynda** [comment]
Check out the [Snipe migrations package](https://laravel-news.com/snipe-migrations-laravel-package), which will do this for you. 

We’ve implemented similar that essentially runs `migrate:refresh` then `mysqldump`. We then use these dumps in a customised `RefreshDatabase` trait.

**Comment by garygreen** [comment]
A more suitable package would be to use something like this: https://github.com/Xethron/migrations-generator

I mean this is something you can do yourself on a periodic basis. I'm not sure it's something that Laravel should incorporate and maintain out the box.

**Comment by olivernybroe** [comment]
Laravel does have this now btw. 
https://laravel.com/docs/8.x/migrations#squashing-migrations

**Comment by Sladewill** [comment]
I think most of us have seen, but these issues on this repo get left open forever
