### ISSUE TITLE
[Proposal] Authorization routes configurable via environment file

### ISSUE THREAD

**Issue by ryancco** [laravel/ideas#1621]
Laravel allows customization of the following additional routes when registering auth routes:
 - /register (registration routes)
 - /reset (password reset routes)
 - /verify (email verification routes)

This is done so through an optional array passed to Auth::routes()
https://github.com/laravel/framework/blob/fac363d281ed47a4db161072ade1446de096c72d/src/Illuminate/Routing/Router.php#L1157-L1170

The end result may look something like this in your routes file:

```php
\Illuminate\Support\Facades\Auth::routes([
    'register' => false,
    'verify' => true,
]);
```

### What's the issue?
More often than not I find myself configuring these attributes on a per-environment/conditional basis. Sure, open registrations, password reset, or email verification may be off for an application in  production or while the application is in an invite-only state. However, in development, and even possibly staging, those may (and probably should) all be on. This currently requires code changes in those environments or while changing state of the application.

### Proposal
By updating `config/auth.php` to have an additional configuration item, we can drop the parameter from the above mentioned `auth()` method (and the facade) and update `Router::auth()` to rely on the environment file for overwrites where needed.

```php
// config/auth.php
return [
    ...
    'routes' => [
        'register' => env('AUTH_ROUTE_REGISTER', true),
        'reset' => env('AUTH_ROUTE_RESET', true),
        'verify' => env('AUTH_ROUTE_VERIFY', false)
    ]
];
```

```php
// Illuminate/Routing/Router.php
public function auth()
{
    // Authentication Routes...
    $this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
    $this->post('login', 'Auth\LoginController@login');
    $this->post('logout', 'Auth\LoginController@logout')->name('logout');
    // Registration Routes...
    if (config('auth.routes.register')) {
        $this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
        $this->post('register', 'Auth\RegisterController@register');
    }
    // Password Reset Routes...
    if (config('auth.routes.reset')) {
        $this->resetPassword();
    }
    // Email Verification Routes...
    if (config('auth.routes.verify')) {
        $this->emailVerification();
    }
}
```

If this is seen as a conveniency worth pulling in, I'm more than willing to draft up a PR as well. Thanks!

**Comment by thannaske** [comment]
Just wondering if it would it be an option for you to call `Auth::routes()` depending on the current environment? Making it depend on the .env file doesn‘t seem to make sense to me as you won‘t change the values throughout. If your app is invitie-only it usually will be for a longer period.

**Comment by ryancco** [comment]
> Just wondering if it would it be an option for you to call Auth::routes() depending on the current environment?

Currently the work-around I've found is implementing the above changes to the `config/auth.php` file and registering auth routes with `Auth::routes(config('auth.routes'));`. Assuming this, or similar, is what you meant, it's of course possible but this comes at the expense of additional logic that I'd like to think could be remedied by being pulled into the framework if enough people could make use of it.

> Making it depend on the .env file doesn‘t seem to make sense to me as you won‘t change the values throughout.

Not entirely sure what you mean by this.

>If your app is invitie-only it usually will be for a longer period.

While this doesn't address the other, primary use case (production vs stage vs development), whether invite only lasts a day, week or month it requires a code change and to redeploy when switching states.

**Comment by thannaske** [comment]
> Currently the work-around I've found is implementing the above changes to the config/auth.php file and registering auth routes with Auth::routes(config('auth.routes'));

What I meant was something like this:

routes.php
```
if (App::environment(['local', 'staging'])) {
    // Auth::routes() that enables registration routes
} else {
    // Auth::routes() that disables registration routes
}
```

> Not entirely sure what you mean by this.

You need to see behind the reasons why Laravel is even using .env files for some configuration values. Take the mail settings as example: They need to be different in different environments for testing purposes, they can change over the time and you won't want to re-deploy your application just because the API token for your outgoing mail provider changed. Variables that live in the .env files must be somewhat dynamic to change without changing code itself. They are not controlling any functionality of the code. If you start adding configuration- or even environment-variables for controlling Framework behavior you are moving away from the code-centric approach of Laravel.

Therefore - in my opinion - the approach to control Auth::routes()' behavior via .env files or even configuration variables is a little too specific to be implemented for the broad range of developers.

**Comment by martinbean** [comment]
```php
Auth::routes([
    'register' => app()->environment('production'), // true if production, false if other
]);
```

**Comment by thannaske** [comment]
Even better.

**Comment by ryancco** [comment]
> What I meant was something like this:
> 
> routes.php
> 
> ```
> if (App::environment(['local', 'staging'])) {
>     // Auth::routes() that enables registration routes
> } else {
>     // Auth::routes() that disables registration routes
> }
> ```

This would be another, sure. But what this doesn't address, for instance, would be email verification routes being off by default. Which I may want off in production under certain circumstances, and on in development.

> You need to see behind the reasons why Laravel is even using .env files for some configuration values. Take the mail settings as example: They need to be different in different environments for testing purposes, they can change over the time and you won't want to re-deploy your application just because the API token for your outgoing mail provider changed. Variables that live in the .env files must be somewhat dynamic to change without changing code itself. They are not controlling any functionality of the code. If you start adding configuration- or even environment-variables for controlling Framework behavior you are moving away from the code-centric approach of Laravel.

This is exactly what I'm trying to target, is deploying less often due to frequently changing environment variables. Currently, when I want to take an application out of "invite-only" (registration is disabled) mode, if I had not implemented any workarounds, I would need to push a code change to allow `/register` (on by default - remove any directive) and `/verify` (off by default - add additional directives) routes. If I then want to re-enable registration, I need to push a code change to disallow `/register` (on by default - add additional directives) and `/verify` (off by default - remove any directive). 

Also, once this code change to allow or disallow is currently set to "disallow", any developers on the project need to make that _temporary_ alteration in their development environments.

If this functionality responded to the environment variables this would be a seamless process. I appreciate the example workarounds, and I definitely agree there are a bunch of ways to reach the same end result, but my question is more of whether or not this fits enough people's use cases to make it worth considering being pulled into the core of the framework.

**Comment by drbyte** [comment]
Lots of great suggestions here, including creative alternatives. Definitely worth capturing some of them in a blog post or other ideas-sharing repository.

While I completely understand the pain of pushing code changes for things that should be a simple switch, I feel like `.env` is the wrong place to put this sort of switch. To me it feels like that sort of feature switch should be in userland ... a setting that can be controlled in-app. Granted, I realize some apps don't have control panels with such switches/controls, and in that case, your customized code to leverage the use of .env settings for your own situation makes sense, but would still be an app-specific implementation, not the framework.

Just my 2 cents' worth.

**Comment by ryancco** [comment]
> Lots of great suggestions here, including creative alternatives. Definitely worth capturing some of them in a blog post or other ideas-sharing repository.
> 
> While I completely understand the pain of pushing code changes for things that should be a simple switch, I feel like `.env` is the wrong place to put this sort of switch. To me it feels like that sort of feature switch should be in userland ... a setting that can be controlled in-app. Granted, I realize some apps don't have control panels with such switches/controls, and in that case, your customized code to leverage the use of .env settings for your own situation makes sense, but would still be an app-specific implementation, not the framework.
> 
> Just my 2 cents' worth.

That's fair, and my approach up until now. I definitely agree if this is a narrow enough use case (as it seems to be) I'll keep the solution in user land code when and where I run into it. I was, or still am, hoping I wasn't the only one running into this frequently enough to see it as a convenience worth having out of the box. But, not a big deal if not.

**Comment by martinbean** [comment]
I’m not a fan of my code behaving differently depending on what environment it’s in. It can lead to some interesting bugs.

If you want to register users whilst the application is invite-only, then you could just create a console command that does just that.
