### ISSUE TITLE
[Proposal] Use statements grouped for all namespaces.

### ISSUE THREAD

**Issue by ecreeth** [laravel/ideas#1625]
The purpose of this is to start using grouped usage statements throughout the framework.

#### From
```
use Illuminate\Support\Str;
use Opis\Closure\SerializableClosure;
use Illuminate\Support\ServiceProvider;
use Illuminate\Queue\Connectors\SqsConnector;
use Illuminate\Queue\Connectors\NullConnector;
use Illuminate\Queue\Connectors\SyncConnector;
use Illuminate\Queue\Connectors\RedisConnector;
use Illuminate\Contracts\Debug\ExceptionHandler;
use Illuminate\Queue\Connectors\DatabaseConnector;
use Illuminate\Queue\Failed\NullFailedJobProvider;
use Illuminate\Contracts\Support\DeferrableProvider;
use Illuminate\Queue\Connectors\BeanstalkdConnector;
use Illuminate\Queue\Failed\DatabaseFailedJobProvider;
```
#### To
```
use Opis\Closure\SerializableClosure;
use Illuminate\Support\{ Str, ServiceProvider };
use Illuminate\Contracts\Debug\ExceptionHandler;
use Illuminate\Contracts\Support\DeferrableProvider;
use Illuminate\Queue\Failed\{ NullFailedJobProvider, DatabaseFailedJobProvider };
use Illuminate\Queue\Connectors\{ SqsConnector, NullConnector, SyncConnector, RedisConnector, DatabaseConnector, BeanstalkdConnector };
```

**Comment by rs-sliske** [comment]
Laravels code style is to have them sorted by length

**Comment by ecreeth** [comment]
I agree that the functionality is the same. But, from my point of view, the code is cleaner and more eloquent. This feature was added in https://wiki.php.net/rfc/group_use_declarations PHP 7.0 and we are currently using Laravel version 7.1.3 of php. So there would be no changes 
> Laravels code style is to have them sorted by length, and from the various prs trying to reorder them being closed i wouldnt expect that to change, i also dont see a strong reason to change it, the top one looks cleaner to me, and both have exact same functionality

**Comment by mfn** [comment]
Sorting by length is horrible.

Grouping is even worse, say goodbye finding _something_.

The most usable option is to sort alphabetically. There's a reason a telephone book is sorted that way 🤷‍♀️
