### ISSUE TITLE
Ideas github "maintenance" bot

### ISSUE THREAD

**Issue by garygreen** [laravel/ideas#1634]
This repository get's pretty large full of ideas, some liked, some disliked by developers.

Would it be a good idea to have some kind of maintenance bot that periodically goes thru the repository and closes any ideas that it deems to be overwhelmingly disliked by developers? Plus add popularity labels to the remaining ones that are popular?

### Closing Criteria

So the closing criteria would be:

1. Idea is 3 months or older
2. The like/dislike percentage is 40% - so if more than 40% of developers disliked the idea then the idea is closed OR the idea received less than 3 like votes.

The idea would be closed describing the reason why with a friendly template. The developer can then decide whether to re-submit a new idea with fresh information/different strategy or accept that it's not popular and move on.

### Popularity Labels

The bot can also be responsible for adding popularity labels, as a way of gauging which of the remaining open ideas are considered "hot" by developers. These could be a gauge based on hotness:

* Fire 🔥 >= 90% likes
* Hot 🌶 >= 70% likes
* Warm ☕ >= 60% likes

(numbers are provided as examples, they can be tweaked)

### Why is this a good idea?

I think this would add a lot more value to this repository because then you can actually see what ideas are potential good candidates to be included in core as they are liked by a lot of developers.

This repository will no longer be seen as just a "junk yard" to store ideas that never make any traction/receive much love; instead it'll become a tangible place to express your ideas with feedback from the community and provide a clearer indication of what features developers want to see. It'll also encourage more developers to come here and vote on ideas.

### So what's your vote?

Obviously this is going to be up to @taylorotwell to decide if he's willing to let a bot be built and roam freely on this repository. But assuming this idea is received well then hopefully taylor would be up for it too.

**Comment by sisve** [comment]
This would also imply that we need to re-evaluate closed issues. We have a lot of well-supported old issues that has been summarily closed down, some even with an comment indicating that it was a good idea.

https://github.com/laravel/ideas/issues/783
https://github.com/laravel/ideas/issues/709
https://github.com/laravel/ideas/issues/497
https://github.com/laravel/ideas/issues/464
https://github.com/laravel/ideas/issues/431
https://github.com/laravel/ideas/issues/347

**Comment by garygreen** [comment]
Sure, it would make sense to resurrect old popular ideas. Those issues were closed by Taylor without much consideration - but there lies the problem. 

This repository is so large and full of ideas it's impossible for one person to realistically spend time analyzing all the details and deciding if it's a good idea or not. The ideas just grow and grow and soon you just end up with *noise* that becomes difficult to make any meaning of.

Periodically Taylor has gone thru and cleaned up the repository, but the last ["mass exodus"](#1051) of closing down ideas came without much care and even with comments indicating it's good idea, as you say. That would less likely happen with a bot that has specific criteria that can tag issues with meaningful labels to indicate popularity, PR welcome, etc.
