### ISSUE TITLE
JsonResponse for ForgotPasswordController and ResetPasswordController

### ISSUE THREAD

**Issue by blinkofaneye** [laravel/ideas#1638]
The methods in *Illuminate\Foundation\Auth\SendsPasswordResetEmails* and *Illuminate\Foundation\Auth\ResetsPasswords* which return the response in those two traits are labeled as returning a RedirectResponse OR JsonResponse but it's not the case, they always return a RedirectResponse. I will be glad to submit a PR but i wanted to ask first if that is a good idea.

## On error it will return:
419 status code

```json
{ "message" : "An error occured", "error" : { "email" : ["error message"] }}
```

## On success:
200 status code

```json
{ "message" : "success message" }
```

**Comment by musou1500** [comment]
I think it's handy to add default JSON response for case the client expects JSON.

```php
    protected function sendResetLinkFailedResponse(Request $request, $response)
    {
        return $request->expectsJson()
          ? abort(422, 'An error occured')
          : back()
              ->withInput($request->only('email'))
              ->withErrors(['email' => trans($response)]);
    }
```
