### ISSUE TITLE
Add do_safely() helper

### ISSUE THREAD

**Issue by Imangazaliev** [laravel/ideas#1643]
```php
<?php

/**
 * @param  Closure  $callback
 * @return void
 */
function do_safely(Closure $callback): void
{
    try {
        $callback();
    } catch (\Throwable $exception) {
        report($exception);
    }
}

```

This helper may be useful in cases when occurred exception shouldn't interrupt the request. For example, if I send notification about a new user to Discord via [laravel-notification-channels/discord](https://github.com/laravel-notification-channels/discord), it may throw an exception and the user will get a server error. Using `do_safely()` helper I can do this:

```php
do_safely(function () use ($user) {
    $discordChannel = new NewUsersChannel();

    $discordChannel->notify(new NewUserRegistered($user));
});
```

**Comment by Patryk27** [comment]
It could be improved a bit by doing `return $callback();`, but overall I'm not sure about the concept - it's another helper function, which we're rather trying to get rid of + it effectively saves just _one_ line.

**Comment by Imangazaliev** [comment]
> It could be improved a bit by doing return $callback();

I thought about that, but what value it should return if an exception was thrown? null? But what if null is a correct value for the callback?

**Comment by mfn** [comment]
Also: no new global helpers for Laravel

**Comment by crynobone** [comment]
Check on `rescue()` helper.

**Comment by Imangazaliev** [comment]
@crynobone thank you :)
