### ISSUE TITLE
[Proposal] Accept model instance in relationships declaration methods

### ISSUE THREAD

**Issue by jucau** [laravel/ideas#1652]
Currently we have to fill relationships methods with string as first argument : 

```$this->belongsTo(Customer::class);```

Behind, in HasRelationships trait, every relationships methods get the `$related` parameter and instanciate the appropriate class. For example, here is the `belongsTo` method : 

```
public function belongsTo($related, $foreignKey = null, $ownerKey = null, $relation = null)
{
    if (is_null($relation)) {
        $relation = $this->guessBelongsToRelation();
    }

    $instance = $this->newRelatedInstance($related);

    if (is_null($foreignKey)) {
        $foreignKey = Str::snake($relation).'_'.$instance->getKeyName();
    }

    $ownerKey = $ownerKey ?: $instance->getKeyName();

    return $this->newBelongsTo(
        $instance->newQuery(), $this, $foreignKey, $ownerKey, $relation
    );
}
```

`newRelatedInstance()` is returning the class object : 

```
protected function newRelatedInstance($class)
{
    return tap(new $class, function ($instance) {
        if (! $instance->getConnectionName()) {
            $instance->setConnection($this->connection);
        }
    });
}
```

For one particular project, I have to set the table name dynamically (I have one table for writing and one view for reading). Everything works fine with minimum code, thanks to global scope and "retrieved" event. But for relationships, cannot choose the relation table to look in. I have to override or copy all core relationships methods to get what I want : 

```
public function belongsTo($related, $foreignKey = null, $ownerKey = null, $relation = null)
{
    if (is_null($relation)) {
        $relation = $this->guessBelongsToRelation();
    }

    $instance = $this->newRelatedInstance($related);

    // Override
    $instance->setTableForReadOperations();

    if (is_null($foreignKey)) {
        $foreignKey = Str::snake($relation).'_'.$instance->getKeyName();
    }

    $ownerKey = $ownerKey ?: $instance->getKeyName();

    return $this->newBelongsTo(
        $instance->newQuery(), $this, $foreignKey, $ownerKey, $relation
    );
}
```

Wouldn't it make sense to have the ability to provide an already instantiated model class to relation ? that would give the possibility to set a custom table name (or connection) before loading the relationship. It seems we just have to make `newRelatedInstance()` accepting string or Model instance.

I can eventually submit a PR for that.

**Comment by staudenmeir** [comment]
Related: https://github.com/laravel/framework/issues/27278

**Comment by driesvints** [comment]
Going to close this since the pr for it was rejected and taylor made it clear that this won't be supported.
