### ISSUE TITLE
Eloquent model translation

### ISSUE THREAD

**Issue by SzabZol** [laravel/ideas#1663]
Have you ever thought of Eloquent model translation?

**Comment by Patryk27** [comment]
What do you mean by `Eloquent model translation`?

**Comment by SzabZol** [comment]
I mean, when my model has e.g. a description or name attribute and I want to store and use it in different languages depending on user preference.

So you know what I mean? :)

**Comment by Patryk27** [comment]
Ok, this kind of translation - so now comes the second part: what do you mean by `have you ever thought`?

Obviously _somebody_ at least once thought, since otherwise we wouldn't have packages like [laravel-translatable](https://github.com/spatie/laravel-translatable).

**Comment by SzabZol** [comment]
Actually, I would only be interested in why this is not included in the framework default, like file-level localization. And is there any chance that the Laravel framework will have it's own built-in solution for that? Thank you for your answers! :)

**Comment by Patryk27** [comment]
Most likely it's not included in the core, because proper i18n is a quite hard, with no one-fits-all solution - also: there's no reason for the core to be bloated, since at any time you can just do `composer install laravel-somePackageNameHere` and have the translations anyway.

**Comment by SzabZol** [comment]
I see :) Only because file-level localization are there.
Thank you for your answers.
