### ISSUE TITLE
A new Collection function named allContain

### ISSUE THREAD

**Issue by kevinb1989** [laravel/ideas#1671]
There are a lot of use cases that I need to make sure all items in a collection to meet a condition. I have been thinking about a new function named allContain. For example.

```php
$allDelivered = $order->stockItems->allContain(function ($stockItem) {
    return $stockItem->delivered();
});

if ($allDelivered) {
    Mail::queue(new YourOrderHasBeenDelivered($order));
}
```

Or in an even simpler form with higher order message.

```php
if ($order->stockItems->allContain->delivered()) {
    Mail::queue(new YourOrderHasBeenDelivered($order));
}
```

I can create a macro for that. But I think that function deserve to be in the core.

**Comment by sisve** [comment]
This already exists in the every() method.

    $allDelivered = $order->stockItems->every(function ($stockItem) {
        return $stockItem->delivered();
    });

**Comment by kevinb1989** [comment]
Great! Thanks.
