### ISSUE TITLE
[Proposal] Re-order toArray() method so that data shows last

### ISSUE THREAD

**Issue by CharlieBrownCharacter** [laravel/ideas#1678]
**Problem**
Being a back-end developer it is a pain in the ass having to scroll down the x number of records in the data so that I can see the rest of the response in a paginated response. 

**Solution**
Re-order the `toArray()` method in `Paginator.php` so that the `data` property appears last

```
/**
     * Get the instance as an array.
     *
     * @return array
     */
    public function toArray()
    {
        return [
            'current_page' => $this->currentPage(),
            'data' => $this->items->toArray(),
            'first_page_url' => $this->url(1),
            'from' => $this->firstItem(),
            'next_page_url' => $this->nextPageUrl(),
            'path' => $this->path,
            'per_page' => $this->perPage(),
            'prev_page_url' => $this->previousPageUrl(),
            'to' => $this->lastItem(),
        ];
    }
```

to 

```
/**
     * Get the instance as an array.
     *
     * @return array
     */
    public function toArray()
    {
        return [
            'current_page' => $this->currentPage(),
            'first_page_url' => $this->url(1),
            'from' => $this->firstItem(),
            'next_page_url' => $this->nextPageUrl(),
            'path' => $this->path,
            'per_page' => $this->perPage(),
            'prev_page_url' => $this->previousPageUrl(),
            'to' => $this->lastItem(),
            'data' => $this->items->toArray(),
        ];
    }
```

**Comment by mfn** [comment]
The current order is alphabetically and is the only one which doens't need any explanation.

Any deviation from that is wild game and may invite anyone to change it anytime… the code should have at least a comment then.

I do get your idea but there's also the fact that when serialization such a thing to e.g. JSON, order is thrown out of the window that very moment (PHP will still keep the order from the source but others won't necessarily).
