### ISSUE TITLE
[Proposal] Collection::keyByValue()

### ISSUE THREAD

**Issue by AndrewFeeney** [laravel/ideas#1684]
Would you consider mergine a `keyByValue()` method on the collection class?

This:

```php
collect(['ham', 'sandwich'])->keyByValue()->toArray();

// Expression equals ['ham' => 'ham', 'sandwich' => 'sandwich'];
```
Would be equivalent to this:

```php
collect(['ham', 'sandwich'])->keyBy(function ($value) {
    return $value;
});

// Expression equals ['ham' => 'ham', 'sandwich' => 'sandwich'];
```

I find myself often needing to do this, and it would save this repetitive boilerplate. If so I'll put in a PR.

**Comment by AndrewFeeney** [comment]
I suppose `Collection::flip()` would achieve something similar, though less expressively, or readably in my opinion.

**Comment by fletch3555** [comment]
Seems simple enough... Not sure how much discussion this would generate.  Might as well just PR it

**Comment by AndrewFeeney** [comment]
Associated PR:

https://github.com/laravel/framework/pull/28885

**Comment by jycr753** [comment]
what use cases does this have? it seems to create redundant data

**Comment by Sladewill** [comment]
Can't you just use the php function array_combine($keys, $values); without having to overcomplicate things.

**Comment by martinbean** [comment]
> what use cases does this have? it seems to create redundant data

@jycr753 So you’ve _never_ sorted an array by its keys?

**Comment by AndrewFeeney** [comment]
> Can't you just use the php function array_combine($keys, $values); without having to overcomplicate things.

@Sladewill Sure I could, but to me at least this doesn't really fit with the expressive flow of collection pipelines, and wouldn't really be any better than just calling `keyBy()` with a callback.

> what use cases does this have? it seems to create redundant data

@jycr753 I take your point, but I'm not using it to create redundant data. it's something I would always use in combination with a map, e.g.

``` php
    collect(['ham', 'spam', 'lamb'])->keyByValues()->map(function ($meat) {
        return $this->meatClassifier->classify($meat);
    })->toArray();
    
    // Expression equals
    [
        'ham' => [
            'isDelicious' => true,
            'isNutritious'=> false,
        ],
        'spam' => [
            'isDelicious' => false,
            'isNutritious'=> false,
        ],
        'lamb' => [
            'isDelicious' => true,
            'isNutritious'=> true,
        ],
    ];
```

Anyway, the PR was closed by Taylor. Understandably as this method probably doesn't create much value for many people. Thanks all for your input.
