### ISSUE TITLE
[Proposal] Artisan command for a blank class

### ISSUE THREAD

**Issue by b3ndoi** [laravel/ideas#1686]
It would be nice if you didn't have to use the `php artisan make:model {{modelName}}` command for creating a blank class which I find myself doing multiple time only so that you have to strip it to the structure of a blank class. So I propose that the Laravel project comes with a `make:class` command so that you can generate classes on the fly and start implementing your custom functionality immediately. The stub would be almost identical to the model stub
#### Example
```php
<?php

namespace DummyNamespace;

class DummyClass
{
    //
}
```
PS.
I know it could be done with a snippet but it could be nice to give the functionality out of the box.

**Comment by nunomaduro** [comment]
Thanks for this proposal. Personally, I don’t see the value on having this on artisan. I wouldn’t use it for creating a new class. 😕

**Comment by chriskonnertz** [comment]
This is what the PhpStorm IDE creates if you use the `"New" -> "PHP File"` command: 

```php
<?php


namespace DummyNamespace;


class DummyClass
{

}
```

**Comment by ludo237** [comment]
Any editor/IDE can let you use keyboard shortcuts for that....
