### ISSUE TITLE
Why model becomes dirty when the original attributes hasn't?

### ISSUE THREAD

**Issue by kalesh13** [laravel/ideas#1706]
I have a scenario where I have to set attributes to model instance that are not in the database. Everything works fine if I don't have to update the model.

When I update the model, these new attributes are also added to the query. As these attributes are not present in the database, it throws an error.

This is where the attributes that needs an update is checked for. 

```
public function getDirty()
    {
        $dirty = [];

        foreach ($this->getAttributes() as $key => $value) {
            if (! $this->originalIsEquivalent($key, $value)) {
                $dirty[$key] = $value;
            }
        }
        return $dirty;
    }
```

And the code given below is where I suggest an update

```
public function originalIsEquivalent($key, $current)
    {
        if (! array_key_exists($key, $this->original)) {
            return false;
        }
       // other conditions
   }
```

Why is a model considered dirty if an attribute exists in `$this->attributes` and does not exist in the array `$this->original`? The update query should have only the attributes in the `$this->original` array. What above code does is, adding all the model attributes (including the dynamically added attributes) to the update query if it does not exist in `$this->original`.

Or, is there any specific reason why it is coded like this.

My suggestion is to update the code to 

```
public function originalIsEquivalent($key, $current)
    {
        if (! array_key_exists($key, $this->original)) {
            return true;
        }
       // other conditions
   }
```

**Comment by mfn** [comment]
Eloquent models have no knowledge about the database, thus they don't know what columns are available.

It's perfectly valid to _partially_ select a model (i.e. only a few columns) and still *set* a column which was not selected => the should still be saved to the database.

I believe your suggestion would break that.

**Comment by ollieread** [comment]
It very much sounds like you're in need of the `$fillable` property on the model. As mentioned above, it's entirely possible to retrieve a partial result, or even a result with some dynamic values, which would be added to the `$attribute` property.

The `$fillable` property is designed to specify only the columns that can be persisted to the database. Look at 'Mass Assignment' [here](https://laravel.com/docs/5.8/eloquent#inserting-and-updating-models).

**Comment by kalesh13** [comment]
`$fillable` and mass assignment was not what my use case needed. Say, I have a `User` table with only the most frequently accessed fields like `id, email, password, remember_token` as columns and another table with `UserData` with 3 columns namely `user_id, property_key, property_value`. The `UserData` table holds around 20 to 30 properties of a single user like `dob, first_name, last_name` etc

`User` has a `hasMany` relationship with `UserData`. Initially I was doing the property assignment as shown below

```
$userDatas = $user->userData;

foreach($userDatas ?: [] as $userData) {
    // property_key can be dob, first_name, last_name etc. The 20 to 30
   // properties that I mentioned earlier

   $user->{$userData->property_key} = $userData->property_value;
}
```
The above code does work if we are just retrieving the data and no updates are done on the `$user` model after the initialization.

That's when I dig deeper into Laravel codebase to find why it was throwing error.

The concerns raised https://github.com/laravel/ideas/issues/1706#issuecomment-508960938 was valid. So I had to come up with a solution for this use case.

I created a trait

```
trait HasAdditionalProperties
{
    /**
     * The model's additional properties.
     *
     * @var array
     */
    protected $additional_properties = [];

    /**
     * Set an additional attribute to the model.
     *
     * @param  string  $key
     * @param  string  $value
     * @return mixed
     */
    public function setAdditionalProperty($key, $value)
    {
        $this->additional_properties[$key] = $value;

        return $this;
    }

    /**
     * Get an additional attribute from the model.
     *
     * @param  string  $key
     * @return mixed
     */
    public function getAdditionalProperty($key)
    {
        if (!$key) {
            return;
        }

        if (array_key_exists($key, $this->additional_properties)) {
            return $this->getAdditionalPropertyValue($key);
        }
    }

    protected function getAdditionalPropertyValue($key)
    {
        if (isset($this->additional_properties[$key])) {
            return $this->additional_properties[$key];
        }
    }

    /**
     * Get an attribute array of all arrayable attributes.
     *
     * @return array
     */
    protected function getArrayableAttributes()
    {
        return $this->getArrayableItems(array_merge($this->getAttributes(), $this->additional_properties));
    }

    /**
     * Dynamically retrieve attributes on the model.
     *
     * @param  string  $key
     * @return mixed
     */
    public function __get($key)
    {
        if (array_key_exists($key, $this->additional_properties)) {
            return $this->getAdditionalPropertyValue($key);
        }
        return parent::__get($key);
    }
}
```

Added this trait to `User` model (models which have similar property tables) and updated the property assignment code like

```
$userDatas = $user->userData;

foreach($userDatas ?: [] as $userData) {
    // property_key can be dob, first_name, last_name etc. The 20 to 30
   // properties that I mentioned earlier

   $user->setAdditionalProperty($userData->property, $userData->property_value);
}
```
Hope this  helps someone.
