### ISSUE TITLE
[Proposal] Remove Policy stub's HandlesAuthorization trait

### ISSUE THREAD

**Issue by green-mike** [laravel/ideas#1709]
```
php artisan make:policy 
```
Generated policy with HandlesAuthorization that contain allow and deny function. 
```php
<?php

namespace App\Policies;

use App\User;
use Illuminate\Auth\Access\HandlesAuthorization;

class TestPolicy
{
    use HandlesAuthorization;

```

But Gate allow or deny request just use gate's function.
```php

class Gate implements GateContract
{
   use HandlesAuthorization;
    ...
    public function authorize($ability, $arguments = [])
    {
        $result = $this->raw($ability, $arguments);

        if ($result instanceof Response) {
            return $result;
        }

        return $result ? $this->allow() : $this->deny();
    }
```

The stub's trait is useless and confusing. 
It make me assume that I can change response by overwrite deny function until tracing source.

thanks for watching :)

**Comment by garygreen** [comment]
The primary purpose of `HandlesAuthorization` is so you can return deny messages/reasons from your policy:

```
if ($user->banned) {
   return $this->deny('Cannot do this because user is banned.');
}
```

It's an optional feature. In Laravel 5.9 you can remove the trait and use the `Response` object directly, along with sending an error code if you wish:

```php
if ($user->banned) {
   return \Illuminate\Auth\Access\Response::deny('Cannot do this because...', 'some_error_code');
}
```

You can inspect the result from the gate like so:

```php
$access = Gate::inspect('view', $message);
$access->allowed();
$access->message(); // Cannot do this because...
$access->code(); // some_error_code
// plus other features
```

See here for more details: 
https://github.com/laravel/framework/pull/29044
https://github.com/laravel/framework/pull/29117

**Comment by green-mike** [comment]
I known what I misunderstand. I assume the gate function return boolean only. 
Thank you.The gate inspect feature seems useful. :)
