### ISSUE TITLE
Simplify route, config, optimize commands

### ISSUE THREAD

**Issue by garygreen** [laravel/ideas#171]
It would be nice to simplify everything related to performance optimization of the framework into one command:

``` php
php artisan optimize --routes // Optimize routes.
php artisan optimize --config // Optimize config.
php artisan optimize --compiled // Generate the compiled.php of optimized classes.
php artisan optimize --routes --config // Optimize just routes and config.
```

To optimize everything (cache routes, configs, compiled) you do:

``` php
php artisan optimize
```

The structure of the command:

``` php
optimize [--routes] [--config] [--compiled]
```

The `route:clear`, `config:clear`, `clear-compiled` commands to be combined into one `php artisan optimize:clear`.

By doing this there will be:
- 4 less commands
- 1 simple command to optimize the framework, and 1 to clear.

**Comment by Jeroen-G** [comment]
How does clearing a cache optimize my app?
Also, what does the current existing optimize command do exactly?

**Comment by garygreen** [comment]
> How does clearing a cache optimize my app? Also, what does the current existing optimize command do exactly?

It (by default) optimizes your composer autoloader and create's a compiled.php with files that framework defines and ones in your `config/compile.php`.

Clearing cache doesn't optimize your app, but it's useful for testing locally the optimizations and then clearing etc. Maybe the `clear-compiled` command can be merged into the suggested `optimize:clear` as well.

At the moment, all of these commands relate to the same thing - optimising your app. Having one command for optimizing and one for clearing the optimizations makes sense imo.

```php
clear-compiled
optimize
route:cache
route:clear
config:cache
config:clear
```

New proposed commands:

```php
optimize [--routes] [--config] [--classes]
optimize:clear
```

**Comment by Frondor** [comment]
I support this idea to make the build process more handy and generate faster releases. I don't like to wait for one command to finish in order to type the next one until everything is "optimized" either.

Also, there would be really cool if we are able to know what actually is being added into the compiled file when we haven't added any entry to `config/compile.php` yet. I mean, I can go and see the API, but that's not really handy for beginners.

**Comment by taylorotwell** [comment]
Definitely open to this.
