### ISSUE TITLE
[Proposal] Collection Higher Order Messaging - Allow functions on scalar/null types

### ISSUE THREAD

**Issue by joecampo** [laravel/ideas#1713]
First, thanks in advance for hearing this out. :) 

Currently, we can use higher order messaging on collection instances to call methods that exist on the iterated object. From the docs: 

```php 
$users = User::where('votes', '>', 500)->get();

$users->each->markAsVip();
```

So in the above example, the `markAsVip()` method is implemented on the User model so it’s available to be called.

There are instance where I’d like to also use higher order messaging to call built-in PHP functions on scalar types (e.g. to simply call `trim()`, or reject `is_null()` items) to clean up some code.

## Desired Behavior
```php
$collection = collect(["abc ", " def  ", "g h i  ", null]);

$collection->reject->is_null()->map->trim();
// (Currently would fail: PHP Error:  Call to a member function is_null() on string)


// Desired output: 

=> Illuminate\Support\Collection {#3339
     all: [
       "abc",
       "def",
       "g h i",
     ],
   }
```

I know you can pass methods to map simply like `$collection->map('trim')`; however the problem I run into is `key` is forwarded to the function as opposed to the value [Issue #25549](https://github.com/laravel/framework/issues/25549). The idea here would be for the methods to only be called on the value.

### Useful functions

* is_array
* is_bool
* is_int
* is_null
* is_numeric
* filter_var

```php

$collection = collect(['abc', 'def, 'jane@example.com', null])

$collection->filter->filter_var(FILTER_VALIDATE_EMAIL);

/**
=> Illuminate\Support\Collection {#3331
     all: [
       2 => "jane@example.com",
     ],
   }
**/

```
* dump (Can dump values to the dump server in the middle of a collection pipeline) 
* trim

### Drawbacks

* Functions that are haystack, needle (value) as opposed to taking the value as the first parameter. (e.g. `explode()` or `strpos()`). However, I think there are enough valuable functions to promote this change.

### Change

We’d just need check if an item of the type null or a scalar type in `Illuminate\Support\HigherOrderCollectionProxy`’s `__call` method. The only difference I see in behavior is passing null would fall in trying to call the function on null as opposed to a method being called from null (both would result in an error). Not sure that would qualify as a BC.

```php
/**
 * Proxy a method call onto the collection items.
 *
 * @param  string  $method
 * @param  mixed  $parameters
 * @return mixed
 */
public function __call($method, $parameters)
{
    return $this->collection->{$this->method}(function ($value) use ($method, $parameters) {
        if (is_scalar($value) || is_null($value)) {
            return $method($value, ...$parameters);
        }

        return $value->{$method}(...$parameters);
    });
}
```

**Comment by staudenmeir** [comment]
If we use `! is_object($value)` instead of `is_scalar($value)`, we can also work with arrays:

```php
collect([['a' => 'b', 'c' => 'd'], ['e' => 'f']])->map->array_values();
```

**Comment by joecampo** [comment]
Ah, that's a great idea!
