### ISSUE TITLE
[Proposal] queue:listen output to file

### ISSUE THREAD

**Issue by BasvanH** [laravel/ideas#1717]
I'm running Laravel on a Windows box and registered the queue worker as a Windows Service. Windows hasn't got a Stdout mechanism for services, so I would like to request a feature to add an parameter to 'queue' to output it's progress to a logfile.

```php artisan queue:listen --log="<path>"```

Thanks!

**Comment by taylorotwell** [comment]
No plans to take any action on this at the moment.

**Comment by BasvanH** [comment]
Ok, do you have an alternative to monitor the queue listener on Windows?
