### ISSUE TITLE
Validator's 'integer' should check type, not content

### ISSUE THREAD

**Issue by mattwithoos** [laravel/ideas#1719]
From here:

https://github.com/laravel/framework/issues/18918

The current Validator has been designed with just form requests in mind.

At least two major usecases outside of form requests come to mind:

- JSON requests
- Internal data validation (e.g. models)

The behaviour of the current validation is not in line with the ethos of modern PHP. If I validate something is an integer, I expect an error if it's not an integer; it's really that simple. A string is not an integer. I hope I'm preaching to the choir here and not trying to convince anyone that an integer is not a string.

Actual proposal is:

- Implement a new validation, "like_integer", which would check whether a string contains something like an integer (implements the current behaviour of "integer" validation)
- Change behaviour of existing validation, "integer", to simply check if it's an integer. Goes without saying but a string would be rejected.

Cheers

**Comment by hafezdivandari** [comment]
I think adding a new `strict` rule may be better. We may use it with integers like `strict|integer` or other types like `strict|boolean`.

**Comment by mattwithoos** [comment]
I guess that's the practical answer to support those who do not write strict PHP. At the same time, I don't like this soft approach to PHP, it's how things have been done pre-PHP7 as the default and I feel like we should now be pushing forward, not supporting backwards.

Why do **you** think we should use `strict` instead of integer === integer?

**Comment by ollieread** [comment]
I think the problem you have here is that the `numeric` rule is only half of the problem for people that want to check that it's a whole number. Seeing that the vast majority of systems built with Laravel are going to be handling non-json POST requests, you're going to see a lot of integers as strings.

It would be better to add a `type` validator. So you could do..

- `type:string`
- `type:int`
- `type:float`
- etc
- etc

That'd avoid breaking backwards compatibility and keep everyone happy. It'd also work for any other types.

**Comment by mattwithoos** [comment]
While I disagree that this claim...

> "Seeing that the vast majority of systems built with Laravel are going to be handling non-json POST requests"

... is true (there's no data on this; and if it is true, how many are high-traffic commercially successful sites - and why are they doing loosey-goosey validations if it's a serious operation), and that aside I don't see it as a valid argument (WordPress supports bad practices because people and web hosts still use old versions of PHP... doesn't mean we should too) - as it's something that could be included in a future version of Laravel as a deprecation.

However, given it's an uphill battle to make the case for modern PHP validation, I'm in favour of your suggestion of validating the type quite specifically.

If I have some time this weekend or next I'll push a PR for it.

**Comment by DFoxinator** [comment]
@mattwithoos did you ever get a chance to do any work on this? Seems worthwhile - I'm happy to help if needed.

**Comment by ejunker** [comment]
I would like to see a `type` validation in the core. In the meantime, I created this Rule that I am using. Note that since it uses `gettype()` you have to specify `integer` instead of `int` and `double` instead of `float`.

```php
<?php

namespace App\Rules;

use Illuminate\Contracts\Validation\Rule;

class Type implements Rule
{
    protected $type;

    /**
     * Create a new rule instance.
     *
     * @return void
     */
    public function __construct(string $type)
    {
        $this->type = $type;
    }

    /**
     * Determine if the validation rule passes.
     *
     * @param  string  $attribute
     * @param  mixed  $value
     *
     * @return bool
     */
    public function passes($attribute, $value)
    {
        return gettype($value) === $this->type;
    }

    /**
     * Get the validation error message.
     *
     * @return string
     */
    public function message()
    {
        return 'The :attribute must be of type '.$this->type.'.';
    }
}

```
