### ISSUE TITLE
[Proposal] Route::if() to style active nav links

### ISSUE THREAD

**Issue by bram1028** [laravel/ideas#1729]
I think this is a common enough use case that it warrants support in the framework. I'd like to propose a Route::if() function to basically replace the ternary operator:

```php
<a class="navbar-item {!! Route::is('domains.*') ? 'is-active' : '' !!}" href="{{ route('domains.home') }}">Domains</a>
```

with this:

```php
<a class="navbar-item {!! Route::if('domains.*', 'is-active') !!}" href="{{ route('domains.home') }}">Domains</a>
```

I'm happy to do a pull request if there is approval from the maintainers.

**Comment by fletch3555** [comment]
I personally don't like using the facades in views, but perhaps a blade directive?

I'm sure there's already a relatively easy way to do this, so I wouldn't be surprised if it gets declined as too specific.  Just my 2 cents

**Comment by bram1028** [comment]
I don't like directives in the middle of a HTML tag. But I also forgot that Route is macroable, so I guess I can live without it in the core, but I still think it's helpful.

```php
Route::macro('if', function(...$patterns) {
    $true = array_pop($patterns);
    return Route::is(...$patterns) ? $true : '';
});
```

**Comment by ollieread** [comment]
The method you're looking for is `Illuminate\Http\Request::routeIs()`. You can do stuff like `request()->routeIs('admin:page.*')`.

**Comment by bram1028** [comment]
@ollieread You missed the point. That's actually more code than what we already have. My suggestion eliminates the need to use a ternary operator.

**Comment by ollieread** [comment]
What do you mean that's more code than we already have? That's a piece of
functionality that exists in Laravel, it already exists. Are you proposing
changing it? If so, your change only works for cases where people want to
output something.

If it's that much of an issue, create yourself a helper. The functionality
already exists and it's as generic as it needs to be.

**Comment by bram1028** [comment]
Existing:
```php
Route::is('domains.*') ? 'is-active' : ''
```

Your proposal:
```php
request()->routeIs('admin:page.*') ? 'is-active' : ''
```

My proposal:
```php
Route::if('domains.*', 'is-active')
```

I implemented this as a macro for now. I'm simply suggesting that this could be part of the framework, since it would be a very common usage.

**Comment by ollieread** [comment]
I am not proposing anything. I am telling you that it already exists in the
core of Laravel. Go to your editor and open the request class, you'll see
it in there.

**Comment by bram1028** [comment]
You're still missing the point...
