### ISSUE TITLE
Run queued Job even in maintenance mode

### ISSUE THREAD

**Issue by nmokkenstorm** [laravel/ideas#1732]
Right now there's a possibility of making listeners run on a Queue instead of immediately by making them implement the empty `Illuminate\Contracts\Queue\ShouldQueue`.

I thought there was a similar contract for making jobs run even if the application is in maintenance mode, but apparently that's not the case. Would adding a check [here](https://github.com/illuminate/queue/blob/master/Worker.php#L175) for an empty interface called `Illuminate\Contracts\Queue\RunsInMaintenanceMode` or something make sense?

**Comment by martinbean** [comment]
@nmokkenstorm You need to instruct your queue worker to run even in maintenance mode by using the `--force` flag.

**Comment by nmokkenstorm** [comment]
I'm aware of the --force flag, but that would run _all_ jobs, while I'm looking for a way to signal in the code base that a certain type of job is allowed to be ran, regardless of flags on the worker.

**Comment by martinbean** [comment]
@nmokkenstorm Push those jobs to a separate queue, and have that worker run even in maintenance work.
