### ISSUE TITLE
[5.8]When use stack driver, Processor set in custom log driver is not used

### ISSUE THREAD

**Issue by sh-ogawa** [laravel/ideas#1735]
I confirmed createStackDriver, Using a custom log driver with the stack driver felt very difficult to implement Monolog.

So why not put the following sentence in the manual?

"At present, advanced Monolog customization is not available for the stack driver. For example, you can not pass Processor."

**Comment by mfn** [comment]
Isn't that what the `custom` driver is for?

https://laravel.com/docs/5.8/logging#creating-channels-via-factories

**Comment by sh-ogawa** [comment]
I think so, too.
However, the stack driver is implemented in the logger handler loop.
The processor specification depends on the implementation of the log driver, and I thought it would be too wild to apply to all the log channels specified in the stack driver.
Now that you feel that the stack driver extension is a high-impact repair, would you like to announce it? I suggested that.

https://github.com/laravel/framework/blob/5.8/src/Illuminate/Log/LogManager.php#L214-L225

**Comment by DominikStyp** [comment]
If anyone is still interested in fixing this issue: https://github.com/laravel/framework/pull/36591
