### ISSUE TITLE
[Proposal] Change Gates Gates for Gates Permissions

### ISSUE THREAD

**Issue by DarkGhostHunter** [laravel/ideas#1740]
Currently, the Gate Facade handles access authorization in two ways: Gates and Policies. As you can see, the `Gate` is redundant and may allow for confusion.

My proposal is to keep the Gate Facade, but instead of using the `define()` method to define Gates, These Gates should be called Permissions, and use `permission()` alongside `policy()`. Since I'm bad with words, `permission()` could be other simplistic word.

From:

    Gate::define('see-dashboard', 'App\Gates\DashboardGate');

To:

    Gate::permission('see-dashboard', 'App\Gates\Dashboard');

The reason to keep the Gate Facade is because there is already a Contract with the same name. Changing the Facade wouldn't make much sense since the idea of Facades is to be named the same way of the Service/Class it represents.

## Does break anything?

Yes. Gates defined by `define()` would need to change to `permission()`.
Yes. The documentation should change.

## Does it adds something?

Better understanding about Gates, and their types: permissions and policy.

## Does this look kinda unnecessary.

Yes.

**Comment by taylorotwell** [comment]
No plans to take any action on this at the moment.
