### ISSUE TITLE
[Proposal] Adding Unsigned Integer Support to SQLite

### ISSUE THREAD

**Issue by jianjye** [laravel/ideas#1742]
Hi,

As we know that SQLite does not support unsigned integer (neither does Laravel for SQLite), but a workaround for this can be done via `CHECK CONSTRAINT`. 

I am interested in submitting a PR by adding the follow codes into `framework/src/Illuminate/Database/Schema/Grammars/SQLiteGrammar.php` as a workaround for unsigned integer.

```
protected $modifiers = ['Nullable', 'Default', 'Increment', 'Unsigned'];

protected function modifyUnsigned(Blueprint $blueprint, Fluent $column)
    {
        if ($column->unsigned) {
            return " CHECK({$column->name} >= 0)";
        }
    }
```

Would this be considered or accepted?

**Comment by staudenmeir** [comment]
This would also be an option for PostgreSQL and SQL Server.

What happens when you change such a column and make it `signed` again (and the opposite direction)?

**Comment by jianjye** [comment]
SQLite does not support adding or dropping constraint in `ALTER TABLE` statement so we cannot make it `signed` or `unsigned` after we have created the table. 

I think it's important that if a user is creating a table with an unsigned column for SQLite he gets what he asks for, else there is no way to change it but to drop the table and re-create it.

**Comment by sisve** [comment]
Keep in mind that the data type "unsigned integer" does not exist in the SQL standard at all, no unsigned numeric types does. Laravel only supports unsigned integers for Mysql (which is the only grammar implementing the modifyNullable method), all other database implementations will create signed integer columns.

Assuming identity/auto_increment columns, switching from integer (2^31-1) to biginteger (2^63-1). And here's a fun thing; these are also the values of PHP_INT_MAX on 32- and 64 bit systems. An unsigned biginteger maxes out at 2^64-1, which is larger than what php handles on a 64 bit system, so it converts to floats and loses precision. A primary key without precision sounds like a fun thought excercise, and a less fun production issue. Proof of misery: https://3v4l.org/M8IUR

Now, I am not against using constraints to disallow some value ranges for data consistency, similar to enums restrict which values are supported in a field. Using unsigned data types in your database, that isn't being supported by your programming language, is a nightmare waiting to happen.

**Comment by jianjye** [comment]
Taylor has closed my PR https://github.com/laravel/framework/pull/29333 so I'm going to close this.
