### ISSUE TITLE
[Notice] Required improvements of the new logo

### ISSUE THREAD

**Issue by SerafimArts** [laravel/ideas#1744]
As we recently became aware of the new logo will be such an option:

![image](https://user-images.githubusercontent.com/2461257/62042063-d20a9400-b205-11e9-9758-5ede255c80b3.png)

However, I want to note that the letter "R" in the logo looks like the letter "Г" in the Cyrillic alphabet. Such a visualization of the logotype leads to the fact that it reads like "Lagavel". What is associated with the "lag" word. 

I do not want the framework in half of the countries of the world to be associated with buggy and loose, and this will inevitably happen if you leave the logo in its current form.

@taylorotwell please pay attention to this

**Comment by Hunternnm** [comment]
Yes, the new logo has caused just such associations :(

**Comment by likvidatorTM** [comment]
And even without this issue, in my opinion this letter looks ugly.

**Comment by devopsalexandr** [comment]
laГavel = lag as well :D

**Comment by taylorotwell** [comment]
If someone wants to email me a comprehensive SVG package containing slightly modified assets for that go ahead.

**Comment by yekhlakov** [comment]
Still the shape of 'r' differs all too much from other letters in the font. Something like this would look more uniform and smooth.
![laravel6logo](https://user-images.githubusercontent.com/15815146/62271463-230ec800-b452-11e9-8d25-e522136428ca.png)

**Comment by mattstauffer** [comment]
We'll put together updated assets for Taylor to consider.

**Comment by SerafimArts** [comment]
Is it possible to get the original svg version to modify it?

https://github.com/laravel/art is abandoned =(

**Comment by mattstauffer** [comment]
@SerafimArts I was able to get the original assets and Tighten is updating the assets for Taylor to consider.

**Comment by SerafimArts** [comment]
Oh, that's good

**Comment by SerafimArts** [comment]
@mattstauffer today a new site with this funny logo has been released. I understand Taylor ignored your work?

**Comment by mattstauffer** [comment]
🤷‍♂️ I'm sure he's still considering his options. :)

**Comment by andrey-helldar** [comment]
> If someone wants to email me a comprehensive SVG package containing slightly modified assets for that go ahead. Keep in mind that Laravel is written in English and developed in English.

And if such a conversion of a word in another language was read as an obscene insult, would they also say "read in English"?

The Russian-speaking community already says "Lagavel" ...

**Comment by SerafimArts** [comment]
@andrey-helldar 
![image](https://user-images.githubusercontent.com/2461257/69487702-6eb90780-0e6f-11ea-978b-9abfff8f8303.png)

**Comment by githubber** [comment]
I'm surprised a Cyrillic reader would read the r as a g, when CLEARLY the v is a V and not the cyrillic v which look like a capital B. The sharp angle of the existing r also complements the right angles of the logo. Makes total sense to me.

**Comment by SerafimArts** [comment]
@githubber there is nothing like `v` in cyrillic.

**Comment by githubber** [comment]
@SerafimArts I know. The op comment said that the r looks like a Г, and so expressed concern that a cyrillic reader will think it is a "g' sound. But what cyrillic reader will do that when the word itself is clearly not written in cyrillic. The two vowels could be, possibly. But neither the L nor the v are in the cyrillic alphabet as letters, so focusing on just one letter, the r, saying it will confuse readers, seems overblown. If they wrote it like this "Лаrаvел", then sure, that could be more confusing. And besides, most people who are going to come across this product probably already know what the name is and so would not think the r is suddenly a g.

My comment you commented on says the same thing, but I focused on the lack of a cyrillic в , which sounds like an english "v". i think if you read my comment again you'll see what I was saying.

**Comment by SerafimArts** [comment]
It's too late to discuss anything. The word "lagavel" has already become a meme =)

**Comment by githubber** [comment]
true enough I guess. It was *made* into a meme, and not just because Cyrillic readers couldn’t figure it out. Kind of like this store in Kazakhstan known as Pamstop, sounds funny in English, even though it is spelled “Рамстор". It was funnier to call it by the sort-of English name.
