### ISSUE TITLE
[Proposal] ignoreOrCreate Eloquent method

### ISSUE THREAD

**Issue by rogervila** [laravel/ideas#1759]
Hello,

Sometimes there are cases where you want to be 100% sure that you are not inserting duplicated entries, especially on databases where you do not have permissions to create unique keys and codebases that you do not own.

The idea is to have a method that acts mostly like the `updateOrCreate()` method, but without even touching the database.

Example:

```php
Post::ignoreOrCreate([
    'title' => 'hello',
])
```
if there is already a post with that title, there is no action performed on the database.

If this idea is accepted, I can work on its implementation.

Thank you.

**Comment by RikSomers** [comment]
What about using `firstOrCreate`?

**Comment by rogervila** [comment]
`firstOrCreate` runs a select query that returns the object in case it exists.
The idea of this method is to skip that retrieve from the database in case it exists.

**Comment by sierrafayad** [comment]
You will get the object with the first select that is going to be executed in the database (to check if it already exist) so using `firstOrCreate` wouldn't hurt the db performance.

**Comment by rogervila** [comment]
Ok, it looks that `firstOrCreate` is enough for the community. 
Thank you for the feedback,
