### ISSUE TITLE
[Proposal] Optional 'context' argument for policies

### ISSUE THREAD

**Issue by mintbridge** [laravel/ideas#1761]
Hi,

I have a model for a Product and a model for Type, with a many to many relationship between them. Using policies makes it easy to restrict actions for either model independently, e.g. `$user->can('create', App\Product::class);`. 
It gets a lot harder when I want to restrict a user to only create a Product of a certain Type(s).

So my proposal would be to allow for an 3rd optional context parameter to be passed in, e.g.
`$user->can('create', App\Product::class, [context goes here]);`, which would allow for any extra data to be passed in and used for determining the policy result.

From a quick look around, I think that it should be doable in a fairly straightforward (non breaking) way for 3 of the ways to use policies (Via The User Model, Via Middleware, Via Controller Helpers), the one that looks more difficult is blade (`@can('create', App\Product::class)`).

This would solve the use case above, but also allow for a lot more flexible ways to use policies in different contexts.

Happy to have a go at implementing this if people think it's reasonable?

Paul

**Comment by mfn** [comment]
But this is already supported: the 2nd argument to `can` is in fact an array (if not, it gets converted) and they're unwrapped and passed to your actually policy method.

I've policy methods looking like this:
```php
    $user->can('createPost', [$category, $assignedUser, true]);
…
class PostPolicy {
    public function createPost(
        User $user,
        Category $category,
        User $assignedUser,
        bool $specialFlag
    ): bool {
```

**Comment by drbyte** [comment]
> new proposal can we add it to the docs?

Good idea.

It works for `allows`, `denies`, `check`, `any`, `none`, `authorize`, as well as both `can`, `@can` and their any/not variants.

Here are a few references to the code:

https://github.com/laravel/framework/blob/cc2a9e70c6833ead199bb0dfb8a02ea9649866f5/src/Illuminate/Support/Facades/Gate.php#L13-L18

https://github.com/laravel/framework/blob/cc2a9e70c6833ead199bb0dfb8a02ea9649866f5/src/Illuminate/Foundation/Auth/Access/Authorizable.php#L16-L19

https://github.com/laravel/framework/blob/cc2a9e70c6833ead199bb0dfb8a02ea9649866f5/src/Illuminate/Foundation/Auth/Access/AuthorizesRequests.php#L19-L41

https://github.com/laravel/framework/blob/cc2a9e70c6833ead199bb0dfb8a02ea9649866f5/src/Illuminate/Auth/Access/Gate.php#L311-L361

**Comment by mfn** [comment]
Doc updates don't need proposals; they just need the PRs

**Comment by drbyte** [comment]
@mfn How's the wording and example here? https://github.com/drbyte/laravel-docs/commit/156822dc3325478567696c4c04b2bc6d5a9d5035

**Comment by mfn** [comment]
Looks great, with examples 😍

**Comment by driesvints** [comment]
Pr to the docs was merged.
