### ISSUE TITLE
[Proposal] [6.0] Remove Illuminate\Support\Carbon for the original Carbon

### ISSUE THREAD

**Issue by DarkGhostHunter** [laravel/ideas#1765]
## Why?

Because the class is just an empty un-extendable shell that just references the original Carbon class.

## Breaking Changes?

All the framework. This can be fixed to pointing to the base Carbon class rather than the other. This should be going for Laravel 6.0

## Does it add something?

No.

## Does remove something?

Yes. That class

**Comment by raiika** [comment]
I think the main idea of this Support Carbon is when the Carbon got suspended or we implement some method that Carbon does not provide, because laravel depends on this support carbon, and it will be painful if this proposal got accepted and the problem above occures.

**Comment by DarkGhostHunter** [comment]
> I think the main idea of this Support Carbon is when the Carbon got suspended or we implement some method that Carbon does not provide, because laravel depends on this support carbon, and it will be painful if this proposal got accepted and the problem above occures.

I get your idea: If Carbon drops supports for something, having the Support Carbon extending it the framework can leverage the hole with its own methods.

But I don't think it would be problematic unless Carbon doesn't respect semver. At this point, if there is a feature taken off by Carbon, which I doubt, then the _helper_ class can come again.
