### ISSUE TITLE
Throw exception when committing and no transaction is started

### ISSUE THREAD

**Issue by digilist** [laravel/ideas#1770]
Follow up for https://github.com/laravel/framework/issues/29505

- Laravel Version: master (is a "feature" since #14085 / 5.2)
- PHP Version: irrelevant
- Database Driver & Version: irrelevant

### Description:

https://github.com/laravel/framework/blob/e778e3296dce73fddf772844158a8c87f1857bb5/src/Illuminate/Database/Concerns/ManagesTransactions.php#L154-L163

In cases where the user calls `commit()` more often than `beginTransaction()` (e.g. because `beginTransaction()` is removed by accident) the user will never notice.

This method should throw an exception instead, because otherwise the user will never notice (that the transaction has been committed to early or that no transaction is active at all).

@GrahamCampbell already pointed to that issue in #12382 and #14085 but was ignored...

**Comment by driesvints** [comment]
Please don't re-open issues which were closed. Always feel free to respond to the closed issue.
