### ISSUE TITLE
[Proposal] Bind optional binding to raw query Expression object

### ISSUE THREAD

**Issue by mpskovvang** [laravel/ideas#1776]
### Description
The raw expressions is useful when queries contains aggregations, functions etc., however, if not used carefully, you might create SQL injection vulnerabilities.

We already have `whereRaw` which takes a raw expression and optional bindings.

So we could use `Audit::whereRaw('ip = inet_aton(?)', $request->ip());` or `Audit::where('ip', new Expression('inet_aton(?)'))->addBinding($request->ip())` safely.

### Why

But sometimes is would be useful to create an expression object with bindings:

`Audit::where('ip', new Expression('inet_aton(?)', $request->ip());`

It would even allow us to extend the `Expression` class for even simpler usage:

```
class InetAton extends Expression
{
    public function __construct($binding)
    {
        parent::__construct('inet_aton(?)', $binding);
    }
}
```
```
use App\Query\Expressions\InetAton;

Audit::where('ip', new InetAton($request->ip());
```

With custom SQL functions or complex expressions, the actual benefits might become even more valuable:

```
class OptimizationCalcDate extends Expression
{
    public function __construct($type, $field, $default)
    {
        // TODO validate $type
       
        parent::__construct('optimization_calc_date(?, ?, null, ?) as date', [
            $type,
            $field,
            $default
        ]);
    }
}
```
```
use App\Query\Expressions\OptimizationCalcDate;

Analytics::where('customer_id', $customer_id)
    ->addSelect(new OptimizationCalcDate('start', $request->input('field'), Carbon::now());
```

Now, the developer can simply use an object with type hints and optional validation, without knowledge of the actual custom SQL function. Completely safe, without creating SQL injection vulnerabilities.

### Other alternatives
The Eloquent scopes could be an alternative in some cases, especially the first example, but having an `Expression` class with optional bindings would be great with the Query Builder without an Eloquent model.

### Code modifications
This requires the `Ìlluminate\Database\Query\Expression` to be modified to something like:

```
class Expression
{
    public function __construct($value, $bindings = []) { ... }

    ...

    public function getBindings() { ... }
}
```

The `Illuminate\Database\Query\Builder` must be updated multiple places to extract the bindings into the query components:

```
public function where($column, $operator = null, $value = null, $boolean = 'and')
{
    ...

    if (! $value instanceof Expression) {
        $this->addBinding($value, 'where');
    } else {
        // Modification
        $this->addBinding($value->getBindings(), 'where');
    }
}
```

### Community interest
If there is an interest from community and the Laravel team for this approach, I'll be happy to submit a PR.

**Comment by mfn** [comment]
I can't judge the technical feasibility / complexity but I know that I had the need for this too in the past => 👍 for the idea

**Comment by staudenmeir** [comment]
I don't see how this would be feasible. There are dozens of places where you can use raw expressions and they all would have to be adjusted.

For example, consider a query like this:

```php
DB::table('users')->whereIn('column', ['value1', DB::raw('?', 'value2'), 'value3'])->get();
```

**Comment by mpskovvang** [comment]
> I don't see how this would be feasible. There are dozens of places where you can use raw expressions and they all would have to be adjusted.
> 
> For example, consider a query like this:
> 
> ```
> DB::table('users')->whereIn('column', ['value1', DB::raw('?', 'value2'), 'value3'])->get();
> ```

I'm not sure I gets the point of your concern. `DB::raw(...)` creates an `Expression` object. Then, the `whereIn` method adds the bindings through `cleanBindings`, which just has to be modified to also extract the bindings from the `Expression` object.

The change won't force anyone to update the existing use of `DB::raw(...)` or `new Expression(...)`, as the second argument will be optional. You can still do `DB::raw('count(*)')` etc.

**Comment by mpskovvang** [comment]
Another examples of real application use cases.

- Find Eloquent model by binary UUID column: `URL::find(Expressions::unhex($id));`

- Find Eloquent models by obfuscated keys: `User::find(Expressions::decode($id));`

In both cases I could have a class with methods matching the necessary SQL functions - either built-ins or customs.

```
class Expressions
{
    public static function unhex($string)
    {
        return new Expression('unhex(?)', $string);
    }

    ...
}
```

**Comment by mfn** [comment]
Would it solve to add a new `BoundExpression` object? 🤷‍♀️

**Comment by staudenmeir** [comment]
> which just has to be modified to also extract the bindings from the Expression object.

There are *a lot* of places that would need to be adjusted. A few examples:

- Methods like `select()` and `addSelect()`.
- Methods like `where()` and `having()` allow raw expressions as column names:
`where(DB::raw('column'), '=', 'value')`
- You would introduce bindings to parts of the query that don't support them yet:
`->groupBy(DB::raw('...'))`

**Comment by mpskovvang** [comment]
@staudenmeir you're right, quite a few methods would require some adjustments. The obvious ones  contains `$value instanceof Expression`, but some others is more difficult to find because of the magic `__toString()` method.

I didn't thought of raw expressions with bindings in columns, but I'm not sure if we're supposed to handle them anyway, as it seems like is it currently unhandled since the `orderByRaw()` accepts bindings too. A developer can already do `->orderByRaw('?', $order)`?

The implementation is certainly more complicated than first anticipated, but still feasible I guess. The question is, if this feature adds enough value for the community to proceed with this concept.

Another workaround I tend to use, is a `Facade` to an underlying class with an PDO instance and its `quote()` method.

```
class Expressions
{
    public function __construct(PDO $pdo) { ... }

    public function unhex($string)
    {
        return new Expression('unhex(' . $this->pdo->quote($string) . ')');
    }
}
```

```
use App\Facades\SQL;

Post::find(SQL::unhex($id));
```

This alternative kinda gives raw expressions with safe bindings. However, the developer carries a greater responsibility to quote inputs correctly, and the reason why prepared statements is the recommended approach + prepared statements offers better caching.

**Comment by staudenmeir** [comment]
> A developer can already do ->orderByRaw('?', $order) even though it's unsupported?

How do you mean? `orderByRaw()` supports bindings.

**Comment by staudenmeir** [comment]
> A developer can already do ->orderByRaw('?', $order) even though it's unsupported?

How do you mean? `orderByRaw()` supports bindings.

**Comment by mpskovvang** [comment]
> How do you mean? `orderByRaw()` supports bindings (you can't provide the column name as a binding).

My point was to answer your third bullet point:

> You would introduce bindings to parts of the query that don't support them yet:
`->groupBy(DB::raw('...'))`

But I just realized, I misunderstood your point. I do see your concern now. At the time the groups are being compiled and the values are checked against raw expressions, it's apparently too late to add new bindings without a complete refactoring.

Based on your pointers, I realize the complexity of this feature is far from simple.

**Comment by mpskovvang** [comment]
> Why can't you just use getPdo(), or the DB Facade for these things. In either you can write any query you can imagine. Eloquent on the other hand of course has limitations. To me, that's what the PDO instance is for, to handle certain queries that eloquent won't handle.

I prefer not to rewrite Eloquent queries to raw queries just because I need a basic raw expression. However, in more complex queries, like in your example, I might as well go with raw queries. It depends on the use case. In the particular case when opening the discussion, all Eloquent model and relationship keys required a special SQL function while performing lookups. This function required a binding. Instead of rewriting all Eloquent queries to raw SQL, we could just use an `Expression` with a binding - and even simplifying further with a helper class wrapping the SQL function logic.

Anyway, I just wanted to see if anyone else could use the power of `Expression` with bindings and discuss the feasibility.

Because of the complexity of this idea and different workarounds available, I'm going to close this issue for now.

**Comment by johnwc** [comment]
We have a need for this as well, explicitly for the same reason. Being able to use `unhex(?)` 

```PHP
// $id is passed via url path, needs to be sanitized.
$ignore = new UserIgnore();
$ignore->user_id = $user_id;
$ignore->owner_id = DB::raw("unhex(?)", $id);
$ignore->save();
```

@staudenmeir you have a valid issue pointed out, showing that it wouldn't work in some situations. There would be areas where it just would not be supported. But that does not nullify its need elsewhere. If there was a `BoundExpression` class that took on this needed behavior, that would be a starting point to check. As for your 'where column' example, it could check if the type was of `BoundExpression` and then throw exception.
