### ISSUE TITLE
[Proposal] Prevent infinite job processing for failed broadcast events

### ISSUE THREAD

**Issue by iBotPeaches** [laravel/ideas#1786]
So I thought this was a bug: https://github.com/laravel/framework/issues/29656, but it was labeled as an improvement.

So I'm here to propose functionality.

Entities in Laravel such as Mailables, Notifications, Jobs and more all support the notion of `$tries/$timeout` to restrict to a job level the timeout or attempts for a job.

When you use the Broadcasting functionality, the entire Event is wrapped by the BroadcastEvent which does not pull any values from the parent Event. This means if your Broadcast event has an exception - it loops forever, because it ignores any timeout/tries property.

One might say. Just set a hard-coded limit on the queue runner. This does not help if you want some jobs to try for 3 times, events once etc.

PR here: https://github.com/laravel/framework/pull/29657

**Comment by mfn** [comment]
Can't judge the technical complexity but your idea/proposal does make sense to me (also saw the PR)

**Comment by iBotPeaches** [comment]
It was merged in 6.0. Closing :)
