### ISSUE TITLE
[Proposal] Upgrade to Monolog 2.0

### ISSUE THREAD

**Issue by gmsantos** [laravel/ideas#1808]
[Monolog 2.0](https://github.com/Seldaek/monolog/releases/tag/2.0.0) was released this week, with some new interesting handlers like the SqsHandler and the ProcessHandler. I would like to add support for this release in Laravel.

Upgrading it in master branch [didn't break any test](https://github.com/gmsantos/framework/pull/2) and the [upgrade guide](https://github.com/Seldaek/monolog/blob/2.0.0/UPGRADE.md) doesn't seems to have something to fix in Laravel code. I need to test it in a real application though, but this upgrade should only impact who uses a custom handler.

Since Laravel 6.0 release is really close, I would like to suggest that we allow 2.0 to be used in this release (`"monolog/monolog": "^1.12 || ^2.0"`) and for Laravel 7.0 we require 2.0.

**Comment by Christophvh** [comment]
https://github.com/laravel/framework/pull/29814

**Comment by driesvints** [comment]
Merged
