### ISSUE TITLE
[Proposal] Make collections more extensible 

### ISSUE THREAD

**Issue by vaites** [laravel/ideas#1813]
There are situations where you want to create a collection with some extra info. The Laravel Collection class use `new static` in many methods so any added property is lost.

Take this example collection:

```php
<?php

namespace App\Collections;

use Illuminate\Support\Collection;

class TestCollection extends Collection
{
    public $foo = null;

    public function __construct($items = [], $foo = null)
    {
        parent::__construct($items);

        $this->foo = $foo;
    }
}
```

Then, take this example code:

```php
$collection = new TestCollection([1, 2, 2, 3], 'something');

var_dump($collection);

$unique = $collection->unique();

var_dump($unique);
```

The output shows:

```
object(App\Collections\TestCollection)#1348 (2) {
  ["foo"]=>
  string(9) "something"
  ["items":protected]=>
  array(4) {
    [0]=>
    int(1)
    [1]=>
    int(2)
    [2]=>
    int(2)
    [3]=>
    int(3)
  }
}
object(App\Collections\TestCollection)#1361 (2) {
  ["foo"]=>
  NULL
  ["items":protected]=>
  array(3) {
    [0]=>
    int(1)
    [1]=>
    int(2)
    [3]=>
    int(3)
  }
}
```

The goal is to keep the value of `foo` in new collections. So my proposal is to add a non-static method like `newCollection()` to the base collection that can be overriden in child classes:

```php
public function newCollection($items = [], $foo = null)
{
    return new static($items, $foo);
}
```

By default it must return only `new static($items)` and any method calling `new static()` must be modified to call `$this->newCollection()` instead.

**Comment by driesvints** [comment]
Closing this as the PR was rejected.
