### ISSUE TITLE
[Proposal] Fluent Syntax to redirect route

### ISSUE THREAD

**Issue by aarreedd** [laravel/ideas#1815]
To redirect a route you do this:

    Route::get('dashboard', function () {
        return redirect('home/dashboard');
    });

I propose redirect method so you can rewrite this as a simple one-liner:

    Route::get('dashboard')->redirect('home/dashboard');

If this gets support I'd be happy to code it up.

**Comment by drbyte** [comment]
Are you wanting to do something different from the built in methods?
`Route::redirect('/here', '/there');`
`Route::permanentRedirect('/here', '/there');`

https://laravel.com/docs/5.8/routing#redirect-routes

**Comment by aarreedd** [comment]
No, just didn't know that existed.
