### ISSUE TITLE
Possibility to wrap columns with SQL string functions

### ISSUE THREAD

**Issue by andypa** [laravel/ideas#1822]
Problem: I currently run into a problem with case sensitivity because MySQL and Postgresql handle querying JSON columns differently, e.g. JSON_EXTRACT in MySQL vs JSON_EXTRACT_PATH in Postgresql.

Solution: If a column could be "wrapped" with an SQL string function, the problem could be solved like this: 
```
$query->selectWithWrap('json_column->value', 'LOWER')
```

That could result in:
```
SELECT LOWER([database-specific grammer for extracting JSON])
```

This is just a rough first draft, since I'm wondering if such functionality would even be considered. If it would be considered, I would try to provide the functionality.

**Comment by staudenmeir** [comment]
That's a very specific use case and I don't think there will be a dedicated method for it.

You can use this workaround instead:

```php
$query->select('lower('.$query->getGrammar()->wrap('json_column->value').')');
```

**Comment by andypa** [comment]
@staudenmeir thank you for this workaround! It helped me fix a bug in another package.
