### ISSUE TITLE
Adopt PSR-12

### ISSUE THREAD

**Issue by netpok** [laravel/ideas#1829]
PSR-2 coding standard was superseded by PSR-12, Laravel should probably adopt it.

I think the two most affecting changes are the:

#### [multiline if structure](https://www.php-fig.org/psr/psr-12/#51-if-elseif-else)
This would change
```php
if (! hash_equals($request->route('id'), $request->user()->getKey()) ||
    ! hash_equals($request->route('id'), $request->user()->getRouteKey())) {
    throw new AuthorizationException;
}
```
to
```php
if (
    ! hash_equals($request->route('id'), $request->user()->getKey()) ||
    ! hash_equals($request->route('id'), $request->user()->getRouteKey())
) {
    throw new AuthorizationException;
}
```

#### [One trait per line rule](https://www.php-fig.org/psr/psr-12/#42-using-traits)
This would change
```php
class User extends Model implements
    AuthenticatableContract,
    AuthorizableContract,
    CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword, MustVerifyEmail;
}
```
to
```php
class User extends Model implements
    AuthenticatableContract,
    AuthorizableContract,
    CanResetPasswordContract
{
    use Authenticatable;
    use Authorizable;
    use CanResetPassword;
    use MustVerifyEmail;
}
```

**Comment by u01jmg3** [comment]
For info, my recent PR to get the ball rolling with PSR-12 was closed: https://github.com/laravel/laravel/pull/5114

**Comment by driesvints** [comment]
@u01jmg3 it's unlikely that PR would ever get accepted because the code comments above the traits are meant to give more info to them. Moving the trait above them doesn't makes sense. I also don't see how that violates PSR-12. I think placing comments above a trait is fine.

**Comment by u01jmg3** [comment]
> _I also don't see how that violates PSR-12. I think placing comments above a trait is fine._

```php
class LoginController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Login Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles authenticating users for the application and
    | redirecting them to your home screen. The controller uses a trait
    | to conveniently provide its functionality to your applications.
    |
    */

    use AuthenticatesUsers;
```

- @driesvints the code above results in CodeSniffer giving the following error.
  - This comes from [PSR-12 · 4.2 Using traits](https://www.php-fig.org/psr/psr-12/#42-using-traits)

```
The first trait import statement must be declared on the line after the class opening brace
(PSR12.Traits.UseDeclaration.UseAfterBrace)
```

- Maybe the comment would need to be reworded if Laravel wants to comply with PSR-12?

**Comment by driesvints** [comment]
Isn't CodeSniffer just wrong in this case? Like I said: please point out to the PSR-12 spec how a comment before a use statement violates the spec.

**Comment by brunogaspar** [comment]
@driesvints Pretty much `The use keyword used inside the classes to implement traits MUST be declared on the next line after the opening brace.`

Having the comment right after the opening brace, violates this rule it seems heh

**Comment by driesvints** [comment]
Urgh, that's super unfortunate. With this it's unlikely that Laravel will ever adopt PSR-12...

**Comment by brunogaspar** [comment]
Ya, that's a weird rule over there if you ask me lol

**Comment by u01jmg3** [comment]
> _Like I said: please point out to the PSR-12 spec_

I did! 😉 ([PSR-12 · 4.2 Using traits](https://www.php-fig.org/psr/psr-12/#42-using-traits))

> _With this it's unlikely that Laravel will ever adopt PSR-12..._

It seems extreme to ignore the entire PSR-12 coding style due to this one rule as opposed to rewording a comment or excluding just that rule but well well, the decision is to be made and it is optional.

**Comment by netpok** [comment]
I can see the point of that. That comment describes the class, so it should be a class level comment.

For example:
```php
/**
 * Class LoginController
 *
 * This controller handles authenticating users for the application and
 * redirecting them to your home screen. The controller uses a trait
 * to conveniently provide its functionality to your applications.
 * 
 * @see \Illuminate\Foundation\Auth\AuthenticatesUsers
 */
class LoginController extends Controller
{
    use AuthenticatesUsers;

    // rest of the code
}
```

**Comment by driesvints** [comment]
> I did! 😉 (PSR-12 · 4.2 Using traits)

Sorry! Missed that 😶

Like I said: it's probably not going to happen with this rule. We can definitely look at the other rules though.

**Comment by driesvints** [comment]
Although it does seem like afaik there's only one comment block each time. We could move them to class blocks indeed. But in general I think it's a bit weird that this rule dictates where you can place comments.

**Comment by netpok** [comment]
I my opinion it tries to tell where not to put the comment, I think here the reason is to not push the traits down with half a page of comments and try to get people to move class level comments up.

Of course if there is a reason the rule can be broken, it's not like the PSR police will take us away (there probably wouldn't any free programmers).

**Comment by driesvints** [comment]
> try to get people to move class level comments up.

That indeed applies to class level comments but you might want to add some info about a specific trait.

> Of course if there is a reason the rule can be broken, it's not like the PSR police will take us away 

If tools like CodeSniffer are going to enforce this then that leaves little room for interpretation.

**Comment by adiachenko** [comment]
I am against adopting PSR-12 because unlike PSR-2 it contains quite a few questionable choices like enforcing strict types and grouped imports, including groupings with compounds depth and function based imports etc., for example:

```
<?php

declare(strict_types=1);

use function Another\Vendor\functionD;
use function Vendor\Package\{functionA, functionB, functionC};
use Vendor\Package\SomeNamespace\{
    SubnamespaceOne\ClassA,
    SubnamespaceOne\ClassB,
    SubnamespaceTwo\ClassY,
    ClassZ,
};
```

It's a travesty of a standard imo. Standards should not be this opinionated.

**Comment by netpok** [comment]
It tells:
- When strict types are used it should be declared before the use statements. 
- When grouped imports are used it, must not contain more than two levels.

Both of them are optional and only applies if you chose to use the feature.

**Comment by adiachenko** [comment]
@netpok I stand corrected. Fell into a trap of reading code examples instead of paying more attention to what the standard actually says. It's indeed not as opinionated as I made it out to be.

**Comment by byteworksng** [comment]
I think the wording is where the confusion is. CodeSniffer sees this as valid.
`
class ResetPasswordController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Password Reset Controller
    |--------------------------------------------------------------------------
    |
    | This controller is responsible for handling password reset requests
    | and uses a simple trait to include this behavior. You're free to
    | explore this trait and override any methods you wish to tweak.
    |
    */
    use ResetsPasswords;`

**Comment by bikalbasnet** [comment]
>Deprecated - As of 2019-08-10 PSR-2 has been marked as deprecated. PSR-12 is now recommended as an alternative.

@taylorotwell It has been more than a year since PSR-2 has deprecated, What is the final decision on this? Will laravel adapt PSR-12?

**Comment by driesvints** [comment]
Doesn't seems like we'll be adopting it at the time. Specifically the required `()` syntax for newing up objects isn't going to happen in the Laravel codebase. On the other hand, most of the Laravel codebase is already PSR-12 compliant. 

You're of course free to adopt PSR-12 in your own app.
