### ISSUE TITLE
Enhanced maintenance mode (artisan down/up)

### ISSUE THREAD

**Issue by iget-master** [laravel/ideas#1831]
# The problem

On some of our projects, we need to schedule a maintenance, manually inform all users that the application will enter in maintenance on scheduled date/time.

# Proposed solution

1. Allow scheduling the maintenance: the `artisan down` command might receive an `on` option that accepts any carbon valid datetime, eg: "now", "+1 day", ...
2. Trigger three events: `MaintenanceScheduled`, `MaintenanceStart` and `MaintenanceFinish` (or any other meaningful name that you suggest)

This way, the user can implement it own maintenance event handlers, and for example broadcast on Pusher the maintenance so the front-end application can inform user about a scheduled maintenance, and maintenance start/finish.

If you guys accept this proposal, I can code it and send a PR.

**Comment by regiszanandrea** [comment]
@iget-master If you let me, I would like to implement a package with this functionality

**Comment by regiszanandrea** [comment]
Nevermind, @iget-master checkout this package: https://github.com/awjudd/maintenance-mode#events

**Comment by iget-master** [comment]
Haha, Nice! I'll close this issue so.
