### ISSUE TITLE
[Bug] migration Lumen 6.0 ->default(value);

### ISSUE THREAD

**Issue by Tukizz** [laravel/ideas#1832]
i have migration file with this column :
```php
$table->tinyInteger('access')->default(0);
```
it throw a error like this :
```
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '('0'), `uuid` varchar(255) null, `provider` varchar(255) null, at line 1
```
then i move the ->default(0) to another place in the same file it still throw error like that
then i remove the ->default(0) and place default to model it work normal
but every table and column using ->default(value) it throw same error like previous

but in Lumen 5.8 it's not throwing error like that

i using : 
Lumen 6.0
MySQL 5.7
PHP 7.2

**Comment by staudenmeir** [comment]
This will be fixed in the next release of `illuminate/database`: https://github.com/laravel/framework/pull/29943

**Comment by Tukizz** [comment]
Please Close this issue if it has been fixed

**Comment by Tukizz** [comment]
Please Mention me if this issues was fixed

**Comment by nnadhif** [comment]
When the next release (6.0.3) will be published?

**Comment by driesvints** [comment]
I'll try to get this fixed with Taylor later today.

**Comment by driesvints** [comment]
v6.0.3 of the illuminate components should be released by now.
