### ISSUE TITLE
Add --auth option laravel installer

### ISSUE THREAD

**Issue by nowendwell** [laravel/ideas#1833]
I would like to PR this to the installer in order to automatically pull in the laravel/ui package and do a make auth. Let me know if this is something worth while.

Instead of
```bash
laravel new project
composer require laravel/ui
php artisan ui:auth
```
simply add the --auth command option
```bash
laravel new project --auth
```

I have implemented this in the  tightenco/lambo#72 repo and would just port that over to the installer.

Let me know if you guys are up for this and I'll do a pr to the laravel/installer repo.

**Comment by mattstauffer** [comment]
I'm very interested in the idea--I don't love how many steps it takes to do this. I don't run into it because I use Lambo, but it definitely makes the pitch of "how few steps it takes to get a simple, auth-enabled, Laravel app up and running" harder to make.

**Comment by mattstauffer** [comment]
Taylor the PR suggesting this, which means it won't be merged. For anyone looking in this direction in the future, check out Lambo, which can help you automate this and other tasks you might commonly perform when spinning up a new Laravel app.

https://github.com/tightenco/lambo/
