### ISSUE TITLE
[Proposal] Document the Pipeline

### ISSUE THREAD

**Issue by DarkGhostHunter** [laravel/ideas#1836]
[I made an article about the Pipeline](https://medium.com/@DarkGhostHunter/laravel-the-hidden-pipeline-part-1-a4ae91fc55a4). While it's a niche class, the awesomeness of it should have it's own documentation, even more considering it's pivotal for [Route Middleware](https://laravel.com/docs/master/middleware#assigning-middleware-to-routes) and [Job Middleware](https://laravel.com/docs/master/queues#job-middleware).

It's kind of a challenge to explain it using a well common use case.

**Comment by GC-Mark** [comment]
Nice article, thanks for sharing 👍
