### ISSUE TITLE
Support for Markdown panels and tables in Notification mail messages

### ISSUE THREAD

**Issue by pauladams8** [laravel/ideas#1842]
It would be convenient to use the Markdown panel component (and even tables too) with the Notification emails.

Example:
```
public function toMail($notifiable)
{
    $url = url('/invoice/'.$this->invoice->id);

    return (new MailMessage)
                ->greeting('Hello')
                ->line('One of your invoices has not been paid')
                ->panel('Warning: your account will be closed if you do not pay your invoice')
                ->action('View Invoice', $url)
                ->line('Thank you for using our application!');
}
```

Which would return something that might look like this (but in Laravel markdown of course, not a GitHub code block):
```
Warning: your account will be closed if you do not pay your invoice
```

Or for a table, a Markdown rendered table could be automatically generated directly from a PHP array:
```
public function toMail($notifiable)
{
    $url = url('/invoice/'.$this->invoice->id);

    return (new MailMessage)
                ->greeting('Hello')
                ->line('Here are some details about your invoice')
                ->table([
                'id' => '20',
                'description' => 'Some random invoice',
                'due_date' => '5 years ago'
                ])
                ->action('View Invoice', $url)
                ->line('Thank you for using our application!');
}
```
Rendered:

Name | Value
---- | -----
Id | 20
Description | Some random invoice
Due date | 5 years ago

**Comment by hubertnnn** [comment]
I think going too deep in how this simple message is build might cause more harm than help.
Where should be the panel? 
Where should be the table? 
After or before action?
After or before lines?
Will it be compatible with different mail clients?

I would rather have the ability to return a Mailable instead of MailMessage for all the more complex situations and use a custom template.

**Comment by pauladams8** [comment]
I tend to use the notification messages for purely transactional messages (eg your card has expired, please update it or to alert the user of problems with their account).

Perhaps the table functionality would be unnecessary, but it would be useful to have support for Markdown quotes / panels so I could quote error messages back to the user, for example.

**Comment by pauladams8** [comment]
Example:

A problem occurred whilst processing your payment. Please contact support.

> Some error from the Stripe API
