### ISSUE TITLE
[RFC] SphinxQL support

### ISSUE THREAD

**Issue by wucdbm** [laravel/ideas#1846]
Heya,

I was using illuminate/database's query builder to simplify sphinx queries and stumbled upon LIMIT / OFFSET where sphinx QL requires the shorthand LIMIT 40, 20, rather than LIMIT 20 OFFSET 40.

I dug into the codebase and made my own SphinxConnection that uses my own SphinxQlGrammar that overrides compileLimit and compileOffset, so that works now.

ConnectionFactory also needs two new cases for `sphinx` driver config option where it returns a `MySqlConnector` @ `createConnector` and the aforementioned `SphinxConnection` @ `createConnection`.

I also have the necessary code to support the max_matches option @ queries with code completion @ query builder (Connection class needs to be properly annotated for that to work): `SELECT ... LIMIT 1000, 10 OPTION max_matches = 1000`

Would anyone be interested in that?

Generally, for my own use I only need the Connection. Supporting this in the library would allow me to use it like so, without hacking around and constructing the connection myself. I guess that'd be useful in Laravel itself too, being able to configure a sphinx connection.

```php
<?php 

public static function create(
        string $driver, string $host, string $port,
        string $db, string $user, string $pass
    ): Connection {
        $capsule = new Capsule;

        $capsule->addConnection([
            'driver'    => $driver,
            'host'      => $host,
            'port'      => $port,
            'database'  => $db,
            'username'  => $user,
            'password'  => $pass,
            'charset'   => 'utf8',
            'prefix'    => '',
        ]);

        return $capsule->getConnection();
    }
```

```php
<?php

$connection = MyFactory::create('sphinx', 'host', ...$params);
```

Else:

```php
<?php 

public static function createSphinxConnection(
        string $driver, string $host, string $port,
        string $db, string $user, string $pass
    ): Connection {
        $config = [
            'driver'    => $driver,
            'host'      => $host,
            'port'      => $port,
            'database'  => $db,
            'username'  => $user,
            'password'  => $pass,
            'charset'   => 'utf8',
            'prefix'    => '',
        ];

        $connector = new MySqlConnector();
        $pdo = $connector->connect($config);

        return new SphinxConnection($pdo, $config['database'], $config['prefix'], $config);
    }
```

**Comment by mfn** [comment]
I think this would be a perfect fit for a Laravel package instead of being in core. SphinxQL currently isn't very popular (in relation to the currently supported ones in core).

**Comment by hubertnnn** [comment]
I also think it should be a package, rather than core.
Also I think it would be better to make it a scout driver than database one.

**Comment by wucdbm** [comment]
I'm primarily using Symfony, I just knew for years that Laravel has a decent query builder. So I'll also have to look into how scout actually works.
For that matter though, it's in database on purpose, because my sphinx use-case was aggregating huge amounts of data real-time, rather than full text search, and it does so at amazing speeds.

I guess then for the time being, I could make a package and put it on packagist, I believe I came across an option for a custom connection factory or something, but I'll have to look into it again.

**Comment by wucdbm** [comment]
As a followup, I've published a package at https://github.com/wucdbm/sphinx-query-builder that covers my current needs for aggregating big chunks of data, hopefully that'd be useful to someone else too, plus some basic examples in its readme.
