### ISSUE TITLE
[Help] Is there any way to map relative model objects to own fields?

### ISSUE THREAD

**Issue by mevanso01** [laravel/ideas#1853]
Hello, everyone.
I'm struggling to solve an issue in Eloquent Model class.
Now I can get relative Model objects using Eloquent Relations.
```
class Product extends Model
{
    protected $table = "product";

    protected $fillable = [
        'id', 'title', 'serial_code', 'name', 'category_id', 'use_count', 'purchase_date', 'supplier_name', 'purchase_price', 'quotation_price', 'previous_use_date', 'previous_use_event_name', 'use_history', 'status'
    ];

    public function category()
    {
        return $this->hasOne('App\Category', 'id', 'category_id');
    }

    public $timestamps = true;
}
```

But what I want is to automatically map relations to fields automatically.
When I run this statement `Product::all();`, I hope each item to contain **category** field holding **Category** Model object.
Thanks

**Comment by mobayen** [comment]
here is not to get help!

btw: for: Eager Loading Multiple Relationships](https://laravel.com/docs/5.8/eloquent-relationships#eager-loading)

**Comment by oprypkhantc** [comment]
This is not an idea. Refer to the docs.
