### ISSUE TITLE
Relationships on pivot models

### ISSUE THREAD

**Issue by stancl** [laravel/ideas#1857]
I have an `OrderProduct` pivot model. On that model, I define a relationship, `options`:

```php
public function options()
{
    return $this->belongsToMany(Option::class, 'order_product_options')
        ->using(OrderProductOption::class);
}
```

I think calling `$order->products()[0]->options` should return the options of the ordered product, not the options of the product.

**Comment by rimace** [comment]
Wouldn't it be easier to just define it as following:

```
public function options()
{
    return $this->hasMany(OrderProductOption::class);
}
```
This returns a collection of the OrderProductOption models, exactly how you want it.

**Comment by stancl** [comment]
It would and it's what I went with. I was trying to get belongsToMany to work because I wanted these relationships to integrate nicely with Nova.
