### ISSUE TITLE
isEmpty operation on Builder or Eloquent Collection

### ISSUE THREAD

**Issue by dallincoons** [laravel/ideas#1860]
I find it's common to see some form of `$model->relation()->count() == 0`. Would it be appropriate to add an `isEmpty` method to either the Builder or Eloquent Collection class that runs a `count(*)` query?

**Comment by rimace** [comment]
Isn't there already one for Eloquent Collection? See https://laravel.com/docs/6.x/collections#method-isempty
I'm not sure about the Query Builder though.

**Comment by dallincoons** [comment]
> Isn't there already one for Eloquent Collection? See https://laravel.com/docs/6.x/collections#method-isempty
> I'm not sure about the Query Builder though.

That method is on the Support Collection class.

**Comment by blakethepatton** [comment]
What about `$model->has($relation)`?

**Comment by dallincoons** [comment]
I actualy think `Model::exists()` should suffice for most purposes.
