### ISSUE TITLE
Make @empty works with collections

### ISSUE THREAD

**Issue by josegus** [laravel/ideas#1864]
Blade @empty only works with arrays, i suggest to make it compatible with collections, since most of my iterable data passed to views are instance of collection.

Currently this must be done:

@if ($users->isNotEmpty())
    // Show users..
@else
    // No users found
@endif

My suggestion:

@empty ($users)
    // Show users..
@else
    // No users found
@endempty

Seems more expressive to me.

**Comment by ManojKiranA** [comment]
you can use `forelse` Blade Directive

```
@forelse ($users as $user)
This is user {{ $user->id }}
@empty  
No users found.
@endforelse
```

**Comment by josegus** [comment]
@ManojKiranA thanks
