### ISSUE TITLE
Route function that considers domain

### ISSUE THREAD

**Issue by shreyanshpanchal** [laravel/ideas#1866]
In my `web.php` file i have following:

```
Route::get('/homepage', 'VisitorController@homepage')->name('homepage');

Route::domain('superadmin.'.config('app.url'))
    ->group(base_path('app/Http/Routes/superadmin.php'));

Route::domain('user.'.config('app.url'))
    ->group(base_path('app/Http/Routes/user.php'));
```

Now when i'm on a page that is defined in `superadmin.php`, And i try to generate link to the homepage by doing `{{ route('homepage') }}`.

The link is built like this: `superadmin.appurl.com/homepage`.
I feel that ideally the link should be `appurl.com/homepage` even when i'm under `superadmin` subdomain.

Can i get your opinion on this please?

**Comment by rs-sliske** [comment]
route helper takes an optional parameter for if it should generate absolute or relative url (which defaults to relative)

**Comment by shreyanshpanchal** [comment]
Let's say if you're on `https://superadmin.appurl.com`
And you try to generate route for `homepage`.

A) `{{ route('homepage',[],true) }}` will create `https://superadmin.appurl.com/homepage`
B) `{{ route('homepage',[],false) }}` will create `/homepage`.

If you click through the scenario **B)** you'll still be redirected to `https://superadmin.appurl.com/homepage`

The solution you're proposing, Doesn't actually solve the problem.

Remember we're trying to navigate between the root domain & subdomain.

Route "Homepage" is actually at `https://appurl.com/homepage`.

So the ideal [link/redirection] should be at `https://appurl.com/homepage`.

**Comment by shreyanshpanchal** [comment]
@JeffreyWay @taylorotwell @themsaid 
I'm really sorry for tagging you guys.
I would love to send a PR if someone can guide me on right path.

> If everyone agrees that this needs fixing

**Comment by julienbourdeau** [comment]
If you start using domain in your route definitions, you probably want to define the domain everywhere. 

There is no reason `homepage` would generate a path the app url and not a subdomain since you didn't give it a domain. I'm pretty sure `/homepage` will respond to all 3 subdomains with the same content.

Try the following and let me know how it worked.

```php
Route::domain(config('app.url'))->get('/homepage', 'VisitorController@homepage')->name('homepage');
```

**Comment by shreyanshpanchal** [comment]
Thank you so much for the input man.
I don't know why this didn't come to me intuitively.

This was misunderstanding on my part.

I just had to use `domain` on `homepage` routes.

Thanks so much again man. 
Cheers :tada:
