### ISSUE TITLE
Implement Model::onlyWith('relationship');

### ISSUE THREAD

**Issue by JamesFreeman** [laravel/ideas#1873]
I need to be able to turn off the default `$with` attributes for certain model queries.

Model: 
```php
class Product extends Model{
    protected $with = ['prices', 'colours', 'brand'];

    public function colours(){ ... }
    public function prices(){ ... }
    public function brand(){ ... }
}
```

At the moment, I would only be able to achieve this by doing:
```php
Product::without(['prices', 'colours'])->get();
```
If I was ever to add future relationships to my base model, they would be included by default, it would be nice to be able to do something like:

```php
Product::onlyWith(['brand']);
```

Is this something that I can currently already do? 
Would this be something that would be worth my time producing a PR to add this functionality? Can you think of any footfalls with this?

**Comment by mpyw** [comment]
Try this

```php
Product::make()->newModelQuery()->with(['brand']);
```

**Comment by mpyw** [comment]
Quick implementaion via trait

```php
trait EagerLoadsOnly
{
    public static function onlyWith(...$args)
    {
        return static::make()->newQueryWithoutRelationships()->with(...$args);
    }
}
```

```php
class Product extends Model
{
    use EagerLoadsOnly;

    protected $with = ['prices', 'colours', 'brand'];

    public function colours() { ... }
    public function prices() { ... }
    public function brand() { ... }
}
```

```php
dd(Product::onlyWith(['brand'])->get());
```

**Comment by oprypkhantc** [comment]
Imho, no. You should never use global `$with` when these aren't used literally everywhere in your project with one or two exceptions, in which case you can do `newQueryWithoutRelationships` as described above.

**Comment by mpyw** [comment]
> You should never use global `$with` when these aren't used literally everywhere in your project with one or two exceptions

I agree
