### ISSUE TITLE
[Proposal] Artisan Command Enhancement For Migration

### ISSUE THREAD

**Issue by prezire** [laravel/ideas#1875]
Would it be possible to find a workaround on a contextual level during migration? This might probably boil down to team processes however, would it be possible to pass a **required parameter**? Hopefully the context acts like a cache key that stores the previous state of the database before any migration is run. The value can be something like a branch name from a VCS.

`php artisan migrate --context=some_unique_branch_name`

The thing is, most team workflows would be to SSH to test servers, switch Git (or other VCS) branches along with different DB schema and unintentionally run migrations. This workflow is related to updates like renaming tables, fields, indices and so forth, mostly for production servers with already lots of data in them. So the option of dropping all tables and data even for testing is not ideal.

I haven't thought about the full details or workflow as of yet but hopefully anyone can find a better workaround. Suggestions are welcome.

**Comment by oprypkhantc** [comment]
I.. don't entirely get it. 

If you switch branches, you **have** to run migrations, otherwise things won't work. If your migrations include a `down` method, you can rollback them as well to switch to an older branch. It works in both directions flawlessly.

**Comment by prezire** [comment]
In that case, the current logged user has to always perform the **down** migration before logging out the **shared server** once he's done. I was thinking since the framework guides developers about the workflow (MVC, facades, migrations) every step of the way, it might be better to integrate the migration behavior to any VCS. Switching to different branches with different migration structures messes up the database entirely.

**Comment by oprypkhantc** [comment]
If there's only one server available, there should only be one schema. If you want your QA team to test things independently, it's probably better for them to the project(s) up and running on their PCs. It's the way it works for us and the QA team rarely has any problems with something being messed-up due to migrations.

I'm not sure what would be the workflow. You'll have to be changing the schema all the time either way, regardless of whether you go with simple migrations or not.

**Comment by netpok** [comment]
I would say in this case a different branch should use a different database, this could be done by updating the `.env`.

A git hook could do this (and create the database and run the migrate command) when you pull or change branch. Another git hook could remove the testing database when the branch is removed from the server.

**Comment by prezire** [comment]
A good one there @netpok . I was thinking mostly about the framework to solve this kind of workflow. I guess the solution should come from the VCS since the changes of the structure was caused by VCS itself in the first place.

I think this is closed. Can anyone like me, just close a ticket?

**Comment by drbyte** [comment]
@prezire since you opened the ticket, you can close it by clicking the Close button below.

**Comment by prezire** [comment]
Awesome!. Thanks @drbyte .
