### ISSUE TITLE
[proposal] Add `.vagrant` to .gitignore

### ISSUE THREAD

**Issue by howlowck** [laravel/ideas#1877]
## Background:
When using [Per-Project Setup] of Homestead, user would run `vagrant up` inside of the project directory. This causes `vagrant` to create a `.vagrant` directory to house all of its caching and provider-specific artifacts. This `.vagrant` directory should not be committed to git.

There is already evidence for excluding environment-specific files for the per-project homestead setup in the `.gitignore` file (see [Homesteam.yaml in .gitignore](https://github.com/laravel/laravel/blob/bb969c61d41ec479adbe4a6da797831002b75092/.gitignore#L10))

## Proposal:
Add `.vagrant` to the `.gitignore` file.

**Comment by brunogaspar** [comment]
One of the many attempts to do so https://github.com/laravel/laravel/pull/5078

I can also add, on top of what Taylor said, that you can create a global `.gitignore`.

**Comment by howlowck** [comment]
ok that makes senses..
