### ISSUE TITLE
Allow LazyCollection creation from Traversables

### ISSUE THREAD

**Issue by netpok** [laravel/ideas#1880]
Currently the only way to create a lazy collection is to pass a closure which is in many case contains only a yield from statement.

In most cases I think it would be great to create the LazyCollection from the Traversable itself.

Currently I see two ways of this:

1. Accept Traversables as source, this would allow running `LazyCollection::make($generator)`. While this could work it would be a breaking change and would require using `LazyCollection::make(iterator_to_array($generator))` to achieve current behaviour.

2. Introduce a new `LazyCollection::from(Traversable $source)` method which accepts the traversable and creates an instance with that.

For example this would allow creating lazy collections from stripe collections like this: `LazyLollection::from(StripeCustomer::all()->autoPagingIterator())`

Mentioning @JosephSilber to share his opinions, because he made the LazyCollection implementation.

**Comment by JosephSilber** [comment]
`getArrayableItems` already calls `iterator_to_array`:

https://github.com/laravel/framework/blob/869f02783a49cd0e16c66c0d362d2e4ea371f4b6/src/Illuminate/Support/Traits/EnumeratesValues.php#L817-L819

**Comment by JosephSilber** [comment]
In an earlier version of the API I had actually designed it that way.

I later removed it because it can lead to confusing semantics around the immutability of a lazy collection:

```php
$array = [1, 2, 3, 4, 5];

$collection = LazyCollection::make($array)->skip(1);

array_shift($array);

$collection->first(); // 3 :open_mouth: 
```

Maybe doing it only for `Traversable`s wouldn't lead to this confusion :man_shrugging:

**Comment by netpok** [comment]
I just realized that the LazyCollection creates a new generator on every call, so if I'm creating it from an iterable it substantially changes it's behaviour.

for example:

```php
$closure = function ($limit, &$count){
    while ($count < $limit){
        yield 1 + $count++;
    }
};

// just like passing an iterator
$generator =  $closure(5, $count);
$data = LazyCollection::make(function () use ($generator) {
    yield from $generator;
});

$data->take(2)->all(); // [1, 2]
$data->all(); // [2, 3, 4, 5]

// usual make syntax
$data = LazyCollection::make(function () use ($closure) {
    yield from $closure(5, $count);
});

$data->take(2)->all(); // [1, 2]
$data->all(); // [1, 2, 3, 4, 5]
```

So right now the QueryBuilder cursor creates a new cursor for each "end call". Is this even desired? I mean generally LazyCollections are evaluated once, but there is always a possibility to evaluate them more times.

**Comment by JosephSilber** [comment]
> Is this even desired?

Yes. That's the nature of lazy enumeration. C#'s `IEnumerable`s work the same way.

I've actually toyed with a `remember()` method, which would cache all values being enumerated. I never got a chance to fully finish it (it's more complicated than it may seem at first).

**Comment by netpok** [comment]
Thanks for the info, I don't have much experience with C#.

I had an idea about the `remember()` method, but after trying it I'm not sure if it's possible.
Here is my implementation: https://github.com/netpok/laravel-framework/tree/feature/lazycollection-remember

The problem is once the source was exhausted I don't think there is a possibility to load new items.

**Comment by JosephSilber** [comment]
That implementation is a little naive.

You can't simply exhaust the cache and call it a day. A different enumeration may hydrate additional items into the cache after this one has exhausted it.

**Comment by netpok** [comment]
Yes, not a little and I had the same problem, that's why I wanted to close this issue (instead of just sending a reply), because I don't see a workaround for this and it also affects my `from()` idea.

Thanks for answering all my questions.

**Comment by JosephSilber** [comment]
I finished my implementation of `remember`.

Here's the PR for your reference: https://github.com/laravel/framework/pull/30443

**Comment by netpok** [comment]
Isn't this implementation has the same cache exhaustion problem as mine?

```php

    public function testRemember2()
    {
        $source = [1, 2, 3, 4];

        $cached = ($collection=LazyCollection::make(function () use (&$source) {
            yield from $source;
        }))->remember();
        $this->assertSame([1, 2, 3, 4], $cached->all());

        $source[] = 5;
        $this->assertSame([1, 2, 3, 4, 5], $collection->all());
        $this->assertSame([1, 2, 3, 4, 5], $cached->all());
    }
```

It will fail on the last assertion. I also tried with my implementation and all your provided test are pass with that implementation.

**Comment by JosephSilber** [comment]
> Isn't this implementation has the same cache exhaustion problem as mine?

No.

> It will fail on the last assertion.

It should. A lazy collection's source should be immutable. Why are you surprised that caching a source's values, then changing the source, doesn't reflect the changes in the cached values?

> I also tried with my implementation and all your provided test are pass with that implementation.

I just tried it, and it fails in `testRememberWithTwoRunners`.

**Comment by netpok** [comment]
> It should. A lazy collection's source should be immutable. Why are you surprised that caching a source's values, then changing the source, doesn't reflect the changes in the cached values?

Looks like I misunderstood the original problem, I thought the problem was that it cant load more elements while just the internal cache was f***ed up.

> I just tried it, and it fails in testRememberWithTwoRunners.

I don't know how I made that pass, maybe forgot to save something, you're right.

Thanks for helping me understand where I was wrong. (I really hope my previous comment didn't sound like "Hey, I did the same" as it wasn't meant to be that).

**Comment by JosephSilber** [comment]
> Looks like I misunderstood the original problem

I guess this comment wasn't clear enough:

> You can't simply exhaust the cache and call it a day. A different enumeration may hydrate additional items into the cache after this one has exhausted it.

What I was trying to point out is the following scenario:

1. Enumeration A pulls 1 item
2. then enumeration B pulls 2 items
    - 1 from the cache
    - then 1 new one (and adds that new one to the cache)
3. then enumeration B pulls another item.

In your implementation, since enumeration A has exhausted the cache (which happens to have been empty), it won't revisit it. So enumeration A will end up with items `[1, 3]` instead of `[1, 2]`.

This is exactly what the `testRememberWithTwoRunners` checks for.

---

Hope that was clearer 🙏
