### ISSUE TITLE
Introduce HigherOrderWhenProxy

### ISSUE THREAD

**Issue by netpok** [laravel/ideas#1881]
I propose we introduce proxies for when on collections and the query builder.

Example use cases:
- Collection sorting: `$collection->when($field)->sortBy($field)`
- Database filtering: `User::when($coreDataOnly)->select(['name', 'email'])->get()`

Working principle:
- if the value is true, then the called method is called on the target object and the result is returned
- if the value is false, then the called method is skipped and the target is returned

**Comment by driesvints** [comment]
Closing as this idea was rejected by Taylor.

**Comment by netpok** [comment]
This feature was implemented in 9.x via [#37632](https://github.com/laravel/framework/pull/37632)
