### ISSUE TITLE
Add collection like String object

### ISSUE THREAD

**Issue by zendraxl** [laravel/ideas#1887]
Right now if we want to do any manipulation with strings we face same problem like with an array before collections where we have to read the code inside out.

```php
$title = Str::title(Str::replaceArray('_', [' '], Str::snake('fooBar')));
```

Also Str object in Laravel does not accept the string that is being manipulated as the first argument across all methods like `replaceArray()`.

It would be great to bring that kind of power and functionality to Laravel and surpass current language limitations.

```php
$title = (new Str('fooBar'))->snake()->replaceArray('_', [' '])->title()->get();
```

Also add helper function to make it even cleaner.

```php
$title = str('fooBar')->snake()->replaceArray('_', [' '])->title()->get();
```

Having `dd()` on that object is a must :D

```php
$title = str('fooBar')->snake()->replaceArray('_', [' '])->dd()->title()->get();
```

I have an implementation ready but I'm not sure will this play well with `Macroable` trait.

**Comment by mpyw** [comment]
Not so bad. However, `Collection` class is very often carried around as it is (not as an primitive `array` type), while the `String` class seems a bit strange. Primitive `string` type argument looks proper in the most cases. I think this feature is a little over-engineered.

**Comment by mpyw** [comment]
If such a statement appears occasionally, take the following solution. The readability will be improved.

```php
$title = Str::snake('fooBar');
$title = Str::replaceArray('_', [' '], $title);
$title = Str::title();
```

**Comment by netpok** [comment]
You should have a look on [Stringy](https://packagist.org/packages/danielstjules/stringy)

**Comment by zendraxl** [comment]
@mpyw for me the approach I've proposed is far more readable than having multiple assignments to the same variable. Like I've said, you have methods which do not except the string you are modifying as a first argument.

@netpok the thing I dislike about Stringy is that the method names do not align with the names of the Laravel's `Str` object so you have to learn another API to use it.

**Comment by julienbourdeau** [comment]
@zendraxl I think the new Symfony String component is a great solution: 

https://symfony.com/doc/master/components/string.html

```php
$text = (new UnicodeString('This is a déjà-vu situation.'))
    ->trimEnd('.')
    ->replace('déjà-vu', 'jamais-vu')
    ->append('!');
// $text = 'This is a jamais-vu situation!'
```

You'll be missing thing like chaining `dd` but maybe there is an easy way to add it.

**Comment by zendraxl** [comment]
@julienbourdeau that looks nice. Thanks for suggestion. I'm thinking to create a PR to the framework and see what happens. If it does not get accepted then I can create a package and use it in my projects or try libraries you guys suggested.

**Comment by mpyw** [comment]
I was reluctant to support this at the framework level, but it looks nice given that Symfony has already adopted it.

**Comment by zendraxl** [comment]
PR wasn't accepted.

**Comment by julienbourdeau** [comment]
Will you turn it into a package?

**Comment by zendraxl** [comment]
@julienbourdeau sorry that I didn't follow up on this. After [PR](https://github.com/laravel/framework/pull/30363) was rejected I've created a [package](https://github.com/zendraxl/laravel-string).
