### ISSUE TITLE
Get a random Eloquent model instance

### ISSUE THREAD

**Issue by HenkPoley** [laravel/ideas#1888]
E.g. `User::all()->random()` without first fetch **all** the users. 

Example: `User::randomInstance(3)`, randomly get 3 Users from your database.

Useful for the Database Seeder

Would answer: https://stackoverflow.com/questions/44102483/in-laravel-how-do-i-retrieve-a-random-user-id-from-the-users-table-for-model-fa

**Comment by 36864** [comment]
What's wrong with `User::inRandomOrder()->first()`?

**Comment by HenkPoley** [comment]
👍 Probably nothing, if if does lazy loading (doesn't fetch everything at once).

**Comment by 36864** [comment]
You shouldn't need to do anything to make it work.
The Model class forwards the call to the underlying query builder instance and hydrates the models for you.
```>>> User::inRandomOrder()->limit(3)->select('id')->get();
=> Illuminate\Database\Eloquent\Collection {#3603
     all: [
       App\TenantModels\User {#3602
         id: 10,
       },
       App\TenantModels\User {#3600
         id: 2503,
       },
       App\TenantModels\User {#3582
         id: 523,
       },
     ],
   }```

**Comment by HenkPoley** [comment]
Cool. I was just confused that PhpStorm doesn't understand anything of the black magic that Laravel Eloquent does.

Feels very much paper and bubblegum, but I guess if it works, it works 🤷‍♂️. Just no guidance if it's correct, except when it breaks while using it.
