### ISSUE TITLE
Route model binding not working in packages

### ISSUE THREAD

**Issue by innoflash** [laravel/ideas#1898]
Can you guys fix that in the next release?

**Comment by martinbean** [comment]
@innoflash In your package routes, you need to make sure they’re wrapped in at least the `bindings` middleware. When they are, route-model bindings will be ran.

**Comment by innoflash** [comment]
@martinbean thanks for that nice piece. Let me see to it now

**Comment by innoflash** [comment]
> @innoflash In your package routes, you need to make sure they’re wrapped in at least the `bindings` middleware. When they are, route-model bindings will be ran.

Thanks buddy, its working perfect
