### ISSUE TITLE
[Lumen] Custom Morph Map Name Relation Not Working

### ISSUE THREAD

**Issue by Tukizz** [laravel/ideas#1899]
i have a problem with polymorph relation in Lumen
default polymorph name in database inserted like this `App\Models\Comment`
but i want this polymorph name inserted like this `Comment`
this my boot  `AppServiceProvider` code

```php
namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Http\Resources\Json\Resource;
use Illuminate\Database\Eloquent\Relations\Relation;

class AppServiceProvider extends ServiceProvider
{

    public function register()
    {
        //
    }

    public function boot()
    {
        Relation::morphMap([
            'Comment'   => Comment::class,
        ]);

        Resource::withoutWrapping();
    }
}
```
when i use Laravel, this code work with inserted name 'Comment'
but in Lumen this not working

i use lumen 6.0

if you have a suggest or a example code let me know

**Comment by timrspratt** [comment]
Is this an exact paste of your AppServiceProvider, because the import for `App\Models\Comment` isn't included

**Comment by Tukizz** [comment]
it's fixed !
i change `Comment::class` to `App\Models\Comment`
thanks for remind me
