### ISSUE TITLE
Can not find where i dd() in test suite

### ISSUE THREAD

**Issue by foremtehan** [laravel/ideas#1903]
Sometimes i forgot where i did ```dd()``` in my test suite, I think it would be nice we could find the place in ```dd()``` method.

![Capture](https://user-images.githubusercontent.com/53290883/67758576-316d7f80-fa53-11e9-9c12-b341edb810da.PNG)

**Comment by ludo237** [comment]
You can `ctrl+f`, or whatever shortcut you have to search in your IDE/Code Editor, to find them....

**Comment by julienbourdeau** [comment]
It happens to me when I start dding in the vendor directory and I can find it anymore. Because there is A LOT of code and it’s typically ignored in your search.

**Comment by michaeldyrynda** [comment]
Use the `ddd()` helper instead in future. It’ll give you a stacktrace, too, so you can find your rogue debug 👍🏻

**Comment by martinbean** [comment]
@foremtehan Not sure what this has to do with Laravel.

Use your editor/IDE to find “dd(” in your codebase.
