### ISSUE TITLE
Nested route binding

### ISSUE THREAD

**Issue by inxilpro** [laravel/ideas#1911]
This is a follow up to a [Twitter conversation about this feature](https://twitter.com/inxilpro/status/1191365194016006145).

## The set up

Suppose you're developing an education app, and for SEO purposes, you'd like your URLs to look something like:

```
/courses/intro-to-laravel/implicit-route-binding-101
```

So, you set up your route, models & controller like this:

```php
Route::get('/courses/{course}/{page}', [PageController::class, 'show']);
```

```php
class PageController extends Controller
{
    public function show(Course $course, Page $page) {
        return view('courses.page', compact('course', 'page'));
    }
}
```

```php
class Course extends Model
{
    public function pages() {
        return $this->hasMany(Page::class);
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }
}

class Page extends Model
{
    public function course() {
        return $this->belongsTo(Course::class);
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }
}
```

## The problems

This introduces two particular issues:

  1. If you call `$page->course->title` this will force Laravel to query the database again, because the course and the page were loaded independent of eachother.

  2. There's no guarantee that `$page` is actually part of `$course`—if someone goes to `/courses/advanced-react/implicit-route-binding-101` everything will load correctly, but the course and the page will be mismatched.

## Userland solutions

Right now, one of the easiest solutions is something like this:

```php
class PageController extends Controller
{
    public function show(Course $course, Page $page) {
        // Make sure the page is a child of the course
        abort_unless($page->course_id === $course->id, 404);

        // And manually set the relationship
        $page->setRelation('course', $course);

        return view('courses.page', compact('course', 'page'));
    }
}
```

Or, a little more magical way to approach it would be to add something like this to our `Page` model, so it could automatically load via the `Course` if it exists:

```php
public function resolveRouteBinding($value)
{
    $course = Request::route('course');

    if ($course instanceof Course) {
        return $course->pages()
            ->where($this->getRouteKeyName(), $value)
            ->firstOrFail()
            ->setRelation('course', $course);
    }

    return parent::resolveRouteBinding($value);
}
```

## Potential framework solutions

But as a _PHP artisan_, I want something more elegant :)  I can think of a few possible ways to approach this:

  1. **The most auto-magic solution** would be to update the implicit route binding logic to just apply this automatically for us. The basic logic could be something like:

      - The first route parameter is `{course}` — resolve that as usual
      - The second route parameter is `{page}` — since we've already resolved a prior parameter, look to see if that resolved model has a relationship called `page`
      - If the relationship exists, resolve the `{page}` parameter through that relationship. If not, use the usual resolution logic.

  2. **An opt-in magic option** would be to introduce the above behavior as a new piece of middleware, so that anyone who wants it could swap out `SubstituteBindings` for `SubstituteBindingsAndRelations` or something.

  3. **Another opt-in magic option** would use the same logic above, but only if the model implements a second interface. Right now we have `UrlRoutable` to indicate that an object can be loaded via implicit route binding. We could add something like `NestedUrlRoutable` to indicate that an object can additionally be loaded using nested routing logic. This would mean that you could opt-in on a per-model basis.

  4. **An explicit alternative** would be to opt-in to this behavior at the route definition level, with something like `Route::get(/* ... */)->resolveNested('page')`

## Initial thoughts

I was originally going to suggest option 4 as the best solution, because it makes the behavior explicit. But as I write this out, I find it difficult to imagine a scenario where you might run into a false positive with option 1.  Just think about it:

  - How often are two models bound to a route when there isn't a relationship between the two?
  - If two **unrelated** models are bound to the route, how likely is it that they have a named relationship that matches the other model?

The only case where it could cause a problem is with god objects like `User` that may be related to almost everything. We'd certainly need to provide a way to opt-out of the behavior.

I'm going to start on a PR at some point, but I'd love feedback before I start heading down a particular path. Let me know!

**Comment by inxilpro** [comment]
Another potential solution would be to use reflection on the `resolveRouteBinding()` call. So instead of just passing the value from the route, we could determine what other parameters that method expects and check to see if previously resolved route parameters match them.

```php
public function resolveRouteBinding($value, Course $course = null)
{
    if ($course) {
        return $course->pages()
            ->where($this->getRouteKeyName(), $value)
            ->firstOrFail()
            ->setRelation('course', $course);
    }

    return parent::resolveRouteBinding($value);
}
```

Then, in the `ImplicitRouteBinding` class, we'd use `ReflectionMethod` to determine what the parameters of `resolveRouteBinding` are for the given class, and pass them in if we have them.

I still think just doing it totally automatically isn't a terrible idea, but I think this is a good alternative if we want something more explicit.

**Comment by Frozire** [comment]
I want to add that this isn't a specific use case either, I've continuously run into something like this when designing anything with a community/user aspect. 

Currently working on a project which has this into three layers. `{username}/{list}/(item}`.

In all my cases, I have gone with the `resolveRouteBinding` because the easiest ("Manual" handling in the controller") grows too complicated with project size.

Solution one with automatic handling, although magical, would be great!

**Comment by Frozire** [comment]
I want to add that this isn't a specific use case either, I've continuously run into something like this when designing anything with a community/user aspect. 

Currently working on a project which has this into three layers. `{username}/{list}/(item}`.

In all my cases, I have gone with the `resolveRouteBinding` because the easiest ("Manual" handling in the controller) grows too complicated with project size.

Solution one with automatic handling, although magical, would be great!

**Comment by Lootjs** [comment]
Look at my decision https://github.com/laravel/framework/pull/30553
Nested routes declared like this:
```
Route::get('/courses/{course}/{page__from__course}', [PageController::class, 'show']);
```

**Comment by Lootjs** [comment]
I would prefer this syntax: `/courses/{course}/{course.page}`, but SymfonyRoute forbids using a dot.
