### ISSUE TITLE
Why doesn't an internal Repository Module

### ISSUE THREAD

**Issue by voyula** [laravel/ideas#1913]
Eloquent ORM is the have a many features but if application is biggest, will have a problem with encapsulate and manage all ORM commands.

Why doesn't an internal Repository management for encapsulation of all database process.

**Comment by mfn** [comment]
There is and it works exactly as you suggested; it's only the Builder / ORM stuff: https://github.com/illuminate/database

**Comment by voyula** [comment]
@mfn No, this is not a Repository Pattern.

**Comment by mfn** [comment]
I see. You phrasing was hard to decipher and I did my best to understand the question. I thought you were talking about why the database can't be used standalone, as a separate code repository 🤷‍♀️

I'll try one more to understand what you're after. This isn't per se called repository pattern, I believe what you're after is a `EntityManager` (unless I'm wrong again).

I doubt Eloquent will ever have one. If you want one, you can use Doctrine.

**Comment by voyula** [comment]
@mfn Thanks!

Doctrine Entity manager is good work, yes i want a like this.
A Repository Pattern and UnitOfWork Pattern. :)

**Comment by mfn** [comment]
You can use Doctrine with Laravel
