### ISSUE TITLE
Error when using translation strings as keys, when there is a lang file with same name as the key

### ISSUE THREAD

**Issue by alwintom** [laravel/ideas#1936]
- Laravel Version: 6.5.1
- PHP Version: 7.3.0
- Database Driver & Version: mysql 5.7.17

### Description:
When I use a translation string as key and there happens to be a file inside the `resources/lang` folder with the same name as the string being translated, laravel throws an error:
`htmlspecialchars() expects parameter 1 to be string, array given`

### Steps To Reproduce:
In a blade file include this line:
```html
<button> {{ __('validation') }} </button>
```

### Additional information:
On linux servers the error is thrown only if the string being validated matches exactly (same case) with one of the files inside the `lang` directory. So the following blade snippet will not cause error:
```html
<button> {{ __('Validation') }} </button>
```

However the above snippet will cause the error on a windows server. I assume this is because in windows file names are case-insensitive.

**Comment by driesvints** [comment]
Transferring this issue to the ideas repo for now because this technically isn't a bug atm.

**Comment by alwintom** [comment]
@driesvints 

I think the framework already prioritizes entries in the JSON file.

This is the relevant code (located in `Illuminate/Translation/Translator.php`)
```php
    public function get($key, array $replace = [], $locale = null, $fallback = true)
    {
        $locale = $locale ?: $this->locale;
        // For JSON translations, there is only one file per locale, so we will simply load
        // that file and then we will be ready to check the array for the key. These are
        // only one level deep so we do not need to do any fancy searching through it.
        $this->load('*', '*', $locale);
        $line = $this->loaded['*']['*'][$locale][$key] ?? null;
        // If we can't find a translation for the JSON key, we will attempt to translate it
        // using the typical translation file. This way developers can always just use a
        // helper such as __ instead of having to pick between trans or __ with views.
        if (! isset($line)) {
            [$namespace, $group, $item] = $this->parseKey($key);
            // Here we will get the locale that should be used for the language line. If one
            // was not passed, we will use the default locales which was given to us when
            // the translator was instantiated. Then, we can load the lines and return.
            $locales = $fallback ? $this->localeArray($locale) : [$locale];
            foreach ($locales as $locale) {
                if (! is_null($line = $this->getLine(
                    $namespace, $group, $locale, $item, $replace
                ))) {
                    return $line ?? $key;
                }
            }
        }
        // If the line doesn't exist, we will return back the key which was requested as
        // that will be quick to spot in the UI if language keys are wrong or missing
        // from the application's language files. Otherwise we can return the line.
        return $this->makeReplacements($line ?: $key, $replace);
    }
```

So I think the change we need to do is chnage `126` from
```php
return $line ?? $key;
```

to
```php
return ($line && is_string($line)) ? $line : $key;
```

AND line 134 from:
```php
return $this->makeReplacements($line ?: $key, $replace);
```
to
```php
return $this->makeReplacements(($line && is_string($line)) ?: $key, $replace);
```

Of course it's only an idea and I still have to try it

**Comment by alwintom** [comment]
Created a PR here:
https://github.com/laravel/framework/pull/30666

**Comment by driesvints** [comment]
Unfortunately we've decided to let things be for BC reasons. Please see Taylor's comment here: https://github.com/laravel/framework/pull/30690#issuecomment-559106987
