### ISSUE TITLE
The new Laravel logo is read in Russian as Lagavel

### ISSUE THREAD

**Issue by andrey-helldar** [laravel/ideas#1937]
The new logo of the framework uses the Cyrillic letter "г" (g) - Laгavel (Lagavel).
When using this letter, the name of the framework is read as a derivative word from "lag" and "laravel". That is, a framework consisting of lags.
"Лаг", "лаги" (rus) - "lag", "lags".

Just to know :)

**Comment by brunogaspar** [comment]
https://github.com/laravel/ideas/issues/1744
