### ISSUE TITLE
[Proposal] Add an option to not output 'No scheduled commands are ready to run'

### ISSUE THREAD

**Issue by anasbouzid** [laravel/ideas#1939]
My scheduled commands log looks like:
```
Nov 25 22:19:12 acme php[21678]: No scheduled commands are ready to run.
Nov 25 22:20:11 acme php[21759]: No scheduled commands are ready to run.
Nov 25 22:21:11 acme php[21800]: No scheduled commands are ready to run.
Nov 25 22:22:11 acme php[21844]: No scheduled commands are ready to run.
Nov 25 22:22:12 acme php[21848]: Running scheduled command: '/usr/bin/php7.2' 'artisan' inspire > '/dev/null' 2>&1
Nov 25 22:23:11 acme php[21885]: No scheduled commands are ready to run.
Nov 25 22:24:11 acme php[21927]: No scheduled commands are ready to run.
Nov 25 22:25:11 acme php[21967]: No scheduled commands are ready to run.
...
```
Every minute, `artisan schedule:run` outputs a default message if no event has been run. It can be handy when you run the command manually, but when using Cron it's almost unimportant. I propose an option that doesn't output this message and **keep other logs**. A workaround is to extend [ScheduleRunCommand](https://github.com/laravel/framework/blob/6.x/src/Illuminate/Console/Scheduling/ScheduleRunCommand.php), but I think an option could be better.

**Comment by Namoshek** [comment]
Alternatively you might be able to do this with a shell command like
```sh
php artisan schedule:run | sed -e '/No scheduled commands are ready to run\./d'
```
The `-e $regex` option will remove all lines matching the given regex.

**Comment by anasbouzid** [comment]
@Namoshek I totally forgot I can use `sed` or `awk`, thanks!
