### ISSUE TITLE
Add setJsonAttribute() for setting array to json columns

### ISSUE THREAD

**Issue by ajcastro** [laravel/ideas#1941]
This eliminates using extra variable as suggested in the docs and make the code block more compact.
```php
$user = App\User::find(1);

$options = $user->options;

$options['key'] = 'value';

$user->options = $options;
$user->save();
```

Proposal: 

```php
$user->setJsonAttribute('options', function ($options) {
    $options['key'] = $value;
    return $options;
}); 
```
or simply

```php
$user->options = function ($options) {
    $options['key'] = $value;
    return $options;
});
```

Is this also possible? We just pass the variable by reference so the options attribute will be updated, thus we can eliminate the return statement.
```php
$user->options = function (&$options) {
    $options['key'] = $value;
});
```

**Comment by driesvints** [comment]
This will be solvable with the custom cast functionality coming in Laravel 7
