### ISSUE TITLE
About "Illuminate \ Bus \ Queueable"

### ISSUE THREAD

**Issue by lee2son** [laravel/ideas#1945]
<?php

class Test implements \Illuminate\Contracts\Queue\ShouldQueue
{
    use \Illuminate\Bus\Queueable;
    public $queue="other";
}

// run error
PHP Fatal error:  App\Jobs\Test and Illuminate\Bus\Queueable define the same property ($queue) in the composition of App\Jobs\Test

-------------------
Q:
Why didn't the author take this into account? Does the author discourage this?

**Comment by martinbean** [comment]
@lee2son ???
