### ISSUE TITLE
Higher-order "when" method on Json Resources

### ISSUE THREAD

**Issue by danilopinotti** [laravel/ideas#1962]
Hi!
The concept of this idea is simple.

Currently, when we need show a resource attribute based on a condition, we should use the 'when' method. But, the 'when' method needs a Closure as second argument. When we need choose to show a simple model attribute (for example), the code is quite polluted.

Example:

``` php
class Invoice extends Resource
{
    /**
     * Transform the resource into an array.
     *
     * @param  Request  $request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'payer' => $this->when($this->status == 'processed', function () {
                  return $this->payer;
           })
       ]; 
    }
}
```

My suggestion is allow to use a higher-order 'when' when isn't passed the second argument:
``` php
class Invoice extends Resource
{
    /**
     * Transform the resource into an array.
     *
     * @param  Request  $request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'payer' => $this->when($this->status == 'processed')->payer;
       ];
    }
}
```

**Comment by koenhoeijmakers** [comment]
Why not just `$this->when($this->status === 'processed', $this->payer)`?

**Comment by danilopinotti** [comment]
> Why not just `$this->when($this->status === 'processed', $this->payer)`?

Because, if condition is 'false' and payer is a relationship, payer will be loaded anyway.
