### ISSUE TITLE
[Proposal] Return Form Request errors as json when used through API routes

### ISSUE THREAD

**Issue by Chris1904** [laravel/ideas#1971]
Hi everyone,

Something I regularly do when working on APIs is overwriting the `failedValidation` method like so:

![image](https://user-images.githubusercontent.com/6228425/70928845-b5b99900-1fe6-11ea-8056-3045243b2dac.png)

This way, I receive a response that the frontend can work with:
![image](https://user-images.githubusercontent.com/6228425/70929231-78a1d680-1fe7-11ea-8111-1d746a73ac85.png)

Is this something that could make its way into core? Does anyone handle Form Requests within API calls differently?

Looking forward to some responses 👍🏼

Chris

**Comment by rs-sliske** [comment]
set a request header of Accept: application/json
