### ISSUE TITLE
Hide telescope routes from route:list

### ISSUE THREAD

**Issue by shahvirag** [laravel/ideas#1982]
Artisan command `php artisan route:list` displays all application routes.
After telescope install it shows all telescope routes with application routes.

Ignore telescope routes to display in `php artisan route:list` command just like ignition package routes are doing.

# Before laravel/telescope installed.
![before_telescope](https://user-images.githubusercontent.com/24240840/71397775-7c1b0a80-2644-11ea-8115-e89d6367fb5d.PNG)

# After laravel/telescope installed.
![after_telescope](https://user-images.githubusercontent.com/24240840/71397782-81785500-2644-11ea-9692-56b3c0e9d38f.PNG)

**Comment by Stokoe0990** [comment]
`route:list` should group the routes together in the order they were loaded in.

So all your telescope routes will be next to eachother, horizon routes etc.

Just scroll past. Or if you're looking for something specific, ctrl+F is your friend.

**Comment by shahvirag** [comment]
> 
> 
> `route:list` should group the routes together in the order they were loaded in.
> 
> So all your telescope routes will be next to eachother, horizon routes etc.
> 
> Just scroll past. Or if you're looking for something specific, ctrl+F is your friend.

I can do that. But for simplification we could also add more options to display all routes.
`route:list --with-plugin`

**Comment by julienbourdeau** [comment]
I agree that with Telescope, Horizon or Nova routes, you don't really use them often, but many packages add routes to your app that you're going to use. Then, how do you differentiate them?

**Comment by shahvirag** [comment]
> I agree that with Telescope, Horizon or Nova routes, you don't really use them often, but many packages add routes to your app that you're going to use. Then, how do you differentiate them?

Agreed.
Is there any better way that we can differentiate our application routes with application routes..
Or at least laravel first party package routes are listed differently.

**Comment by stefancroweult** [comment]
Having run into this issue it got me thinking would it be possible to have a method to **exclude** when using the filter options such as `--path`?

Similar to how you can exclude search terms in Google by prefixing with a minus symbol ("-excluded") maybe a similar format can be used?

e.g. php artisan route:list --path=-telescope

I realise that URLs have dashes in them but must be rare people would start with the dash?

**Comment by Stokoe0990** [comment]
What you're asking for already exists @stefancroweult :

https://github.com/laravel/framework/blob/7.x/src/Illuminate/Foundation/Console/RouteListCommand.php#L251

**Comment by stefancroweult** [comment]
Sorry I may not have been clear - I meant **enhancing** the current filters, including `--path`, to allow negation symbols.

So if I wanted all routes **except** /telescope I could do `--path=-/telescope` (note the `-` before `/telescope`)

**Comment by Stokoe0990** [comment]
Then build it and create the PR?

You could add a "not" option. Which shifts items from the array if their path matches the given pattern[s]?

It's really not difficult.

**Comment by stevenweirultimate** [comment]
> Then build it and create the PR?
> 
> You could add a "not" option. Which removes items from the array if their path matches the given pattern[s]?
> 
> It's really not difficult.

But isn't this an Ideas board for discussing...."ideas".... 0_o
