### ISSUE TITLE
30 dec test

### ISSUE THREAD

**Issue by greatrohit007** [laravel/ideas#1990]
### ### ### ### ### ### ### PHP
1. Core (all)
2 .advance
 include and reqiured
 cookies and sessions
3. oop
4. data base
 insert, delete and edit
 ### ### ### ### ### ### ### **JQUERY**
1 jquery effects
2. jquery html
### ### ### ### ### ### ### ### ### CSS
1. boader
2. backrounds
3. margin and padding
4. table
4. form
5. float
### ### ### ### ### ### ### ### ### LARAVEL
1. basic
routing -middleware-controller
request-response
2. database
pegination-migration

**Comment by sabbir25112** [comment]
What is it?

**Comment by MouadZIANI** [comment]
wa saat wach hreb lik wla malek ?
