### ISSUE TITLE
[Pagination] SEO Friendly First Page

### ISSUE THREAD

**Issue by andrewnclark** [laravel/ideas#1999]
I'd like to propose the follow addition to Laravel:

```php
Paginator::seoFriendly(true):
```

It prevents `example.com/list?page=1` from working in favor of `example.com/list` whilst all other pages and functionality would remain as is.

This behavior is something that I have added to multiple projects in the past and would be happy to write a PR for. Happy to change the method name to something more explicit if preferred.

**Comment by andrewnclark** [comment]
### Alternative Approach

Additional method that could be chained on each paginator instance, so as not to force every one to behave the same:

```php
$model->paginate()->seoFriendly();
```

Internally, either method would simply set a flag which is referenced during the URL generation and prevent adding the `page=1` parameter whenever the page is the first one.

I'd be lieing if I said I was happy with the method name though.

**Comment by Sladewill** [comment]
This is usually why you use canonical meta tag in your HTML/layout.

**Comment by Nuranto** [comment]
I agree with @andrewnclark 
However, it should be default. 
It's cleaner, even if canonical tag may do the trick for most search engines.
Also, it should be simple (and usefull for seo) to add `rel="prev"` and `rel="next"`  attributes on prev/next buttons and on prev/next pages links.

**Comment by andrewnclark** [comment]
I'd like to reopen this issue for discussion - I closed it initially due to time constraints at the time.

Whilst using a canonical tag in your HTML is a valid option the rules are a bit different for `page=1` and `page=2` and by removing the page=1 parameter it would make it easier to manage out of the box.

Given `/collection?page=1` you would want to canonical `/collection` and add a `rel="next" src="/collection?page=2"`
Given `/collection?page=2` you would want to canonical `/collection?page=2` and add a `rel="next" src="/collection?page=3"` & `rel="prev" src="/collection"`

If you rel previous to a `/collection?page=1` that is going against the canonical provided in the first rule - thus causing the search engines confusion or you opt to use `?page=1` as your canonical and promote that over the plain `/collection` url.

Given the ability to force a first page without a parameter, the canonical can simply be the full URL of a given listing (minus any filter params but that's another topic).

There's a valid argument that these kind of details are not a frameworks concern and it may be better suited to a package but this option makes fundamental seo simpler.

I hope this helps to explain my point of view, if not I'll post some reference material that might better explain the pagination/canonical recommendations.

**Comment by Nuranto** [comment]
```
@Nuranto - the rel next/prev elements are already handled by the default pagination template I believe.
```

If I remember correctly, `rel` attributes are set on "prev" and "next" link 👍 

```
previous[rel=prev] 1 2 3[active] 3 4 5 next[rel=next]
```

but not on page link :

```
previous[rel=prev] 1 2[rel=prev]  3[active] 4[rel=next] 5 next[rel=next]
```

Honestly, I don't know if this change could have any impact on SEO or Accessibility. (Some SEO guy ask for it though)

**Comment by andrewnclark** [comment]
> 
> 
> > @Nuranto - the rel next/prev elements are already handled by the default pagination template I believe.
> 
> If I remember correctly, `rel` attributes are set on "prev" and "next" link :
> 
> ```
> previous[rel=prev] 1 2 3[active] 3 4 5 next[rel=next]
> ```
> 
> but not on page link :
> 
> ```
> previous[rel=prev] 1 2[rel=prev] 3[active] 4[rel=next] 5 next[rel=next]
> ```
> 
> Honestly, I don't know if this change could have any impact on SEO or Accessibility. (Some SEO guy ask for it on my project though)

The way it is at the minute is correct, a page only has one next and previous,

**Comment by vahidalvandi** [comment]
do it can work ?
`$model->paginate()->seoFriendly();
`

**Comment by andrewnclark** [comment]
> do it can work ?
> `$model->paginate()->seoFriendly(); `

No, the PR was never pursued I'm afraid. For the most part, Laravel's pagination is already extremely SEO friendly and will render the appropriate `rel="next"` and `rel="prev"` attributes in your markup.

This sort of canonical management, whilst nice is perhaps outside the scope of a PHP framework an maybe better suited to a package.
