### ISSUE TITLE
[cache] Cache::has($regex)

### ISSUE THREAD

**Issue by erlangp** [laravel/ideas#2008]
```php
if (Cache::has('my_data_2020_01_*')) {
    //
}
```

**Comment by voyula** [comment]
Laravel cache isn't a search engine.

**Comment by erlangp** [comment]
@voyula i see in validation something like this:

```php
$validator = Validator::make($request->all(), [
    'person.*.email' => 'email|unique:users',
    'person.*.first_name' => 'required_with:person.*.last_name',
]);
```

i think is possible to implement in `Cache::has`
just an idea XD

**Comment by voyula** [comment]
Think one million in-memory data and search a wildcard key in. 😺

**Comment by patrickclochesy** [comment]
Laravel's Cache is simply a wrapper for existing caching backends. Memcached for example does not support this. Redis supports KEYS but it is not intended for production - debugging only.
