### ISSUE TITLE
[Proposal] Share the Authenticated user into all views

### ISSUE THREAD

**Issue by DarkGhostHunter** [laravel/ideas#2009]
# Updated: Rewrote the whole logic.

It would be cool to **opt-in** to let the user to inject the authenticated user into all views, by adding a default `ShareAuthenticatedUser` middleware to the Kernel middleware.

```php
    /**
     * The application's route middleware groups.
     *
     * @var array
     */
    protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            // \Illuminate\Session\Middleware\AuthenticateSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
            // App\Http\Middleware\ShareAuthenticatedUser::class
        ],
        'api' => [
            'throttle:60,1',
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],
    ];
```

The middleware is pretty simple:

https://gist.github.com/DarkGhostHunter/8bd3be43129dcd1c517007e8c8710f76

But it could extend one on the framework and keep it much more simple, and allowing the user to use any custom logic to name the variable in their views. For example:

```php
<?php
namespace App\Http\Middleware;

use Illuminate\Contracts\Auth\Middleware\ShareAutheticatedUser as BaseMiddleware;

class ShareAuthenticatedUser extends BaseMiddleware
{
   /**
     * The variable to share as the authenticated user in all views
     *
     * @return string
     */
    protected function name()
    {
        // return 'authenticated';
        
        if ($this->user instanceof \App\Batman) {
            return 'batman';
        }

        return 'superman';
    }
}
```

**Comment by 36864** [comment]
This is easy enough to implement in your own project. You can use `View::share` to prevent multiple resolutions as in your example (`->composer('*', ...)` will be called once for each view layout, partial, component, etc). https://laravel.com/docs/6.x/views#sharing-data-with-all-views

**Comment by DarkGhostHunter** [comment]
> This is easy enough to implement in your own project. You can use `View::share` to prevent multiple resolutions as in your example (`->composer('*', ...)` will be called once for each view layout, partial, component, etc). https://laravel.com/docs/6.x/views#sharing-data-with-all-views

Thanks, totally forgot about that.

**Comment by DarkGhostHunter** [comment]
Now that I think about sharing it, a middleware would be needed since when the app boots no authenticated user will be present. Much alike ShareErrorsFromSession:

```
public function handle($request, Closure $next)
{
    View::share('authenticated', $request->user());
    
    return $next($request);
}
```

something like that.
