### ISSUE TITLE
[queue] run create & run a pending task using ignore_user_abort(true);

### ISSUE THREAD

**Issue by erlangp** [laravel/ideas#2010]
an alternative to queue
(without using: proc_open, exec, shell_exec, etc.)

my experiment is something like https://github.com/erlangp/sample-slim-run-background-task/blob/bdd6aba9ac50605bea67e1b326dd7425cdade0d8/index.php#L43

**Comment by erlangp** [comment]
my experiment is something like https://github.com/erlangp/sample-slim-run-background-task

**Comment by themsaid** [comment]
Can you please share more details?

**Comment by erlangp** [comment]
i want to run pending task / job / queue with `proc_open` **disabled**, sir

**Comment by erlangp** [comment]
thanks @themsaid (for your update https://github.com/laravel/framework/pull/31300)
