### ISSUE TITLE
[Proposal] Consumable Signed Routes (one time use)

### ISSUE THREAD

**Issue by DarkGhostHunter** [laravel/ideas#2015]
Currently, signed routes are verified by only the signature. No further verification is done, so a logic may run multiple times while the signed route is valid.

To tackle this, a `signed.consumable` middleware would extend on the `signed` middleware, but also use the app Cache to mark the signature as _consumed_ once the Request has been handled to the Controller.

The way this works is simple:

1. Check if the signature exists in the Cache. If it does, return an `InvalidSignatureException`.
2. After the response is handled by the controller, save the signature in the Cache. Use the same expiration date of the signature for the Cache key.

(Based on my article about [Consumable Signed Routes](https://medium.com/@DarkGhostHunter/laravel-combining-signed-routes-with-temporal-tokens-c5177769b432))

**Comment by MuluhGodson** [comment]
This is interesting.
