### ISSUE TITLE
[Proposal] Laravel 7.0 should focus on the server side

### ISSUE THREAD

**Issue by mbougarne** [laravel/ideas#2016]
With the rise of SPAs and use of JavaScript frameworks at the Front-End, I suggest that Laravel should get minimized in new version to focus just about the Back-End. As in V6 and the separation of UI, Helpers to standalone packages. I suggest to make the Blade a standalone packages with all the parts of Front-End and if there's a need of them we can require'em through Composer: 

``` composer require laravel/blade ```

**Comment by tomschlick** [comment]
The alternative is that you can just ignore blade if that's what you want. You can even unload the view service provider. But removing it from the default is a bad move IMO. The majority of apps are not SPAs.

**Comment by mattstauffer** [comment]
Ew

**Comment by mbougarne** [comment]
It won't be removed just in separate package. As in **Symfony** if you want to use **Template** you can require **twig-bundle** with ``` composer require symfony/twig-bundle ```. 

If you take a look at **Laravel** installation ```Vendor Folder``` There's a lot of package which you won't use them. if will be good **IMHO** to make the base app as minimized as possible.

**Comment by mattstauffer** [comment]
Why? What purpose would this serve?

**Comment by mbougarne** [comment]
My experience, lately I start to use Laravel as a **REST-API** provider and the Front-End handled by **Vue** using **Nuxt**, why blade or any Front-End feature/functionality/package there on my Laravel app since I don't use/need them? The purpose is to make the base installation has what you need to start with Laravel. 

If you want **Blade** or other parts of **Front-End**  I suggest to add type of installation like this:
```bash
laravel new restapi --api #  Installation for API projects
laravel new cms --full # Full installation 
```

**Comment by mattstauffer** [comment]
Sure.. but just because you're using Laravel for REST APIs doesn't mean others aren't. So you're proposing introducing a cost to folks who use Blade, but haven't suggested any benefit that would actually provide.

**Comment by mattstauffer** [comment]
And I'm not just saying this to be pedantic. I literally have the same question still:

What benefit will this provide? In what way will your apps be better as result of this change that makes the development experience worse for some other folks?

**Comment by mbougarne** [comment]
I didn't say that! Although the vast majority of Laravel projects that I see use it as an all-in-one solution! Anyway, about your question: ```What benefit will this provide?``` Before that, I'm not talking just about Blade! No, but about all the unused services that get loads with the app. In ```config/app.php```  There're 22 services loaded, some of them don't uses in some applications but they get loaded with the app which means a bad performance.  So, the answer to your question is:

- A better performance.
- Uses for SOA or MSA.
- Make some services of Laravel available for uses outside it.
- Use what/when you want.

I believe that not all apps need these:
```php
        Illuminate\Broadcasting\BroadcastServiceProvider::class,
        Illuminate\Notifications\NotificationServiceProvider::class,
        Illuminate\Pagination\PaginationServiceProvider::class,
        Illuminate\Queue\QueueServiceProvider::class,
        Illuminate\Redis\RedisServiceProvider::class,
        Illuminate\Translation\TranslationServiceProvider::class,
```
I hope that I answered your question and thanks for this chit-chat.

**Comment by TheNewSound** [comment]
If you run Laravel strictly as back-end only, why not just use a completely different (+faster) framework?

**Comment by mattstauffer** [comment]
Have you ever tried Lumen? And are you actually running into speed issues or just imagining these things might be speed issues?

**Comment by rs-sliske** [comment]
which part of laravel isnt back end focused :p

you are free to make changes to the config files if there are services in there you dont want. 

i would be very surprised if they are many applications not using any of the 6 service providers you listed. pretty much any app should paginating queries imo, a decent % will have notifications and /or queuing jobs (queuing notifications even) and more people should probably be using translations. i certainly dont feel like any of these should be disabled by default

redis and broadcasting could maybe make argument to comment out but i would be surprised if that made a noticeable (or even measurable) difference to performance

**Comment by villeneuve-michael** [comment]
I see lot's of pushback, let me jump in just to give a different perspective, I understand the point that @mbougarne is trying to make. Moving in the direction of stateless app is a good move as it will become in my humble opinion more and more common. It just happens that during the past year almost every major app I develop is using laravel stictly as an API (but of course I use queue's, notifications, etc.) and build my UI using Nuxt (so freak'in good!). 

Now the best point I read so far is from @mattstauffer as Lumen should be the way to go for us. Maybe the way the proposal is framed isn't ideal, but I like the suggestion to have the following option: 

```
laravel new restapi --api
```
It would simply omit installing the resources folder, package.json and blade dependency. It's not really about performance, but about having a clean project ready to go for stateless app. It's annoying to have a bunch of file folders to cleanup every time I start a project!

**Comment by crynobone** [comment]
I believe the best move forward is to build your own standard skeleton, there nothing wrong since you said that you done it multiple times for your project. There nothing wrong with that and @mattstauffer and his team did build [tightenco/jigsaw](https://github.com/tightenco/jigsaw).

To say Laravel should just focus on backend is not the correct approach, since I and many others still use the default most of the time.

**Comment by mbougarne** [comment]
Lumen, I know it and I worked with it. I like the idea of micro-framework in Laravel ecosystem, but to be honest with you, It didn't bring anything new. I want to ask you @mattstauffer  did you use Lumen before? I think you didn't.

I know that I can use other frameworks or even Language which is I already do, the vast majority of my REST projects are done with NodeJS, but giving an idea or share a method of work with the **Laravel** people it won't hurt! :) 

Anyway, I didn't mean at all that we must take Blade or the parts that I mentioned off from Laravel, what I suggest is make the start of Laravel project light and take a lot of services as standalone packages, when we need any of them, we add it to the project, or we can create full project from start with all the services:

```bash
# Full installation
laravel new app 
# Just for API
laravel new app --rest

# If we want to add other services
laravel add SERVICE_NAME {blade}
# OR
composer require laravel/blade
# Like this
composer require laravel/helpers
```
There's a lot of Laravel services that will be great if they're available to work with outside Laravel world, as reusable components.

**Comment by simphiwehlabisa** [comment]
@mbougarne Your argument is sound.

**Comment by 36864** [comment]
>There's a lot of Laravel services that will be great if they're available to work with outside Laravel world, as reusable components.

Most laravel components can be used as standalone components already. What are you referring to exactly?

**Comment by MarcinDyszkiewicz** [comment]
As @mbougarne mentioned `laravel new app --rest` would be great.
Lumen is cool as micoservice, but what if you need rather bigger api service, laravel is much better in my opinion. 
In the end it's just all about speed up development process

**Comment by ollieread** [comment]
@36864 That's not strictly true anymore. A lot of the packages rely on so many of the other packages that they are never truly used as standalone.

I like the idea of a separate first-party blade package, but not so that it's stripped from the default framework implementation, but so that it could be used elsewhere. The problem is again, that it's going to pull in enough stuff that it's going to be somewhat redundant.
