### ISSUE TITLE
URL::defaults for named routes (not using prefixes)

### ISSUE THREAD

**Issue by TheNewSound** [laravel/ideas#2018]
Picture the following situation: 

- A single laravel application is deployed on a server.
- 2 domains point to this laravel application: `example.com` and `example.nl`
- I'm using **named** routes because that is the cleanest ofcourse.
- I **do not** want to use prefixed url's based on the users language, so the following url's exist:
```PHP
Route::get('/', 'HomeController@index')->name('home');
Route::get('about', 'AboutController@index')->name('about');
Route::get('register', 'AuthController@register')->name('register');
Route::get('/', 'HomeController@index')->name('home');
Route::get('over', 'AboutController@index')->name('about');
Route::get('registreren', 'AuthController@register')->name('register');
```
- I **do** want to use the route cache

You see the problem? 
If I were to use prefixed url's, I could use `URL::defaults()` in the middleware to set the prefix, so `url('register')` can use the correct url, but when using named url's without prefixes in a multi-language environment, this is impossible?

If we check for a request's language in the router, the route cache mechanism will not cache all of our urls.

Am I something missing here or is this a feature to be added?

Route should have a `->locale('')` method. 

**EDIT:**
Better yet, I see Laravel 5.5+ supports prefixed names in routes.
```PHP
Route::name('admin.')->group(function () {
    Route::get('users', function () {
        // Route assigned name "admin.users"...
    })->name('users');
});
```

Then I would define the following routes:
```PHP
Route::name('en.')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('about', 'AboutController@index')->name('about');
    Route::get('register', 'AuthController@register')->name('register');
});
Route::name('nl.')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('over', 'AboutController@index')->name('about');
    Route::get('registreren', 'AuthController@register')->name('register');
});
```
... and use the correct **name** prefix when calling `url()`, example: `url('en.home')`. If only there is a way to set the **name** prefix in a middleware, so I can just call `url('home')` ...

**Comment by driesvints** [comment]
Since Taylor rejected the PR we're probably not going to implement this anytime soon, sorry.
