### ISSUE TITLE
eager loading with different name

### ISSUE THREAD

**Issue by khanzadimahdi** [laravel/ideas#2032]
add ability in loading methods **with** and **load** to load relations with given name.

for example imagine i have a relations named **houses** and i want to load it as **departments** and another time i want to load it as **assets**

i need to rename relationships.

**Comment by bert-w** [comment]
Whats the actual use case of this? Why not simply use the solution below if its absolutely necessary to have a different relation name:

```php
public function houses()
{
    return $this->hasMany(House::class, ...);
}
public function departments()
{
    return $this->houses();
}
````

**Comment by mfn** [comment]
I second the suggestion from @bert-w , "renaming" isn't a common cause and I don't think it makes sense to permanently add complexity (=code) to the project for this, when there are workarounds possible.

**Comment by khanzadimahdi** [comment]
in restful API i want to use relation with brief name to save band width. for example the relation's name is **cars** and i want to use it as **c**

or in many cases i want to load a relation with given name.

**Comment by 36864** [comment]
Can't you do that with api resources?

**Comment by khanzadimahdi** [comment]
@36864 it cant be done with resources.

**Comment by 36864** [comment]
Changing the name of any field of a model for api calls can very much be done with api resources, and it works with relationships just the same.

For example, this returns a json representation of the model where the user's company is in the field named "foo", where `company` is a relationship on the User model:
```
<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class User extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'id' => $this->id,
            'foo' => $this->company,
        ];
    }
}
```

With this route definition:
```
Route::get('/user/{user}', function($user) {
  return new User(App\User::with('company')->find($user));
});
```

I get this result:
```
{"data":{"id":1448,"foo":[{"id":10267,"name":"Test Company"}]}}
```
