### ISSUE TITLE
[Proposal] Cache::getOrSet($key, $callback, $ttl = 60)

### ISSUE THREAD

**Issue by villeneuve-michael** [laravel/ideas#2033]
As my title state, it is pretty self explanatory. I often find myself using this helper that I created, I thought maybe it could be interesting for the whole community. 

I have the following method in my BaseController, which I use pretty often.

```php
    protected function getOrSetCache($key, $callback, $ttl = 60) {
        if (Cache::has($key)) {
            $data = Cache::get($key);
        } else {
            $data = $callback();
            Cache::put($key, $data, $ttl);
        }

        return $data;
    }
```

Usage: 

```php
    public function sport(string $sport)
    {
        $key = 'lines_' . $sport;
        $data = $this->getOrSetCache($key, function() use ($sport) {
            return $this->repository->getForSport($sport);
        });
        return response()->json($data);
    }
```
The idea would be to migrate my helper function to the Cache facade.

I was thinking that it would  be neat to do a pull request, but since I have never contributed to the framework before, I thought that I'd post it here first to get your thought. If it's something that is aligned with the vision I can take care of the test / implementation / PR.

**Comment by michaeldyrynda** [comment]
Is there some reason you can’t use `Cache::remember()` for this?

As far as I can tell, this behaves the same way as your proposal.

**Comment by villeneuve-michael** [comment]
@michaeldyrynda  urghh I can't beleive I didn't see this before. I kept looking for something like this but the keywords that I used were instinctively to play around what eloquent offers (ie: firstOrCreate).

I'll close this proposal and start using this! Thanks for pointing it out!
