### ISSUE TITLE
RefreshDatabase performace optimization

### ISSUE THREAD

**Issue by danilopinotti** [laravel/ideas#2034]
Hi,

In a project that I work, we have hundreds of migrations and, currently, when we run tests using RefreshDatabase, the test suite take about 7 seconds to begin to execute.

My suggestion is make a command like `php artisan db:cache-migrations` that executes all migrations and create a final .sql with all executed SQLs on migrations.

That way, the trait RefreshDatabase looks first to cached migrations file. If doesn't exists, execute fresh command as currently, else, executes the final SQL only.

What do you think?

**Comment by mfn** [comment]
IMHO `RefreshDatabase` is somewhat flawed. And what if the SQL statements itself are the culprit?

In general, it's more efficient to:
- run the migrations _upfront_ once before any test starts
- use `DatabaseTransactions` instead of refreshing

**Comment by danilopinotti** [comment]
@mfn Thanks for share your opinion!

I do simple benchmarks applying my idea and I saved 3~4 seconds on the process, but, IMO, 4 seconds its still slow to begin the tests.

I think we need to use the way that you suggest.

**Comment by mfn** [comment]
In general, there are two things I do with Laravel projects:

1. use a dedicated test database
  I newer liked the tests meddling with the local dev database
2. throw away the whole test databse and migrate **once**, then run all (database related) tests in said transaction trait

For 2. I'm using this trait at the moment:
```php
<?php declare(strict_types = 1);

use Illuminate\Database\DatabaseManager;
use Illuminate\Foundation\Application;
use Illuminate\Foundation\Console\Kernel;

trait DatabaseSetupTrait
{
    private static $databaseSetupDone = false;

    private function setupDatabaseOnce(): void
    {
        if (self::$databaseSetupDone) {
            return;
        }

        /** @var Application $app */
        $app = $this->createApplication();
        $this->setupDatabases($app->make('db'), $app->make(Kernel::class));

        self::$databaseSetupDone = true;
    }

    private function setupDatabases(DatabaseManager $db, Kernel $console): void
    {
        // Delete all tables on all connections
        foreach (array_keys(config('database.connections')) as $connectionName) {
            $db
                ->connection($connectionName)
                ->getSchemaBuilder()
                ->dropAllTables();
        }

        // Run migrations on clean database
        $console->call('migrate');
    }
}
```
and in the apps `TestCase::setUp` I call the `setupDatabaseOnce` method.

This only works if you're _not_ using parallel execution or process isolated tests AFAIK.

**Comment by danilopinotti** [comment]
I'm checking the RefreshDatabase trait and it already migrate once.
It is on this initial migration that I suggest to optimize. The database cache file may be re-builded according migration folder's hash.

**Comment by mfn** [comment]
> I'm checking the RefreshDatabase trait and it already migrate once (L6.x).

O_O

Thanks. I had this trait in place since the beginning (L 5.1) and that trait was introduced with 5.5 .. need to check that. Glad I mentioned it 😄 

As to your initialization problem: I've a similar issue but I don't think I have it due to the actual migration, in my case I've special "fixtures" I pre-seed the database _once before all tests, too_. But I didn't benchmark it lately…

**Comment by danilopinotti** [comment]
@mfn Well, I made a workaround for this problem.

I create a hash of migrations folder and fresh database once according this hash. This solution is faster than original idea, because now, the migrations executes once according migrations instead of before each test.

Follow my implementation (suggestions are welcome :D)
https://gist.github.com/danilopinotti/785851fbc284e4ae36e7cc5b6effe588

Thanks!
