### ISSUE TITLE
[Proposal] Query builder 'reorder' method

### ISSUE THREAD

**Issue by derekmd** [laravel/ideas#204]
For growing Laravel projects, there is a need to re-use model relationships and scopes. For query builders, two common problems I've come across are:
1. Inability to use query builder `count()` on a relationship that orders the results when eager-loaded.
   
   ``` php
   class Gallery extends Model
   {
      public function photos()
      {
          return $this->morphMany(Photo::class, 'parentable')->orderBy('photo_order');
      }
   }
   ```
   
   For `$gallery->photos()->count()`, this statement will generate Postgresql error:
   
   ```
   column "photos.photo_order" must appear in the GROUP BY clause or be used in an aggregate function
   ```
   
   This use case isn't a show-stopper since you can use the eager-loaded `photos` property's Collection `count()` method when the operation's memory footprint isn't too expensive. However:
2. Scopes and relationships are unable to remove an existing order (added by a preceding scope) or re-sort the relationship it re-uses.
   
   ``` php
   class Album extends Model
   {
      public function reviews()
      {
          return $this->hasMany(Review::class)
              ->with('reviewer')
              ->orderBy('created_at', 'desc');
      }
   
      public function rankedReviews()
      {
          return $this->reviews()
              // Becomes secondary sort column but we want it as primary
              ->orderBy('rating', 'desc');
      }
   }
   ```
### Introducing `reorder()` to class `Illuminate\Database\Query\Builder`

Below is an example implementation macro:

``` php
<?php

namespace App\Providers;

use Illuminate\Database\Query\Builder;
use Illuminate\Support\ServiceProvider;

class QueryBuilderMacros extends ServiceProvider
{
    public function boot()
    {
        Builder::macro('reorder', function() {
            $property = $this->unions ? 'unionOrders' : 'orders';

            $this->{$property} = null;

            if (func_num_args() > 0) {
                return $this->orderBy(...func_get_args());
            }

            return $this;
        });
    }

    public function register()
    {
    }
}
```

> This `reorder()` implementation does not affect global scopes applied on the Eloquent model so the
> `withoutGlobalScopes()` method must be called to exclude orderBy() added in such a scope.

With the above examples, you can call `$gallery->photos()->reorder()->count()` to avoid an SQL aggregation function error and change the secondary `Album@rankedReviews()` model relationship to:

``` php
public function rankedReviews()
{
    return $this->reviews()
        ->reorder('rating', 'desc');
}
```

These are simple examples that will illicit the response, "uh, just copy and paste a few extra lines, then?" But when projects reach into majestic monolith proportions, report queries containing 5+ scopes scream for the ability to re-start the query's ordering at any time.

I originally added this `reorder()` ability in Laravel 5.1 but have since learned Ruby on Rails has its own [Active Record reorder](http://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-reorder) that exists to work around the same problems.

**Comment by shirshak55** [comment]
Is there any news regarding it?

**Comment by derekmd** [comment]
Any codebase can macro it into the `Illuminate\Database\Query\Builder` class using the above code sample.

Problem #1 hasn't been an issue since Laravel 5.5 removed `ORDER BY` when running aggregate queries: https://github.com/laravel/framework/pull/19022

Problem #2 feels more like an edge case since only 13 people have ticks that like button since Sept 2016 and at least two of them are coworkers of mine.

**Comment by derekmd** [comment]
You can still use `reorder()` by registering the macro in `AppServiceProvider`:

https://github.com/laravel/laravel/blob/master/app/Providers/AppServiceProvider.php

Edit app/Providers/AppServiceProvider.php in your project:

```php
namespace App\Providers;

use Illuminate\Database\Query\Builder;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        Builder::macro('reorder', function() {
            $property = $this->unions ? 'unionOrders' : 'orders';

            $this->{$property} = null;

            if (func_num_args() > 0) {
                return $this->orderBy(...func_get_args());
            }

            return $this;
        });
    }

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }
}
```

**Comment by shirshak55** [comment]
thanks, it is working good.

**Comment by jacobsmith** [comment]
For future reference, I had to update this to:

```
        Builder::macro('reorder', function () {
            $property = $this->query->unions ? 'unionOrders' : 'orders';

            $this->query->{$property} = null;

            if (func_num_args() > 0) {
                return $this->orderBy(...func_get_args());
            }

            return $this;
        });
```

presumably from a version change

**Comment by derekmd** [comment]
The code snippet I posted registers the macro on Laravel's `Illuminate\Database\Query\Builder` class. If your sample works, I assume that means you registered it on `Illuminate\Database\Eloquent\Builder` since property `Illuminate\Database\Query\Builder@query` doesn't exist in Laravel 5.8.* or 6.0.4.

Putting it on the base query class also allows the method to work on `DB::table()` queries outside of Eloquent models.

At least for the Postgres grammar, these below tests ensure the app code continues working with each Laravel upgrade.

```php
namespace Tests\Unit\Macros;

use App\User;
use Illuminate\Database\Query\Builder;

class BuilderMacrosTest extends \TestCase
{
    public function testReorderWhenRemovingSort()
    {
        $query = (new User)
            ->orderBy('created_at')
            ->reorder();

        $this->assertStringNotContainsString('order by "created_at" asc', $query->toSql());
    }

    public function testReorderWhenAddingAnotherSort()
    {
        $query = (new User)
            ->orderBy('created_at')
            ->reorder('id', 'desc');

        $this->assertStringNotContainsString('order by "created_at" asc', $query->toSql());
        $this->assertStringContainsString('order by "id" desc', $query->toSql());
    }
}
```

**Comment by jacobsmith** [comment]
Ah, thank you @derekmd ! My IDE auto-imported the Builder and clearly imported the wrong one. Appreciate your response!
