### ISSUE TITLE
Deprecate $factory variable when defining Eloquent Model factories

### ISSUE THREAD

**Issue by SonOfHarris** [laravel/ideas#2054]
**Edit: `factories()` function approach no longer the suggested solution. See the comment regarding using a Facade instead https://github.com/laravel/ideas/issues/2054#issuecomment-583923046.**

---------------

I've noticed previous discussions regarding adding type hinting for IDEs when defining Eloquent Model factories (see https://github.com/laravel/framework/pull/24647 and sorry if it brings back bad memories).
An outcome of this was adding a doc comment that was type-hinting the `$factory` variable.
Whilst this solves the problem, this causes issues in case there is a refactor or change in how factories are defined in the future not to mention the potential debt in existing factory definition files.

Recommend the following changes to allow the best of both worlds:

https://github.com/laravel/framework/compare/6.x...SonOfHarris:6.x-factories

## Pros of approach:

* `factories()` helper function is controlled via framework so can deal with any future refactoring
* `$factory->` can be easily replaced with `factories()->` via text substitution in existing files
* Removes the need for the doc type hint
* Fully backwards compatible

## Cons of approach:

* Requires creating a new helper `factories` function thus potentially causing naming conflicts
* Internally requires setting a static instance (`Factory::$loaderInstance`) to ensure the factory instance is correct at the time the files are being loaded (other suggestions more than welcome)

**Comment by SonOfHarris** [comment]
P.S. Changes quick link: https://github.com/laravel/framework/compare/6.x...SonOfHarris:6.x-factories

**Comment by ollieread** [comment]
@SonOfHarris What you're proposing will also be an issue in the future if factories are changed. Adding the docblock is the simplest solution right now. You can't avoid something like that on the off chance that there's a fundamental change in the future. If there's a fundamental change, no solution will be viable.

**Comment by SonOfHarris** [comment]
@ollieread Thanks for your response as you made a very valid point and it made me question the deeper motivations of this request.

When you look at a fresh install of a Laravel app, there are generally the following patterns:

- Files that define classes (e.g. service providers, migrations)
- Files that return arrays (e.g. configuration)
- Files that run procedural code (e.g. routes, bootstrap, factories)

When you break down the procedural files they either:

- Return an instance (e.g. bootstrap/app.php)
- Interact with the application via Facades (e.g. routes)

These files are written in a way that does require them to be loaded from a specific point.
Model factories appear to be an exception as they are dependent upon the `$factory` variable being defined before loading the file.
What I'm hoping to achieve is deprecating this dependency and asking that factories be written in a manner consistent with the rest of the framework.
But there are some issues with this of which feedback is greatly appreciated.

Digging deeper into the factory chain:

- The `factory()` function relies upon the `Illuminate\Database\Eloquent\Factory` service
- The `Illuminate\Database\Eloquent\Factory` service is registered via the `Illuminate\Support\ServiceProvider::loadFactoriesFrom()` method
- The service provider relies upon the `Illuminate\Database\Eloquent\Factory::construct()` method that in turn loads the factory files after instantiating the factory
- Factory files are loaded within the factory instance so technically factories can be registered using `$this` or `$factory`

So from this there is an assumption within the framework, enforced via the `factory()` function, that there is only one factory instance.
Based on this it seems more sensible to use a Facade to define factories.

The roadblock here has to do with how the factory is being resolved.
Currently the factory files are loaded before the factory service is within the service container (see `Illuminate\Database\Eloquent\Factory::construct()`).
The following changeset attempts to solve this issue by loading the files after the service has been resolved.

https://github.com/laravel/framework/compare/6.x...SonOfHarris:6.x-factory-facade

# Pros of approach

- `$factory->` can be easily replaced with `Factory::` via text substitution in existing files
- `use` statement importing the facade can be easily added to existing files
- Removes the need for the docblock hint
- Brings factories inline with other procedural files
- Backwards compatible with existing factories as `$factory` variable is still passed through
- Documentation can be updated to recommend using facade approach
- Breaking change can be introduced in next major version by removing `$factory` variable 
- Eventually allows files to be safely loaded outside of the factory instance (e.g. via function rather than method)

# Cons of approach

- Requires creation of a new Facade
- Depends upon the assumption there is only one factory instance to load factories in to, so there any be unforseen breakages
- Deprecated `Factory::construct()` as files would be unable to use the `Factory` facade, but this method is only used within the `DatabaseServiceProvider` so impact within user space is unknown

If the need arises to have access to the `$factory` variable there are solutions such as the factory files returning a closure or array of closures
When the factory file returns a closure, the factory can then pass itself as the first argument of the closure.

Is this facade approach more viable?

**Comment by SonOfHarris** [comment]
Pull request contains a more concise description of the requested change.
