### ISSUE TITLE
Better DatabaseMigrations to increase the tests performance

### ISSUE THREAD

**Issue by devmsh** [laravel/ideas#2062]
While Laravel defaulted the testing database to the in-memory SQLite database, I think the framework must provide enhanced `DatabaseMigrations` version that didn't perform the migration rollback.

I decreased the test time by 50 ms/test just by removing the line 

```php
$this->artisan('migrate:rollback');
```

from the current `DatabaseMigrations` trait. for a simple test suite, it goes down from 4.6 to 3.8 sec, it will definitely be better for bigger suites without any code change 😉

If you need to use the trick right now, you can copy the trait into your `Tests` namespace beside the `TestCase` class, and add the following `setup` function to the `TestCase` itself.

```php
    protected function setUp(): void
    {
        parent::setUp();

        $uses = array_flip(class_uses_recursive(static::class));

        if (isset($uses[DatabaseMigrations::class])) {
            $this->runDatabaseMigrations();
        }
    }
```

Happy testing!

**Comment by michaeldyrynda** [comment]
Laravel already provides enhanced migration functionality in tests via either the DatabaseTransactions or RefreshDatabase traits.
