### ISSUE TITLE
implement a circuit breaker pattern for api 

### ISSUE THREAD

**Issue by ujwaldhakal** [laravel/ideas#2068]
Currently there is no way to laravel support auto retries, auto retries on queue etc so it would be better for robust stateless apps

**Comment by LIQRGV** [comment]
Does time limit auto retries good enough for you?
https://github.com/illuminate/queue/blob/master/Queue.php#L182
https://laravel.com/docs/5.5/queues#max-job-attempts-and-timeout

**Comment by ujwaldhakal** [comment]
What if I wanted to handle synchronously?

**Comment by LIQRGV** [comment]
Well...
I think that would costly for a webserver.
I don't know your use case, so I don't know the solution atm.
