### ISSUE TITLE
Separate framework version from application version

### ISSUE THREAD

**Issue by brantmessenger** [laravel/ideas#2077]
I appreciate all the laravel provides but a framework is supposed to play a supporting role to the application not vise versa.

`App::version()` looks like it is referencing the application but it really is the framework's version. Maybe change to `App::laravelVersion()` or `App::frameworkVersion()` and allow `version` method to consume (`config('app.version')`) the application's version instead of the framework's version. 

src/Illuminate/Foundation/Application.php

`    /**
     * The Laravel framework version.
     *
     * @var string
     */
    const VERSION = '6.15.0';
`

`
    /**
     * Get the version number of the application.
     *
     * @return string
     */
    public function version()
    {
        return static::VERSION;
    }
`

**Comment by martinbean** [comment]
@brantmessenger What will this achieve? The application skeleton _should_ be tied to the framework version. You wouldn’t use say, version 6 of the application skeleton with version 7 of the framework as the skeleton may reference old classes, methods, etc.

This is why the Laravel documentation has an upgrade guide. You wouldn’t update the framework version without updating your application to reflect changes.

**Comment by brantmessenger** [comment]
@martinbean thanks for your response. Did not realize that the version in discussion was the skeleton's version. I thought I read through the documentation but I guess I missed this.
