### ISSUE TITLE
Add pick method to collection

### ISSUE THREAD

**Issue by half2me** [laravel/ideas#2081]
Would it be useful to have a `pick()` method on collections? Basically what lodash has:
https://lodash.com/docs/4.17.15#pick

Example:
```php
collect([
  'a' => 'foo',
  'b' => 'bar',
  'c' => 'baz',
])->pick(['a', 'c'])->toArray();
```
would output:
```php
[
  'a' => 'foo',
  'c' => 'baz',
]
```

I currently have it implemented as a macro in one of my projects:
```php
Collection::macro('pick', fn(array $items) => $this->filter(fn($val, $key) => in_array($key, $items)));
```

Its really simple, but I thought it could be quite useful. I could create a PR if needed.

**Comment by 36864** [comment]
Sounds like you're looking for the `only` method: https://laravel.com/docs/6.x/collections#method-only

**Comment by half2me** [comment]
> Sounds like you're looking for the `only` method: https://laravel.com/docs/6.x/collections#method-only

Yep, thats the one. Thanks for the heads-up!
