### ISSUE TITLE
Shorter version to get authenticated user

### ISSUE THREAD

**Issue by zsoro2** [laravel/ideas#2090]
Current options:
`auth()->user()`
`Auth::user()`

Idea:
`uauth()`

**Comment by ryangjchandler** [comment]
This function should really live in user land. Most people are happy using the facade or auth() helper to get the current user.

**Comment by mantas-done** [comment]
I have a function in my projects:

`user()`

Probably one of the best shortcuts. 

Remember when we neede to type Carbon::now()?
Had now() before Laravel implemented it :)
