### ISSUE TITLE
[Proposal] Str::format

### ISSUE THREAD

**Issue by stevelacey** [laravel/ideas#2124]
This is mostly a copy of [Python's String.format](https://docs.python.org/3.4/library/string.html#string-formatting), a more intuitive `sprintf`.

The macro works as shown, it allows for the formatting of predefined template strings using automatic, positional and key placeholders: `{}`, `{1}`, `{key}`.

```php
Str::format('acme.{network}.app.{id}', ['id' => 123, 'network' => 'testserver'])
=> "acme.testserver.app.123"

Str::format('acme.{}.app.{}', ['testserver', 123])
=> "acme.testserver.app.123"

Str::format('acme.{0}.app.{1}', ['testserver', 123])
=> "acme.testserver.app.123"

Str::format('acme.{1}.app.{0}', [123, 'testserver'])
=> "acme.testserver.app.123"
```

The idea is that you'd use this in places where you don't want to use interpolation, or want to supply a standard template for something else to customize.

The macro looks like this, there's some obscure loose ends under edge cases that could be handled better but largely it works, supports escaping, and yields sensible errors:

```php
Str::macro('format', function (string $string, array $vars) : string {
    preg_match_all('/(?<!{){(\w*)}(?!})/', $string, $matches);

    $i = 0;

    foreach ($matches[1] as $ref) {
        $key = $ref === '' ? $i++ : $ref;
        $limit = $ref === '' ? 1 : -1;
        $string = preg_replace('/(?<!{)\{' . preg_quote($ref) . '\}(?!})/', $vars[$key], $string, $limit);
    }

    $string = preg_replace('/{{(\w*)}}/', '{\1}', $string);

    return $string;
});
```

I use it on occasion to do things like format a class constant, which allows for fixed templates that can be shared, reused, pulled from config:

```php
class UserChannel extends Channel
{
    const FORMAT = 'acme.{network}.user.{id}';

    public function __construct(User $user)
    {
        $this->name = Str::format(self::FORMAT, [
            'id' => $user->id,
            'network' => config('app.network.name'),
        ]);
    }
}
```

The macro raises `E_NOTICE` if an offset is requested that is not provided, e.g. too many `{}` or `{missing_key}`, whilst this is different to Python which fails hard if you do that, this is more consistent with the rest of PHP:

```php
>>> @Str::format('acme.{network}.app.{id}', ['id' => 123])
PHP Notice:  Undefined index: network
=> "acme..app.123"
```

```php
>>> @Str::format('acme.{}.app.{}', ['testserver'])
PHP Notice:  Undefined offset: 1
=> "acme.testserver.app."
```

Alternatively, missing keys could leave the placeholder and/or not yield an `E_NOTICE`, and this could use `Arr::get` to support references to nested values in dot syntax.

Multiple errors result in multiple notices in the expected order:

```php
>>> @Str::format('acme.{1}.app.{0}', [])
PHP Notice:  Undefined offset: 1
PHP Notice:  Undefined offset: 0
=> "acme..app."
>>> @Str::format('acme.{}.app.{}', [])
PHP Notice:  Undefined offset: 0
PHP Notice:  Undefined offset: 1
=> "acme..app."
```

Nulls result in an empty string with no error, same as echos, blade:

```php
>>> Str::format('acme.{network}.app.{id}', ['id' => 123, 'network' => null])
=> "acme..app.123"
```

Escaping is supported the same way as Python `{{}}` > `{}`:

```php
>>> Str::format('acme.{{network}}.app.{id}', ['id' => 123])
=> "acme.{network}.app.123"
```

**Comment by patrickclochesy** [comment]
I think this makes a lot of sense to add to Str::, as this type of string formatting is becoming very popular. C# uses a similar format allowing formatting.

I would almost think that silently removing replacement keys without a provided replacement would be the way to go.

Is simple replacement sufficient, or is formatting/etc. a la C#'s String.format and stdlib/PHP/etc's *printf necessary?

**Comment by stevelacey** [comment]
I don't know that silence is the way to go if a key that doesn't exist is referenced, Python KeyError's, but it could do an empty string replace instead of a skip with `$replacement = $vars[$key]`

**Comment by driesvints** [comment]
Closing because the PR was rejected.

**Comment by ollieread** [comment]
Could you not achieve the same thing by hooking into the way Laravel handles translation strings?
