### ISSUE TITLE
[Proposal] Add dispatch_chain helper 

### ISSUE THREAD

**Issue by ajcastro** [laravel/ideas#2136]
I believe it is better if we can easily modify and control job chaining if we make all the jobs chain in the same array, so later we can easily change the calls for each jobs. For me this is also more verbose.
The current syntax is like this:
```php
ProcessPodcast::withChain([
    new OptimizePodcast,
    new ReleasePodcast
])->dispatch();
```
But if you need to edit this code later or re-arrange them it might be cumbersome especially if those jobs have constructor parameter.

So I suggest we can call them like this, where they can be easily rearrange later even with construct parameters.
```php
dispatch_chain([
  new ProcessPodcast,
  new OptimizePodcast,
  new ReleasePodcast,
]);
```

Maybe this is also doable by creating your own helper:
```php
function dispatch_chain($jobs) {
  $first = array_shift($jobs);
  return dispatch($first)->chain($jobs);
}
```

**Comment by driesvints** [comment]
We have no plans to add any more global helpers atm.
