### ISSUE TITLE
Add JSON serialization for cast attributes that implement Jsonable or JsonSerializable interface

### ISSUE THREAD

**Issue by andriichuk** [laravel/ideas#2152]
For example, I have Eloquent casts

```php
    protected $casts = [
        'price' => \Vendor\Library\PriceCast::class,
    ];
```

`PriceCast` is a vendor library class that is defined as `final` but implements the `JsonSerializable` interface.
I want to serialize Eloquent data using `toArray` method but I can't implement `Arrayable` interface because I cant extends vendor final class (and composition is not suitable for me). 
Proposal - call the JSON serialization method on cast attributes that implement Jsonable or JsonSerializable interfaces.

Here are the changes we need to make:

`src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php` class (method `addCastAttributesToArray`)

![image](https://user-images.githubusercontent.com/38154251/77591177-1b77c400-6ef8-11ea-80f0-39c2a40c5075.png)

**Comment by ragulka** [comment]
Another option would be if custom casts could provide a `serialize` method. It would be even more flexible, allowing to exactly control how data is serialized.
