### ISSUE TITLE
[Proposal] DB instance from Eloquent model

### ISSUE THREAD

**Issue by ahmeti** [laravel/ideas#2163]
Sometimes, we need to DB instance queries for more performance. (eg. more then 30K rows query)

But we can not access DB instance in Eloquent model.

Actual Status : 
```php
$tableName = (new InvoiceItem)->getTable();
DB::table($tableName)->select('...')->get();
```

Why can't we get a DB instance from the model?
```php
InvoiceItem::DB()->select('...')->get();
```

I use this feature a lot and I definden method on BASE MODEL.
I think this is a useful suggestion.
Thank you.

**Comment by staudenmeir** [comment]
You can get a query builder from a model:

```php
InvoiceItem::getQuery()->select('...')->get();
```

**Comment by ahmeti** [comment]
Thank you @staudenmeir 
I overlooked the getQuery method.
