### ISSUE TITLE
Having Laravel rewritten in TypeScript, for NodeJS

### ISSUE THREAD

**Issue by let-aurn** [laravel/ideas#2174]
#### Well, before you scream that "whaaaaat?!", let me explain 😁

# Introduction

The entire Laravel ecosystem is driven around its eloquence, its expressiveness and its clarity.
And those qualities are tightly coupled with the language in which the framework is written.
However I feel like PHP ruins everything: its syntax and core structure isn't ideal for a beautiful framework.

# PHP ruins the beauty of Laravel

I'm talking about details, such as:
- The `$` sign before variables
- The `.` to concatenate strings (how logic is that?)
- The `->` to access object properties (ok, maybe that one is cool, but little bit too long to type)
- Most of built-in functions are abbreviated.
To check if a string contains a substring, we use `strpos()`. 
This is not eloquent at all, and kind of goes against Laravel principles.
Like, was it costly to write the words entirely? 😁
- To work with arrays, we have to pass the array itself in a function.
Example: `in_array($array, $x)` instead of `$array->contains($x)`
- Passing external variables to closure ( 😭)
- Semicolon `;` is required to end a statement

# JavaScript (and TypeScript)

Whenever I switch to a Laravel backend, I really miss the following
- async-await notation
- Typescript's generic-types
- Object Property Value Shorthand
- Types in general (although it will be an upcoming feature)
- The arrow notation (also an upcoming feature)
- module support
- Custom method definition `X.prototype.myCustomMethod()`
- The array helpers
- and more...

I feel like JavaScript (and TypeScript) are more eloquent than PHP.

# PHP is so unexpressive without a framework

Laravel does a good job about offering sets of helpers (eg: Laravel Collection, Stringable) to try to compensate the shortcoming of PHP. I understand that that's what a Framework is supposed to do, but IMO the language itself should do something about it.

# Community

To finish, I feel like there are more interesting features delivered in EcmaScript (and TypeScript) releases than in PHP. See, like, we usually get exited for new Laravel versions, but not really for new PHP versions (am I wrong?). And that's an issue.

So, yeah.. is that crazy? 😁 😭 😭

**Comment by happyDemon** [comment]
use adonisjs, it's the closest thing you'll get.
I'm pretty sure Laravel won't make the switch

**Comment by brother** [comment]
> * The `->` to access object properties (ok, maybe that one is cool, but little bit too long to type)
> 
> * Most of built-in functions are abbreviated.
>   To check if a string contains a substring, we use `strpos()`.
>   This is not eloquent at all, and kind of goes against Laravel principles.
>   Like, was it costly to write the words entirely?

Either things are too long or they are not. Having the troll cake and eating it at the same time is hard.

**Comment by let-aurn** [comment]
@brother I mean, `strpos()` does not clearly say what it does. You can't be sure unless you read some doc (wich means, is not eloquent).
I guess I'd be okay with `index_of()` or something else not abbreviated.
And yeah,  maybe the `->` souldn't be in that list.

**Comment by ollieread** [comment]
@let-aurn yeah but `str` is an almost universally understood abbreviation of string and `pos` is an almost universally understood abbreviation of position.
