### ISSUE TITLE
Out of the box Support for Change Password.

### ISSUE THREAD

**Issue by ManojKiranA** [laravel/ideas#2184]
For 90% of the web Application there will be a change password Feature.

I am adding this feature  every Laravel Projects. It would be Helpful if Laravel Supports out of the box by default.

**Comment by alexbowers** [comment]
This is built in as a Forgot Password feature already.

https://laravel.com/docs/7.x/passwords

**Comment by ManojKiranA** [comment]
> This is built in as a Forgot Password feature already.

I am talking about Change Password Feature while i logged in. I am not talking about Resetting Password.

**Comment by cyrildewit** [comment]
@ManojKiranA you can send a pull request and see if it's getting merged.

**Comment by ManojKiranA** [comment]
Closing this because of Jetstream Package

**Comment by ManojKiranA** [comment]
Closing this because of Jetstream Package
