### ISSUE TITLE
Name Attribute not supported on Route Groups.

### ISSUE THREAD

**Issue by Sahaj-15** [laravel/ideas#2207]
Whenever you supply the 'name' attribute to a route group in a way like this:
`Route::group(['name' => 'admin. '], function() { });`
it doesn't actually work. You may try using the route helper and you can reproduce the error yourself. Instead, if we use 'as' attribute, we get the functionality needed. For example: you may assign the name attribute to 'admin' and make a get route within the route group, you will see that 'admin.' is not getting preppended to the name of that route. More detailed steps-:

HOW TO REPRODUCE:
1. Make a route group as described above.
2. Make a route within that route and name it whatever you want.
2. Make any blade file and try to use the route helper to get URL of the route. The expected functionality is something like `route('admin.name')` but instead it gives an error. If you use `route('name')` it does actually work.

Not only that, you can also do something like this ``Route::name()->group();`` and it works. Why is that so?

**Comment by Sahaj-15** [comment]
Sorry, wrong repo

**Comment by fletch3555** [comment]
You're looking for `prefix` by the way

**Comment by Sahaj-15** [comment]
nope. names are different than prefixes.

**Comment by fletch3555** [comment]
Nope, a prefix on a route group is prepended to the name of any routes defined within the group.
