### ISSUE TITLE
Mark some obvious TODO points in the code

### ISSUE THREAD

**Issue by adamhopkinson** [laravel/ideas#2210]
Would it be beneficial to developers new to Laravel if certain parts of the out-of-the-box config were marked with TODO (which - at least in PHPStorm - flag in the TODO pane)?

For example, I've just setup mail notifications but need to remember to configure the default `from` address - so I've added a TODO:

```
// TODO customise default from email address
'from' => [
    'address' => env('MAIL_FROM_ADDRESS', 'hello@example.com'),
    'name' => env('MAIL_FROM_NAME', 'Example'),
],
```

Happy also to be told that this is not the direction the code should go in!

**Comment by mfn** [comment]
If we start doing this and people using IDEs relying on this, they get reminded about things they not even created and that might be "noise" for them.

E.g. IDE have default settings to check "TODO" in code before _commiting_ , this could be quite annoying.

And then there might be people not even need this feature but still have the TODO marker there for no reason.

Therefore 👎 from me. This is simply an education/docs problem, if it is one at all.

**Comment by adamhopkinson** [comment]
Fair. Thanks for your input @mfn!
