### ISSUE TITLE
Idea: Command setVerbosity to set output's verbosity too

### ISSUE THREAD

**Issue by JohnyProkie** [laravel/ideas#2220]
Laravel 5.8
`\Illuminate\Console\Command::setVerbosity` sets verbosity to self only, leaving `\Illuminate\Console\Command::$output` verbosity unchanged. That is kinda unexpected behavior by me.
Can `setVerbosity` definition be as following?
```
protected function setVerbosity($level)
    {
        $this->verbosity = $this->parseVerbosity($level);
        $this->output->setVerbosity($this->verbosity);
    }
```
E.g. When I define custom `--dry-run` I automatically set Debug verbosity, therefore extra line is necessary
```
if ($this->hasOption('dry-run')) {
    $this->dryRun = $this->option('dry-run');
    $this->setVerbosity(OutputInterface::VERBOSITY_DEBUG);
    $this->output->setVerbosity(OutputInterface::VERBOSITY_DEBUG);
}
```
Didnt test Laravel 6+ or 7+ behavior but it seems to be the same.

Or from different perspective, is `\Illuminate\Console\Command::$verbosity`needed at all? Can output's verbosity be passed where needed, instead of creating?

**Comment by themsaid** [comment]
Feel free to submit a PR
