### ISSUE TITLE
Queue: dispatch event for Queue::push

### ISSUE THREAD

**Issue by thiagof** [laravel/ideas#2222]
- It will be helpful for monitoring and debug purposes;
- It could be available for automations and coupling;
- It would enable some extendability of the drivers without touching those services.

https://github.com/laravel/framework/blob/0b12ef19623c40e22eff91a4b48cb13b3b415b25/src/Illuminate/Queue/RedisQueue.php#L91

**Comment by themsaid** [comment]
Feel free to submit a PR
