### ISSUE TITLE
Allow to auth with email or username

### ISSUE THREAD

**Issue by gentritabazi01** [laravel/ideas#2223]
### This is more cool:
`
Auth::attempt($emailOrUsername, $password);`

**Comment by JustSteveKing** [comment]
`Auth::attempt()` accepts an array of credentials allowing you in your business logic to dictate the logic attribute in a model level, I'm not sure how valuable this would be

**Comment by crynobone** [comment]
You could check out https://github.com/laravie/authen which provide this exact feature.
