### ISSUE TITLE
Ability to ignore default route parameters in controller methods

### ISSUE THREAD

**Issue by Stichoza** [laravel/ideas#2224]
`URL::defaults()` is a very nice feature, especially for setting locales, but the thing is that in most cases those default parameters (like `locale`) is not needed in any controller method.

In current case, all controller method signatures should include `$locale` parameter while it's not used in most of the time.

### Idea

make something like `URL::ignoredDefaults(...$keys)` which will remove parameters from controller methods.

So if we have `URL::ignoredDefaults('locale')`, then in controller

```php
public function page($locale, $id, $slug) { /* $locale is not used at all */ }
```

will become:

```php
public function page($id, $slug) { ... }
```

### More info about locales

As I've seen, most people have a middleware where they set `app.locale` depending on url segment. after that, the locale parameter is not used in controller methods so the unused parameter is just making code dirty.

Plus, most translation packages (like [astrotomic/laravel-translatable](https://github.com/Astrotomic/laravel-translatable)) use `app.locale` for translations.

I think it will make controllers much cleaner.

**Comment by koenhoeijmakers** [comment]
To achieve said feature you can already create a middleware that does the following:
```
$request->route()->forgetParameter('locale');
```
This middleware would have to be registered _before_ `SubstituteBindings`.

**Comment by Stichoza** [comment]
@koenhoeijmakers Thanks man! Never heard of `forgetParameter` method before. You've just literally improved my everyday life 😁
