### ISSUE TITLE
It should be possible for getPdoForSelect to optionally fallback to the write connection

### ISSUE THREAD

**Issue by addshore** [laravel/ideas#2225]
This may be desired in some situations.

Currently if the "read" hosts can not be connected to there is no further fallback possible.
This means the PDOException will bubble all of the way up.
Ideally via configuration it should be possible to fallback to the "write" host in these cases.

This will likely need modification in and around:
 - https://github.com/laravel/framework/blob/39056ae4cb6172ef7d86dbc2b1a54c0bf97f0c04/src/Illuminate/Database/Connectors/ConnectionFactory.php#L99-L102 (gets the read PDO callback, which has fallback through the registered hosts)
 - https://github.com/laravel/framework/blob/39056ae4cb6172ef7d86dbc2b1a54c0bf97f0c04/src/Illuminate/Database/Connectors/ConnectionFactory.php#L177-L189 (which is the callback falling through read hosts)

Possible solutions:
 - Wrap this closure in another closure that handles fallback to write if the previous closure fails to get a connection
 - Modify createPdoResolverWithHosts to not always shuffle, allowing the write host to be added to the end of the read hosts?
 - Something else

**Comment by themsaid** [comment]
Feel free to submit a PR with the suggested changes.
