### ISSUE TITLE
Detecting Expired Cache and Refreshing the Cache

### ISSUE THREAD

**Issue by kharysharpe** [laravel/ideas#2226]
Hey Artisans,

I have a situation wherein I get data from a third party API that updates infrequently and often times it's down / unavailable / not updated ... the usual suspects.

I want to check if the data has expired and attempt to get new data while continuing to serve the expired (cached) data to users.

I would like for a way for expired cache to remain around and continue to be accessed until it is updated.

Currently there is no framework way to manage stale (expired) content.

_My thoughts as code:_

```php
// Cache::put('key', 'value', $seconds, $keepAlive = false);
Cache::put('key', 'value', $seconds, true); // keep alive after expiration

// $value = Cache::get('key', 'default', $refreshOnExpiration = false);
Cache::get('key', function() {
  return do_something();
}, true);

```

**OR**

```php
// Cache::put('key', 'value', $seconds, $keepAlive = false);

Cache::put('key', 'value', $seconds, true); // keep alive

if (Cache::expired('key')) {
    // Get the lock so this is the only process updating the cache
    $lock = Cache::lock('key', 90);

    if ($lock) {
        // We got the lock so attempt to update the cache
       $value = do_something();

       if ($value) {
           Cache::put('key', $value, now()->addMinutes(10), true); // keep alive after expiration
       } else {
           // Getting the new value failed return expired cache until next attempt
           $value = Cache::get('key');
      }       
    } else {
      // Another process is updating the cache return what we currently have stored
       $value = Cache::get('key');
    }

}

echo $value
```

May also solve #1733

Can this become apart of the core and drop the need for third party solutions?

**Comment by linaspasv** [comment]
Well you do not need any 3rd party... You can easly get the bahaviour you want with a Cache::rememberForever, where you also add expires date inside the cache. There is no need to reinvent the wheel.

See an example code below:

```php
Cache::rememberForever('response', function () {
    $response = [
        'hello world'
    ];

    return [
        $response,
        Carbon::now()->subDays(2)
    ];
});

if ([$payload, $expires_at] = Cache::get('response')) {
    // check if data inside the cache has expired, keep serving the old one or just update it
    if ($expires_at->isPast()) {
        dd('Cache has expired, do something about it.');
    }

    dd($payload);
}
```

**Comment by kharysharpe** [comment]
That's how I envisioned it being implemented but it also needs to take in to consideration atomic locking with first to lock doing the updating of the cache or returning the current cache otherwise. 

Based on what you wrote, it could possible be as simple as this

```php
// $value = Cache::get('key', 'default', $refreshInSeconds = false);

$response = Cache::get('response', function() {
  return 'hello world';
}, Carbon::now()->subDays(2));
```  

Looking for first class support and better developer experience.

**Comment by themsaid** [comment]
No plans for this at the moment.
