### ISSUE TITLE
Configuration in database.php for "Transaction isolation level"

### ISSUE THREAD

**Issue by duxthefux** [laravel/ideas#2228]
Hi,

we currently ran into the situation where we need to set the transaction isolation level for mysql.

We implemented it and thought maybe it makes sense to bring that into laravel core, as laravel currently lacks that possibility, whereas Doctrine provides that possibility.

We currently configure it in database.php
```
return [
    'connections' => [
          'default' => [
                ...
               'host' => env('DB_HOST'),
               ...
               'isolation_level' => env('DB_ISOLATION_LEVEL', 'REPEATABLE READ'),
              ....
            ]
      ]
];
```

I could prepare a pull request if it makes sense.

Best

**Comment by jorgcastellano** [comment]
I'm interested in know if it works, this

**Comment by mfn** [comment]
I'd say go for a PR; many of these options have been merged (e.g. new addition in `\Illuminate\Database\Connectors\MySqlConnector::connect` maybe).

**Comment by duxthefux** [comment]
@mfn created PR https://github.com/laravel/framework/pull/33783

**Comment by duxthefux** [comment]
PR got merged

**Comment by mfn** [comment]
@duxthefux congratulations 😄
