### ISSUE TITLE
Eloquent whereConcat(...) orWhereConcat(...)

### ISSUE THREAD

**Issue by gofish543** [laravel/ideas#2232]
I am once again faced in my application the need for a concat column.
Seems relatively straight forward, `User::select(DB::raw('CONCAT(first," ", last) as full_name'))`.
Except now that line of code will only work with MySQL (Or a MySQL variant) 

Now what happens if I have a **test suite that runs off of Sqlite** where concat is done using `||`?
Or another database management system? I can't.

What I propose is two additional Eloquent methods, `whereConcat()` and `orWhereConcat()` with the parameters:
`whereConcat($columns, $operator = '=', $value='')`
`whereConcat(['first', 'last'], '=', 'My Full Name')`
with the resulting query looking like  `SELECT CONCAT(first," ", last) as first_last FROM users` with the 'AS' line being set to `implode('_', $columns)`

Let me know your thoughts!

**Comment by koenhoeijmakers** [comment]
Or you could just test on a database that actually represents your production environment, have a look at [this](https://laravel-guide.readthedocs.io/en/latest/database-testing/#using-transactions)

**Comment by gofish543** [comment]
Or I could have a local testing with SQLite and also have my staging system for mirrored testing as well. 
Your comment felt really back handed and disrespectful and not really relevant in anyway to the original idea... not something I usually see out of the Laravel community; especially in the idea section of the framework

**Comment by gofish543** [comment]
Or I could have systems that just happen to use different databases. Your comment feels kinda disrespectful imo

**Comment by hicham-saddek** [comment]
i guess you can try to make your own driver that extends the Laravel own mysql driver and extends your desired functions and then use them as a package, might work but will require certain modifications on your part if you would like to spend some time on it.

or you can always add a scope in a Trait like this:

file app/Traits/scopes/ConcatScope.php
**First part (i couldnt take a screenshot of all in one go)**
![image](https://user-images.githubusercontent.com/36214361/81421706-2c9c2d80-9152-11ea-8a5e-7628bce819b8.png)

**Second part**
![image](https://user-images.githubusercontent.com/36214361/81421340-a41d8d00-9151-11ea-8b7b-7eef66a142c7.png)


and then you can use it this way:
![image](https://user-images.githubusercontent.com/36214361/81421242-71739480-9151-11ea-876b-691544bd64a4.png)


this way now if you would like to do a select you can always now use
`User::whereConcat(['first', 'last'], 'John Doe')`

i don't know if this is the solutions you've been looking for but i tried my best, sorry for my english btw am from france lol ...

Well hope you find your answer if this is not enough, wish u best luck.

**Comment by hicham-saddek** [comment]
Sorry i did one small mistake on the line 20 should be DB::raw($select)instead of $as
`return $builder->select(DB::raw("$select as $as"))->where(DB::raw($select), $value);` and then it works like a charm...

**Comment by hicham-saddek** [comment]
This is an example for the usage in tinker, but i only tried in MySQL so if you would like to try it u can add a file named database.sqlite in your database folder and then use sqlite driver in your .env file and try it again ...
![image](https://user-images.githubusercontent.com/36214361/81424443-42abed00-9156-11ea-9492-3383fac6b452.png)

**Comment by gofish543** [comment]
@hicham-saddek I appreciate your answer, but I want to avoid doing a custom driver and I currently use a trait to solve the problem (actually very similar to your code) but it feels hacky and not the best solution.

When this idea inevitably gets closed I’m thinking of doing a query builder macro similar to https://laravel.io/forum/03-10-2015-how-to-properly-create-a-custom-query-builder-method this tutorial and seeing how it turns out

**Comment by hicham-saddek** [comment]
I mean yeah it would really be a nice thing to add to Laravel, cuz it might not be obvious at first but when you look at it it can help solve many problems like having to deploy on many different servers at once while using different drivers... this should be added to Laravel.
am sure @driesvints can be really kind here to tell us if they can or can not add this to laravel some time in the future ?

**Comment by gofish543** [comment]
For anyone who has this same problem and wants `concat` built into the query builder here is my solution...

Usage (I wrote the escape like helpers, but you get the idea
```php
<?php

User::where(function (Builder $query) use ($search) {
    return $query->orWhereConcat(['first', 'last'], 'LIKE', "%{$this->escapeLike($search)}%")
        ->orWhereConcat(['last', 'first'], 'LIKE', "%{$this->escapeLike($search)}%");
});
```
My Provider to register the macro
```php
<?php

namespace App\Providers;

use App;
use App\Database\Query\Builder\Macros\WhereConcat;
use Illuminate\Database\Query\Builder;
use Illuminate\Support\ServiceProvider;

class QueryBuilderServiceProvider extends ServiceProvider {

    /**
     * Bootstrap any application services
     *
     * @return void
     */
    public function boot() {
    }

    /**
     * Register any application services
     *
     * @return void
     */
    public function register() {
        $this->registerWhereConcat();
    }

    /**
     * Register the rankings method for collections
     *
     * @return void
     */
    private function registerWhereConcat() {
        Builder::macro('whereConcat', function ($columns, $operator = '=', $value = null) {
            return WhereConcat::whereConcat($this, $columns, $operator, $value);
        });

        Builder::macro('orWhereConcat', function ($columns, $operator = '=', $value = null) {
            return WhereConcat::orWhereConcat($this, $columns, $operator, $value);
        });
    }
}
```

Macro
```php
<?php

namespace App\Database\Query\Builder\Macros;

use Exception;

// @todo test
class WhereConcat {

    /**
     * @param $builder
     * @param $columns
     * @param string $operator
     * @param null $value
     * @return mixed
     * @throws \Exception
     */
    public static function whereConcat($builder, $columns, $operator = '=', $value = null) {
        $phrase = self::Builder($builder, $columns);

        return $builder->whereRaw("{$phrase} {$operator} ?", $value);
    }

    /**
     * @param $builder
     * @param $columns
     * @param string $operator
     * @param null $value
     * @return mixed
     * @throws \Exception
     */
    public static function orWhereConcat($builder, $columns, $operator = '=', $value = null) {
        $phrase = self::Builder($builder, $columns);

        return $builder->orWhereRaw("{$phrase} {$operator} ?", $value);
    }

    /**
     * @param $builder
     * @param $columns
     * @return string
     * @throws \Exception
     */
    private static function Builder($builder, $columns) {
        switch ($builder->getConnection()->getDriverName()) {
            case 'mysql':
                foreach ($columns as $key => $column) {
                    $columns[$key] = "`{$column}`";
                }
                $cols = implode(", ' ', ", $columns);

                $concatPhrase = "CONCAT({$cols})";
                break;
            case 'sqlite':
                foreach ($columns as $key => $column) {
                    $columns[$key] = "`{$column}`";
                }
                $cols = implode(" || ' ' ||", $columns);

                $concatPhrase = $cols;
                break;
            default:
                throw new Exception("Unsupported driver for whereConcat");
                break;
        }

        return $concatPhrase;
    }
}
```

**Comment by LemarinelNet** [comment]
Sure this would be helpful in the core in my own !!
I found myself using this particular use-case (search on name concatenated to surname with a like) many times, and I think it should be part of the core...
How can we propose this to the laravel team ?

**Comment by 3AMC** [comment]
There is a simple way too based on the comments above (with Capsule): 

`use Illuminate\Database\Capsule\Manager as Capsule;

private function getConcatString($aToConcat) {
        //Variables
        //Code
        switch (Capsule::connection(env("DB_CONNECTION"))->getDriverName()) {
            case 'sqlite':
                return implode(' || ', $aToConcat);
            default:
                return "CONCAT(" . implode(',', $aToConcat) . ")";
        }
    }`

**Comment by mattkenefick** [comment]
I made a few changes to @gofish543's `WhereConcat` class. 

**Notably:**

- It compares the provided columns to the builder table's columns. If not found, assumes literal string.
- Assumes a default equality operator if one isn't provided.

This can handle operations like:

```
    $name = 'John Smith';
    $model = MyModel::whereConcat([ 'first_name', ' ', 'last_name'], $name);
```

---

```
<?php

namespace App\Database\Query\Builder\Macros;

use Exception;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * WhereConcat
 */
class WhereConcat
{
    /**
     * Memoize columns from table
     *
     * @var array
     */
    private static $columnListings = [];

    /**
     * @param $builder
     * @param $columns
     * @param string $operator
     * @param null $value
     * @return mixed
     * @throws \Exception
     */
    public static function whereConcat($builder, array $columns = [], $operator = '=', $value = null)
    {
        $phrase = self::Builder($builder, $columns);

        // e.g. ->whereConcat([...], 'myvalue');
        if ($value === null) {
            $value = $operator;
            $operator = '=';
        }

        return $builder->whereRaw("{$phrase} {$operator} ?", $value);
    }

    /**
     * @param $builder
     * @param $columns
     * @param string $operator
     * @param null $value
     * @return mixed
     * @throws \Exception
     */
    public static function orWhereConcat($builder, array $columns = [], $operator = '=', $value = null)
    {
        $phrase = self::Builder($builder, $columns);

        // e.g. ->orWhereConcat([...], 'myvalue');
        if ($value === null) {
            $value = $operator;
            $operator = '=';
        }

        return $builder->orWhereRaw("{$phrase} {$operator} ?", $value);
    }

    /**
     * @param $builder
     * @param $columns
     * @return string
     * @throws \Exception
     */
    private static function Builder($builder, array $columns = []): string
    {
        // SQL driver name as lowercase
        $driverName = self::getDatabaseDriverName($builder);

        // Columns from the table
        $tableColumns = self::getColumnsForTable($builder->from);

        // Determine how to wrap our field names
        $filter = function($field) use($tableColumns) {
            return in_array($field, $tableColumns)
                ? "`{$field}`"
                : "'" . addslashes($field) . "'";
        };

        // Differentiate concatenation techniques per driver
        switch ($driverName) {
            case 'mysql':
                $concatPhrase = 'CONCAT(' . implode(', ', array_map($filter, $columns)) . ')';
                break;

            case 'sqlite':
                $concatPhrase = implode(' || ', array_map($filter, $columns));
                break;

            default:
                throw new Exception('Unsupported driver for whereConcat');
                break;
        }

        return $concatPhrase;
    }

    /**
     * Fetch column listings for the table and cache them
     *
     * @param string $tableName
     * @return array
     */
    private static function getColumnsForTable(string $tableName): ?array
    {
        if (!isset(self::$columnListings[$tableName])) {
            self::$columnListings[$tableName] = DB::getSchemaBuilder()->getColumnListing($tableName);
        }

        return self::$columnListings[$tableName];
    }

    /**
     * Return a simplified driver name for our connection that we
     * can switch on.
     *
     * @return string
     */
    private static function getDatabaseDriverName($builder): string
    {
        return strtolower($builder->getConnection()->getDriverName());
    }
}
```
