### ISSUE TITLE
Laravel Documentation Dark Mode

### ISSUE THREAD

**Issue by gentritabazi01** [laravel/ideas#2234]

**Comment by qwertynik** [comment]
+1
@gentritabazi01 thanks for adding

**Comment by WoLfulus** [comment]
This is really useful. I went looking to make a PR for this, but the docs repository seems to contain only markdown files :(

**Comment by julienbourdeau** [comment]
@WoLfulus I believe this is this repository: https://github.com/laravel/laravel.com-next/blob/master/app/Http/Controllers/DocsController.php

**Comment by gentritabazi01** [comment]
@taylorotwell @driesvints

**Comment by themsaid** [comment]
Feel free to submit a Pull Request 👍
