### ISSUE TITLE
Requested: saveAndRefresh() and updateAndRefresh() method for models

### ISSUE THREAD

**Issue by dylan7778** [laravel/ideas#2235]
I find myself writing an extra line of code every time I update a model and then subsequently need to access the updated model, specifically updated relationships. For instance, I might have something like this:

`$article->user_id = $request->user_id;`
` $article->save();`

But then if I want to reference the $article->user relationship on the model, I have to call $article->refresh() first. Wouldn't it be possible for us to just have a simplified method for $article->saveAndRefresh() that would save the data, and then immediately allow us to access the relationship without having to write the separate line of refresh() code? I envision the same thing with the update method.

**Comment by Lloople** [comment]
I think you could also do `$article->user()->attach($request->user_id)` to achieve that. Or maybe you would need to load the user first with `User::find($request->user_id)`, but haven't tried it yet

**Comment by dylan7778** [comment]
I believe you still have to reload article if you do that, but I will try and see. Regardless, this is a very basic example I cane up with off the top of my head. A function that saves and refreshes the model in one line and does it very purposefully and plainly would still be great to have.

**Comment by themsaid** [comment]
Feel free to open a PR with your suggestion
