### ISSUE TITLE
Why is stub publishing its own command?

### ISSUE THREAD

**Issue by ollieread** [laravel/ideas#2237]
The `stub:publish` command doesn't seem to make a huge amount of sense as its own command.

Shouldn't this be part of the `vendor:publish` command under the tag `stubs`?

**Comment by hicham-saddek** [comment]
There quite a difference i guess,am not a Laravel certified user,but i guess the `vendor:publish` publish any publishable assets from vendor package such as migrations and configurations etc ... but the `stub:publish` it does in fact publish the vendor files but it does the same for anything else available, so i guess the difference here is that vendor publish` only interacts with the vendor folder if u would like to do other changes before or smthng ...

hope my answer is true...

**Comment by ollieread** [comment]
@hicham-saddek The `vendor:publish` command also publishes laravel assets, not just third party vendor assets.

**Comment by hicham-saddek** [comment]
Well in that case i agree this should only be one and only one command to keep `stub:publish` for example.

@JeffreyWay if you can take a deeper look at this.
