### ISSUE TITLE
Laravel Eloquent Model properties

### ISSUE THREAD

**Issue by ashishkpoudel** [laravel/ideas#2240]
Laravel Eloquent is no doubt an awesome ORM but having dynamic properties that auto-magically map to table column is not how I see laravel should move forward. Now that PHP 7.4 has typed properties I think it's time to bring real properties to model. Having to access properties that don't even exist in class is not good.

Accessing properties in large codebase from models sucks, it forces us to always visit what column is in the database. Models are not always about database tables.

Someone might say use doc-block but let me tell you that it does not make code better. having to access their properties in large models sucks also resource class do have the same problem of accessing magic properties I think there is room for improvement.

Given code is taken from Yii models
```
namespace app\models;

use yii\base\Model;

class ContactForm extends Model
{
    public $name;
    public $email;
    public $subject;
    public $body;
}
```
reference link:-  https://www.yiiframework.com/doc/guide/2.0/en/structure-models#defining-attributes

I can't think of any reason why it's not possible in laravel. Also at last thank you laravel core, community folks for making such an awesome framework.

**Comment by koenhoeijmakers** [comment]
> Models are not always about database tables.

What do you mean by this? Eloquent models always refer to some kind of persistence.

I do agree that accessing magic properties isn't really preferred and i normally end up with methods like `getName(): string` and such to enforce type safety and readability, but i don't think Eloquent is going to change to this kind of ORM. (you can have a look at **doctrine** though which does what you describe).

**Comment by ashishkpoudel** [comment]
> > Models are not always about database tables.
> 
> What do you mean by this? Eloquent models always refer to some kind of persistence.
> 
> I do agree that accessing magic properties isn't really preferred and i normally end up with methods like `getName(): string` and such to enforce type safety and readability, but i don't think Eloquent is going to change to this kind of ORM. (you can have a look at **doctrine** though which does what you describe).

It's quite common to think model as a representation of the table in the database but it's just one use case

**Comment by koenhoeijmakers** [comment]
Could you explain another usecase where you _need_ the representation to be a model instead of a plain old php object

**Comment by hicham-saddek** [comment]
i agree with @koenhoeijmakers sometimes you need to get over with things like fillable and guarded if we can somehow not entirely remove the virtual attributes but instead we would use the own php variables to simulate the fillable attributes and their types as the casting type we can in fact result in a more secure and easy way to simulate our Model and ofcourse the other attributes can be added in the PHPDoc for viewing purposes.

**Comment by ashishkpoudel** [comment]
> Could you explain another usecase where you _need_ the representation to be a model instead of a plain old php object

**Comment by ashishkpoudel** [comment]
@koenhoeijmakers yes one example would be a representation of data from a CSV files

**Comment by sisve** [comment]
The important part is the name; "Eloquent models". Eloquent is Active Record, and an Eloquent model matches a corresponding table. Building a csv writer/reader will create another type of domain models, and using Doctrine a third type of models. I've often worked in projects that have several different projects all named "{ProjectName}.Domain" where every sub-component has different domain models.

Transforming Eloquent into something else sounds like a huge undertaking, and perhaps a waste of time when there already are well-known replacements like Doctrine. http://www.laraveldoctrine.org/

**Comment by julienbourdeau** [comment]
I think that would break the Accessors & Mutators feature and especially the new amazing custom cast feature.
https://laravel.com/docs/7.x/eloquent-mutators

**Comment by hicham-saddek** [comment]
it won't because if u use for example protected values like
```
/** @var Json $meta */
protected $meta = [];
```

it won't break them as the use the call method to access those feature and if you try to access them it will obviously return you to the call method so it stills the same nothing will change ?

am not an expert in Eloquent but if my logic is right that could be a nice feature to add to even add auto generated migrations for example...

**Comment by themsaid** [comment]
No plans for this at the moment
