### ISSUE TITLE
Is there a reason Laravel doesn't provide psr/container-implementation?

### ISSUE THREAD

**Issue by AegirLeet** [laravel/ideas#2241]
As the title says, is there a specific reason neither `illuminate/container` nor `laravel/framework` [provide](https://getcomposer.org/doc/04-schema.md#provide) `psr/container-implementation` in their *composer.json*, or is this just an oversight?

PSR-11 [says](https://www.php-fig.org/psr/psr-11/#2-package):

> Packages providing a PSR container implementation should declare that they provide psr/container-implementation 1.0.0.
> 
> Projects requiring an implementation should require psr/container-implementation 1.0.0.

Since the container already implements PSR-11, adding this seems like no-brainer to me.

**Comment by julienbourdeau** [comment]
> Projects requiring an implementation should require psr/container-implementation 1.0.0.

Laravel need illuminate/container, not any container implementation.

Requiring `psr/container-implementation` is for package which need **any PSR-11 container**. This is usually for packages for instance.

**Comment by AegirLeet** [comment]
> Laravel need illuminate/container, not any container implementation.

I'm talking about the other part of that quote. Laravel should **provide** psr/container-implementation.
