### ISSUE TITLE
Having a cache helper for storing results in current request

### ISSUE THREAD

**Issue by avinash403** [laravel/ideas#2242]
There are cases where a single query/computation happens multiple times within a request. It would be nice to have a way of caching a method's result in memory(maybe using an array cache driver) and then use it even outside that class.

let's say this is a method
```
public function expensiveCalculation($argOne, $argTwo)
{
    return quickCache(function(){
 		return "some expensive calculation";
    })
}
```
Now, for retrieving this we only have to call some combination of class/method name.
Internally it could have used json_encode string of `$argOne` & `$argTwo`(method/class name) as key.

**Comment by royduin** [comment]
https://github.com/spatie/once 👍

**Comment by martinbean** [comment]
@avinash403 This would introduce as many bugs as it would “fix”.

Caching needs a nuanced approach. You can’t just cache the output of a method for future invocations.
