### ISSUE TITLE
Add filtering by column which added with addSelect() method

### ISSUE THREAD

**Issue by adiletmaks** [laravel/ideas#2243]
Now, I can only sort like this

```php
Destination::addSelect(['last_flight' => Flight::select('name')
    ->whereColumn('destination_id', 'destinations.id')
    ->orderBy('arrived_at', 'desc')
    ->limit(1)
])
->orderBy('last_flight')
->get();
```

but I can't filter by this column

```php
Destination::addSelect(['last_flight' => Flight::select('name')
    ->whereColumn('destination_id', 'destinations.id')
    ->orderBy('arrived_at', 'desc')
    ->limit(1)
])
->where('last_flight', '')
->get();
```

**Comment by koenhoeijmakers** [comment]
MySQL's order of execution defines that the `where` clauses are executed before the `select` clause, therefore your `last_flight` doesn't exist yet.

But i can somehow see this work if Eloquent would check if a subquery exists for the given column and replicate said query.
