### ISSUE TITLE
Eloquent ->latest() doesn't work if model doesn't use timestamps

### ISSUE THREAD

**Issue by arsen-s** [laravel/ideas#2245]
By default `->latest()` uses 
```
if (is_null($column)) {
            $column = $this->model->getCreatedAtColumn() ?? 'created_at';
        }
```
but it doesn't work if $timestamp is false for model because it still tries to order by created_at.
Would it be best to use id by default?

**Comment by ManojKiranA** [comment]
you can pass `id` as a argument to `latest `method

**Comment by arsen-s** [comment]
@ManojKiranA yeah, I know, but the default it uses non existing column

**Comment by mrcat323** [comment]
@arsen-s by default it checks for timestamps, but you can view all your "latest" records with certain column, i think everything is fine

**Comment by rs-sliske** [comment]
it feels like a fairly big breaking change to just switch it to use id rather than created at

maybe it is reasonable to allow which field it uses by default to be configured in each model

something like 
```php
public function getColumnForLatest() : string {
    return $this->getCreatedAtColumn();
}
```

**Comment by Sn0wCrack** [comment]
Could this not be achieved by modifying the latest method on the Eloquent Query Builder with something similar to the following?

```php
    /**
     * Add an "order by" clause for a timestamp to the query.
     *
     * @param  string  $column
     * @return $this
     */
    public function latest($column = null)
    {
        if (is_null($column)) {
            if ($this->model->usesTimestamps()) {
                $column = $this->model->getCreatedAtColumn() ?? 'created_at';
            } else if ($this->model->getKeyType() == 'int') {
                $column = $this->model->getKeyName();
            } else {
                $column = 'created_at';
            }
        }


        $this->query->latest($column);

        return $this;
    }
```
