### ISSUE TITLE
implement lock() function for authentication

### ISSUE THREAD

**Issue by ariaieboy** [laravel/ideas#2246]
since laravel 6 we have a new middleware called password.confirm that force people to confirm their password before they wanna access to a specific route 
sometimes password confirmation is needed after an event for example after user change password or trying to submit a form multiple time in a short amount of time or u may wanna lock user each 10 min and ask him to confirm the password and etc 

having a method that lock user and ask for password verification is useful in my opinion

**Comment by mfn** [comment]
I'm not too well acquainted with it, but wondering it [Rate Limiting](https://laravel.com/docs/7.x/routing#rate-limiting) can help here.

Especially the new implementation for Laravel 8 might solve this => https://github.com/laravel/framework/pull/32726 ?

**Comment by ariaieboy** [comment]
> I'm not too well acquainted with it, but wondering it [Rate Limiting](https://laravel.com/docs/7.x/routing#rate-limiting) can help here.
> 
> Especially the new implementation for Laravel 8 might solve this => [laravel/framework#32726](https://github.com/laravel/framework/pull/32726) ?

definitely it will help but still the function that i said is required so after a user reached the limit we can lock his session and ask him to enter his password again 
the function just add more flexibility to the codes that programmer have this feature to lock a specific user whenever he want

**Comment by themsaid** [comment]
I think this is better implemented as a package.
