### ISSUE TITLE
Extend support of "fromSub" to relations

### ISSUE THREAD

**Issue by SergioDonati** [laravel/ideas#2249]
Actually this throw IllegalArgumentException
```php
// throw IllegalArgumentException
$query->fromSub($user->myHasManyRelation(), 'my_relation_table'); 

// work
$query->fromSub($user->myHasManyRelation()->getQuery(), 'my_relation_table'); 
```
fromSub support only `\Closure|\Illuminate\Database\Query\Builder|string`

I think that it is really easy support also `\Illuminate\Database\Eloquent\Relations\Relation` so we can just pass the relation without remember to call `->getQuery()`

What you think about add this little change?

**Comment by themsaid** [comment]
Feel free to open a PR
