### ISSUE TITLE
Provide static setUpBeforeClass and tearDownAfterClass to allow model creation/destruction

### ISSUE THREAD

**Issue by sfsccn** [laravel/ideas#2250]
In addition to `setUp()` and `tearDown()`, I'm wondering if `Illuminate\Foundation\Testing\TestCase` could also provide the static methods `setUpBeforeClass()` and `tearDownAfterClass()`. One possible result would be that by calling `parent::setUpBeforeClass()` one could create models in `setUpBeforeClass()` and, similarly, delete them in `tearDownAfterClass()`.  This would allow the models to be created/deleted once per class rather than in every test method in the class via `setUp()` and `tearDown()`.

I believe a key step in `setUpBeforeClass()` and `tearDownAfterClass()` would be something like the non-static `createApplication()` method in the `CreatesApplication` trait. Currently, I can work with models in `setUp()` if `parent::setUp()` is called. As far as I can tell, `parent::setUpBeforeClass()` does nothing, it's just the empty PHPUnit method meant to be overridden. Therefore, I cannot seem to work with models in `setUpBeforeClass()` unless I add something like this:

``` php
    public static function boostrapApp()
    {
        $app = require __DIR__ . '/../../../bootstrap/app.php';
        $app->make(Kernel::class)->bootstrap();
    }
```

Is there some reason that `setUpBeforeClass()` and `tearDownAfterClass()` are not defined in `Illuminate\Foundation\Testing\TestCase`? Should models not be created/deleted at the class level? 

See the related issue https://github.com/laravel/ideas/issues/1350.

**Comment by mr-feek** [comment]
Here's a little hack I did to get around this issue

-------

**Context:**
I wanted to write some feature tests ensuring my caching logic was being hit, and forgotten appropriately. I figured `@depends` along with `Event::fake` was a good way to go about doing so. Usually I wrap my tests  in database transactions, but that doesnt work well with `@depends` since the database transactions rollback after each individual test case run.

**Hack:**
```php
/**
     * @var array<\Illuminate\Database\Eloquent\Model>
     */
    protected static $modelsToCleanup = [];

    public function setUp(): void
    {
        parent::setUp();

        Event::fake([CacheHit::class, CacheMissed::class, KeyWritten::class, KeyForgotten::class]);

        Event::listen(['eloquent.saved: *'], function (string $eventName, array $models): void {
            foreach ($models as $model) {
                dump('saved');
                self::$modelsToCleanup[] = $model;
            }
        });
    }

/**
     * This is definitely a hack, but I cant think of a better way to do this.
     * @see https://github.com/laravel/ideas/issues/2250
     */
    public static function tearDownAfterClass(): void
    {
        $instance = new static();
        $instance->refreshApplication();

        foreach (self::$modelsToCleanup as $model) {
            /** @var \Illuminate\Database\Eloquent\Model $model */
            $model->forceDelete();
            dump('deleted');
        }

        $instance->tearDown();
    }
```

**Comment by sfsccn** [comment]
Thanks, good to know I wasn't missing some standard mechanism.

**Comment by themsaid** [comment]
Feel free to submit a PR.
