### ISSUE TITLE
Support protocol port for laravel route?

### ISSUE THREAD

**Issue by mitoop** [laravel/ideas#2252]
In my case, I use protocol port to differentiate applications in one project. 

For now, I do it in `App\Providers\RouteServiceProvider` by using `$request->getPort() == '8080'`  and  `$request->getPort() == '8090'` to differentiate,  8080, 8090 is custom port. 

This works well except that I cant use `route:cache` command which will lose some route because in console environment, it cant recognize port correctly. 

Could laravel provide a `port` method for route which means this route(s) can only access under this port?

Maybe like this:

```php
Route::port('8080')->group(function(){
      
});
```

**Comment by themsaid** [comment]
Feel free to open a PR
