### ISSUE TITLE
New safe method lockForUpdateSkipLocked() for FOR UPDATE SKIP LOCKED

### ISSUE THREAD

**Issue by Alexeykhr** [laravel/ideas#2253]
I saw this [PR](https://github.com/laravel/framework/pull/31287) and it seems to me that it would be nice to transfer this method to **Builder** or to move it somewhere:

[Illuminate/Queue/DatabaseQueue@getLockForPopping()](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Queue/DatabaseQueue.php#L232)

To a method, for example - `lockForUpdateSkipLocked()`. Which allowed to safely enable `SKIP LOCKED` functionality if it is supported by the current DB or its version.

Now it is necessary to use the `lock('FOR UPDATE SKIP LOCKED')`, but before that, check whether the client has the current database.

**Comment by sisve** [comment]
A thought; if the locking management is important for me, then I expect the code to throw an exception when it isn't supported, similar how a `->lock('FOR UPDATE SKIP LOCKED')` would probably generate a query exception if the syntax isn't supported.

The DatabaseQueue is in a bit of flux. It has historically been considered something for use during development, but should be avoided in production. It is doing its best to work as well as possible, but there are no guarantees.
