### ISSUE TITLE
Ability to pass relationship attributes to custom casts

### ISSUE THREAD

**Issue by madsem** [laravel/ideas#2256]
Right now it doesn't seem possible to pass a relationship to a custom cast as attribute.
For example I'm currently implementing a `Money` value object for a `Campaign` model, where the `currency_code` is in the `Account` model with a `belongsTo` relationship.

The `MoneyCast` would also be needed in other places, but in those models the relationship to get the `currency_code` is different, so I can't just use the relationship directly in the `MoneyCast` class.

It would be great if you could simply do this:

```php
/**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'optimize'  => 'boolean',
        'amounts'   => MoneyCast::class.':relationship=account',
    ];
```

I haven't found a good way to achieve this, but believe it would be beneficial for many use cases.

**Comment by Briareos17** [comment]
Looking for this to, trying to make relation works as value object (image)

**Comment by themsaid** [comment]
Feel free to submit a PR
