### ISSUE TITLE
Ability to listen to Eloquent model events per object

### ISSUE THREAD

**Issue by ChristopheB** [laravel/ideas#2257]
I have a use case where I need to execute some actions after the model is saved, and before [syncOriginal()](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Database/Eloquent/Model.php#L775) is executed, so that I can check what has changed in the model. 

The `saved` model event is basically a place for that, but the actions I need to execute are not generic enough to be bound to the whole class using `static::saved()`.

The idea would be to register some actions on the fly on the Eloquent model events, something like this:
```php
<?php

$user->when('saved', function ($user) {
    // ... this will be executed only for this particular user object
})->save();

$anotherUser->save();  // nothing happens

```

Of course the term `when` is not really great as it has other meanings elsewhere in the framework.

I use this basic implementation at the moment:

```php
<?php

abstract class Model extends \Illuminate\Database\Eloquent\Model
{
    protected $events = [];

    protected static function boot()
    {
        parent::boot();

        Event::listen('eloquent.booted: '.static::class, function ($model) {
            foreach ($model->getObservableEvents() as $event) {
                static::$event(function ($model) use ($event) {
                    $model->triggerEvent($event);
                });
            }
        });
    }

    public function triggerEvent($event)
    {
        foreach ($this->events[$event] ?? [] as $action) {
            $action($this);
        }
    }

    public function when($event, $closure)
    {
        $this->events[$event][] = $closure;

        return $this;
    }
}
```

**Comment by themsaid** [comment]
That doesn't seem like a good use case for using events at all.

**Comment by ChristopheB** [comment]
Ah, thank you for looking into that!

Honestly I have no idea how to tackle that in a different way. As said before, I sometimes _need to execute some actions after the model is saved, and before syncOriginal() is executed_. I currently use the above principle on one model for the saved event. If that can help anyone:


```php


class MyModel extends Model
{
    protected $savedEvents = [];

    protected static function booting()
    {
        static::saved(function ($myModel) {
            $myModel->whenSaved();
        });
    }

    public function whenSaved($closure = null)
    {
        if ($closure) {
            $this->savedEvents[] = $closure;

            return $this;
        }

        foreach ($this->savedEvents as $action) {
            $action($this);
        }
    }
}
```

**Comment by themsaid** [comment]
> so that I can check what has changed in the model.

You can use `$model->getChanges()` after `syncOriginal` is called to find what was changed.

**Comment by ChristopheB** [comment]
In fact I also perform a comparison of changes in some relationships. But thanks for the reminder, my initial code might be pre 5.6, I should dive into it again (it's a complex use case in our repo).
