### ISSUE TITLE
Ability to set `SoftDeletes::deletedAt` with a future value

### ISSUE THREAD

**Issue by edmandiesamonte** [laravel/ideas#2258]
I have a particular use case wherein an entity has an expiration date. I feel that it would be redundant if I will add another column for this use case other than `deletedAt` that is set in the future.

The idea is to simply change this part of [SoftDeletingScope.php](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Database/Eloquent/SoftDeletingScope.php):
```php
  /**
     * Apply the scope to a given Eloquent query builder.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $builder
     * @param  \Illuminate\Database\Eloquent\Model  $model
     * @return void
     */
    public function apply(Builder $builder, Model $model)
    {
        $builder->whereNull($model->getQualifiedDeletedAtColumn());
    }
```
Instead of only checking for `null` value, we could add another check if `now()` is less than the `deletedAt` value. Calling `Model::delete()` should still be as it is. We could also add a method `SoftDeletes::scheduleDelete($date)`.

I also believe that this should be the expected behaviour and use of that column.

I could make a PR if this idea gets accepted.

**Comment by themsaid** [comment]
It's very opinionated, feel free to do that in your own app.
