### ISSUE TITLE
Suggestion for validation messages of `gte` and `lte` rules

### ISSUE THREAD

**Issue by vHeemstra** [laravel/ideas#2259]
* Laravel Version: 7.12.0

Just a small suggestion :)

**Current situation**
In the validation messages for the `gte` and `lte` rules, the text contains "must be ... than or equal :value.". This produces a message like:
`The field must be greater than or equal other field.`
This sounds a little off...

**Suggestion**
I would replace "equal" with "equal to" in these two rules and their variations.
(As is the case for the dates variations, e.g. `before_or_equal`.)

Of course this is easily done on ones own version, but maybe it's a nicer default?

**Comment by themsaid** [comment]
No plans for this at the moment.
