### ISSUE TITLE
Add `required` method to Request object

### ISSUE THREAD

**Issue by omitobi** [laravel/ideas#2260]
`required` validation rule is the most popular rule that I have seen and this is used often by developers. This feature adds a new `required` method to `Request` object as a shorthand to "validate" and return required fields.

```php
$request->required(['user_id', 'email']) //returns ['user_id' => 1, 'email' => 'abc@example.com']
```
The above snippet validates both `user_id` and `email` and return an array that is similar to `validated()` method of `FormRequest` object.

The benefit is that for a little validation that only requires `required` rule without creating a Form request or writing custom validation.

**Comment by themsaid** [comment]
No plans for this at the moment.
