### ISSUE TITLE
Official support for MongoDB (not as a MySQL replacement)

### ISSUE THREAD

**Issue by elfeffe** [laravel/ideas#2262]
MongoDB is great for a lot of cases, I’m using https://github.com/jenssegers/laravel-mongodb on production for some years, and this is great for some projects (ecommerce, machine learning, statistics).
But that project is not as updated as it should be, that stops me to use MongoDB and then Laravel.
Laravel is a latest technology software, it should support MongoDB in my point of view.
When you deal with nested attributes there is nothing like MongoDB, EAV is really a bad idea in modern systems, and you need that in a lot of cases.

**Comment by mfn** [comment]
You're not the first to suggest this => https://github.com/laravel/ideas/issues?q=is%3Aissue+MongoDB

I can only quote:
> Be the change that you wish to see in the world

Maybe you can find others to:
- convince the Laravel project to include it or
- step up and contribute to the package to bring it up2date

**Comment by elfeffe** [comment]
>     * convince the Laravel project to include it or

Yes, this is the reason why I add it to this repository. If Taylor wants us to share ideas here, I share mine.
Unfortunately, I have to time to collaborate with this, I don't even have the knowledge. That's why I collaborate buying things from Laravel's ecosystem, that's the way the people from the team get paid.

I really think MongoDB will give Laravel the extra that it needs. I see Laravel sponsors Livewire, I don't see the reason why they can't do the same with MongoDB project.

You should be not complaining to people that ask for extra features on Open Source projects saying "Yeah, if you want it you have to do it by yourself", and understand that I'm not saying this on Laravel repository, I say it on Laravel Ideas repository, and this is the reason why this repository exists.

This is great that I'm not the first to suggest that, maybe it is time to hear me and the rest of the people.

Now that I see you have free time, you can go to the rest of the "ideas" here and say "this is Open Source, go and make it by yourself".

**Comment by mfn** [comment]
> You should be not complaining to people that ask for extra features

Wasn't my intention, but given the duplicates at _looked_ like low effort on your part as we already have issues for this and joining seemed more appropriate to me. No ill intention was meant here, I absolutely assumed best intentions on your part!

**Comment by elfeffe** [comment]
@mfn no problem.
In any case, I say "not a a MysQl replacement". it will be impossible to convince Taylor to offer full support for MongoDB.
But at least give a help to the actual extension.
MongoDB is great for some use cases, I have been working almost 20 years on ecommerce, and in large systems MySql is always a pain compared with what MongoDB offers out the box.

**Comment by LIQRGV** [comment]
Laravel's eloquent revolving around single RDBMS,
so I think it's not easy and small change on laravel part.
Maybe even the interface and API call changes too.
This idea is good, so let community vote for it to see if it's worth.

**Comment by themsaid** [comment]
No plans for this at the moment.
