### ISSUE TITLE
Add `splatPipe` method to Illuminate\Support\Collection

### ISSUE THREAD

**Issue by omitobi** [laravel/ideas#2263]
#### Intro
In Laravel 5.4 [`pipe` method was added to the list of methods](https://laravel.com/docs/5.4/collections#method-pipe) in `Illuminate\Support\Collection` class which helps to pipe a resulting collection into a closure and modify the result.
[Freek explained a good use case](https://freek.dev/477-the-pipe-collection-macro) of this method before it was finally added to Collection class.

### The method
Now, this new `splatPipe` method would help help to peep into the collection and split the items in a collection as argument lists of a the closure passed into this method like so:

```php
collect([1, 2])->map(function ($num) {
    return (string)$num;
})->splatPipe(function ($data1, $data2) {
    if (is_int($data1)) {
        return [$data1];
    }
    return [$data1, $data2];
});
```

`$data1`, represents the value first item in the collection, and `$data2`. 

The above looks cleaner instead of:

```php
collect([1, 2])->map(function ($num) {
    return (string)$num;
})->pipe(function($collection) {
   if(is_int($collection->first())) {
     return [$data1]
   }

   return [$collection->first(), $collection[1]]
});
```

#### Implementation possibility
The simplest way is depicted with this macro:

```php
Collection::macro('splatPipe', function ($callback) {
    return $callback(...$this->items);
});
```

#### Other consideration
1. To limit the number of unneeded arguments passed through to the closure, for a huge number of items in a collection, Reflection may be employed e.g [to get argument count](https://stackoverflow.com/a/15257952/5704410) before spreading the values to the callback and it may look like so:

```php
Collection::macro('splatPipe', function ($callback) {

    $reflected = new \ReflectionFunction($callback);

    return $callback(...$this->take($reflected->getNumberOfParameters())->all());
})
```

#### Possible concern
2. Some times there are associative array, how do I get the values and the keys?
> This is open for discussion.

#### Future updates
What if I want to skip some item index in the collection as PHP `list` function would behave?

```php
[,$num2,,$num4] = [1,2,3,4];
```
To use `splatPipe` like so:

```php
collect([1, 2, 3])->map(function ($num) {
    return (string)$num;
})->splatPipe(function ($data1, , $data3) {
    if (is_int($data1)) {
        return [$data1];
    }
    return [$data1, $data2];
});
```
> This is more of PHP capability than something to implement. Hopefully, future PHP version will enable this possibility. This is open for discussion also.

**Comment by themsaid** [comment]
Feel free to open a PR
