### ISSUE TITLE
Add a "smart" relation count

### ISSUE THREAD

**Issue by tontonsb** [laravel/ideas#2265]
Quite often I find myself checking the relation count, e.g.

```
public function getDeletableAttribute()
{
    return !$this->children->count();
}
```

But this approach is not always optimal as to how it gets the count. I might be loading a list where I could ideally just load it `withCount`. Or maybe I don't need the relation loaded and I would only do `children()->count()`. In an ideal non lazy world the method would be something this:

```
public function getDeletableAttribute()
{
    if (array_key_exists('children_count', $this->attributes))
        return !$this->children_count;

    if ($this->relationLoaded('children'))
        return !$this->children->count();

    return !$this->children()->count();
}
```

What would you think about a method that would do all of these checks under the hood? Maybe something like `$model->children()->getCount()`?

**Comment by azakhozhy** [comment]
Good idea, I'm tired of writing special counters for relations in my models.

**Comment by tontonsb** [comment]
Made a PR: laravel/framework#33300
