### ISSUE TITLE
Use the symfony mechanism for managing env files

### ISSUE THREAD

**Issue by kcassam** [laravel/ideas#2269]
The mechanism described here is more flexible/smart : https://symfony.com/doc/current/configuration.html#overriding-environment-values-via-env-local

Well explained here : https://symfony.com/blog/improvements-to-the-handling-of-env-files-for-all-symfony-versions
and here : https://symfony.com/blog/new-in-symfony-4-2-define-env-vars-per-environment

Each env variable is managed at the right place.

This mechanism mimics the behavior of Create React App, Rails' DotEnv and probably some other libs (https://github.com/symfony/symfony/pull/28533)

**Comment by themsaid** [comment]
No plans for this at the moment.
