### ISSUE TITLE
Bind and hide parent model to the relation

### ISSUE THREAD

**Issue by tontonsb** [laravel/ideas#2272]
I am quite often in the need of the parent model of the relation.

I.e.
```
$users = User::with('posts.user')->get();
```

However, this leads to double loading. If I am not lazy, I might do

```
$users = User::with('posts')->get();

foreach ($users as $user)
    foreach ($user->posts as $post)
        $post->setRelation('user', $user);  // or simply $post->user = $user
```

However, I have now set up myself for a serialization loop as soon as I do `return $users;`. So I had to not only `setRelation` but also `makeHidden`.

What I would propose is the following feature on relations:

```
// User model

public function posts()
{
    $this->hasMany(Post::class)->withSelfAs('user');
}
```

that would bind the `user` model to each of the posts and make it `hidden` from serialization.

**Comment by themsaid** [comment]
No plans for this at the moment.
