### ISSUE TITLE
[Proposal] Split Timestamps Activation

### ISSUE THREAD

**Issue by procd92** [laravel/ideas#2276]
I would like to suggest the following solution, to allow developers to use only `created_at` or `created_at` and `updated_at`.

The current Laravel `Model` uses `HasTimestamps` traits that touch timestamps when saving and updating a model. And you can only disable them both or activate them both, and not one.

```php
public $timestamps = false;
```

My suggestion is to add a new property that only enables and disables `updated_at`, for example:

```php
public $updatedAtTimestamp = true;
```

and `$timestamp` still disable them both in case of `false` to preserve backward-compatibility. And for migrations, we could have two new methods:

```php
public function createdAtTimestamp($precision = 0)
{
    $this->timestamp('created_at', $precision)->nullable();
}

public function updatedAtTimestamp($precision = 0)
{
    $this->timestamp('updated_at', $precision)->nullable();
}

public function timestamps($precision = 0)
{
    $this->createdAtTimestamp(precision);

    $this->updatedAtTimestamp(precision);
}
```

My reasoning for this is that I have a lot of models that are never updated, so there is no need for an `updated_at` timestamp, I know I could just use the following:

```php
$table->timestamp('created_at')->useCurrent();
```

and in my model:

```php
public $timestamps = false;

public $dates = ['created_at'];
```

But in this case, the database is setting the timestamp for me and not the application, which could cause a conflict in the timezone if it is set incorrectly. So I need my application as the only source of truth.

I am willing to implement this feature if it approved by you guys. Thank you for reading.

**Comment by mfn** [comment]
Doesn't this solve your problem?
```php
    public function getUpdatedAtColumn(): ?string
    {
        return null;
    }
```
This is e.g. used in `\Illuminate\Database\Eloquent\Concerns\HasTimestamps::updateTimestamps` to make this work.

**Comment by procd92** [comment]
Yep, but I was hoping to streamline the process

**Comment by procd92** [comment]
Thank you @mfn

**Comment by mfn** [comment]
Maybe it doesn't need a technical solution (I'm not seeing the current code handling all this is complex, but your suggestion would add yet-another-way to achieve what's already possible) but some clarity in the docs. I don't remember how I found out; probably just by reading Laravels source 😬

**Comment by procd92** [comment]
Agree
