### ISSUE TITLE
[Proposal] Route::redirectAll() to redirect an array of routes

### ISSUE THREAD

**Issue by alexpgates** [laravel/ideas#2277]
I'd like to be able to provide an array of routes to redirect to a single route.

**Before:**
```
Route::redirect('contact_us', 'contact');
Route::redirect('contact-us', 'contact');
Route::redirect('contactus', 'contact');
Route::view('contact', 'content.contact');
```

**After:**

```
Route::redirectAll(['contact_us', 'contact-us', 'contactus'], 'contact');
Route::view('contact', 'content.contact');
```

Here's a commit that does this:

https://github.com/alexpgates/framework/commit/154aa91d5efde28062cb379eb65fabf69ff50a88

Instead of returning the defined route, this approach returns an array of defined routes. 

I'm not sure of the performance impact, and the test included in the commit is incomplete. But I'd love some feedback - if this is useful, I can polish things up a bit and submit a PR.

**Comment by themsaid** [comment]
Feel free to open a PR
