### ISSUE TITLE
[Proposal] route() helper to auto add current locale as first parameter

### ISSUE THREAD

**Issue by aneeskhan47** [laravel/ideas#2279]
guys don't you think route() helper should auto add first parameter current locale

i mean if you have a locale middleware which auto add current locale like if you visit users/1 the middleware will redirect you to en/users/1

now if you use route() helper and use `route('users', ['1'])` it will throw exception 

`Missing required parameters for [Route: users] [URI: {locale}/users/{id}].`

now if you use laravel auth (forget pass etc) they all uses route() helper so if you visit password reset link it throw missing required params exception

thats why my proposal is modify route() helper to always add first param current locale and other params after it

currently i'm using my own helper locale_route() to achieve this

```
if (! function_exists('locale_route')) {
    /**
     * Generate the URL to a named route.
     *
     * @param  array|string  $name
     * @param  mixed  $parameters
     * @param  bool  $absolute
     * @return string
     */
    function locale_route($name, $parameters = []  ,$absolute = true)
    {
        
        $parameters = Arr::prepend(Arr::wrap($parameters), current_lang());

        return route($name, $parameters, $absolute);
       

    }
}
```

but as i said it will be very nice to have laravel route() have this by default :)

**Comment by fletch3555** [comment]
Not everyone uses locale as the first param (or at all).

What you're looking for is already available and documented, albeit a slightly different approach: https://laravel.com/docs/7.x/urls#default-values

**Comment by aneeskhan47** [comment]
> Not everyone uses locale as the first param (or at all).
> 
> What you're looking for is already available and documented, albeit a slightly different approach: https://laravel.com/docs/7.x/urls#default-values

thanks that what i was looking for
