### ISSUE TITLE
Multiple Laravel sessions on the same browser

### ISSUE THREAD

**Issue by kishore032** [laravel/ideas#2280]
It seems like I can have only one session of a Laravel App running in a given browser. So, if Joe is logged into the app, any browser instance he opens shows the same instance of the application. 

Is it possible to have multiple users log into the same browser but maintain their own sessions? Like Gmail does. 

I assume this will require session cookies that are signed with the application key as well as a user key.

**Comment by lk77** [comment]
Hello,

it's not possible, browsers do not support this.

**Comment by kishore032** [comment]
Indeed, that's exactly what I am requesting.  The browser runs a session for an application/domain and doesn't know about users. But the backend can maintain multiple user sessions (with their own states) on the same browser - say with different session cookies - and let the user switch accounts. Or even lock one account when the other is being used, but maintain state.

This is very helpful not just for testing, but in many situations where the same user has different accounts and different roles.

**Comment by ProjektGopher** [comment]
I've run into a situation where this functionality would be super useful as well. A retailer has a browser window open to your app, but each sales person has a different account. I want a quick way to switch accounts through a dropdown, or to be able to have a separate browser tab open for each sales person.
