### ISSUE TITLE
Add eloquent model default ordering column and direction.

### ISSUE THREAD

**Issue by stephenjude** [laravel/ideas#2281]
I was thinking it would be nice to add a default eloquent model properties for applying default order to eloquent query.

Here is an example

![carbon (2)](https://user-images.githubusercontent.com/31182887/86268561-468d4600-bbc0-11ea-8efb-d995e654a88f.png)

**Comment by stephenjude** [comment]
I decided to put a package around it. Check it out [https://github.com/stephenjude/default-model-sorting](https://github.com/stephenjude/default-model-sorting)

**Comment by ronnyandre** [comment]
You shouldn't close even if you made a package. This is a great idea.

**Comment by stephenjude** [comment]
Thanks for checking it out.
