### ISSUE TITLE
Typed Collections

### ISSUE THREAD

**Issue by tpaksu** [laravel/ideas#2282]
Hello all, 

I thought that having a typed collection class would be beneficial for some who need all their items to be the same type in a collection. So what I've thought can be achieved in multiple ways:

#### 1. 
```php 
$typedColl = collect([])->ofType(\NS\Object);
$typedColl->push(new \NS\Object()); // pass
$typedColl->push(new \NS\AnotherObject()); // throw
```

#### 2. 
```php 
// in \NS\Object
use Collectible;
// in another document
$typedColl = \NS\Object::collect([]);
$typedColl->push(new \NS\Object()); // pass
$typedColl->push(new \NS\AnotherObject()); // throw
```

What do you think?

**Comment by tpaksu** [comment]
Seems like it's been proposed [here](https://github.com/laravel/ideas/issues/529) but closed. Didn't understand why.

**Comment by themsaid** [comment]
Feel free to open a PR
