### ISSUE TITLE
MySQL unique constraints with soft deleting

### ISSUE THREAD

**Issue by vibar** [laravel/ideas#2285]
I read many articles and questions related to Laravel [soft deleting](https://laravel.com/docs/7.x/eloquent#soft-deleting) feature.

In request validation:

```
$id = $this->post->id ?? 'NULL';

return [
     'name' => "unique:posts,name,{$id},id,deleted_at,NULL",
];
```

At application level, this works fine with desired validation.

My migration is something like this:

```
Schema::table('posts', function (Blueprint $table) {
     ...
     $table->softDeletes();
     $table->unique(['name', 'deleted_at']);
});
```
MySQL allows multiples rows with `deleted_at` null. This is the problem.

If I use soft deleting, I cannot add unique constraint to MySQL?

Someone has the same problem? Any ideas to solve this?

I have considered to change the default value of `deleted_at` to '0000-00-00 00:00:00' or anything different from `null` but this is very ugly and have a big impact.

Other solution is to create an extra `boolean` column like `is_live` and setup this automatically with eloquent model events. The database problem will be solved with:
```
$table->unique(['name', 'is_live']);
```  

PS: I don't want to use "thashed" model scopes and pollute my application.

**Comment by mmollick** [comment]
I do this in my own applications frequently. My preferred method is to mutate the data contained within the "unique" column(s) when it's been deleted. In some cases overwriting the original value (destructive) and in others applying a prefix to the original value (non-destructive).

```
class UserObserver
{
    public function deleted(User $user)
    {
        // Destructive
        $user->name = uniqid();

        // Non-destructive
        $user->name = time() . '::' . $user->name;

        $user->save();
    }
}
```
