### ISSUE TITLE
Add support for constructor arguments of partial mocks

### ISSUE THREAD

**Issue by Zakini** [laravel/ideas#2287]
Mockery supports [passing constructor arguments to mocks](http://docs.mockery.io/en/latest/reference/creating_test_doubles.html#constructor-arguments). There's not much use for this with regular mocks, but this can be essential for partial mocks if the non-mocked methods depend on something passed into the constructor.

Maybe something like this could work, since it matches the signature of `Mockery::mock()`:
```php
$this->mock(A::class, [new B()], function ($mock) {
    // ...
});
```
That array would have to be optional of course, so that we don't break existing code. We could even resolve those dependencies via the service container as usual.

Is there any appetite for adding this?

**Comment by ragulka** [comment]
I just ran into this - was trying to create a partial mock for a service class that had constructor dependency injection. I only wanted to mock a single method of the class, but other methods on the class were called during the test - and those depended on the dependency, which was not injected.

```php
class MyService
{
    protected $repository;

    public function __construct(MyRepository $repository)
    {
        $this->repository = $repository;
    }

    public function thisWillBeMocked() {
       // I only wanted to mock this...
    }

    public function thisIsNotMockedButWillBeCalled() {
        // but this was also called during the test...
        $this->repository->doSomething();
    }
}

// test

$this->partialMock(MyService::class, function($mock) {
    $mock->shouldReceive('thisWillBeMocked')->with('some_argument')->once();
});

// ...some code here that calls both `thisWillBeMocked()` and `thisIsNotMockedButWillBeCalled` internally
```

This results in an error:

```
Call to a member function doSomething() on null
```

**Comment by themsaid** [comment]
Feel free to open a PR
