### ISSUE TITLE
CommonMark environment customisation

### ISSUE THREAD

**Issue by Zakini** [laravel/ideas#2288]
Following on from [#30973 in laravel/framework](https://github.com/laravel/framework/pull/30973), while I agree that swapping out the entire markdown parser/renderer might be a bit overkill, being able to customise the environment would be a nice feature to have. Specifically, [adding custom renderers](https://commonmark.thephpleague.com/1.5/customization/overview/#customize-html-output-with-custom-renderers) would be nice, so that you can stick to markdown but the final HTML matches a target design more easily.

**Comment by themsaid** [comment]
No plans for this at the moment.
