### ISSUE TITLE
Allow for setting pagination perPage automatically

### ISSUE THREAD

**Issue by Zakini** [laravel/ideas#2289]
The current page to be displayed when using pagination [gets set automatically](https://github.com/laravel/framework/blob/0b12ef19623c40e22eff91a4b48cb13b3b415b25/src/Illuminate/Pagination/PaginationServiceProvider.php#L40). Perhaps a similar thing could be done for `$perPage` with a matching `Pagination::perPageResolver()` function.

**Comment by themsaid** [comment]
Feel free to open a PR
