### ISSUE TITLE
Support using detach in combination with where

### ISSUE THREAD

**Issue by d-luk** [laravel/ideas#2290]
Imagine a situation where you have a model called `User` with a many-to-many relation to `Role`. A role has a `'type'` column which can be `'admin'`.

Now you do the following:

```php
$user->roles()->where('type', 'admin')->detach();
```

Anyone would expect this to only detach the role where the type is `'admin'`. Instead, all the roles are detached.

This behaviour it's highly counter-intuitive and misleading as the API provides a `where` method which is subsequently ignored. This is very prone to bugs.

**Suggested solution:** Do not discard the provided `where` when calling `detach`.

**Comment by themsaid** [comment]
No plans to add this.
