### ISSUE TITLE
Track applied local query scopes

### ISSUE THREAD

**Issue by mikaeljorhult** [laravel/ideas#2294]
I use local query scopes in a model to add a few sub queries to aggregate some values. These are then displayed in my Blade templates and used as conditionals to show certain parts of the UI.

This looks something like this (truncated and renamed for brevity)

```php
public function scopeWithFilterData(Builder $query)
{
    $query->addSelect(['sub_query_aggregate'] => ...
}
```

I also have a scope to use these aggregated values to filter the models. I check if the sub query has been added through the scope and otherwise add it to make the sub query aggregates available.

```php
public function scopeFilterData(Builder $query)
{
    $query->when($this->hasFilterDataScope($query), function ($query) {
            $query-> scopeWithFilterData();
        })
        ->havingRaw('sub_query_aggregate IS NULL');
}
```

I have however not found any nice way to check if the local scope has been applied already so the hasFilterDataScope method checks if the aggregate name is present in the Query Builder objects columns property.

```php
private function hasNeedsAttentionScope(Builder $query)
{
    $columns = $query->getQuery()->columns;

    return is_null($columns)
           || count(preg_grep('/sub_query_aggregate/', $columns)) === 0;
}
```

I would like to see the query builder to track the name of scope methods that has been applied to the query and a `hasLocalScope` or `hasAppliedScope` method. This would allow me to check if a scope has previously been applied by calling it with the name of the scope method, like `$query->hasLocalScope('scopeWithFilterData')`.

**Comment by themsaid** [comment]
Feel free to open a PR
