### ISSUE TITLE
What about adding official centrifugo support

### ISSUE THREAD

**Issue by adiletmaks** [laravel/ideas#2295]
Centrifugo is a free and scalable real-time messaging server that is language-independent. Now it is very popular, and is often used for real-time applications. It could replace pusher. It would be cool if we will add new driver for brodcasting.

**Comment by osbre** [comment]
Alternatives compatible with Pusher API :

https://github.com/edgurgel/poxa
https://github.com/tlaverdure/laravel-echo-server

**Comment by adiletmaks** [comment]
> Alternatives compatible with Pusher API :
> 
> https://github.com/edgurgel/poxa
> https://github.com/tlaverdure/laravel-echo-server

pusher is paid service

**Comment by happyDemon** [comment]
@adiletmaks he's listing opensource alternatives, there's also laravel-websocket.

They use the same api, so there's no need to tweak the any client/backend libraries.

**Comment by themsaid** [comment]
You can write this as a package.
