### ISSUE TITLE
Are there any plans to rewrite routing with PHP Attribute?

### ISSUE THREAD

**Issue by allowing** [laravel/ideas#2297]

**Comment by julienbourdeau** [comment]
It used to exists with docblocks annotations but he route files are a much better solution. I don't think Laravel will reintroduce this.

**Comment by wenpeng** [comment]
PHP Attribute is ugly, Really unrecommended.

**Comment by buismaarten** [comment]
https://github.com/spatie/laravel-route-attributes

**Comment by themsaid** [comment]
no plans for this
