### ISSUE TITLE
What about adding config support for notification channel?

### ISSUE THREAD

**Issue by zerist** [laravel/ideas#2300]
### Reason
I wanted to use email notifications，but I dont know how Laravel render it, where is the mail view, what is the channel in functin via(). So I inspected source code, then I find something puzzling. 

### In Source Code
In default Model User, it use Notifiable trait, function notify() in it. Then make \Illuminate\Notifications\ChannelManager(extends Manager) instance , get MailChannel by function createDriver().
`$method = 'create'.Str::studly($driver).'Driver';
            if (method_exists($this, $method)) {
                return $this->$method();
 }`
the param $driver return by  Nofitication class, functin via().
e.g. in via().
`public function via($notifiable)
    {
        return [ 'mail'];
    }` 
will get 'createMailDriver', in ChannelManager class, return MailChannel.
### Question
So what about adding config file support for notification channel?
Then we can extend a channel more convenient, and easier to config channel's view tpl.

**Comment by zerist** [comment]
Indeed, I just think function create****Driver() unelegant.

**Comment by mfn** [comment]
That's how most of the "drivers" can be extended in Laravel, it's not unique to the notifications.

Config would be possible but creating a driver often is specialized and may need other resources not simply "configurable" so having the `create*Driver` way is the approach with the most freedom.

**Comment by zerist** [comment]
Thanks for answering, I understand you idea.

**Comment by zerist** [comment]
But, so many channel in Laravel, hao can I know them more? Too little info about channels in Laravel doc, I just know that it can work but dont know why.
