### ISSUE TITLE
Improve error message for failed jobs

### ISSUE THREAD

**Issue by wturrell** [laravel/ideas#2305]
Currently, a generic error is logged when a job on a queue fails:

> local.ERROR: App\Jobs\Foo has been attempted too many times or run too long. The job may have previously timed out.

It would save significant debugging time if the message stated *which* of these reasons it was.

When [maxAttemptsExceededException](https://github.com/laravel/framework/blob/6121a522c1830542f0b1783847894e48d7187c54/src/Illuminate/Queue/Worker.php#L646) is thrown, could a reason also be passed?

**Comment by themsaid** [comment]
Here are the possible reasons: https://divinglaravel.com/job-has-been-attempted-too-many-times-or-run-too-long
