### ISSUE TITLE
suggestion for validation default fields

### ISSUE THREAD

**Issue by mooseh** [laravel/ideas#2307]
I think it would be absolutely amazing if we could have a default value in the validation system something like the following

`
$request->validate([
 "eat_icecream" => "boolean|optional:true"
])
`
Or

`
$request->validate([
 "eat_icecream" => "boolean|default:true"
])
`

I feel this would be incredible for cleaning up code and giving a quick and neat way of adding default values.

**Comment by wenpeng** [comment]
Don't agree that, I think what you need is a "sanitizer" but not a "validator".

**Comment by mooseh** [comment]
> Don't agree that, I think what you need is a "sanitizer" but not a "validator".

why could you not have both in one? it makes a lot of sense.

**Comment by wenpeng** [comment]
> > Don't agree that, I think what you need is a "sanitizer" but not a "validator".
> 
> 
> 
> why could you not have both in one? it makes a lot of sense.

Maybe "KISS(Keep It Simple, Stupid) is more better, don't make a package too heavy, should know that not everyone have that senses, you can create your own validators by extend the Validation class in your projects.
