### ISSUE TITLE
[Proposal] Allow descending indexes in migrations

### ISSUE THREAD

**Issue by LiddleDev** [laravel/ideas#2314]
I think it should be possible to specify the order of the indexes.

At the moment I must do something like

`DB::statement('ALTER TABLE table ADD INDEX index_name (column1 ASC, column2 DESC)');`

I propose that we are given the option to to pass the order like this

`$table->index(['column1', ['column2', 'DESC]]);`

**Comment by themsaid** [comment]
Feel free to open a PR
