### ISSUE TITLE
[Proposal] enable 'many' on Cache facade

### ISSUE THREAD

**Issue by Norgul** [laravel/ideas#2318]
I think it is rather inconvenient that the Cache facade (and further down the line `Illuminate\Contracts\Cache\Repository`) doesn't have `many` and `putMany` functions by default. 

I would like to optimize the code in my package to the maximum extent, but I'm afraid it will break if I use `Cache::many()` and whoever uses the package decides not to use i.e. Redis driver, but a driver without method implemented.

**Comment by mfn** [comment]
I haven't tried it, but the contract implements `\Psr\SimpleCache\CacheInterface` which requires to implement `getMultiple` and `setMultiple`; can you call them maybe?

**Comment by Norgul** [comment]
Digging deeper, it looks like all drivers in one way or another implement the method. It just isn't listed in the Facade. So I suppose nothing will break. Closing the issue
