### ISSUE TITLE
[Proposal] Bulk insert/update/upsert DB records

### ISSUE THREAD

**Issue by paras-malhotra** [laravel/ideas#2329]
This has been suggested multiple times (https://github.com/laravel/framework/issues/1295, https://github.com/laravel/ideas/issues/1413) and turned down but I'd like to do a better job at articulating the feature requirements this time!

**Why do we need this?**
- More efficient queries for bulk insert/update (one query vs multiple queries)
- Take care of bulk insert logic (e.g. handling insertion of duplicate records - skip conflict, raise exception, update duplicate)
- Upsert functionality (update or insert) in a more efficient / bulk manner than current implementation of `firstOrCreate` that only works for a single upsert

**Exclusions**
- Inserting timestamps
- Triggering events

I think the previous issues focussed on either inserting timestamps or triggering events. I propose not to implement these 2 features (triggering events for each insert/update would be too cumbersome for a bulk operation and timestamps can be handled differently without hydration of the models / PHP logic ). Instead, I propose to provide an easy way to efficiently insert/update/upsert bulk records in Laravel.

**Comment by paras-malhotra** [comment]
Implemented: https://laravel.com/docs/8.x/queries#inserts

**Comment by xorock** [comment]
BTW. Is it also possible to create the upsertMany method for related models?

`$post->comments()->upsertMany()`
