### ISSUE TITLE
Laravel Services: A better way for communicating with APIs

### ISSUE THREAD

**Issue by alexander-schreiner** [laravel/ideas#2332]
Laravel is the best PHP Framework for building Monolithic applications. As projects grow, developers will be finding themself refactoring & rewriting old applications. Many companies opt to split up a big monolith into smaller microservices.

I was personally in this situation and working with Laravel got me thinking. Isn't there a better way for setting up the the API calls to these new microservices than 'just' the HTTP facade? How about a new component which deals with this problem.

**How about isolated classes for a external service interaction via http.** 

Let me explain by example. Lets say there is a service developed by your company which creates thumbnails of websites, you give it a url, it gives you a screenshot of the page. Now this service returns a 1d JSON array with the following data:

```
{
	"success": true|false,
	"error": string|null,
	"screenshot_url": string|null
}
```

Now you implemented the call to this service in your application via the Http Facade. Sometimes things go wrong and the thumbnail service doesn't return a screenshot_url, but a error message instead. Now you have to figure out via the error message what went wrong. As you can image, this can get messy the more possible error messages there are. Next problem: How do you go on handling a error/exception in the external thumbnail service? Wouldn't it be cool if you could map certain errors in the API, to certain exceptions in your main application? Like so:

```
{
	"success": false,
	"error": "parameter_url_required",
	"screenshot_url": null
}
```

Would for example throw a _RequiredParameterMissing_ Exception and the mapping happens in your service class. So now let say you got a Thumbnail Service Class and now you want a thumbnail for a certain URL. You call the Thumbnail Service like so:

```
use App\Http\Services\Thumbnail;

// Everything works
$response = Thumbnail::get('https://laravel.com/');
dd($response->screenshotURL);

// Something failed
try {
	$response = Thumbnail::get('laravel.com');
} catch (ParameterURLNoURL $e) {
	dd('Parameter url is no url');
} catch (Exception $e) {
	dd('Unknown error');
}
```

I think the concept of what i am thinking of should now be clear. What the service classes itself should look like isn't clear to me yet. But here are some bullet points:

- Multiple methods for each http verb
- Mapping of errors in the external API to 'local' Exceptions ('parameter_url_required' => RequiredParameterMissing Exception)
- Mapping of the response statuscodes to local Exceptions
- Chaining HTTP Clients methods to Service Class Methods:
```
use App\Http\Services\Thumbnail;
Thumbnail::timeout(10)->get('https://laravel.com/');
/*
(...)
*/
// In this part of the application I can't afford to wait up to 10 seconds
Thumbnail::timeout(3)->get('https://laravel.com/');
```
- (...)

Let me know what you think. Feedback appreciated

**Comment by fletch3555** [comment]
Sounds a whole lot like business logic, not something the framework needs to be concerned with... Unless of course I've misunderstood your post in some way.

**Comment by codegefluester** [comment]
Agree with @fletch3555 here. Form the description you provided this sounds like a problem that a composer package/simple class can already solve today. 

What I'm unclear about is what value Laravel, or any other framework for that matter, would add to the process. If you take Laravel out of the equation, what would change about the situation you're finding yourself in right now?

**Comment by alexander-schreiner** [comment]
@fletch3555 @codegefluester Thanks for your Feedback. After thinking about it for a while i agree with your statements. This should probably be a library and not a part of Laravel. I'll be making this my first library. I am closing this issue since. https://github.com/alexander-schreiner/laravel-services
