### ISSUE TITLE
schedule:listen command to register cron locally

### ISSUE THREAD

**Issue by dillingham** [laravel/ideas#2338]
In trying to figure out how to cron schedule:run locally, I realize it could use some laravel fairy dusk.
Like some really smart coder could figure a way I (an average coder) doesn't need to figure this out :)

Would be cool if schedule:listen acted the same as queue:listen

Even if it just simulated it like:
```
while :
    do
        php artisan schedule:run
        sleep 60
    done
```

**Comment by fletch3555** [comment]
Any reason you can't just add a crontab entry to your system like [mentioned in the docs](https://laravel.com/docs/8.x/scheduling#introduction)?

**Comment by dillingham** [comment]
@fletch3555  I've never worked with `crontab`. Im sure Im not alone.
The `idea` of this post was to suggest a simple way of testing locally.
Im guessing if you add an entry to crontab it runs indefinitely? 
So maybe the `reason` here might be to test it while the command is active.. similar to `queue:listen`

**Comment by fletch3555** [comment]
No worries. I didn't mean for my comment to be argumentative, so apologies if it came across that way.

Cron is the standard mechanism for scheduling tasks in a *nix environment (sorry windows people...), and crontab is the name for the file holding the cron definitions.

For windows, you would have to use the Windows Task Scheduler (which is a nightmare and a half for most people).

I agree this may be somewhat excessive for local development, since these tasks would be "forever".

Having said that, Laravel Horizon would definitely meet this need as well, and I believe does include a command that will function like what you're describing

**Comment by dillingham** [comment]
@fletch3555 no no it was a valid question, it kinda forced me to explore my "why" more.

In doing so, we can add windows users to the beneficiaries of such a console command haha.

Yeah I just wanted an easy way to see the kernel schedules in action for like 10 minutes

```php
$schedule->job(new ActionStats)->everyMinute();
```

I didn't know horizon ran the schedules too, interesting.. will look into that thanks!

Also thanks for the explanation.. Im going to try and get familiar with this file you speak of :)

**Comment by fletch3555** [comment]
I may have misspoke.  Been a while since I've looked at Horizon.  Looking again, I'm pretty sure it's just for queues. So that idea can be discarded.

**Comment by dillingham** [comment]
Here's what Im using, seems to work as exected:

```php
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Artisan;

class ScheduleListen extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'schedule:listen';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Listen for scheduled tasks';

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle()
    {
        $this->line('Listening for scheduled tasks..');

        while (true) {
            if(now()->startOfMinute()->is(now())) {
                Artisan::call('schedule:run');
                $output = Artisan::output();
                if($output != 'No scheduled commands are ready to run.') {
                    $this->line($output);
                }
            }

            sleep(1);
        }
    }
}
```

**Comment by hivokas** [comment]
@dillingham now it is part of the core https://github.com/laravel/framework/pull/34618

**Comment by dillingham** [comment]
@hivokas thats awesome! Thanks so much for doing that :)
