### ISSUE TITLE
Slight error in Laravel.com documentation

### ISSUE THREAD

**Issue by brada1703** [laravel/ideas#2374]
Hey guys,

I just wanted to correct a slight error in the documentation.

On this page: https://laravel.com/docs/8.x/artisan#writing-output, under `You may use the newLine method to display a blank line` 

It states:

```
$this->newLine();

// Write three blank lines...
$this->newLine(3);
```

Note that this will result in a BadMethodCallException.

It should state, instead:

```
$this->output->newLine();

// Write three blank lines...
$this->output->newLine(3);
```

This gives you the correct behaviour. 

Thanks :)

**Comment by ahinkle** [comment]
Hey there,

Not an error -- that feature hasn't been released yet. Check back tomorrow on the next Laravel release. https://github.com/laravel/framework/pull/34754

**Comment by brada1703** [comment]
Thanks Andy!
