### ISSUE TITLE
Pause a specific Queue if

### ISSUE THREAD

**Issue by base64bits** [laravel/ideas#2391]
I’m not sure how much of a need this is, but when interacting with a shaky API that is down it will be nice to have an option to pause a specific queue based on some conditional and restart the queue once the API is up and running again.

Here is the use case:
Say I dispatch x number of jobs to a named queue, the workers start to process and part of the job is getting a token and sending a payload, if either one of those interactions with the API fail then I will like to update a JSON file that servers as a signal for other uses and pauses that named queue, I also have a schedule that runs every x minutes to check the API status and once the API is back up then the named queue will be restarted.

Of course new jobs will be piling up while the queue is paused, but they will get handled once the API is back up.

This will help with a few things:

1. Not increase the count of retry

2. Not use resources knowing that is useless to try to connect to an API that’s down

**Comment by paras-malhotra** [comment]
There's a few things you could do here:
1. Stop the queue worker (or supervisor) and start back after the API service is up. This would work only if you're dispatching all the API specific jobs to a dedicated queue and also the worker is dedicated for that queue alone.
2. Implement a job middleware on the circuit breaker pattern and include it in all jobs that hit unstable APIs

**Comment by base64bits** [comment]
Thanks for the tips

1. Will work since this is a specific queue however I am not sure if stopping supervisor will also stop all other queues

2. Sounds like a better way, I will need to learn about job middleware, once I figure it out I will comeback here and post how I did it.

**Comment by paras-malhotra** [comment]
@base64bits if you have multiple Supervisor "programs" for different queues, you can just do `sudo supervisorctl stop program-name:*` and this would only stop the queue workers for the specific queue.

**Comment by base64bits** [comment]
> @base64bits if you have a Supervisor "program" for each queue, you can just do `sudo supervisorctl stop program-name:*` and this would only stop the queue workers for the specific queue.

I don't have separate Supervisor for each queue and quite frankly I thing adding non PHP code for something like this is overkill, Im sure there is a better way or there should be a better way.

**Comment by paras-malhotra** [comment]
Yep, the best way is the circuit breaker middleware!

**Comment by mfn** [comment]
Also, when using horizon you only have one main supervisor so this could not work there.

**Comment by paras-malhotra** [comment]
@mfn, a few days ago, I PR'ed a way to pause/continue specific supervisors and not just the main supervisor: https://github.com/laravel/horizon/pull/914

**Comment by base64bits** [comment]
Thanks a lot @paras-malhotra this is awesome! I posted this question in laracast, I will link that to here in case someone else has a need for it.
