### ISSUE TITLE
Adding ability to schedule and un-schedule models without cron job.

### ISSUE THREAD

**Issue by neelkanthk** [laravel/ideas#2435]
Creating this issue for the Discord discussion: https://discordapp.com/channels/297040613688475649/486650494790402061/785225715222052874

Hi @taylorotwell  , @nunomaduro , @themsaid , @JeffreyWay, @jbrooksuk, @mattstauffer, @GrahamCampbell, @driesvints     and other Laravel core developers and maintainers,

A couple of months ago I developed Laravel Schedulable (https://github.com/neelkanthk/laravel-schedulable) A package for adding feature of scheduling and un-scheduling models without cron jobs.

**A little background:** 
Currently in any project if there is a requirement of fetching a particular model on a particular future date and time then the created_at column needs to be filled with a future datetime and then in DB queries a "whereDate()" is to be used to filter out the results. Although this works perfectly fine but it violates the basic definition of "created_at". 

created_at must only contain the date-time when the model was actually created. It should not be containing any other date-time. Further this gives rise to another question : What datetime to be updated in created_at column if we want to un-schedule that model?

In my opinion if the feature provided by https://github.com/neelkanthk/laravel-schedulable can be added in the core itself then it can prove to be very useful for developers because it adds a separate column "scheduled_at" and makes use of scopes to hook into the default model queries. Further this package also provides dedicated model events which can be used in Observer to hook into the scheduling and un-scheduling process.

Do you think that this feature can become a part of the core framework? 

I would be happy to contribute to the open source community and create a pull request for this feature if you think that this feature will add some value to the Laravel Framework.  :slight_smile:

Thanks and regards.
Neelkanth

**Comment by themsaid** [comment]
This seems like a pretty simple thing to do in your own application. I don't think it'll be added to the core.
