### ISSUE TITLE
Add toSqlWithBindings()

### ISSUE THREAD

**Issue by zarpelon** [laravel/ideas#2450]
Hey Sirs,

Today to debug a query and your bindings, we need to write:

`dd($query->toSql(), $query->getBindings());`

Is there a way to create specific method that your output is the SQL + bindings? Like $query->toSqlWithBindings()

Make sense?

**Comment by crynobone** [comment]
https://github.com/laravel/framework/blob/8.x/src/Illuminate/Database/Query/Builder.php#L3277-L3287

**Comment by zarpelon** [comment]
Tks @crynobone
