### ISSUE TITLE
Relation::upsertMany() method

### ISSUE THREAD

**Issue by tarraq** [laravel/ideas#2473]
In my current project I have nightly jobs fetching data from external API's.
Occationally there's a hiccup and I need to re-import. 

Now I collect lines in a Collection and do `$model->orderLines()->saveMany($collection);`.

However it would be great to be able to do `$model->orderLines()->upsertMany($collection);`, making sure I don't get duplicates and also won't have to delete everything from that day already.

Implementation-wise I would guess it would be fairly simple, using existing upsert functionality, injecting the relation ID as a hidden uniqueness key.

**Comment by mc0de** [comment]
@tarraq this allready exist

```php
public function updateOrCreate(array $attributes, array $values = [])
{
    return tap($this->firstOrNew($attributes), function ($instance) use ($values) {
        $instance->fill($values)->save();
    });
}
```

just do
```php
Model::updateOrCreate(['id' => $id], $data);
```
