### ISSUE TITLE
Callback in routes does not support object method callable type

### ISSUE THREAD

**Issue by maduranma** [laravel/ideas#2481]
I opened this issue: https://github.com/laravel/framework/issues/36079

It is not supported, adding support would be perfect as it's essential for some programming paradigms.

### Description:
In the routing, you cannot pass a callable array formed by an object and a string (function name), even this is a supported callable.

PHP manual: [https://www.php.net/manual/en/language.types.callable.php](https://www.php.net/manual/en/language.types.callable.php) (type 3)

You can try it like this:
```php
class foo
{
    public function bar()
    {
        echo 'This is a test';
    }
}

$callback = [new foo, 'bar'];
$callback(); // It echoes "This is a test"
```

### Steps To Reproduce:
In the routes file:
```php
class foo {
    public function bar() {
        echo 'This is a test';
    }
}
Route::get(
    '/test',
    [new foo, 'bar']
);
```

This throws an error in ```Illuminate\Routing\RouteAction``` as in line ```34``` it tries to convert the object to a string when concatenating for ```uses``` and ```controller``` in return array.

**Comment by themsaid** [comment]
Feel free to open a PR with your suggested changes.
