### ISSUE TITLE
Opposite of helper array_dot()

### ISSUE THREAD

**Issue by adamgoose** [laravel/ideas#2488]
A helper like this would be great for those using a package like Sentry, for example.

**Comment by IfnotFr** [comment]
> Well that can easily be done :
> 
> ```
> $array = array();
> foreach ($arrayDot as $key => $value) {
>   array_set($array, $key, $value);
> }
> ```

This is still valid. But with `Arr::set` instead of `array_set` since Laravel 5.7.

```
use Illuminate\Support\Arr;

$array = [];
foreach ($arrayDot as $key => $value) {
    Arr::set($array, $key, $value);
}
```

But i would also love to see something like `Arr:undot();` available :)
