### ISSUE TITLE
Add parameter for confirmed validation rule - custom matching field name

### ISSUE THREAD

**Issue by mesiarm** [laravel/ideas#2517]
rule confirmed (https://laravel.com/docs/8.x/validation#rule-confirmed) should have alternative (maybe confirmed_field?) which would allow to use parameter like this: confirmed_field:password2 which means custom name of matching field instead of predefined {field}_confirmation.

**Comment by ahinkle** [comment]
Have you tried using the `same()` rule?

```php
request()->validate([
    'password' => 'required|string|min:6|max:255',
    'password2 => 'required|string|same:password',
])
```

**Comment by ahinkle** [comment]
Have you tried using the `same()` rule?

```php
request()->validate([
    'password'   => 'required|string|min:6|max:255',
    'password2' => 'required|string|same:password',
])
```

**Comment by mesiarm** [comment]
I didn´t know that, thank you.
