### ISSUE TITLE
Option to specify the Laravel version on installation (for easier installation automation)

### ISSUE THREAD

**Issue by palypster** [laravel/ideas#2518]
When installing Laravel using recommended Docker way:
https://laravel.com/docs/8.x/installation#getting-started-on-linux

it should be convenient to have an option to specify the Laravel version you would like to install, something like:
```
curl -s "https://laravel.build/example-app?version=8" | bash
```

I know there is a way to do it using Installation via composer:
https://laravel.com/docs/8.x/installation#installation-via-composer

but in this way you have no option to specify the docker-compose services you'd like to pre-generate.

Currently there is no easy option to automate the process of Laravel installation (imagine tools/packages built on top of Laravel).

**Comment by rs-sliske** [comment]
just save the script and make the changes you want to it before running rather than piping it directly to bash if you want to change how it works

**Comment by palypster** [comment]
You're right, thanks
