### ISSUE TITLE
Upgrade egulias/EmailValidator to 3.x

### ISSUE THREAD

**Issue by nasatome** [laravel/ideas#2535]
https://github.com/egulias/EmailValidator/releases/tag/3.1.0

This new version seems to be more "aggressive" with emails that previously marked  `"example@examp&"` as valid.

current version in composer.json:`"egulias/email-validator": "^2.1.10" `

**Comment by donnysim** [comment]
It is already updated in the `master` branch.

**Comment by nasatome** [comment]
Excellent, I didn't think to check master
