### ISSUE TITLE
Add code coverage to artisan test?

### ISSUE THREAD

**Issue by nessor** [laravel/ideas#2539]
Hi guys,

we're currently facing the challenge in our team to run our tests in a CI/CD pipeline in parallel including a code coverage.
Here it would be super handy and save a lot of effort if there was a command like 

```bash
php artisan test --parallel --coverage
```

which would perhaps internally just call [paratest's coverage](https://github.com/paratestphp/paratest#generating-code-coverage)?

**Comment by rhzs** [comment]
This is good idea, i usually need to use another CLI to get the code's coverage. I'd be much better if we can integrate it with php artisan command.

**Comment by nessor** [comment]
Yes, exactly. You can then use the same command locally as well as in pipelines. This makes things more consistent in my opinion.

**Comment by themsaid** [comment]
Feel free to submit a PR with your suggested changes.
