### ISSUE TITLE
High Performance Laravel with PHP Fibers

### ISSUE THREAD

**Issue by rhzs** [laravel/ideas#2540]
* Laravel Version: 9.X
* PHP Version: 8.1
----

**Description** 

Currently we know that PHP 8.1 adopting Fibers. https://wiki.php.net/rfc/fibers 
I believe that it will be tremendous performance gain after implementing Fibers. 

Area that could be implement it with Fibers:
1. Laravel HTTP Client
2. Database Connections
3. Laravel Unit Testing
4. Laravel Request/Response context

**Comment by themsaid** [comment]
Fibers on its own doesn't offer asynchronous code execution.
