### ISSUE TITLE
Eloquent model "constructed" event

### ISSUE THREAD

**Issue by JakeBooher** [laravel/ideas#2541]
This event would likely fire at the end of `__construct` and would be helpful to define default values that are dynamic, and need to be set when the model is instantiated. For example, if you have a multitenant application with separate sites you could autopopulate a `site_id` attribute based on however that is detected (Request header on an API, the domain, etc). For example:

```php
    public static function bootSiteContentTrait(): void
    {
        static::registerModelEvent('constructed', function(Model $model) {
            if (Core::site() && !$model->exists && !$model->site_id) {
                $model->site_id = Core::site()->id;
            }
        });
    }
```

**Comment by tpetry** [comment]
Is there a specific reason you can't use the creating event?

```php
public static function booted(): void
{
    static::creating(fn ($model) => $model->site_id = $model->site_id ?? Core::site()->id);
}
```
