### ISSUE TITLE
Add Str::isNullOrEmpty

### ISSUE THREAD

**Issue by nessor** [laravel/ideas#2543]
Would it perhaps be helpful to add a method isNullOrEmpty for the string helpers? 
The implementation would be very simple. Maybe like this:

```php
public static function isNullOrEmpty($str){
    return (!isset($str) || trim($str) === '');
}
```

What do you guys think?

**Comment by tpetry** [comment]
The `blank()` helper is doing exactly what you are searching for.

**Comment by nessor** [comment]
Oh boi. That's nice! nvm

BTW: Why isn't there a static method for this?

**Comment by tpetry** [comment]
Because it's not limited to string, you can pass in arrays, numbers and booleans too.
