### ISSUE TITLE
Laravel Breeze install overwrites web routes

### ISSUE THREAD

**Issue by j-dexx** [laravel/ideas#2544]
https://github.com/laravel/breeze/blob/1.x/src/Console/InstallCommand.php#L78

This behaviour is fine if your steps are new project then install breeze.

On an existing laravel application it's really quite annoying.

**Comment by michaeldyrynda** [comment]
The idea of the scaffolding is to scaffold a new application. None of the scaffolding (Breeze or Jetstream or even laravel/ui) is intended to be added to an existing app.

**Comment by j-dexx** [comment]
Ok, I find that a little weird but fair enough.

**Comment by susanBuck** [comment]
@j-dexx - I ran into the same frustration. Was expecting it to append routes like laravel/ui does, not wipe the routes file clean.

I found that [Fortify](https://laravel.com/docs/8.x/fortify) is a better fit for incorporating authentication into existing applications.

**Comment by j-dexx** [comment]
Thanks @susanBuck I'll look at Fortify next time I need to add auth.
