### ISSUE TITLE
Warn if relation's foreign key is not in select list

### ISSUE THREAD

**Issue by shaedrich** [laravel/ideas#2550]
If I have something like this

```php
class Post extends Model
{
    public function comments(): HasMany
    {
        return $this->hasMany(Comment::class)->select('body');
    }
}

class Comment extends Model
{
    public function attachments(): HasMany
    {
        return $this->hasMany(Attachment::class);
    }
}
```
`Comment` just has an empty `attachments` array. I now, why this happens and that I can solve this, by adding 'id' to the 'select()` method call, but wouldn't it be good if Eloquent _knew_ that it needs this key? Since there's no error message, the mistake is everything but obvious due to the abstraction Laravel and Eloquent have.

**Comment by themsaid** [comment]
Feel free to submit a PR with your suggested changes.
