### ISSUE TITLE
dynamic Controller method

### ISSUE THREAD

**Issue by astutesixface** [laravel/ideas#2554]
Hi team,
I need some clarification with dynamic controller method
i upgrading the laravel 5.1 to 8.*, all is done, but only one bug,
my url is admin/admin-profile in 5.1 is working fine, but laravel 8 is not working 404 page error is showing.
this url will call method getAdminProfile(){  } but is not calling.
if this functionality is not available in laravel 8, then how can i manage this, if single url i will create route, but my application have more than 100 url like this, so please help me to solve this...
i was check this issues  by compare all file both laravel 5.1 and laravel 8
missing one file to capture the like this problem from ControllerInspector from routing folder.
so please help to solve this.. 
i can't write each method in web.php

**Comment by astutesixface** [comment]
any one can help this issue

**Comment by ahinkle** [comment]
This repository is for framework ideas and new features. For help please use the support channels:

- [laracasts.com/discuss](https://laracasts.com/discuss)
- [laravel.io/forum](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/mPZNm7A)
