### ISSUE TITLE
Feature request: fight against Google FLoC

### ISSUE THREAD

**Issue by ondrejmirtes** [laravel/ideas#2576]
Laravel is in a unique position to stand for clients and users of developers that use this framework and fight for their privacy.

Please read this article: https://plausible.io/blog/google-floc

And consider sending header `Permissions-Policy: interest-cohort=()` by default in all Laravel apps.

Thank you.

**Comment by akbarjimi** [comment]
I'm agree with you

**Comment by tobiasthaden** [comment]
https://github.com/laravel/framework/commit/c42988a551ffdae0e70aa15959969732265789c0
