### ISSUE TITLE
prohibited_if_exists add new validation rule

### ISSUE THREAD

**Issue by egXcoder** [laravel/ideas#2584]
i am working on a project where i am trying to validate request('feeling_id') and request('activity_id'). so the rule is, i can't have both of them at same time either request have feeling id or activity id. and it is not required to have any of them.
so i may have empty
or feeling_id
or activity_id
but feeling_id + activity_id should throw validation error

at the moment, i can't find any validation rule match my rule. the only near validation i found is 
'feeling_id'=>'prohibited_if:activity_id',
'activity_id'=>'prohibited_if:feeling_id',

but its not valid because prohibited_if require to have two parameters such as
'feeling_id'=>'prohibited_if:activity_id,value1',
'activity_id'=>'prohibited_if:feeling_id,value2',

but this is not helpful in my case.

so my suggestion is we can do it in two ways
option[1] -either introduce new rule 'prohibited_if_exists:activity_id' , where it will take only one parameter
option[2] -either parse the value where we can have * representing any character and it can be escaped
'prohibited_if:activity_id,*'
'prohibited_if:activity_id,\*'  but the escaping part is a bit tricky, so i would recommend option [1]

**Comment by themsaid** [comment]
Feel free to open a PullRequest with your proposal.
