### ISSUE TITLE
getRoutesByPath: Filter the routes by path

### ISSUE THREAD

**Issue by sinkcup** [laravel/ideas#2589]
```
$ php artisan route:list --help

Options:
      --method[=METHOD]    Filter the routes by method
      --name[=NAME]        Filter the routes by name
      --path[=PATH]        Filter the routes by path
```

route command has 3 filters, but only 2 in code:

![image](https://user-images.githubusercontent.com/4971414/116379484-9fac2180-a845-11eb-9746-2b50219f7145.png)

```php
Route::getRoutes()->getRoutesByMethod();
Route::getRoutes()->getRoutesByName();
```

https://github.com/laravel/framework/blob/277c2fbd0cebd2cb194807654d870f4040e288c0/src/Illuminate/Routing/CompiledRouteCollection.php#L270

suggestion: support getRoutesByPath: Filter the routes by path

```php
Route::getRoutes()->getRoutesByPath();
```

**Comment by themsaid** [comment]
Feel free to open a PR.
