### ISSUE TITLE
Document "version added" for functionality that was added in a minor version 

### ISSUE THREAD

**Issue by apokryfos** [laravel/ideas#2592]
I recently saw this question in [StackOverflow ](https://stackoverflow.com/questions/67317907/laravel-queueprune-batches-is-not-defined) which was asking why a feature that was in the 8.x documentation did not exist. I've seen similar questions before about this (last one was about `upsert` if I recall correctly). 

I think it would be helpful, if a feature is not shipped when the major version is released but rather added in a minor version, to note this in the documentation since it might save some development time (and more importantly) might provide motivation/reminder to always use the latest minor version.

**Comment by ahinkle** [comment]
Feel free to open a PR; they are open source.

**Comment by apokryfos** [comment]
While I can open a PR for this specific case, how can we enforce this happens every time a new feature is added to the documentation under e.g. version 8.x but is only available after e.g. version 8.40 or something like that? What I'm suggesting is more of a "Todo" for anyone updating the documentation to add the version available when they are documenting a new feature added in this way.

**Comment by apokryfos** [comment]
Based on the comment in https://github.com/laravel/docs/pull/7120  PRs for this sort of change are not welcome as the assumption is always using the latest Laravel version.
