### ISSUE TITLE
Helper: replace like ltrim and rtrim

### ISSUE THREAD

**Issue by cajakre** [laravel/ideas#2597]
Today, I've run into the situation that I needed to replace something only on the left side of the string.

For example, I have a uri: `path/to/nested/child/page`
From this uri, I wanted to remove up until a specific parent page. The result should be: `child/page`

I tried using `ltrim`, but because I didn't understand the nature of `$character_mask` as the second argument, I often had empty trim results.

Then I noticed, that Laravel doesn't have a convenient helper function for that (or has it?!). So I wrote that clunky code:

```php
$childUri = preg_replace(
    '/^' . preg_quote($parent->uri, '/') . '\//',
    '',
    $child->uri
);
```

Pretty unpleasant. I think a nice helper function like `replaceLeft` and `replaceRight` could satisfy the Artisan's pursue for happy code.

🖖

**Comment by michaeldyrynda** [comment]
You could use `Str::after()` if you just want the string fragment `child/page` or `Str::replaceFirst()` if you want to mutate the original string; either of these should get you where you need to be. 

The `Str` class is documented [here](https://laravel.com/docs/8.x/helpers#strings).

**Comment by cajakre** [comment]
Thanks, @michaeldyrynda.

Both seem sufficient in my case. Have only skimmed the helpers, there are so many of them!
