### ISSUE TITLE
Marix notification / log channel

### ISSUE THREAD

**Issue by zoomyboy** [laravel/ideas#2600]
Hey People,

As Matrix (https://matrix.org/) is geting more popular these days, it would be amazing to create a log channel or to write logs directly to a matix room. 

Or we could create a notification channel as well to send direct matrix notifications.

**Comment by thannaske** [comment]
I guess this is out of scope for the Laravel Core. There are tons of notification plugins out there and I guess it would be the best bet to develop it as 3rd party package.

**Comment by zoomyboy** [comment]
Sure, that's always an option. On the other hand, why is e.g. Slack natively supported then?

**Comment by themsaid** [comment]
I'm afraid we have no plans for this at the moment.
