### ISSUE TITLE
Ability to add value to existing Cache key

### ISSUE THREAD

**Issue by foremtehan** [laravel/ideas#2606]
I tried to add _pushing_ feature to cache system but it rejected for some reason https://github.com/laravel/framework/pull/34998

I think taylor didnt like the implementation so i opened this ticket for last try because in all my projects i copy paste the same macro and already tired of it.

So example here
https://stackoverflow.com/questions/48110089/pushing-value-to-existing-cache-value-in-laravel/48110145

**Comment by themsaid** [comment]
I'm afraid there are no plans to add this at the moment. Thanks for your contribution.
