### ISSUE TITLE
[Concern] Laravel Jetstream - Test naming convention

### ISSUE THREAD

**Issue by yob-yob** [laravel/ideas#2611]
so I just tried out jetstream and I'm also trying to learn TDD.

my concern is that why would jetstream create 2 test files for `ApiTokenTest`? one for `CreateApiTokenTest` and one for `DeleteApiTokenTest`

wouldn't it be a good idea to just merge both tests in one file named `ApiTokenTest`?

this may be too specific but I'm afraid that there is somewhat a larger idea behind the reason for using this type of naming convention, so before I'll try to make a pull request to Laravel I would like to ask the reason behind such convention.

**Comment by themsaid** [comment]
This repo is for suggesting features to the framework. Please use the forums to post questions.
