### ISSUE TITLE
Add PHP Type Declarations to Laravel Components

### ISSUE THREAD

**Issue by dinhquochan** [laravel/ideas#2614]
Now, Laravel `9.x` is required PHP version `7.4` and `8.0`. I think we should update all classes in Laravel core to support PHP Type Declarations (type-hints).

What do you think?

**Comment by akbarjimi** [comment]
I agree with you.
Laravel, as the major framework of the PHP world, needs to adapt to language changes and push developers to use new features.

**Comment by taylorotwell** [comment]
Adding types is a breaking change. *You* are free to go type crazy in your own application. 👍
