### ISSUE TITLE
custom name for XSRF-TOKEN cookie

### ISSUE THREAD

**Issue by msporleder-work** [laravel/ideas#2621]
We would like to rename our XSRF-TOKEN cookie to reflect the APP_ENV: XSRF-TOKEN-dev, for example.

It looks like it is here: https://github.com/laravel/framework/blob/277c2fbd0cebd2cb194807654d870f4040e288c0/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php#L193
and
https://github.com/laravel/framework/blob/277c2fbd0cebd2cb194807654d870f4040e288c0/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php#L208

anywhere else?

**Comment by themsaid** [comment]
You should ask on the forums.
