### ISSUE TITLE
add a --tailwind flag to artisan:serve

### ISSUE THREAD

**Issue by tobz-nz** [laravel/ideas#2643]
How about adding a --tailwind flag to artisan:serve that runs `npx tailwindcss -o public/app.css --watch --jit --purge="./resources/**/*.blade.php"` when starting the server.

**Comment by ahinkle** [comment]
Shouldn't really be needed with Laravel Mix and making some small adjustments to your package.json file within your application:

currently:
```json
"scripts": {
        "dev": "npm run development",
        "development": "mix",
        "watch": "mix watch",
        "watch-poll": "mix watch -- --watch-options-poll=1000",
        "hot": "mix watch --hot",
        "prod": "npm run production",
        "production": "mix --production"
    },
```

Update your development script with Tailwind:
```json
    "development": "TAILWIND_MODE=build mix",
```

**Comment by tobz-nz** [comment]
Lol, of course. I don't know where my head was at when I posted this.
