### ISSUE TITLE
Better type hints on magic methods

### ISSUE THREAD

**Issue by guiwoda** [laravel/ideas#284]
## Context
Laravel uses the magic `_call` and `__callStatic` methods in multiple places: Facades, Managers, Eloquent, etc. In most of them, method autocompletion is hard and library-dependent (see https://github.com/barryvdh/laravel-ide-helper). In other cases, generic methods (such as Managers' `driver()`method) document a `mixed` return type that is useless for hints on subsequent calls.

## Proposal

* Use class-level `@method` docblocks to document magic methods.
* Use `@return Foo|Bar|null` docblocks to suggest currently "mixed" cases.
* Build a tool / adapt Barry's code to easily regenerate this documentation based on concrete methods.

I'm available to start sending PRs about this, but I wanted @taylorotwell's input before doing so, as I assume I'm not the first one suggesting this, and it could mean a large number of files changed (although docblock only, so no risk of BC). 

Cheers!

**Comment by barryvdh** [comment]
I would be happy to adapt my code to generate phpdocs for actual Laravel classes :)

**Comment by xfoxawy** [comment]
I think it's something we all need to speed up our development process
I vote for this ala one

**Comment by taylorotwell** [comment]
Can we try it on one class so I can see what it looks like?

**Comment by guiwoda** [comment]
A simple example could be:

```php
namespace Illuminate\Support\Facades;

/**
 * @method static void get(string $uri, \Closure|array|string $action)
 * @method static void post(string $uri, \Closure|array|string $action)
 * @method static void put(string $uri, \Closure|array|string $action)
 * @method static void delete(string $uri, \Closure|array|string $action)
 * @method static void patch(string $uri, \Closure|array|string $action)
 * @method static void options(string $uri, \Closure|array|string $action)
 * @method static void match(array|string $methods, string $uri, \Closure|array|string $action)
 * @method static void resource(string $name, string $controller, array $options = [])
 * @method static void group(array $attributes, \Closure $callback)
 * @method static \Illuminate\Routing\Route substituteBindings(\Illuminate\Routing\Route $route)
 * @method static void substituteImplicitBindings(\Illuminate\Routing\Route $route)
 *
 * @see \Illuminate\Routing\Router
 */
class Route extends Facade
```

This could be generated by parsing the corresponding class (in this case, the `Illuminate\Contracts\Routing\Registrar`).

**Comment by guiwoda** [comment]
![screenshot from 2016-11-04 18-03-38](https://cloud.githubusercontent.com/assets/1625545/20022414/31bca9f6-a2b9-11e6-85b3-ad23710090b4.png)

**Comment by MordiSacks** [comment]
This is a must.

**Comment by guiwoda** [comment]
@taylorotwell should I keep 'em coming?

**Comment by barryvdh** [comment]
I don't know if you used my code for this, but it could also replace the phpdocs on the actual classes. Be happy to help if Taylor approves :)

**Comment by guiwoda** [comment]
@barryvdh I wasn't using your code, threw a few calls to `phpDocumentor` classes that were already there (phpunit needs them).
How could we cooperate? Should we work on one of our forks and then make a single PR?

**Comment by barryvdh** [comment]
Let Taylor decide first what he wants. The facades aren't changing that much.
And to be honest, most faces are on their way out, replaced by helpers etc.
I think phpdocs for Eloquent query builder etc are more useful perhaps.

**Comment by HipsterJazzbo** [comment]
Everyone I know who uses an IDE wants this so badly. It's an absolute must for those of us that do use an IDE — I hope it doesn't get rejected simply because most of the internals team don't :)

**Comment by ivandokov** [comment]
@taylorotwell already merged a [PR](https://github.com/laravel/framework/pull/16399) with docblocks for magic methods so I guess we can assume he approves the change.

**Comment by mikemand** [comment]
Any chance they could be backported to the other 5.x releases? This is so helpful!

**Comment by straube** [comment]
Hey guys! Are you still working on this? I'd like to contribute adding type hints to Facades that still don't have them. I'm not sure if I should submit pull requests to [5.5](/laravel/framework/tree/5.5) or [master](/laravel/framework/tree/master), though. Do you have any directions?

**Comment by mfn** [comment]
> I'm not sure if I should submit pull requests to 5.5 or master

This is easily answered: if in doubt, target master. *Especially* if you want to change something.

**Comment by n0rtan** [comment]
Guys, what about Illuminate\Database\Eloquent\Model? 
Models doesn't autocomplete in phpstorm without docblocks... Need to do this too?
![image](https://user-images.githubusercontent.com/9141547/37246239-dad5021a-24b6-11e8-8c94-7852779ab5e4.png)

**Comment by OzairP** [comment]
This should be closed @guiwoda !

**Comment by TBlindaruk** [comment]
@n0rtan , you can use my package for model type hinting https://github.com/TBlindaruk/laravel-idea-type-hinting

**Comment by guiwoda** [comment]
Thanks for the heads-up, @OzairP!

**Comment by mfn** [comment]
@TBlindaruk I took a look at your package and have an observation and a question:
- having to extend your Model doesn't work when a project already requires a custom parent eloquent model => you could add to your readme that the provided traits can be used directly in this case
- however isn't this obsoleted by https://github.com/barryvdh/laravel-ide-helper ?
  I've the latter installed and _do get_ autocomplete on regular and static methods like `whereKey` or `::whereKey`etc. That package adds phpdoc metadata to your models which means the IDE already knows about this:
  ```php
   * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\SomeModel whereToId($value)
   * @mixin \Eloquent
   */
  class SomeModel extends SomeOtherEloquentBaseModel
  ```
