### ISSUE TITLE
[Improvement] Filter mysql table data from json field (in array)

### ISSUE THREAD

**Issue by lkmadushan** [laravel/ideas#296]
This is what you have in Laravel now.

```
// SQL tags -> {"name": "javascript"}
SELECT * FROM books WHERE tags->"$.name" = 'javascript'

// Builder
DB::table('books')->where('tags->name', 'javascript')->toSql();
```
What I am suggesting is make it easier to search in json array,

```
// SQL tags ->  {"name": ["javascript", "php", "java"]}
SELECT * FROM books WHERE JSON_CONTAINS(tags->"$.name", '["javascript", "php"]');

// Builder
DB::table('books')->where('tags->name', ['javascript', 'php'])->toSql();

// Eloquent
Book::whereJsonContains('tags->name', ['javascript', 'php']);

// or
Book::jsonContains('tags->name', ['javascript', 'php']);
```

I would like to make a pull request for this. Please let me know your suggestions.

**Comment by yoosuf** [comment]
@taylorotwell  looks a like this an awesome way of filtering son contents

**Comment by ntzm** [comment]
Why not use `whereIn`?

**Comment by lkmadushan** [comment]
@ntzm as method name?

**Comment by sepehr** [comment]
> Why not use `whereIn`? _— [**@ntzm**](https://github.com/ntzm) on [Nov 10, 2016, 3:05 PM GMT+3:30](https://github.com/laravel/internals/issues/296#issuecomment-259668338 "2016-11-10T11:35:00Z")_

The proposed functionality is totally different from `whereIn`. See [`JSON_CONTAINS`](https://dev.mysql.com/doc/refman/5.7/en/json-search-functions.html#function_json-contains) docs.

**Comment by JoeMugen** [comment]
@lkmadushan Just facing the same need , a `whereIn` like in an array stored in a JSON column type (no keys)
For now, I'm using a scope doing a raw request D:

Your approach is interesting but does it work with this kind of structure: `["foo", "bar", "laravel"]`
If you do this:
```
Book::whereJsonContains('tags', ['javascript', 'php']);
```
You'll get all records havings tags `javascript` **AND** `php` or I'm wrong? If yes, what's your idea to manage **OR** case?

Thanks :)

**Comment by royduin** [comment]
I'd the same "issue", what I've done for now in my shop model:
```
public function products()
{
    return Product::whereRaw('JSON_CONTAINS(shops,"'.$this->id.'")');
}
```

Something like this would be nice to have in the framework: 
```
whereJsonContains($column, $value, $comparison = 'and')
```
And it would be really awesome if `hasMany()`could work with this.

**Comment by Mittler1** [comment]
This feature would be awesome! Searched around the net and there is no *really* satisfying solution yet.

**Comment by staudenmeir** [comment]
I proposed `whereJsonContains()`: https://github.com/laravel/framework/pull/24258

**Comment by staudenmeir** [comment]
The next release will contain `whereJsonContains()`: #24330

**Comment by staudenmeir** [comment]
@driesvints Can be closed.

**Comment by BNhashem16** [comment]
How to search in json?
$posts = Post::where('country_id' , $search_country)->where('page_id' , $page->id)->whereJsonContains('title',['like','%'.$search_post.'%'])->paginate(12);

**Comment by phpdev1995** [comment]
To see if the template_ids `JSON` field contains "any" of the values in a needle array, you gonna need to utilize multiple OR'd `JSON_CONTAINS` conditions which requires MySQL 5.7:
for more [stackoverflow](https://stackoverflow.com/questions/44669673/search-in-json-column-using-laravels-eloquent)

     $ids = ['1', '3', '48'];
     Post::where('accessable_to', 1)
    ->where(function ($query) use ($ids) {
        $firstId = array_shift($ids);

        $query->whereRaw(
            'JSON_CONTAINS(template_ids, \'["' . $firstId . '"]\')'
        );

        foreach ($ids as $id) {
            $query->orWhereRaw(
                'JSON_CONTAINS(template_ids, \'["' . $id . '"]\')'
            );
        }

        return $query;
    });
    return Post::paginate(3);

**Comment by ch-dani** [comment]
> $posts = Post::where('country_id' , $search_country)->where('page_id' , $page->id)->whereJsonContains('title',['like','%'.$search_post.'%'])->paginate(12);

Also not working on my end. Please guide if someone has solution.

**Comment by ikramooe** [comment]
> > $posts = Post::where('country_id' , $search_country)->where('page_id' , $page->id)->whereJsonContains('title',['like','%'.$search_post.'%'])->paginate(12);
> 
> Also not working on my end. Please guide if someone has solution.

any solution !
