### ISSUE TITLE
Eloquent casts to array return an empty array by default

### ISSUE THREAD

**Issue by alexdover** [laravel/ideas#369]
I've just been using the casts feature to cast a text field to an array, very helpful.

However, when the text field is empty the default return value is null. At present the default behaviour is to return the result of `json_decode`. I would propose an extra check here for the result and return an empty array instead.

This would then avoid having to check if the attribute is an array prior to handling as such.

For example

```
if (in_array(1, $my_model->options) {
    // ...
}
```
rather than
```
if (is_array($my_model->options) && in_array(1, $my_model->options) {
    // ...
}
```

I'd be happy to put this change together as a pull request but wanted to see if anyone had any reasons why this shouldn't be the default behaviour?

**Comment by bbashy** [comment]
Can you use this instead?
```php
if (array_has($my_model->options, 1) {
    // ...
}
```

**Comment by andrey-helldar** [comment]
@alexdover, it seems to me that the changes proposed in laravel/framework#30958 PR will allow this to be implemented in custom castes.

**Comment by mfn** [comment]
Laravel 7 provided custom casts https://laravel.com/docs/7.x/eloquent-mutators#custom-casts so you can make any behavior you want now.
