### ISSUE TITLE
[Proposal] Improve error responses for requests that expect json

### ISSUE THREAD

**Issue by adiachenko** [laravel/ideas#451]
## Current behavior:
- when `HttpException` (e.g. `abort()`) or general uncaught exception is thrown from within the app, default Handler always responds with **html page** disregarding request headers.

## Expected behavior:
- when  `HttpException` is thrown, show json response with a message that corresponds   to it's status code. For example, `abort(400)` will give you:

```
{
    "error": "Bad Request"
}
```
- when general uncaught Exception is thrown and `APP_DEBUG` is equal to `false`, show html page with a stack trace
- when general uncaught Exception is thrown and `APP_DEBUG` is equal to `true`, show json response with the following contents:

```
{
    "error": "Internal Server Error"
}
```

## Possible implementation (needs revision)

Don't consider this final or preferred implementation. Currently, I achieve described behavior by overriding 2 methods on `App\Exceptions\Handler`:

```
    /**
     * Prepare response containing exception render.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Exception $e
     * @return \Symfony\Component\HttpFoundation\Response
     */
    protected function prepareResponse($request, Exception $e)
    {
        if ($this->isHttpException($e)) {
            return $this->toIlluminateResponse($this->renderHttpException($e), $e);
        } else {
            return $request->expectsJson() && ! config('app.debug')
                ? response()->json(['error' => Response::$statusTexts[500]], 500)
                : $this->toIlluminateResponse($this->convertExceptionToResponse($e), $e);
        }
    }

    /**
     * Render the given HttpException.
     *
     * @param  \Symfony\Component\HttpKernel\Exception\HttpException  $e
     * @return \Symfony\Component\HttpFoundation\Response
     */
    protected function renderHttpException(HttpException $e)
    {
        $status = $e->getStatusCode();

        if (request()->expectsJson()) {
            // See Symfony\Component\HttpFoundation\Response
            return response()->json(['error' => Response::$statusTexts[$status]], $status);
        }

        view()->replaceNamespace('errors', [
            resource_path('views/errors'),
            __DIR__.'/views',
        ]);

        if (view()->exists("errors::{$status}")) {
            return response()->view("errors::{$status}", ['exception' => $e], $status, $e->getHeaders());
        } else {
            return $this->convertExceptionToResponse($e);
        }
    }
```

## Random Thoughts

1. As API routes are conventionally placed under `/api` prefix anyway it may be worth considering to add `starts_with($request->path(), 'api/')` check in addition to `$request->expectsJson()` check to make json error handling more deterministic (e.g. what if you're viewing your API resource in the browser and don't send appropriate `Accept` header).

2. It seems like a good idea to bring validation errors under namespace (Laravel already utilizes `error` top-level member) when displaying them inside json so that json error responses are consistent in structure by default.

## Conclusion

These were my thoughts on the matter. I won't be submitting any PRs for now because it seems like a fairly opinionated suggestion and I'm not sure whether anyone else is interested.

But it doesn't seem like an optimal workflow to tweak exception handler each time you start writing some genertic API. Just feels like a bother to me (especially that the changes are fairly trivial and don't contradict other contexts like web routes). Any thoughts on this?

**Comment by AkenRoberts** [comment]
This was added back in 5.5. 👏
