### ISSUE TITLE
[Proposal] An option to throw exception when a relation is accessed and does not exist in $relations property.

### ISSUE THREAD

**Issue by ajcastro** [laravel/ideas#455]
This will prevent developers from accidentally experiencing N+1 query problem. Because there are times that developers forget to eager load the relations.

__Example usages__:

__Set on a local/single query__:
```php
$users = User::strictRelations(true)->with(['posts'])->get();
```

__Set globally__:
```php
class User extends Model {
  protected static $strictRelations = true;
}
```

__NOTE__: Feel free to suggest a more appropriate term other than `strictRelations` :).

**Comment by ntzm** [comment]
I really like this idea. What about something like an array of relations that you can prevent from being non-eager loaded.

Something like:

```php
class User extends Model
{
    // All relationships have to be eager loaded before use
    protected $eagerLoadOnly = ['*'];

    // Relationships can be eager loaded or loaded later (default)
    protected $eagerLoadOnly = [];

    // Users have to be eager loaded, but every other relation can be loaded later
    protected $eagerLoadOnly = ['users'];
}
```

Obviously the variable name is terrible, but I think this flexibility would be nice.

**Comment by ajcastro** [comment]
That's also good.

**Comment by deleugpn** [comment]
I'm not sure if I understood the suggestion here, but if I did, I think this would be the wrong approach. Instead of demanding strict use of eager load, perhaps what you guys want is to disable lazy load. That way, if you try to access a specific relationship, it will automatically fail.

**Comment by ajcastro** [comment]
@deleugpn , Yeah it will work that way. You can call it hack, not an official "laravel-way". Since it is not the official way on how to do that. A beautiful api on how to enable that feature for that can be decided by the majority or by @taylorotwell.

Your solution is acceptable and thanks for that! :)

**Comment by tonysm** [comment]
Something very similar was recently merged into Rails: https://blog.saeloun.com/2020/02/25/rails-strict-loading-mode-to-fix-n-1.html

To have a similar implementation, we could support the first suggested syntax:

```php
$users = User::withStrictRelations()->with(['posts'])->get();
$users->posts; // works

$users = User::withStrictRelations()->first();
$users->posts; // would throw the exception.
```

I guess somehow we would have to change the model hydration (including relationships) when the query is set to strict relations.

In the Rails version, there's also the possibility to make it per relationship, so:

```php
class User extends Model
{
  public function posts()
  {
    return $this->hasMany(Post::class)->withStrictRelations();
  }
}

$user = User::with('posts')->first();
$user->posts; // works

$user = User::first();
$user->posts; // throws exception.
```

**Comment by donnysim** [comment]
And I thought I was insane for disliking automatically loading of relationships 😅 I actually have a model that disables it for all relations:
```php
    public function getRelationValue($key)
    {
        if ($this->relationLoaded($key)) {
            return $this->relations[$key];
        }

        if (\method_exists($this, $key)) {
            throw new RestrictedException(\sprintf('Loading relation should be explicit: %s::%s.', static::class, $key));
        }

        return null;
    }
```
and I really dig it, it makes the developer think about loading relations - does he really need a relation or maybe he can go with a simple join instead of just littering the template with relations accessors and spamming needles queries just for one additional column.

I actually go even further as to forbidding `$appends` 🤷‍♂️ there's nothing worse than having appends by default.

**Comment by themsaid** [comment]
I've opened a PR to introduce a strict mode that restricts lazy loading.

https://github.com/laravel/framework/pull/37334
