### ISSUE TITLE
Improve Eloquent casting for collection type

### ISSUE THREAD

**Issue by arcanedev-maroc** [laravel/ideas#460]
I'm wondering if it's a good idea to return an empty `Collection` object instead of `null` when we specify a casting like this:

```php
// Meta Model Class

protected $casts = [
    'keywords' => 'collection',
];
```

This will avoid us to add more checks like `is_null($this->keywords)`. And it's views friendly when you do something like this `{{ $meta->keywords->implode(', ') }}`.

And for if statement, i prefer to do something like `@if ($meta->keywords->isEmpty())` than `@if (is_null($meta->keywords))`.

So, my PR will be something like this ([At this section](https://github.com/laravel/framework/blob/master/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L456-L491) on `master` branch):

```php
/**
 * Cast an attribute to a native PHP type.
 *
 * @param  string  $key
 * @param  mixed  $value
 * @return mixed
 */
protected function castAttribute($key, $value)
{
    if (is_null($value)) {
        return $this->castNullAttribute($key, $value);
    }

    switch ($this->getCastType($key)) {
        case 'int':
        case 'integer':
            return (int) $value;
        case 'real':
        case 'float':
        case 'double':
            return (float) $value;
        case 'string':
            return (string) $value;
        case 'bool':
        case 'boolean':
            return (bool) $value;
        case 'object':
            return $this->fromJson($value, true);
        case 'array':
        case 'json':
            return $this->fromJson($value);
        case 'collection':
            return new BaseCollection($this->fromJson($value));
        case 'date':
            return $this->asDate($value);
        case 'datetime':
            return $this->asDateTime($value);
        case 'timestamp':
            return $this->asTimestamp($value);
        default:
            return $value;
    }
}

/**
 * Cast a null attribute.
 *
 * @param  string  $key
 * @param  mixed  $value
 * @return mixed
 */
protected function castNullAttribute($key, $value)
{
    switch ($this->getCastType($key)) {
        case 'collection':
            return new BaseCollection;
        default:
            return $value;
    }
}
```

We can also add `array` to the casts instead returning a `null` value.

```php
/**
 * Cast a null attribute.
 *
 * @param  string  $key
 * @param  mixed  $value
 * @return mixed
 */
protected function castNullAttribute($key, $value)
{
    switch ($this->getCastType($key)) {
        case 'array':
            return [];
        case 'collection':
            return new BaseCollection;
        default:
            return $value;
    }
}
```

cc: @taylorotwell @themsaid @GrahamCampbell

**Comment by sisve** [comment]
This seems related to #9

**Comment by taylorotwell** [comment]
I agree an empty collection may make sense in this situation.

**Comment by suadhuskic** [comment]
+1

**Comment by linaspasv** [comment]
@arcanedev-maroc when could we expect PR for this?

**Comment by sisve** [comment]
It would make sense to add a not-null collection cast (another cast) for this feature to allow code to check for null values vs empty collections. Different models (or same model in different context) may behave differently.

**Comment by darron1217** [comment]
I created PR to close this issue :)

**Comment by linaspasv** [comment]
It's a shame that this idea was not implemented yet.

**Comment by basepack** [comment]
Yes a great idea, my +1 on it 👍

**Comment by hawezo** [comment]
Any news on that? Sounds really great.

**Comment by kfirba** [comment]
Is this going to get implemented :)?

**Comment by andrey-helldar** [comment]
@arcanedev-maroc, it seems to me that the changes proposed in laravel/framework#30958 PR will allow this to be implemented in custom castes.
