### ISSUE TITLE
New method whereBetweenDate for QueryBuilder

### ISSUE THREAD

**Issue by projct1** [laravel/ideas#489]
Will be good convert:
```
$builder->whereBetween(DB::raw('date(created_at)'), ['2017-01-03', '2017-02-10']);
```
into:
```php
$builder->whereBetweenDate('created_at', ['2017-01-03', '2017-02-10']);
```

**Comment by eskrano** [comment]
@rorc 
So how about this

```php 
$date= Carbon::now()->addDays(10);

SomeModel::whereBetween('created_at',[
    $date->copy()->startOfDay(),
    $date->copy()->endOfDay()
])->get()

**Comment by rorc** [comment]
@eskrano You propose to create new method `whereBetweenDay`?
Yea, good idea too, as well as `whereBetweenMonth` and `whereBetweenYear` 👍

**Comment by deleugpn** [comment]
What keeps you from `$builder->whereBetween('created_at', ['2017-01-03', '2017-02-10']);
`

**Comment by rorc** [comment]
@deleugpn If i pass equal dates, thats become not working (0 results found)

**Comment by eskrano** [comment]
@rorc u can use my variant for wherebetween and it's working

**Comment by rorc** [comment]
@eskrano But its a crutch...

**Comment by rorc** [comment]
@eskrano And my variant better `$builder->whereBetween(DB::raw('date(created_at)'), ['2017-01-03', '2017-02-10']);`

**Comment by eskrano** [comment]
@rorc why your variant is bettwer?

**Comment by rorc** [comment]
@eskrano Cleaner and more understandable :)
