### ISSUE TITLE
[Proposal] Multiple or batch update support in query builder.

### ISSUE THREAD

**Issue by ajcastro** [laravel/ideas#490]
An api for updating multiple records in one query to avoid N+1 query issue.

Sample Method API:
```php
updateBatch($keyName = 'id', $rows, $columns = null);
 // If columns is given, only those columns will be included in update.
```

```php
DB::table('users')->updateBatch('id', [
  [
    'id'    => 1,
    'name'  => 'John',
    'email' => 'john@yeah.com',
  ],[
    'id'    => 2,
    'name'  => 'Mary',
    'email' => 'mary@ok.com'
  ],
]);
```
The resulting mysql query for this would be:
```mysql
UPDATE `users`
SET 
`name` = CASE
  WHEN `id` = 1 THEN 'John'
  WHEN `id` = 2 THEN 'Mary'
  ELSE name
END,
`email` = CASE
  WHEN `id` = 1 THEN 'john@yeah.com'
  WHEN `id` = 2 THEN 'mary@ok.com'
  ELSE email
END
WHERE `id` IN (1,2)
```

Feel free to suggest or improve this api. :slightly_smiling_face:

**Comment by skyrpex** [comment]
I thought saveMany already did a batch update..

**Comment by ajcastro** [comment]
I checked the source code of it,. It is calling save. on each model.. Also saveMany() is a different use-case

**Comment by skyrpex** [comment]
Oops, you're right. I found a related issue: https://github.com/laravel/framework/issues/1295.

**Comment by ajcastro** [comment]
I think it is better if we will create a separate package, which can be called __"laravel-unit-of-work"__.
A __Unit Of Work Pattern__ for laravel. Just like doctrine's `EntityManager`.

**Comment by Dylan-DPC** [comment]
Bulk updates (in sql terms) normally indicate that you want to update the same field(s) for multiple rows (which is possible in Eloquent as well). I don't think there is a update mechanism that suits your use case. (I may be wrong though :wink: )

**Comment by concept-core** [comment]
Are there any updates on this @ajcastro ?
