### ISSUE TITLE
[Proposal] PluckMultiple Collection method

### ISSUE THREAD

**Issue by Alexgmin** [laravel/ideas#491]
Sometimes I miss the need of having a pluck method that can pluck multiple values

Example:
```php
$a = collect(
    [
        [
            'foo' => 'fooValue',
            'foo2' => 'fooValue2',
            'foo3' => 'fooValue3',
        ],
        [
            'foo' => 'fooValueb',
            'foo2' => 'fooValueb2',
            'foo3' => 'fooValueb3',
        ],
    ]
);
$a->pluckMultiple(['foo', 'foo2']);
/*
[
    0 => [
        'foo' => 'fooValue', 
        'foo2' => 'fooValue2',
    ],
    1 => [
        'foo' => 'fooValueb', 
        'foo2' => 'fooValueb2',
    ],
];
*/
$a->pluckMultiple(['foo', 'foo2'], 'foo3');
/*
[
    'fooValue3' => [
        'foo' => 'fooValue',
        'foo2' => 'fooValue2',
    ],
    'fooValueb3' => [
        'foo' => 'fooValueb',
        'foo2' => 'fooValueb2',
    ],
];
*/
```

Right now I have this quick macro
```php
Collection::macro('pluckMultiple', function ($values, $key = null) {
    return $this->mapWithKeys(function ($item, $itemKey) use ($values, $key) {
        $results = [];

        foreach ($values as $value) {
            $itemValue = data_get($item, $value);
        
            $resultKey = last(explode('.', $value));
            if (is_null($key)) {
                $results[$resultKey] = $itemValue;
            } else {
                $results[data_get($item, $key)][$resultKey] = $itemValue;
            }
        }

        if (is_null($key)) {
            return [$itemKey => $results];
        } else {
            return  $results;
        }
    });
});
```
Would something like this be a good idea to add to the framework?

**Comment by Dylan-DPC** [comment]
Pluck takes multiple parameters. You can do `->pluck('name', 'age')`

**Comment by sebastiandedeyne** [comment]
> Pluck takes multiple parameters. You can do ->pluck('name', 'age')

No you can't, the second parameter is the key, so you'd get a collection of names keyed by age.

**Comment by Alexgmin** [comment]
You can also do something like `->pluck(['user', 'name'], 'age')`, but that's just the same as`->pluck('user.name', 'age')`.

**Comment by Dylan-DPC** [comment]
@Alexgmin pluck doesn't accept an array as 1st parameter

**Comment by Alexgmin** [comment]
@Dylan-DPC Yes it does. 
https://github.com/laravel/framework/blob/5.4/src/Illuminate/Support/Collection.php#L681
https://github.com/laravel/framework/pull/17649

**Comment by Dylan-DPC** [comment]
Oh ya the collection method does the builder method doesn't :)

**Comment by GeorgeNance** [comment]
+1 for this. This would be very useful to have

**Comment by fede91it** [comment]
@taylorotwell Why don't you want to integrate this feature? It's more than useful!

**Comment by edvordo** [comment]
You can always do something simple like this

```php
// reusing $a from first post
$a->keyBy('foo')->map(function (array $item) {
    return collect($item)->only(['foo', 'foo3'])->toArray();
});
```

Or with Eloquent models

```php
Model::all(['column_1', 'column_2', 'column_3'])->keyBy('column_1')->map(function (Model $item) {
    return $item->only(['column_2', 'column_3']);
});
```
which will run pretty much the same query pluck
```sql
select `column_1`, `column_2`, `column_2` from `models`;
```

---
Or create the PR, based on the reaction on the first post, seems like this feature was liked, so it may have been close just because noone touched it.
