### ISSUE TITLE
2 Query Builders

### ISSUE THREAD

**Issue by watchwood** [laravel/ideas#494]
https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Eloquent/Builder.php

https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Query/Builder.php

Was poking through the source code and noticed this.  There seems to be a fair bit of overlap between them, so I'm wondering if one should extend the other or if they should both come from a common core.

**Comment by skyrpex** [comment]
Both use `Illuminate\Database\Concerns\BuildsQueries` trait, and the `Eloquent\Builder` uses the `Query\Builder` internally. Not sure if there's still code that can be refactored, though,

**Comment by KKSzymanowski** [comment]
@skyrpex I agree

> Not sure if there's still code that can be refactored, though,

If there was, it would be.
