### ISSUE TITLE
[Proposal] Unit of Work Pattern for Laravel

### ISSUE THREAD

**Issue by ajcastro** [laravel/ideas#495]
This can be a separate composer package.
A __Unit Of Work Pattern__ for laravel. Just like doctrine's `EntityManager`.
I have started a draft on how to do this. I will post it here later.

Related issue: https://github.com/laravel/internals/issues/490

**Comment by sisve** [comment]
Could you clarify what a unit-of-work pattern would mean for Laravel? Perhaps clarify how this differs from wrapping all your stuff in a database transaction?

**Comment by RemiCollin** [comment]
My first guess would be that the unit-of-work pattern would be extremely diffcult to implement due to the tight coupling between an Eloquent model and the database. Probably not even implementable without altering the core itself.

**Comment by guiwoda** [comment]
You could implement UoW as an observer object, so that a middleware could trigger saves inside a transaction. That way, you know _which objects were changed_ without them needing to send the `save()` message.

TBH, I don't think it's a common use of an AR. If you're into AR, you should accept the fact that you're tightly coupled to the database and model around that. Database details **will** leak anyway... UoW makes sense in Doctrine because, as soon as an Entity is fetched, it looses database context, so you have to track them somehow...

**Comment by ajcastro** [comment]
The problem with ActiveRecord, is that it is easy to make your application slower when you have lots of models to save,
because, it performs a lot of individual insert/update queries that cause the slow down of the application.
That's why I feel UOW is a need, just how Doctrine's `EntityManager` works.

I came into a situation where I remove all save() and create() calls because it took several minutes to finish, then replace it with a UOW pattern.
The difference is big as it just took a matter of seconds when using UOW pattern. 

In my UOW, I just mark the created, updated and deleted models, and perform batch inserts, updates, and deletes, that's why it is faster.
:slightly_smiling_face:

**Comment by ajcastro** [comment]
I like how Doctrine's `EntityManager` works, but I would more love to use a laravel-like syntax or terminology of the api.

**Comment by ajcastro** [comment]
Kindly read this for article for reference: http://culttt.com/2014/07/07/doctrine-2-different-eloquent/

**Comment by shulard** [comment]
The main advantage of using an UoW can be to avoid SQL requests to retrieve the same entity during a web request processing :

> Doctrine 2 however manages these kinds of scenarios through it’s Identity Map.
>
> Doctrine 2 is clever enough to keep track of entities and so it will just return you the same instance over and over for the duration of the PHP request. This means you can request the same object in  multiple different ways, but Doctrine 2 won’t need to hit the database.

This kind of feature can be a huge improvement in the Laravel Eloquent implementation.

**Comment by ajcastro** [comment]
This can be good as a package. https://github.com/ajcastro/laravel-uow

**Comment by mnavarrocarter** [comment]
Maybe implementing a method that returns a raw SQL Statement in the Model class would work. We wrap it around a DB:: Transaction to do the trick. Not a nice way to do it, but it could do the job.
