### ISSUE TITLE
Runtime cache

### ISSUE THREAD

**Issue by rentalhost** [laravel/ideas#496]
Currently Laravel have supports to Cache things that are shared to all users (since that uses the same key). By other side, it's not possible create a kind of cache that uses the same key that exists only during current request (basically the same that setup the cache type to `array`, but that works together with the `file` cache or similar).

**This should be a shortcut to that:**

```php
class MyClass {
    static private $cache;

    static public function compile() {
        if (!static::$cache) {
            static::$cache = doSomethingHeavy();
        }

        return static:$cache;
    }
}
```

**This is what I wants to do:**

```php
class MyClass {
    static public function compile() {
        return RuntimeCache::rememberForever(MyClass::class, function () {
            return doSomethingHeavy();
        });
    }
}
```

It'll avoid create properties on class that cache things, and will make it more flexible, because you can determine a key for each cache key (for instance, a cache based on class but treating a specific user: `className.userId`).

**Comment by skyrpex** [comment]
IMO this is easily achiveable using the container to declare a singleton object (maybe a Illuminate's cache with the array driver directly).

**Comment by tomschlick** [comment]
I believe you can do this with

```php
Cache::store('array')->put('bar', 'baz');
```

**Comment by rentalhost** [comment]
@tomschlick It has worked to me. Seems fine. There some way to I make it a facade that runs without I always call the `::store('array')`? Like `RuntimeCache::put()`.

**Comment by tomschlick** [comment]
I would suggest creating the RunTimeCache manually as a wrapper around the main Cache class with the store() method.

**Comment by LKDevelopment** [comment]
@rentalhost Look at https://github.com/spatie/laravel-blink
