### ISSUE TITLE
Use namespaces in migrations and seeds

### ISSUE THREAD

**Issue by skyrpex** [laravel/ideas#497]
Migrations and seeds aren't currently following the PSR-4 standard, which mentions:

> The fully qualified class name MUST have a top-level namespace name, also known as a “vendor namespace”.

I propose using the `Migrations` and `Seeds` root namespaces for the related folders (like App and Tests). This needs altering the composer.json.

Is there any reason not to do so?

**Comment by rentalhost** [comment]
_Reviving this important topic..._

I think that the unique reason is that the migration class name is based on migration filename. Eg. `2018_03_01_093100_create_users.php` is for `CreateUsers` class.

It have a big disadvantage, once that you can't have two migrations with the same name in none domain of project, and it affects directly packages projects with multiple domains.

**Eg. how could it be:**

```
\Users\Migrations\0000_00_00_000000_install.php  -> App\Users\Migrations\Install
\Medias\Migrations\0000_00_00_000000_install.php -> App\Media\Migrations\Install
```

**How it must be for now:**

```
\Users\Migrations\0000_00_00_000000_users_install.php   -> UsersInstall
\Medias\Migrations\0000_00_00_000000_medias_install.php -> MediasInstall
```

And the solution is very simple. Instead of depends of filename to determines the class name, just run [`get_declared_classes()`](http://php.net/manual/en/function.get-declared-classes.php) before include file, then run again to identify the new loaded class and consider it as the migration class from this file.

**Comment by sisve** [comment]
The migrations are not loaded via PSR-4. The Migrator class [looks into the defined folders for the migrations](https://github.com/laravel/framework/blob/a35c52dee08a4f49da7317c08bf27b179c688071/src/Illuminate/Database/Migrations/Migrator.php#L427-L436) and [loads them with a call to require_once](https://github.com/laravel/framework/blob/a35c52dee08a4f49da7317c08bf27b179c688071/src/Illuminate/Database/Migrations/Migrator.php#L446-L448).

Is it really that important to be able to reuse class names in your migrations?

I believe a more proper implementation of namespaces would be to modify the conversion of filename-to-classname in the [resolve method](https://github.com/laravel/framework/blob/a35c52dee08a4f49da7317c08bf27b179c688071/src/Illuminate/Database/Migrations/Migrator.php#L446-L448) and prefix it with your namespace.

**Comment by rentalhost** [comment]
When you are working with a multi-domain project it is really important, else you will have long filenames as workarround.

**Comment by mundomatt** [comment]
How come this was closed? My CI has a hook to check PSR2 compliance and I just ran into this issue. Can't be PSR2 compliant without namespaces.

**Comment by Jlonghi** [comment]
Why was this closed? I wasted an entire day trying to get namespace migrations working.

**Comment by mundomatt** [comment]
@michaeldyrynda It seems you are correct, although when checking your code for PSR2 compliance with a tool like `phpcs` it will fail stating "each class must be in a namespace of at least one level". I guess that is a setting I will have to configure in the code sniffer.

**Comment by michaeldyrynda** [comment]
Just have it look only at your `app` directory

**Comment by ibrunotome** [comment]
Just look at https://github.com/artesaos/migrator

**Comment by winni4eva** [comment]
@michaeldyrynda setting my sniffer to point to just the app directory worked, just wondering if that is the best solution though since all class changes outside the app namespace a prone to psr2 violations now

**Comment by JasonTheAdams** [comment]
To be clear, this does violate PSR-1, not PSR-2:
![PSR-1 Screenshot](https://cl.ly/8a6c70ab98a6/Image%2525202019-05-07%252520at%2525202.30.47%252520PM.png)

**Comment by tnatanael** [comment]
+1

**Comment by Esternome** [comment]
> To be clear, this does violate PSR-1, not PSR-2:
> ![PSR-1 Screenshot](https://camo.githubusercontent.com/3cfb3020b789a39d9c999cc36f00ddd9d80b5d23/68747470733a2f2f636c2e6c792f3861366337306162393861362f496d61676525323532353230323031392d30352d303725323532353230617425323532353230322e33302e343725323532353230504d2e706e67)

What about PSR-12?  Thanks
