### ISSUE TITLE
Join via relation

### ISSUE THREAD

**Issue by rentalhost** [laravel/ideas#501]
Currently Eloquent have two features, `join()` that allows you references the own table in query and _relations_ that allows you get related rows from a loaded row. I guess that both can be united, then the `join()` can be more simplified, taking advantage of two existing features.

On pratical:

```php
class User extends Model {
    public function phones() {
        return $this->hasMany(Phone::class);
    }
}
```

Then on query, it should be allowed:

```php
$usersQuery = User::query();
$usersQuery->joinRelation('phones');
$usersQuery->where('phones.type', 'residential');
```

That will be a replacement for:

```php
$usersQuery->join('phones', 'phones.user_id', 'users.id');
```

It'll take advantage of the relation data, making possible you join data directly on query to make operations like `where()` works over this _query-relation_. Another advantage is that any change on relation will affects the join (then you need change only in one place, when it is need).

---

**Signature suggestion:**

```php
$model->joinRelation (
    string $relationName,
   ?string $alias        = null,
   ?string $type         = null, /** @default "inner" */
   ?bool   $where        = null, /** @default false */
);
```

---

**To be discussed:**

It should works fine for relations like `HasMany`, but I still don't know how it should does in case of other relations, like `HasOne`. Should not be allowed or then implements a method of accept only compatible relation? (It's possible?)

**Comment by alberto-bottarini** [comment]
What is the purpose of $where boolean?

**Comment by rentalhost** [comment]
@alberto-bottarini I don't know, but the current implementation on `join()` exists this argument. Seems like an alternative to join, it implements with where instead of join. But it make joined table unusable by other wheres.

**Comment by Dylan-DPC** [comment]
@rentalhost What's the purpose of this ? what does it achieve? pros/cons?

**Comment by Garbee** [comment]
```php
$usersQuery = (new User)->newQuery();
$userQuery->whereHas('phones', function (Builder $query) {
   $query->where('type', '=', 'residential');
});
$data = $userQuery->get();
```

This is currently a provided API to achieve this. Is there any reason this doesn't work for you?

**Comment by rentalhost** [comment]
On reality, join accept more complex things, like you do order by some joined values. For instance:

```sql
LEFT JOIN phones ON
    phones.user_id = users.id

...
ORDER BY
    phones.priority,
    phones.created_at
```

Then the `joinRelation()` will help that by allowing you use a preexistent relation `HasMany` as a filler for join arguments.

```php
$usersQuery->joinRelation('phones'); // is a replacement for
$usersQuery->join('phones', 'phones.user_id', 'users.id');
```

And as a mentioned, the major advantage is that you will have only a maintenance point if you need change how this join will works (in case, in the own relation).

**Comment by fico7489** [comment]
see https://github.com/fico7489/laravel-eloquent-join
