### ISSUE TITLE
Request::only and Collection::only behave inconsistently

### ISSUE THREAD

**Issue by adamtomat** [laravel/ideas#504]
`Collection::only` returns a subset of items with specific keys. 
`Request::only` Does the same thing — except when a key is not present it sets the value to null.

`Request:: intersect` behaves like `Collection::only`. While (according to the docs) `Collection::intersect` is the same as `Collection::only`.

I think it would make more sense to make `only` and `intersect` more consistent, changing `Collection::only` to behave more like `Request::only`, by adding `null` values. This would make `Collection::intersect` useful again.

Secondly, `Request::only` returns an `array` while `Collection::only` returns a `Collection` that can be chained. Would it be better to return a collection in both cases? If you need the request fields as an `array`, then you'd simply use `toArray`, which is more declarative.

Given a `$request` and `$collection` both have an input of:

```php
[
    'foo' => 123,
    'foobar' => 456,
]
```

**Example of current behaviour.**

```php
$allowedFields = ['foo', 'bar'];

$collectionOnly = $collection->only($allowedFields);
// returns Illuminate\Support\Collection with items:
// 'foo' => 123,

$requestCollection = $request->only($allowedFields);
// returns array with:
// 'foo' => 123,
// 'bar' => null
```

**Proposed change:**

```php
$allowedFields = ['foo', 'bar'];

$collectionOnly = $collection->only($allowedFields);
// returns Illuminate\Support\Collection with items:
// 'foo' => 123,
// 'bar' => null

$requestCollection = $request->only($allowedFields);
// returns Illuminate\Support\Collection with items:
// 'foo' => 123,
// 'bar' => null
```

**Comment by derekmd** [comment]
https://github.com/laravel/framework/pull/18695
