### ISSUE TITLE
A convenient way to upload file with extension

### ISSUE THREAD

**Issue by imam** [laravel/ideas#507]
Upload files functionality become common things to a web developer, but it seems that I can't find a way to store files to the storage with the extension in a convenient way. 

There feels like that it should be a method on the framework named like `storeAsWithExtension()`. It feels inconvenient to create this functionality where it feels like it should be in the framework by default. Or am I missing something?

**Comment by drbyte** [comment]
The [`storeAs` or `putFileAs`  methods](https://laravel.com/docs/5.4/filesystem#file-uploads) allow specifying a filename.

When you mentioned `extension`, were you talking about file extensions? What about file extensions are you finding problematic?

**Comment by imam** [comment]
I'm sorry if I wasn't clear.

Yes, I'm aware of the `storeAs` and the `putFileAs` methods, but none of them save the file name with the original file extensions. So we should always use this `$file->storeAs($targetDirectory,$filename.'.'.$file->getClientOriginalExtension())` to store file with custom file name but original file extensions. Which is not convenient.

I think the solution is to create new functions to `storeAs` like this:
- `storeAsWithExtension($targetDirectory,$fileName)`, output `$file->storeAs($targetDirectory,$fileName.'.'.$file->extension())`
- `storeAsWithClientOriginalExtension($targetDirectory,$fileName)`, output `$file->storeAs($targetDirectory,$fileName.'.'.$file->getClientOriginalExtension())`
