### ISSUE TITLE
[Suggestion][5.4] Blade @component without slot

### ISSUE THREAD

**Issue by arcanedev-maroc** [laravel/ideas#509]
I want to acheive something like this:

```blade
<!-- OPTION 1 -->
@component('_components/total-label', ['color' => 'danger'])
    {{ $paginator->total() }}
@endcomponent
```

```blade
<!-- OPTION 2 -->
@component('_components/total-label', ['total' => $paginator->total()])
```

```blade
<!-- /resources/views/_components/total-label.blade.php -->
<span class="label label-{{ $color or 'info' }}">
    {{ $slot or trans('general.total', compact('total')) }}
</span>
```

Is it possible to implement this feature to `5.4` ?

**cc:** @taylorotwell @themsaid

**Comment by sebastiandedeyne** [comment]
I'd really want this too, but I don't think this is possible for the Blade engine since this can't be achieved with plain regexing and replacing (it needs some sort of lookahead).

On the other hand, you can just use `include` for this (although it would be nicer to just have `component`).

**Comment by jordyvandomselaar** [comment]
They could just have `@component` return `@include`
