### ISSUE TITLE
[Proposal] Add contract for Middleware and others internal concepts ?

### ISSUE THREAD

**Issue by shulard** [laravel/ideas#510]
Hello !

I think it can be cleaner if the Middlewares uses an interface to define the `handle` method. Same remark is possible for Notifiable and newer concepts.

Most of the logic relied on a method which has a required name with a required list of parameters. This is an interface that must be followed to ensure code compatibility.

With that kind of structure, the internal object model will be more understandable and easy to use. I know that there are the `make:*` commands which generates the code but the contract layer is a really important thing in Laravel architecture and some concepts which miss its usage can take advantage of it.

**Comment by alberto-bottarini** [comment]
ViewComposers need a Contract to for their ```compose``` method

**Comment by shulard** [comment]
The #468 issue describe the same need too.
