### ISSUE TITLE
[Proposal] MINOR feature request: improved model stub

### ISSUE THREAD

**Issue by stevendesu** [laravel/ideas#511]
- Laravel Version: 5.4.0
- PHP Version: N/A
- Database Driver & Version: N/A

### Description:

Upon generating a new model in Laravel, a file like the following is created:

```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class MyModel extends Model
{
    //
}

```

This file does not make obvious the large number of `protected` members available. Nearly 100% of the time I find myself having to manually type:

```php
/**
 * The attributes that are mass assignable.
 *
 * @var array
 */
protected $fillable = [];
```

just to get started. It would make development faster and prevent simple bugs from accidentally mistyping these common attributes if the Model stub gave you a pre-commented list of available protected members when a model was first generated. Something like:

```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class MyModel extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable;

    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded;

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates;

    // ... (continue with all protected members)
}

```

I feel this would make Laravel a bit easier and faster to work with, and it would prevent simple mistakes like misspelling a protected member.

### Steps To Reproduce:

```
php artisan make:model MyModel
```

### Prior Discussion:

[This issue was originally opened on the Laravel/Framework repo](https://github.com/laravel/framework/issues/18617). To quote some comments from that original discussion and my thoughts on the matter:

>Best way would be to introduce an option into the make model command to include these attributes if desired. Eg. php artisan make:model MyModel --attrubutes
> -- @mrkatz

>If you need it for yourself, you can easily extend the MakeCommandConsole and override the stub method, but if the goal is to help new developers, then you're in a contradiction because they won't know about the optional parameter without reading the documentation and if they read the documentation, they don't need this at all.
> -- @deleugpn

I agree that it makes sense to have an attribute for controlling this behavior, as some people may not like to "clutter" their models with additional code. However @deleugpn's issue is easily resolved by simply flipping the meaning of the attribute. If by default these variables are appended but an attribute can remove them (e.g. `--clean`) then veteran Laravel practitioners who have memorized the documentation can do away with the cruft by simply appending `--clean` to their make:model statement while newbies are presented all of their options front and center.

There is, however, one point that may be made against this. That cluttering your code with variable declarations you aren't even using isn't "elegant". However I whole-heartedly **disagree** with the notion that elegant code _implies_ minimal code.

What makes code elegant, I feel, is the ability to skim through it and with no extra effort understand exactly what it's trying to accomplish. This is done more easily with **standards** than with **size**. There's nothing minimalist about every model beginning with `use Illuminate\Database\Eloquent\Model;
` - but because it's **always** present we know two things:

 1. If it's missing, this isn't a model
 2. If it's present, we can gloss over it and ignore the details

I don't believe extending the default model definition by 100 lines to include all available options would violate Laravel's principle of elegant code, at all. In fact -- I think it would make the code even **more** elegant, as you're explicitly stating which features you **don't** care to use.

**Comment by AkenRoberts** [comment]
I think this is a reasonable request, and fits in well with Laravel's developer-friendly nature.

My recommendation would be to generate a more full stub with attributes by default, and include a flag (`--clean` / `--no-attributes` / etc.) to skip them. It takes a lot less time to select some lines of code and hit delete than it does to add attributes manually.

Should be an easy PR if anyone has been considering contributing!
