### ISSUE TITLE
Notification customizable email address

### ISSUE THREAD

**Issue by a-komarev** [laravel/ideas#516]
- Laravel Version: 5.4.17
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7.17

### Description:

There is no way to define custom notification email address. Additionally to this `MailMessage` class [was changed at the end of 2016](https://github.com/laravel/framework/commit/ff68549) and doesn't have `to()` method anymore.

### Steps To Reproduce:

There are 2 use cases I can see so far.

#### 1. User doesn't have email yet

User primary email is empty until successful verification process. Notifiable model don't have email address yet, but we need to send verification email to start verification process.

#### 2. User has many email addresses and want to receive email on not a primary one

Notifiable model has 2 emails attached to it. Primary email is blocked, lost, hacked or unavailable for some other reasons. User trying to send password reset on a secondary email address which notification receives in constructor.

```php
public function __construct($token, $email)
{
    $this->token = $token;
    $this->email = $email;
}
```

**Possible solution №1:** Override notifiable email attribute.
```php
public function toMail($notifiable)
{
    $notifiable->email = $this->email;

    return (new MailMessage())
        ->subject('Reset your password')
        ->action('Reset Password', "/password/reset/{$this->token}");
}
```

**Possible solution №2:** Use old MailMessage class which still have `to()` method.
```php
public function toMail($notifiable)
{
    return (new MailMessageWithCustomRecipient())
        ->to($this->email)
        ->subject('Reset your password')
        ->action('Reset Password', "/password/reset/{$this->token}");
}
```

Both solutions were worked until I've tried to test sending emails using Queues :(

**Comment by a-komarev** [comment]
Both of these solutions aren't working because method `routeNotificationFor` of the class `\Illuminate\Notifications\RoutesNotifications` gets a new Notifiable instance is instantiated when notification sending is executed.

The working solution I found is add `routeNotificationForMail` method to `Notifiable` model:
```php
public function routeNotificationForMail()
{
    if ($email = request()->input('email')) {
        return $email;
    }

    return $this->email;
}
```

**Comment by a-komarev** [comment]
I've ended with more secure solution but which will require to have hidden input in template additionally:

```php
public function routeNotificationForMail()
{
    if (request()->has('email_override') && request()->has('email')) {
        return request()->input('email');
    }

    return $this->email;
}
```

**Comment by mahdyfo** [comment]
You can modify email address after saving user.

```
$user->save();

$user->email = "abc@example.com";
$user->notify(...);
```
This way the email in db will remain empty but notification works correctly.

**Comment by rsdrsd** [comment]
For empty emails it may work, but if you want to send to another email. You'd better make a dummy user class like this, where you can additional properties for the Notifiable:
```
<?php
namespace App\Models;

use Illuminate\Notifications\Notifiable;

class DummyUser {

    use Notifiable;

    public function __construct($user, $email)
    {
        $this->user= $user;
        $this->email = $email;
    }
}
```
If you want to send a notification for a certain user to a different email, you can do the following:
```
$differentEmail = 'mail@example.com';
$user = User::find(1);
$dummyUser = new DummyUser($user, $differentEmail);
$dummyUser->notify(....);
```
In the notification class, the $notifiable variable will consist a DummyUser instance, which holds the user and the new email.

**Comment by luwynne** [comment]
> * Laravel Version: 5.4.17
> * PHP Version: 7.1
> * Database Driver & Version: MySQL 5.7.17
> 
> ### Description:
> There is no way to define custom notification email address. Additionally to this `MailMessage` class [was changed at the end of 2016](https://github.com/laravel/framework/commit/ff68549) and doesn't have `to()` method anymore.
> 
> ### Steps To Reproduce:
> There are 2 use cases I can see so far.
> 
> #### 1. User doesn't have email yet
> User primary email is empty until successful verification process. Notifiable model don't have email address yet, but we need to send verification email to start verification process.
> 
> #### 2. User has many email addresses and want to receive email on not a primary one
> Notifiable model has 2 emails attached to it. Primary email is blocked, lost, hacked or unavailable for some other reasons. User trying to send password reset on a secondary email address which notification receives in constructor.
> 
> ```
> public function __construct($token, $email)
> {
>     $this->token = $token;
>     $this->email = $email;
> }
> ```
> 
> **Possible solution №1:** Override notifiable email attribute.
> 
> ```
> public function toMail($notifiable)
> {
>     $notifiable->email = $this->email;
> 
>     return (new MailMessage())
>         ->subject('Reset your password')
>         ->action('Reset Password', "/password/reset/{$this->token}");
> }
> ```
> 
> **Possible solution №2:** Use old MailMessage class which still have `to()` method.
> 
> ```
> public function toMail($notifiable)
> {
>     return (new MailMessageWithCustomRecipient())
>         ->to($this->email)
>         ->subject('Reset your password')
>         ->action('Reset Password', "/password/reset/{$this->token}");
> }
> ```
> 
> Both solutions were worked until I've tried to test sending emails using Queues :(

The to() method within the toMail function does not work
