### ISSUE TITLE
Simplification complex validation (inline)

### ISSUE THREAD

**Issue by projct1** [laravel/ideas#517]
How about do not transfer multi conditional rules into `sometimes` function?

Now this will not work properly, because second rule will trigger even if first rule is not pass:
```php
$rules = [
    'task.remind_at' => 'required_if:status.parent_id,25|before_or_equal:' . \Date::now()->add('10 days')
];
```
Now we have to out this rule into sometimes function like this:
```php
public function withValidator(Validator $validator)
{
    $validator->sometimes('task.remind_at', 'required|before_or_equal:' . \Date::now()->add('10 days'), function($data) {
        return $data->status['parent_id'] == 25;
    });
}
```
And i propose simplify this through adding some service word at first (like sometimes, bail), or replace `|` to `&`, for example:
```php
$rules = [
    'task.remind_at' => 'together|required_if:status.parent_id,25|before_or_equal:' . \Date::now()->add('10 days')
];
//or
$rules = [
    'task.remind_at' => 'required_if:status.parent_id,25&before_or_equal:' . \Date::now()->add('10 days')
];
```
In this case rule will trigger only if all rules are pass.

**Comment by Dylan-DPC** [comment]
> In this case rule will trigger only if all rules are pass.

Not sure what i'm missing, but doesn't that happen in normal validations as well?

**Comment by rorc** [comment]
@Dylan-DPC 

> Now this will not work properly, as second rule will trigger even if first rule is not pass:

**Comment by Dylan-DPC** [comment]
@rorc from the docs: 
> Sometimes you may wish to stop running validation rules on an attribute after the first validation failure. To do so, assign the bail rule to the attribute

**Comment by rorc** [comment]
@Dylan-DPC Does not work as I want :(
Even if i write `bail` at first `'task' => 'bail|required_if:parent_id,25|before_or_equal:some-date'` rule `before_or_equal` will trigger anyway if `parent_id is not equal 25`
