### ISSUE TITLE
[Proposal] Add additional parameter to Slack Notification to link user names and channels

### ISSUE THREAD

**Issue by sevenpixels** [laravel/ideas#523]
**link_names**
As it stands right now, if you send over `@channel` or `@username` or `#channel` it is just text. However, if you set this parameter to `1` it will then create a link. This is good in instances where you have notifications turned on in Slack. You get the alert in Slack and can check the channel it was posted in.

https://api.slack.com/docs/message-formatting

If you wanted to maintain the same way it works today, just default it to `0` and then when you call the method it sets the value to `1`.

https://gist.github.com/sevenpixels/9bccead7fb460653eac1c934beb472cd

**Comment by sevenpixels** [comment]
https://github.com/laravel/framework/pull/18765

**Comment by deleugpn** [comment]
Close?
