### ISSUE TITLE
Proposal: Namespace reserved variable names

### ISSUE THREAD

**Issue by benlipp** [laravel/ideas#527]
Blade has several reserved variable names that potentially interfere with existing variables. I propose that these be namespaced, to avoid naming conflicts.
`$loop`, `$message`, and `$errors` could all be prepended with an `_` to avoid name conflicts, or some other name could be used.

```
$_loop
$lara_loop
$l_loop
```
etc.

For reference, I am attaching [this issue.](https://github.com/laravel/framework/issues/18783)

**Comment by Garbee** [comment]
I don't think modifying the variables is necessary. Generic names are very common in templating engines.

What we should do though is have a list of reserved variable names used by Laravel. And when a new one is to be introduced try and give one release notice before it is added so people can migrate their codebases as they work without having immediate breakage if they don't.
