### ISSUE TITLE
[PROPOSAL] Nested implicit route bindings

### ISSUE THREAD

**Issue by LonnyX** [laravel/ideas#533]
Hello,

Who has never used the implicit route bindings?
How cool is to just specify the type and Laravel get you the model...

## The problem
When you want to combine this with the *nested resources*, it may loose its benefits.
Ex:
Let there be two orders made by two different users
- Post 1 has comment 1
- Post 2 has comment 2

We don't want to let members view a comment that is not associated with the specified post.
- /posts/1/comments/1 **(OK)**
- /posts/2/comments/2 **(OK)**
- /posts/1/comments/2 **(NOK)**
- /posts/2/comments/1 **(NOK)**

This is the current solution:
```php
Route::get('posts/{post}/comments/{comment}', function(App\Post $post, $commentID) {
    // as we need to check the post_id here, we can't use the implicit binding for Comment
    return $post->comments()->findOrFail($commentID);
});
```
Usually, we have to repeat this logic on `store()` `show()` `delete()` `update()` and even on custom methods

#### Repeat it 
Using `middleware` is a good workaround but why do we need to repeat this middleware for each resource on every project. 

#### Abstract it
With a quickfix on `Router` now you can easily make this:
```php
Route::get('posts/{post}/comments/{comment}', function(App\Post $post, App\Comment $comment) {
    // if this line is reached, we know that Comment belongs to Post
    return $comment
});
```

The only problem I see here, it's when someone doesn't follow the Laravel naming conventions and in this case we can simply return the ID of the model or an empty model if the type is specified.

**Comment by jrlawhorne** [comment]
How would the Router determine $comment belongsTo Post without touching the data store?  Or, you're suggesting it does touch the data store to determine this?

**Comment by LonnyX** [comment]
Yes, it is. The data store has to be touched. Something like this :

```php
$previousModel->{$model->getTable()}()->...->firstOrFail()
```

**Comment by jrlawhorne** [comment]
The Router is probably the wrong place to do this because Separation of Concerns.

**Comment by jrlawhorne** [comment]
Also, what if you want the implicit injection but don't want the requirement of the relationship - maybe you just want both objects without regard to relationship?

**Comment by arcanedev-maroc** [comment]
I use something similair but with explicit bindings :

```php
// Bindings
Route::bind('post', function ($id) {
    return Post::firstOrFail($id);
});

Route::bind('comment', function ($id, Illuminate\Routing\Route $route) {
    return $route->hasParameter('post')
        ? $route->parameter('post')->comments()->findOrFail($id)
        : Comment::firstOrFail($id);
});

// Routes
Route::get('posts/{post}/comments/{comment}', function (Post $post, Comment $comment) {
    // some logic
});
```

**Comment by LonnyX** [comment]
@jrlawhorne 
it's not the wrong place, it's on the same place as the actual one.
Give me ONE use case when you want this : /posts/1/comments/1  and you don't want relationship ?

@arcanedev-maroc yes something like this but more generic

**Comment by jrlawhorne** [comment]
Would the route pattern extend and require the relationship name in the route?

i.e. /modelA/idA/relationship-B-name/idB/relationship-C-name/idC ?

Could I add scopes?

i.e./modelA/idA/relationship-B-name/scopeOnB/idB ?

How much does the framework want to lean on conventions?  That's really what we're talking about, right?  You could imagine a comparison or suitability page between two objects that are not related but could be made related via user action.  One may want their route for that to be in the same format.  Of course, they could work around the default behavior in this case.  Or, one could work around the existing default behavior and the framework is less complicated for it.

**Comment by LonnyX** [comment]
@jrlawhorne Yes you are right, it can cause some troubles with scopes and others non trivial routes

But, what if this "Nested implicit bindings" can be activated on the routes declaration ?
i.e: 
```php
Route::get('posts/{post}/comments/{comment}')->nestedImplicitBinding();
```
The `nestedImplicitBinding()` method use the same logic as @arcanedev-maroc but abstracted for simpler use.

If you have scopes, you could just omit it and the classic binding will still be applied.

**Comment by jrlawhorne** [comment]
I'd support the option, but not the default.  At that point, you might leave out the implicit and just call it `nestedBinding()`.

Of course, as an option, adding it to the `Model` like a middleware would also be nice.  `$this->middleware('nestedbinding')`
