### ISSUE TITLE
Expect-CT Header?

### ISSUE THREAD

**Issue by m1guelpf** [laravel/ideas#534]
Maybe Laravel could integrate the new Expect-CT header for certificate transparency.
Details: http://httpwg.org/http-extensions/expect-ct.html

**Comment by tomschlick** [comment]
Here is another good post on Expect-CT: https://scotthelme.co.uk/a-new-security-header-expect-ct/

However, I think this should be delegated to a "security headers" package that includes HSTS/CT/Content Security Policy / Referrer policies.

**Comment by franzliedke** [comment]
Take a look at this package: https://github.com/aidantwoods/SecureHeaders

Version 2.0 is around the corner, and it will likely have an adapter for Symfony's HTTP Foundation. If not, it will be very simple to add.

**Comment by BePsvPT** [comment]
I have already created a package that may meet your needs, https://github.com/BePsvPT/secure-headers, hope this will help you.
