### ISSUE TITLE
[Proposal] Reactive computed model attributes and relations.

### ISSUE THREAD

**Issue by ajcastro** [laravel/ideas#535]
I read the vue docs. And I encountered the term "reactive". It is really good. For me, it means that, update or run computed attributes function if the dependencies are changed... I also think that it should be applied to laravel eloquent's accessors.. So that, if only dependencies(attributes) are changed, that's the only time the accessor will be executed, else, the model should return a cached value of the accessor, just like in vue's `computed` property. :slightly_smiling_face:

Maybe the syntax can be like this (you may suggest another better api):
```php
// Using the current accessor syntax, we will just add parameters 
// which will be the dependencies attributes
// By using ReflectionClass, eloquent model can determine 
// that this accessor depends on the birthdate attribute
public function getAgeAttribute($value, $birthdate)
{
  // birthdate can be also a carbon date instance when declared in getDates() method. 
  // for this example i will just use the string date.

  // The result of this accessor is cached.
  // Whenever the birthdate changes, the cache for age is destroyed,
  // and when no cache is found for age, it will evaluate this accessor,
  // then put it in cache again.
  return (new Carbon($birthdate))->diffInYears();
}

```
We can check if attribute is changed by checking if the newly set attribute is not equals (`!=`) to the existring attribute. Aside from this, we can also optionally create a method for determining if an attribute is changed. This is useful for non-scalar attributes, like carbon dates.
```php
public function isBirthdateChanged($oldBirthdate, $newBirthdate)
{
  // In this example, we demonstrate that a birthdate is a carbon instance.

  return $oldBirthdate->format('Y-m-d') != $newBirthdate->format('Y-m-d');
}
```

Some model dependency attributes are not found in the `protected $attributes`. So I think it's also useful for us to create a method to get a dependency attribute.:
```php
public function getBirthdateDependencyAttribute()
{
  // any code or logic where you can get the birthdate and return it.
}
```

**Comment by ajcastro** [comment]
It is also good, if we can easily make the model save (include in insert or update) some of its derived/computed attributes. Maybe like this (open for a better implementation):

```php
class User extends Model 
{
 protected $saveDerived = ['age'];  // or saveComputed, or what...
}
```

**Comment by sisve** [comment]
I'm not sure I understand. Do you want runtime reflection/parsing of model code to find all dependencies? If so, that will quickly get extremely complex, like if you access another accessor, access a field on a related object, etc. There's also performance issues of doing this at model load.

It would be easier to set the "observation system" into some kind of recording state, then call the accessor, and see what it accessed... except that this will miss observables that are accessed conditionally.

Can you perhaps provide a rudimentary implementation of this in a PR that can be discussed further?

**Comment by ajcastro** [comment]
Please wait for the PR. For now I've come up to a better and cleaner approach/api. This makes more sense, and easier to implement in the code. This is also applicable for computed relations. Computed attributes are cached on `$attributes`. Computed relations are cached on `$relations`. When dependencies attributes has changed, unset the cache e.g. `unset($this->attributes['age']);`. If cache exists, return it, else evaluate it, then cache and return it.

Syntax is `compute<Attribute>Attribute` or `compute<Relation>Relation`:
```php
public function computeAgeAttribute($birthdate)
{
  // return computed age
}
```
For dependencies is resolved first, from `$attributes`, next, from `$relations`, or, can be resolved by a method `get<Dependency>Dependency`:
```php
public function getBirthdateDependency()
{
}
```
If a computed attribute is declared in `$saveComputed = []`, it will also be saved.

**Comment by prohalexey** [comment]
$model->getDirty() + observers ?
