### ISSUE TITLE
Job-based retry delay?

### ISSUE THREAD

**Issue by trevorgehman** [laravel/ideas#537]
So currently I'm setting `$timeout` and `$tries` on the Job itself (rather than on the queue worker) which works great.

I'd also like to be able to do the same with `$delay`, so that I can set the time for a specific Job to wait before a retry is attempted. There is currently a `public $delay` on the `Illuminate\Bus\Queueable` trait, but that only affects the initial delay before the job is available, not the subsequent retries.

**Comment by SlyDave** [comment]
I'd go further with this and ask for the ability to separate the initial job delay from the retry delay.

I have need to delay the start of a job by x, then if that job fails, wait y before trying again.

**Comment by benyanke** [comment]
This really needs to happen. It's crazy to let a queue job run and run again if something external going down causes the fail.

For example, if your mail server goes down for 10 seconds, and laravel runs 100 retries in 10 seconds, the job will fail, whereas if it would have waited even just a second or two before retrying, it would have gone through just fine the moment the server came up.

**Comment by torkiljohnsen** [comment]
If you have special requirements for certain types of jobs, you can do different things. Adding these certain jobs to a queue of their own could be an option:

For instance, retry every hour for three days:

`php artisan queue:work --queue=mailables --delay=3600 --tries=72`

Dispatch to mailables:
´Job::dispatch()->onQueue('mailables');´

Or you can set `$tries = 72;` on the job itself, and then release the job manually, something like this perhaps:

```php
public function handle()
{
    try {
        // Do stuff that might fail
    } catch(Exception $e) {
        if ($this->attempts() < $this->tries) {
            $this->release(3600);
        } else {
			throw $e;
        }
    }
}
```

Lifted that last part from here: https://stackoverflow.com/questions/35258175/how-can-i-create-delays-between-failed-queued-job-attempts-in-laravel

**Comment by neoteknic** [comment]
It should be something like --retry-delay=10,300,3600 (if tries= 3 or more)
For example : If a job fail, retry after 10 sec (because of a server restart), if it fail again retry in 5min (minor server problem), if fail retries every 1 hour (serious server problem!).
Like this it will be perfect !

**Comment by peterchrjoergensen** [comment]
I just ran into a case where I would have liked to do this.

E.g. if an external API fails, one should be able to specify on the job to try again after a set time.

**Comment by trevorgehman** [comment]
> For instance, retry every hour for three days:
> 
> `php artisan queue:work --queue=mailables --delay=3600 --tries=72`

Indeed this will work. And it's the best solution for mailables in particular. That's because when the job fails, it will place it back onto the queue, taking into account the `--delay` set on the worker:

https://github.com/laravel/framework/blob/db89f541bb26b071a6f3666daefb541f72651b5f/src/Illuminate/Queue/Worker.php#L366-L371

The issue is, it doesn't take into account a delay if it is set on the Job itself, which I think it should and [pointed out here](https://github.com/laravel/framework/pull/25101#issuecomment-445318210).

> Or you can set `$tries = 72;` on the job itself, and then release the job manually, something like this perhaps:
> 
> ```
> public $tries = 72;
> 
> public function handle()
> {
>     try {
>         // Do stuff that might fail
>     } catch(Exception $e) {
>         if ($this->attempts() < $this->tries) {
>             $this->release(3600);
>         } else {
> 			throw $e;
>         }
>     }
> }
> ```
> 
> Lifted that last part from here: https://stackoverflow.com/questions/35258175/how-can-i-create-delays-between-failed-queued-job-attempts-in-laravel

This solution requires wrapping the entire handle method in a try-catch block, which I think isn't a good solution, but I've done this in the past as a workaround.

**Comment by tim-hanssen** [comment]
Is it possible to set the --delay setting from the Horizon config? Since Horizon is running the workers i'm not able to set the setting on the superv. config.

**Comment by taylorotwell** [comment]
I would be perfectly fine with a PR to accomplish this if someone wants to work one up.

**Comment by jaymoh** [comment]
@tim-hanssen hey, did you find a solution to this behavior when running the workers with horizon?
