### ISSUE TITLE
vendor/illuminate/database/Eloquent/Builder.php will support except method ?

### ISSUE THREAD

**Issue by yanyandenuonuo** [laravel/ideas#538]
I want use except method to define the fields which I didn't select in each select. Now, I can only use get(['field_1', 'field_2', 'field_3', 'field_4', ...]). If I had 10 fields and I just want select 9 of those, I need to write 9, but if support except method, I just need to write 1
example:
$this->where($filter)->except(["the filed which I didn't want "])->toArray();
$this->where($filter)->get(["the filed which I want"])->toArray();

**Comment by michaeldyrynda** [comment]
The model doesn't know about the fields, though so it would have to `select *` first, then filter the resulting collection.

You could easily implement this in your application in a base model you extend from. I wouldn't suggest including it in the framework unless there's a more efficient way of getting the fields. Something like the following, perhaps:

```php
<?php

namespace App;

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Eloquent\Model as BaseModel;

class Model extends BaseModel
{
    protected function except($columns = [])
    {
        $columns = is_array($columns) ? $columns : func_get_args();

        $query = $this->newQuery();

        tap(Schema::getColumnListing($this->getTable()), function ($modelFields) use ($query, $columns) {
            $query->select(array_diff($modelFields, $columns));
        });

        return $query;
    }
}
```

This way, you're going to have to execute two queries - one to fetch the columns (`Schema::getColumnListing`) and one that will actually run the query. The only other way to avoid the duplicate query is to define the columns on the model itself but that then means you have to remember to update it when you add new columns to your database 🤢

**Comment by alexweissman** [comment]
Is the multiple-query approach (get the column names, then run a `select` with those names) necessarily less efficient than traversing the fetched collection and removing the values?  Would be good to get some benchmarking on this.

**Comment by alexweissman** [comment]
If anyone is interested, I've implemented this by extending the `Query\Builder` class, implementing the `exclude` method and overriding the base `get` method. See https://github.com/userfrosting/UserFrosting/blob/67f846a76ce4c3a7ad92f6c7f215535bab123285/app/sprinkles/core/src/Database/Builder.php#L84-L209

Not sure if this would be appropriate as a PR to Laravel; we have a few integration tests but no unit tests for these methods: https://github.com/userfrosting/UserFrosting/blob/67f846a76ce4c3a7ad92f6c7f215535bab123285/app/sprinkles/core/tests/Integration/DatabaseTests.php#L658-L774
