### ISSUE TITLE
Use variable in route group prefix

### ISSUE THREAD

**Issue by erfansahaf** [laravel/ideas#539]
I tried to set a Config Variable to Route Group Prefix  instead of a String just like this (L 5.4):
```php
Route::group(['prefix' => config('custom.admin_path') , 'namespace' => 'Admin'], function(){
        Route::get('/login', 'AdminAuthController@Login')->name('login');
        Route::post('/login', 'AdminAuthController@Authenticate');
});
```
But in POST routes in the group, there is a problem. When the form has submitted the error **TokenMismatchException** is shown. I used this way to route my requests in Laravel 5.2 but there wasn't any problem.
Is it Laravel bug? My Project is fresh without any complicated codes.

**Comment by sebastiandedeyne** [comment]
This should work. Does your form hava a CSRF token?

**Comment by erfansahaf** [comment]
Yes, it does. I used {{ csrf_field() }} to put csrf input in my form.
Did you use this way to route requests?

**Comment by sebastiandedeyne** [comment]
All of our routes are contained in a variable prefix, the locale. We've never experienced token mismatches due to this.

**Comment by erfansahaf** [comment]
But I have! It is so strange.
I have no routes except this group.

**Comment by sede2** [comment]
I've tested this on a fresh install and works fine 

`Route::group(['prefix' => config('app.locale')], function(){
	Route::get('/', function(){return view('welcome');});
	Route::post('/', function(){return 'ok';})->name('form');
});`

On the welcome view I have a form:
`
<form method="post" action="{{ route('form') }}">
        {{ csrf_field() }}
        <button>ok</button>
</form>
`

**Comment by erfansahaf** [comment]
Maybe the problem was made by Namespace.
I have AdminAuthController.php inside controllers/Admin/ folder.
Route:
`Route::group(['prefix' => config('system.ADMIN_PATH'), 'namespace' => 'Admin'], function(){\n
        Route::get('/login', 'AdminAuthController@Login')->name('login');\n
        Route::post('/login', 'AdminAuthController@Authenticate')->name('check');\n
    });`
