### ISSUE TITLE
Collection->except fails on single element array

### ISSUE THREAD

**Issue by infernobass7** [laravel/ideas#540]
I recently came across an error where if you pass an array of size one to collection's except it would pass the array all the way down to the Arr::exists methods as an array, causing an error to be thrown by array_key_exists(), stating that the first argument of array_key_exist should be either a string or integer.

**Comment by Dylan-DPC** [comment]
@infernobass7 Steps to reproduce?

**Comment by infernobass7** [comment]
I had grabbed a list of ids from a model's relationship.
```
$model1List->except($model2->model1Relations)->random()
```
