### ISSUE TITLE
Prefix mix scripts in package.json

### ISSUE THREAD

**Issue by deframe** [laravel/ideas#549]
Perhaps it makes sense to prefix the current Mix-specific scripts in Laravel's default package.json?

    "scripts": {
        "mix:dev": "node node_modules/cross-env/dist/bin/cross-env.js ...",
        "mix:watch": "node node_modules/cross-env/dist/bin/cross-env.js ...",
        "mix:watch-poll": "node node_modules/cross-env/dist/bin/cross-env.js ...",
        "mix:hot": "node node_modules/cross-env/bin/dist/cross-env.js ...",
        "mix:production": "node node_modules/cross-env/dist/bin/cross-env.js .."
    }

Just calling these scripts 'dev', 'watch', etc, doesn't make a great deal of sense contextually, especially if the user has defined additional scripts.

**Comment by m1guelpf** [comment]
@deframe This would be politically correct, but it would be a **very** breaking change. Imagine `artisan migrate` & `artisan serve` would be renamed to artisan `laravel:migrate` & `artisan laravel:merge`

**Comment by barryvdh** [comment]
laravel/laravel is just the starter repo, so users don't usually update that. 
But if a command conflicts, they can rename the commands without problem right? Or are the commands used anywhere by Laravel?

**Comment by deframe** [comment]
@m1guelpf It would only break automated calls to those commands, e.g. via deployment scripts & maybe some test suites. Beyond that it's not a big stretch asking users to run `npm run mix:dev` instead of `npm run dev`, especially in a bigger BC-breaking point release like 5.5.

**Comment by Garbee** [comment]
This wouldn't be a breaking change at all. Unless people try to auto-merge changes to `laravel/laravel` to their app. But if you're doing that you have bigger problems.

However it is entirely unnecessary. If developers don't like the script names, they can just rename them in their app. Nothing will be broken internally.

We need to remember `laravel/laravel` is for the app-level starter. It isn't meant to be auto-updated nor left in un-modified ways. You're encouraged to modify it to fit your projects needs.

**Comment by sisve** [comment]
Changing this would also break all existing tutorials.

If the commands are prefixed, keep supporting the old commands in some way. I would prefer if they tell the user that the command is obsoleted and they should start using the new command, and have this message present for a release.

Relevant: https://github.com/laravel/internals/issues/383
