### ISSUE TITLE
[Proposal] option to declare observer in the model itself?

### ISSUE THREAD

**Issue by boynet** [laravel/ideas#551]
I have some big website with many models and most models also have an event observer

And I am afraid of the performance penalty of this observers as it's basically loading all this observers on each laravel boot so the performance is loading multiple maybe unnecessary files  + multiple method_exists calls ([the method](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php#L33))

maybe I am over thinking here does it good idea to add an option to declare the observer in the model itself? like 
```
class User extends Authenticatable
{
    protected $observer = UserObserver::class;
}
```

that's way the observer will only load when the model loaded

**Comment by kszyrvercobrador** [comment]
Actually, you can do this,

`public static function boot() {
    parent::boot();
    SalesOrderDetail::observe(new SalesOrderDetailObserver());
}`

Register your Observer when on the model boot function.
In this way the Observer only load when the model loaded.

**Comment by brayniverse** [comment]
I think you can also use a trait which will auto register on the model of you provide a method on the trait that follows the following convention boot[TraitName].

I.e

```php
trait Observable
{
    public function bootObservableTrait()
    {
        if (isset($this->observer)) {
            static::observe($this->observer);
        }
    }
}
```
```php
class User extends Model
{
    use Observable;

    protected $observer = User observer::class;
}
```

**Comment by boynet** [comment]
thanks good idea

> Also, have you tried measuring the impact of registering an observer? Is the show down noticable?

didnt test it, I know I should but from the beginning it doesn't feel right for me to load this 20 observers in every request

**Comment by salarmehr** [comment]
@boynet Yes, I agree with you and with https://laracasts.com/discuss/channels/laravel/l51-event-listener-gets-instance-of-model-instead-of-event-itself?page=1 question owner, 

The way that event are handled in the model is over smart! and it can far easier. 

This is the way that events are handled in the Phalcon framework elegantly., 

use Phalcon\Mvc\Model;

```
class Products extends Model
{
    public function beforeCreate()
    {
        // Set the creation date
        $this->created_at = date('Y-m-d H:i:s');
    }

    public function beforeUpdate()
    {
        // Set the modification date
        $this->modified_in = date('Y-m-d H:i:s');
    }
}
```

**Comment by robjbrain** [comment]
Just another thought on doing this, since this issue is the top result on Google for registering the observer on the model.

I declare the model on the observer itself using an $observes property. Then loop through my observers directory in a service provider to auto register each observer.

```php
        $path = app_path('observers');
        foreach (glob($path . '/*.php') as $file) {
            $observer_class = $this->getClassName($file);

            foreach($observer_class::$observes as $model_class) {
                call_user_func_array([$model_class, 'observe'], [$observer_class]);
            }
        }
```


```php
namespace App\Observers;

use App\User;

class UsersObserver
{
    public static $observes = [
        User::class
    ];

    public function saving(User $user)
    {
        // do something
    }
}
```

**Comment by AntoineDewaele** [comment]
I submit a new issue about this topic one week ago (https://github.com/laravel/ideas/issues/2612), didn't see this one.
The implementation is almost the same as @wimurk (I prefer the way he deals with class name btw)

`EventServiceProvider.php`
```php

public function bootObservers()
{
    $files = Finder::create()->files()->in(app_path() . '/Api/Core/Models');
    foreach ($files as $file) {
        $className = str_replace('/', '\\', str_replace('.php', '', $file->getRelativepathname()));
        $observerClassName = "App\\Api\\Core\\Observers\\".$className.'Observer';
        if (class_exists($observerClassName)) {
            $class = "App\\Api\\Core\\Models\\".$className;
            $class::observe($observerClassName);
        }
    }
}
```
