### ISSUE TITLE
Docblocks and code style problems.

### ISSUE THREAD

**Issue by prohalexey** [laravel/ideas#554]
- Laravel Version: 5.4

### Description:

Hello! I was made review for some files(1/10) of **laravel/framework** repository. 
I found what many function has outdated or broken docblocks like **@throw** properties what are absent. 
Functions can throw up to 5 or even more different exceptions, but there is no records about it. 
In some functions variables wait an object what implements an interface, and later you call functions on these objects what does not exist in this interface. 

Another problem is "return null" problem.
By default if return statement doesn't exists in a function, return value is null, but in a function docblock 
 we can see **@return void**. Or  in a function docblock **@return string|null** but code is like this:
```
/** 
* @return void
*/
public function something1()
{
     return;
}

/** 
* @return string|null
*/
public function something2($str)
{
    return $this->something1($str);
}
```

What we can do with this ?

### Steps To Reproduce:

Look at this commit: https://github.com/prohalexey/framework/commit/6a80c56ea2a4fa885f5d19188e02666fcb05c3a5

**Comment by Garbee** [comment]
`null` is not actually returned from empty methods or a `return;` statement. Nothing is returned really but when you try to assign it it becomes `null` then since there is no `void` thing in PHP.

As far as the docblocks go, PR away as you see problems. There's not much to really discuss with these. Just as you notice issues PR them and use the FQCN in the docblock for any statements.

**Comment by prohalexey** [comment]
I want to show what docs and code are different. Null and void are for a sample. But in the future(for PHP 7.1), this work needs to be done.

You can read this: https://wiki.php.net/rfc/void_return_type
```
function returns_null(): void {
    return null; // Fatal error: A void function must not return a value
}
```

There is an other problems. Throws and call functions what are not implemented in interfaces.

**Comment by michaeldyrynda** [comment]
The idea behind the `@return void` is to indicate that you shouldn't expect or rely on any return value from the method. PHP hasn't historically - but now does PHP 7.1 - supported the notion of void, though, so the docblock annotation is used as a stopgap.
