### ISSUE TITLE
->first()->first() gives surprising result

### ISSUE THREAD

**Issue by jonashaag** [laravel/ideas#557]
This is something I just hit. Due to a misuse of the Eloquent API, I called something along the lines of `X::where(...)->first()->first()`. This gives as result the first `X` object in the database. I'm not sure if the `first()` method needs to be available on a model instance? What does it mean to get the `first()` item of a model instance on the first place?

To reproduce:

```
var_dump(X::where("id", 2)->first()->first()->id);
int 1
```

Expected: "Error, unknown method `first()`"

**Comment by Garbee** [comment]
This is a tricky bit of the way Eloquent works. It actually is working as intended.

First you're getting a *Model* with the ID of 2. Then, on that, you're calling `first()` again. This will create a new, clean query and then  execute it. Which will then return the first item in the DB. In this case the one with an ID of 1.

**Comment by jonashaag** [comment]
Why would you allow queries on model instances in the first place? How does that even make sense?

**Comment by Garbee** [comment]
That's how the active record pattern works. If you don't like it then data
mappers like doctrine exist or you can use raw SQL. It's not something that
can't​ be changed as applications heavily expect this behavior to work as
it is.

**Comment by jonashaag** [comment]
Sorry, maybe my question wasn't clear enough. I wonder why the `first()` method is available on *instances*, i.e. as non-static methods? As an example, I feel like this makes sense:

```
X::where(...)
```

but this doesn't:

```
(new X())->where(...)
```

**Comment by Garbee** [comment]
Consistency and allowing people to be as concise as they want with code most likely.

**Comment by jonashaag** [comment]
I just realised the issue I'm having here is probably simply a side effect from how "static" methods are implemented for model objects, i.e.

```
X::foo()  ->  (new X)->foo()
```

Do you know of any examples where the query methods being available on model instances makes code more consistent or more concise? For safety reasons, wouldn't it be smarter to require an explicit `->newQuery()` in these cases? (I guess it's used rather uncommonly.)

**Comment by Garbee** [comment]
Consistency, well you're hitting it. `X::first()` is equivalent to `(new X)->first()`. So developers don't need to consider what mode their in to use the API. (For better or worse.)

Conciseness is because, `(new X)->first()` is simpler to write and look at than, `(new X)->newQuery()->first()`. Developers don't need to remember what they're able to use in different contexts and how. Once again, for better or worse.

We can debate about safety all day and get nowhere.

Look, I am someone who likes more strictness as well. That's why I use PHPStan to help me out in making sure everything is done as well as I can. That doesn't mean however that the framework should bend to my likeness. We can get what we want with proper tooling checking over our code.

**Comment by jonashaag** [comment]
> We can debate about safety all day and get nowhere.

Or we can start designing APIs that are hard to misuse :-)

Sorry for bothering you with this. Do you know where I can find examples of people actually using query methods on model instances? I.e. the other "mode" (non-static) you talked about?

**Comment by Garbee** [comment]
Anyone injecting models and not calling `newQuery` on things for starters. There is no way to accurately know what all is even using Laravel much less in what way.

> Or we can start designing APIs that are hard to misuse :-)

I get this completely. However, Taylor has proven time and time again he'd rather have an API that is developer-friendly over hard to misuse.

**Comment by jonashaag** [comment]
> Anyone injecting models and not calling `newQuery` on things for starters.

I see... that's a very good example, and unfortunately that's actually a PHP limitation because in PHP classes aren't first-class objects.

**Comment by Dylan-DPC** [comment]
Also note that the second `first()` migh be calling the collection `first` method

**Comment by Garbee** [comment]
@Dylan-DPC It absolutely is **not** in this case. Because there is only *one* item being returned from the query, so it is a general model and not a collection.
