### ISSUE TITLE
public_path helper hardcoded to 'public'

### ISSUE THREAD

**Issue by snapey** [laravel/ideas#558]
It should be possible to change the target for public_path helper.

Application.php contains hardcoded 'public'

    public function publicPath()
    {
        return $this->basePath.DIRECTORY_SEPARATOR.'public';
    }

This should come from config for people that have the name of their public folder mandated by the service provider.

**Comment by arcanedev-maroc** [comment]
The workaround about this is to create a custom `Application` class, something like: 

* https://github.com/ARCANESOFT/ARCANESOFT/blob/master/app/Application.php#L11-L26
* https://github.com/ARCANESOFT/ARCANESOFT/blob/master/bootstrap/app.php#L7

**Comment by laurencei** [comment]
You can override the public path in your service provider already:

```
App::bind('path.public', function() {
    return base_path().'/public_html';
});
```

**Comment by snapey** [comment]
The problem of a hardcoded value is that it affects those least experienced since they are probably the ones using shared hosting and have no control over the document root.  The solution therefore needs to be simple to implement.

**Comment by arcanedev-maroc** [comment]
So, you want to bring back something like [this](https://github.com/laravel/laravel/blob/v4.2.0/bootstrap/paths.php) ?

**Comment by snapey** [comment]
Maybe, but with .env support ?
