### ISSUE TITLE
Composer installtion problem

### ISSUE THREAD

**Issue by uengineer01** [laravel/ideas#559]
getcomposer.org is not operational i am looking for alternatives to complete project. Can any body tell me what is the alternative of composer.

**Comment by laurencei** [comment]
The website is working for me?

**Comment by deleugpn** [comment]
It may be a dumb assumption from my side, but I think, I THINK, if the most important package tool in the PHP Community were down, the internet would know.

**Comment by franzliedke** [comment]
I don't think this is the right place for support with Composer installation / usage troubles. Please close this ticket.

**Comment by Dylan-DPC** [comment]
@uengineer01 kindly close the issue :) thanks
