### ISSUE TITLE
Pause queues when using Redis (and perhaps others)

### ISSUE THREAD

**Issue by omanizer** [laravel/ideas#561]
I used to use Beanstalk for queues however I switched as AWS Elasticache offered easy Redis redundancy, and since I was already using Redis for my cache, why not also use it for queues and have one less server in my cloud setup? TL:DR; I'm using Redis for Queues.

I have an auto-scaling group of queue worker instances that increases as number of tasks in the queue grows. Typically there are 2 worker instances scaling up from there. I usually process about 5M jobs per day, many of them transactional HTTP requests, DB aggregation tasks, etc. Suffice it to say that it's very difficult (if not impossible) to quickly pause or stop all of these workers in the event of an emergency (a customer needing to cancel a message they just sent to 500k people or...though this would never ever happen...some bad code was pushed).

Beanstalk has a nice feature of being able to pause a queue (tube) and it just stops making jobs available. Unfortunately Redis doesn't have the same ability. I'm guessing that if I have this problem it's likely somebody else has it as well, so either there's something I'm not seeing or there's an opportunity for me to contribute, which has thinking how this could actually happen. I see a couple possible solutions:

1) Implement a flag inside of Redis that a queue worker checks before requesting a job. If that flag says the queue is currently paused, the worker would go to sleep as if there were no jobs in the queue and try again after that interval.
2) It appears that when I call php artisan queue:restart it adds a flag that workers on all other instances listen to. If there were some sort of "stop" flag that worked the same way... Being that all my workers are backed up by Supervisor, it would be difficult to actually stop them unless Supervisor listens to a specific type of Kill signal. Haven't researched this option much, and frankly it's starting to sound a lot like (1) if Supervisor doesn't respond this way.

So, would it be a logical thing to have every worker check a flag (in redis only) to determine if a queue has been paused?

It would be very easy to modify Illuminate\Queue\RedisQueue::pop to check for a "pause" flag within Redis and return null if such a flag exists.

**Comment by sisve** [comment]
Just for clarification, are you talking about ...
1. pausing a single queue,
2. pausing a single queue worker,
3. or pausing all queue workers?

**Comment by omanizer** [comment]
#1 or #3 would be solutions to this.  #1 is more what I am referring to however.

As mentioned, Beanstalk has a built-in way to do #1.

Being that I'm running over 200 worker processes on sometimes 12 different instances it makes it quite difficult to connect to every server and take supervisor down in a short time.

As you mentioned with #3 though, it would fulfill this need to have something like a `php artisan down` specifically for queue workers...  I an see how this could work with Redis being that there is a shared cache, but how that would work with something like Beanstalk and multiple worker instances without shared communication through a DB or something beats me, but it's an interesting concept.

**Comment by taylorotwell** [comment]
Can be done. USR1 and SIGCONT signals.

**Comment by sisve** [comment]
@taylorotwell This cannot currently be done. Sending those signals will pause the targeted _queue worker_, not the queue. There could be several queue workers processing the same queue, and a queue worker could be handling several queues.
