### ISSUE TITLE
Add method `inputOrFail()` in Http Request.

### ISSUE THREAD

**Issue by ajcastro** [laravel/ideas#562]
I think this is useful and handy.

`inputOrFail($key, $statusCode = 400)`

Sample usage:
```
$request->inputOrFail('some_required_query_param', 400);
$request->inputOrFail('some_required_query_param', 422);
```

**Comment by alberto-bottarini** [comment]
Why can't you use validator?

**Comment by ajcastro** [comment]
I know I can do this with validator but this is quicker to use.

**Comment by alberto-bottarini** [comment]
It's quicker if you only to need validate the presence of request parameter. If you need more validation rules, inputOrFail becomes useless

**Comment by ajcastro** [comment]
Yeah, that's why "there are times" inputOrFail() is preferable.. because there are times you just need to validate the presence of a query parameter.

**Comment by calebporzio** [comment]
I don't know how I feel about the usage. But I can definitely see where this would be really nice to have.

Cool idea!
