### ISSUE TITLE
Mailables as Listeners

### ISSUE THREAD

**Issue by benswinburne** [laravel/ideas#564]
Perhaps I'm implementing this wrongly in my app, but it seems that whilst event listeners and mailable can implement `Illuminate\Contracts\Queue\ShouldQueue` I appear to have to listen for the event with a listener which then fires and generates the Mailable.

Either can be queued so does it make sense that I can just make Mailable a listener for an event and queue it directly from there?

**Comment by Kyslik** [comment]
You make mailable that implements ShouldQueue and just hit send method on mailer class.

**Comment by themsaid** [comment]
Mailer needs to know to whom it shall send the email, if you add it as a listener how would you configure that?

**Comment by benswinburne** [comment]
Take for example the following

    // ContactController.php
    // public function post() [abridged]
    $data = $request->except('_token');
    $mailer->to($request->input('email'))->send(new ThanksForContacting($data));
    $mailer->send(...); // second email
    $mailer->send(...); // third email
    event(new ContactSubmission($data);

This sends 3 emails and clutters up the controller for something which is firing an event just after. 

Take for example one with a event -> listener -> mailable

    // App/Listeners/Registration/SendEmail.php;
    public function handle(Registered $event)
    {
        $this->mail->to($event->user->email)->send(
            new ThanksForRegistering($event->user)
        );
    }

    // ThanksForRegistering is a mailable

This just seems like an unnecessary step if we could make Mailables event listeners?

**Comment by themsaid** [comment]
Check http://themsaid.com/laravel-mailables-notfiications-as-event-listeners-20170516/
