### ISSUE TITLE
New toCsv method on Collection class

### ISSUE THREAD

**Issue by Modelizer** [laravel/ideas#573]
Convert a given array into CSV format example:

```php
echo collect([
   ['title', 'description'],
   ['hello world', 'lorm ipsom'],
])->toCsv();
``` 
will give us

```php
title,description
hello world, lorm ipsom
```

**Comment by Dylan-DPC** [comment]
And how would you convert a JSON column or something cast into an array?

**Comment by joshmanders** [comment]
@Dylan-DPC convert it to a json string?

**Comment by joshmanders** [comment]
Honestly, I'd rather see this:

```php
$collection = collect($users); // array of User models.

echo $collection->toCsv(['name', 'email', 'created_at']);
```

Which produces:

```
name,email,created_at
John Doe,john.doe@example.com,2017-05-08 00:00:00
Jane Doe,jane.doe@example.com,2017-05-08 00:00:00
```

If one of the columns has a `toString` method on it, call it, or `toJson` call that and stringify it, etc.

**Comment by drbyte** [comment]
Just a reminder that there are a few "escaping" rules relevant to CSV output: https://tools.ietf.org/html/rfc4180

Perhaps consider integrating/extending https://github.com/usmanhalalit/laracsv ... which uses `league/csv` under the hood.

**Comment by Modelizer** [comment]
@Dylan-DPC give a practical example for your question.

@joshmanders adding `['name', 'email', 'created_at']` is just a column which can be merge in collection and then convert it to csv. This way we can minimize params in `toCsv` method.

**Comment by Dylan-DPC** [comment]
Practical example? A lot of people use JSON structures

**Comment by Modelizer** [comment]
first you need to do json decode then pass it to collection and then convert it into csv.

**Comment by joshmanders** [comment]
@Modelizer By adding the column headers to the function it allows you to do things with the collection before you decide to cast to CSV.

If I had them as part of the collection, I can't filter and map over the collection before calling `toCsv()` on it.

Plus I don't think CSV dependent things should be in the collection before it's cast to CSV.
