### ISSUE TITLE
Update multiple rows with different update values feature request

### ISSUE THREAD

**Issue by knieber** [laravel/ideas#575]
This could be a great addition for the Query Builder API. There really isn't a way to update multiple rows with different update values with the current api. Here's the example use case:

**Dataset**
```php
[ 
    [ 'id' => 1, 'name' => 'Jeff' ],
    [ 'id' => 2, 'name' => 'Mark' ],
    [ 'id' => 3, 'name' => 'Jim' ],
]
```

Currently with Query Builder, you'd have to update each of these records separately by looping over an update call like so:

```php
DB::table('users')
    ->where('id', $array['id'])
    ->update(['name' => $array['name'])
```

This can be problematic if you're looping through many records (obviously). It'd be handy if the Query Builder had an api to handle such a use case in one query. Here is an example solution I implemented for updating `display_indexes` in my project:

```php
public function updateDisplayIndex(array $values)
{
    $caseString = 'case id';
    $ids = '';
    foreach ($values as $value) {
        $id = $value['id'];
        $displayIndex = $value['display_index'];
        $caseString .= " when $id then $displayIndex";
        $ids .= " $id,";
    }
    $ids = trim($ids, ',');

    DB::update("update products set display_index = $caseString end where id in ($ids)");
}
```

(this is obviously a sloppy and very inflexible solution, but it's merely an example)

I'll be glad to fully code the solution and create a PR if you feel this would be a valuable and acceptable feature for the Query Builder API.

Thanks!

**Comment by weklund** [comment]
+1

**Comment by sisve** [comment]
The best way to get response for something like this would probably be to write that PR.

**Comment by barryvdh** [comment]
This would usually only work for updating the same columns for all models right? And doesn't account for casting etc. But I've tested this with a simple id => value array, based on the example from @knieber, which gives me a 13x boost, when updating 1000 rows (vs updating each model with `update(['value'=>''])`

```php
public static function updateValues(array $values)
{
    $table = MyModel::getModel()->getTable();

    $cases = [];
    $ids = [];
    $params = [];

    foreach ($values as $id => $value) {
        $id = (int) $id;
        $cases[] = "WHEN {$id} then ?";
        $params[] = $value;
        $ids[] = $id;
    }

    $ids = implode(',', $ids);
    $cases = implode(' ', $cases);
    $params[] = Carbon::now();

    return \DB::update("UPDATE `{$table}` SET `value` = CASE `id` {$cases} END, `updated_at` = ? WHERE `id` in ({$ids})", $params);
}
```

But that is skipping some logic that `update` does (like parameterizing all ids instead of casting to int) etc. Still gives quit a boost for a specific use-case.

**Comment by knieber** [comment]
@barryvdh You're correct that it would only be for updating the same columns for all models. However, I only spent a small amount of time trying to come up with a solution for my use-case and there could be a more dynamic solution.

I hadn't tested the performance gain yet, and it's encouraging to hear your found a 13x boost! I'll try to put some time in today/tonight and link a PR to this issue. I appreciate the feedback.

**Comment by mavinoo** [comment]
update batch (bulk) laravel
https://github.com/mavinoo/updateBatch

**Comment by cossay** [comment]
For anyone looking for a solution that has no dependency on the laravel, here's one: https://github.com/cossay/bulk-update-query-writer .
It uses the same logic as @mavinoo with a few exceptions:
1. It escapes values using PDO
2. it returns the generated query as a string
3. Accepts additional conditions
4. it can be used anywhere since it doesn't depend on any laravel specific features.

**Comment by fgilio** [comment]
I really think some shape of this should be part of the framework

**Comment by piyush1104** [comment]
So, did it get included in the framework or not?

**Comment by staudenmeir** [comment]
@piyush1104 No, it didn't.

**Comment by marchershey** [comment]
Might want to fix the error in this code:

``` php
DB::table('users')
    ->where('id', $array['id'])
    ->update(['name' => $array['name']) <-- Missing closing bracket
```

**FIX:**
``` php
DB::table('users')
    ->where('id', $array['id'])
    ->update(['name' => $array['name']])
```

**Comment by progdaif** [comment]
I wrote a version to update multiple columns for multiple records based on @barryvdh code:

public function updateMultiple(array $values)
    {
        $table = $this->model()::getModel()->getTable();;
        $ids = [];
        $params = [];
        $columnsGroups = [];
        $queryStart = "UPDATE `{$table}` SET";
        $columnsNames  = array_keys(array_values($values)[0]);
        foreach ($columnsNames as $columnName) {
            $cases = [];
            $columnGroup = " `".$columnName ."` = CASE `id` ";
            foreach ($values as $id => $newData){
                $cases[] = "WHEN {$id} then ?";
                $params[] = $newData[$columnName];
                $ids[$id] = "0";
            }
            $cases = implode(' ', $cases);
            $columnsGroups[] = $columnGroup. "{$cases} END";
        }
        $ids = implode(',', array_keys($ids));
        $columnsGroups = implode(',', $columnsGroups);
        $params[] = Carbon::now();
        $queryEnd = ", `updated_at` = ? WHERE `id` in ({$ids})";
        return DB::update($queryStart.$columnsGroups. $queryEnd, $params);
    }

**Comment by WebMedic-X** [comment]
hi all,

i understand this is an old thread

but curious why is this not in the framework?

**Comment by proliteweb** [comment]
@WebMedic-X that is interest question, but how does it will works with model casts on update

**Comment by cichondev** [comment]
> update batch (bulk) laravel
> https://packagist.org/packages/mavinoo/laravel-batch

That package solves my problem, thanks @mavinoo!

**Comment by bhojkamal** [comment]
> > update batch (bulk) laravel
> > https://packagist.org/packages/mavinoo/laravel-batch
> 
> That package solves my problem, thanks @mavinoo!

@cichondev 
Can we update and insert if new records  or not match id in this mavino/laravel-batch update? 
Thanks
