### ISSUE TITLE
[Proposal] Events conflicting with model relationship.

### ISSUE THREAD

**Issue by patrickomeara** [laravel/ideas#577]
I have a model `event`. A `user` hasMany `events`

```php
// User.php
public function events() {
    return $this->hasMany(Event::class);
}
```

Trying to upgrade to Laravel 5.4 `$user->events` now returns the protected array from `Concerns\HasEvents` instead of the previously expected collection of events from that user.

```php
// Laravel 5.3
$user->events; // \Illuminate\Database\Eloquent\Collection {#items: []} 
$user->events()->get() // \Illuminate\Database\Eloquent\Collection {#items: []} 

// Laravel 5.4
$user->events; // []
$user->events()->get() // \Illuminate\Database\Eloquent\Collection {#items: []} 
```

I have looked through the other properties of Model, none of them really conflict with possible model names, except for events. I see this as an oversight. 

Within `Illuminate\Database\Eloquent\Concerns\HasEvents` the protected methods use the terminology `ModelEvents`

```php
// Illuminate\Database\Eloquent\Concerns\HasEvents
protected function filterModelEventResults($result) {}
protected function fireCustomModelEvent($event, $method) {}
protected function fireModelEvent($event, $halt = true) {}
protected static function registerModelEvent($event, $callback) {}
```

It seems the obvious name for a protected variable to hold those events would be `$modelEvents`. This would also help with the ambiguity between model events and dispatched events.

I'm happy to put a PR together, depending on feedback.

:)

**Comment by sisve** [comment]
And how would you do this without breaking code for all those 5.4 users already using the $events array?

**Comment by patrickomeara** [comment]
It would be a 5.5 change to avoid any backward compatibility issues.

**Comment by sisve** [comment]
This is still breaking changes. Targeting a major release doesn't avoid that. Major releases are allowed _some_ breaking changes, and people are expecting it. Code running happily on 5.4 (and accessing this property) will break in 5.5 with this change. There's no functional gain to explain to users why the framework broke their code.

**Comment by patrickomeara** [comment]
I would think it much more likely that people have had this issue with models named "event", or will in the future during upgrades to 5.4, than people already on 5.4 who are specifically accessing `$this->events` from within a model. 

It's a common term, and is used in many apps eg. timesheets, calendars, festivals, hospitality bookings, functions etc.

Facebook has Facebook Events, Meetup has Events, Apple has Apple events, nearly every part of my infrastructure on aws has events.

If it is to stay as `$events`, the **Defining Models** section of the docs should state that naming a model "event" will result in different behaviour for it's relationships. https://laravel.com/docs/5.4/eloquent#defining-models

**Comment by sisve** [comment]
The issue isn't with models named Event, but relationships named `events`, just as there's issues with `observables` (HasEvents), `relations` & `touches` (HasRelationships), `timestamps` (HasTimestamps), `attributes` & `original` & `casts` & `dates` & `appends` (HasAttributes).

Just rename your relationship so that it does not conflict with Laravel functionality.

**Comment by lagbox** [comment]
There is no issue from outside the model with this. Only internally or if bypassing the visibility restrictions would it be an issue.

```php
$user = new App\User;
$user->events;  // null
$user->table; // null
$user->primaryKey; // null
$user->setRelation('events', App\User::find([])); // set it to an eloquent collection
$user->events; // that collection
```

Internally you have to make these adjustments, just like you can't have an attribute named 'table' (or any of the protected properties that exist ever on the model) and expect to reach it via `$this->table` (expecting `__get`), as that is an accessible property so `__get` doesn't get called.

**Comment by patrickomeara** [comment]
@lagbox, you're right. My initial problem was within the model, I was trying to simplify the example. The issue still stands. 

```php
// Laravel 5.3
$this->events; // \Illuminate\Database\Eloquent\Collection {#items: []} 
$this->events()->get() // \Illuminate\Database\Eloquent\Collection {#items: []} 

// Laravel 5.4
$this->events; // []
$this->events()->get() // \Illuminate\Database\Eloquent\Collection {#items: []} 
```

**Comment by lagbox** [comment]
You have to make adjustments internally. This is no different than trying to access attributes or anything else from inside the model.

```php
$this->getAttribute(...); // that is __get
```

Tomorrow when someone wants an 'attribute' named 'table' and can't get it internally, (`$this->table`), because `protected $table` exists, does that get renamed? And the next day when someone wants a relationship named 'dates' and wants to access it internally via `$this->dates` that property now has to be renamed ... so on and so on ?
Then when those new names end up clashing in someone's project, those properties need to be renamed again?

That can not be what is being proposed here, right?

'events' is just a random word in the scope of all of this. It is no more special than any other potential variable name.

**Comment by patrickomeara** [comment]
I see you're point @lagbox, I still think it's a little inconsistent having those four functions use 'ModelEvent' and a property called 'events'. 

Thanks for the discussion.

**Comment by lagbox** [comment]
Yea I can't say anything about that point :-).
Perhaps keep this open, so that particular issue still gets considered.

**Comment by ghunti** [comment]
I lost a couple of hours on this too. Maybe in the future upgrade guides, at least a not about possible clashes between new protected variables and relation names would be nice ;)

**Comment by joshmanders** [comment]
@sisve If the behavior worked fine on 5.3 and then upgraded to 5.4 broke it, wasn't that a breaking change? So wouldn't reverting back to that behavior in 5.5 not be that big of an issue?

**Comment by sisve** [comment]
That would result in another breaking change for those 5.4 users that access the new $events stuff.

This cannot be easily reverted, our goal now would be to figure out how this doesn't happen again. That, however, is a much larger problem area than this issue discusses.

**Comment by patrickomeara** [comment]
This has changed in 5.5

https://laravel.com/docs/5.5/upgrade

![image](https://user-images.githubusercontent.com/571773/29397324-bd523714-8360-11e7-86cd-fff7f919200a.png)
