### ISSUE TITLE
[Proposal] Add wildcard support to `only` methods on Request & Collection classes.

### ISSUE THREAD

**Issue by slashequip** [laravel/ideas#578]
The only method on a request doesn't play well when trying to get multidimensional post data using the * wildcard accessor.

e.g `$request->only('data.*.id');`

I'd expect the above to return something like this:
```
[
    "data" => [
        [
            "id" => 1
        ],
        [
            "id" => 2
        ],
    ]
]
```

What I'd actually get is this:
```
[
    "data" => [
        "*" => [
            "id" => [1, 2]
        ]
    ]
]
```

Trying the same thing on a Illuminate\Support\Collection yields an empty collection so similar improvements could be added to collections as well.

**Comment by deleugpn** [comment]
Looks like the behavior you want is in `pluck()`?

**Comment by scrwdnet** [comment]
Perhaps in this overly simplified example `pluck` *could* be used. I haven't played with multidimensional arrays and `pluck` but the proposal is about wildcards not working in `only` calls.

Let's pretend I wanted more items from my `only` call (as per most use cases of `only`) then `pluck` is no longer viable, if it even was in the first place.
