### ISSUE TITLE
[Proposal] array_collect(): collect only specific keys from an array

### ISSUE THREAD

**Issue by rentalhost** [laravel/ideas#582]
Lastly I was working with the Bungie API (from a game called "Destiny") and I had made a [simple app](https://github.com/rentalhost/destiny-activity-report) with Laravel. But I had a "small problem" (_ironically_) with this API. 

Well, basically, each API response (_from some available endpoints_) have about 10~100KB (JSON). It is slow, then I had cached it. The app does about 1.500 calls from this API initially, then I started to use the Redis to cache it, but it consumes about 1GB of memory!

The problem is that from each response I use about 200 bytes of data on app (it is less than 0.5% of total response). And not make sense I store ALL response on cache. From current 1GB, I guess that I could reduces the memory usage to ONLY 5MB.

**Okay, and what does this have to do with Laravel?**

Well, Laravel have a lot of array helpers and I think that we could create one to handle problems like that (I can work on that if approved). I thought of the following signature:

> **array_collect**($array, array ... $keys): array
> Collection::**collect**(array ...$keys): array

Then `$array` should receives your array (eg. the API response). The `$keys` should receives a lot of keys from array and return the input array only with specified keys.

**Example:**

```php
$input = [
	'success' => true,
	'message' => 'Success',
	'data' => [
		'numbers' => [ 1, 2, 3, 4, 5 ]
		'strings' => [ 'a', 'b', 'c', 'd', 'e' ],
		'array1' => [
			'x' => [ 1, 2, 3 ],
			'y' => 1,
			'z' => 'a'
		],
		'array2' => [
			'x' => [ 1, 2, 3 ]
		]
	]
];

$collect = array_collect($input, [
	'success',
	'data.numbers',
	'data.string.2',
	'data.string.4',
	'data.*.x.2',
]);

// Result of $collect:
$array = [
	'success' => true,
	'data' => [
		'numbers' => [ 1, 2, 3, 4, 5 ]
		'strings' => [ 2 => 'c', 4 => 'e' ],
		'array1' => [
			'x' => [ 2 => 3 ]
		],
		'array2' => [
			'x' => [ 2 => 3 ]
		]
	]
];
```

We should think about a better name, because should be nice if we do it reversely too (for instance, instead of collect all keys, collect all _except_ the keys).

**Comment by jrmadsen67** [comment]
First impression: I think collect()->pluck() does most of what you are after for actually grabbing the data - does this have such a wide use case that it warrants its own wrapper function around the individual calls?

**Comment by Dylan-DPC** [comment]
you can do this with `pluck` and specify the keys that you need

**Comment by rentalhost** [comment]
It is like a `pluck()` that keeps the array structure (instead of just return a unique key). With pluck I could rewrite the array one-by-one, but seems to be a hard work.
