### ISSUE TITLE
[Proposal] Add Controller function that references it's `@` name

### ISSUE THREAD

**Issue by 5outh** [laravel/ideas#585]
Currently, the way to access a Controller's methods for the purposes of routing, as per the documentation, is as follows:

```php
Route::get('user/profile', 'UserController@showProfile')->name('profile');
```

What I propose is adding a static function to the `Illuminate\Routing\Controller` that directly references controller functions instead:

```php
public static function method($name)
{
    if (!method_exists(static::class, $name)) {
        throw new BadMethodCallException(
            'Method ' . $name . ' does not exist in class ' . static::class
        );
    }
    return static::class . '@' . $name;
}
```

This allows the following, much safer way to refer to methods on controllers:

```php
Route::get('user/profile', UserController::method('showProfile'))->name('profile');
```

`method` will now fail on application start if `showProfile` does not exist on `UserController`, guaranteeing that all routes point to a valid handler.

**Comment by sebastiandedeyne** [comment]
You'd have to either write FQCN's or import all your controllers in your routes file though, kind of a dealbreaker for me

**Comment by 5outh** [comment]
That same compromise was made the other way with service provider configuration in `config/app.php` and I think it's totally worth it for the safety aspect.

**Comment by joshmanders** [comment]
Nothing stopping you from putting that static method on `App\Http\Controller.php`

**Comment by jrmadsen67** [comment]
Nothing stopping anyone from putting any of these proposal in their own projects.

That's not what the internals list is about.

**Comment by michaeldyrynda** [comment]
It's a bit verbose, don't you think? A missing controller method should only bite you in development, once at most. It seems like the only thing this adds is more keystrokes and shifting where the exception is generated from.

**Comment by brayniverse** [comment]
I've not checked as I'm AFK but can you use `Route::get('user/profile', [User controller::class, 'showProfile']);`?

**Comment by deleugpn** [comment]
I think this would completely mess up `artisan route:cache`

**Comment by 5outh** [comment]
@joshmanders I've done this in all of my projects and love it. Just want to push some of that upstream to help others.

@michaeldyrynda What if you change the name of the method somewhere along the line? This is much better for changing code. Also, this shifts the exception to application boot, which is the main benefit. The application won't start unless all routes (generated in this format) are valid.

@brayniverse The solution you've provided doesn't have the safety mechanism I'm proposing (throwing an exception on startup if the method doesn't exist)

@deleugpn Why? I don't know enough about the laravel internals to refute that but I'm curious.

**Comment by MarkVaughn** [comment]
@deleugpn I can't see it messing up the route cache. Checked by unserializing the cache, e.g `MediaController::method('missing)` becomes `..:4:"uses";s:60:"App\Media\Controllers\MediaController@missing";s:2:"as"...`

**Comment by deleugpn** [comment]
@5outh because the Route mapping is no longer a string, it became a callable and therefore it cannot be serialized. If this gets implemented, it also needs to rework the caching command to resolve the name. I think it can be done, but I'm guessing it wouldn't be easy work because both Closures and this would be detected as callable. Closures cannot be cached, so it would need to figure out how to identify this method as callable but not as a Closure and then resolve the route name for caching.

**Comment by MarkVaughn** [comment]
@deleugpn it's not a callable, it's a static function that returns a string.

**Comment by decadence** [comment]
@5outh I think you should make PR to get attention for this idea.

**Comment by 5outh** [comment]
@decadence I'm happy to do that - just wanted to go through the appropriate channels.

**Comment by decadence** [comment]
@5outh I'm afraid you can't get real answer here because maintainers come here not very often. But PRs are considered more quickly.
