### ISSUE TITLE
[Proposal] Change behaviour of `Route::group(['as' => 'foo'])` for unnamed routes

### ISSUE THREAD

**Issue by FrittenKeeZ** [laravel/ideas#589]
Currently the behaviour of ```Route::group(['as' => 'foo'])``` prefixes all routes' names regardless if it has been set.
For example if you setup routes as so:
```php
Route::group(['as' => 'baz'], function () {
    Route::get('foo', 'MyController@foo')->name('foo');
    Route::get('bar', 'MyController@bar');
});
```
You only expect ```/foo``` to have its name prefixed as ```bazfoo```, but in fact ```/bar``` is also "prefixed" and gets the name ```baz```.

I don't know how difficult is it to rework this behaviour, but wouldn't it make sense it leave unnamed routes unnamed and only apply the group name prefix to already named routes?

**Comment by deleugpn** [comment]
Why is the unnamed route in the Group, then?

**Comment by FrittenKeeZ** [comment]
@deleugpn I was trying to find a way to easily namespace Route::auth() without having to copy the code, as we're working on a project with dynamic prefixed auth routes like ```/{dealer}/login```.
