### ISSUE TITLE
[Suggestion] renaming of the `users` table

### ISSUE THREAD

**Issue by WisdomSky** [laravel/ideas#591]
When I was renaming the default users and password_resets tables into something else and then when I try to register an account, I then encountered an error:

![screenshot](https://cloud.githubusercontent.com/assets/6792172/26100563/d6d7ab86-3a60-11e7-8899-d9616c6253a6.png)

It seems that the query still uses the default table name, and when I went to the `RegisterController.php`,
the problem was caused by the validator rule `unique:users` for the `email` field. And to fix it, we need to update the validator rule to use the new table name.

What I'm trying to suggest is maybe we can make it a little more dynamic rather than hardcoding it.

Since the Registration Controller is somehow tied with the `app/User` model,  I'm wondering if we can include a method in the model like:

```php
    public static function getTableName()
    {
        return (new static)->table;
    }
```

and update the validator method in the `RegisterController.php` into something like:

```php
    protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:'.User::getTableName(),
            'password' => 'required|string|min:6|confirmed',
        ]);
    }
```

or simply:

```php
    protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:'.(new User())->getTable(),
            'password' => 'required|string|min:6|confirmed',
        ]);
    }
```

or any better ideas?

**Comment by laurencei** [comment]
Did you change the model reference in `config\auth.php`? You can set the model for the providers there?

**Comment by laurencei** [comment]
The idea of the RegisterController is you can override any function you want.

So you can just override it and set your own validation rule?

**Comment by ConnorVG** [comment]
I do believe this probably makes more sense to have it automatically figure out the users table from the controller stub (for this specific issue) – that said, if you're changing your default table name then I guess it's sort of assumed that you understand more about how this works than your average Joe.

How difficult is it to get the users table from the default guard? We could always just:
 > attain current / default guard
 > grab it's user provider
 > retrieve it's model
 > use the model's table

*On that note...* I always thought it'd be nice to be able to call something like `Rule::unique(User::class, $user->id)` etc etc. This makes for a decent use case.

**Comment by timacdonald** [comment]
@ConnorVG it's a bit thrown together for my projects, but I've just added your unique suggestion to this [rule builder](https://github.com/timacdonald/rule-builder#unique-rule-with-class-or-instance) package if your interested in being able to do that. Sorry to highjack the thread with unrelated stuff.

**Comment by ConnorVG** [comment]
@timacdonald that is amazing dude – any plans to PR this sort of extension into laravel/framework?

**Comment by timacdonald** [comment]
@ConnorVG kinda, but kinda not. Needs more fleshing out and what-not before it'd be a valid candidate + I think I saw there is going to be a new Rule class in 5.5 on twitter + it's so easy to just do stuff the 'stringy' way, I think majority of people would be against this being in the core...probs.

**Comment by ConnorVG** [comment]
I think it's more about extending the current Rule class that's already implemented. It won't take much to add the support here, I don't think: https://github.com/laravel/framework/blob/5.4/src/Illuminate/Validation/Rule.php#L56-L66

**Comment by timacdonald** [comment]
Oh, totally, yea, for just the built in unique rule, yea. I thought you meant the whole package haha. I'd love someone to PR it, I might if I get time, but would love someone else to if they have the time for sure.

**Comment by ConnorVG** [comment]
It might even make sense just to support: `Rule::unique($user)` – all the information is available there to do it.

**Comment by timacdonald** [comment]
yea, my package allows a table string, class string or Model instance. Makes it very nice.

**Comment by timacdonald** [comment]
@ConnorVG [Submitted an internals proposal to see community feedback](https://github.com/laravel/internals/issues/604) and so we can stop polluting this thread (sorry everyone).
