### ISSUE TITLE
[Proposal] withCount to support relationships on different database connections.

### ISSUE THREAD

**Issue by danielbaylis** [laravel/ideas#593]
The `with()` method allows eager loading of relationships even if the related model is on a different database connection. Very cool. `withCount()` however fails when trying to do this, as it forms a single sql statement to access the primary and related model, causing a **table not found** exception (even when the different connections are explicitly declared on each model).

Is it possible that `withCount()` could handle this just as `with()` does given it is accessing the same relationship and the only difference should be that it returns an aggregate count vs. the individual related records?

**Comment by tiagomatosweb** [comment]
Did it go forward?

**Comment by trijulio** [comment]
Im also interested
