### ISSUE TITLE
New methods for Eloquent: withSum, withAvg, etc like withCount

### ISSUE THREAD

**Issue by projct1** [laravel/ideas#600]

**Comment by decadence** [comment]
There was PR for that but it was not merged for some reason.
https://github.com/laravel/framework/pull/16815
https://github.com/laravel/framework/pull/18303

**Comment by alexweissman** [comment]
#19363 appears to be the most up-to-date PR for implementing these methods.

**Comment by taylorotwell** [comment]
Has been tried and failed a few times but open to attempts.

**Comment by alexweissman** [comment]
I'm going to go ahead and add this as extended functionality in UserFrosting 4.2. If it stands the test of time in UF, maybe we can revisit the notion of a PR to Laravel.

**Comment by anik786** [comment]
What's the state of this feature. Are we planning to add it?

**Comment by kjdion84** [comment]
+1

Curious as to why this failed. Seems like a very useful feature.

**Comment by alexweissman** [comment]
Keep in mind that although for some applications this will be useful, you should consider if on-the-fly aggregates might impact performance as your record sets grow. An alternative to `withSum`, `withAverage`, etc is to cache aggregate values in your database, and use [model events](https://laravel.com/docs/5.6/eloquent#events) to automatically update your aggregates whenever you create/update/delete the records being aggregated.

If you need to store aggregates over lots of different ranges (for example, time periods), you could consider using [dimension tables](https://en.wikipedia.org/wiki/Dimension_(data_warehouse)) to set up reporting periods.
