### ISSUE TITLE
Make @each syntax feel natural when reading it.

### ISSUE THREAD

**Issue by mitchjam** [laravel/ideas#611]
### Current
```@each('alerts.error', $errors, 'error')``` - This syntax is not readable naturally. If I had to try I would say "Render the 'alerts.error' view for all $errors as 'error'.

### Proposed
```@each('error', $errors, 'alerts.error')``` - This syntax reads "For each 'error' in $errors render the 'alerts.error' view.

**Comment by sisve** [comment]
1. Have you thought about how you would change this without causing any breaking changes?
2. The php syntax for a foreach loop has the same order of the array and value; `foreach($errors as $error)`. Why is your way better than keeping the default order of php?

**Comment by mitchjam** [comment]
Simon, thanks so much for the questions!

1. I imagine it as a breaking change. Similar to the order of arguments change made in 5.3 for first(), last(), and where().
2. It is subjective weather "errors as error" is better than "error in errors" though I prefer the latter in this instance. However, I think ```@each($errors, 'error', 'alerts.error')``` would also be more readable than ```@each('alerts.error', $errors, 'error')```. The view parameter being first is what breaks my stride. When I write the current @each I find i'm reading the literal code as I write it causing me to stop and "translate" instead of an expression that I'm familiar with such as "Foreach error in errors" or "Foreach errors as error". Neither of which I have to "translate".

Thoughts?

**Comment by m1guelpf** [comment]
👍 for `@each($errors, 'error', 'alerts.error')`

**Comment by CupOfTea696** [comment]
If we do opt for the "Foreach error in errors" syntax, should we not change the `@foreach` syntax as well? Or we could just allow both syntaxes:

`@foreach ($error in $errors)`
`@foreach ($errors as $error)`

Secondly, would it make sense to to add the currently implicit "as" (or "in" if we change the order) to the syntax, like so:

`@each ($error in $errors, 'alerts.error')`
`@each ($errors as $error, 'alerts.error')`

**Comment by mitchjam** [comment]
@CupOfTea696 Great points! I think you are right that they should be consistent. I love the idea of having the first argument an expression mirroring the @foreach. That may also be something that could be implemented as a non-breaking change which would be fantastic (@sisve).

I still find the "in" syntax more pleasant and it is used in Javascript as well as Ruby.

**Comment by CupOfTea696** [comment]
Yeah, I agree, but the "as" syntax is the way PHP does it so it does make sense to at least have the option to use that syntax.

**Comment by mitchjam** [comment]
I think for the sake of simplicity and consistency there should be only one way to write it. Also, looking at the current BladeCompiler I doubt Taylor would want any conditionals inside his compile functions.

I think I am convinced that it would make the most sense right now to use the "as" syntax.

**Comment by calebporzio** [comment]
Agreed. "as" not "in" in this instance get's what we want accomplished and has a better shot of getting merged.
