### ISSUE TITLE
[Suggestion] Implement @times into Blade 

### ISSUE THREAD

**Issue by DevDaveo** [laravel/ideas#615]
Laravel Version: 5.4 / 5.5

It would be nice to have something similar to Collection::times which is basically a @for but loops n times, for example:
```
@times(4)
    {{ $loop->iteration }} // output: 1 2 3 4
@endtimes
```

I expect this a common pattern among many developers so it would be a neat little helper!

**Comment by AndreasElia** [comment]
Blade already has an `@for` so am unsure on why this would be needed?

**Comment by DevDaveo** [comment]
It's supposed to be a shorthand for `@for` and be more intuitive.

**Comment by m1guelpf** [comment]
:+1:

**Comment by arcanedev-maroc** [comment]
is the `@times(x) ` refer to `range()` function ? Like `@foreach(ranget(1, x)) ..`
