### ISSUE TITLE
[Proposal] Aware contracts

### ISSUE THREAD

**Issue by ed-fruty** [laravel/ideas#619]
Maybe it may sense to add aware contracts for all laravel components ? 

For example `events`.

I can fire events in a different way:
```php
event(new MyEvent());
```

Or

```php
Event::dispatch(new MyEvent());
```

But code will be more clean when i inject event dispatcher contract into my class

```php

class MyClass
{
   public function handle(\Illuminate\Contracts\Events\Dispatcher $eventDispatcher)
   {
         //
   }
}
```

But in many situations dependencies in `handle` method can be so many... Yes we can divide some part to the constructor, BUT!

Why I must think about injection when I can do not do this? And laravel can help in this very well with the aware contracts. And it help me to concentrate only about payload parameters.

Events aware interface and trait example:
```php
interface EventDispatcherAwareInterface
{
  public function setEventDispatcher(\Illuminate\Contracts\Events\Dispatcher $eventDispatcher);
}




trait EventDispatcherAware
{
  protected $eventDispatcher;

  public function setEventDispatcher(\Illuminate\Contracts\Events\Dispatcher $eventDispatcher)
  {
      $this->eventDispatcher = $eventDispatcher;
  }
}

```

Now my class can be:

```php

class MyClass implements EventDispatcherAwareInterface
{
    use EventDispatcherAware;

    public function handle($onlyPayloadHere)
    {
         ///
    }
}

```

And If my class needs many dependencies, like command bus, url generator, router, view factory or other, all i need to do is add suitable aware interface and trait.

So maybe will be good idea to add something like `AwareServiceProvider` like

```php

class AwareServiceProvider extends ServiceProvider
{
    protected $aware = [
          EventDispatcherAwareInterface::class => [
               'setEventDispatcher'   => \Illuminate\Contracts\Events\Dispatcher
          ],
         BusAwareInterface::class => [
               'setBus' => \Illuminate\Contracts\Bus\Dispatcher
         ]
        ...
    ];


    public function boot()
    {
           foreach ($this->aware as $aware => $methods) {
               $this->app->afterResolving($aware, function($service) use ($methods) {
                     foreach ($methods as $method => $inject) {
                          $service->$method(
                              $this->app->make($inject)
                          );
                     }
               });
           }
    }
}

```

Yes, we can use only ugly traits, without interfaces, like

```php
trait BadTraitForEvents
{
     public function getEventDispatcher()
     {
            return app('events');
     }
}
```

But such code are stinks.

Aware contracts for every laravel component will be good.

```php

class MySuperDuperClass implements ViewFactoryAwareContract, EventDispatcherAwareContract, CommandBusAwareContract
{
    use ViewFactoryAware, EventDispatcherAware, CommandBusAware;


    public function handle()
    {
         // I can access them all here and all are clean and transparent.
    }
}

**Comment by ed-fruty** [comment]
I can make PR if it will be approved.

**Comment by sisve** [comment]
What you describe is "interface injection".

> interface injection: the dependency provides an injector method that will inject the dependency into any client passed to it. Clients must implement an interface that exposes a setter method that accepts the dependency.

Source: https://en.wikipedia.org/wiki/Dependency_injection

Implementing this means that a service can be in an invalid state between the time the object is constructed and the the setters are invoked. This means that every code that uses the dependency must now check `if ($this->dependency === null) throw new InvalidStateException();` to ensure that all the dependencies has been resolved.
