### ISSUE TITLE
Distinguish between PUT and PATCH in resourceful route Route::resource and make changes in resource controller

### ISSUE THREAD

**Issue by kroko** [laravel/ideas#620]
A resourceful controller using

```sh
php artisan make:controller SampleController --resource --model=Sample
```

is created.

Controller gets auto generated methods as per docs (called actions there)
https://laravel.com/docs/5.4/controllers#resource-controllers

Now when using resourceful route to the controller

```php
Route::resource('samples', 'SampleController');
```
both `PUT` and `PATCH` are directed to update method in the controller.

I would like to get that `PATCH` and `PUT` are distinguished. They (_intention_ and also _implementation_) are not the same! This works

```php
Route::resource('samples', 'SampleController');
Route::put('samples/{sample}', 'SampleController@replace');
```

## Proposal/suggestion/question

Yes, there is only one _U_ in _CRUD_ :)  
But wouldn't it be  better if `PATCH` and `PUT` would be distinguished OOB? I do know that this is not the norm usually. 

As I see it it could be easily implemented w/o breaking existing stuff so that so that resourceful controller would be created with two methods, for example

```php
class Controller {
  update()
  replace() // or whatever other meaningful name
}
```
and `Route::resource` would direct  
* `PATCH` -> `update()`
* `PUT` -> `replace()`

The controller template by default would just forward `replace()` to `update()`, so that existing behaviour does not change, both `PUT` and `PATCH` by default still land in `update()`

```php
class Controller {
  update() {
  //
  }
  replace() {
    update()
  }
}
```
but it gives ability to react to `PUT` and `PATCH` differently if needed (just remove call to `update()` from `replace()` and implement `PUT` as desired).

Any comments?

Thanks!

**Comment by TimOgilvy** [comment]
Definitely think at least an option to do this would be good - it might seem reasonable to assume that PATCH requests will become more popular and common, and if the default resource controller forces them to both be the same outcome, it makes it inefficient for developers to implement this approach without having to write a significant amount of extra code.

Magic is good, magic with more capacity to manage the assumptions is better!

**Comment by kroko** [comment]
@taylorotwell closed means rejected?
