### ISSUE TITLE
[Suggestion] ->first() returns a new/empty model object so  don't get null object error. 

### ISSUE THREAD

**Issue by patrickcurl** [laravel/ideas#621]
We're always running into issues where if an object is null -- and we do ->first() or something and it's null we can't then access attributes on that model. 

However if it were to return an empty/new instance -- then $obj->id would still return null, but wouldn't error when trying to display in a view.  -- Maybe institute this in other places where a null is returned instead of an object instance.

**Comment by sisve** [comment]
This is a _giant_ breaking change. You could implement the [Null Object pattern](https://en.wikipedia.org/wiki/Null_Object_pattern#PHP) in userland code and easily fallback to it in queries; `$query->first() ?? new NullModel()`. But changing framework code to do this is a _huge_ change that will probably break all existing Eloquent code that checks if a value was returned.

I consider this an issue with developer practice/praxis, not a framework issue. It is the developer's responsibility to check for null values where they are logically (and documented) returned.

**Comment by sebastiandedeyne** [comment]
There's a `firstOrNew` method that does this.

**Comment by ryanwinchester** [comment]
There are methods that would probably cover every way you would typically want it to behave depending on your context:

`first`, `firstOrFail`, `firstOrNew`, `firstOrCreate`

**Comment by patrickcurl** [comment]
It's just an issue that crops up once in awhile when doing something odd/weird like iterating through one set of data, and getting another model using an attribute of the first set, or something I can't think of the actual context right off, but it does crop up a bit ... would just be nice if first always returned an object of some sort, just being nitpicky I guess. Probably the #1 error we encounter on our team.

**Comment by brayniverse** [comment]
Looks like [Collection::first()](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Support/Collection.php#L503) allows you to pass a default value through. So you could do the following:

```php
$query->first(null, new NullModel);
```

Or if you really want that to be the default behavior for your model you could override the `newCollection` method on that model and return a class that extends `Illuminate\Database\Eloquent\Collection` and overrides the default `first` method like so.

```php
public function first(callable $callback = null, $default = null)
{
    return parent::first($callback, $default ?: new NullModel);
}
```

---

Thinking about it, using the technique above, we could allow for a default NullModel without breaking existing applications by overriding the `first` method within the `Illuminate\Database\Eloquent\Collection`. You can see what I mean below.

```php
public function first(callable $callback = null, $default = null)
{
    return parent::first($callback, $default ?? $model->getDefaultInstance());
}
```

I'm not sure how the collection class would know what model it's dealing with. But I'd expect the `getDefaultInstance` method to return `null` to allow for backward compatibility.

```php
public function getDefaultInstance()
{
    return null;
}
```

Is this worth looking into? Can anybody help me think of a way to know which model to get the instance from? Is there a better method name than `getDefaultInstance`?

**Comment by FatBoyXPC** [comment]
@brayniverse I've been toying around with this, too. I'm actually a bit frustrated that most people find `$collection->first(null, new User)` harder to understand than `$collection->first() ?: new User`. I have been trying to come up with a sensible solution for this, but I don't want it to mean I have to create a custom collection for every model I have.
