### ISSUE TITLE
Command to check if they're migrations available

### ISSUE THREAD

**Issue by m1guelpf** [laravel/ideas#623]
It'd be cool to have something like migration:check, that checks connection to the database and if there is something to migrate...

**Comment by drbyte** [comment]
You can run 

```php
php artisan migrate --pretend
```

It will query the database and either return "Nothing to migrate" or a list of queries to migrate.

**Comment by sisve** [comment]
There's also `php artisan migrate:status` that lists all migrations and if they've been executed or not.

@m1guelpf Could you provide a use-case not already supported by the existing artisan commands?

**Comment by m1guelpf** [comment]
@sisve An example use case would be to check if they are migrations to run for deploying. If they are, I can turn manteniance mode on and migrate, but if they aren't, I can skip all that.

**Comment by sisve** [comment]
`php artisan migrate:status` will answer that.

However, these commands are meant for human consumption. I don't think they have any exit codes you can rely on to automate the process. But your description sounds like you do not have an automatic deploy process setup anyway.

**Comment by m1guelpf** [comment]
@sisve I actually have, that's why I'm trying to automate migration detection

**Comment by sisve** [comment]
That sounds like an odd thing for a deploy process to do. Just take down the server, do the deploy, and bring up the server again? Sure, I skipped over the details of "do the deploy"-step, but it would involve a `php artisan migrate` which will be quick and do nothing if there's nothing to be migrated.

The take-down-server and bring-up-server steps aren't a requirement for migrations, but a way for you deploy mechanism to signal your load balancer to stop sending http requests to the machine until the deploy to that machine is complete.

**Comment by m1guelpf** [comment]
The thing is that I have almost-zero-downtime-deployments. I just turn the site diwn to migrate the database

**Comment by sisve** [comment]
A very important question; is this a single-server setup? Because zero-downtime-deployments aren't even hard with two machines and a load balancer. You could technically have one server in maintenance mode forever in such a setup, and still have 100% uptime...

**Comment by m1guelpf** [comment]
Yep, it's a dingle server

**Comment by fgilio** [comment]
I'm in the same spot. @m1guelpf did you find a way to do this?
I only want to do an `artisan down` if there're migrations to execute

**Comment by m1guelpf** [comment]
@fgilio If I find some time, I migth make a package for this.

**Comment by fgilio** [comment]
That would be really nice

**Comment by erjanmx** [comment]
https://gist.github.com/erjanmx/723eaeb6ef2554a5ea1fcb61764dd178

Encountered the same problem. Came up with this quick solution. Maybe it will help you as well.

If everything is ok, will make a package for this

![34158320-e93a62c6-e4d5-11e7-94ed-d4ee9a5c9a37](https://user-images.githubusercontent.com/4899432/34159036-b223e3ea-e4d8-11e7-8a63-df33adeb2e4b.gif)

**Comment by fgilio** [comment]
Awesome!

**Comment by fgilio** [comment]
@themsaid what do you think of having https://github.com/erjanmx/laravel-migrate-check built in? I've been using it since Dec 2017 and it's proven to be very useful

**Comment by michaeldyrynda** [comment]
It may be simpler to (submit a PR to) modify `migrate:status` to return with a non-zero exit code if there are migrations you be run. 

You can then adjust your deployment process to check for this and `migrate` automatically as @m1guelpf was trying to do. 

Seems a trivial change, though not sure if it would be considered breaking, because I’m sure somebody somewhere will be relying on a zero exit code for something. 

Maybe something to target for `master`/`8.x`

**Comment by fgilio** [comment]
> Maybe something to target for `master`/`8.x`

Yes, I think that would be the safest bet. I'll give it a spin. Thanks Michael!
