### ISSUE TITLE
[Proposal] Organising database migration files into sub-directories in future versions

### ISSUE THREAD

**Issue by santhoshkorukonda** [laravel/ideas#625]
**Edit**: Right now laravel migration tool is creating all migrations and identifying migrations only in ``database/migrations`` directory and developer has limited chance to organise them into sub-directories (by using ``--path=PATH``). But the problem here is developer has to run ``--path=PATH`` equals to # of times of sub-directories.
Just like we all do for **models** in ``app`` directory, I think its good to organise migrations into sub-directories by ``php artisan make:migration Users/create_users_table`` and let migration tool identify migrations inside sub-directories recursively by ``php artisan migrate -R`` or ``php artisan migrate --recursive``.

### Benefits
1. Neat and clean ``database/migrations`` directory. Everything is organised into their respective directories. Ex: **Users** directory may contain - _Users, UsersEmails, UsersPhones_ and **Vendors** directory may contain - _Vendors, VendorsEmails, VendorsPhones_ something like based on ``ER Schema grouping``.

It is not a major issue, but organising looks clean and neat in my view.

### From the discussion below the proposal is:
For organised migrations in sub-directories run migrations using
``php artisan migrate -R`` or ``php artisan migrate --recursive``

For unorganised mirations (all migrations in ``database/migrations`` directory not its sub-directories)
``php artisan migrate`` still works fine.

**Comment by sisve** [comment]
I believe this is already supported using the `php artisan migrate --path=...`

https://github.com/laravel/framework/blob/b2d9b4697f2a295a86697f0ae7648f2dbcae1beb/src/Illuminate/Database/Console/Migrations/MigrateCommand.php#L19

**Comment by sisve** [comment]
Wait, are you saying that you Laravel to look in database/migrations _recursively_? So that subfolders are automatically included when looking for migrations?

If so, how would that work with --path?

**Comment by santhoshkarmanya** [comment]
@sisve Yes it is supported. If I'm using ``php artisan migrate --path=[PATH]``, I have to run this command times equals to # of sub-directories which is a bit of manual work for the developer. So let the migration tool recognise migration files in the sub-directories of the given path.

Actually I had given a PR for this issue [to 5.4 branch] but it is closed because its a breaking change for 5.4. That's why I'm proposing for future versions. Here is the link for my previous PR. https://github.com/laravel/framework/pull/19382

**Comment by santhoshkorukonda** [comment]
@sisve Yes it is supported. If I'm using ``php artisan migrate --path=[PATH]``, I have to run this command times equals to # of sub-directories which is a bit of manual work for the developer. So let the migration tool recognise migration files in the sub-directories of the given path.

Actually I had given a PR for this issue [to 5.4 branch] but it is closed because its a breaking change for 5.4. That's why I'm proposing for future versions. Here is the link for my previous PR. https://github.com/laravel/framework/pull/19382

**Comment by uruloke** [comment]
Path has support for Wildcards, why not just use that?

**Comment by santhoshkorukonda** [comment]
@uruloke Yes I can use wildcards in path, something like ``php artisan migrate --path="database/migrations/*"``. But it solves upto some extent. Consider this case, if there are multiple sub-directories like ``database/migrations/Masters/Transactions/*.php`` and ``database/migrations/Masters/General/*.php`` then path wildcards cannot recursively look into all sub-directories. Here is why? Please look into [this](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Migrations/Migrator.php#L423)

**Comment by santhoshkorukonda** [comment]
Consider these scenarios to understand my view. If migrations are organised into sub-directories something like:
``database/migrations/Users/create_users_table``
``database/migrations/Users/create_users_emails_table`` and so on

``database/migrations/Vendors/create_vendors_table``
``database/migrations/Vendors/create_vendors_emails_table`` and so on

``database/migrations/Masters/Transactions/create_vendors_transactions_table``
``database/migrations/Masters/Transactions/create_users_transactions_table`` and so on

``database/migrations/Masters/General/create_phones_table``
``database/migrations/Masters/General/create_emails_table`` and so on

Creating some migrations which does not fit into any groups. Something like:
``database/migrations/create_uuid_extension`` (PostgreSQL - CREATE EXTENSION ...)
``database/migrations/create_development_schema`` (PostgreSQL - CREATE SCHEMA ...)

Now by using wildcards I can only get some migrations from this kind of directory organisation. So what I meant to say is let the migration tool identify the files where ever they are in sub-directories **of the given path** and execute them. Correct me if I'm wrong.

**Comment by Dylan-DPC** [comment]
Well some people like to archive their migrations and place it in `archive` directory inside `migrations`. That would run these archived migrations as well.

**Comment by santhoshkorukonda** [comment]
@Dylan-DPC Yes I completely agree with you. If I implement this thing into current versions like 5.4 it is really a big issue. So I'm proposing to future versions. You know how its going to be if this kind of organising is there.

**Comment by uruloke** [comment]
@santhoshkorukonda I understand it, and I can see why it would be nice to have. And possibly also a config for blacklisting folders, so people still can have their archive folder.

However pretty sure Taylor won't accept a pull request with this feature, but you could try and hope.

**Comment by santhoshkorukonda** [comment]
@uruloke Thank you man for your review. I had already made a PR to 5.4 its rejected because at that time I did not considered the case ``archives`` and its a breaking change to framework.

If you consider this is good, without any config we can have flag like ``php artisan migrate --considerall`` which considers all migrations in all sub-directories **of the given path** and ``php artisan migrate`` will work as it is like in the past.

I have small doubt correct me if I'm wrong. Is it okay to have ``archives`` which may or may not be used in application but still stored in application's main directories? I mean if they are historical why storing in application's main directory?

**Comment by uruloke** [comment]
@santhoshkorukonda A better syntax would more be an `R` flag for recursive, as that is a syntax we are used to.  
I can see the flag solution as having better odds of making it through Taylor.

**Comment by santhoshkorukonda** [comment]
@uruloke Yeah ``R`` flag is better than ``considerall``. What do you think about the feature? Is it good to have in framework or not a good one? Making it through Taylor is secondary because if you guys here think its not a good feature there is no use of considering it and giving a PR right. So please give me your suggestions. If it is good I will continue, if not I will close it.

**Comment by uruloke** [comment]
I think it's a nice to have feature. 
Can't speech for others though ;)

**Comment by Dylan-DPC** [comment]
My guess is most people will leave all their migrations in the same folder. If you want to you can implement this in a package (or use one )

**Comment by santhoshkorukonda** [comment]
@Dylan-DPC Yes but from the discussion above we can use ``php artisan migrate -R`` only if people wanted to organise migrations into sub-directories, if not still ``php artisan migrate`` works same as it is in the previous way. We can satisfy both kinds of people who wants to organise and who doesn't wants to organise.

Let me see for few more days. If there is good backing for this feature I'll go with a PR or I'll close it and go with a package for my projects.

**Comment by uruloke** [comment]
@santhoshkorukonda Maybe change the original thread so people do not have to read the whole thread to understand what the feature is/has changed to.

**Comment by itsmill3rtime** [comment]
one issue i see is it would have to load a list from every folder and subfolder and down the line until it has a list of every migration file name. then sort them by the date pre-pended on the file name before running. it couldn't just run a subfolder, then the next, then the next. migrations would run out of order
