### ISSUE TITLE
[Proposal] Add source to log statements

### ISSUE THREAD

**Issue by ps** [laravel/ideas#627]
When using the Log facade `Log::info("hello world");`, default logs look roughly like this:
```
[2017-06-06 21:37:57] local.INFO: hello world  
[2017-06-06 21:37:58] local.INFO: hello world1  
[2017-06-06 21:37:59] local.INFO: hello world2 
```

It would be great to for the Log facade to also spit out information about where the log statement came from, since it is not uncommon to have duplicate log messages across two different classes. I know that I get this sort of info in my logs by adding IntrospectionProcessor to the monolog instance and then writing my logs as follows:
```
Log::getMonolog()->info("hello world);
```

I just think it would be good to have some sort of info (line number, class, method) in log statements by default. Me personally, one of the first things I do when starting a new Laravel app is add the IntrospectionProcessor so that I can debug better from log statements.

Java's Log4j package handles this by creating logs of the following structure [[1]](https://www.mkyong.com/logging/log4j-hello-world-example/)
```
2014-07-02 20:52:39 DEBUG className:200 - This is debug message
2014-07-02 20:52:39 DEBUG className:201 - This is debug message2
```

I'd be willing to work on this if there aren't major arguments against this.

**Comment by drbyte** [comment]
Why not just update the processor in your AppServiceProvider?

ie:

```php
    public function register()
    {
        // Configure logging to include files and line numbers
        $monolog       = \Log::getMonolog();
        $introspection = new \Monolog\Processor\IntrospectionProcessor (
            \Monolog\Logger::WARNING, // whatever level you want this processor to handle
            [
                'Monolog\\',
                'Illuminate\\',
            ]
        );
        $monolog->pushProcessor($introspection);
    }
```

**Comment by ps** [comment]
@drbyte my point is that everytime I start a new Laravel app I have to write code to get line numbers to show in my logs. So I am proposing that it would be nice to have this functionality baked into Laravel, since right now it is not, it requires additional configuration on the users part.

**Comment by drbyte** [comment]
Fair. I understand your point.

It's possible many may argue that they'd prefer not to have line numbers on all their Log calls. So in their case they'd complain that they have to reconfigure it "not to". 
Tough to know what the majority would want.

**Comment by michaeldyrynda** [comment]
Even if it doesn't come into core, there's nothing preventing you from creating a package you can use in your projects in future. Would work for your needs and anybody that needs it could use it also.

**Comment by ps** [comment]
@drbyte can you think of a real world use case where it would be detrimental to have line number on all of Log calls?

@michaeldyrynda Hmm I didn't think about that. But this might not be so straight forward. The reason being is that if I recall correctly, adding the IntrospectionProcessor (similarly as @drbyte showed above), will make statements like `Log::info('hello world');` show line numbers, but the line numbers will not be correct due to the Log facade being a wrapper around a Monolog instance or something along those lines. Hence as a result in order to get the correct line numbers the log statement has to be written as `Log::getMonolog()->info('hello world');`. So I think if I went with your approach I'd have to write a logging package wrapper around Monolog from scratch, which is basically reinventing the wheel and in retrospect it is definitely much less overhead to copy 5-10 lines of code in each new Laravel project as opposed to writing a brand new Log package, and then actively maintain it.

**Comment by drbyte** [comment]
Real world case: Maybe I'm using logging to log audit-trail events. I don't care what line it was on; just that it was logged 

```php
Log::info("user ABC deleted record 123 from IP address xxx.xxx.xxx.xxx");
```

with this
```php
    public function register()
    {
        // Configure logging to include files and line numbers
        $monolog       = \Log::getMonolog();
        $introspection = new \Monolog\Processor\IntrospectionProcessor (
            \Monolog\Logger::DEBUG,
            [
                'Monolog\\',
                'Illuminate\\',
            ]
        );
        $monolog->pushProcessor($introspection);
    }
```
The following output is generated. While the filenames and line numbers are correct, I wouldn't want the extra info in my logs.

> [2017-06-06 20:58:43] local.INFO: user ABC deleted record 123 from IP address xxx.xxx.xxx.xxx  {"file":"/app/Http/Controllers/AdminController.php","line":31,"class":"App\\Http\\Controllers\\AdminController","function":"index"}

Granted, I can mitigate it by setting the logging level to NOTICE or WARNING, so INFO level messages wouldn't get the line numbers.

**Comment by ps** [comment]
@drbyte yes, and another counter argument that I can think of is that for the particular use case that you mentioned you are either using a log parsing package (or you're parsing the log yourself), which would parse the log message with line numbers for you without an issue and you simply then extract just the message. Additionally, if you don't care what line it was on, then just ignore that information.

Also, thanks for showing me how you modified the monolog instance. The way I modified it was by fetching it in `bootstrap/app.php` right before the `return $app;` because that is what [Laravel docs suggest](https://laravel.com/docs/5.4/errors#custom-monolog-configuration), but with your way, `Log::info('hey');` displays the line numbers correctly so thanks!

**Comment by Dylan-DPC** [comment]
I don't think its something everyone would like to have. You could implement it as a package and include the package wherever you want it

**Comment by sisve** [comment]
Retrieving the line numbers using the IntrospectionProcessor involves getting a full debug_backtrace on _every log statement_. ([Reference](https://github.com/Seldaek/monolog/blob/e5ff7eb0746c50d483fc9797f1f288acd8cbb5fc/src/Monolog/Processor/IntrospectionProcessor.php#L54)) I have no numbers [or any facts at all] to back this up, but my experience from totally other systems (.NET) tells me that this is an expensive operation. I presume it is in PHP too.

Could the magical `__FILE__` and `__LINE__` constants be used instead?

**Comment by ps** [comment]
@sisve I'm only suggesting that this would be nice to have whoever this can be accomplished (the computationally cheaper the better obviously). Using `__FILE__` and `__LINE__` would be fine as long as it's hidden behind the Log facade (aka so that the user doesn't have to remember to add it to every log statement).

@Dylan-DPC When there is extra information in the log, those people can simply ignore it and move on. In the current setup, the people who want the line numbers can't 'ignore it and move on', they have to do extra work to get this done. So in essence it doesn't seem like adding line numbers would be a nuisance for people who don't want it as it is a nuisance for people now who do want it.

**Comment by troelskn** [comment]
`__FILE__` and `__LINE__` won't be helpful here. And I agree that pulling a full backtrace on each log line is very expensive.

Perhaps such a feature could be controlled by a config-setting? That way, the default could be to remain as is, but getting the information would be a simple edit to a config file. This would also be convenient in debugging-scenarios, where you might want to enable it temporarily.
