### ISSUE TITLE
[Proposal] Add a more flexible route where method

### ISSUE THREAD

**Issue by alberto-bottarini** [laravel/ideas#628]
Route ```where``` method accept, as second parameter, a regexp in order to "validate" a path variable.

I think it should be more flexible if it could accept also a closure to implement more flexible rules.

For example:
```php
Route::get('/people-by-age/{age}', [
   'as'   => "people-age",
   'uses' => 'MyController@myMethod'
])->where('age', function($age) {
   return $age > 17;
});
```

What do you think?

**Comment by brayniverse** [comment]
Seems reasonable. Submit a PR.

**Comment by michaeldyrynda** [comment]
The only thing I'd be mindful of when using a closure like this is the ability to cache the route afterward. I know that routes can't be serialized if they're closure-based, and I suspect it'll be an issue with a `where` closure as well.

**Comment by bloggervista** [comment]
Exactly my i also have concerns with route caching :(

**Comment by alberto-bottarini** [comment]
@michaeldyrynda you are right. There will be some issue about route caching. 

The only thing that come to my mind to avoid it, it's this solution:

```php
Route::get('/people-by-age/{age}', [
   'as'   => "people-age",
   'uses' => 'MyController@myMethod'
])->where('age', 'MyRouteValidator@validateAge');

class MyRouteValidator {
  public function validateAge($age) {
    return $age > 18;
  }
}
```


What do you think?

**Comment by m1guelpf** [comment]
@alberto-bottarini I think it's a good solution, but I personally don't think Taylor would accept this solution, as it adds (unnecesary) complexity to the framework

**Comment by vpratfr** [comment]
How about being able to reuse existing validation rules?

`->where('age', 'integer|min:18');`

**Comment by alberto-bottarini** [comment]
@vpratfr I really like your solution. I will think about :+1:

**Comment by alberto-bottarini** [comment]
Damn! Route validation is encapsulated into Symfony router. 
Laravel does nothing about this task but "pass" requirements to Sympfony.

**Comment by lucasmichot** [comment]
Indeed @alberto-bottarini , to achieve this, changes have to made in `\Symfony\Component\Routing\Route::sanitizeRequirement` so that it accepts closures.

**Comment by vpratfr** [comment]
In order to maintain backwards compatibility, one would either need to:

- Add a `whereRule` method which accepts such rules either as string or array
- Make the `where` function eitheir accepts `string` (regex as before) or `array` (set of validation rules)

I would also suggest to ping @taylorotwell on this matter, your PR may just be rejected directly if that is not something juged as `wanted` in a future release.

**Comment by taylorotwell** [comment]
Closure seems reasonable.
