### ISSUE TITLE
[Proposal] Allow callback for dispatch failure 

### ISSUE THREAD

**Issue by lukepolo** [laravel/ideas#629]
Use Case :

We have an external worker using beanstalkd. Laravel sends a dispatch and fails and will report an error that we cant connect, which is good but there is a problem.

Lets say we create a new Setting and this setting effects something on an API outside your app, so we created a job.

public function createSetting() {

    $setting = Setting::create([
        'name' => 'should_report_errors',
        'value' => true
    ]);

    dispatch(new SendSettingToApp($setting))

    return response()->json($setting);
}

laravel/framework#19519
With the current code we would have to write our own try catch , to make sure we are dispatching , with my changes you can do it like this

public function createSetting() {

    $setting = Setting::create([
        'name' => 'should_report_errors',
        'value' => true
    ]);

    dispatch(new SendSettingToApp($setting, function() use($setting) {
         $setting->delete();
        // or we can do  DB::rollBack(); , as long as we start the transcations 
    }))

    return response()->json($setting);
}

I do not think this is the best method , so I would like to have a good discussion on how we should handle this within the framework.

**Comment by sisve** [comment]
I assume that dispatch() would throw an exception on failure. Wrapping Setting::create and dispatch() in a DB::transaction would be enough to automatically rollback the db changes when the exception is thrown.

**Comment by themsaid** [comment]
Yes I think it's something you can do using a simple try..catch
