### ISSUE TITLE
[Proposal] Allow multiple $dateFormat

### ISSUE THREAD

**Issue by bdsoha** [laravel/ideas#630]
Wouldn't it be great if models would allow different date formats for different attributes. The `$dates` array can be rewritten to support attribute names as `keys` and formats as `values`.

```php
class MultipleDateFormats extends Model
{
    protected $dates = [
        'expiration' => 'm-y',
        'birthday'   => 'm-d-Y',
        'default_date'
    ];
}
```

**Comment by timacdonald** [comment]
this is similar to https://github.com/laravel/internals/issues/669.

**Comment by bdsoha** [comment]
@timacdonald The only difference is that I suggested it weeks before...

**Comment by timacdonald** [comment]
Totally, Sorry @bdsoha, was just linking them - wasn't trying to say you put up a duplicate. Sorry should have been more clear. Just wanted to be able to help link up conversations about it.

**Comment by taylorotwell** [comment]
Possible now.
