### ISSUE TITLE
[Proposal] Add --lts option to Laravel Installer

### ISSUE THREAD

**Issue by Jamesking56** [laravel/ideas#633]
Imagine you're creating a new Laravel project using the Laravel Installer. Wouldn't it be nice if you can choose to use the latest LTS version by adding `--lts` to your command?

`laravel new app --lts` to install Laravel 5.1 LTS for example.

This option would install whatever the latest LTS version is at the time.

**Comment by lucasmichot** [comment]
See PR https://github.com/laravel/installer/pull/66

**Comment by Jamesking56** [comment]
Worth a rethink @taylorotwell ? 6 likes already so definitely a use case.

**Comment by m1guelpf** [comment]
Also see https://github.com/laravel/installer/pull/65 & https://github.com/laravel/installer/pull/40
