### ISSUE TITLE
[Proposal] Local query scopes as classes

### ISSUE THREAD

**Issue by salomoni** [laravel/ideas#636]
https://laravel.com/docs/5.4/eloquent#query-scopes

## Currently

```php
class User extends Model
{
    public function scopeActive(Builder $query)
    {
        return $query->where('active', 1);
    }
}
```
```php
$users = User::active()->get();
```

## Proposed

```php
class ActiveScope implements Scope
{
    public function apply(Builder $builder, Model $model)
    {
        $builder->where('active', 1);
    }
}
```

```php
$users = User::scoped(ActiveScope::class)->get();
```

**Comment by Dylan-DPC** [comment]
What's the gain?

**Comment by salomoni** [comment]
Just an alternative way to write query scopes.

Keeps the models clean.

Also nice when sharing the same scope between models. So far I have just written a scope trait or just duplicated the code.

Maybe easier to break the scope logic into smaller pieces.

```php
class ActiveScope implements Scope
{
    public function apply(Builder $builder, Model $model)
    {
        $this->verified($builder);
        $this->emailed($builder);
        $this->notOld($builder);

        // ...
    }
}
```

**Comment by Dylan-DPC** [comment]
ya but other than `apply` I don't see any other method you will have in the class. Also if you want common functionality across models you could use a trait

**Comment by ajcastro** [comment]
The current disadvantage of the current local scope is that in IDE like in sublime, when you f12 or find symbol for the method, it could not really find it because its method is actually `scopeActive` and not `active`

**Comment by mfn** [comment]
This issue is years old and the problem you described isn't specific to Sublime, any IDE has this issue.

Laravel is simple full of wonderful magic and some if it you can't escape if you _want_ to use certain patterns.

I'd also say any project seriously using laravel should use https://github.com/barryvdh/laravel-ide-helper which, AFAIK, support scopes by creating phpdoc on the classes to allow at least autocomplete in modern IDEs.

**Comment by jaripekkala** [comment]
I still think this would be a cool feature.

However I do see the point of not adding every single cool feature to the core.

**Comment by lptn** [comment]
A semi hacky way to use Scope classes for local queries:

```php
public static function getNumberOfAdults(): int
{
    return self::query()
        ->tap(function (Builder $query) {
            (new AgeScope(18))->apply($query, $query->getModel());
        })
        ->count();
}
```

As you can see there are to ugly parts:
1. Useless $query->getModel()
1. Extra Lambda/Closure.

ideally it should looks like:

```php
public static function getNumberOfAdults(): int
{
    return self::query()
        ->applyScope(new AgeScope(18))
        ->count();
}
```

or for scopes without arguments:

```php
public static function getNumberOfAdults(): int
{
    return self::query()
        ->applyScope(AgeScope::class)
        ->count();
}
```

**Comment by mpyw** [comment]
I really like class scope approach

**Comment by mpyw** [comment]
The only disadvantage of this feature is that users must know what scopes are applicable to the model. It's very unclear unlike to the trait approach.

**Comment by mpyw** [comment]
```php
// The macro should be called only in model definitions

Builder::macro('scoped', function ($scope, ...$parameters) {
    if (is_string($scope)) {
        $scope = app($scope, $parameters);
    }
    if (!$scope instanceof Scope) {
        throw new LogicException('$scope must be an instance of Scope');
    }
    return $scope->apply($this, $this->getModel());
});
```

```php
// Class scope should be re-defined as a method scope

class User extends Model
{
    public function scopeActive(Builder $query): Builder
    {
        return $query->scoped(ActiveScope::class);
    }
}
```

**Comment by mpyw** [comment]
I published as a package: [mpyw/laravel-local-class-scope: A tiny macro that reuse a global scope class as a local scope](https://github.com/mpyw/laravel-local-class-scope)
