### ISSUE TITLE
Models namespace

### ISSUE THREAD

**Issue by m1guelpf** [laravel/ideas#637]
Due to an accidental Pull Request (https://github.com/laravel/laravel/pull/4290), the Laravel community started discussing again about the model namespace (see the Pull Request comments). I know this has been discussed before, but GitHub search couldn't find a single related issue in this repo, so here it is.

<details>
<summary>TLDR</summary>
The proposal consists on moving the models to their own namespace (probably App/Models/Eloquent)
</details>

**Comment by troccoli** [comment]
I personally like the idea of having the models on their own namespace. Moving the User model into  app/Models is almost the first thing I do in a new project.

**Comment by decadence** [comment]
And important thing is that PR has base model we can edit

**Comment by m1guelpf** [comment]
@decadence I personally don't like the idea, but feel free to open another internals issue. (Both of the ideas have few possibilities of getting merged, so joining both doesn't seem a good idea...)

**Comment by tomschlick** [comment]
Not a fan of the Models directory/namespace at all. I'd prefer to keep it as is. 

Also, you can already just specify "Models\" in the artisan command like this

```sh
php artisan make:model "Models\Post"
```

**Comment by thehiredgun** [comment]
@fonini thank you for the link - that is a fair point. And it reminds me that technically the namespace for User (and other Eloquent models) should probably be App\Models\Eloquent, not (as in my original/accidental pull-request) App\Models.

**Comment by m1guelpf** [comment]
@thehiredgun And that would prevent what Taylor said... good idea!

**Comment by connectkushal** [comment]
@fonini thanx! :)

**Comment by lucasmichot** [comment]
https://github.com/laravel/laravel/pull/4680 is an alternative that introduces custom generator namespaces.
