### ISSUE TITLE
[Proposal] For insert, allow users to pass a column array

### ISSUE THREAD

**Issue by OhligerJ** [laravel/ideas#639]
Right now, we force developers to pass an array of associative arrays in order to to insert, so if a developer wants to insert multiple times (such as for a seeder), they must type out each column name each time.

For a seeder with hundreds of inserts, this slows things down significantly. It also does not fit the pattern for raw INSERT statements: (INSERT INTO table_name (col1, col2, ...) VALUES (val1, val2,...), (val1,val2, ...), (..);

I propose adding a $columns array at the beginning of the insert function so that columns can be defined first, and then an array of arrays for values.

My first crack at a solution in src/Illumindate/Database/Query/Builder.php wasn't showing up well in the code markdown. The relevant additions:

Line 2093:
`  public function insert(array $columns=[], array $values=[])
    {
        if(is_array($columns[0]) && count($values) == 0){
            $values = $columns;
        }`

Now line 2112:
`        if (count($columns) > 0 && (count($columns) == count($values[0])) ){
            foreach($values as $key => $value){
                $value=array_combine(sort($columns), $value);
            }
        }`

As a first-time contributor and relatively new Laravel developer, I am uncertain of the optimal solution. The general idea here is to take the columns and build the associative array for each array of values, and then otherwise keep the the logic the same. To maintain backwards compatibility, we also let them provide only one argument, the associative arrays.

**Comment by sisve** [comment]
This sounds like something that would need to handle the per-database limit of max number of parameters. I know that SQL Server has a limit of 2100 parameters, which would make it impossible to insert 101 rows of 21 columns (101*21 = 2121).

SQLite is even worse, it defaults to 999 parameters according to "Maximum Number Of Host Parameters In A Single SQL Statement" in https://www.sqlite.org/limits.html

**Comment by OhligerJ** [comment]
I agree. I haven't run into that error yet, but I think it would be a good idea to surface that barrier should a seeder run into it. The current insert process could run into the same issue, but it's less likely given that the developer would either have to write out each associative array by hand, or do the array_combine themselves.

Keep in mind that in that particular case, we're starting to blur the line between seeding and DB dumping. Creating Eloquent-compatible DB dumps may be a viable, but larger project, and outside the current scope of this feature request.

**Comment by spronkey** [comment]
For what it's worth, Laravel has plenty of places already where it can run into SQL variable limits. All the relation attach/sync methods can fail if passed too many relations.

I wrote this PR ages ago to try to allow optional columns to work, so that in cases when you are inserting a large dataset with a large amount of optional data, you don't have to specify empty columns, but it was rejected: https://github.com/laravel/framework/pull/15689
