### ISSUE TITLE
feature request: artisan migrate should protect against parallel execution by default

### ISSUE THREAD

**Issue by tback** [laravel/ideas#641]
Modern hosting environments like kubernetes run multiple instances of laravel for load-balancing and ha. They often execute migrations before launching the application itself. I've seen quite a few apps executing migrations in parallel by accident. This could be avoided if artisan migrate would lock in some way by default.
Maybe a table lock on the migration table would do the trick.

**Comment by lksnmnn** [comment]
+1 this is a feature we also need, as we are currently looking into deploying a micro services based on multiple Laravel applications.

**Comment by taylorotwell** [comment]
Open to suggestions on how to implement or PRs.

**Comment by rogatty** [comment]
@taylorotwell Liquibase does it by creating a lock in a separate table. See http://www.liquibase.org/documentation/databasechangeloglock_table.html for a short description and  https://github.com/liquibase/liquibase/blob/master/liquibase-core/src/main/java/liquibase/lockservice/StandardLockService.java for the implementation.

**Comment by chescos** [comment]
Couldn't this simply be done using advisory locks? MySQL ([GET_LOCK](https://dev.mysql.com/doc/refman/5.7/en/locking-functions.html#function_get-lock)) and PostgreSQL ([pg_try_advisory_lock](https://www.postgresql.org/docs/9.1/functions-admin.html)) both support them.

Before starting to run any migrations, just check if the lock can be acquired. If it can't be acquired, output an error and abort. If it can be acquired, run the migration and then free the lock.

**Comment by iwasherefirst2** [comment]
@tback doesn't the database itself take care of that? https://stackoverflow.com/questions/46354270/do-laravel-migrations-lock-the-tables-they-affect#:~:text=Laravel%20does%20not%20control%20table,used%20to%20finalize%20the%20change
