### ISSUE TITLE
feature request: pivot table should check for relationship and use create() for attaching

### ISSUE THREAD

**Issue by iateadonut** [laravel/ideas#642]
InteractsWithPivotTable.php::attach() uses insert() to add a pivot.  You might want to have attributes when adding the entry come from a relationship, specifically a relationship with ->where().

->where in a relationship might be used when you have different types of an object.  In the particular case I'm looking at, there is a user_role relationship, and there is an extra column on the pivot table 'company_id'.

the $user->roles() relationship is belongsToMany(...)->where(company_id, $id).  I'd like the company_id to be added through ->attach() without having to add the attribute.

**Comment by Dylan-DPC** [comment]
You can still do it. Check this link https://stackoverflow.com/questions/40949818/how-to-add-data-to-additional-column-in-pivot-table-in-laravel
