### ISSUE TITLE
Date validation rule

### ISSUE THREAD

**Issue by garygreen** [laravel/ideas#643]
It would be nice if in the validator you could specify rules like:

```php
use Illuminate\Validation\Rule;

$rules = [
    'date' => Rule::date()->format('d/m/Y')->isWeekday()
];
```

Any function call would defer onto Carbon and see if it returns a truthy value.

You could even add a `is` function so you can e.g. easily check a date format and their age:

```php
$rules = [
    'date' => Rule::date()->format('d/m/Y')->is('age', '>=', 18)
];
```

The current alternative to this would be to do something like the following:

```php
$rules = [
    'date' => 'bail|date_format:d/m/Y|min_age:18,d/m/Y'
];
```

Which is a bit clunky because your custom `min_age` validation would need to know the date format, if you wanted to compare additional things it would also need the date format too, as well as the order of the rules being critical (along with the bail), unless your `min_age` validates date format, too.

**Comment by diego1araujo** [comment]
your suggestion is more readable IMO. but if we already have a solution for it i think it will be hard Taylor takes a look on it right now

**Comment by jrmadsen67** [comment]
You might look at what @timacdonald is doing here: https://github.com/timacdonald/rule-builder and see if it helps or is something you could contribute to

**Comment by timacdonald** [comment]
thanks for the shout out @jrmadsen67, yea the rule builder I put together is just a hobby package for me (so no tests yet - sorry), but would love any PR's to make it more awesome-er foe sure. Also, pretty sure the next iteration of Laravel with the custom validation rule classes will open up a lot more possibilities.

PS. keep in mind you can [macro the Rule class](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Validation/Rule.php#L9) already to do all types of witchcraft and wizardry if needed.

**Comment by timacdonald** [comment]
Just a heads up - I've updated the package to version 3. Its now tested. And I'm working on a date helper so you can pass in carbon instances...

`Rule::before(Carbon::now()->addYear())`
