### ISSUE TITLE
[Proposal] Unique keys for pushing onto stacks

### ISSUE THREAD

**Issue by jlem** [laravel/ideas#646]
I have blade partial that represents a color picker input field. Because color picking is not cross-browser, I am reliant on a rather heavy JS library to provide the color picker interface. 

I do not want to include this library at the global level since it will not be used on 95% of pages. Nor do I want to have to include it separately on the pages where the color picker partial will be included. I want the color picker partial to be self-contained, such that `@include('common::input.color')` automatically imports its scripts dependencies.

However if I simply use...

```
@push('vendor')
   ...
@endpush
```

...and I include that color picker input several times, it will also push that color library onto the stack multiple times. 

Thus it would be nice if we could specify a unique key when pushing onto a stack, such that if that key already exists, subsequent pushes with that key are ignored.

```
@push('vendor', 'my-unique-key')
   ...
@endpush
```

**Comment by franzliedke** [comment]
You could also introduce a new directive `@push_once` that simply generates a unique key as an implementation detail...
