### ISSUE TITLE
[Proposal] Positional insertion for Collections

### ISSUE THREAD

**Issue by Loilo** [laravel/ideas#650]
I'd like to propose two new methods called `insertBefore` and `insertAfter` for the `Illuminate\Support\Collection` class.

## Motivation
Sometimes there's the need to construct a Collection where a certain order not attainable by the `sort()` method is desired.

I personally came across this requirement when having to programmatically construct a `composer.json`. A basic collection for that purpose was created, then some optional properties had to be inserted at certain positions (e.g. `require-dev` after `require` etc.).

As far as I can tell there is currently no such method available in Laravel's Collection.

## Proposed Solution
> **Side note:**
> * Explanations and examples below only refer to `insertAfter`. Of course, the `insertBefore` method behaves analogical.
> * Example code contains way too much whitespace on purpose. Don't call me crazy, it's just there to help keeping track of stuff during the first read.

The method signature of the suggested methods would be the following:

```php
public function insertAfter (mixed $value, mixed $items): Collection;
```

In words: Calling the `insertAfter` method on a `$collection` takes a `$value` and some `$items` (being anything that can be handled by the `getArrayableItems` method). It merges the given `$items` into the `$collection`. The position where the items are put is determined by the given `$value`:

* If `$value` is a non-string `callable`:
  * Iterate over the `$collection`.
  * Call `$value($item, $key)` on each entry.
  * If the call returns a truthy value, insert the `$items` after that entry.

* Otherwise:
  * Check for the first occurrence of `$value` in the `$collection`.
  * Insert `$items` directly after that.

> **Side note:**
> This proposal has gone through multiple iterations.
> Coming from the `composer.json` generation example, it was only a `insertAfterKey`/`insertAfterKey` thing at first. But I think we'd be better off having a more general solution, not least because having a positional insert that regards keys but not values would be weird.

### Basic Example
To get a more visual grasp of what the `insertAfter` method does, have a look at the following example—it shows the case that led me to thinking about this proposal in the first place:

```php
$composer = collect([
  'name' => 'loilo/my-package',
  'description' => 'An example package to prove a point',
  'require' => [
    'laravel/laravel' => '^5.4'
  ],
  'autoload' => [
    'psr-4' => [
      'Loilo\\MyPackage\\' => 'src/'
    ]
  ]
]);


$composer->insertAfter(
  function ($item, $key) {
    return $key === 'require';
  },
  [
    'require-dev' => [
      'loilo/some-other-dependency' => '^1.0'
    ]
  ]
);

/*
[
  'name' => 'loilo/my-package',
  'description' => 'An example package to prove a point',
  'require' => [
    'laravel/laravel' => '^5.4'
  ],
  'require-dev' => [
    'loilo/some-other-dependency' => '^1.0'
  ],
  'autoload' => [
    'psr-4' => [
      'Loilo\\MyPackage\\' => 'src/'
    ]
  ]
]
*/
```

### Additional Specifications
Below are rules about the behaviour of the proposed methods in general and in some edge cases.

* In analogy to `push` and `prepend`, the proposed methods should modify the original Collection. Laravel doesn't seem to be completely sold on immutability, but if modification is too undesirable, the method names should be changed. In my opinion, `insert*` clearly sounds like modification.

  I think in that case, `mergeBefore` and `mergeAfter` would be a good fit.

* If the check for an item to insert before/after does not yield any results, the `$items` are pushed to the end of the Collection:

  ```php
  collect([
    'foo' => 1,
    'bar' => 2
  ])
    ->insertAfter(
      function ($item, $key) {
        return $key === 'qux';
      },
      [ 'baz' => 3 ]
    );

  // [ 'foo' => 1, 'bar' => 2, 'baz' => 3 ]
  ```

* Each associative key-value pair of the inserted `$items` does only override entries previously associated with their respective key (if present), but also move the key to the correct position:

  ```php
  collect([
    'foo' => 1,
    'bar' => 2,
    'qux' => 3,
    'baz' => 4 // 'baz' goes from here...
  ])
    ->insertAfter(
      function ($item, $key) {
        return $key === 'foo';
      },
      [
        'flob' => 5,
        'baz' => 'gotcha!'
      ]
    );

  /*
  [
    'foo' => 1,
    'flob' => 5,
    'baz' => 'gotcha!', // ...to here.
    'bar' => 2,
    'qux' => 3
  ]
  */
  ```

* No matter if previous associative pairs were removed, the position calculation of the new items must happen before that removal to correctly insert items.

## Implementation
Below is a complete (and unnecessarily heavily commented) working implementation of the proposed methods:

**Update:** Renamed the protected helper method from `insertAt` to `insertNear` for clarification reasons.

```php
/**
 * Insert new items at a calculated position
 *
 * @param  mixed  $value
 * @param  mixed  $items
 * @param  int    $offset
 * @return $this
 */
protected function insertNear ($value, $items, $offset)
{
    // Get items to insert as array
    $itemsArray = $this->getArrayableItems($items);

    // Get associative keys to be removed from current items if necessary
    $keysToIgnore = array_filter(array_keys($itemsArray), 'is_string');
    
    // Determine inserting position of new items
    $oldItemsKeys = array_keys($this->items);
    $oldItemsLength = sizeof($this->items);

    $insertKey = $this->search($value);
    $insertPos = $insertKey === false
        ? $oldItemsLength
        : array_search($insertKey, $oldItemsKeys, true)
    ;
    $insertAtEnd = $insertPos + $offset >= $oldItemsLength;

    // Build the new items iteratively
    $results = [];
    for ($index = 0; $index < $oldItemsLength; $index++) {
        $key = $oldItemsKeys[$index];

        // Insert new items if in the right place
        if (!$insertAtEnd && $index === $insertPos + $offset) {
            $results = array_merge($results, $itemsArray);
        }

        // Exclude existing associative pairs if necessary
        if (is_string($key)) {
            if (!in_array($key, $keysToIgnore, true)) {
                $results[$key] = $this->items[$key];
            }

        // Always append non-associative items
        } else {
            $results[] = $this->items[$key];
        }
    }

    // Append new items after old ones if necessary
    if ($insertAtEnd) {
        $results = array_merge($results, $itemsArray);
    }

    $this->items = $results;

    return $this;
}

/**
 * Insert new items before a certain position
 *
 * @param  mixed  $value
 * @param  mixed  $items
 * @return $this
 */
public function insertBefore ($value, $items)
{
    return $this->insertNear($value, $items, 0);
}

/**
 * Insert new items after a certain position
 *
 * @param  mixed  $value
 * @param  mixed  $items
 * @return $this
 */
public function insertAfter ($value, $items)
{
    return $this->insertNear($value, $items, 1);
}
```

## Tests
The specs from above should mostly be covered by the tests below. The above implementation passes them:

```php
public function testInsertBefore()
{
    // Insertion before scalar value's position
    $c = new Collection(['one', 'two', 'three']);
    $this->assertEquals(['zero', 'one', 'two', 'three'], $c->insertBefore('one', ['zero'])->all());

    // Insertion before callback position
    $c = new Collection(['one', 'two', 'three']);
    $this->assertEquals(['one', 'two', 'zero', 'three'], $c->insertBefore(function ($item, $key) {
        return $item === 'three';
    }, ['zero'])->all());

    // Mixed associative and non-associative pairs
    $c = new Collection(['one', 'two', 'three']);
    $this->assertEquals(['one', 'four', 'five' => 5, 'two', 'three'], $c->insertBefore('two', ['four', 'five' => 5 ])->all());

    // Remove overridden keys at correct position
    $c = new Collection(['one', 'two' => 2, 'three']);
    $this->assertEquals(['two' => 22, 'four', 'one', 'three'], $c->insertBefore('one', ['two' => 22, 'four'])->all());

    // Insert at position of later removed keys
    $c = new Collection(['one', 'two' => 2, 'three']);
    $this->assertEquals(['one', 'two' => 22, 'four', 'three'], $c->insertBefore(2, ['two' => 22, 'four'])->all());

    // Insert after all if no insert position was found
    $c = new Collection(['one', 'two', 'three']);
    $this->assertEquals(['one', 'two', 'three', 'four'], $c->insertBefore(function () { return false; }, ['four'])->all());
}

public function testInsertAfter()
{
    // Insertion after scalar value's position
    $c = new Collection(['one', 'two', 'three']);
    $this->assertEquals(['one', 'zero', 'two', 'three'], $c->insertAfter('one', ['zero'])->all());

    // Insert after last item
    $c = new Collection(['one', 'two', 'three']);
    $this->assertEquals(['one', 'two', 'three', 'zero'], $c->insertAfter('three', ['zero'])->all());

    // Insertion after callback position
    $c = new Collection(['one', 'two', 'three']);
    $this->assertEquals(['one', 'two', 'zero', 'three'], $c->insertAfter(function ($item, $key) {
        return $item === 'two';
    }, ['zero'])->all());

    // Mixed associative and non-associative pairs
    $c = new Collection(['one', 'two', 'three']);
    $this->assertEquals(['one', 'two', 'four', 'five' => 5, 'three'], $c->insertAfter('two', ['four', 'five' => 5 ])->all());

    // Remove overridden keys at correct position
    $c = new Collection(['one', 'two' => 2, 'three']);
    $this->assertEquals(['one', 'two' => 22, 'four', 'three'], $c->insertAfter('one', ['two' => 22, 'four'])->all());

    // Insert at position of later removed keys
    $c = new Collection(['one', 'two' => 2, 'three']);
    $this->assertEquals(['one', 'two' => 22, 'four', 'three'], $c->insertAfter(2, ['two' => 22, 'four'])->all());

    // Insert after all if no insert position was found
    $c = new Collection(['one', 'two', 'three']);
    $this->assertEquals(['one', 'two', 'three', 'four'], $c->insertAfter(function () { return false; }, ['four'])->all());
}
```

**Comment by CupOfTea696** [comment]
I think it'd be cool if `insertAt` was public, and instead of an `$offset` parameter, it would have an `$index` parameter. You'd need to modify the `insertBefore` and `insertAfter` methods as well, to calculate the insert index.

**Comment by Loilo** [comment]
I agree that `insertAt` would be nice, but that'd technically not be the scope of this proposal. `insertAt` implies inserting at a position, my implementation of `insertAt` doesn't do this.

So that's probably me doing poor naming in the first place. Maybe my general method should be renamed to something like `insertNear`.

**Comment by CupOfTea696** [comment]
I'm sure this could be added to the scope, no? Because that `insertAt` method could definitely be used for `insertBefore` and `insertAfter`, which would make your `insertNear` method obsolete if an `insertAt` method would be introduced later on.

**Comment by Loilo** [comment]
It actually would not. If you read the latter two points of the "additional specifications" section, you'll see it's not as trivial as "find the index, insert there".

Consequently, because `insertBefore` and `insertAfter` as specified above couldn't make use of an `insertAt` method and, it belongs into a separate proposal.

**Comment by Loilo** [comment]
Hey @taylorotwell, it would be nice to get some hint why this issue was closed. Did you consider it stale or do you have objections against the proposal itself? (If yes, I'd love to hear a short thought about that.)

**Comment by chrisGeonet** [comment]
Looking for this exact thing. @taylorotwell Any update?

**Comment by ludo237** [comment]
1 year old proposal, probably the code base is not compatible

**Comment by loilo** [comment]
@ludo237 Meh, the architecture of the `Collection` class is pretty simple and stable, the proposal still works as intended. 😉
