### ISSUE TITLE
[Proposal] Pluckables

### ISSUE THREAD

**Issue by nhuebnereagle** [laravel/ideas#651]
- Laravel Version: 5.4.x
- PHP Version:   7.x
- Database Driver & Version:   Any

### Description:

Create a method that can provide a list of `pluck` possibilities. 

### Steps To Reproduce:

```
array_pluckables([
'my' => 
   [
   'nested' => 
      [
          'array' => 'is here'
       ]
   ]
]);
```

The array is iterated and can provide a basic array containing all `pluck possibilities` which could be used against the array.

**Result**
```
[
   0 => 'my',
   1 => 'my.nested',
   2 => 'my.nested.array',
]
```
Perhaps the same functionality for Collections if possible.

Thanks for all your hard work, Laravel is my life's breath <3

**Comment by Dylan-DPC** [comment]
I don't think this is something that should be included in core

**Comment by sebastiandedeyne** [comment]
This kind of already exists, `array_dot`

https://laravel.com/docs/master/helpers#method-array-dot

For your exact use case, you'd need to retrieve the keys, so `array_keys(array_dot($myArray))`

**Comment by Dylan-DPC** [comment]
@themsaid this can be closed
