### ISSUE TITLE
[Proposal] Index Methods for Eloquent

### ISSUE THREAD

**Issue by BrandonSurowiec** [laravel/ideas#652]
I saw this talk last month "RailsConf 2017: The Secret Life of SQL: How to Optimize Database Performance by Bryana Knight": https://www.youtube.com/watch?v=BuDWWadCqIw

Bryana is an engineer at Github and shows how to optimize your database with indexes and even denormalization if necessary. I learned a lot and it would be useful to have an easy way in eloquent to use the following methods:

* FORCE INDEX() 
* USE INDEX() 
* IGNORE INDEX()

(From my understanding these commands are not supported in PostgreSQL.)

This is an old issue request from a few years ago to ask whether a PR would be accepted which Taylor felt at the time was unnecessary. https://github.com/laravel/framework/issues/4625

Would it be accepted now?

Currently we can't do something nice like `Post::forceIndex('index_to_use')->...` and need to do `Post::from(DB::raw('posts FORCE INDEX(index_to_use)')->...` 

Thoughts?

**Comment by fernandobandeira** [comment]
I think that would be a nice addition, just keep in mind that we should add support for this for any database that supports this feature.

That means MySQL and Sqlserver

Syntax change a little bit but Sqlserver also supports FORCE INDEX

```sql
USE AdventureWorks
GO
SELECT c.ContactID
FROM Person.Contact c
WITH (INDEX(AK_Contact_rowguid))
INNER JOIN Person.Contact pc
WITH (INDEX(PK_Contact_ContactID))
ON c.ContactID = pc.ContactID
GO
```

You can ping taylor on slack to be sure if he would consider a PR for this...
