### ISSUE TITLE
[Proposal] Some real default tests to help get new devs started

### ISSUE THREAD

**Issue by BrandonSurowiec** [laravel/ideas#658]
Writing tests can be difficult if a developer has never done it before. It might be useful to have some default Feature tests that test the login, registration and password reset process so there is something to look at  / work off of. It would also make sense to setup PHPunit with a default sqlite memory database.

**Comment by Dylan-DPC** [comment]
I don't think everyone who creates a project needs help with that. It could be in a package

**Comment by BrandonSurowiec** [comment]
I don't think new devs would look for a package. Easy enough to delete the 3/4 extra test files that would be there to start if someone wanted less tests.

**Comment by Dylan-DPC** [comment]
Not really. There are a lot of CRUD packages that work in the same way

**Comment by drbyte** [comment]
NOTE: The login/reg/pwd stuff isn't present unless one runs `artisan make:auth` .... so you wouldn't want those tests present unless you've run that.

**Comment by verax5** [comment]
To be quite frank anyone who's written tests in past won't need any default tests.. documentation does a great job of getting people rolling. I personally think if you're having issue writing even the most basic tests in Laravel it's best to write basic PHP app and run your unit tests there to get grasp of fundamentals. I've noticed a lot of people who have never written tests before start writing tests when they switch to Laravel, I did the same and had my head banging on desk until I went back writing basic tests in vanilla PHP and then switch back to laravel testing.

**Comment by BrandonSurowiec** [comment]
The whole thought behind it is to add some default tests for people completely new to testing. Being able to start from some real tests would be a great help for someone who doesn't know anything. Sure they can read the documentation and that helps, but real code is always good exposure.

**Comment by RikSomers** [comment]
Isn't the `artisan make:auth` there for new devs to get easy scaffolding anyways? I think it would be a great addition. 

Maybe you could put it behind a flag so the default is to generate it without tests, but you could run it like `php artisan make:auth --tests` (or something similar) to get tests that work with the default scaffolding. Great if you want to start refactoring the scaffolding right away!

**Comment by BrandonSurowiec** [comment]
@RikSomers I like the flag idea. Perhaps tests are there by default unless `--no-tests` is passed in.

**Comment by DCzajkowski** [comment]
[The Pull Request](https://github.com/laravel/framework/pull/20562) got closed. I wouldn't expect miracles. This issue, sadly, can be closed.
