### ISSUE TITLE
Collection sorBy no works properly

### ISSUE THREAD

**Issue by stankiewiczpl** [laravel/ideas#661]
Hi.
I need to use
`$collection->sortByDesc('my_key');`
Result of sorting i same as before sorting
 Illuminate\Support\Collection.php in line 996 (LV 5.3), is function sortBy().
In my opinion the mistake is to assign the keys in the old order.
Sorting works properly after few modifcations:
`        foreach (array_keys($results) as $new_key=>$old_key) {
            $results[$new_key] = $this->items[$old_key];
        }
`

The example from https://laravel.com/docs/5.4/collections#method-sortby not works also.
Is my mistake,or not?

**Comment by alexbowers** [comment]
Some reformatting:

```
foreach (array_keys($results) as $new_key => $old_key) {
    $results[$new_key] = $this->items[$old_key];
}
```

Are you able to give a direct re-producable example that doesn't work?

Also, I think this belongs on laravel/framework issues. 

@themsaid

**Comment by Dylan-DPC** [comment]
@themsaid this can be closed
