### ISSUE TITLE
[Proposal] Add Macroable trait to Blueprint class

### ISSUE THREAD

**Issue by unstoppablecarl** [laravel/ideas#662]
There is currently no simple way to extend or swap the `Illuminate\Database\Schema\Blueprint` class. 

 For example, I would like to add the following function:

```php
public function basicEnumColumns() {
    $this->increments('id');
    $this->string('slug')->unique();
    $this->string('display_name');
    $this->text('description')->nullable();
    $this->integer('display_order')->default(0);
}
```

My current implementation to accomplish this is:

```php
namespace App\Helpers;

use Illuminate\Database\Schema\Blueprint;

class BlueprintHelper {
    static public function basicEnumColumns(Blueprint $blueprint) {
        $blueprint->increments('id');
        $blueprint->string('slug')->unique();
        $blueprint->string('display_name');
        $blueprint->text('description')->nullable();
        $blueprint->integer('display_order')->default(0);
    }
}
```

```php
Schema::create('primary_roles', function (Blueprint $table) {
    BlueprintHelper::basicEnumColumns($table);
    $table->string('additional_info');
    // ...
});
```

This works fine, but I would prefer to add the function directly to the `Blueprint` class for api consistency in the migrations that use it. Then it would look like this:
```php
Schema::create('primary_roles', function (Blueprint $table) {
    $table->basicEnumColumns();
    $table->string('additional_info');
    // ...
});
```

I know this seems nitpicky, but all I'm asking is to add one line to implemnet the trait.

**Comment by sebastiaanluca** [comment]
Grouping recurring migration fields would be neat to have. Could've used this tons of times.

Macro all the things!

**Comment by m1guelpf** [comment]
See https://github.com/laravel/framework/issues/19862

**Comment by sisve** [comment]
This issue can be closed since the PR was merged.
