### ISSUE TITLE
[Proposal] Add ability to group routes in router classes

### ISSUE THREAD

**Issue by sebastiaanluca** [laravel/ideas#663]
Similar to the new [macro mixins](https://github.com/laravel/framework/pull/19782), validation rules, et cetera coming in Laravel 5.5, I thought it'd be nice to give the flow of __defining and grouping routes__ a makeover too.

### Current situation

Right now, routes are grouped in `web.php`, `api.php`, and similar plain PHP files normally required in a service provider. This still feels somewhat _hackish_ and can get messy and unwieldy quite fast, especially for medium to large projects.

### How it can work

See the [laravel-router](https://github.com/sebastiaanluca/laravel-router#how-to-use) package for the current implementation and more info.

Create a router class:

```php
<?php

namespace App\Http\Routers;

class UserRouter extends Router
{
    public function map()
    {
        $this->router->group(['middleware' => ['web', 'guest']], function () {
            $this->router->get('/users', ['uses' => 'UserController@index']);
        });
    }
}
```

The above might seem kind of bloated or too much hassle for a single route, but add a few more with each their options and you'll be happy you have routers to split them into :)

Register the router in your app's HTTP kernel:

```php
<?php

namespace App\Http;

use Illuminate\Foundation\Http\Kernel as HttpKernel;

class Kernel extends HttpKernel
{
    /**
    * The application routers to automatically boot.
    *
    * @var array
    */
    protected $routers = [
        \App\Http\Routers\AuthRouter::class,
        \App\Http\Routers\UserRouter::class,
        \App\Http\Routers\NewsRouter::class,
        \App\Http\Routers\MediaRouter::class,
    ];
}
```

All done!

### Benefits of routers

- Ditch plain PHP files and **move to classes** overall (optionally) (factories next? :))
- No more loose routes directory and routes files, but make it part of the `App` namespace, keep it in the same parent namespace as controllers, transformers, … and thus **provide a more cohesive application structure**
- Routes are grouped per functionality (or however one sees fit)
- Single place of entry for routes and routers as they can all be registered in the HTTP kernel (optional). **One place to look** for routes and gives a direct overview of all the types of routes in a project.
- Great for packages to ditch the weird `require_once` or similar syntax inside a method. Here we can either provide a `$routers` variable of some sort that holds a list of routers to register or they can instantiate the routers themselves manually wherever they like (see package for auto-mapping routers).
- Even allows you to conditionally enable or disable a router, perhaps based on environment, without one big `if` around a bunch of routes
- **Overall unified approach** to registering routes, similar to middleware or middleware groups, mixins, …
- It's **entirely optional** (unless you decide to make it not so)

### Remarks

- This functionality is currently already provided as a package and works wonderfully so, but having it readily available to the broadest possible audience as part of the Laravel core would mean all of the above benefits and as a result, better code, better apps, happier developers.
- I agree a root `routes` directory can be useful to immediately follow the flow of a certain resource/action, but I personally haven't used that for over a year now and I don't miss it. The benefits of router classes outweigh the current implementation, plus its entire optional.
- Maybe we can even provide an API and web router by default like now as to give a good example and starting point
- I allowed to set the namespace and other route group options in earlier versions of the package, but removed that functionality again when it proved to be more of a nuisance than a time-saver. This could be re-introduced in a more streamlined way however, enabling users to set group options per router class (think namespace, middleware) instead of creating yet another group with those options around the routes.
- Auto-mapping routers are a thing in the package (by just doing `app(\App\Http\Routers\UserRouter::class)` for instance), but you might want to either keep that feature out of it or have a global method helper perform the action (e.g. `Route::register($router)` or more like `dispatch()` does).
- I named them routers, but since this might be too similar to the core router, maybe route groups or just groups could work too. Lesser 'jazzy' ring to it though.
- Depending on a yes or a no, **I'd be glad to submit a PR for this**

Would love some feedback on this or a 👍  if you want this in Laravel 5.x!

**Comment by taylorotwell** [comment]
Pretty nifty idea but I think I will leave this as a package for now.
