### ISSUE TITLE
[Proposal] Add PostgreSQL CTE(Common Table Expressions) feature to Laravel Query Builder

### ISSUE THREAD

**Issue by kamrava** [laravel/ideas#665]
I can't use PostgreSQL CTE feature in Laravel. So sad...
I need to return a CTE query as **Query Builder**, But I can't.
There is not feature for working with CTEs in Laravel.

Please add this feature.

**Comment by staudenmeir** [comment]
I've created a package for common table expressions: https://github.com/staudenmeir/laravel-cte
