### ISSUE TITLE
Fluent: accept null on constructor

### ISSUE THREAD

**Issue by rentalhost** [laravel/ideas#666]
Currently `Fluent` requires an array on constructor. It could be changed to accept `null` too, then in case where we can receive an `?array` or `?\Traversable`, it keep being valid. The implementation is very simple and has no BC.

```php
    /**
     * Create a new fluent container instance.
     *
     * @param  array|object|null  $attributes
     * @return void
     */
    public function __construct($attributes = null)
    {
        if ($attributes !== null) {
            foreach ($attributes as $key => $value) {
                $this->attributes[$key] = $value;
            }
        }
    }
```

And I know that I can extend this class (was what I did), but I see no reason to it no be part of the core.

PS. Issue #666 😈

**Comment by alexbowers** [comment]
A possible BC would be that the signature has changed, causing `Warning` of incompatible changes if extended

**Comment by rentalhost** [comment]
@alexbowers You mean that?

```php
class Fluent {
    public function __construct($a = null) { // New signature.
    }
}

class NewFluent extends Fluent {
    public function __construct($a = []){ // Old signature.
    }
}
```

It keep working (https://3v4l.org/B8cHo).

**Comment by timacdonald** [comment]
This won't make any difference in functionality. The only thing this would allow is for you to specifically pass through a `null` value, i.e. `new Fluent(null)`, which I personally don't see any value in.

With the current constructor, if you don't pass anything in, it won't loop through anything as the array is empty, so no need for a null check - unless I'm missing something.

```
new Fluent() === new Fluent ([])
```

**Comment by rentalhost** [comment]
> **Tim MacDonald wrote:**
> This won't make any difference in functionality. The only thing this would allow is for you to specifically pass through a null value, i.e. new Fluent(null), which I personally don't see any value in.
> 
> With the current constructor, if you don't pass anything in, it won't loop through anything as the array is empty, so no need for a null check - unless I'm missing something.
> 
> `new Fluent() === new Fluent ([])`

It does. When you have an external source that returns an `?array` (that is now valid for PHP as a nullable array), then it is possible and will be common. There are a workaround, but it should works locally when you do something like `$externalSource ?? []` to avoid errors. But it can be improved on core by accept nullable arguments. 

It is done on `Illuminate\Support\Collection`, where you can pass `null` as argument to constructor and it will create an empty `Collection` without any issues.

**Comment by timacdonald** [comment]
Yea, I removed my comment as I re-read it and realised I was off.

**Comment by rentalhost** [comment]
Oh, great. I thought it was a problem with my page view, so I copied the contents of the email to maintain a context. hehe
