### ISSUE TITLE
[Proposal] add canonicalize method to FormRequests

### ISSUE THREAD

**Issue by Evertt** [laravel/ideas#670]
Right now, `FormRequest` objects have an `authorize()` and a `rules()` method. I propose to change that to `authorize()`, `canonicalize()` and `validate()` (the last one being a renaming of `rules()`).

And in `canonicalize()` you return an array of rules, very similar to validation-rules, but they would be canonicalization rules. For example:

```php
class UpdateUserRequest extends FormRequest
{
    function authorize()
    {
        return $this->user()->id == $this['id'];
    }

    function canonicalize()
    {
        return [
            'email' => 'trim|lower_case';
            'phone' => 'digits', // removes all non-digits
        ];
    }

    function validate()
    {
        return [
            'email' => 'email',
            'phone' => 'phone',
        ];
    }
}
```

What do you guys think?

#### edit

I'm also open to using the word `sanitize` instead of `canonicalize`.

**Comment by coderabbi** [comment]
👍 though it seems that the docs use the word "normalization" instead of "canonization"; I'm also reminded of @daylerees sanitize package from the early days, so would suggest either `normalize()` or `sanitize()` to `canonicalize()` as a more immediately and universally understood alternative (even though you are technically correct, of course). 🤷‍♂️

**Comment by sisve** [comment]
Could we separate the introduction of a new canonicalize/normalize/shazaamize method from renaming rules to validate? The later would be a huge breaking change.

**Comment by Evertt** [comment]
@coderabbi yeah I agree, I think the word `sanitize` is probably more intuitive for people than the word `canonicalize`.

@sisve I agree the breaking change would be quite big. However, I do believe that these should go together, because otherwise the naming doesn't make any sense.

**Comment by decadence** [comment]
![screenshot_1](https://user-images.githubusercontent.com/1434668/27853910-5c108fe2-616d-11e7-88c6-7ea804d9dc7b.png)

**Comment by Evertt** [comment]
Yes that makes sense, so let's try to make an exhaustive list:

* trim (e.g. `trim:+-,left`), including the following arguments:
    * a string of characters to trim, optional (default: space)
    * "left", "right" or "both", to specify which side of the input should be trimmed, optional (default: both).
* min (e.g. `min:8,0,left`), including the following arguments:
    * the minimum number of characters, required
    * the string to pad the input with if it doesn't meet the minimum length, optional (default: space)
    * "left" or "right", to specify which side of the input should be padded, optional (default: right).
* max (e.g. `max:8,left`), including the following arguments:
    * the maximum number of characters, required
    * "left" or "right", to specify which side of the input should be truncated, optional (default: right).
* remove (e.g. `remove:0123456789`), including the following arguments:
    * all characters to remove from the input, required.
* remove_regex (e.g. `remove:[0-9]`):
    * the regex to match for and remove from the input, required.
* numeric, which removes all non-numeric characters
* alpha-numeric, which removes all non-alpha-numeric characters
* digits, which removes all non-digits (the difference with numeric is that this one also removes decimal characters)
* alpha-dash
* lowercase
* uppercase
* int, which casts to int
* bool, which casts to bool
* string, which casts to string
* float, which casts to float, including the following arguments:
    * what to assume is the correct decimal character when it's ambiguous in the input, optional. For example in `"1,000"` it's ambiguous whether the comma is meant as a decimal point or as a thousands-separator. If this argument has been specified then that character will be used, otherwise an exception will be thrown.
* date, which casts to Carbon using `Carbon::parse()`, including the following arguments:
    * the date format, optional. If given then before `Carbon::parse()` is used first `Carbon::createFromFormat()` is tried.
* array, cast to array using `json_decode` (or just returning if the input is already an array)

That's all I could think of right now.

**Comment by sisve** [comment]
Many of the operations involve culture-aware string modifications. Stuff like`lowercase`/`uppercase` would need to know which culture rules to apply. `float` would have no ambiguous if it had a culture to conform to, the culture either uses a dot, or a comma.

1. trim would trim whitespaces, not spaces.
2. the regex rules would need some way to pass in flags (case sensitivity, unicode rules, etc)
3. a reverse regex rule that tells which characters to keep sounds reasonable.
4. the min/max rules can be more clearly named min_length/max_length.

I also note that you say that the functions work with number of characters. Could we clarify that further; are you talking about bytes? Unicode codepoints? Actual graphemes? How many characters is a "Ö"? https://3v4l.org/Xi0bX

One important sanitisation rule would be utf8 normalisation. Due to the fact that php works with "binary strings" makes this important, you need a uniform representation of your characters in your code base. The example with "Ö" has the character encoded in one particular normalisation (D), there are others...

**Comment by Evertt** [comment]
> Many of the operations involve culture-aware string modifications.

I agree. Precisely for that reason I wished Laravel used [jenssegers' date package](https://github.com/jenssegers/date) which is based on Carbon, but adds localization to it.

> Stuff likelowercase/uppercase would need to know which culture rules to apply.

Really? Damn, I was intending to just use `strtolower()` and `strtoupper()`. I prefer to go for simplicity at first at the cost of completeness.

> I also note that you say that the functions work with number of characters. Could we clarify that further; are you talking about bytes? Unicode codepoints? Actual graphemes? How many characters is a "Ö"?

Preferably we would count graphemes, but again, I'd prefer to go for simplicity at first.

> One important sanitisation rule would be utf8 normalisation. Due to the fact that php works with "binary strings" makes this important, you need a uniform representation of your characters in your code base. The example with "Ö" has the character encoded in one particular normalisation (D), there are others...

I never knew this. I'm wondering, would you be willing to write the string related functions to make sure this behaves like it should?

**Comment by garygreen** [comment]
I like this idea except I do think it belongs as more of a package than in the core of Laravel as it can be quite opinionated - I don't like `sanitize` I see it as more of a general `transformer` which is pretty common terminology particular in the API world of things.

It would be cool to be able to do expose a `transform` helper and do stuff like:

```php
transform($data, [
    'users.*.name' => 'ucwords',
    'users.*.postcode' => 'strtoupper',
    'users.*.price' => function($price, $attribute) {
        // Silly example, but let's say first user get's it free.
        if ($attribute == 'users.0.price') {
            return 0;
        }
        return $price;
    }
]);
```

Adding custom transforms:

```php
transform()->add('upper', 'App\Transforms\Transformer@transformUpper');
transform()->add('upper', function($value, $attribute) [
    return strtoupper($value);
});
```

The only thing I would say, is this any better or easier than just mapping over the values?

```php
$data['users'] = collect($data['users'])->map(function($user) {
    return [
        'name' => ucwords($user['name']),
        'postcode' => strtoupper($user['postcode']),
    ];
});
```

I suppose it get's to a point where your adding more 'junk' but in it's raw form the above doesn't look too bad.

**Comment by Evertt** [comment]
@garygreen well yeah your code doesn't look so bad, because you're only applying one rule per field. If you wanted to write more rules per field then it would become real messy real fast.

**Comment by taylorotwell** [comment]
We have a few sanitization issues open right now and I think probably discussion needs to be consolidated onto one issue thread because right now it's a little spread out.

**Comment by sisve** [comment]
Okay, which issue are we consolidating this and others into?
