### ISSUE TITLE
[REQUEST] Split illuminate/foundation

### ISSUE THREAD

**Issue by kevindierkx** [laravel/ideas#672]
It seems `illuminate/foundation` doesn't get split and is only available in the complete framework.
This makes testing simples user models with Authorizable traits a bit of a pain, because this one specific trait is provided only in the foundation component. Forcing me to require the whole framework for just this one trait during CI.

is there a specific reasons this component isn't split?

**Comment by Evertt** [comment]
Maybe it's too tightly coupled to the rest of the framework? As in, Foundation can't do much by itself without any of the other components?

**Comment by alexbowers** [comment]
I've needed this before, for some of the "helpers" to be available in external projects.
