### ISSUE TITLE
[Proposal] Add support for '*' dot syntax on Builder

### ISSUE THREAD

**Issue by driade** [laravel/ideas#683]
Hi, good night.

I think it'd be a useful feature if we could write

```php
$product = Product::where('brand.id', $id)->get();
```

instead of 

```php
$product = Product::whereHas('brand', function ($q) use ($id) {
    $q->where('id', $id);
})->get();
```

Thanks!

**Comment by LonnyX** [comment]
Not good for performance...

**Comment by michaeldkroener** [comment]
We are in PHP, one can extend the Model and implement the behaviour if desired.

**Comment by sisve** [comment]
>  Not good for performance...

@LonnyX Can you clarify how this would be bad for performance?

**Comment by LonnyX** [comment]
> @LonnyX Can you clarify how this would be bad for performance?

My bad, I misread the code, this will not affect performance. But why not simply

```

**Comment by LonnyX** [comment]
> We are in PHP, one can extend the Model and implement the behaviour if desired.
It's not about the extension, you can extend everything, indeed. He is suggesting this as built-in functionality

> @LonnyX Can you clarify how this would be bad for performance?
My bad, I misread the code, this will not affect performance.

What is the difference with this:

```
$products = Brand::findOrFail($id)->products
// or for complexe query
$products = Brand::where('country', 'US')->products
```

**Comment by driade** [comment]
Hi @LonnyX 

Maybe the example using the primary key is not the best possible, though, for example, your code doesn't works exactly as mine (yours throws and error, mine would return an empty Collection).

Let's thing is something a bit more more complicate.

Instead of

```php
function getEbooksByPublisher(Publisher $publisher)
{
    return Book::whereHas('publisher', function ($q) use ($publisher) {
        $q->where('id', $publisher->id);
    })
        ->whereHas('editions.versions', function ($q) {
            $q->whereIn('type', [Version::TYPE_EPUB, Version::TYPE_MOBI]);
        })
        ->get();
}
```

write

```php
function getEbooksByPublisher(Publisher $publisher)
{
    return Book::where('publisher.id', $publisher)
        ->whereIn('editions.versions.type', [Version::TYPE_EPUB, Version::TYPE_MOBI])
        ->get();
}
```

In my opinion this is a common scenario the framework might cover.

**Comment by LonnyX** [comment]
Hmm I understand your case now and yeah this is a very good idea

**Comment by driade** [comment]
(made a typo in the example, sorry, it's $publisher->id)

**Comment by koenhoeijmakers** [comment]
The thing is, how do you know that you're doing a `whereHas` or doing a `where` because you joined the table `publishers`?

Joined:
`Model::join('publishers'...)->where('publishers.name', $name):`

Your proposal:
`Model::where('publishers.name', $name);`

**Comment by driade** [comment]
@koenhoeijmakers You're completely right.

**Comment by driade** [comment]
Another possibility 

```php
function getEbooksByPublisher(Publisher $publisher)
{
    return Book::where(':publisher.id', $publisher->id)
        ->whereIn(':editions.versions.type', [Version::TYPE_EPUB, Version::TYPE_MOBI])
        ->get();
}
```
