### ISSUE TITLE
[Proposal] Ability to create a fake file from any MIME type

### ISSUE THREAD

**Issue by sylouuu** [laravel/ideas#686]
Its good to fake an image with `UploadedFile::fake()->image('image.jpg');` but what about other file types?

In my case I want to test when you upload a file with `audio/mpeg` MIME type. I expected that the `create` could take a MIME type parameter.

Best

**Comment by luizguilhermefr** [comment]
Anybody knows if this feature is already available?

**Comment by ludo237** [comment]
Any update on this? The current version of `UploadedFile::Fale()->create()` is kinda useless without Mime type specification 😕

**Comment by sisve** [comment]
The mimetype is autogenerated from the filename. `UploadedFile::fake()->create('filename.mp3')` will create an UploadedFile instance with mime type `audio/mpeg`. Isn't this enough?

**Comment by vitorbari** [comment]
The full list of extensions => mime type is available at [Illuminate\Http\Testing\MimeType](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Http/Testing/MimeType.php)

**Comment by ludo237** [comment]
@sisve not at all, for example if I create a file `UploadedFile::fake()->create("someaudio.ogg")` it will be converted to `video/ogg` instead of `audio/ogg`.

I know it's seems border line but the same example can be applied to `mpeg` and even `mp4` extensions.

In conclusion I think that a manual override of the mime type could help.

**Comment by sylouuu** [comment]
@sisve You're right, it works.

@ludo237 Creating a .ogg gives me `application/octet-stream` MIME type.

I let this issue open, as @ludo237 described, an extra parameter to force the MIME type without depending on the file extension could be useful for edge cases.

Bests

**Comment by freezer278** [comment]
Have the same problem when i try to test `audio/webm` file upload, it always creates uploaded file with `video/webm` mime type.
