### ISSUE TITLE
[Proposal] Add ceilf helper function

### ISSUE THREAD

**Issue by Ben-Russell** [laravel/ideas#687]
I would like a new helper function that will allow functionality similar to php's base method `ceil()` but with a precision parameter for floats.

I have been using the comment found at:
https://stackoverflow.com/questions/8239600/rounding-up-to-the-second-decimal-place#comment67989595_8239620

```
function ceilf($value, $precision = 0)
{
    $offset = 0.5;
    if ($precision !== 0) {
        $offset /= pow(10, $precision);
    }
    return round($value + $offset, $precision, PHP_ROUND_HALF_DOWN);
}
```

**Comment by Dylan-DPC** [comment]
This isn't needed in the framework but wherever you implement it do consider this:

> Floating point numbers have limited precision. Although it depends on the system, PHP typically uses the IEEE 754 double precision format, which will give a maximum relative error due to rounding in the order of 1.11e-16. Non elementary arithmetic operations may give larger errors, and, of course, error propagation must be considered when several operations are compounded.

from: [the docs](http://www.php.net/manual/en/language.types.float.php)
