### ISSUE TITLE
[Proposal] Inheritance with polymorphic types

### ISSUE THREAD

**Issue by alexweissman** [laravel/ideas#690]
## Current behavior

The `Relation::morphMap` method already allows you to customize the identifier used to store the polymorphic type in the database.  For example, if I have the following model and relation:

```
namespace App;

class Post extends Model
{
    /**
     * Get all of the tags for the post.
     */
    public function tags()
    {
        return $this->morphToMany('App\Tag', 'taggable');
    }
}
```

By default, entries in `taggables` will use the string `App\Post` to indicate that the entity being tagged is a `Post`:

Table `taggables`

| tag_id | taggable_id | taggable_type |
| ---- | ---- | ---- |
|  1   |  1   | `App\Post` |

If I want to override this behavior, I can use `morphMap` to map an alternative identifier for `App\Post`:

```
Relation::morphMap([
    'post' => 'App\Post'
]);
```
`Tag`s for `Post`s will then be represented in the database as:

| tag_id | taggable_id | taggable_type |
| ---- | ---- | ---- |
|  1   |  1   | `post` |

Invoking `Post::tags()` generates a query that searches for the value `post` in the `taggable_type` column.

## The problem

Suppose I extend the `Post` model with a child class - for example, `AdminPost` (on the DB level, suppose I am using the [Table-per-type pattern](https://stackoverflow.com/a/190306/2970321)):

```
namespace App;

class AdminPost extends Post
{
    ...
}
```

If I call `Post::tags()`, the default identifier in the database is `App\Post`, but if I call `AdminPost::tags()` the default identifier in the database will be `App\AdminPost` instead.

In a table-per-type scenario, `Post` and `AdminPost` refer to the same table, and I may want to "canonicalize" both of these classes with a common identifier in the `taggables` table.  In this case, it would be useful if `morphMap` could support multiple mappings for the same identifier:

```
Relation::morphMap([
    // Map both Post and AdminPost objects with the 'post' identifier
    'post' => [
        'App\Post',
        'App\AdminPost'
    ]
]);
```

Then both `AdminPost::tags()` and `Post::tags()` would retrieve the same set of related entities by matching the `post` identifier in the generated query.

Another approach, which might be even more flexible, would be to use different identifiers in the table itself, but allow the query builder to generate a `WHERE taggable_type=___ OR taggable_type=___` clause to match multiple identifiers.  For example:

```
Relation::morphMap([
    'post' => 'App\Post',
    'admin_post' => [
        'App\Post',
        'App\AdminPost'
    ]
]);
```

Invoking `AdminPost::tags()` would match only records in `taggable` with the `admin_post` identifier, whereas invoking `Post::tags()` would match records with the `post` OR `admin_post` identifier.  Essentially this would preserve the subtypes in the database and at the same time introduce the notion of inheritance to polymorphic types.

Finally, a third option would be to simply allow setting a custom list of identifiers in the `morph*` methods.  Developers could specify this list when defining relationships in the base class, and then choose, if they wish, to override the relationship in their child class to set a stricter list of identifiers.

**Comment by llioor** [comment]
@alexweissman do you have a solution for it?

**Comment by alexweissman** [comment]
@llioor I believe I was able to solve my particular use case by changing my data model, which of course isn't ideal.

Has this been resolved in a recent version of Laravel? Otherwise it needs more discussion, but I suppose that until enough other people run into this same problem (or I have time to submit a PR), we should leave this closed.

**Comment by ejunker** [comment]
I ran into this issue. I have Subuser models that extend User. I am using spatie/laravel-permission which using polymorhpic relation for roles. I added some roles to a User instance which created the roles with a model_type of App\User but then later in my app the same user was an instance of Subuser but the roles did not show up because of the different model class.

I am not sure if it would work but it would be nice if you could specify the morph classes in each model as an array and then when Laravel generated the SQL it could do a WHERE IN (...)

For example, in my User class I could specify:
```php
class User extends Model
{
    public static $morphClasses = [
        self::class,
        Subuser::class
    ];
}
```

Illuminate\Database\Eloquent\Concerns\HasRelationships::getMorphClass() which returns a string could be renamed to getMorphClasses() and return an array. Illuminate\Database\Eloquent\Realtions\MorphToMany::addWhereConstraints() could be updated to add a whereIn() query.

**Comment by donnysim** [comment]
I don't think thats ever going to work. When retrieving a morph relation that is named `user` and is mapped to `User` and `Subuser`, how should it know what class you expect to receive? The morph type should more or less be overriden based on context to receive the expected model.
