### ISSUE TITLE
Support dot notation of relation for withCount

### ISSUE THREAD

**Issue by projct1** [laravel/ideas#693]
Now i cant do this:
```php
Model::withCount([
    'revises.order' => function($Q) {
        $Q->where('status_id', 1);
    }
])
```
Got error `Call to undefined method Illuminate\Database\Query\Builder::revises.order()`.

**Comment by ajcastro** [comment]
why is this closed? I believe this is a good idea/syntax... it is analagous with the `with()` method.

**Comment by staudenmeir** [comment]
This would be very complex or even impossible to implement.

You can use `HasManyThrough` for cases with two relationships:

```php
// User::withCount('posts.comments')

User extends Model
{
    public function comments()
    {
        return $this->hasManyThrough(Comment::class, Post::class);
    }
}

User::withCount('comments')
```
