### ISSUE TITLE
Separate PUT and PATCH for resources.

### ISSUE THREAD

**Issue by lucasmichot** [laravel/ideas#694]
Resource Controller are a great feature of Laravel: the update route responds to `PUT` and `PATCH` methods which in most case fine.

However in many cases we want to be able to provide different feature depending on the HTTP verb: 
- a full entity update with `PUT`
- a partial entity update with `PATCH`

_More about PUT/PATCH differences:_

- http://weblog.rubyonrails.org/2012/2/26/edge-rails-patch-is-the-new-primary-http-method-for-updates/
- `PUT` : http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.6
- `PATCH` : http://tools.ietf.org/html/rfc5789

---

At the moment, we have to use some workarounds - one of them coule be:
```php
Route::resource('posts', 'PostController', ['except' => ['update']]);
Route::patch('posts/{post}', '\App\Http\Controllers\PostController@patchUpdate');
Route::put('posts/{post}', '\App\Http\Controllers\PostController@putUpdate');
```

Other solutions might exist, with `Route` macros - In any case no easy out-of-the-box solution exists.

---

This PR introduces the following changes in resource routing:

- The `PATCH/PUT` update route will not be generated anymore
- A `PUT` route will be generated to `...\MyController@replace`
- A `PATCH` route will be generated to `...\MyController@update`

---

**Comment by fernandobandeira** [comment]
I think there shouldn't be a problem separating these routes since anyone that needs to use both of them ends separating them.

The only problem is that currently we are using ``` PUT ``` with the behavior of ``` PATCH ``` on forms, etc so changing ``` PUT ``` to ``` replace ``` will break a lot of app's.

Can we provide an easy solution for ppl that might be migrating their app? Maybe provide a way to change the action name on a service provider like we do for localization...

**Comment by lucasmichot** [comment]
> Can we provide an easy solution for ppl that might be migrating their app? Maybe provide a way to change the action name on a service provider like we do for localization...

yes @fernandobandeira - of course.
With a flag / response trait or middleware also provided in a PR, people could use their PUT/PATCH route still targeting only `Controller@update` method
