### ISSUE TITLE
remove use of == and != from the framework

### ISSUE THREAD

**Issue by xcombelle** [laravel/ideas#698]
original issue: https://github.com/laravel/framework/issues/20141

regarding this issue https://github.com/laravel/framework/issues/19995  Looks like the use of == or != leads to bugs which would be easily avoided by using only strict comparison

A simple search show that they are lot of them

```
$ egrep "([^']!=[^=])" . -R |wc -l
46
$ egrep "([^=!']==[^='])" . -R|wc -l
166

```
A good thing to do would be, once these occurrence removed would be to add a pre or post commit hook to avoid future insertions.

**Comment by deleugpn** [comment]
Could you support your claim with evidence?

**Comment by sisve** [comment]
Well, what is the claim? That php's type juggling when using loose comparisons can lead to bugs? 

https://github.com/laravel/laravel/commit/ba0cf2a1c9280e99d39aad5d4d686d554941eea1

**Comment by sisve** [comment]
Here's another. https://github.com/laravel/framework/commit/7836868e0125e29ed6255f27727c2933105991ec

**Comment by ntzm** [comment]
I wouldn't say remove all of them, occasionally they are useful. However each one should be reviewed and made strict if it doesn't need type juggling.

**Comment by xcombelle** [comment]
How they are useful as long as explicit conversion exists?

**Comment by lucasmichot** [comment]
I cannot agree more guys - unless we use a loose comparison, which happen sometimes.

On the same topic, I am also really favoring using `assertSame` as much as possible in tests, instead of `assertEquals`

---

In any case it will be a huge PR review for taylor, so better pass all these changes step by step

**Comment by xcombelle** [comment]
Is there some case where loose comparison can't be replaced by conversion plus strict comparison?

**Comment by lucasmichot** [comment]
Yeah @xcombelle  almost everywhere 🤣

**Comment by sisve** [comment]
> Is there some case where loose comparison can't be replaced by conversion plus strict comparison?

Yes, specially when we're talking about classes that act like value objects. An example would be comparing two Carbon objects where you _probably_ want to compare if they represent the same instant, not the exact same instance.

**Comment by lk77** [comment]
strict mode is not always an option, we have seen that with the strict mode in select component, with old data being passed to select as string which failing the selection process, cause of a strict mode.

**Comment by xcombelle** [comment]
I don't speak about strict mode, but strict comparison ( === instead of == )

**Comment by xcombelle** [comment]
One solution to avoid the use of == and still allow have equality between objects is to use for this purpose the following function:

```
function objectEquals(a,b) {
    return a == b;
}
```

It is verbose, but it clearly marks the intent.

**Comment by lk77** [comment]
yes i know it's about strict comparison, but for me it could lead to same types of problems like 0 !== '0'

**Comment by xcombelle** [comment]
@lk77 What are the problem you see that '0' !== 0 ? They are not equals at all ?

**Comment by xcombelle** [comment]
By the way the code for objectsEquals I given is incorrect as == still does a loose comparison on object attributes, but different of what  would be the == on object attribute
```

php -r 'error_reporting(E_STRICT); class Foo {public function __construct($a) {$this->$a=$a;}
                             }
                             var_dump( (new Foo("0e3"))  == (new Foo("0e4")));
                             var_dump( "0e3" == "0e4" ); 
                             var_dump( (new Foo("0")) == (new Foo(0)));
                             var_dump( "0"==0);'
bool(false)
bool(true)
bool(true)
bool(true)
```

**Comment by lucasmichot** [comment]
`'0'` and `0` are equals/equivalent but not strictly equals.

To sum up, newly introduced code should always take consideration of strict comparisons, and all code base should be moved to strict comparisons (when possible) step by step (this also include `assertSame` and `assertEquals`)

**Comment by sisve** [comment]
@lucasmichot Is that a suggestion from you, or a new rule for Laravel contributions?

**Comment by lucasmichot** [comment]
Nah it's a suggestion, and a best practice.
Laravel contributions guidelines do not enforce any rule on that

**Comment by lk77** [comment]
yes i know they are not strictly equal, it's the point. We need to be careful, as it can change expected behaviour, introduce bugs etc.. When using old data, i'm expecting that 0 != '0' return false, 
but  0 !== '0' will return true, and this will not work anymore.

**Comment by lucasmichot** [comment]
I've just submitted a small PR https://github.com/laravel/framework/pull/20346 on this topic
Not sure Taylor will merge it though

**Comment by ntzm** [comment]
Thanks @lucasmichot!

**Comment by lucasmichot** [comment]
And another one for positive string comparisons : https://github.com/laravel/framework/pull/20352
