### ISSUE TITLE
[Proposal] Re-order JsonResponse setData order

### ISSUE THREAD

**Issue by ragingdave** [laravel/ideas#701]
Based on trying to integrate with Fractal, I noticed that with the default Laravel JsonResponse (Illuminate\Http\JsonResponse) the order of getting data from a model seems out of order.

For example from JsonResponse:
```
    public function setData($data = [])
    {
        $this->original = $data;
        if ($data instanceof Arrayable) {
            $this->data = json_encode($data->toArray(), $this->encodingOptions);
        } elseif ($data instanceof Jsonable) {
            $this->data = $data->toJson($this->encodingOptions);
        } elseif ($data instanceof JsonSerializable) {
            $this->data = json_encode($data->jsonSerialize(), $this->encodingOptions);
        } else {
            $this->data = json_encode($data, $this->encodingOptions);
        }
        if (! $this->hasValidJson(json_last_error())) {
            throw new InvalidArgumentException(json_last_error_msg());
        }
        return $this->update();
    }
```
This prioritizes `toArray()`, then `toJson`, then `jsonSerialize`.

The almost opposite logic is used in a default Eloquent Model:
```
    public function toJson($options = 0)
    {
        $json = json_encode($this->jsonSerialize(), $options);
        ...
    }
    ...
    public function jsonSerialize()
    {
        return $this->toArray();
    }
````
This logic prioritizes `toJson`, then `jsonSerialize` then `toArray`.

My Proposal is that the order of functions called to generate a JsonResponse follows the order that is used in the Model. In this way, you can actually customize the json response separate from a general array logic.

As such:
```
    public function setData($data = [])
    {
        $this->original = $data;

        if ($data instanceof Jsonable) {
            $this->data = $data->toJson($this->encodingOptions);
        } elseif ($data instanceof JsonSerializable) {
            $this->data = json_encode($data->jsonSerialize(), $this->encodingOptions);
        if ($data instanceof Arrayable) {
            $this->data = json_encode($data->toArray(), $this->encodingOptions);
        } else {
            $this->data = json_encode($data, $this->encodingOptions);
        }
        if (! $this->hasValidJson(json_last_error())) {
            throw new InvalidArgumentException(json_last_error_msg());
        }
        return $this->update();
    }
```
On some initial testing this doesn't seem to break anything based on the current tests. This is partially because the tests only cover each individual case of implementation (ie. Jsonable, JsonSerializable, Arrayable) rather than a true test of all being implemented.

I would say this would be a minor change since overall the flow would be the same since ultimately, by default, `toJson` calls `toArray`, so only edge cases would/could be affected.

**Comment by scrwdnet** [comment]
If I understand correctly I don't think 'refactoring' the `setData` method is the right thing to do here, as you mention there are no integration tests for a full app (obviously), why not just reorder the individual methods in the model if the order is something that bothers you that much?

**Comment by ragingdave** [comment]
The reason I'm suggesting the refactor is because it seems confusing that modifying the `toJson` method on a model has no effect on the json response, but modifying the `toArray` method changes the json response. This just seems unintuitive. Plus, re-ordering the methods on the Model directly could end up causing many more breaking changes, and having `toArray` calling `toJson` doesn't make any sense, IMHO.

**Comment by taylorotwell** [comment]
No plans to implement this right now. But, if you feel this is a true "bug" it belongs more as an issue of laravel/framework.
