### ISSUE TITLE
[Proposal] Decouple testing component from PHPUnit

### ISSUE THREAD

**Issue by shulard** [laravel/ideas#706]
Hello !

I saw that in the Testing component, PHPUnit is called statically so it's a hard dependency for the framework. I think that giving boilerplate code to start testing is a great advantage but if someone prefer using another testing framework (Atoum, Simpletest, Kahlan...) actually he can't.

Maybe adding a bridge to PHPUnit can be a nice move to let users using their testing framework of choice.

**Comment by taylorotwell** [comment]
No plans on changing this for now.
