### ISSUE TITLE
[Proposal] Add custom storage:link path (optional parameter) ?

### ISSUE THREAD

**Issue by fsasvari** [laravel/ideas#710]
Is there any way to create custom storage:link path ?

Now, when we run `storage:link` in terminal, it links "public/storage" with "storage/app/public". Is there any way to create optional parameter in `storage:link` artisan command like `storage:link {path=storage}`.

Code:
https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/Console/StorageLinkCommand.php

**Comment by lk77** [comment]
i think you could just use ln -s

**Comment by fsasvari** [comment]
I know but it could be easier this way :) and more friendly for new developers.

The storage url can be defined in filesystems config file.

**Comment by sisve** [comment]
What's the use case here? Why would you want to change the `public/storage` path? This would mean that the [docs](https://github.com/laravel/docs/blob/f8e09eb17d2d29a4f0650bb259db97d6ba4f1756/structure.md#the-storage-directory) and the [default config](https://github.com/laravel/laravel/blob/master/config/filesystems.php#L54) needs to match too.

This sounds like you want to change a framework component to match your specific use-case, so can you tell us the details of it?

**Comment by fsasvari** [comment]
We are migrating website from old framework to Laravel, and there is `upload` folder instead of `storage`. I know it's very edgy use case but still. 

I can always set disk url to:

    'url' => env('APP_URL').'/upload',

But for new work colleagues it is simpler to use `php artisan storage:link upload` then `ln -s /full-path/ /full-path/`.

I know this is not even in low development priority and you could user `ln -s`, but still, for some type of customization.

**Comment by taylorotwell** [comment]
You can link it as needed using Bash commands, etc.
