### ISSUE TITLE
Throw an error if a model's $primaryKey is an array

### ISSUE THREAD

**Issue by andrechalom** [laravel/ideas#712]
There are lots of closed issues regarding the use of composite primary keys, and all of them have been closed by the dev team (eg. https://github.com/laravel/framework/issues/5517). However, the documentation does not clearly mention that composite keys are not supported, and even has an example for generating a migration with a composite primary key.

I understand the reason why this feature will not be implemented, but can you provide a check to provide the application developers with a clear error when they try to implement a composite primary? As it stands, when I tried to use a composite key in one of my models everything started to fail with an "illegal offset type" error, which is not helpful at all.

(Migrated from https://github.com/laravel/framework/issues/20393)

**Comment by taylorotwell** [comment]
No plans on changing this for now.
