### ISSUE TITLE
[Proposal] Custom resolution for implicit route model binding.

### ISSUE THREAD

**Issue by montyclt** [laravel/ideas#716]
Hi all,

Working in a project, I installed HashIds for ofuscate ID's for routes, but I'm using implicit model binding.

I need use the hashed ID in routes, thats mean, I need a custom resolution of parameter value to a model instance.

Example:
Requesting `application.app/customer/Kd3mD5`, resolve the model with ID 1.

For achieve this, I forked [Illuminate/Database](https://github.com/montyclt/database), [Illuminate/Contracts](https://github.com/montyclt/contracts) and [Illuminate/Routing](https://github.com/montyclt/routing) and I've done this changes:

In `Illiminate\Database\Eloquent\Model`
Added [`resolve`](https://github.com/montyclt/database/blob/master/Eloquent/Model.php#L999) method with the logic thats resolve the model. By default, uses firstOrFail method. The idea is override this method in model class if you want change the logic to resolve it (in my case, decoding first the hashed ID).

In `Illuminate\Routing\ImplicitRouteBinding`
[Delegated resolving logic](https://github.com/montyclt/routing/blob/master/ImplicitRouteBinding.php#L34) to `resolve` method of model.

In `Illuminate\Contracts\Routing\UrlRoutable`
Added [`resolve`](https://github.com/montyclt/contracts/blob/master/Routing/UrlRoutable.php#L13) method to the contract.

Overriding `resolve` method in your model class, you can do a custom resolution logic:

```
public function resolve($parameterValue)
{
    $id = \Hashids::decode($parameterValue)[0];

    return $this->newQuery()->findOrFail($id);
}
```

If it's approved, I can contribute and send the pulls request.

**Comment by montyclt** [comment]
I think a good idea is this method can return the model instance instead of the key value.

**Comment by Dylan-DPC** [comment]
There is already a method called `getKeyName()` which already performs the above functionality

**Comment by Propaganistas** [comment]
@montyclt See https://github.com/propaganistas/laravel-fakeid

**Comment by montyclt** [comment]
I forked [Illuminate/Database](https://github.com/montyclt/database) and [Illuminate/Routing](https://github.com/montyclt/routing) and I've done this changes:

In `Illiminate\Database\Eloquent\Model`
Added `[resolve](https://github.com/montyclt/database/blob/master/Eloquent/Model.php#L999)` method with the logic thats resolve the model. By default, uses firstOrFail method.

In `Illuminate\Routing\ImplicitRouteBinding`
[Delegate resolving logic](https://github.com/montyclt/routing/blob/master/ImplicitRouteBinding.php#L34) to `resolve` method of model.

**Comment by montyclt** [comment]
Forked [Illuminate\Contracts](https://github.com/montyclt/contracts) and added [`resolve`](https://github.com/montyclt/contracts/blob/master/Routing/UrlRoutable.php#L13) method to the `UrlRoutable` contract.

Updated main thread.

**Comment by michaeldyrynda** [comment]
Any reason you'd do this in the model itself over just using [`Route::bind`](https://laravel.com/docs/5.4/routing#explicit-binding) in your service provider?

I feel like using this custom resolution logic in your model, you're no longer using implicit.

**Comment by laurencei** [comment]
As @michaeldyrynda said - this can already be done:

```
    Route::bind('user', function ($value) {
        return App\User::where('id', \Hashids::decode($value))->first();
    });
```

**Comment by montyclt** [comment]
@michaeldyrynda, @laurencei  Two reasons:

- Don't repeat the same logic for all models. I preffer create a base model with resolution logic.
- My app is extendible by the customer application installation in his servers, for do this, I use [modules](https://github.com/nWidart/laravel-modules) and the customer can create owns modules with owns models. I think the customer don't worry creating its provider (can do it, but is optional) and adding its models to the provider, with the same resolution logic for all the models.

**Comment by Dylan-DPC** [comment]
@montyclt I don't think this is something needed in the core. You can extract it into a package if you feel you are going to use it often

**Comment by montyclt** [comment]
@Dylan-DPC Yes, if I can do it with a package, is a good idea create the package, I had not thought about it because I've never created a package for Laravel (I do not even know how to do it, but I'll investigate) and because resolution logic is in the kernel, I thought a package could not alter it.

Thanks you

**Comment by Dylan-DPC** [comment]
Also just a note. Next time you plan on a PR, you don't have to fork illuminate repos. Instead fork `the `laravel/framework` repo.

**Comment by montyclt** [comment]
@Dylan-DPC Sorry, Is my first time when I tried to PR this project, and I don't know how do it. Thanks you for the note.

**Comment by Dylan-DPC** [comment]
No issues :) Here to help :)

**Comment by montyclt** [comment]
I think to extends `Illuminate\Routing\Router`, overriding `substituteImplicitBindings` and rebind my router to the container in the package provider.

I have a doubts doing this:

- Can I rebind a bound interface in the container?
- If in some project, a developer uses it's owns Router and bind it to container, and I create other router in a package and bind it, the developer will lose it implementation.
- Is possible in framework some dependency of the Router class instead of the `router` key bound in the container?

**Comment by flugger** [comment]
Couldn't you instead use a middleware to decode the parameters before they reach the controller?

**Comment by sisve** [comment]
"Custom resolution for implicit binding" ... sounds like you want the [explicit binding](https://laravel.com/docs/5.4/routing#explicit-binding) then?

**Comment by montyclt** [comment]
@flugger Can you explain how I can do it?
@sisve No really, read the @michaeldyrynda and @laurencei comments and my response.

**Comment by flugger** [comment]
Something like this:

```php
<?php

namespace App\Http\Middleware;

class DecodeHashedIds
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \Closure                 $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        collect($request->route()->parameters())->each(function ($value, $parameter) use ($request) {
            $request->route()->setParameter($parameter, \Hashids::decode($value));
        });

        return $next($request);
    }
}
```

**Comment by montyclt** [comment]
@flugger I'm going to try it now, thanks you! 😘 😘

**Comment by montyclt** [comment]
@flagger, Is not working, in the middleware I get the model resolved, if I typehint model and send the hashed ID, NotFoundException is throwed before the middleware is called.

**Comment by flugger** [comment]
When you're adding the middleware in the HTTP kernel, are you adding it to the middleware groups or the global middleware stack. And are you adding it before or after the `SubstituteBindings` middleware? You need to add it before, else the implicit binding will take place first

**Comment by montyclt** [comment]
I was add it to web group after SubstituteBinding, I tried now adding before SubstituteBinding and it's Ok, thanks you!

Can I get in middleware the typehinted class in route?

**Comment by taylorotwell** [comment]
No plans on changing this for now.

**Comment by taylorotwell** [comment]
See resolveRouteBinding.

**Comment by vortechron** [comment]
how to make custom route binding for your CUSTOM class

1. implement Illuminate\Contracts\Routing\UrlRoutable;

2. and implement resolveRouteBinding($parameter) method on your CUSTOM class.
