### ISSUE TITLE
[Proposal] Bind custom keys to Validation Rules

### ISSUE THREAD

**Issue by lorisleiva** [laravel/ideas#717]
Hello,

I am really looking forward to the new way of writing custom validation rule provided in 5.5. Is there a plan to add the ability to bind a extension key to those custom rules? That way we can use them as if they were added using `Validator::extends()`.

I was thinking of something like that:

```php
class MyCustomRule implements Rule
{
    protected $key = 'my_custom_rule'; // Optional property.

    public function passes($attribute, $value) { ... }
    public function message() { ... }
}
```

```php
rules = [
    'title' => 'required|my_custom_rule',
];
```

**Comment by cosecantt** [comment]
That implementation would be very clean and helpful!

**Comment by lorisleiva** [comment]
Okay so regarding the implementation: because the `Validator` will see a `string` and not an instance of `Illuminate\Contracts\Validation\Rule`, we somehow need to bind that string to the class. we have several options.

**1. In the Illuminate `ValidationServiceProvider` by scanning the classes in the `app/Rules` folder.**

 | Pros | Cons |
 | - | - |
 | We can define the key as a property on the class itself (see original example above). | We scan a folder when we might not even need validation. We become coupled to the location of `Rules` folder. |

**2. In an application service provider.** 

by providing an helper like 
```php
Validator::rule('my_custom_rule', App\Rules\MyCustomRule::class)
```
 | Pros | Cons |
 | - | - |
 | No folder scanning. Not tight to any folder location. | Information about the custom rule outside the class. Possible confusion between this and `Validator::extends()`. |

*2.bis Similar idea but in a config file instead. Same dilemma.*

**3. Resolving the key automatically based on the class name.**

When the validator receives the key `my_custom_rule`, it will check the `app/Rules` folder for the class `MyCustomRule` and instantiate it if it exists.

 | Pros | Cons |
 | - | - |
 | No need to bind the key anywhere. | Loose the ability to define a key that is different to the class name. We are again coupled to the location of the `app/Rules` folder. | 

That's all I've got at the moment. Any suggestions?

**Comment by btkostner** [comment]
Just going to throw my 2 cents in here and say number 2 seems like the correct way. It's similar to how the `AuthServiceProvider` works.

```php
protected $rules = [
    'my_custom_rule' => App\Rules\MyCustomRule::class,
];
```

**Comment by mbaeuerle** [comment]
I think the main problem with the string based approach in general is that you can only use the default constructor without passing any arguments into the custom rule.

**Comment by m1guelpf** [comment]
I'd go for two, as it seems consistent with the Console commands and the HTTP Kernel.

**Comment by lorisleiva** [comment]
@mbaeuerle Of course we can. We would be using string parameters like `min:3` or `my_custom_rule:foo,bar,baz`. The challenge here is mostly to find a binding that makes sense between the string with the Rule class. It seems like [it is not going to happen](https://github.com/laravel/framework/pull/21096#issuecomment-328193146) anyway.

**Comment by taylorotwell** [comment]
No plans on changing this for now.
