### ISSUE TITLE
[Proposal] Missing observer class exception

### ISSUE THREAD

**Issue by routegroup** [laravel/ideas#718]
Should we let know developer that given observer to a class, while is registering observers, is missing? Something like to check if class exists before running ```registerModelEvent```.

### Current thing:
1. Register observer for a class (in a boot or service provider).
2. Give it a wrong namespace. (ex. App\UserObserver instead of App\Observers\UserObserver).
3. Run anything that would run event in observer.
4. No exception for a missing class.

**Comment by unstoppablecarl** [comment]
PHP already has a good way to do this.

http://php.net/manual/en/migration55.new-features.php#migration55.new-features.class-name

**Comment by taylorotwell** [comment]
Open to PRs.
