### ISSUE TITLE
Separate $dateFormat per attribute for toJSON()

### ISSUE THREAD

**Issue by stevendesu** [laravel/ideas#719]
- Laravel Version: 5.4.0
- PHP Version: 7.0
- Database Driver & Version: MySQL 5.7

### Description:
I have a model which contains both `date`s and `datetime`s in the database. I access this model primarily through a REST API, using VueJS on the front-end. Therefore it's extremely convenient to, in my controller, simply return the model like so:

```php
public function show($id)
{
    return Model::find($id);
}
```

The issue I run into is that the returned JSON looks something like this:

```json
{"id": 123, "datetime_field": "2017-08-06 01:23:45", "date_field": "2017-08-06 00:00:00"}
```

I then try to use this in VueJS like so:

```html
<input type="date" name="date_field" v-model="date_field" />
```

But the field doesn't get filled in. This is because VueJS expects a string of the form "Y-m-d" for date fields, and expects "Y-m-d H:i:s" for datetime fields.

I cannot use Laravel's `protected $dateFormat` property to fix this, as it similarly breaks the `datetime_field`

I furthermore cannot use Laravel's accessors to resolve the problem like so:

```php
public function getDateFieldAttribute()
{
    return (new Carbon($this->attributes['date_field']))->format('Y-m-d');
}
```

Because this hides the underlying Carbon entity and prevents me from performing logic in my controllers like so:

```php
if ($model->date_field->isToday())
{
    // do stuff...
}
```

### Feature Recommendation:
Extend the `$dateFormat` to allow a map from attribute to format. For instance:

```php
protected $dateFormat = [
    "datetime_field" => "Y-m-d H:i:s",
    "date_field" => "Y-m-d"
];
```

Looking through the Eloquent code briefly, it looks like this would require extending the `getDateFormat()` method to take a parameter (the field for which we want the format), then any calls to `getDateFormat()` would need to be updated to pass this parameter. Backwards compatibility could be easily maintained by checking the type:

```php
protected function getDateFormat($field)
{
    $dateFormat = $this->dateFormat ?: $this->getConnection()->getQueryGrammar()->getDateFormat();
    if (is_string($dateFormat))
    {
        return $dateFormat;
    }
    else if (is_array($dateFormat))
    {
        return $dateFormat[$field];
    }
    else
    {
        throw new Exception("Invalid");
    }
}
```

**Comment by themsaid** [comment]
Check https://github.com/laravel/framework/pull/20463

**Comment by timacdonald** [comment]
Also check: https://github.com/laravel/internals/issues/669#issuecomment-319844105 That is a working implementation you can just put in your base eloquent model to get this without any issues.
