### ISSUE TITLE
[Proposal] When using Mail::fake(), render views to check for exceptions

### ISSUE THREAD

**Issue by mateusjatenee** [laravel/ideas#720]
One thing that happens when you use `Mail::fake()` is that the mailables are just stored in an array. Perhaps we could build the views so the user knows if there is a syntax error or something? what do you guys think?

**Comment by thecrypticace** [comment]
I would typically write separate tests of the mailable that don't use `Mail::fake` but something like the log mail driver (or mail trap — that's a fairly decent one to use too) to ensure that they build and send correctly.

**Comment by mateusjatenee** [comment]
@thecrypticace that's what I do, I just imagine a lot of people don't and get some errors on production (making little changes and relying on the tests that don't actually test that)

**Comment by thecrypticace** [comment]
I'll leave this one for others to decide.

My opinion: Sounds like a good idea on the face of it but it is not necessary as there's an existing way to test it and I don't see a major benefit to rendering views behind the scenes when they're not going to actually be used (or useful afaict) for the tests that use `Mail::fake`.

**Comment by taylorotwell** [comment]
No plans on changing this for now.
