### ISSUE TITLE
please add support for alphabet and spaces in validation 

### ISSUE THREAD

**Issue by ARKKYN** [laravel/ideas#722]

**Comment by ARKKYN** [comment]
please make a modular format for large scale app deployment and also enhance Eloquent Orm better than Doctrine with auto model generation

**Comment by tomschlick** [comment]
lol

**Comment by joshmanders** [comment]
also please implement a `make:unicorn` command that allows me to set a `--mrr` flag to define how much monthly recurring revenue it makes.

**Comment by ntzm** [comment]
You can make your own custom validators.

**Comment by taylorotwell** [comment]
No plans on changing this for now.
