### ISSUE TITLE
please add support for request object and Auth Scafolding

### ISSUE THREAD

**Issue by ARKKYN** [laravel/ideas#723]
please add support for jwt in Auth Scaffolding and add support for user action logging and client information logging by providing browser information etc . with the request object

**Comment by Dylan-DPC** [comment]
I don't think so this is needed in the framework. Can easily be part of a package :smiley:

**Comment by ARKKYN** [comment]
yes it is now a days growth of spa apps and jwt is increasing, so adding support for  jwt and also adding it for Auth it will help more developers reduce time and ALso please add little bit clear documentation for dependency injection 

thanks, @taylorotwell

**Comment by Dylan-DPC** [comment]
Yes growth of SPA apps are increasing. But that doesn't mean everyone needs "JWT". No point adding something that of people will just discard when they install a new app

**Comment by ARKKYN** [comment]
and also people dont need full stack application native like session

**Comment by michaeldyrynda** [comment]
The request object is a wrapper over Symfony's request object - a lot of this information can be pulled out already (user agent, client IP, etc.).

JWT is already available using token authentication - or Passport if you need more functionality.

If you don't need the full stack framework, there's always Lumen.

**Comment by Dylan-DPC** [comment]
Primarly when laravel started, full stack apps were more common than APIs. Also despite a lot of people going towards API, sessions is still an important part. If you look through the history, a lot of things that weren't needed in the core are in seperate repositories -  laravel collective stuff like form facades, ssh (which were earlier part of the framework), passport, horizon etc.

**Comment by taylorotwell** [comment]
No plans on changing this for now.
