### ISSUE TITLE
Filesystem S3 Adapter should support CNAME

### ISSUE THREAD

**Issue by Binternet** [laravel/ideas#726]
When retrieving `Storage::disk('s3')->url('foo.jpg')` it returns the full S3 URL.

The configuration of `s3` disk should have a `cname` option that could be customized for URL retrieval.

**Comment by taylorotwell** [comment]
Open to PRs.

**Comment by Binternet** [comment]
On it, but how can I read filesystem's config file from `\Illuminate\Filesystem\FilesystemAdapter::getAwsUrl`?

**Comment by Binternet** [comment]
Nevermind, [I see this option already exists.](https://github.com/illuminate/filesystem/blob/master/FilesystemAdapter.php#L406)

**Comment by Binternet** [comment]
Nevermind, [I see you can specify the url in the config](https://github.com/illuminate/filesystem/blob/master/FilesystemAdapter.php#L406), that will do the job.
