### ISSUE TITLE
(proposal) apiToken in Bluprint.php

### ISSUE THREAD

**Issue by amirniknami** [laravel/ideas#727]
public function apiToken()
    {
	    return $this->string('api_token', 60)->nullable();
    }

**Comment by amirniknami** [comment]
i do this a lot in my projects i should there should be this wrapper for api token

**Comment by Dylan-DPC** [comment]
What's the advantage of this?

**Comment by amirniknami** [comment]
laravel has some wrapper function for commom table type for example for remember token and for softDelete and etc ... and i create api token filed for my projects a lot .and i think many people make this field to . so it is needed to have a wrapper for increasing coding speed.

**Comment by amirniknami** [comment]
the whole purpose of a framework is increasing coding speed by doing common tasks for developers . don't you think?

**Comment by sisve** [comment]
My api tokens are 64 _bytes_ and non-nullable. How will this change affect me? Why is your usage of api_token good enough to be introduced into the framework, but not mine?

**Comment by amirniknami** [comment]
it could be dynamic .you can pass the argument for the length of it .  one another thing . it was just a suggestion . you could comment more politely . don't you think ?

**Comment by Dylan-DPC** [comment]
> you could comment more politely . don't you think ?
That comment was "polite enough". 

> the whole purpose of a framework is increasing coding speed by doing common tasks for developers . don't you think?

It is. But that doesn't mean any change will be accepted just on pretext of "increasing coding speed". Also it may be common for you but not many others here. You can always extract it to a package in some way if you feel you will be doing it often.

**Comment by ntzm** [comment]
If you wanted to make it dynamic length, it's literally the same as `string()->nullable()`...

**Comment by amirniknami** [comment]
yeah . you are right

**Comment by unstoppablecarl** [comment]
@amirniknami `Blueprint` is macroable now you can add your own functions to it.

**Comment by taylorotwell** [comment]
No plans on changing this for now.
