### ISSUE TITLE
Nested routes implicit binding with parent constraint

### ISSUE THREAD

**Issue by alhoqbani** [laravel/ideas#729]
When we have a nested route for example:
```php
Route::resource('posts.comments', 'PostCommentController');
```

Accessing route `posts/100/comments/200` will return the comment with `id = 200` even if it does not belong to the post with `id  = 100`.

The`PostCommentController@show` method will resolve the comment without any constraint.

Shouldn't this check if there is a relationship exists? and if not return a ModelNotFoundException? or I'm misunderstanding how nested controllers should work?

**Comment by ntzm** [comment]
You have to do that check manually

**Comment by taylorotwell** [comment]
I don't find nested resources truly necessary all that often since you still have a primary key for the child resource.
