### ISSUE TITLE
Route Namespace prefix behaviour break consistency with uses

### ISSUE THREAD

**Issue by vinodraut** [laravel/ideas#731]
- Laravel Version: 5.4.x

### Description:
we use controllers at different folders like components we use route like given below so it can treat namespace from the beginning like so

`Route::get('/xyz', [
    'uses' => '\App\Xyz\ControllerClass@index',
]);`

While it works good but if we have lot of controllers which we want to have under the group it won't work as uses do, so we felt this should follow consistency with **uses**.

`Route::group(['namespace' => '\App\Xyz\'], function () {
   Route::get('/xyz', [
        'uses' => 'ControllerClass@index',
    ]);
});`

This will not work.

**Comment by brunogaspar** [comment]
I'm very confused with this one.

I use namespaced route groups all the time, mainly for this purpose, and they work as expected, even nested namespaced route groups work as well.

So either you're not explaining the issue properly or you're using the feature incorrectly.

Btw, this `Route::group(['namespace' => '\App\Xyz\']` will most likely give you a syntax error, not sure if it was a bad copy paste job or if you were really trying to use it like that.

**Comment by vinodraut** [comment]
Let me explain

By default laravel uses `App\Http\Controllers` etc namespace for controllers, as defined in RouteServiceProvider.

So when you define route in web.php etc you need to add your name space after that. correct?

Suppose you have controller at `App\Http\Controllers\ControllerClass`  then you just need to add it like below in routes.

`Route::get('/xyz', [
     'uses' => 'ControllerClass@index'
]);`

Now suppose you have another controllers with different file structure. like below.

`App\Component\Controllers\ControllerClass`

Now you need to define route like below.

`Route::get('/xyz', [ 
    'uses' => '\App\Component\Controllers\ControllerClass@index'
 ]);`

by adding `\` at beginning you tell uses to start this namespace from the beginning and not from namespace defined in RouteServiceProvider

It works perfect if I use this concept on direct route using **uses** but not with the Namespace prefix on the route group

**It doesn't work**

```
Route::group(['namespace' => '\App\Component'], function () { 
    Route::get('/xyz', [
         'uses' => 'Controllers\ControllerClass@index'
    ]); 
});

```
It uses Namespace like (Not expected):
`App\Http\Controllers\App\Component\Controllers\ControllerClass`

What we expect is this:
`\App\Component\Controllers\ControllerClass`
 
Hope this is more clear now.

**Comment by brunogaspar** [comment]
Ahh i see.. i remember this being discussed before, but i don't use it to be honest, i feel that's very unintuitive.

If i need different namespaces for my controllers, i either remove the namespacing from the service provider and add them on the file or just add a new namespaced group on the service provider that points to a new file.

But in all case, if this works one way but not in groups, it seems a bug.

**Comment by vinodraut** [comment]
We do it by altering the $namespace value in RouteServiceProvider, but now we don't want to alter **Laravel** defaults

**Comment by RikSomers** [comment]
@vinodraut There is nothing wrong with altering the defaults laravel provides if it suits your app's needs. Most of the default values are just there to make the framework work out of the box.

That being said, it does seem like a feature that should be implemented / a bug that should be fixed.

**Comment by vinodraut** [comment]
@RikSomers you are right but most of the times we built products, in that case we consider to minimise our custom alterations to Laravel defaults so the users of our products can develop features further on those products using Laravel Documentation & they shouldn't get stuck in to the problem as defaults not working.

**Comment by taylorotwell** [comment]
No plans on changing this for now.
