### ISSUE TITLE
[Proposal][5.5] default "return view()" on controller to guess the view path

### ISSUE THREAD

**Issue by MohannadNaj** [laravel/ideas#739]
Hello Artisans!

In short, here I want to discuss the possibility of implementing a "guess the view path from the controller and action name" feature. I think it's a great idea. my implementation of it [here](https://github.com/MohannadNaj/framework/commit/922990d13674771d1891aade0178983a47a42278).

#### Background:

I always liked it about .NET MVC projects that's we can do [this](https://github.com/aspnet/MusicStore/blob/4237a93ee8e258a39373ea62715e15fad382311c/samples/MusicStore/Controllers/ManageController.cs#L189):

    public class ManageController : Controller
    {
	    public IActionResult ChangePassword()
	    {
	        return View();
	
	        // or return View(MyViewModel);
	    }
    }

and this will make the Razor Engine to look up the view existence in some defined paths, one of them: the **Manage** (*the controller name*) directory, then the **ChangePassword** view file (*[Manage/ChangePassword.cshtml](https://github.com/aspnet/MusicStore/blob/4237a93ee8e258a39373ea62715e15fad382311c/samples/MusicStore/Views/Manage/ChangePassword.cshtml)*).

I think it's a good idea to have the same functionality applied in laravel.

#### In Laravel:

I may say, we can see a typical Laravel Controller look like this (modified from [here](https://github.com/laracasts/Lets-Build-a-Forum-in-Laravel/blob/53ea141237bb3e0f7d9691397984cd479c69e376/app/Http/Controllers/ProfilesController.php#L18)):

    <?php
    namespace App\Http\Controllers;
    
    class ProfilesController extends Controller
    {
        public function show(User $user)
        {
            return view('profiles.show', ['profileUser' => $user]);
        }
    }

Here, we can see the `profiles` part is repeated in the controller name, and in the parent directory for the view path, and the `show` part is repeated in the action name, and in the view file name.

and that's exactly what Razor engine is doing, guessing the path from the controller name, and the action name.

so what if we can turn that's controller to:

	class ProfilesController extends Controller
    {
        public function show(User $user)
        {
            return view(['profileUser' => $user]);
        }
    }

or if we don't have any data to pass:

        public function index()
        {
            return view();
        }

#### Implementation:

I did my best here to implement and test this functionality, and to be honest, I didn't think it will be this easy. I'm still not sure if this implementation is the "that's it!" or I missed something.

[Here you can see the framework file changes in order to implement this.](https://github.com/MohannadNaj/framework/commit/922990d13674771d1891aade0178983a47a42278)

I don't know if I should PR the changes, and discuss there or see the authors feedback, or I did the right thing by opening the issue here first.

##### when should laravel guess the view path?
there is two cases where we want to know that's now we should guess the path:
1- the controller action method returned `view()` only without any data.
2- the `view(['foo'=>'bar'])` helper method was used by ignoring the string view-path first argument, and received the array data as the first argument.

in case 1, we can't break the `return the view factory instance`, so I considered returning the `view factory instance` as a **Response Content**, is a sign from the user that it should guess the path before throwing the exception.

and that's handled in the Response.php edits.

in case 2, where the first argument is an array of data, we will consider the second argument as the merge data, and we will make the guessed view path instantly.

and that's handled in the `view()` helper method definition.

##### how can laravel guess the view path?
Considering the following action: `App\Http\Controllers\Foo\BarController@baz`.

First, by using the `Str::parseCallback` we will get the controller as the first part before the `@` and the action as the part after.

Then, in the resulted controller `App\Http\Controllers\Foo\BarController`, we will take everything after `Controllers\` in the namespace (result: `Foo\BarController`) , then we will remove -if exists- the commonly used suffix `Controller`. and by replacing the backslash with a dot and applying `lcfirst` for each sub namespace in the controller, we will have a `foo.bar` as a controller. and `baz` as an action. "hearing a voice from the sky: I told you, you should start learning regex ASAP".

#### This post:

here we have two things:

1- the idea itself, is it a good idea to have a guessed view paths? is it going to cause confusion, is encouraging people to follow a predefined structure for views is good or not?

2- the implementation and the details of it, I was just trying to work it out, and suddenly found myself somehow confident about the results.

**Comment by Dylan-DPC** [comment]
I see it in a lot of frameworks  and I was happy that laravel doesn't have it. It includes unwanted magic. And makes it hard to discover for someone looking at it the first time

**Comment by brunogaspar** [comment]
I also agree with @Dylan-DPC and prefer to not see this implemented on the core.

**Comment by m1guelpf** [comment]
You are not having into account standard controller names (index, edit...)

**Comment by vlakoff** [comment]
Agree with the other comments. Coming from a CodeIgniter background, this behavior may be appealing at first glance, but actually it does more harm than good.

Also, you may be interested in the [recently added](https://github.com/laravel/framework/pull/19835) `Route::view()` helper.

**Comment by vlakoff** [comment]
As there is a clear consensus against this proposal, I think this could be closed.

(indeed, I recently went back on a CodeIgniter project, and the "implicit views" did confuse me)

**Comment by taylorotwell** [comment]
No plans on changing this for now.
