### ISSUE TITLE
Why getFromJson() (or __() helper) does not work with groups?

### ISSUE THREAD

**Issue by palypster** [laravel/ideas#740]
We are creating a translations management package. We design it for applications with heavy use of translations. We are wondering, why was getFromJson() method designed not to have an option to set a group translation belongs to? In the source code there is written this note:

```
// For JSON translations, there is only one file per locale, so we will simply load
// that file and then we will be ready to check the array for the key. These are
// only one level deep so we do not need to do any fancy searching through it.
$this->load('*', '*', $locale);
```
and it loads the translations under default '\*' namespace and default '\*' group as well. Why is that so? Shouldn't be better to have the ability - especially for projects with a heavy use of translations - to set up your own group?

According to the Laravel docs:
> **For applications with heavy translation requirements**, defining every string with a "short key" can become quickly confusing when referencing them in your views. For this reason, Laravel also provides support for defining translation strings using the "default" translation of the string as the key.

We think that for applications with heavy translation requirements it is crucial to have some sort of grouping/categorizing.

We of course can work-around it, but we would like to know, if we are not missing anything or if it was designed like that on purpose.

**Comment by taylorotwell** [comment]
No plans on changing this for now.
