### ISSUE TITLE
Allow wherePivot to accept closures for grouped queries

### ISSUE THREAD

**Issue by timacdonald** [laravel/ideas#742]
So, currently you can pass a closure the the Eloquent builders `where` method to create a nested where query.

When working with pivot tables, you can also use the where method to create a nested where query.

I'm currently working on a project that has ceremonies and different cut off times for different aspects of the ceremony. The ceremony is considered closed if...

```php
$this->ceremonies()
    ->wherePivot('submissions_open_at', '<', Carbon::now())
    ->where(function ($query) {
        $query->where($this->ceremonies()->getTable().'.'.'submissions_close_at', '>', Carbon::now())
            ->orWhere($this->ceremonies()->getTable().'.'.'payments_close_at', '>', Carbon::now())
            ->orWhere($this->ceremonies()->getTable().'.'.'uploads_close_at', '>', Carbon::now());
    });
```

This is all fine and works as expected, but does anyone see the benefit in being able to do the same with the `wherePivot` call so we no longer need to append table names etc...

```php
$this->ceremonies()
    ->wherePivot('submissions_open_at', '<', Carbon::now())
    ->wherePivot(function ($query) {
        $query->wherePivot('submissions_close_at', '>', Carbon::now())
            ->orWherePivot('payments_close_at', '>', Carbon::now())
            ->orWherePivot('uploads_close_at', '>', Carbon::now());
    })
```

I have a working PR ready to roll, but wanted to flag it with others before bothering the *boss man* with it and also to get any feedback or 👎 

```php
// BelongsToMany.php

public function wherePivot($column, $operator = null, $value = null, $boolean = 'and')
{
    // add this if condition and contents...
    if ($column instanceof \Closure) {
        $query = $this->getModel()->newQueryWithoutScopes();

        $column($this->newInstanceWithQuery($query));

        $this->query->addNestedWhereQuery($query->getQuery(), $boolean);

        return $this;
    }

    $this->pivotWheres[] = func_get_args();

    return $this->where($this->table.'.'.$column, $operator, $value, $boolean);
}

// add this method...
protected function newInstanceWithQuery($query)
{
    return new static(
        $query,
        $this->parent,
        $this->table,
        $this->foreignKey,
        $this->relatedKey,
        $this->relationName
    );
}
```

**Comment by Ben52** [comment]
Any reason why this was closed?

**Comment by timacdonald** [comment]
@Ben52 I totally jumped the gun on this one. It actually worked perfectly fine as it is with a `where`. This is the working code I have to compare to the above example.

``` php
return $this->ceremonies()
    ->wherePivot('submissions_open_at', '<', Carbon::now())
    ->where(function ($query) {
        $query->where('submissions_close_at', '>', Carbon::now())
            ->orWhere('payments_close_at', '>', Carbon::now())
            ->orWhere('uploads_close_at', '>', Carbon::now());
    })
```

**Comment by ddeath** [comment]
@timacdonald this wont work when you have same field names on pivot and model

**Comment by timacdonald** [comment]
@ddeath so you think there might be something to my original proposal? If so I might PR it.

**Comment by timacdonald** [comment]
I might do some testing to confirm what you mentioned and write up some tests.

**Comment by ddeath** [comment]
@timacdonald yes I do.

Let see what happens with your code if you have column payments_close_at on ceremonies model an also pivot table:
```
return $this->ceremonies()
    ->wherePivot('submissions_open_at', '<', Carbon::now())
    ->where(function ($query) {
        $query->where('submissions_close_at', '>', Carbon::now())
            ->orWhere('payments_close_at', '>', Carbon::now())
            ->orWhere('uploads_close_at', '>', Carbon::now());
    })
```

`Integrity constraint violation: 1052 Column 'payments_close_at' `

**Comment by timacdonald** [comment]
huh, nice. well not nice, but you know what I mean haha. I'll get some tests written and PR this bad boi.

**Comment by timacdonald** [comment]
@ddeath and @Ben52 I've just PR'd this: https://github.com/laravel/framework/pull/21970
