### ISSUE TITLE
Email Verification

### ISSUE THREAD

**Issue by djh101** [laravel/ideas#743]
It seems there was some talk of adding email verification back in 5.2 (https://github.com/laravel/framework/pull/11335/) and the possibility of this being added to 5.3 brought up. It also seems that this was forgotten about so I'd like to bring it up again. The code by tjbp from two years ago seems to be working fine in my project with only one line needing to be changed (_Http/routes.php_ had to be changed).

**Comment by taylorotwell** [comment]
I have this on my internal todo list.
