### ISSUE TITLE
Tag memory-based caches by default using site-wide tag

### ISSUE THREAD

**Issue by aik099** [laravel/ideas#744]
Right now it's easy to get cache collisions (one website is getting cache set by other website) between different Laravel-based websites running on same Web Server. This is usually happening on developer machines and shared hostings.

To solve this I'm proposing to introduce site-wide tag used for all memory-based cache stores. Tag name would be dynamic (built from database connection dsn) with ability to override from config:

```php
'site_serial:' . crc32('mysql://user:pass@host:database')
```

That would allow for `flush` method to be Laravel-based website specific and won't touch any other data on same cache server (e.g. memcache).

It can be implemented like this:

1. when creating memory-based cache stores (e.g. `\Illuminate\Cache\CacheManager::createMemcachedDriver` method):
 * immediately call `tags` method on them using site-wide tag
 * pass result of calling `tags` method to `\Illuminate\Cache\CacheManager::repository` method call
2. add `\Illuminate\Cache\TaggedCache::tags` method (same signature as  `\Illuminate\Cache\TaggableStore::tags`), that will:
 * either replace `TagSet` class instance with new `TagSet` class instance, that will contain all previous tags (e.g. site-wide tag) and user supplied tag names
 * return $this

Change is transparent to developers, because the `tags` method still would return `TaggedStore` class instance.

**Comment by sisve** [comment]
This is already implemented. Change the prefix setting in your [config/cache.php](https://github.com/laravel/laravel/blob/37d39a7cf5b3941072a90b7c52fe43686b8d5b83/config/cache.php#L78-L89).

**Comment by aik099** [comment]
I was aware of that, but unfortunately there is no easy way (or `flush` method would use it) to invalidate cache for particular website without restart of whole cache server (e.g. Memcache).

The best approach would be to somehow merge `\Illuminate\Cache\TagSet::tagId` method functionality (https://github.com/laravel/framework/blob/5.4/src/Illuminate/Cache/TagSet.php#L87) into code that uses `config.cache.prefix` setting.

Now, that I know what `cache.prefix` config setting does I can suggest alternative approach:

1. add `\Illuminate\Cache\CachePrefix`trait, that will have
 * protected `tags` property to store `\Illuminate\Cache\TagSet` class object
 * protected `makeUnique($prefix)` that will create new `\Illuminate\Cache\TagSet` class object using given `$prefix` as tag name and assign it to `tags` property
 * protected `flushUnique` method, that will call `$this->tags->reset()` method
2. in cache stores that use prefix (not necessary also extending `TaggedCache`):
 * use above created trait
 * in constructor replace `$this->prefix = $prefix;` with `$this->prefix = $this->uniquePrefix($prefix);`
 * in `flush` method call only `$this->flushUnique();` method

That would require much less changes as in my original proposal.

**Comment by taylorotwell** [comment]
Open to PRs.
