### ISSUE TITLE
Making mailables testable

### ISSUE THREAD

**Issue by markwalet** [laravel/ideas#747]
I am following the test driven laravel course of Adam Wathan. He is using normal email templates and those are testable.

It is almost impossible to render markdown views in a test.

Something like a public `render()` method would be ideal.

**Comment by brayniverse** [comment]
Looks like that will be available with 5.5 https://github.com/laravel/framework/blob/master/src/Illuminate/Mail/Mailable.php#L168

**Comment by markwalet** [comment]
Awesome!
