### ISSUE TITLE
NotificationFake->sendNow() should trigger event NotificationSent()

### ISSUE THREAD

**Issue by jschlies** [laravel/ideas#749]
Laravel Version: 5.4.*
PHP Version:7.1.2
Database Driver & Version: mysql 5.7.17
Description:

Illuminate\Support\Testing\Fakes\NotificationFake->sendNow() should trigger \Illuminate\Notifications\Events\NotificationSent()

**Comment by taylorotwell** [comment]
This is a bug report, not an idea.
