### ISSUE TITLE
SyncJob does not increment attempts counter

### ISSUE THREAD

**Issue by vyuldashev** [laravel/ideas#754]
- Laravel Version: 5.4
- PHP Version: 7.1

### Description:
[SyncJob](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Queue/Jobs/SyncJob.php#L59) always returns 1 for attempts. Hence, it does not increment when release method is called. 

### Steps To Reproduce:

In any test class:

```
$job = new ExampleJob();

dispatch($job);
$job->attempts(); // returns 1

dispatch($job); // or $job->release()

$job->attempts(); // returns 1, but it it’s not correct
```

### Why do I need it

In my job there is some logic that checks that job attempts === 1, then code x is run, if attempts > 1 it is required to run another code. You should get the point. 

Tests are being executed using sync queue driver and the only solution now to make it work is to create class in tests that extends required Job and has public attempts property which in tests is overridden to desired value. Looks like a dirty solution. 

Also, release method should execute SyncJob again. 

### Conclusion

If this feature can be accepted I will make a PR. Waiting for a feedback.

**Comment by themsaid** [comment]
When a sync job fails it doesn't re-run, an exception is thrown instead. How do you pretend it failed in your tests?

**Comment by vyuldashev** [comment]
```
try {
  // do something...
}
catch (Exception $exception) {
  $this->release(60);
}
```

**Comment by taylorotwell** [comment]
Bug report.
