### ISSUE TITLE
Super simple file uploads... with a slight inconvenience

### ISSUE THREAD

**Issue by piperone** [laravel/ideas#755]
Handling file uploads is very simple now after L5.3. Docs recommends to keep public files in ```storage/public``` and run the ```php artisan storage:link```-command to get the alias. 

A common use case for me with uploaded files, is to persist the resulting path to the database for later use. In a controller handling a file upload, this is what you'd expect:

```php
public function store(MyRequest $request)
{
    $path = $request->file('myfile')->store('public');
    \App\Models\MyFile::create(['path' => $path]);
}
```

The problem with this is that ```$path``` will look something like ```public/aVeryLongFilename.txt``` and later in my views, I will try to use the MyFile-rows this way: ```<img src="{{ asset($myFile->path) }}>```. This yields a 404 because the **alias** created by ```php artisan storage:link``` is named *storage*, not *public*. Hence the path I need to persist is ```storage/aVeryLongFilename.txt```. As far as I can tell, there is no easy, 'Laravelish' way of getting what I want in this case. Up until now, I have used ```str_replace()``` to change 'public' to 'storage'.

Wouldn't it be better if the ```storage:link```-command created an aliased folder with the same name as the folder of which it is an alias? That would squash this inconvenience.

Thanks.

**Comment by sisve** [comment]
You're not dealing with assets, and shouldn't be using `asset()`.

The store method takes a path, not a disk. You need to specify the public disk as the second parameter. `$request->file('myfile')->store($somewhere, 'public')`. This is documented under [File Storage > File Uploads > Specifying A Disk](https://laravel.com/docs/5.4/filesystem#file-uploads).

The path returned by the storage system is opaque and local to the storage implementation. It shouldn't be exposed directly the end-user. Instead, ask the disk for the url to the file. Use `Storage::disk('public')->url($path)` instead. This is documented under [File Storage > Retrieving Files > File URLs](https://laravel.com/docs/5.4/filesystem#file-uploads).

**Comment by piperone** [comment]
@sisve You're happy quoting the docs, so please go read this part: [File Storage > Configuration > The Public Disk](https://laravel.com/docs/5.4/filesystem#the-public-disk). I *am* dealing with assets and the docs even say to use the asset-method.

The files in question are located in the ```storage/app/public```-directory which is what I am specifying in the store()-method. I am not trying to specify a disk and I don't want to specify a filename, because I would like to use the one the storage-system generates for me.

From the docs:
> Laravel makes it very easy to store uploaded files using the store method on an uploaded file instance. Simply call the store method with the path at which you wish to store the uploaded file

An example then follows which is remarkably similar to the one I used in this issue.

**Comment by sisve** [comment]
You're not using the public disk in any of your code examples. You're using the local disk. Both are disks that use the local driver. You need to either change the default disk in your `config/filesystems.php` or specify the public disk when you store the file, and when you generate the url to the file.

Do not use the asset helper for this.
