### ISSUE TITLE
Ability to add middleware to resource controller

### ISSUE THREAD

**Issue by dionysiosarvanitis** [laravel/ideas#757]
It would be useful for `Router::resource` to support adding middleware specifically for any of the routes. Then we could just use it in the following way:

```
    Route::resource('issues', 'IssueController', ['middleware' => [
        'index' => 'can:index',
        'create' => 'can:store',
        'edit' => 'can:store',
        'store' => 'can:store',
        'update' => 'can:update,issue',
        'destroy' => 'can:destroy,issue'
    ]]);
```

Something similar has already been implemented for Resource Routes Naming

```
Route::resource('photo', 'PhotoController', ['names' => [
    'create' => 'photo.build'
]]);
```

**Comment by deleugpn** [comment]
Better to do this in the construct of the controller, no?

**Comment by arvanoid** [comment]
I prefer to decouple my controllers from authz. Therefore, I always define the middleware in routes.

**Comment by unstoppablecarl** [comment]
There is a helper for this on the controller.

https://github.com/laravel/framework/blob/5.5/src/Illuminate/Foundation/Auth/Access/AuthorizesRequests.php#L83


Example
```
class PostController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Post::class);
    }
}
```

Note: Laravel 5.5 does not have an ability mapped to `index` by default.

**Comment by taylorotwell** [comment]
No plans on changing this for now.

**Comment by abdurrahmanriyad** [comment]
Does this have on laravel 5.7?
