### ISSUE TITLE
[Proposal] Allow HTML in default Notification email view template

### ISSUE THREAD

**Issue by syntacticNaCl** [laravel/ideas#759]
It would be great to be able to use HTML in the default Notification email blade. I ran into this when I was trying to set a `salutation()` and discovered I could not use a `<br>`. I propose changing all Blade statements (except for the `actionUrl`) in the `src/Illuminate/Notifications/resources/views/email.blade.php` file from `{{ }}` to `{!! !!}`.

**Comment by taylorotwell** [comment]
Open to PRs.
