### ISSUE TITLE
Rendering Views For Collections no $loop available

### ISSUE THREAD

**Issue by Tjeu** [laravel/ideas#762]
- Laravel Version: 5.4.33
- PHP Version: 7.1.8
- Database Driver & Version: n.a.

### Description:
Within a foreach loop with blade it is possible to access the $loop variable. One would expect this to be the same for the each statement when reading the Laravel documentation. Apparently this is not the case, but I think it would be a nice feature.

### Steps To Reproduce:
template.blade.php

    @foreach ($users as $user)
        @include('layout.user')
    @endforeach

    @each('layout.user', $users, 'user')

layout/user.blade.php

    $loop->iteration

Result:  
Undefined variable: loop  
When you remove the last line from the template.blade.php everything works again as expected.

**Comment by gabriel-caruso** [comment]
This would be nice, a lot of times I needed to use the `$loop` variable inside `@each`, but @atayahmet [already submitted this PR](https://github.com/laravel/framework/pull/19964), but wasn't merged!

**Comment by taylorotwell** [comment]
If this is PR'd again it's needs more solid integration tests.
