### ISSUE TITLE
Add ifEmpty method to Collection object

### ISSUE THREAD

**Issue by Ben52** [laravel/ideas#763]
When I have a collection and want to return it, or a different value if its empty, it would be nice to be able to call an `ifEmpty` method that executes and returns the value, or returns the collection if it is not empty. 
I don't know if there is a fluent way to do that currently.

Any interest in such an addition?

**Comment by Dylan-DPC** [comment]
I don't think this is a need for this in the framework as most people are happy to see an empty collection return the default values. You can create your custom collection over the default Laravel one and add the functionality if you wish to

**Comment by Ben52** [comment]
Makes sense.
I ended up adding this: 
```
Collection::macro('ifEmpty', function($cb) {
		    if(! $this->isEmpty()) return $this;
		    if($cb instanceof Closure) return $cb();
		    return $cb;
	    });
```

**Comment by Dylan-DPC** [comment]
You can close the issue if you don't want to pursue this as a proposal :)

**Comment by timacdonald** [comment]
@ben you might be interested in this

https://github.com/spatie/laravel-collection-macros

**Comment by timacdonald** [comment]
@Ben52 you might be interested in this

https://github.com/spatie/laravel-collection-macros

**Comment by unstoppablecarl** [comment]
At first, I was against this. After trying to write some alternative examples I realized there is not a concise way to write this like you can with an array.

```php
$array = [];
return $array ?: $whatever;
```

The closes you can get is:
```php
return $collection->isNotEmpty() ? $collection : $whatever;
```

Being able to write this would be nice:
```php
return $collection->ifEmpty($whatever);
```

This would be even nicer:

```php
return $collection->or($whatever);
```

**Comment by Dylan-DPC** [comment]
@unstoppablecarl 
>  After trying to write some alternative examples I realized there is not a concise way to write this like you can with an array.

You can do:
```
$array->toArray() ?: 'foo';
!empty($array) ?: 'foo'; 
```

Not as elegant but I don't see much gain in having this function

**Comment by taylorotwell** [comment]
No plans on changing this for now.
