### ISSUE TITLE
Index method removed in authorizeResource ?

### ISSUE THREAD

**Issue by mathieutu** [laravel/ideas#772]
Hi, just a question about resources authorization: 

I've seen that the `index` method was removed of `\Illuminate\Foundation\Auth\Access\AuthorizesRequests::resourceAbilityMap` by @taylorotwell, [here](https://github.com/laravel/framework/commit/d2a41e46949b4cdd45bf0fe3f0fd63dac2ee4858#diff-bb6f96b7b90070077db82955aac3b8a2and) and I can't understand why. 

Resource controllers have this method, why to remove it here ?

Thank's.

**Comment by unstoppablecarl** [comment]
To me, it looks like it was non-trivial assumption that if you can `view` you can also list records. An assumption that could easily be overlooked by someone using this. And overlooking it could be a big deal as this is a security issue.

**Comment by unstoppablecarl** [comment]
Setting your own index ability is pretty clean too

```
class PostController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Post::class);
    }
    
    protected function resourceAbilityMap()
    {
        return array_merge(parent::resourceAbilityMap(), ['index' => 'view']);
    }
}
```

**Comment by mathieutu** [comment]
Yeah of course. I know that you can overwrite it. But it fact this is a missing method here. I'll think about that and maybe try a PR...

**Comment by csiszarattila** [comment]
This hit me too.

Why not use 'index' instead of 'list'? It pretty obvious, right?

**Comment by taylorotwell** [comment]
Because typically you would limit the things you can view in your query.

**Comment by ilumos** [comment]
Building on @unstoppablecarl's snippet, repetition in every controller can be avoided by adding this to your base controller `app\Http\Controllers\Controller.php`:

```php
namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use DispatchesJobs, ValidatesRequests;

    use AuthorizesRequests {
        resourceAbilityMap as protected resourceAbilityMapTrait;
    }

    /**
     * Get the map of resource methods to ability names.
     *
     * @return array
     */
    protected function resourceAbilityMap()
    {
        // Map the "index" ability to the "index" function in our policies
        return array_merge($this->resourceAbilityMapTrait(), ['index' => 'index']);
    }
}
```

This allows you to write a separate policy for listing/indexing a resource, for example:

```php
namespace App\Policies;

use App\User;
use App\RoleAssignment;
use Illuminate\Auth\Access\HandlesAuthorization;

class RoleAssignmentPolicy extends BasePolicy
{
    use HandlesAuthorization;

    /**
     * Determine whether the user can list all roleAssignments.
     *
     * @param  \App\User $user
     * @param  \App\RoleAssignment $roleAssignment
     * @return mixed
     */
    public function index(User $user)
    {
        return false;
    }


    /**
     * Determine whether the user can view a specific roleAssignment.
     *
     * @param  \App\User $user
     * @param  \App\RoleAssignment $roleAssignment
     * @return mixed
     */
    public function view(User $user, RoleAssignment $roleAssignment)
    {
        return true;
    }
```

And of course using `authorizeResource()` in each controller means no need to write lots of repetetive code!

```php
namespace App\Http\Controllers;

use App\RoleAssignment;

class RoleAssignmentController extends Controller
{
    /**
     * RoleAssignmentController constructor.
     */
    public function __construct()
    {
        $this->authorizeResource(RoleAssignment::class);
    }

    // ....
```

It's not too kludgey a workaround, thanks to how Laravel's built.

**Comment by ilumos** [comment]
@taylorotwell Please consider re-adding the index method into `\Illuminate\Foundation\Auth\Access\AuthorizesRequests::resourceAbilityMap` so out of the box we can easily write policies that can allow or prevent listing of **all of a resource's items**.

I agree filtering based on authorization should be done in the query, but in many cases it's very easy to say "only admins should be able to access this resource's index page".

Sure we can currently achieve this using middleware, but why not allow `authorizeResource()` to be able to authorize all resource actions, instead of all but one.

Many thanks!

**Comment by hackel** [comment]
Since reserved keywords like "list" are now allowed as method names as of PHP 7, which Laravel now requires, should this issue be revisited?  I'm currently using it with no ill effects.

**Comment by laassseeee** [comment]
I also tend to use `@can('list', App\User::class)` in blade views to hide a "Users" nav item from non-admins. Would be handy to have list in the authorizeResource array instead of having to add `$this->authorize('list', App\User::class);` to the index method of the UserController. Looks a little bit out of place with only the index method having this custom call, while the rest is solved by "magic".

**Comment by ilumos** [comment]
To add to the above, make sure you `use` the classes specified in the policy, as I believe the gate will silently return false if the policy classes can't be found / resolved. This has caught me out big time in the past.

**Comment by peterthomson** [comment]
For anyone finding this bug in a legacy Laravel system. There is now a viewAny method that can be added to Policies for resourceful controllers. It automatically pairs with the Index method in the Controller.
