### ISSUE TITLE
[Proposal] Give migrations access to command

### ISSUE THREAD

**Issue by mnabialek** [laravel/ideas#777]
When you run seeds you can output anything you want because you have command set, for most migrations it's not necessary to output anything but sometimes in migrations you do something more than playing with database structure and you want to output some data.  At the moment as far as I know it's not easily possible to do this.

@themsaid any chance to approve change like this?

**Comment by deleugpn** [comment]
Would you care to elaborate on an actual use-case for this? Seems a little edge-case for it to be in the core.

**Comment by mnabialek** [comment]
Well, this is exactly same as for seeders. For example in migration you can create some accounts or add something conditionally into database and you would like to know if something was added or it wasn't added because of this or that. Now it's impossible to achieve this in nice way

**Comment by sisve** [comment]
The functionality makes sense, you may want to output some progress information from your seeders. It's already possible via `$this->command->getOutput()->writeln("Hello world!");`

**Comment by sisve** [comment]
Sorry, I totally misread everything. My answer was for seeders, but you're talking about migrations. Ignore it. Pretend it never happened.

**Comment by Dylan-DPC** [comment]
> The functionality makes sense, you may want to output some progress information from your seeders. It's already possible via $this->command->getOutput()->writeln("Hello world!");

@sisve why wouldn't the same work for migrations?

**Comment by taylorotwell** [comment]
No plans on changing this for now.
