### ISSUE TITLE
Opting Out of Package Discovery - Clear goal required

### ISSUE THREAD

**Issue by afraca** [laravel/ideas#784]
I made a brief (somewhat vague) bug report on /laravel/framework here:
https://github.com/laravel/framework/issues/21051

I think it's  pretty self-explanatory. The problem is this: what do we want to do with the dont-discover that our vendor packages have? 

- We want to respect them all
- We only want the dont-discover from the application's composer.json to be respected

As developer of an in-house CMS as an external package required by the application, my pragmatic vote goes to the **first** option. There is one minor downside: 
Requiring a new package in your application can break your package because suddenly a provider is NOT discovered automatically anymore.

**Comment by unstoppablecarl** [comment]
I could see this causing some serious headaches.

Cases for packages with dont-discover dependencies:
- package conditionally registers a dependency service provider
- package needs to register a dependency service provider in a specific order (before or after its own). 

Can anyone think of any other cases?

This brings up a new question how do you control the order of service providers with the package auto-discovery system? I know ideally if everything is in the correct boot/register method order shouldn't matter but there are cases it does (overwriting a binding for example).

It looks like the `vendor/composer/installed.json` determines the order the service providers are registered. I do not know what determines its order though. 

As far as I know currently the only way to completely control it would be to disable all auto discovery and register everything manually in the `config/app.php` providers array.

**Comment by afraca** [comment]
On `installed.json`, it has been noted by @Seldaek that the order CANNOT be relied on.
Honestly, this auto-discovery mechanism feels like a nice trick, but when thinking about it there are just many downsides, exactly the ones @unstoppablecarl  is mentioning.

**Comment by unstoppablecarl** [comment]
I thought Laravel service providers could have a `$parent` property to declare providers that should be registered before them. Maybe I am remembering wrong or confusing it with something else.

**Comment by afraca** [comment]
I don't recognize it, and it's currently not there anymore (on your `$parent` property). 
I think the current **implicit** Laravel stance is that providers should NOT depend too much on order. 

Also, I think even without the discovery we can have a little bit of mess when packages are themselves conditionally loading other providers. (Which is actually what we do ourselves...) That would be when your application is also loading that provider, you then get in an awkward combination. 

With that being already awkward and as there does not seem to be a clear solution for that, I think the logical way for this topic to be my original option number 1:
- Respect the `dont-discover` of ALL packages

Do you get what I mean?

**Comment by unstoppablecarl** [comment]
Yes. How do you resolve 2 packages with the same dependency and one auto-discoveres and one does not?

**Comment by johannesschobel** [comment]
i once suggested to disable `auto-discovery` by using a configuration flag [here](https://github.com/laravel/internals/issues/787)

I would highly appreciate a way to configure it - rather than "searching" in the `composer.json` file to disable it on specific (or all) packages..

**Comment by afraca** [comment]
For future visitors, this was mostly addressed in this PR:
https://github.com/laravel/framework/pull/22443
