### ISSUE TITLE
[Proposal] to have multi delay for each channel

### ISSUE THREAD

**Issue by daison12006013** [laravel/ideas#785]
### Description:
There is no way for us to make a delay for specific channel, Upon checking `NotificationSender`, based on my understanding, the loop call under [L51](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Notifications/NotificationSender.php#L151) only uses the direct value of notification delay.

We have the `sendNow()` which only possible to inject channels in real time sending, however on `send()` we don't have the option to inject, so an option would probably help to, or check out my suggestion below.

### Suggestion:
Allow the property `$delay` to be an array, if it's an array, we will map the channel based on value.

```
public $delay = [
    'push_notification' => Carbon...,
    'email' => Carbon...,
    'database' => Carbon...,
];
```

Since we can't inject carbon directly under the property, a dev can inject the call thru the constructor instead, which is a good work around.

On `NotificationSender`, the mapping will be based on the key channel, if the key doesn't exists, the default value will always be 0.

In reality, we want to limit sending of push notifications when it's evening.

---

Another option is to have a method call `{$channel}Delay()` if exists then we will use that, else we will use 0, so each notifications we can set the delay per channel too.

**Comment by daison12006013** [comment]
anyone who would like to answer this, or atleast leave a comment or suggestion, I'm planning to alter the `NotificationSender` however, I need someone advice so I don't need to do PR and will just be rejected.

**Comment by themsaid** [comment]
I believe if we're going to have this then we may allow a per channel:
- Queue
- Connection
- Delay

**Comment by taylorotwell** [comment]
It's unclear to me what this issue is talking about.

**Comment by sisve** [comment]
Well, it seems like @themsaid understood the problem. Wouldn't it make more sense to ask for clarification than just outright close the issue?

**Comment by lagbox** [comment]
@sisve *shake shake* "Ask again later" *shake shake* "Most likely" *shake shake* "Reply hazy, try again"

**Comment by daison12006013** [comment]
If you have some business that runs on multiple platform, your users are pissed off when they received a lot of push notifications, I can't see any scheduler for each notification service, we only have the `delay()` method which affects across all services activated inside the `via()` method.

Ofcourse there are work around to this kind of scenarios.

```
$notification = new NewJobAvailable();
$notification->only('mail', 'database');
$user->notify($notification);

$notification = new NewJobAvailable();
$notification->only(OneSignalChannel::class);
$user->notify($notification)->delay(push_notification_timing());
// well, the helper push_notification_timing() determines the current time, if the current time landed at 11pm up until 6am, I need to reschedule it at 6:01 to 6:30 randomly.
```

The above code, I separate into 2 `NewJobAvailable` instance, I added a new `only()` method inside the base notification to support the `via()` method on determining which lists of services to be passed inside the `via()`

My approach looks fine, hence the code is redundant.

---

My suggestion is to make Notification as flexible to handle delays per service, not the entire services to delay.

If this is a rare kind of scenario, then I'm fine with it.
