### ISSUE TITLE
Remove bootstrapping for api routes ?

### ISSUE THREAD

**Issue by lakinmohapatra** [laravel/ideas#791]
Hi

We want to remove additional bootstrapping when routes are registered for API .

It's like All Lumen features will be inside Laravel. 

As web is becoming more & more API centric , it will be better to have more API features rather than monolythic structures . 

We also need support for angular 4 .

**Comment by sisve** [comment]
Could you rewrite this issue to clarify what you are proposing? Should this issue perhaps be rewritten into several issues? And how is support for Angular 4 relevant to Laravel as a framework?

**Comment by lakinmohapatra** [comment]
Lumen has been optimized for micro services .
We need same optimisation for Laravel API routes. Because it starts bootstrapping unnecessary stuffs which increases loading time. 

As scaffolding for react & vue are already there. 
We need similar stuffs for angular 4 . If angular 4 will be used , we will use its directory structure . 
We will need Laravel for for api development.

**Comment by sisve** [comment]
So you're asking for two things; 1) optimization for micro services and 2) scaffolding for Angular 4. You should move out the Angular 4 relevant parts to a separate issue, it's separate from the optimization.

I'll only discuss the first point, optimization, in this issue further on.

Can you tell us what ways Lumen has been optimized that is also applicable to Laravel? Do you know what specifically needs to change, and how that can be changed while not breaking existing Laravel installations?

**Comment by drbyte** [comment]
For Angular, perhaps collaborate with https://github.com/laravel-frontend-presets as mentioned in https://github.com/laravel/internals/issues/525

**Comment by themsaid** [comment]
This proposal is unclear, @lakinmohapatra please provide more context or close the issue if you're no longer interested.

Thanks

**Comment by Dylan-DPC** [comment]
This issue has been active for a while. Can be closed.

**Comment by taylorotwell** [comment]
No plans on changing this for now.
