### ISSUE TITLE
[Proposal] String, Array & Collection Packages

### ISSUE THREAD

**Issue by vinkla** [laravel/ideas#792]
Since the string, array and collection helpers are very useful it would be great if we could install them in other packages without downloading everything within the `illuminate/support` package. 

I know the collection class has already been adopted into a new package by Tighten. IMO it would be better to rely on `illuminate/*` packages instead of third-party packages.

We could move the classes into these three packages; `illuminate/array`, `illuminate/string` and `illuminate/collection`. We could still keep the current classes in `illuminate/support` and extend the old classes from the new packages. This means it wont be a breaking change.

This would come in extra handy for developers building framework-agnostic packages.

**Comment by m1guelpf** [comment]
@vinkla I don't think this is going to be a thing, but if it does, it would also be very useful to extract the Macroable trait.

**Comment by vinkla** [comment]
> @vinkla I don't think this is going to be a thing, but if it does, it would also be very useful to extract the Macroable trait.

I know this has been discussed before and you're probably right. I'm just frustrated not having the option to exclude classes I don't need from the `illuminate/support` package.

**Comment by taylorotwell** [comment]
No plans on changing this for now.
