### ISSUE TITLE
[Proposal] 5.5 Remove Filesystem / FileSystemManager inconsistencies

### ISSUE THREAD

**Issue by CupOfTea696** [laravel/ideas#793]
There's a few inconsistencies with creating files between File/Filesystem and Storage/FileSystemManager. 

Storage will ensure the path where it creates a file exists, and if it doesn't create the required missing directories. However, with File, when you try to create a file in a path that has missing part of its tree, it will throw an error. Would it be a good idea to change the File behaviour to the Storage behaviour? I realise Storage is using Flysystem, which is why it behaves this way, but it's very convenient, and I don't think adding that functionality to File is a breaking change.

Secondly, while Storage will throw an Exception when trying to overwrite a file, File uses PHP's `copy` function, and will overwrite files without question. It'd be great if both File and Storage would have the option to overwrite files, and refuse to overwrite files. 

Example:

```php
File::copy($originFile, $existingTarget, $allowOverwrite = true); // No Exception (default behaviour)
File::copy($originFile, $existingTarget, false); // Throws Exception

Storage::copy($originFile, $existingTarget, $allowOverwrite = false); // Throws Exception (default behaviour)
Storage::copy($originFile, $existingTarget, true); // No Exception
```

This would still be slightly inconsistent but would not be a breaking change. We could deprecate the behaviour of `File::copy` not throwing an Exception is change it to throwing an Exception by default in the next major release?

**Comment by taylorotwell** [comment]
They are not intended to be entirely consistent. They serve different purposes.
