### ISSUE TITLE
[Proposal] Return the full prepared sql query

### ISSUE THREAD

**Issue by OwenMelbz** [laravel/ideas#797]
Currently when you do something like

```php
$query = User::where('username', 'my-username')->toSql();
```

You get a response back like 

```
select * from users where username = ?
```

Which isn't great to debug.

Would be great to have to ability of actually seeing the query as it would run.

Heres an example prototype macro of the functionality

```php
\Illuminate\Database\Query\Builder::macro('realQuery', function () {
    $statement = str_replace(' ?', ' %s', $this->toSql());
    $bindings = $this->getBindings();
    
    return sprintf($statement, ...$bindings);
});
```

Is this something that could be considered? or even if it was expanded into a standalone package to pull in?

**Comment by far2** [comment]
You can do that with the [laravel debugbar](https://github.com/barryvdh/laravel-debugbar) package:

![debugbar](https://i.imgur.com/XNYnVoz.png)

It spits out the full query for every query run, with the bindings stripped in.

**Comment by OwenMelbz** [comment]
@far2 you can do a lot with other packages :p

But..

We shouldn't need to add an extra package to just see a query easily.

However...

You need to consider other scenarios e.g if your developing an API and don't have a GUI which renders the debug bar or an command for example.

Or even if your platform that requires an easy way to see the queries e.g. For logging etc.

So although the debug bar provides logging capabilities - it's not really a solution to this specific issue

**Comment by timrcoulson** [comment]
+1 for test debugging as well.

**Comment by deleugpn** [comment]
Laravel Debugbar offers the same output as JSON format for API debugging as well.

**Comment by OwenMelbz** [comment]
@deleugpn read up ^^ :) Says why thats not always appropriate

**Comment by Dylan-DPC** [comment]
@OwenMelbz since the PR got closed I don't see it being added to the framework. You may close the proposal

**Comment by paulofreitas** [comment]
IMO this makes sense by introducing a new optional argument to `toSql()` method itself, not in a new method. This of course would require any proposal to be sent to the next major release since the method signature would be changed. 👍 

Maybe if this get more and more requested they may change their mind. 😛

**Comment by Dylan-DPC** [comment]
Yes. This is something @jakebathman and I were discussing as well. It doesn't need to go to 5.6 as it can be an optional parameter (which isn't a breaking change or at least on the fence). Though i don't see a possibility that it will get accepted.

**Comment by taylorotwell** [comment]
No plans on changing this for now.
