### ISSUE TITLE
artisan key:generate is failing silently

### ISSUE THREAD

**Issue by andrechalom** [laravel/ideas#798]
The code for generating a new APP_KEY in the .env file is [here](https://github.com/laravel/framework/blob/bd352a0d2ca93775fce8ef02365b03fc4fb8cbb0/src/Illuminate/Foundation/Console/KeyGenerateCommand.php#L91)

This works just fine to create a new key and to substitute existing keys under normal circumstances. However, I found out after some hours of debugging that this function does not work correctly if the .env file is malformed, for example:

```bash
APP_K3Y=base64:7Bio4...
```

In this case, the `preg_replace` will not find the required pattern, and the key will not be updated, but the artisan command will return a success message and exit code. 

So:
(1) Is this behavior expected?
(2) Shouldn't `writeNewEnvironmentFileWith` check the `$count` of matches replaced, and throw a warning/error if this is zero? This seems to be coherent with [throwing an error if .env is not found](https://github.com/laravel/framework/pull/7357)
(3) An alternative to (2), maybe the function could append a new line to the end of .env? 

I'll be happy to write a PR after some feedback.

**Comment by jakebathman** [comment]
I’m onboard for throwing an exception, since it’s something the developer should want to know (instead of just adding a new line to .env).

I wonder if there are any deployment/installation scripts that would be impacted by changing the return from this command, but that’s the only downside I see.
