### ISSUE TITLE
Exceptions handler - Incorrect docblock

### ISSUE THREAD

**Issue by Numline1** [laravel/ideas#799]
Hey,

one of our projects recently started being analyzed by phpStan and I've noticed one (possibly) incorrect docblock.

https://github.com/laravel/laravel/blob/master/app/Exceptions/Handler.php

The render method on the laravel/laravel Handler.php render() method seems to specify to return `\Illuminate\Http\Response`, whereas the underlying method being returned (parent::render()) returns a `\Symfony\Component\HttpFoundation\Response`.

Is this by design or can this be fixed? If it's just a simple mistake, I'll have PR ready tomorrow.

**Comment by carusogabriel** [comment]
Many PR were made and Taylor always rejects

**Comment by Numline1** [comment]
@taylorotwell 

![image](https://user-images.githubusercontent.com/12192684/37371777-de8c04e2-2710-11e8-810b-9878753d0869.png)

**Comment by jakesyl** [comment]
@carusogabriel like which ones?
