### ISSUE TITLE
[proposal] Add --tag option to select framework version on laravel installer

### ISSUE THREAD

**Issue by yaronuliel** [laravel/ideas#801]
Hi,
Recently I needed to create a new project that should have been compatible with php 5.6 - when I created the project using the `laravel new` command - it was created using the latest framework version (currently 5.5)

Adding a new option to `laravel/installer` to support choosing version seems to me like a pretty useful thing + it's very easy to implement

(Also useful for package developers who want to check their work on different versions)

I know it is also easy to do by cloning a git tag - but still, the `laravel new` way is the most convenient one

**Comment by alexbowers** [comment]
Perhaps a different command `laravel choose [version] [name]` ?

**Comment by alexbowers** [comment]
That way, `laravel new` indicates the latest.

**Comment by yaronuliel** [comment]
@alexbowers  I think that `new` stands for new project (and not new as latest) so I it still makes sense to use `laravel new` - the version selection I suggest is an option for that..

**Comment by taylorotwell** [comment]
No plans on changing this for now.
