### ISSUE TITLE
Ability to use API resource transformer directly on a collection.

### ISSUE THREAD

**Issue by ivalkenburg** [laravel/ideas#802]
Would be much more readable if you could do:
```php
$clients = Clients::paginate(30)->transformer(ClientResource::class);
```
instead of
```php
$clients = ClientResource::collection(Clients::paginate(30));
```

**Comment by deleugpn** [comment]
API Resources is something new and unlikely to get approved to mix with collections right now  (which is a stable feature). I would recommend you to use a Macro for this for now.
