### ISSUE TITLE
Add support for json inline path operator

### ISSUE THREAD

**Issue by fede91it** [laravel/ideas#804]
As described in the MySQL 5.7 documentation, JSON columns support two search operators. The first is `->` and the second is `->>`. 

Eloquent is already able to manage the operator `->` and the resulting SQL is correct but, when using the operator `->>` in the resulting SQL, the operator `->` is used instead of `->>`.

If in normal cases the operators in practical terms have the same effect, in specific cases it is necessary for the operator `->>` and Laravel should recognize and support this second operator as well. 

Using `->`

```php
Location::where('foo->bar', 'something')
        ->get();
```

outputs

```sql
select * from `locations` where `foo`->'$."bar"' = 'something'
```

But using  `->>`

```php
Location::where('foo->>bar', 'something')
        ->get();
```

outputs the same

```sql
select * from `locations` where `foo`->'$."bar"' = 'something'
```

This issue is also reflected in `Eloquent:: whereIn` method that, because do not support the operator `->>`, it will not work when used on JSON columns, at least if the values of the set will be quoted.

**Comment by taylorotwell** [comment]
Open to PRs.

**Comment by fede91it** [comment]
Could you tell me where I should put hands to add this functionality to Laravel?

**Comment by brayniverse** [comment]
Hey @fede91it I don't know the specifics for adding this functionality but after searching the illuminate/database repository I found the following references to JSON specific logic.

- https://github.com/illuminate/database/blob/0674afca9d18518843f2d23105f0f7f69c19fb7b/Eloquent/Concerns/HasAttributes.php#L562
- https://github.com/illuminate/database/blob/0674afca9d18518843f2d23105f0f7f69c19fb7b/Query/JsonExpression.php

Then driver specific grammars:
- https://github.com/illuminate/database/blob/9ed89ee5b664a14a07ddb479c6163a71752b48e0/Query/Grammars/MySqlGrammar.php
- https://github.com/illuminate/database/blob/f89c35f035b4fb859b980e68944c4a9ad9dcfa03/Query/Grammars/PostgresGrammar.php

I hope this helps you get started.

**Comment by fede91it** [comment]
thanks
