### ISSUE TITLE
[BUG] Login event not dispatched with TokenGuard. (If is intended it must be specified in the docs)

### ISSUE THREAD

**Issue by jhm-ciberman** [laravel/ideas#807]
The `'Illuminate\Auth\Events\Login'` Event is not dispatched when ussing the `TokenGuard` driver. If is not the intended functionality, the bug must be corrected. However, if it is the intended functionality, the behavior should be specified in the documentation, since it's not intuitive. 

I don't know if other events are not dispatched. I have only tested it with the Login event, but if it is the case, the other events should be added also to be homogeneous with the `SessionGuard`. 

Example code to reproduce the event:

in the `EventServiceProvider`:
```php
protected $listen = [
    'Illuminate\Auth\Events\Login' => [
        'App\Listeners\UpdateOnlineAt',
    ],
];
```
And in my event I have:
```php
public function handle(Authenticated $event)
{
    \Log::info("Event dispatched");
    $event->user->online_at = Carbon::now();
    $event->user->save();
}
```
And of course in all my API controllers I have the `'auth'` middleware and the default guard set to `api`.

**Comment by mtrajano** [comment]
I'm not sure if a user is "logging in" per se when authenticating by a token. Token guard doesn't maintain the state of a user, it simply retrieves the user associated with a token every time a token is sent. Or in reality, it shouldn't, I believe Laravel stores the user throughout multiple requests for better performance. This is different from the session guard which maintains the state of the user in the session. I can be wrong though.

**Comment by jhm-ciberman** [comment]
> Either way, you're correct in that it should probably be documented. I believe it can cause some confusion.

It caused confusion to me, and it took me hours of work and digging into Laravel's sourcecode to realize what the problem was. So, I really think that this should be documented. (or added a new different event with different name to avoid conflicts)

**Comment by taylorotwell** [comment]
Open to PRs or documentation here.
