### ISSUE TITLE
[Proposal] Make Database Cache Taggable

### ISSUE THREAD

**Issue by slashequip** [laravel/ideas#812]
Currently the database cache type does not support tagging.

If you are trying to work with caching and tagging locally it is not super easy without having something like Redis setup locally. Enabling tagging for the Database Store would make this much easier.

If we were to introduce an additional column onto the cache table to store the tags would this not be sufficient to allow implementation of a `DatabaseTaggedCache` class? The column could be `JSON` for easy searching of tags when deleting BUT database support for this might be limited so perhaps `TEXT` and use something like a `LIKE` query?

**Comment by taylorotwell** [comment]
No plans on changing this for now.
