### ISSUE TITLE
Handle null relationship better on eloquent

### ISSUE THREAD

**Issue by kocoten1992** [laravel/ideas#813]
```
$computer->cpu->model
```

if cpu is null, access to model will throw

In 5.5, ```optional``` method was introduce, but on eloquent, it should handle it natively (we have higher order message) because if the chain are long, the optional chain doesn't look good:

```
optional(optional($cluster->computer)->cpu)->model
```

Ultimately, it should look like this:
```
$cluster->computer->cpu->model // if any on chain null, null the rest
```

https://gist.github.com/eric1234/7991763

**Comment by sisve** [comment]
Would this still work if I did `if($computer->cpu === null) { ... }`?

**Comment by Dylan-DPC** [comment]
You can just do `$computer->cpu->model ?? 'foo';`

**Comment by Kyslik** [comment]
`optional()` helper is also available.

**Comment by deleugpn** [comment]
What about `withDefault()`?

**Comment by Dylan-DPC** [comment]
Duplicate of #748
