### ISSUE TITLE
[Proposal] Auto Generated Index Names Too Long

### ISSUE THREAD

**Issue by benyanke** [laravel/ideas#814]
_Moved from laravel/framework#21446_

The following function, `Illuminate\Database\Schema\Blueprint::createIndexName()`, given longer table inputs, will generate an index name that is quite long, and has no error checking to ensure that the index name isn't too long.

```php
 protected function createIndexName($type, array $columns)
    {
        $index = strtolower($this->table.'_'.implode('_', $columns).'_'.$type);
        return str_replace(['-', '.'], '_', $index);
    }
```
[link](https://github.com/laravel/framework/blob/d4169a50d88048560ca9f418dad02a05ea67ecfb/src/Illuminate/Database/Schema/Blueprint.php#L1121)

In my brief research, MySQL limits to 64 [in most cases](https://dev.mysql.com/doc/refman/5.7/en/identifiers.html), [MSSQL limits to 128](https://stackoverflow.com/a/19296947/5374301), [PostgreSQL is 63](https://til.hashrocket.com/posts/8f87c65a0a-postgresqls-max-identifier-length-is-63-bytes), and SQLITE [seems to be 63](https://github.com/comfy/comfortable-mexican-sofa/issues/304) (though I'm having trouble finding a better reference for that).

There seems to be no good reason for autogenerated names to be breaking queries. The entire point of an autogenerated name is to make life easier for the developer, not worrying about minor things like index names.

I'd like to propose a check against the index name to get the character limits, and limit to a reasonable limit, such as 62 chars, which would make it compatible with all these databases. Additional logic could be provided to ensure that autogenerated names never go above 62 chars. Perhaps even a simple implementation could be a random string.

Thoughts?

**Comment by benyanke** [comment]
An example implementation could look like this.

It follows the following steps:

1. It follows the existing logic if that logic keeps the string under the char limit
2. If it does not fit, it tries to remove duplicate words, and then checks again. This would keep some semblance of the originally generated key, while making it shorter. 
3. If this does not work, it creates a string containing `index_$tableName` which it then trims to half the char limit, then attaches that to an MD5 of the inputs, allowing this to remain deterministic in it's random generation. This is finally run through a string trim function, to trim the rest of the hash to ensure it fits. The "half the char limit" above is to ensure enough of the hash is present to make it usable.

```php
protected function createIndexName($type, array $columns) {

        $charLimit = 64;

        $index = strtolower($this->table.'_'.implode('_', $columns).'_'.$type);
        $name = str_replace(['-', '.'], '_', $index);

        // If name is too long, try some shortening methods:
        if(strlen($name) < $charLimit) {
                return $name;
        }

        // Remove duplicate words
        $nameExp = explode("_", $name);
        $nameExp = array_unique($nameExp);
        $name = implode("_", $nameExp);

        // Check to see if this was sufficient
        if(strlen($name) < $charLimit) {
                return $name;
        }


        // Hard-cut to char limit

        // If the type itself is too long to even fit, just name the index as 'index_table_HASH'
        $prefix = rtrim(substr("index_" . $this->table,0,($charLimit/2)), "_");
        $hash = "_" . md5($index);

        return substr($prefix . $hash,0,$charLimit);


}
```

**Comment by benyanke** [comment]
To give you a sense of the algorithm, here's a few sample inputs and outputs:

- Out: 'foo_bar_relation_bar_relation_foo_relation_foreign' (50 chars)
  - Type: 'foreign'
  - Cols: ['bar_relation','foo_relation']
  - Table: 'foo_bar_relation'
  - This worked without trimming 

- Out: 'foo_bar_relation_table_values_foreign' (37 chars - down from 70)
  - Type: 'foreign'
  - Cols: ['bar_relation_values','foo_relation_values']
  - Table: 'foo_bar_relation_table'
  - This worked by removing duplicate words. Note that it's still fairly readable, while removing unneeded info we don't have space for.

- Out: 'index_foo_bar_relation_table_b44261c28c63270e382a0bec2ba3a275' (61 chars - down from many)
  - Type: 'foreign'
  - Cols: ['bar_relation_values_long_col_names','foo_relation_value_tables']
  - Table: 'foo_bar_relation_table'
  - This worked by the hashing method, because removing duplicate words didn't solve the issue.

**Comment by ebuildy** [comment]
The fix will break nothing because no key more than 64 is generated yet!

A simple:

```
if (strlen($index) > 64) {
            $index = md5($index).'_'.$type;
        }
```

Will do the trick.
