### ISSUE TITLE
[Proposal] Encapsulation in Eloquent

### ISSUE THREAD

**Issue by lucavallin** [laravel/ideas#816]
Hello,
is it possible and do you think it would make sense to enable encapsulation in Eloquent models?
I believe this is good for abstraction, public properties seem too loose in certain situations and when depending on a class, I cannot make sure that an instance of that class will have certain properties.

```
class UserTransformer {
    public function transform(User $user) {
        return ['name' => $user->name]; // what if I want to depend on an interface instead, or if the name of the property changes, will have to change it everywhere?
    }
}
```

```
class UserTransformer {
    public function transform(UserInterface $user) {
        return ['name' => $user->getName()]; // doesn't really matter what $user is
    }
}
```

Maybe this is not a very clever idea, but I'd like to hear your opinion.

**Comment by RemiCollin** [comment]
It's already possible, juste make your `User` class extends an interface, or maybe I didn't get the intent ?

**Comment by sisve** [comment]
What you've shown in code is very close to [Eloquent: API Resources](https://laravel.com/docs/5.5/eloquent-resources) that was introduced in Laravel 5.5.

If that is not what you're looking for, could you perhaps show some use-cases where this makes sense? As @RemiCollin mentioned, this is already possible by creating and implementing your own UserInterface with the functionality you need.

**Comment by LuCavallin** [comment]
Ok, but for example, in the new API resources, if I do $user->getFriends(), will it behave in the same way as $user->friends, so "auto-serializing" the relationship?
