### ISSUE TITLE
[Proposal] Split QueueManager and Application

### ISSUE THREAD

**Issue by fr05t1k** [laravel/ideas#819]
### Description:
I'm using `illuminate/queue` in my project and I have to use a whole `\Illuminate\Foundation\Application` for 
`Illuminate\Queue\QueueManager`.
What would you think if we split `QueueManager` and `Application`? There only one feature which related to `Application`. Do not start a worker if the app is down for maintenance.

### Steps To Reproduce:

- [ ] We should use `Illuminate\Container` instead of `Application`. 
- [ ] Create another worker (MaintainableWorker and MaintainableQueueManager) which support this feature.

**Comment by deleugpn** [comment]
I'm a fan of the idea

**Comment by crynobone** [comment]
have you read https://github.com/illuminate/queue#illuminate-queue ?

**Comment by fr05t1k** [comment]
@crynobone sure

**Comment by taylorotwell** [comment]
Open to PRs.
