### ISSUE TITLE
[Proposal] Allow `assertJsonStructure` in strict mode on TestResponse

### ISSUE THREAD

**Issue by iget-master** [laravel/ideas#820]
Hi Guys,

The `TestResponse` class have a nice method called `assertJsonStructure()`, that check if the response have that json structure. But it doesn't fails if the response contains more then that structure.

For example, if I have a api endpoint that the response varies if the user is admin or not, including sensitive information for example, I need to check in strict mode.

    $response = $this->getJson('...'); // Imagine that the response returns 'name', 'email', and 'address' fields
    $response->assertJsonStructure(['name', 'email']);

In non strict mode, the test above will pass, but it's leaking sensitive information like `address`.

My suggestion is that we allow a strict mode, changint the method signature from

    public function assertJsonStructure(array $structure = null, $responseData = null)

to

    public function assertJsonStructure(array $structure = null, $responseData = null, $strict = false)

And make it fail when the json structure is different from this.

**Comment by Dylan-DPC** [comment]
Hi yes. I'm the one who made the PR to `assertJson` and converted it to strict mode and later realised that I could have done the same for the other 2 functions. It is a very simple PR so if you want to do it (especially if it is your first time contributing) go ahead and do it :+1: Else I can submit it later

**Comment by iget-master** [comment]
I'll do the PR when have time and propose here.

**Comment by pedzed** [comment]
Why has this been closed? Is it implemented?
