### ISSUE TITLE
[Proposal] Custom Default Exception Rendering

### ISSUE THREAD

**Issue by ejunker** [laravel/ideas#822]
Currently in `Illuminate\Foundation\Exceptions\Handler::renderHttpException()` it checks if a `errors::{$status}` view exists and if so renders it. If not, it goes onto `convertExceptionToResponse()` which renders the exception with Whoops if debug is enabled, otherwise it uses Symfony's exception handler (`Symfony\Component\Debug\ExceptionHandler`) to render the exception.

My proposal is that instead of rendering the exception with Symfony if no view is found for that status code, that Laravel has its own default HTML that is rendered when there is an exception and allow a user to provide their own custom view at `resources/views/errors/default.blade.php` which would be used if it exists.

Alternatively, the code to determine if there is a custom view from `renderHttpException` could be extracted into a new method like the one shown below. This would allow more control and flexibility on how to render an exception.

```
    /**
     * Determine the view to render for the exception.
     *
     * @param \Symfony\Component\HttpKernel\Exception\HttpException  $e
     * @return string
     */
    protected function viewForException(HttpException $e)
    {
        $status = $e->getStatusCode();
        $view = "errors::{$status}";

        return view()->exists($view) ? $view : '';
    }
```

For the company, I work at, we never want to display the Symfony rendered exception because it is not very descriptive. If I was able to define a custom view to use, I could make sure all rendered exceptions contain our company logo and information on how to contact support.

**Comment by Dylan-DPC** [comment]
You could overwrite it with your own exception handler in your projects

**Comment by ejunker** [comment]
@Dylan-DPC I have had to overridden parts of the exception handler to get this functionality. I think it would be useful to have it built-in to Laravel. Laravel already looks for `errors.$status` views, so wouldn't be much different to also look for a `default.blade.php` view.

**Comment by taylorotwell** [comment]
Open to PRs.
