### ISSUE TITLE
[Proposal] Add `forceMake` to Eloquent Builder

### ISSUE THREAD

**Issue by edsamonte** [laravel/ideas#825]
Since there exists `forceCreate` on Builder, it might seem rational to have `forceMake` as well.
This might be helpful if you want to avoid `MassAssignmentException` if the attributes have already been pre-validated before making the model instance. Use-case is common for Repository Design Pattern.

Current workaround on Laravel 5.5 is to use Macros:
```php
Builder::macro('forceMake', function ($attributes) {
    return $this->newModelInstance()->forceFill($attributes);
});
```

**Comment by georgeboot** [comment]
This seems relatively simple. Why not create a PR?

**Comment by edsamonte** [comment]
I agree. I just want to get feedback/reactions if this is really reasonable to add. 🙂

**Comment by taylorotwell** [comment]
Seems generally fine.
