### ISSUE TITLE
Support parsnick/eloquentjs to bring laravel eloquent in the browser.

### ISSUE THREAD

**Issue by ajcastro** [laravel/ideas#830]
See https://github.com/parsnick/eloquentjs.

I suggest to have eloquent available in the browser in just a snap like `parsnick/eloquentjs`. 
We can support that package or create a better package or version for that.

Related #474

**Comment by Dylan-DPC** [comment]
My answer is the same like last time. So i will just quote it:

> not sure if everyone would want this to be in a default project. You could achieve this using a store (like vuex) or create a seperate package for it
