### ISSUE TITLE
Fire events on migrations

### ISSUE THREAD

**Issue by alexbowers** [laravel/ideas#854]
Can we have events fired in Migrations?

I'm thinking:

- `migrations.before`
- `migrations.after`
- `migrations:refresh.before`
- `migrations:refresh.middle`
- `migrations:refresh.after`

etc.

This would allow for things like clearing of the cache when the migrations are being fired.

A use case i've come across is some of our migrations have data populated for User groups and their roles (using spatie laravel permissions).

When trying to run a `migrate:refresh` it will fail on the `migrate` half of it, because of how the caching is setup by default in spatie laravel permissions.

Even though the data is all deleted, it throws exceptions on create attempts because the cache still exists.

I'd like to be able to catch the "after truncate" bit, and clear the cache so that populate works.

There are also use cases for this in production too, such as sending a notification to a monitoring service whenever a migration has been ran, to help track performance metrics before / after migrations etc.

**Comment by alexbowers** [comment]
@taylorotwell I can open a PR to do this, but if possible i'd like feedback about whether you have any immediate objections to this.

**Comment by ttomdewit** [comment]
@alexbowers Were you able to find a solution in the mean time? I'd be rather thrilled to have such events which I can subscribe to.

**Comment by alexbowers** [comment]
I never found a solution to this, I instead changed how our code worked

**Comment by ttomdewit** [comment]
@alexbowers Thats fair enough. I’ve mentioned @driesvints on Twitter and he mentioned they’d appreciate a PR but the final decision lies with @taylorotwell. I’d appreciate such an addition so I might take this upon myself to PR the desired changes.

**Comment by alexbowers** [comment]
@ttomdewit Have you started on this? If not, I can do it this evening.

**Comment by ttomdewit** [comment]
@alexbowers If you’re available, please. I don’t have the time this week.

**Comment by alexbowers** [comment]
@ttomdewit PR sent.
