### ISSUE TITLE
DB::table support sub query

### ISSUE THREAD

**Issue by 354651432** [laravel/ideas#855]
I hope `DB::table` can proc sub query like this
```php
DB::table(function ($query){
    $query->from("memberinfo")->select("id","name")->where("isDelete",0);
},"t1")->get();
```

it can generate sql like this
```sql
select * from ( select id,name from memberinfo where isDelete = 0) t1
```

**Comment by staudenmeir** [comment]
You can use this:

    DB::query()->fromSub(function ($query){
        $query->from("memberinfo")->select("id","name")->where("isDelete",0);
    },"t1")->get();

**Comment by 354651432** [comment]
good what version support `fromSub` method !!

**Comment by staudenmeir** [comment]
Laravel 5.6.12

**Comment by 354651432** [comment]
thanks

**Comment by sisve** [comment]
So, is this feature already implemented? If so, can this issue be closed?
