### ISSUE TITLE
Auto increment without primary key.

### ISSUE THREAD

**Issue by mathieutu** [laravel/ideas#857]
- Laravel Version: 5.5
- PHP Version: 7.1
- Database Driver & Version: Mysql 5.7

### Description:

Hi guys, 
I'm wondering why Laravel is setted to transform automatically any integer with `auto_increment=true` property in primary key..!

This is imo a totally unintuitive way to process.

https://github.com/laravel/framework/blob/d24235a8ee57781391a795f32bc804b504d72323/src/Illuminate/Database/Schema/Grammars/MySqlGrammar.php#L885-L890

I've quickly tried to handle that easily by using `dropPrimary` but for now it doesn't work, we may have to handle that by writing raw queries directly.

### Steps To Reproduce:
```php
$table->uuid('id');
$table->primary('id');
$table->increment('bar')
$table->integer('foo', true);
```

How have you planed to do that, and why to limit standard sql abilities like that ?

Thanks.

**Comment by mathieutu** [comment]
Linked to https://github.com/laravel/framework/issues/21840

**Comment by Kyslik** [comment]
Not sure but take a look around the web: 

https://www.google.sk/search?q=autoincrement%20without%20primary%20key%20mysql&cad=h

Many topics on this I don't think it is strictly related to Laravel, its just good practise?

**Comment by mathieutu** [comment]
No, this issue is directly related to Laravel. Laravel, in the query Grammars, converts a simple auto_increment property in primary key. Mysql and others don't need a primary key to auto_increment. Just a standard index, unique.

**Comment by 36864** [comment]
As for why it does that, probably because that's the most common use-case. The majority of users will use the id field as the primary key, and the default is to make that field auto-increment.

An auto-increment field must be a key (as in, MySQL for example will not even let you define an auto_increment column if it's not a key). That's probably why you're not able to simply drop the key. Try defining a second key for the field before dropping.

**Comment by Dylan-DPC** [comment]
I rarely find the need for any other field to be auto incrementing.

**Comment by iwasherefirst2** [comment]
@Dylan-DPC here is a use-case where it makes sense to have seperate primary key and auto incrementing field: https://stackoverflow.com/questions/47434607/laravel-last-insert-id-is-0-after-insert

**Comment by 36864** [comment]
@iwasherefirst2 What you linked is a case where the auto-incrementing field is part of the key, not a separate key. If it were a separate key, it would be a candidate key, so it might as well be the primary key.

What you linked is more an abuse of the feature than a proper solution for the described problem. An auto-increment field is meant to be unique. In the linked problem, the field being auto-incremented would not be unique.

**Comment by taylorotwell** [comment]
I'm fine with changing it overall but would be a breaking change.
