### ISSUE TITLE
Passport for Lumen

### ISSUE THREAD

**Issue by rogervila** [laravel/ideas#861]
This issue has been commented many times, but I think that Passport should should have support for Lumen.

There are [some packages out there](https://packagist.org/?q=lumen%20oauth&p=0), including a [passport adaptor for lumen](https://github.com/dusterio/lumen-passport), but, in my opinion, Passport support for Lumen needs to be official.

**Comment by skyrpex** [comment]
Yeah. AFAIK, the only reason for Passport to not support Lumen is that uses Facades.

I'd love to contribute.

**Comment by rogervila** [comment]
@taylorotwell would it be possible to addapt Passport for Lumen?

**Comment by crynobone** [comment]
Where exactly does passport uses facades that prevent you from using it with Lumen?

**Comment by taylorotwell** [comment]
Lumen can already consume passport tokens and authenticate them. Lumen is supposed to be a micro-framework focused on APIs so prefer to just let it consume for now.
