### ISSUE TITLE
[Proposal] Replacing a previous hasOne relationship

### ISSUE THREAD

**Issue by luiz-brandao-jr** [laravel/ideas#863]
By definition a hasOne relationship should return only one model, so when saving a hasOne relationship shouldn't it replace the previous one? 

Right now if I want to replace a hasOne relationship with a new model I need to first delete the existing record (or set the foreign key to null if allowed) and then save the new one. 

What are your thoughts on a new `replace` method for the `hasOne` relationship? Something like this:

```php
\Illuminate\Database\Eloquent\Relations\HasOne::replace(Model $model)
{
    $this->delete();

    $this->save($model);
}
```
It just makes sense to be. If one wants to keep the previous record instead of deleting it, she would need to call dissociate first, but we could also introduce a flag for that, something like `replace($model, $dissociate = false)`

Let me know if it's worth it sending a PR over.

**Comment by taylorotwell** [comment]
Fine with me.
