### ISSUE TITLE
[Question] Why is there no artisan command like `make:db` ?

### ISSUE THREAD

**Issue by wata727** [laravel/ideas#867]
Hi all,

When I first developed an application with Laravel, I'm confused that there was no way to create a database. I want to run migration smoothly as follows:

```
$ laravel new myapp
$ php artisan make:migration
$ php artisan make:db
$ php artisan migrate
```

Is there any reason why such a command does not exist? If not, is such a feature accepted?

Thanks.

**Comment by wata727** [comment]
@sisve Thanks for your quick reply. This command reads the database name and the kind of database from the configuration, and creates the database accordingly. This feature allows the user to set up the required database quickly.

In addition, thank you for your opinion about the name. As a result of rethinking, I think `db: create` is the proper name.

I have not started this work yet, but I think that the implementation of Rails probably will be helpful. In Rails, there is already the feature like this.

MySQL:
https://github.com/rails/rails/blob/v5.1.4/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb#L279

PostgreSQL:
https://github.com/rails/rails/blob/v5.1.4/activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb#L46

SQLite3:
https://github.com/rails/rails/blob/v5.1.4/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb#L30

**Comment by bennxumalo25** [comment]
You can add this to your application, as an new command...
 have a look here
https://anthonysterling.com/posts/using-an-artisan-command-to-create-a-database-in-laravel-or-lumen.html

**Comment by benyanke** [comment]
@bennxumalo25 
Shouldn't that be using config() instead of env?

I agree, this would be a useful addition, and would love to see it implemented. Creating the DB is a natural part of migration which should be included.

**Comment by bennxumalo25** [comment]
@benyanke  I think its a better practice to use env but then again it depends on how you feel.

**Comment by michaeldyrynda** [comment]
The problem with using `env` is that the variables are unavailable if you’re caching your configuration (unless you’re using proper environment variables, as opposed to the `.env` file)

**Comment by bennxumalo25** [comment]
php artisan config:cache

any comments?

**Comment by michaeldyrynda** [comment]
Yes, if you run that command, any call to `env()` outside of your confit files will return `null`, unless they’re real environment variables.

**Comment by bennxumalo25** [comment]
makes sense

**Comment by benyanke** [comment]
The laravel way to do things is to use your config files for config, then use env() in the config files, if there are things that change from env to env. That allows you to easily make settings global or env-specific without changing all your code.

**Comment by skyrpex** [comment]
> Creating the DB is a natural part of migration which should be included.

I don't think this way: IMO that's part of the environment setup (something that sysadmins / devops should do).

Also, which databases should that command create? You can have multiple database configurations in `config/database.php`.
