### ISSUE TITLE
[Proposal] Add $model->loadCount function

### ISSUE THREAD

**Issue by manniL** [laravel/ideas#869]
While `$model->load()` and `$model->loadMissing()` functions for eager-loading (missing) relationships exists, no  `$model->loadCount()` function is present.

It might be useful to have a `Model::withCount()` pendant :)

**Comment by hulkur** [comment]
As I need it myself I'm willing to do a PR if this is something a framework would accept.

**Comment by staudenmeir** [comment]
https://github.com/laravel/framework/pull/25997 already added a `Collection::loadCount()` method. So `Model::loadCount()` wouldn't be a big step.

**Comment by driesvints** [comment]
Closing this as this has been merged.
