### ISSUE TITLE
Feature request: Ability to see URL for events logged in log - especially errors

### ISSUE THREAD

**Issue by UnrulyNatives** [laravel/ideas#879]
Today the ability to see URL which produces error helped me to resolve important issue, which troubled me for some time. I recommend that the URL info `url()->current()` would be included in the debug stack. At least as an option. 

In my example: in one blade template I have mistakenly reversed parameter and Model instance ID in the code which was generating URL.

**Comment by taylorotwell** [comment]
Probably could be added to context data when we add user ID... open to PRs.

**Comment by taylorotwell** [comment]
Actually can be done by overriding context() method of exception handler...

something like `return array_merge(['url' => request()->fullUrl()], parent::context());`

**Comment by sisve** [comment]
Keep in mind that an exception thrown when reading data for the context can cause a call to the exception handler, which will cause either a segfault or out-of-memory error. https://github.com/laravel/framework/issues/23415
