### ISSUE TITLE
[Proposal] Do not send Secure cookies over unsecure connections

### ISSUE THREAD

**Issue by barryvdh** [laravel/ideas#885]
Currently, cookies with the Secure flag are still sent on HTTP connections. These cookies will be ignored by browsers (see https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#Secure_and_HttpOnly_cookies ), but are still sent over unsecure connections.  For example, if a middleware is used to redirect to the HTTPS version upon first request, it would still send the cookies on the first request over HTTP, where they could be sniffed by a MitM attack.

According to http://php.net/manual/en/function.setcookie.php the programmer should make sure the cookies are only sent on HTTPS connections:

> **secure**
> Indicates that the cookie should only be transmitted over a secure HTTPS connection from the client. When set to TRUE, the cookie will only be set if a secure connection exists. On the server-side, it's on the programmer to send this kind of cookie only on secure connection (e.g. with respect to $_SERVER["HTTPS"]).

While you could say it's up to the developer to make sure that no cookies are sent on HTTP, or the application isn't even reached on HTTP, we could make sure that in Laravel, secure cookies are only sent on secure connections.  I understand it can be circumvented by not hitting Laravel on HTTP at all, but could be an extra step preventing this.

**Comment by impvhc** [comment]
Hi, I'm dealing with this in my project right now
We are using a McAfee tool to perform an analysis of our site, and even if the "secure" tag is activated (session.php, Laravel 5.1), we are receiving the following error:
_Cookie with a "secure" attribute was initially set by an insecure connection; i.e. HTTP vs HTTPS._

Any idea of how can I solve this?
Thank you in advance!

**Comment by barryvdh** [comment]
Yeah make nginx/apache redirect to https directly.

**Comment by impvhc** [comment]
Hi, thanks for your comment
Currently, I have my HTTPS redirection at Laravel level with a Middleware:
```
if (env('APP_ENV') == "production" && $request->header("x-forwarded-proto") <> "https") {
            return redirect()->secure($request->path());
        }
```
but this is not working for me
So, if I put the redirect at the Apache level (htaccess), will it correct my problem? Or do you think I will have the same result? and maybe something else is the problem.
```
    RewriteCond %{HTTP:X-Forwarded-Proto} !https
    RewriteRule ^ https://llr2.com%{REQUEST_URI} [L,R=301,NE]
```
We are using an ELB, I do not know if this could affect.
Thanks for your help.

**Comment by taylorotwell** [comment]
I'm open to PRs here.
