### ISSUE TITLE
[Proposal] Wrap default validation rules into Rule objects.

### ISSUE THREAD

**Issue by montyclt** [laravel/ideas#886]
In Laravel 5.5, we can use Rule objects to create custom rules, that have some advantages over the classical `Validator::extends()`.

But, to perform the validation I have the next code:

```
request()->validate([
    'document' => [
        'required|unique:people|max:11|bail',
        new DocumentFormat,
    ]
]);
```
I think wrapping default rules into object makes the validation code more "homogeneous":
```
request()->validate([
    'document' => [
        new Required,
        new Unique(Person::class), //Model class, encapsulate table and connection.
        new Max(11),
        new Bail,
        new DocumentFormat,
    ]
]);
```

Of course, I do not propose breaking the classic string with the rules that should continue working, I simply propose create classes that wrap the default validation rules, that can be optionally used instead of the rules string.

**Comment by Dylan-DPC** [comment]
What's the gain of this?

**Comment by montyclt** [comment]
@Dylan-DPC Coherence in the code, passing only an array of Rule, instead of array of string (index 0) and rule in the others indexes.

In the database rules, it also allow use model classes, to encapsulate the table and connection.

**Comment by taylorotwell** [comment]
Unlikely to take this on probably.
