### ISSUE TITLE
Implement has method on Illuminate\Contracts\Cache\Store

### ISSUE THREAD

**Issue by gmsantos** [laravel/ideas#887]
We are doing a stress test on our application and found something interesting on Redis logs. We verified a large number of duplicated Redis GET operations on the same key. 

Digging deeper there is a `has` method on https://github.com/laravel/framework/blob/5.5/src/Illuminate/Cache/Repository.php#L68 that "fallback" to `get`.

The thing is that it's an onerous request for large keys on Redis. Consider this kind of implementation

```
if (Cache::has('some-key')) {
    return Cache::get('some-key');
}
```

Using Redis cache, it will result on two `GET` operation on Redis server, that could be changed to a [`EXISTS`](https://redis.io/commands/exists) on `has` method.

**Proposal**: Any chance to implement a real `has` method on all `Illuminate\Contracts\Cache\Store` implementations so that will save roughly 50% of Redis cache operations? 

Are there any reason to keep using `get` on `Illuminate/Cache/Repository::has()`?

**Comment by gmsantos** [comment]
For now we solved the issue removing all occurrences of `Cache::has` on our codebase and calling only `Cache::get` directly, but a fix on Laravel core will avoid this problem for everyone.

**Comment by gmsantos** [comment]
ping @themsaid

**Comment by gmsantos** [comment]
ping @taylorotwell

**Comment by sisve** [comment]
Wouldn't it be better to always do a `Cache::get` and check if you got a valid result back? I'm thinking about scenarios where `Cache::has` returns true, but the items is expired before `Cache::get` is called.

**Comment by gmsantos** [comment]
Nice catch @sisve, in that case is better not to use `Cache::has` after all. 

My concern is with how to avoid `Cache::has` misusing. Will a documentation amend be enough?

**Comment by taylorotwell** [comment]
Yeah I would probably just always use `get`. I don't think I've ever used `Cache::has` TBH.
