### ISSUE TITLE
[Proposal] Optional Event Tracking 

### ISSUE THREAD

**Issue by ibourgeois** [laravel/ideas#893]
I am prepared to create a PR if it's okay, but what about an event tracking system that is opt in?

If tracking is enabled in the config, then in the Request class (if `$request->user()` is set) and provided the controller is RESTful then using `$request->route()->action['controller']` we can generate event actions like "`$user viewed $item`" if index() is fired or "`$user edited $item`" when update() is fired. In the case of non-RESTful methods or need for customer action message then call the method directly and pass in the message `$request->track("Custom action method here...")` before redirecting/returning.

My thoughts would be no UI. just a migration for tracking...
```php
Schema::create('tracking', function (Blueprint $table) {
        $table->increments('id');
        $table->integer('user_id')->unsigned();
        $table->string('action');
        $table->timestamps();

        $table->foreign('user_id')
                ->references('id')
                ->on('users')
                ->onDelete('cascade');
});
```

This could be implemented several ways, from middleware to adding a `track()` method to Route to enable tracking for certain methods: `Route::resource('/', 'SomeController')->track(['index', 'edit']);`, a config file that lists controllers to be tracked explicitly, and of course requiring the track() method to be called in the controller method or constructor to enable tracking.

I was planning on creating this as a package, but curious if a PR would be an option first?

**Comment by drbyte** [comment]
This package might already cover that and more: https://docs.spatie.be/laravel-activitylog/v2/advanced-usage/logging-model-events

**Comment by taylorotwell** [comment]
Would rather see this as a package.
