### ISSUE TITLE
[Proposal] storage:link should create a relative symlink, not absolute

### ISSUE THREAD

**Issue by Jakobud** [laravel/ideas#899]
Currently, `artisan storage:link` creates an absolute path symlink in the public directory. It seems like it would be way better to create a relative url symlink. For example to `../storage/app/public`.

The most obvious reason for this is that in a given project, an absolute symlink makes the project non-portable. You can't move the project to a different directory or deploy the project onto a server with a different directory structure, etc. If you do, that symlink is always going to be broken.

If you had a relative path symlink, then I would think this would fix the problem. But I also know that different systems handle symlink creation differently so I don't even know if you can commit something like this to a repo. But at least being able to move the project to a different folder on a system, you can know that this symlink won't break.

This is actually how I ran across this problem. I created a Laravel install in a temporary folder, installed some dependencies (which created the storage symlink) and then I moved the project to a different folder and got some symlink storage errors, which lead me to figure it out and now I'm here.

I don't think you should require people to run artisan storage:link if they don't have to. Seems like relative symlinks are a simple solution.

Anyways, any thoughts on this?

**Comment by byustephen** [comment]
Me too. We just ran into this issue and don't know a way around it. We want to have photos be accessible in a public directory, but then we'd have to worry about the symlink for each developer AND for the staging server. 
Thoughts anyone?

**Comment by Jakobud** [comment]
@byustephen At this point, running `artisan storage:link` needs to just be part of the deployment process. That is the only workaround. Shouldn't really be necessary though. I mean, the whole purpose of a relative symlink is that it makes something portable.

**Comment by sisve** [comment]
Just to understand the use-case here; are you committing the symlinks to your git repository?

**Comment by byustephen** [comment]
That's the question. Should we be gitignoring the symlink? I don't know what the best practice is here. So, at first we had the symlink in the git repo, but that won't work when we have multiple machines involved. 

So, should I just consider this task as part of the configuration and deployment process? I think the steps would be:

1. Add a gitignore record so we don't track the symlink. 
2. have each developer run the symlink command. 
3. Also run that command on the deploy process (we use rocketeer). 

Is there anything else I should know about?

and @Jakobud how do I create a relative symlink? When I run the `artisan storage:link` command it creates absolute links. Any help would be appreciated.

**Comment by Jakobud** [comment]
In my use case I wasn't committing the symlink but I suppose that would be another case for it. In my situation I was simply wanting to move my laravel installation from directory to another. Doing this broke it since the symlink was absolute.

**Comment by PetraBester** [comment]
Has anyone figured this out yet?

**Comment by byustephen** [comment]
Here's a link to what we settled on:

https://laracasts.com/discuss/channels/laravel/public-symlink-with-mac-and-windows-developers-with-an-ubuntu-production-machine

In short, we added a route like this:

`Route::get('file/{filename}', 'FileController@getFile')->where('filename', '^(.+)\/([^\/]+)$')->name('files');`

and built a function like this:

`public function getFile($filename) { return response()->download(storage_path($filename), null, [], null); }`

We thought it was a good compromise between security and usability. So best of luck @PetraBester!

**Comment by taylorotwell** [comment]
I'm fine with it as long as it's not a breaking change.

**Comment by rayronvictor** [comment]
An important use-case is running a Docker for development. Inside the docker container the symlink point to a different location.

**Comment by byustephen** [comment]
Not everyone wants to use Docker for development. The ideal method for
using multiple developers is to exclude the public storage from the git
repo, and just set the symlink with each deploy.

For me, I'd lean towards using Homestead before I'd set up everything in
Docker.

**Comment by biztems** [comment]
This is breaking our Jenkins pipeline - we expected the symlinks to be relative, instead they're absolute and as such they're created with the Jenkins' workspace absolute path, which won't work after the artifact is deployed on the remote server.

Is there any reason for them to be absolute instead of relative?

If there is, you could give the option to create symlinks via an additional artisan command? (like `artisan storage:relativelink` or something)

Thanks!

**Comment by Jakobud** [comment]
@biztems The command is: `artisan storage:link` in order to recreate the link

**Comment by biztems** [comment]
> @biztems The command is: `artisan storage:link` in order to recreate the link

Err, yeah, I know that much - I was asking something else entirely. Thanks for trying to help, though.

**Comment by sisve** [comment]
The primary reason for the links to be absolute is because those that want a relative one hasn't sent a PR yet. ;)

The relevant code is probably in the [StorageLinkCommand](https://github.com/laravel/framework/blob/e3593ad182bae93bbb939890f48fd36aa1ef81b1/src/Illuminate/Foundation/Console/StorageLinkCommand.php#L34-L36). Keep in mind that both storage_path and public_path are user-changeable, so you would probably still need both those calls to get two absolute paths, then resolve a relative path from public to storage.
