### ISSUE TITLE
[Proposal] More advanced "sometimes" validation

### ISSUE THREAD

**Issue by CupOfTea696** [laravel/ideas#902]
### The Problem

I've been recently trying to figure out a way to validate distinct values in an array, but on the condition that the index is present in another array. I'll illustrate with an example, that'll make it clearer.

```php
// $input = request()->input();
$input = [
   'map' => [
      'from' => [0 => 'project', 1 => 'projectId'],
      'to' => [
         0 => '{"index":1,"title":"Project"}',
         1 => '{"index":0,"title":"Project ID"}',
         3 => '{"index":1,"title":"Project"}'],
         4 => '{"index":4,"title":"User"}',
   ],
];

$rules = [
    'map.from' => 'required|array',
    'map.to' => 'required|array',
    'map.to.*' => 'required_with:connection.map.from.*|distinct',
];

$validData = $request->validate($rules);
```

The above will result in a validation error, because `map.to.3` is validated with the `distinct` rule. However, I want this to pass as long as `map.from.3` isn't present. I don't think this is currently possible. Even if I were to use `Validator::sometimes()` I don't have access to the current input value that's being processed. 

### My Proposal

I think it might be nice to have something like a `sometimes_with` rule, in the same vain as the `required_with` rule. This way, I could use the following rule for `map.to.*` instead: `sometimes_with:connection.map.from.*|required|distinct`.

Additionally, I think it might be useful to pass the attribute (and value) being validated along with the input to the `Validator::sometimes()` callback function.

```php
$v = Validator::make($input, $rules);
$v->sometimes('map.to.*', 'required|distinct', function ($input, $attribute, $value = null) {
   return array_has($input, str_replace('.from', '.to', $attribute));
});
```

**Comment by brunogaspar** [comment]
I got bitten by this issue in the past, had to do things in a more hacky way 😁  so yeah, i would like to see this to be improved for nested arrays.

**Comment by taylorotwell** [comment]
Honestly rather than just trying to code up all these special cases in the `sometimes` method, I've found it's easier to just do $validator->after(fn) and do your own logic inside the callback. It just ends up being clearer code IMO.
