### ISSUE TITLE
JSON responses don't execute model's getters when attributes are named according to the camelcase convention

### ISSUE THREAD

**Issue by CODEheures** [laravel/ideas#905]
for getter function in model like
In model:
```
public function getMyValueAttribute() { 
    return "getter value" ; 
}
```

In Controller
```
$foo = MyModel::first();
return response()->json($foo);
```

if attribute is naming "my_value" in database (snake_case) response is ok:
`{"id":1, .... , "my_value": "getter value"}`

if attribute is naming "myValue" in database (camelCase) response is NOT ok:
`{"id":1, .... , "myValue": "ORIGINAL value"}`

The json response depend of name attribute convention (only for complete model attributes list response).

**Comment by taylorotwell** [comment]
It just follows what your database uses.

**Comment by CODEheures** [comment]
? Database return always the same value whether it is snake_case or camelCase
When my attribute is snake_case the getter returns the computed value whereas if the attribute is camelCase the getter is not called
