### ISSUE TITLE
[Proposal] add $route->rawParameters function 

### ISSUE THREAD

**Issue by green-mike** [laravel/ideas#906]
'route model binding' let $request->route('param') return string or object. But it depend on that the model is resolved or not. It may cause some problem because high coupling. 

For Example, the formRequest can't fetch origin route param by "$request->route('param')". It means the formRequest is hard to reuse. 

Middleware has same situation, So need to very careful the controller is resolving model or not.

@sisve notice that I can use explicit model binding. It is good to solve many situation. But I think it is lower coupling if there is a function to get raw path parameters.

Thanks for reading.

**Comment by Dylan-DPC** [comment]
Can you provide an example?

**Comment by green-mike** [comment]
sure!

--- 

laravel new Project

then paste at 'router/web.php' 
```php

Route::get('/users/{user}', function (Illuminate\Http\Request $request, App\User $user) {
    return $request->route('user');
});
Route::get('/second-example/{user}', function (Illuminate\Http\Request $request) {
    return $request->route('user');
});
```
first path display eloquent and second path display string.
the example look like just show the feature, but it only because in the same file. Developer can easily notice that model is resolved or not. 

---
if there is a middleware of log path parameter

route/web.php
```php
Route::group(['middleware' => 'log_user_id', ], function () {
    Route::get('/users/{user}', function (Illuminate\Http\Request $request, App\User $user) {
        return $request->route('user');
    });
    Route::get('/second-example/{user}', function (Illuminate\Http\Request $request) {
        return $request->route('user');
    });
});
```

LogUserIdMiddle.php
```php
class LogUserIdMiddle
{
    public function handle($request, Closure $next)
    {
        Log::debug($request->route('user'));  // can't work without check type
        return $next($request);
    }
}

```

--- 
In other case
a formRequest for validate parameter of user:

```php 
public function rules()
{
    return [
        'unique_column' => [
            // need to know the controller code. if not resolved, it can't work.
            Rule::unique('users')->ignore($this->route('user')->id),  
        ],
    ];
}
```

In some case, the form request may reuse by multiple controller then it can't work without 'if else'.

thank you.

**Comment by taylorotwell** [comment]
Feel free to send a PR.

**Comment by huntie** [comment]
A particular use case for this I'm coming across is to pass through the same set of existing raw parameters to a named route under the same group.

e.g. In example template for route `'user.project.asset.index'`, I need to supply three route parameters were resolved from slugs into the adjacent route `'user.project.asset.edit'`:

```blade
<a href="{{ route('user.project.asset.edit', Request::route()->rawParameters()) }}">...</a>
```

Unless there is another way of doing this, this is far cleaner than recreating the three slug values.

May look at taking on the PR for this, but would happen in a week or so after my need for it.
