### ISSUE TITLE
tinker error text should be white not grey

### ISSUE THREAD

**Issue by ChangePlaces** [laravel/ideas#919]
white on dark red is really difficult to see, can it be something more visible like black?

**Comment by martinbean** [comment]
White on red is _far_ more legible than black. It’s also worth bearing in mind people with colour blindness that see red as grey: what your proposing would result in those people having to try and decipher black on grey, which doesn’t have as much contrast as white would.

**Comment by ChangePlaces** [comment]
Actually, I just double-checked this, the text colour is a dark-grey. As for the point @martinbean  raises, there needs to be more of a contrast between the dark red, and the dark grey. Maybe it *should* be white!

**Comment by 1Rhino** [comment]
It was really really difficult to read. I need to double-click to see it :(
<img width="413" alt="screen shot 2017-12-29 at 14 48 54" src="https://user-images.githubusercontent.com/3173969/34432152-7501d068-eca7-11e7-9d65-2de554a7f8f2.png">

**Comment by 626Pilot** [comment]
I've had this problem as well. It's almost impossible to read without highlighting the output. There are some posts online about how to fix this globally. None of them actually works. It would be great if something could be done about this. Failing that, a workaround would be nice.

**Comment by taylorotwell** [comment]
I don't think I have any control over that? That is a package.

**Comment by maxrinal** [comment]
To fix that trouble you have to change a line in a file from a vendor in your local repository

./vendor/psy/psysh/src/Output/ShellOutput.php

178://$formatter->setStyle('error',   new OutputFormatterStyle('black', 'red', ['bold']));
178:$formatter->setStyle('error',   new OutputFormatterStyle('black', 'white', ['bold']));
