### ISSUE TITLE
Request validate response in json format.

### ISSUE THREAD

**Issue by ThunderBirdsX3** [laravel/ideas#925]
It will be good. If can use `$request->validate([...]);` and response in JSON type, When it was failed.

May be.
```
$request->validate([
  'something' => 'required'
])->toJson();
```

**Comment by sisve** [comment]
Isn't this already built into Laravel? `$request->validate(...)` throws a ValidationException that your ExceptionHandler renders as a json response if you've sent the approperiate http headers (`Accept: application/json`).

**Comment by ThunderBirdsX3** [comment]
Hmmm. I didn't know. 

But, When I `POST` with header  `Content-Type: application/json`, In validation fail case. It was returned index page.

**Comment by sisve** [comment]
`Content-Type: application/json` says that you're posting json to the server. You _also_ need to send the `Accept: application/json` to say that you accept a json response.
