### ISSUE TITLE
[proposal] Expected data type should be in accept headers

### ISSUE THREAD

**Issue by pavinthan** [laravel/ideas#933]
if someones need the JSON response, they should have Accept header, so you don't need to use `($this->ajax() && ! $this->pjax()) || $this->wantsJson();` checks because some ajax requests may request HTML or XML responses
https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.1

@taylorotwell please review this issue

**Comment by sisve** [comment]
The naming of this issue is really vague. "Regarding response handle changes". What response handle? You want to change a response handle?

Why is this even an issue in this repository? There is already an open PR for it since three days back, and we're now discussing details about the fix.

**Comment by pavinthan** [comment]
@sisve it's not related to adding another check for response the expect type, need to remove other checks
