### ISSUE TITLE
Cache tags double cache hits

### ISSUE THREAD

**Issue by ghunti** [laravel/ideas#958]
With current implementation of Cache tags, the framework is hitting the cache twice for every key that we want to retrieve.
```
Cache::tags(['image'])->get('default.png');
Cache::tags(['image'])->get('another.png');
```
This code will perform 4 memcache ```get``` calls:
- Two calls will be placed for getting the key that was once generated for the ```image``` tag
- One call to retrieve the default.png
- One call to retrieve the another.png

Solutions:
1 - "Cache" the tag key in a static property  so we only retrieve it once per request
2 - Generate an md5 of the tag instead of a random ```uniquid``` so we don't need to store/retrieve from the memcache. This would invalidate the ```flush()``` method, but would reduce the amount of calls placed to memcached

**Comment by taylorotwell** [comment]
Open to PRs in this area.

**Comment by ghunti** [comment]
@taylorotwell any particular way you would prefer this to be improved?
