### ISSUE TITLE
[Proposal] Non-database models

### ISSUE THREAD

**Issue by mtinsley** [laravel/ideas#965]
A few times I have run into situations where I would like to create a model for something other than a database record. For example an API response or data stored as json in a field in the database.  In particular I would like to create a class that has attributes, casts, accessors, and mutators.

I could just extend the Eloquent Model to accomplish this, but it feels incorrect to have a class that has methods like `save()` that will just throw an exception if called. Just using the HasAttributes trait won't work either as it is tightly coupled with the eloquent model.

I would like to submit a PR for breaking the non-database functionality out of the eloquent model into a base model in `Illuminate\Support\Model`. The eloquent model would then extend this class, similar to how the eloquent collection extends the support collection.

Is this something other people would find useful?

**Comment by sisve** [comment]
Could you explain why you would want the attributes, casts at all? If it were a non-Eloquent backed model, then you could just use the correct data types to begin with. And the getters and setters (accessors and mutators) would enforce those data types.

**Comment by mtinsley** [comment]
@sisve To clarify, I don't want to use accessors and mutators for every field, just those that need to be transformed.

The only difference between what I am proposing and an eloquent model is the source of the data. If I am creating a class to represent the response from an API I don't want to write getters and setters for every field for the same reason I don't want to do it for an eloquent model: It is repetitive, undifferentiated code.

**Comment by RemiCollin** [comment]
I like this idea. Thought it would be as simple as using the `HasAttributes' trait, but you're right it's tightly coupled to Eloquent (reference to $this->relations mostly..).. Maybe it's just a matter of fixing this trait in a more SRP fashion so we can use it in any class ?

**Comment by mtinsley** [comment]
@RemiCollin That was my original intention; pulling that thread is how I got here 😃 

I think the underlying issue is those traits do not stand on their own, they belong to the model and they belong to one another. The traits are being used to group related code rather than to create reusable behavior. While that may not be "by the book", I'm not sure it is something that must be changed.

If the objective is for the framework to expose the "attributes" behavior for extension, making the HasAttributes trait reusable is going to require more refactoring than having the database model be a subtype of a more general model, in my opinion.

**Comment by mtinsley** [comment]
Pull request has been created:

https://github.com/laravel/framework/pull/22946

**Comment by mtinsley** [comment]
The pull request was rejected, but I still think it would be great if the framework could address these use cases. Is there a better way to go about this?
