### ISSUE TITLE
[Proposal] Add model casts support to API Resources

### ISSUE THREAD

**Issue by uonick** [laravel/ideas#967]
[API Resources](https://laravel.com/docs/master/eloquent-resources) not support model type casts. If in model casts exists: 

```php
protected $casts = [
        'is_group' => 'boolean',
        'is_published' => 'boolean',
        'is_accept' => 'boolean',
    ];

```

API Resource json is:
```json
{
   "is_group" : 0,
   "is_published" : 1,
   "is_accept" : 0,
}

```

**Comment by chimit** [comment]
+1. It's unexpected behavior.

**Comment by taylorotwell** [comment]
You should cast your data in the resource's translation layer when you decide what attributes to include.
