### ISSUE TITLE
hope remove the middleware in sub-router

### ISSUE THREAD

**Issue by Except10n** [laravel/ideas#968]
such as this:

```
$router->group(['middleware' => 'outter'], function($router) {
   $router->get('xxxx', ['middleware' => null or otherwise]
})

```

Is there any way to exclude parent - level middleware from the sub-router?

**Comment by jrbarnard** [comment]
@Except10n You can do something with controller middleware if they share a Controller:
https://laravel.com/docs/5.5/controllers#controller-middleware

E.g your controller has:
`
$this->middleware('some-middleware')->except('a-specific-method');
`

I don't think you can do this from the router currently, potentially would be nice to see a fluent method such as?
`
$router->group(['middleware' => 'outter'], function($router) {
   $router->get('/', 'Controller@example')->exceptMiddleware('outter');
})
`

**Comment by Except10n** [comment]
hi @jrbarnard 
Yes, I can use middleware and exceptmiddleware in the controller.
But I think it's reasonable to have a unified configuration of middleware, so I try to set it up in the routing table as much as possible.

It's not just the middleware, but there are other routing properties, and it's also very simple and practical to add an exclusion method

In my opinion, it is better to add a method to exclude group attributes in "sub-router", which is just a suggestion, and I hope to be considered.

**Comment by taylorotwell** [comment]
No plans to add right now. More of a support request regardless.
