### ISSUE TITLE
Add a default editorconfig?

### ISSUE THREAD

**Issue by royduin** [laravel/ideas#973]
See: https://github.com/laravel/laravel/pull/4561 and @taylorotwell his comment here: https://github.com/laravel/laravel/pull/3693#issuecomment-198332035: 

> The laravel/laravel repo is more where companies should add their own editorconfig IMO.

Why not just add a default? I'm getting bored of adding one for every new Laravel project. If anyone want to use something else they can change it right... maybe a vote?

**Comment by michaeldyrynda** [comment]
You can always create your [own](https://github.com/spatie/blender) [base](https://github.com/michaeldyrynda/founder) [repo](https://github.com/cmgmyr/laravel-starter) for your specific app configurations, it will let you really hone in on what each of _your_ apps need.

**Comment by taylorotwell** [comment]
I think this already exists in the Laravel framework? I'm not totally opposed to including one in laravel/laravel that matches. :shrug:
