### ISSUE TITLE
[Proposal] Shared storage for chained jobs

### ISSUE THREAD

**Issue by FrostBy** [laravel/ideas#974]
Hi there!
Has Laravel any features for passing/saving/changing states of variables between chained jobs? Or just make something like shared isolated storage for a specific chain.
For example:
```
App\Jobs\Test::withChain([
       new \App\Jobs\Test1($user),
       new \App\Jobs\Test2($user),
    ])->dispatch($user);
```
or
```
App\Jobs\Test::withChain([
       new \App\Jobs\Test1(),
       new \App\Jobs\Test2(),
    ], ['shared' => $user])->dispatch();
```
In this example I want to use $user as a shared object, change it's properties in Test job, depending on changes in the previous step make more changes in Test1 job and finish everything in Test2 job

**Comment by sisve** [comment]
This would be awesome. Imagine being able to pass a UploadedFile to a processing job without having to persist it somewhere first.

**Comment by taylorotwell** [comment]
It's hard to say what this would actually mean. Does it serialize the object in between jobs? If so, not all objects are serializable? ... It's an interesting idea but one I fear would be a maintenance burden and bug-laden.
