### ISSUE TITLE
\Illuminate\Support\Fluent concerns

### ISSUE THREAD

**Issue by aleksandrlat** [laravel/ideas#975]
I don't really like usage of `\Illuminate\Support\Fluent` because it is not very clear what are possible values in each case. 
For example when we use `Illuminate\Database\Schema\Blueprint` in migrations to create columns `Fluent` is used as container for column attributes. But there are strict list of possible column attributes. 
It would be nice to use dedicated class for column instead of `Fluent` so we could perform static analyze on code. 
Also we could use IDE autocompletion for possible column attributes instead of referring to documentation. This would save use time.

**Comment by mfn** [comment]
Agreed.

`Fluent` and IDEs are somehow on the opposite of the spectrum.

**Comment by arjasco** [comment]
This is a magic method issue right? 

Wondering if there is any extra phpdoc that can be added to help IDE's...?

**Comment by taylorotwell** [comment]
I still find it a pretty simple solution that leverages the power of the dynamic nature of PHP.
