### ISSUE TITLE
[Proposal] [5.6] Rename stack log driver to prevent confusion with slack log driver

### ISSUE THREAD

**Issue by SjorsO** [laravel/ideas#979]
Laravel 5.6 introduces a [reworked logging system](https://github.com/laravel/framework/pull/22635). It looks great, it is definitely an improvement over the old system. The only problem i have with it is that the new `stack` driver is named very similarly to the new `slack` driver. I've already confused the two multiple times while reading trough the [documentation](https://laravel.com/docs/5.6/logging) and the [logging config file](https://github.com/laravel/laravel/blob/develop/config/logging.php).

I know its a minor problem, but i feel like its worth considering a name change before 5.6 releases.

**Comment by taylorotwell** [comment]
They are different words.
