### ISSUE TITLE
Dynamic creation of Local Scopes for Models

### ISSUE THREAD

**Issue by mbitokhov** [laravel/ideas#982]
I thought I'd get opinions before I make a pull request

I've found myself having to rewrite a query whenever I want to add new functionality. And for complicated queries it takes a small amount of time to figure out. For databases that are small or well thought out, this isn't that much of an issue as we can assume the developers know what they're doing, but for large projects, there's a good chance that every single developer on the team won't know every single table and every single relationship.

So I realized it might be easier to have a localScope that just take in a $type, and join the two tables. So all I'd have to do is

```php
User::joinComments('left');
```

But after adding in all of the scopes required, I realized it looks like a bit of a mess. The solution I figured out includes checking the existence of a key inside the model, and using that as parameters. And all the developer has to do is describe the relationship inside the `User` model

```php
class User
{
    protected $joins = [
       'joinComments' => ['comments','comments.user_id', '=', 'users.id']
    ]
}
```

This way, in order to add in a "local scope", you just need one line of code and the framework takes care of it. There could technically be a way to use the existing relationships, but I think that would lead to unintended bugs. My solution is explained in this gist

https://gist.github.com/mbitokhov/20921d506fd46417277e51f0e0b3381c

(PS: sorry for accidentally making a blank issue. Pinkie slipped when pressing enter, and accidentally pressed shift as well)

**Comment by sisve** [comment]
Scopes are meant to be for constraints. I'm not seeing how it's relevant to implement this in some way with scopes.

You could just create a static method that accepts a query builder and adds the joins to it.

    $query = User::newQuery();
    User::addTheJoin($query);
    $result = $query->get();

    class User {
        static function addTheJoin($query) {
            $query->join(...)->on(...);
        }
    }

The scenario you describe, complicated queries and lots of developers, is usually solved by repositories where queries are written once and people can call when needed. That way you have only one place, the UserRepository, to find all queries done that fetches users and thus only one file to verify the joins in.

**Comment by mbitokhov** [comment]
@sisve 

> Scopes are meant to be for constraints. I'm not seeing how it's relevant to implement this in some way with scopes.

Scopes is a bad example. What I would like to replicate is similar to a scope, but is dynamically created. To make it more clear, the type of behavior I'd like to replicate is the following. Let's say we have the tables called `customers`, `orders`, `order_items`. And let's also say that we want to create a summary of all of the customers and the total amount each customer bought from us

The behavior that I would like to use is like such

```php
$customers = Customer::select(
                         'customers.*',
                         DB::raw('sum(order_items.total)')
                     )
                     ->joinOrders()
                     ->joinOrderItems()
                     ->groupBy('customers.id')
                     ->get();
```
Which will build
```php
$customers = Customer::select(
                         'customers.*',
                         DB::raw('sum(order_items.total)')
                     )
                     ->join('orders','customers.id','=','orders.customer_id')
                     ->join('order_items','orders.id','=','order_items.order_id')
                     ->groupBy('customers.id')
                     ->get();
```

But in order to accomplish the same thing, I would have to create a separate function for every single table I want to relate to `Customer` to. Then I have to do the same thing for `Order` and `OrderItem`. This is fine for small databases. But after a while it becomes tedious and more difficult to maintain

My solution involves making an array of the relationships. So instead of making 4 lines for every single scope, it is shortened to one line per relationship

> The scenario you describe, complicated queries and lots of developers, is usually solved by repositories where queries are written once and people can call when needed

This sounds interesting. I'd have to look it up. It sounds useful, but it looks like it falls into the issue of writing too much to describe one relationship

**Comment by mfn** [comment]
There was a similar idea to infer the inner joins for simple cases, see https://github.com/laravel/internals/issues/931 .

A working PR was made but not accepted.

**Comment by mbitokhov** [comment]
@mfn 

I see the similarities. But the way my implementation found [in my gist](https://gist.github.com/mbitokhov/20921d506fd46417277e51f0e0b3381c) works, is that it still keeps the power of the join to the developer, because the developer still needs to write out the relationships. This way if there is a case to use operators other than `=`, the developer has the choice to do so

And yours has the issue of joining tables that belong to a different table

```php
DB::table('comments')->join('users');
```

This would assume it's going from comments.id to users.comment_id. My implementation allows for the reverse.

```php
class Comment extends Model
{
    $joins = [
        'joinUsers' => ['users', 'comments.user_id', '=', 'users.id']
    ];
}

Comment::joinUsers();
```

**Comment by taylorotwell** [comment]
No plans on adding right now.
