### ISSUE TITLE
laravel 5.6 should be LTS not 5.5.

### ISSUE THREAD

**Issue by AGhasemzadeh** [laravel/ideas#983]
In laravel 5.6 we have some changes which is important:
1-Bootstrap v4
2-New hashing
3-php version 7.2
4-new blade directive.

I think v5.6 can be LTS.

**Comment by marcelogarbin** [comment]
Hi, I have a doubt.

Use or not LTS version? (Taking into consideration that the always updates and new features...)

I'm starting a project, which in a way will be a large project. I was in this doubt of using LTS version of Laravel.

**Comment by AGhasemzadeh** [comment]
@marcelogarbin 
I start new projects with 5.6 I hope I could upgrade them to next version.

@taylorotwell 
Can you help us about this topic?(Use LTS or Current?)

**Comment by drbyte** [comment]
LTS doesn't mean "always the latest and greatest". It means "long term support", and what qualifies as LTS was originally driven by underlying Symfony component LTS terms. 
If you want "latest and greatest", then use the most recent release. And upgrade when new releases are published.  https://laravelshift.com/ makes upgrading as painless as possible.

Here is a great summary of which Laravel versions to use, based on support terms, maintained by @jamesking56:
https://whichlaravel.me

In my opinion, if you're undecided whether to use LTS, then you do NOT need to worry about LTS.

https://laravel-news.com/laravel-5-5-lts
https://medium.com/@jasonmccreary/laravel-lts-is-a-trap-97b1d1103961
https://laracasts.com/discuss/channels/laravel/what-version-of-laravel-do-you-recommend-i-use-51-or-52
