### ISSUE TITLE
[Proposal]Add the ability to work with COMPOSER_VENDOR_DIR

### ISSUE THREAD

**Issue by Vendin** [laravel/ideas#985]
`The vendor directory contains your Composer dependencies.`

Composer can install the dependencies into a directory other than vendor, but it's not used.

https://getcomposer.org/doc/03-cli.md#composer-vendor-dir

**Comment by drbyte** [comment]
Correct. Laravel currently requires `vendor` to be the directory name:

https://github.com/laravel/laravel/blob/master/artisan#L18
https://github.com/laravel/laravel/blob/master/public/index.php#L24

**Comment by Vendin** [comment]
same in `PackageManifest` and `tinker`
https://github.com/laravel/framework/blob/6a5eb9023b1353abdb36d52d5e6ae3290f477af1/src/Illuminate/Foundation/PackageManifest.php#L58
https://github.com/laravel/tinker/blob/master/src/Console/TinkerCommand.php#L57
