### ISSUE TITLE
[Proposal] Support for URL types in FilesystemAdapter when accessing Rackspace Cloud Files

### ISSUE THREAD

**Issue by stevie-mccomb** [laravel/ideas#989]
When using the FilesystemAdapter through the `Storage` facade, the call to `getPublicUrl()` could accept a URL type from Rackspace's OpenCloud constants but it's currently hard-coded not to pass any arguments through. Here's an excerpt from `\Illuminate\Filesystem\FilesystemAdapter` class showing the call being made on line 245:

    return (string) $adapter->getContainer()->getObject($path)->getPublicUrl();

If we instead passed in one of the constants (or even the string equivalent from our .env/config files) when making the call, we could control whether or not the CDN url returned was HTTP/HTTPS/Streaming/etc. like so:
    
    return (string) $adapter->getContainer()->getObject($path)->getPublicUrl($config['url_type'] ?? null);

I've tested this by hard-coding 'SSL' into the call and it seems to work as expected, returning the HTTPS version of the URL instead of the HTTP version.

The strange thing is that Laravel's example configuration for Rackspace shows an option called `url_type` but it only seems to be used in `\Illuminate\Filesystem\FilesystemManager` when retrieving a Rackspace Cloud Files container, not when retrieving the actual objects from that container:

    'rackspace' => [
        'driver'    => 'rackspace',
        'username'  => 'your-username',
        'key'       => 'your-key',
        'container' => 'your-container',
        'endpoint'  => 'https://identity.api.rackspacecloud.com/v2.0/',
        'region'    => 'IAD',
        'url_type'  => 'publicURL', // <-- This guy right here
    ],

Digging through the Rackspace OpenCloud docs, I've found that there are two url types accepted for a container and they are 'publicURL' and 'internalURL'. Furthermore, setting this value to anything other than 'publicURL' ('internalURL' or otherwise) causes the requests to get object URLs to fail. This seems to be different from the URL types accepted for individual resources within the containers, which are defined in `\OpenCloud\ObjectStore\Constants` as:

    const CDN = 'CDN';
    const SSL = 'SSL';
    const STREAMING = 'Streaming';
    const IOS_STREAMING = 'IOS-Streaming';

    const TAR = 'tar';
    const TAR_GZ = 'tar.gz';
    const TAR_BZ2 = 'tar.bz2';

If these two 'url types' really are different things altogether, then maybe it's best to add a new config option for Rackspace to specify this type of url. Maybe something like `object_url_type` and then having the adapter check for its existence before attempting to use it:

`Filesystems config file`

    'rackspace' => [
        'driver'    => 'rackspace',
        'username'  => env('RACKSPACE_USERNAME'),
        'key'       => env('RACKSPACE_API_KEY'),
        'container' => env('RACKSPACE_CONTAINER'),
        'endpoint'  => env('RACKSPACE_ENDPOINT', 'https://identity.api.rackspacecloud.com/v2.0/'),
        'region'    => env('RACKSPACE_REGION', 'IAD'),
        'url_type'  => env('RACKSPACE_URL_TYPE', 'publicURL'),
        'object_url_type' => env('RACKSPACE_OBJECT_URL_TYPE', 'CDN'),
    ],

`\Illuminate\Filesystem\FilesystemAdapter`

    /**
     * Get the URL for the file at the given path.
     *
     * @param  \League\Flysystem\Rackspace\RackspaceAdapter $adapter
     * @param  string $path
     * @return string
     */
    protected function getRackspaceUrl($adapter, $path)
    {
        $urlType = config('filesystems.disks.rackspace.object_url_type');

        if (empty($urlType)) {
            return (string) $adapter->getContainer()->getObject($path)->getPublicUrl();
        } else {
            return (string) $adapter->getContainer()->getObject($path)->getPublicUrl($urlType);
        }
    }

There may be a better way to implement this, but so far this is the best I've come up with and it seems to work as intended when retrieving storage objects with and without the the configuration line. Here's the code I'm using to retrieve the SSL object URL through the `Storage` facade inside one of my models:

    return Storage::disk('rackspace')->url($this->uri); // (e.g. $this->uri = 'media/test-image.jpeg')

**Comment by taylorotwell** [comment]
Feel free to PR any improvements.
