### ISSUE TITLE
Redirect with hash

### ISSUE THREAD

**Issue by divdax** [laravel/ideas#991]
Sometimes i want to redirect back or to a route with a hash e.g. `http://excample.com/route#hash`

##### To achieve this you can do:
```
return redirect(route('routename') . '#hash');
```
##### If you want redirect back you have to do:
```
return redirect(url()->previous() . '#hash');
```
In my opinion this looks ugly!

### What about to add a new method to append a hash like so?
```
return redirect()->back()->withHash('hash');
return redirect()->route('routename')->withHash('hash');
```

**Comment by Patryk27** [comment]
Technically this part is called `fragment` (https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax, http://uri.thephpleague.com/4.0/components/overview/), so I'd go with `withFragment(...)` - I like the idea overall though.

Case to consider:
- if `redirect()->back()` already contains a fragment, should `...->withFragment()` overwrite it?

**Comment by sisve** [comment]
I'm assuming that a ->withFragment() would return a new Response object with a different fragment. This exactly matches PSR-7. I guess that the idea about an immutable Response is only important if we're following PSR-7, but no matter what I still expect the method to overwrite the existing fragment.

    /**
     * Return an instance with the specified URI fragment.
     *
     * This method MUST retain the state of the current instance, and return
     * an instance that contains the specified URI fragment.
     *
     * Users can provide both encoded and decoded fragment characters.
     * Implementations ensure the correct encoding as outlined in getFragment().
     *
     * An empty fragment value is equivalent to removing the fragment.
     *
     * @param string $fragment The fragment to use with the new instance.
     * @return static A new instance with the specified fragment.
     */
    public function withFragment($fragment);

Source: https://www.php-fig.org/psr/psr-7/

**Comment by taylorotwell** [comment]
I'm open to something here if someone wants to work on it. Probably subsequent calls to withFragment would overwrite existing fragments.

**Comment by ConsoleTVs** [comment]
Fast forward 3 years and for future reference, we do have this in place at `Illuminate\Http\RedirectResponse` with the exact API proposed here.

```
return redirect()
    ->route('example.route')
    ->withFragment('example-hash')
```
