### ISSUE TITLE
Take xdg-mime into account when validating file type

### ISSUE THREAD

**Issue by Cysioland** [laravel/ideas#993]
In my script I have to deal with some stubborn MP3s. Ones, that to `file` and `finfo` are nothing more than `application/octet-stream`, yet to `xdg-mime` are perfectly valid MP3 files. Maybe the validator should, in case of `application/octet-stream` try falling back to other methods available, and for `xdg-mime` to be able to be used if it's present?

**Comment by taylorotwell** [comment]
You can try implementing a custom validation rule to suit your needs.
