### ISSUE TITLE
[Proposal] Add whereLike, whereBeginsWith and whereEndsWith

### ISSUE THREAD

**Issue by Tucker-Eric** [laravel/ideas#995]
It would be nice to have these methods added to the query builder. I'm currently implementing them in local scopes my package https://github.com/Tucker-Eric/EloquentFilter/blob/master/README.md#additional-filter-methods and they've been working out well.

I can send a PR if this is something that could be added?

Cheers!

**Comment by ntzm** [comment]
Would be nice to implement escaping as discussed here: laravel/framework#22864

**Comment by Tucker-Eric** [comment]
So maybe a `whereLike` that would escape by default and add a `whereLikeRaw` that would not escape?

**Comment by alberto-bottarini** [comment]
I already tried: https://github.com/laravel/framework/pull/22516

**Comment by taylorotwell** [comment]
Eh, generally fine with me I think.
