### ISSUE TITLE
[Proposal] Add first and last pagination links

### ISSUE THREAD

**Issue by sean-ww** [laravel/ideas#998]
The pagination would benefit from a first and last button:
![screen shot 2018-02-13 at 09 35 46](https://user-images.githubusercontent.com/12208691/36140357-50f17002-10a1-11e8-8628-3239e511deb2.png)

[See PR](https://github.com/laravel/framework/pull/23138)

Currently in 5.6.3 it has just previous and next with the wrong symbols ([fixed here](https://github.com/laravel/framework/pull/23127)).

**Comment by HandsomeMatt** [comment]
please.

**Comment by sisve** [comment]
Have you tried sending a PR to the correct repo with a fix?

**Comment by sean-ww** [comment]
Yes, you can see in the PR links. The fix was merged (fixing the wrong symbols). The subsequent pull request to add first and last was closed due to the belief that it was already first and last. I'll try again perhaps...

**Comment by drbyte** [comment]
@sean-ww note: taylor has said that he has github notifications turned off. So the only way he sees anything about a PR that he's closed is if someone in his inner circle notifies him, or if you open a new PR. So, once he's closed something, you've gotta do a new PR or find someone who can get his attention back to it.

**Comment by sean-ww** [comment]
Resubmitted the pull request: https://github.com/laravel/framework/pull/23263

**Comment by sean-ww** [comment]
Closed again: https://github.com/laravel/framework/pull/23263

The reason being that first and last 'numbers' always display. Which to me, isn't intuitive. Let alone to real clients, but I do appreciate now that the functionality is there.
